### ISSUE TITLE
Disable Drag & Resize

### ISSUE THREAD

**Issue by elvir92** [gridstack/gridstack.js#10]
Hello, please could you tell me is it possible to disable drag&resize , and if it is, explain me how? Thank you.
RE: node.el.resizable('enable') & node.el.draggable('disable');

**Comment by Johnathon332** [comment]
I have tried doing this however it still lets me resize and move the widget 
<div class="grid-stack-item ui-draggable ui-resizable-autohide alertWidget" data-gs-x="8" data-gs-y="0" data-gs-width="4" data-gs-height="2" data-gs-no-resize="" data-gs-no-move="" data-gs-locked="">

**Comment by radiolips** [comment]
You may use the `staticGrid` option. Set this to false when initializing the grid and you will be unable to move or resize any widgets.

**Comment by kidmeke** [comment]
Hi, I had the same question as OP - one thing to note in order to get it to work is that you have to set the data attribute to "true", i.e. data-gs-no-resize="true". I was just adding the attribute without a value and it didn't work.

So the resizing is disabled, but when I do this ui-state-disabled gets added to each widget - why is this? How can I prevent this - I only want to prevent resizing (the ui-state-disabled sets the opacity of each element to .35 and I don't want that)?

Thanks

**Comment by Steimel** [comment]
@kidmeke Did you ever figure out this issue? I have the same problem: I want a static grid, but I don't want ui-state-disabled added. I could manually add a class that overrides the opacity, but that seems unclean

**Comment by Geczy** [comment]
ui-state-disabled

Same problem here, this class makes all my grid items opacity 0.35

**Comment by McQuinTrix** [comment]
Dont know if people will like this solution or not but I completely disabled dragging by commenting out: 

```
drag: function (event, ui) {
                /*
                var x = Math.round(ui.position.left / cell_width),
                    y = Math.floor((ui.position.top + cell_height/2) / cell_height);
                if (!self.grid.can_move_node(node, x, y, node.width, node.height)) {
                    return;
                }
                self.grid.move_node(node, x, y);
                self._update_container_height();
            */
            }
```

line 623 - 629

**Comment by pskumar448** [comment]
This worked for me to disable resizing & dragging
data-gs-no-resize="true" data-gs-no-move="true"

**Comment by bluffrockstar** [comment]
@pskumar448's solution worked as it should

**Comment by toddler4372** [comment]
Does anyone know how to disable resize when you're serializing your grid?

My grid blocks look like this:
`
{x: 3, y: 8, width: 3, height: 4, content: '<div class="grid-stack-item-content"><div class="gridster-box p-m"><div class="gridster-title no-padding"><h4>Payment Adjustment</h4><p class="m-b-0">by Melinda</p></div><a href="javascript:void(0)" onclick="showPopup_PM16();" class="chart-expand" /></a><div id="Pmt_chartdiv16"></div><div class="insight-footer" style="bottom: -3px;"><div class="avatar inline"><img src="images/profile.jpg" alt="avatar" class="profile-2" /></div><div class="comments inline pull-right dk-grey"><a href=""><i class="fa fa-comment fa-lg dk-grey"></i> 6</a></div></div></div></div>'}`

**Comment by ShashankRama** [comment]
add this ' data-gs-no-resize="true" data-gs-no-move="true" data-gs-locked="true"' to grid-stack-item-content div
