### ISSUE TITLE
How to add zoom support?

### ISSUE THREAD

**Issue by ulissepress** [gridstack/gridstack.js#1000]
Editing small grid stack area, will need a zoom factor...

**Comment by david-offord** [comment]
@ulissepress I ended up creating another div, and either layering it over the gridstack/content position or 'd-none'ing the gridstack and replacing the entirety of it with the contents of the widget.

**Comment by radiolips** [comment]
I'm still a little confused, but adding css `zoom: x%` seems to work fine. I verified this by editing the grid on gridstackjs.com in-place. I'm closing this out. If I'm off-base on what you're asking for, please reopen with more context and I'll take a look.
