### ISSUE TITLE
Knockout breaks with latest version of gridstack

### ISSUE THREAD

**Issue by adriver-kwiboo** [gridstack/gridstack.js#1002]
## Subject of the issue
I am using gridstack with knockout, adding widgets causes the browser to hang.

## Your environment
gridstack 1.0.0-dev

## Steps to reproduce
See fiddle:
https://jsfiddle.net/n7mtjp6f/1/

Add four or move widgets and see the browser hang

## Expected behaviour
Widgets continue to add

## Actual behaviour
Gets to about 3/4 widgets and then hangs the browser

**Comment by radiolips** [comment]
Hey @adriver-kwiboo ! I opened your fiddle, but I wasn't able to move any widgets. I *was* able to add a ton of widgets, though...?

**Comment by adriver-kwiboo** [comment]
looks like it's been fixed in 0.5.1-dev
