### ISSUE TITLE
Is it possible to have one row which it can grow horizontally  .

### ISSUE THREAD

**Issue by mbosajin** [gridstack/gridstack.js#1003]
## Subject of the issue
Hi,I need to have a grid which contains one row and grows horizontally when new item gets added.

![image](https://user-images.githubusercontent.com/53353489/61982870-1ca0cc00-afcc-11e9-831a-6e65ed6f75fe.png)

## Your environment
* version of gridstack.js
0.3.0-dev
* which browser and its version

## Expected behaviour
Tell us what should happen

## Actual behaviour
The grid only grows vertically when new item is added to grid.

**Comment by radiolips** [comment]
@mbosajin gridstack uses a 12-column grid by default. I believe you're saying you need to add/remove columns on-the-fly. Is that correct?

**Comment by adumesny** [comment]
I don't believe gridstack is designed for that (1 row expandable with new columns... I assume you want to to scroll (keep items same size) similar to oneColumnMode  but sideway. won't fix. closing.
