### ISSUE TITLE
Draggable helper clone does not clone item attributes and uses child object to drag.

### ISSUE THREAD

**Issue by rob101** [gridstack/gridstack.js#1004]
## Subject of the issue
Draggable helper clone does not clone item attributes and uses child object to drag.

## Your environment
* version of gridstack.js 1.0.0-dev
* which browser and its version: Chrome 75.0.3770.142

## Steps to reproduce
Drag item 1 from left to right; from the blue pallet to the yellow canvas. https://codepen.io/alias51/pen/QeGMYm

## Expected behaviour
Item 1 should be cloned and with original `data-gs-x="0" data-gs-y="0"` attributes. It should be unmoved from its original position in the pallet.

When moving, it should show the 'grid-stack-item' as is the case when `helper:clone` is disabled.

## Actual behaviour
Item 1 is cloned with default(?) `data-gs-x="4" data-gs-y="0"` attributes, moving the item.
When helper clone is enabled, item whilst being dragged only shows `grid-stack-item-content` not `grid-stack-item`.

**Comment by rob101** [comment]
Looking further at this, I think the issue arises because the dragstop event triggers when the item leaves the grid but before the item is dropped. This means the clone picks up the last position at data-gs-x="4" data-gs-y="0"`.

**Comment by radiolips** [comment]
Hey @rob101 . Thanks for logging an issue! I opened up your example, but I'm not exactly following. When a widget is moved from grid A to grid B, it can be placed anywhere in grid B-it doesn't automatically have coordinates.

**Comment by adumesny** [comment]
closing due to no replies. please re-open if still issue.
