### ISSUE TITLE
Fluid height for grid elements

### ISSUE THREAD

**Issue by agenceKanvas** [gridstack/gridstack.js#1006]
I've almost solved all my problems but the main one is the fixed heights of the elements.
Is there a way to work with fluid heights ? 
Or maybe a tip to work with it ? 

Thanks !

**Comment by agenceKanvas** [comment]
For more code, here is what I did : 
http://wordpress-284843-881255.cloudwaysapps.com/demo/float.html
As a workaround, I used cellHeight to 1 but it seems that it's not a pixel unit. 
Anyone with a workaround to calculate automatically the height ? 
What's the height of a unit when we use 1 as a value for cellHeight ? 

Thanks !!! :)

**Comment by radiolips** [comment]
Hey there, @agenceKanvas ! I'm a little confused. What exactly is the problem? All widgets should be vertically resizable (changing height).

**Comment by adumesny** [comment]
closing due to no replies. cellHeight is in pixels (or you can use % now though I have not tested it).
