### ISSUE TITLE
Error while following basic usage

### ISSUE THREAD

**Issue by dahohawley** [gridstack/gridstack.js#1007]
## Subject of the issue
Hello, im trying to following the basic usage ( [Here](https://stackoverflow.com/questions/57651385/gridstack-js-defaults-of-undefined) )

but i get these error 

![image](https://user-images.githubusercontent.com/23535600/63663140-6ce99480-c7eb-11e9-8abb-2c2d1fb1e7ca.png)

im literally copy and pasting the code from the example.  

```html
<div class="grid-stack">
    <div class="grid-stack-item"
        data-gs-x="0" data-gs-y="0"
        data-gs-width="4" data-gs-height="2">
            <div class="grid-stack-item-content"></div>
    </div>
    <div class="grid-stack-item"
        data-gs-x="4" data-gs-y="0"
        data-gs-width="4" data-gs-height="4">
            <div class="grid-stack-item-content"></div>
    </div>
</div>

<script type="text/javascript">
$(function () {
    $('.grid-stack').gridstack();
});
</script>
```

## Your environment
![image](https://user-images.githubusercontent.com/23535600/63663179-96a2bb80-c7eb-11e9-9b29-d2c5be523320.png)

## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://jsfiddle.net/dweiss/dqyvh6vr/) as a base.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

**Comment by radiolips** [comment]
@dahohawley strange. Could you provide a fiddle for this so that I can check it out? I know on the SO page you linked to, someone suggested downgrading jquery–I'm surprised any version of jquery doesn't work. Anyway, if you can provide an example, I'd be happy to take a look for you.

**Comment by radiolips** [comment]
gridstackjs.com uses the most recent version of jQuery and jQueryUI right now, I believe.

**Comment by radiolips** [comment]
@dahohawley Try the latest code snippet on gridstackjs.com. You should be able to copy-paste it in and have a working grid.
