### ISSUE TITLE
Gridstack items misplaced after version update

### ISSUE THREAD

**Issue by vrungov** [gridstack/gridstack.js#1008]
## Subject of the issue
Hi,

We have a dashboards application utilizing gridstack.js for the layout of widgets inside the dashboard container.
After gridstack.js version update from 0.2.4 to 0.4.0 all previously saved dashboards got misplaced.
This means all widgets in previously saved dashboards got different size and appeared in different location in the gridstack container making them hardly usable. 
After downgrading from 0.4.0 to 0.3.0 there was a slight improvement with this issue but there are still misplaced widgets.
My question is as there is obviously a breaking change in the layout of the items inside the gridstack container is there a way to compensate it or work around it?

## Your environment
gridstack - version 0.3.0 / 0.4.0
jquery-ui - version 1.12.1
google chrome - version 76.0.3809.100

## Steps to reproduce
Add several widgets in a container using gridstack.add_widget version 0.2.4:

    add_widget(el: JQuery, x: number, y: number, width: number, height: number, auto_position: boolean): JQuery

Update gridstack.js version to 0.3.0 or 0.4.0.
Observe the widgets added with 0.2.4

## Expected behaviour
Widgets should stay on exactly the same location with the same size between different gridstack versions

## Actual behaviour
Widgets get displaced and different size between gridstack versions

**Comment by radiolips** [comment]
@vrungov do you have an example that I can look at? Though the API has certainly changed, I'd think that the widgets should still be placed in the same location. Just so you know, before long the old API will go away and the new will have to be used–but for your case, for now, it should still work fine.

**Comment by adumesny** [comment]
closing as no replies. Please provide a jsfiddle (ex: https://jsfiddle.net/adumesny/jqhkry7g) if you wish us to take a look. thanks. 0.2.4 is really old...
