### ISSUE TITLE
Dashboard Gadgets/Items Jumping

### ISSUE THREAD

**Issue by JennaCulsh** [gridstack/gridstack.js#1010]
## Gadget are not saving in place within the dashboard and are jumping back to their original location
When changes are made to the dashboard and saved, frequently the gadgets are not saving and are moving back to their previous location

## Your environment
0.2.5 version of gridstack.js
Chrome (in the most recent version and previous version)

## Steps to reproduce
See recording: https://www.loom.com/share/7f7e9951863e4f5ba4d82089185a9897

## Expected behaviour
Gadgets should remain fixed in place

## Actual behaviour
Gadgets are relocating back to their previous position on the dashboard

**Comment by radiolips** [comment]
Hey there, @JennaCulsh ! Two questions: 1) Could you update to a newer version of gridstack.js, at least for testing purposes? 2) How exactly are widgets being saved and reproduced? That's not part of gridstack.js natively, so the code to save off those widgets must be custom.

**Comment by radiolips** [comment]
Closing this out as it's most likely an issue with how the library was used. The serialization can be done purely with DOM, so as long as coordinates are used, this shouldn't be a problem. Please reopen if you have more information.
