### ISSUE TITLE
Is it possible to make certain sizes for the widgets

### ISSUE THREAD

**Issue by 0309620** [gridstack/gridstack.js#1011]
Is it possible to change the widgets from Small, Medium to Large

So you go from data-gs-width="4" to data-gs-width="8" when dragging
instead of it going +1

**Comment by radiolips** [comment]
Hey there, @0309620 ! Would it be an option to use a grid with fewer than 12 columns? For your example, it sounds like four columns might make sense?

**Comment by adumesny** [comment]
actually 4/8/12 would be a 3 column grid which is supported, so just do that! look at doc on how to change # of columns and your widgets would be 1,2,3 sizes.

**Comment by adumesny** [comment]
re-open if this is still an issue given above solutions.
