### ISSUE TITLE
refresh layout after deleting item/node

### ISSUE THREAD

**Issue by aznarepse** [gridstack/gridstack.js#1013]
I am deleting items in the grid by code and I would expect the grid to re layout and stack the item upwards if there is space; basically, the item that was below to occupy the space of the deleted item and so on. However, it does not happen and the space remains blank.

- I have tried with removeWidget(item, true) and removeWidget(item, false).
- I have tried with animate true and false
- tried with staticGrid false and true
- I have even tried commit after teh removal but after looking at the code it seems that it only works for batches.

I have checked the events of the grid and they are fired.

Clearly, I am missing something... Is there any way to force a re -layout of the grid to recalculate empty spaces?

**Comment by aznarepse** [comment]
All right, I have finally created and exposed new method that calls:

- _packNodes();
- _notify();

and it works like a dream.
Am I reinventing the wheel? Is there already some 'official' way to do this?

**Comment by roldeguz** [comment]
If you want to use available spaces, you must set float (gridstack config) to false. 

And when you're adding your items, when doing the addWidget call, set the autoposition option to true (it will ignore X and Y) and will just place the array items as long as it will fit, in sequence.

**Comment by aznarepse** [comment]
@roldeguz Thank you. Unfortunately, I have also tried setting the float property to false and to true and it does not make a difference.
I cannot use autopostion, since the items come with a coordinate and it must be respected.

It is working after I am using the 'custom' method. However, I would prefer an 'official' way. I am inheriting this project and suffering already some oddities within and I would not want any future developer remembering me after such 'customizations'

**Comment by roldeguz** [comment]
@aznarepse hmm, yeah it should behave the way you want it to since the default for the float option is false. Can you please tell me which gridstack version are you using? Thanks.

**Comment by aznarepse** [comment]
@roldeguz Scary! 0.2.5! As I said, inherited it...
Not sure I would lie to uplift and have something breaking...

**Comment by crapthings** [comment]
i have same issue

https://streamable.com/k039m

**Comment by aznarepse** [comment]
@crapthings I did not find a 'vanilla' way to solve it. I wrote and exposed a new method, refresh(), for the prototype that simply calls the already existing 
    _packNodes();
    _notify();

and call it any time I need a refresh (e.g. after removing an item). It works well.

**Comment by radiolips** [comment]
@crapthings  are you also using 0.2.5? This should currently work, not sure about 0.2.5.

**Comment by crapthings** [comment]
after set autopos, its working

.addWidget(widget, x, y, width, height, autopos)

**Comment by radiolips** [comment]
@crapthings Great! I'm closing this out because you got it working, but also because @adumesny put in a fix that may help you in a recent version of gridstack.js Please reopen if you're having issues still.

**Comment by Snash077** [comment]
> All right, I have finally created and exposed new a method that calls internally:
> 
> * _packNodes();
> * _notify();
> 
> and it works like a dream. Am I reinventing the wheel? Is there already some 'official' way to do this?

how to call the both _packNodes(); and  _notify(); method
