### ISSUE TITLE
Widgets initiated with undefined data-gs-x and data-gs-y glitch

### ISSUE THREAD

**Issue by SomMeri** [gridstack/gridstack.js#1017]
If the widgets do not have initial data-gs-x and data-gs-y specified, widgets are rendered with wrong size. They are also all located on one place.

## Your environment
* version of gridstack.js: 0.4.0 <- it worked correctly in previous versions
* which browser and its version: all of them

## Steps to reproduce + Actual behaviour
Working demo: https://jsfiddle.net/2p7a9wjg/

Both widgets are created without data-gs-x and data-gs-y:
````html
<div class="grid-stack">
    <div class="grid-stack-item upper"
        data-gs-width="2" data-gs-height="2">
            <div class="grid-stack-item-content"></div>
    </div>
    <div class="grid-stack-item"
        data-gs-width="2" data-gs-height="2">
            <div class="grid-stack-item-content"></div>
    </div>
</div>
````

Only one widget is visible and it is small.

## Expected behaviour
This is how it should look like - rendered with 0.3.0: https://jsfiddle.net/m3fxs7u1/4/

Both widgets are visible and they are big.

**Comment by adumesny** [comment]
actually if you label them 'item 1' and 'item 2' you will see in rev3
[2]
[1]

while in your fix you get
[1]
[2]

I think ideally not specify a position should land you
[1] [2]
instead of both trying to go space (0,0) as you have...

the overlap and wrong size is incorrect in v0.4 and v0.5 (get inf loop error) so we NEED a fix, don't think this is best fix.

**Comment by radiolips** [comment]
@SomMeri Thanks for logging this and thanks for putting in a PR! @adumesny put in a slightly different version, which I think will help solve the problem. Try this out with our latest develop branch version! Please reopen or log a new ticket if your problem still isn't resolved.
