### ISSUE TITLE
Allow to resize widget to the left side

### ISSUE THREAD

**Issue by pierrefoyard** [gridstack/gridstack.js#1019]
Hello,
I'm able to resize my widgets by grabbing them from lower right side.
This is good to resize widgets towards the bottom and toward the right, 
but when my widget is already at the far right side, I would like to resize it toward the left.
Is there an option to adapt resize direction please?
Many thanks,

Pierre.

**Comment by radiolips** [comment]
Hey @pierrefoyard ! Absolutely there is! https://github.com/gridstack/gridstack.js/tree/develop/doc#options check out the `resizable` option there. For reference, here is where you can see the options for handles https://api.jqueryui.com/resizable/#option-handles
