### ISSUE TITLE
Items become invisible/move when dragging

### ISSUE THREAD

**Issue by flozzel** [gridstack/gridstack.js#1020]
I have a sidebar with dashboards from which you can drag the items to other dashboards.
And while dragging the items outside the sidebar, they get invisible and sometimes the already positioned items in the other dashboards behave strange and start moving as soon as you take an item and drag it.

Here is a short clip for better understanding of the problem (click it for fullsize):

![gridstack_problem_from_swf_to_gif_same_quality](https://user-images.githubusercontent.com/33422121/67382909-88281480-f58e-11e9-99f8-00ff2b57305e.gif)

**Comment by radiolips** [comment]
@flozzel this looks cool! Could you tell me–what version are you using? I don't know if it'll fix your problem, but the dev version should be released today (0.5.0, previously 1.0.0-dev).

**Comment by flozzel** [comment]
@radiolips I am using the "gridstack.js 1.0.0-dev" version. But if you release a new version soon, I will try to update my version first and maybe it already fixes the problem.

**Comment by flozzel** [comment]
Tested the actual dev-version (gridstack.js 0.5.0), but I am still having the same issues.

**Comment by radiolips** [comment]
Thanks for testing that out. We'll take a look.

**Comment by radiolips** [comment]
@flozzel this seems like it might just be a z-index problem? gridstack.js doesn't actually do anything with the item you're dragging until you're dragging it over a grid. In the advanced demo on gridstackjs.com and on the two grids example, it seems to work okay. Could you provide a code example that we could look at?

**Comment by flozzel** [comment]
@radiolips I have created a test system for you in which you can play free around. I will send you the login details via an e-mail. For security reasons, I can not provide the test environment here public for everybody, but I will post the solution of the problem here.

I played around with the z-index, but I did not come up with a solution. Somehow I think the sidebar is the problem here, because it is on an other layer. If you drag some of the elements from the sidebar into the main dashboard and then reload the page, you will see the problem and the already placed items start moving as soon as you start to drag more items from the sidebar.

**Comment by radiolips** [comment]
I was able to resolve this with @flozzel via email. Please reopen if you're still having problems, but in your demo I was able to successfully move the widget from the sidebar to the main screen.

**Comment by flozzel** [comment]
The problem was an overflow-x: hidden and an overflow-y: auto on some of the outer elements containing the dashboard.

For the other problem with the moving items I am still looking out for a solution. radiolips suspects that this could be because of CSS too. I will inform you when I have found out something.

**Comment by adumesny** [comment]
@flozzel > other problem with the moving items I am still looking out for a solution

You could switch between 0.4.0, 0.5.0, 0.5.1, 0.5,3 and see if the behavior changes which might hint if the issue in the lib

**Comment by flozzel** [comment]
I was able to solve most of the problems. Instead of giving the widgets a defined width of 300px by defining it in css, I am using a column width of 12. 

The problems with the wrong widget height, where each item was treated as it has double of its height, was caused by the following statement:

`
this.$dashboard.droppable(
{
 accept: '.grid-stack-item[data-type="employees"], .grid-stack-item[data-type="vehicles"]'
});
`

Instead of this, I am now using the "acceptWidgets" option to controll which widgets are allowed to drop into the dashboard.

And finally the problem with the already placed widgets start moving as soon as you take a new item (widget) and drag it: This was caused because I first load all the items (widgets) from the database and initialize a dom element for each of them, and then allocate this dom element to the sidebar. Then in the next step, when loading the disposals and the widgets assigned to them, I take the already to the sidebar allocated and appended widget and allocate it to the dashboard again.

And this was the reason why an already placed widget starts to move when dragging a new from the same type.

Now the only problem that remains is that items overlap sometimes. Any ideas what might causes this? Maybe a css statement?

**Comment by adumesny** [comment]
> (Edit: I have taken the liberty of tagging you, so that you can see it eventually)
no need as we get all updates as maintainers :)

> I was able to solve most of the problems. Instead of giving the widgets a defined width of 300px by defining it in css, I am using a column width of 12.
grids are column based so YEAH the parent would have to take a fix 300px sizing. Wonder if the doc needs to be clearer about it.

 > Now the only problem that remains is that items overlap sometimes
the only times I've seen this was bad css since we use it do all layouts. if you use other than 12 columns make sure to include the extra.css file!
