### ISSUE TITLE
Create resize button

### ISSUE THREAD

**Issue by dbcdiogo** [gridstack/gridstack.js#1025]
I have item with height=5 and width=5, i want to create a button inner item, when click, automatic resize to width=1 and height=1.

I can resize item, but when move position, return to old size

With resize handler works fine

**Comment by roldeguz** [comment]
On the click event of the button, you can grab the parent widget container and change the data attributes. 

`$(widget).data("gs-width", 1); 
 $(widget).data("gs-height", 1);`

**Comment by dbcdiogo** [comment]
> On the click event of the button, you can grab the parent widget container and use the resize function.
> 
> `$("#gridstack").data("gridstack").resize($(parent), 1, 1);`

Tks a lot. Works fine

**Comment by roldeguz** [comment]
No problem :)

**Comment by adumesny** [comment]
@dbcdiogo you can use slacks to ask question instead of opening an issue. And please close this next time. thanks!
