### ISSUE TITLE
GridStack responsive behavior customize

### ISSUE THREAD

**Issue by vikasKacholia** [gridstack/gridstack.js#1031]
Currently when we resize our window the grid width also get resize accordingly.
but in my case i want instead of resizing the grid they should move to next row and the size of grids remains same always.

## My environment
* version of gridstack.js - 0.4
* Google chrome Version 78.0.3904.70

i tried something as below on window resize - 
```js
$(window).resize(function () {       
        resizeGrid();
      });

// set grid width based on window size
function resizeGrid() {
        var grid = $('.grid-stack').data('gridstack');
        if (isBreakpoint('xs')) {
          // one column mode
        } else if (isBreakpoint('sm')) {
          grid.setGridWidth(3, true);
          // grid._updateNodeWidths(12,3);
        } else if (isBreakpoint('md')) {
          grid.setGridWidth(6, true);
          // grid._updateNodeWidths(12,6);
        } else if (isBreakpoint('lg')) {
          grid.setGridWidth(12, true);
        }
        // loadGrid();
        $('.grid-stack-item').each(function () {
          var width = ($(this).context.dataset.gsWidth * 8.3333333333) + '%';
          $(this).width(width);
          $(this).css("min-width", width);
        });
      };

function isBreakpoint(alias) {
        return $('.device-' + alias).is(':visible');
    }
```
but with this i am facing overlapping and sorting issues on grids.

**Comment by radiolips** [comment]
Hey @vikasKacholia . Could you try unloading and reloading the grid? That might help get the widgets to look at the fact that things have been resized.

**Comment by adumesny** [comment]
closing due to no response... Not that responsive `setColumn()` is now much more robust, so please check the latest https://gridstackjs.com/demo/responsive.html
