### ISSUE TITLE
Install with composer

### ISSUE THREAD

**Issue by PSF1** [gridstack/gridstack.js#1037]
## Subject of the issue
I require this library with composer, it has integration with npm and bower packages without these tools.

With version 0.4.0, we have the dist folder with a working copy of the library, but the folder was removed from 0.5.0 and 0.5.1 and that break the project because we can't install npm/bower on the environments.

Is possible to add the dist folder again?

Thx

**Comment by radiolips** [comment]
Thanks @PSF1 . `npm` is pulling the dist directory, but `bower` is not. I'll take a look.

**Comment by adumesny** [comment]
@PSF1 so you don't use npm (likely only thing we'll support) nor bower (which is obsolete) ? sorry not familiar with composer.

**Comment by PSF1** [comment]
Composer integrate both, but npm don't have 0.5.x versions. Is it possible that npm dont updated her packages?

**Comment by adumesny** [comment]
there definitely is a 0.5.1 npm package - https://www.npmjs.com/package/gridstack 
it's even on some CDN the day we posted it. I don't know how composer works though.

**Comment by radiolips** [comment]
@PSF1 just to add to what @adumesny mentioned–the _develop_ branch isn't available on `npm`, but we're working hard to make sure to frequently release code now, and every release will be available on `npm`.

**Comment by PSF1** [comment]
Wow :_ D I dont know why... Tomorrow I'll see it again.

Thx all

**Comment by PSF1** [comment]
Yes, today I can install the npm version 0.5.1, and yes it has the dist folder, It must be a propagation problem with npm.

The composer integration that I'm using is this: https://asset-packagist.org/

Thx all : ))

**Comment by adumesny** [comment]
great, closing now. 0.5.2 is also out since yesterday...
