### ISSUE TITLE
Passing null values to addWidget() ends with exception

### ISSUE THREAD

**Issue by creage** [gridstack/gridstack.js#1042]
this will fail if we pass `null` as a value of `x`, as `typeof null === 'object'` returns true.

_Originally posted by @creage in https://github.com/gridstack/gridstack.js/pull/1038/review_comment/create_

**Comment by radiolips** [comment]
Thanks, @creage . I'll fix this in the next couple of hours by also checking to make sure it's not null.

**Comment by adumesny** [comment]
@creage thanks for finding this! for now pass `undefined `instead of `null`. fixing now.

**Comment by adumesny** [comment]
fix in next release
