### ISSUE TITLE
Multiple Grids Problem on moving items

### ISSUE THREAD

**Issue by nikoskarakostas** [gridstack/gridstack.js#1043]
## Subject of the issue
Lets say we have two grids: grid A and grid B.
Each grid has some items. Lets say grid A contains item1 and grid B contains item2.
Whenever I move an item on the first one it moves as it is supposed to. 

We assume the following sequence of events: 
event 1: I move item 1
event 2: I move item 2
event 3: I move item 1
event 4: I move item 2
(Moves take place inside each grid and not drag-drop to one another)

While on event 3 (moving item 1 for second time), placeholder doesn't appear.
Also, on start of event 4 (moving item 2 for second time), item 1 gets disappeared. 

This can be checked on [Two grids demo](https://gridstackjs.com/demo/two.html)

Is this a known issue? May it be fixed?

*When acceptWidgets property is not defined, everything works smoothly. 

You have done a great job btw.

## Your environment
* gridstack 0.5.2 (also tested on 0.4 and the same thing happens)
* Firefox 70.0.1

**Comment by radiolips** [comment]
Wow, that's brutal @nikoskarakostas . I'll take a look at what's going on–thanks for logging the issue.

**Comment by adumesny** [comment]
keep in mind that https://gridstackjs.com/demo/two.html is using a very old version of gridstack 2.7-dev - we need to fix that ASAP
but it sounds like you tested locally, and I just tried 0.5.2 and still there!

**Comment by nikoskarakostas** [comment]
I assume you will update this thread if you have any news so I will keep track on it. Thank you.

**Comment by radiolips** [comment]
@nikoskarakostas Check out the code in the develop branch. Let me know if it doesn't resolve your problem. For my local tests, I was able to move widgets in either grid and move them back and forth. IT also fixed a few other strange issues (eg if you move a widget, without letting go of the mouse, from one grid to another, back and forth several times, an error was thrown).
