### ISSUE TITLE
Is it possible to limit value data-gs-height for grid-stack-item?

### ISSUE THREAD

**Issue by pixotri** [gridstack/gridstack.js#1059]
Hello.
I can't find any options to restrict value for data-gs-height attribute..
I want to have all grid-stack-items with parameter data-gs-height not more then 4.
And for example, value of 1 is 25% of height, value of 2 is 50% of height and so on.

**Comment by roldeguz** [comment]
There is a max-height property that you can set when creating a widget.

https://github.com/gridstack/gridstack.js/tree/develop/doc#addwidgetel-options

**Comment by adumesny** [comment]
and `data-gs-max-height`

**Comment by pixotri** [comment]
data-gs-max-height - solved my issue!
