### ISSUE TITLE
How to prevent a widget from being dropped into a full grid?

### ISSUE THREAD

**Issue by Arj4ns** [gridstack/gridstack.js#1062]
Sorry if the title isn't clear. Basically, I have 2 separate grids. I want to stop items from being moved into the second grid if the widgets within it already reach the maximum vertical constraint. No matter what i do though, it still allows the object to dropped into the bottom of the grid. I've tried making the grid static when a widget if picked up, disabled movement, and of course, tried to set a height limit. But I can still drop objects into the grid when it's reached max height. 

Here is a recreation of what i'm working on. To replicate my issue, just take an item from the right column, and drag it to the left column. I want to disable the ability to drop it in that grid unless it has some empty space.
https://jsfiddle.net/npsujfra/

So I guess an easy way of asking this, is that is there a method that would allow me to disable the ability to drop a widget into a grid?

Thanks!

**Comment by adumesny** [comment]
couple issues:
1) your sample uses non default 12 columns, you need to *also* include `gridstack-extra.min.css` to get CSS right
2) you are using `columnn` and `maxRow` which I just added to 0.5.3 (released this morning). you are using 0.5.2 (there would need the old names...)

make those changes and let me know. maxRow should prevent grid from growing and therefore being dropped on.

**Comment by adumesny** [comment]
maybe I should rename it to `gridstack-column.css` or something. I too didn't know what it was for (and missed the doc which is why I updated couple sections) to maybe make it clearer...
The min.js/min.css should still have comments on top which i will later fix.

**Comment by Arj4ns** [comment]
Still doesn't appear to work. I added the changes like you said, or I believe I did at least. I have not heard of the gridstacks extra css file. I did add maxRow in, but i'm still able to bypass it when I drag and drop a widget into the grid.

https://jsfiddle.net/npsujfra/2/

It is very possible that I have the links wrong, so it may not even be loading the proper functions. That being said, I get alerts that certain methods I was using would be removed in the next version, telling me that I did successfully update to 0.5.3.

**Comment by adumesny** [comment]
In your second sample, I still see `gridstack@0.5.2` in multiple places, no `gridstack-extra.css` and you using `height: 11` which is the old name (=== `maxRow` now). please fix if you want me to take a look.

**Comment by Arj4ns** [comment]
My bad, the fiddle didn't update correctly. That was the exact same example I showed in the first post.

This should be the correct example.
https://jsfiddle.net/udk80h53/

**Comment by adumesny** [comment]
nothing jumps at me right now, but bottom item resize the 12x4 really funky... jumps to 1 height.
`var grid = $('.grid-stack').data('gridstack');` would return a list of 3 grids by the way, then you access one of them... could be your issue.
I will try to look tomorrow.

**Comment by roldeguz** [comment]
On the 'dropped' event, determine if the grid is full, then if its true, you can always set the droppable feature of the grid to false.

`$(".grid-stack").droppable("disable");`

And everytime you remove a widget, set it back to true.

**Comment by adumesny** [comment]
seems like the lib should do that for you though.... there is already code to see if you can insert an object... canBePlacedWithRespectToHeight() checks for grid growing past max size. will have to reproduce issue first and debug...

**Comment by Arj4ns** [comment]
Seems like roldeguz's suggestion worked. Thanks for the help guys!

Link to working example
https://jsfiddle.net/wdn35k87/

I have it set up so when dragStart event occurs, the left grid is checked to see if the grid is filled to the maxRow value. If it is, the grid's draggability is disabled.
