### ISSUE TITLE
Column issue

### ISSUE THREAD

**Issue by pixotri** [gridstack/gridstack.js#1065]
I initialize gridstack script as below:
```
var gridStack = $('.grid-stack').gridstack({
      column:3
});
```
When I move blocks in grid system it indeed has 3 columns, but why they are of standard width? Why each column does not have 1/3 of wrapper width?

In CSS I can change width styles how I want, but if it is needed to move anything it becomes a problem. 

How it is possible to make grid column width 100%/column in JS?

**Comment by radiolips** [comment]
Hey @pixotri ! Have you included `gridstack-extra.css`?

**Comment by pixotri** [comment]
> Hey @pixotri ! Have you included `gridstack-extra.css`?

Much better. Thank you!
But I had to remove .grid-stack-1, .grid-stack-2 and so on classes. What are they for?

Is there a possibility to generate smth similar to this but for height(rows)?

**Comment by adumesny** [comment]
@pixotri please check the doc and samples as your 3 questions so far are all spelled out there - but let us know if something not clear!
Slack channel for Q might also take less time than dealing with opened 'issues' here.
Thank you for checking gridtstack!
