### ISSUE TITLE
draggable handle option for particular widget

### ISSUE THREAD

**Issue by spidy10** [gridstack/gridstack.js#1076]
## draggable handle option for particular widget

I have bunch of widgets load on page using grid stack js. It is working good as expected.
I need to implement draggable handle option for particular widget instead of all.
Is it possible with gridstack.js ?

## Using grid stack js with basic javascript and Jquery
* version of gridstack.js is 1.0.0-dev

**Comment by adumesny** [comment]
you mean to have some drag/resize while others don't ? sure - take a look at https://gridstackjs.com/demo/advance.html from the main site.

Also you list 1.0.0-dev, which actually is quite old. we've released 5 time since code was labeled as such.

**Comment by spidy10** [comment]
@adumesny thanks for your quick reply. 

My main problem is I have one widget and inside that widget one text area. Once user try to resize that text area the widget drag automatically. Because text area is inside widget.
I have tried one solution with lock widget once I lock widget and then resize text area but for me this is not feasible.

So can you please suggest me solution for it ?

Thanks

**Comment by spidy10** [comment]
* Fixed issue from my self.
Thanks for help :)

**Comment by adumesny** [comment]
my widgets have only a title area (20pix on top) that can be dragged, the rest is for content interactions. You can also set the grid to not be editable to prevent payout changes if that makes sense, until an explicit mode (which I also do in some apps). 
But sounds like you found a solution.
