### ISSUE TITLE
Version 0.5.4 JQuery 

### ISSUE THREAD

**Issue by adhayward** [gridstack/gridstack.js#1077]
When attempting to install version 0.5.4 of this package JQuery downgrades from 3.4.1 to 3.0.0

I believe that 
https://github.com/gridstack/gridstack.js/blob/a1f10874ab89cfea822785182147505b485dfdf0/package.json#L34

should be "^1.8 || ^2 || ^3"

**Comment by adumesny** [comment]
'3' means any 3.x revisions, and I'm not seeing that issue. I just did a `yarn upgrade gridstack` and it went for 0.5.2 to 0.5.4 and it brought in jquery@3.4.1 (I had 3.2.1 before).

anyone seeing this issue and what did you do get gridstack ?

**Comment by adumesny** [comment]
I just pushed 0.5.5 by the way (but didn't change above dependency).

**Comment by adhayward** [comment]
I'm running a PHP project so I'm installing the npm package via composer (https://asset-packagist.org/package/npm-asset/gridstack).

I don't have much experience with package.json files so that was just a guess seeing as that line had been changed going into 0.5.4.

However 0.5.5 has now installed correctly so I'm going to assume that something was going wrong with how composer/npm communicate the dependencies.
