### ISSUE TITLE
Changing from landscape to portrait or vice versa causes problems on iPad 3rd gen.

### ISSUE THREAD

**Issue by bimarc** [gridstack/gridstack.js#1083]
## Subject of the issue
Changing from landscape to portrait or vice versa causes problems

## Environment
* gridstack.js - last version
* Chrome app - last version
* IPad 3rd generation - 10.3.4

## Steps to reproduce
Using IPad 3rd gen., when the view change from landscape to portrait or vice versa. When resize and move items are enabled.

## Actual behaviour
When the view change from landscape to portrait or vice versa:

- sometimes gridstack renders uncorrectly
- rendering is slow

<br />

- **Error**: cannot call methods on draggable prior to initialization; attempted to call method 'enable'

![image](https://user-images.githubusercontent.com/40889899/70149081-b2014a80-16a7-11ea-91be-29a7284e74d3.png)

**Comment by adumesny** [comment]
are you including jquery UI and touch based ? (I have not tested mobile) what exactly does you file looks like and the error ? thanks.

also 'latest' doesn't tell me if 0.5.5 or 0.5.5-dev current code)

**Comment by adumesny** [comment]
I believe calling enable before init of DD JQ has been fixed. closing
```js
    if (opts === 'enable') {
      $el.draggable().draggable('enable');
```
