### ISSUE TITLE
configurable new widget

### ISSUE THREAD

**Issue by drzraf** [gridstack/gridstack.js#1091]
## Subject of the issue
I would like a "configurable" new widget. Some input are available and according to their value the new widget differ. I can't only get the `helper` to differ, not the final widget.

## Steps to reproduce
```js
$('.newWidget').draggable({
  revert: 'invalid',
  scroll: false,
  appendTo: 'body',
  helper: function() {
    var element_id = $(this).find('input[name="element-id"]').val(),
        element_type = $(this).find('select[name="element-type"] option:selected').val();
    return $(`<div>#${element_id} <input type="${element_type}" /></div>`).clone();
  }
});
```

## Expected behaviour
Selecting `input type=checkbox` in the new widget should create a `checkbox` item, like it does **during** drag (before `mouseUp`)

![Screenshot from 2019-12-13 19-57-44](https://user-images.githubusercontent.com/1169926/70837578-09f42b80-1de3-11ea-8e95-8d0f3daf8b19.png)
![Screenshot from 2019-12-13 19-57-59](https://user-images.githubusercontent.com/1169926/70837589-1aa4a180-1de3-11ea-9bc0-cb38e60fba2a.png)

## Actual behaviour
A copy of the `Add widget <div>` itself is created.
![Screenshot from 2019-12-13 19-58-04](https://user-images.githubusercontent.com/1169926/70837579-0a8cc200-1de3-11ea-88a1-ae5241cdc987.png)

Listening to `dropped` in the second grid does not provide the desired **altered** widget.

**Comment by adumesny** [comment]
@drzraf sorry I didn't respond sooner. Have you found a fix or could you provide a jsfiddle for me to reproduce please ? you can use [this template](https://jsfiddle.net/adumesny/jqhkry7g) as a base.

**Comment by adumesny** [comment]
so I re-wrote the drag&drop and see the old code was cloning the original dragged item (always) while giving you a change to create an `helper` drag feedback. I changed this to use the original node (only when dragging between 2 grids - see #1102 - or when dragging the toolbar item away ) and found jqueryui WILL always remove the helper (after we're called) unless some flag is set (forgot name now), which I don't have control over as a lib... so I would have to clone the helper instead, but then you would loose any function you might have set (like 1102) on the helper.
So unless I can prevent helper from being removed AND I know you want me to use the helper vs the original node copy, it's hard to tell. Maybe there is a callback I could have to let you give me the HTML you want me to insert (kinda like the helper you create but could be different as well.

**Comment by drzraf** [comment]
Any solution
- allowing `newWidget` to define the **final** markup of the widget
- while providing knowledge of original widget

will do it (_my project is in on hold until gridstack.js offer this flexibility_ :))

**Comment by adumesny** [comment]
feel free to offer a solution in the typescript branch (which will move to develop as soon as 2.0 is out - not going back to old JS code) and/or donate $ to help.

**Comment by DevHachi** [comment]
Any progress on that?
I would really like to have this feature as well. :)

**Comment by adumesny** [comment]
while this lib is free, you guys are both capable of donating $ to move this feature along... this isn't something trivial and I have very limited spare time to work on this lib.
What is it worth to you ?

**Comment by DevHachi** [comment]
Well I found a workaround by remove the current Widget and add my Widget loaded by ajax.

So for me I found a solution.

**Comment by adumesny** [comment]
closing without a sample to reproduce... if you do add one we can re-open.
