### ISSUE TITLE
Can I fix the height of "data-gs-current-height"?

### ISSUE THREAD

**Issue by moonlitnighta** [gridstack/gridstack.js#1092]
## Subject of the issue
Can "data-gs-current-height" remain the same when the top distance of "grid-stack-item" changes?

## Your environment
* version of gridstack.js
* which browser and its version

## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://jsfiddle.net/dweiss/dqyvh6vr/) as a base.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

**Comment by adumesny** [comment]
what are you trying to achieve ? your can set the minimum height using CSS and the maximum height with `data-gs-max-row`, but `data=gs-current-height` will always fluctuate based on content and user drag/resize.

**Comment by moonlitnighta** [comment]
> 您想达到什么目的？您可以使用CSS设置最小高度，使用设置最大高度`data-gs-max-row`，但`data=gs-current-height`始终会根据内容和用户的拖动/调整大小而波动。

Hi！My canvas size is 1200x800px, and I want users to maintain this size no matter how they drag, rather than adaptive size

**Comment by moonlitnighta** [comment]
> 您想达到什么目的？您可以使用CSS设置最小高度，使用设置最大高度`data-gs-max-row`，但`data=gs-current-height`始终会根据内容和用户的拖动/调整大小而波动。

My tool is design software similar to Photoshop. The user can set the canvas size and then can only edit within the set size range

**Comment by moonlitnighta** [comment]
@adumesny I did what you said and it seems to solve my problem，Thank you

**Comment by adumesny** [comment]
just use
`.grid-stack {
  min-height: 800px;
}`
and set your grid options `maxRow` to the right number (each row is `cellHeight` + `verticalMargin` until last one that doesn't have a margin) so 800 / (cellheight * row + (row -1) * margin)

I.e. set your cellHeight to have an exact match based on how many rows you wish to have....

That should solve it. re-open if lib is not working as expected. 
And next time use the slack channel to ask questions so others can benefit
