### ISSUE TITLE
Panels lose functionality when they are moved to a new grid

### ISSUE THREAD

**Issue by Arj4ns** [gridstack/gridstack.js#1102]
## Subject of the issue
Lets say I have 2 grids. Both have the option 'acceptWidgets' set to true. In both grids, I have the panels functioning as buttons. So when you click on one, it fires an event. I have an example included with this post. In the example both panels are set to attach text to the bottom of the example. However, when you move the elements to the other grids, their button functionality no longer works. I do not get any kind of error in the console from this either.

## Your environment
0.55 or w/e the latest version is called
Chrome

## Steps to reproduce
https://jsfiddle.net/7zpwvaky/
1. Press both panels at least once.
2. Move either panel to the others grid.
3. Try to press the panel that was just moved.

## Expected behaviour
When a panel is moved to a different grid, it should continue to function as a button, and add text to the screen.

## Actual behaviour
When a panel is moved to a different grid, it will no longer act like a button. It will not produce any text when pressed

**Comment by adumesny** [comment]
I tried with latest rev (yours were 0.3.0 rev, I updated the bug template to have 0.5.5 and simpler includes) and still seeing this even with actual button children. My guess it that it cones the dom elements so JQ events are lost.
https://jsfiddle.net/adumesny/jtf3axsm/

Might need to track the add/remove event and re-attach stuff you care about for now...

**Comment by adumesny** [comment]
@Arj4ns have you found a solution ?

**Comment by adumesny** [comment]
this is fixed in upcoming 2.0.0 release

**Comment by adumesny** [comment]
fix in upcoming 2.0.0-rc2
