### ISSUE TITLE
How do I get the widget in the "added" method?

### ISSUE THREAD

**Issue by moonlitnighta** [gridstack/gridstack.js#1108]
## Subject of the issue
When dragging the widget to the grid, I want to get the current widget. The second parameter of the "added" method can only get the position and size information of the widget, but not the DOM node.

## Your environment
* version of gridstack.js
* which browser and its version

## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://jsfiddle.net/adumesny/jqhkry7g) as a base.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

**Comment by adumesny** [comment]
the nodes passed in the second param each contain an `.el` which is the dom element. All the info is there.
