### ISSUE TITLE
Any way to set AcceptWidgets programatically?

### ISSUE THREAD

**Issue by Almightyzhir** [gridstack/gridstack.js#1113]
## Subject of the issue
I would like to be able to set a grid's state to acceptwidgets to false once a widget has been put inside it. So it will initially be enabled then disabled by calling a method. So the grid is basically locked. I've checked the documentation and have tried a range of API methods but nothing works. Is there any way to do this?
## Your environment
* version of gridstack.js = 0.6.0
* which browser and its version = Google Chrome 79.0.3945.117

## Steps to reproduce
Just a question

**Comment by adumesny** [comment]
I have not tried this, but looking at typescript doc (regular doc needs updating) looks like it can be a function as well, so you cold return false in your condition. Let me know if that works, else if we need to add an explicit method
```acceptWidgets ? : boolean | string | ((i: number, element: Element) => boolean | string);```

**Comment by adumesny** [comment]
closing as function example works.

**Comment by Almightyzhir** [comment]
Thank you very much, very helpful
