### ISSUE TITLE
Can you change a grid's options dynamically?

### ISSUE THREAD

**Issue by Almightyzhir** [gridstack/gridstack.js#1119]
## Subject of the issue
Is there a way to change a grid's options dynamically after it has been set. For example:
 - A grid will be set to options 1 by .gristack(options1). But after an event i would like to change the options of the grid to options 2. Doing .gridstack(options2) has no effect because it has already been set. 

What i am trying to achieve is the ability to change a grid's options once a widget has been dropped into it. E.g. disabling moving/ no longer accepting widgets/animate etc...

Thank you.

P.S. I would like to say thank you for the previous replies to my questions as they have been a huge help!

**Comment by adumesny** [comment]
there isn't a way to get/set all the options after creation (maybe there should be, though that would require quite a bit of work - similar to what I did for `float()` method I added but for each value, but for now you can access that structure with `grid.opts` and update the values you need changed - as long as it doesn't require a bunch of internal changes and only affect future behaviors you should be fine.

**Comment by adumesny** [comment]
let me know how that worked and what calls you would want after the fact. Maybe those can be added before a more generic `grid.options()` method gets added.

**Comment by Almightyzhir** [comment]
Thank you for the reply, i can indeed access grid.options. 

However i've noticed a problem with what i am trying to achieve.

The grid's I have are dynamically added, however since they all use 1 set of options, E.g. turning acceptWidgets = false will not allow any grid to accept a widget. So i guess the only way to do it is to make sure each grid as their own set of options. Is there a way to dynamically provide a unique set of options to each dynamically added grid?? The amount of grids can vary.

Apologies if i was meant to open up another issue.

**Comment by adumesny** [comment]
not sure why you are dynamically creating a bunch of grids, or did you mean grid-item ?
each will need it's own option copy.
