### ISSUE TITLE
data-gs-current-height does not update after remove widget

### ISSUE THREAD

**Issue by UHaooooo** [gridstack/gridstack.js#1131]
## Subject of the issue
After removing widget, _updateContainerHeight is not triggered causing the data-gs-current-height is not updated.

## Your environment
* gridstack.js 0.6.1
* Google Chrome Version 79.0.3945.130

## Steps to reproduce
Simply removing widget by using removeWidget or removeAll

## Expected behaviour
The data-gs-current-height should be updated.

## Actual behaviour
The data-gs-current-height is not updated. Have to manually trigger grid._updateContainerHeight()

**Comment by adumesny** [comment]
@UHaooooo I'm not able to see that bug in our demos. Try https://gridstackjs.com/demo/column.html and click on the X which calls removeWidget() and noticed the grid will shrink.

please create reproducible example (use https://jsfiddle.net/adumesny/jqhkry7g) as a base.

**Comment by adumesny** [comment]
closing due to lack of response,
