### ISSUE TITLE
0.6.2 / oneColumnMode / error width

### ISSUE THREAD

**Issue by leorigaudeau** [gridstack/gridstack.js#1132]
## Subject of the issue
in oneColumnMode the width is incorrect since 0.6.2
each div should fill the entire space in width

## Your environment
* 0.6.2

## Steps to reproduce
just reduce the browser size (oneColumnMode) to see the problem
https://gridstackjs.com/

![2020-02-05_10h41_27](https://user-images.githubusercontent.com/33526057/73830282-b1e70d80-4804-11ea-9b51-9c9a429427fe.png)

**Comment by adumesny** [comment]
thanks, I can see that in the homepage. Funny because both samples I've been using while working on this work fine https://gridstackjs.com/demo/responsive.html and https://gridstackjs.com/demo/column.html

**Comment by adumesny** [comment]
fixed in next release. webpage demos are ok again.
