### ISSUE TITLE
Dragging broken with grid height = 100%

### ISSUE THREAD

**Issue by pjc0247** [gridstack/gridstack.js#1167]
## Subject of the issue
Dragging threshold is too sensitive. When I moved 1~2 pixels, the object changes its position.

## Your environment
1.0.0 and Chrome

## Steps to reproduce
I'm trying to create a reproducible demo. This only appears on my project so far.

## Actual behaviour
![2](https://user-images.githubusercontent.com/1961216/75304491-ba23ed00-5886-11ea-9af4-d28c5ed3d771.gif)

**Comment by adumesny** [comment]
I have not seen that. please try to replicate in a jsfidle example, or make a code fix review I could take a look. thanks.

**Comment by pjc0247** [comment]
@adumesny 
Please check it,
https://pjc0247.github.io/bugtest/index.html

I found that below code makes the mess.
```
 .grid-stack {
height:100% !important;
}
```

**Comment by adumesny** [comment]
I know the grid likes to grow/shrink as items are moved around, so forcing to 100% (or even maybe a fix height) might throw things off... you should do that on a container div (that could scroll or not) if want that.

**Comment by pjc0247** [comment]
@adumesny

Got it,
However, without `height 100%`, recognition area is pretty small and limited. 
Dragging item like below won't be work.

![image](https://user-images.githubusercontent.com/1961216/75406272-6cc18180-5953-11ea-9b37-2f79ae2c8fb4.png)

**Comment by adumesny** [comment]
sure does - just have `GridStack.init({float=true})` option

**Comment by pjc0247** [comment]
@adumesny Ah sry, but I expected to be stacked not a floating.

![image](https://user-images.githubusercontent.com/1961216/75407011-4d2b5880-5955-11ea-921c-e90587a58a77.png)

**Comment by adumesny** [comment]
I'm confused - you expect to be able to drag the item anywhere, but you want it to snap to the top ? the dropshadow will show where it will go, while the dragging element can go anywhere. you can control placement anywhere with float=true;

**Comment by adumesny** [comment]
closing due to confusing wants and no sample.
