### ISSUE TITLE
empty cell stylization

### ISSUE THREAD

**Issue by ferretwithaberet** [gridstack/gridstack.js#1168]
I want to suggest the addition of more events, few ideeas:

'dragstop' - This is not new, but (at least in my opinion) the event.target should have the new position, not the old one.

'emptycellclick' - This will trigger when the user clicks on an empty cell, the event will contain the X and Y coordinate of the cell.

Also, it would be nice to be able to stylize the empty cells, atm I can do it with a clever background composed of gradients, but that should be easier to do in my opinion. I'd love to be able to add a '+' sign on the empty cells, which onclick would create a new 1x1 grid element.

**Comment by adumesny** [comment]
I think your first item 'dragstop' is related to #932 

as for the empty cell click you could just add a click event on '.grid-stack' element yourself I believe. You can event ask `grid.getCellFromPixel()` which should be empty (as the cell **should** handle the click and prevent propagation up). 

Styling empty cell would be hard (new feature) as we HAVE NO empty placeholder per say. Someone else asked about showing grid lines, which is similar. Unlikely to happen unless you want to add this code.

please post you gradient code for others too see ?

**Comment by RadoiAndrei** [comment]
@adumesny Im trying to do it with the .getCellFromPixel and ,isAreaEmpty now. I want to ask if it is possible to tell the grid to stay at the maximum number of rows, as I need the user to be able to click on any empty cell of the grid. I searched through the docs, but I found nothing.

**Comment by adumesny** [comment]
see my comment on the other feature request... I think a `minRow` might be easier to implement, which might be useful to have to prevent grid from collapsing to 0 as well.

**Comment by RadoiAndrei** [comment]
```css
.grid-wrapper::after {
    --grid-lines-color: rgba(0, 0, 0, .7);
    content: "";
    pointer-events: none;
    background-image:
        linear-gradient(90deg, var(--grid-lines-color), transparent 1px),
        linear-gradient(90deg, transparent calc(100% - 1px), var(--grid-lines-color)),
        linear-gradient(var(--grid-lines-color), transparent 1px),
        linear-gradient(transparent calc(100% - 1px), var(--grid-lines-color) 100%);
    background-size: calc(100% / 12) calc(100% / 12);
    width: 100%;
    height: 100%;
    position: absolute;
    top: 0;
    left: 0;
}
```
I will leave my method of adding the grid lines here too, for others to see. Replace the 12 in calc(100% / 12) with the number of rows/columns you have.

**Comment by adumesny** [comment]
moving this to dup of #662 as related (3rd part - next time file a bug for each issue please!)
