### ISSUE TITLE
Option to set the number of grid rows

### ISSUE THREAD

**Issue by RadoiAndrei** [gridstack/gridstack.js#1172]
We got `column` to set the number of columns, but we do nt have `row` to set the number of rows?
I want a grid with a fixed amount of columns and rows, if I do not have 12 rows, it fucks my whole grid.
**If I have 12 rows**
![image](https://user-images.githubusercontent.com/46427158/75445700-a05dd500-596e-11ea-995f-3114566a2fbb.png)
**If I do not have 12 rows**
![image](https://user-images.githubusercontent.com/46427158/75445746-b23f7800-596e-11ea-8b2e-c93877714bcf.png)

I might try to add it myself later today and will do a pull request. At the moment, I just made the getRow function return 12. 😂

**Comment by adumesny** [comment]
read https://github.com/gridstack/gridstack.js#change-grid-columns is you want something other than 12 columns - that part works,

as for a fix number of *rows* that would be a new feature that is NOT easy to add as you would need to implement a swap feature when dragging items around. Rows are automatically added/removed as needed, with vertical scroll bar in most containers, and top gravity by default. the best you can do that now is set a maxRow but even then things get complicated when you get full... you can set a CSS min height, but that doesn't create extra empty rows either.

**Comment by adumesny** [comment]
I suppose we could have a `minRow` attribute which may not be hard to implement and fix `_updateContainerHeight()` to use it.

**Comment by RadoiAndrei** [comment]
Those lines are made out of linear gradients as a background

**Comment by adumesny** [comment]
yeah, you want to hire me ? :) 
Hint: there is a donation link on the site. I'm doing this on my spare time outside of my day job...

**Comment by RadoiAndrei** [comment]
I am almost 19 years old, there's no chance I will be the one hiring you. I literally want to try to fix that height issue, so I can fix my work project. 😂

**Comment by adumesny** [comment]
my hint 2 msg above should be all you need. use the non min files (clone and look at the demo/ sample) to strep through the code.

**Comment by RadoiAndrei** [comment]
```js
  GridStack.prototype._updateContainerHeight = function() {
    if (this.engine._batchMode) { return; }
    var row;
    if (!this.opts.minRow || this.opts.minRow < this.engine.getRow()) {
      row = this.engine.getRow();
    } else {
      row = this.opts.minRow;
    }
    // check for css min height. Each row is cellHeight + verticalMargin, until last one which has no margin below
    var cssMinHeight = parseInt(this.$el.css('min-height'));
    if (cssMinHeight > 0) {
      var verticalMargin = this.opts.verticalMargin;
      var minRow =  Math.round((cssMinHeight + verticalMargin) / (this.cellHeight() + verticalMargin));
      if (row < minRow) {
        row = minRow;
      }
    }
    this.$el.attr('data-gs-current-row', row);
    if (!this.opts.cellHeight) {
      return ;
    }
    if (!this.opts.verticalMargin) {
      this.$el.css('height', (row * (this.opts.cellHeight)) + this.opts.cellHeightUnit);
    } else if (this.opts.cellHeightUnit === this.opts.verticalMarginUnit) {
      this.$el.css('height', (row * (this.opts.cellHeight + this.opts.verticalMargin) -
        this.opts.verticalMargin) + this.opts.cellHeightUnit);
    } else {
      this.$el.css('height', 'calc(' + ((row * (this.opts.cellHeight)) + this.opts.cellHeightUnit) +
        ' + ' + ((row * (this.opts.verticalMargin - 1)) + this.opts.verticalMarginUnit) + ')');
    }
  };```
As well as adding it to the engine and to the GridStack opts. Ty for the info.

**Comment by adumesny** [comment]
post a code review so I can take a look, an make sure to test all the samples and combinations. thanks

**Comment by RadoiAndrei** [comment]
I need contributor role, right?

**Comment by adumesny** [comment]
create a github fork, make your changes in the default develop branch, submit to your repo, then you can use github to create a code review.

**Comment by RadoiAndrei** [comment]
As a quick question:
What would this break?
```js
  GridStackEngine.prototype.getRow = function() {
    const row = this.nodes.reduce(function(memo, n) { return Math.max(memo, n.y + n.height); }, 0);
    if (this.minRow > row) return this.minRow;
    else return row;
  };
```

**Comment by adumesny** [comment]
in next release, thanks!
