### ISSUE TITLE
Issue with addWidget x=undefined legacy API

### ISSUE THREAD

**Issue by antoineluong** [gridstack/gridstack.js#1177]
## Subject of the issue
Calling `addWidget` with the legacy API does not work correctly if the `x` parameter is undefined.
Using the new API solves the issue.

## Your environment
* GridStack 0.6.4
* Firefox 68

## Steps to reproduce
https://jsfiddle.net/bvqj9whp/

## Expected behaviour
Height and width of the widget set to the values passed.

## Actual behaviour
Height and width of the widget set to 1.

**Comment by adumesny** [comment]
to be honest I've been thinking of taking the legacy one out - it's a pain and ugly to support in upcoming Typescript conversion (you need multiple signature and a single implementation similar to the kludge js version) and don't know why it was created in the first place. I mean 7+ params!!!
and doesn't support setting all properties anyway.

**Comment by antoineluong** [comment]
OK thanks, that would make sense. Anyways, it's just an inconvenience that could occur after a migration from a version < 0.5.2 and is easily solved by using the new API.

**Comment by adumesny** [comment]
will take out in 2.x
