### ISSUE TITLE
disableOneColumnMode: true causes massive lag

### ISSUE THREAD

**Issue by RadoiAndrei** [gridstack/gridstack.js#1180]
## Subject of the issue
disableOneColumnMode: true causes massive lag. I was wondering why my grid is lagging when I move elements, apparently it is because of the `disableOneColumnMode` being set to `true`. It works flawlessly when I remove that option.

## Your environment
Newest Gridstack.js
Brave Version 1.4.95 Chromium: 80.0.3987.122 (Official Build) (64-bit)

## Steps to reproduce
1. Make a grid.
2. Set it's `disableOneColumnMode` to `true`.
3. Try to move an item in the grid.

## Expected behaviour
Smooth not laggy.

## Actual behaviour
Laggy.

**Comment by RadoiAndrei** [comment]
I really dont know why, it was laggy, I tried removing `disableOneColumnMode`, adding it back, removing it again. It seemed that  `disableOneColumnMode` was the problem, but somehow now when I am testing, it works ok.

**Comment by adumesny** [comment]
I've seen this problem in Chrome occasionally when debugging... I'm thinking it may have to do with 
`$(window).resize(this.onResizeHandler);` not being throttled, but then again the handler is pretty efficient at doing nothing really (setColumn() with same value returns right away), so maybe not...

```js
private onResizeHandler() {
    if (this.isAutoCellHeight) {
      Utils.throttle(() => { this.cellHeight(this.cellWidth(), false)}, 100);
    }

    if (this.opts.staticGrid) { return; }

    if (!this.opts.disableOneColumnMode &&
      (window.innerWidth || document.documentElement.clientWidth || document.body.clientWidth) <= this.opts.minWidth) {
      if (this.oneColumnMode) {  return; }
      this.oneColumnMode = true;
      this.column(1);
    } else {
      if (!this.oneColumnMode) { return; }
      this.oneColumnMode = false;
      this.column(this._prevColumn);
    }
  }
```

**Comment by RadoiAndrei** [comment]
I love how my fix works, it was the only major thing I needed to implement in Gridstack so I can use it for my work project. As of this issue, I may need to learn more javascript and understand the Gridstack code better if I want to fix it. If I find anything i will open a new issue or comment on this one, or if I can fix it, I will do a PR.

**Comment by adumesny** [comment]
new bug/PR unless it's this slowdown issue.

**Comment by RadoiAndrei** [comment]
Seems to be because of chrome's caching or something. If you get redirected to the page with the grid, it is laggy, if you normal refresh the page it will still be laggy, but if you hard refresh, it will work smoothly.

**Comment by adumesny** [comment]
can you reproduce this in the sample apps ? would be good to track it down to the issue (sounds like not related to disableOneColumnMode you posted in the subject)

**Comment by RadoiAndrei** [comment]
I found out what was causing the lag for me, my laptop is switching to battery saver sometimes, and I was working with it on battery saver for a lot of time...
