### ISSUE TITLE
Locked widgets are still moveable by other widgets

### ISSUE THREAD

**Issue by ritox842** [gridstack/gridstack.js#1181]
## Subject of the issue
When setting widgets into a locked mode and adding new widgets above it the widgets are been pushed down including the locked widgets. 

## Your environment
* 1.1.0 (was 0.5.3)
* Chrome 80.0.3987.122

## Steps to reproduce
I've added a locked widget. Adding new widgets above it will eventually push the locked widget down.
https://jsfiddle.net/ritox/f5w8beyt/7/
## Expected behaviour
A locked widget should never move under no circumstances. It should hold it's position and new widgets the collide with it should be put below it

## Actual behaviour
New widgets push the locked widget down.

**Comment by adumesny** [comment]
thank you for submitting a simple test case. Now we can take a look.

**Comment by ritox842** [comment]
@adumesny 
Can you please update about this issue?

**Comment by adumesny** [comment]
fixed in next release.

**Comment by ritox842** [comment]
Thanks ! :)
