### ISSUE TITLE
Mouse position issues when setting number of columns besides 1 or 12

### ISSUE THREAD

**Issue by bynormous** [gridstack/gridstack.js#1189]
## Subject of the issue
If you set # of columns to anything but 12 or 1 moving widgets or scaling them doesn't match the mouse position. It happens on the live column demo page: https://gridstackjs.com/demo/column.html and also when testing locally.

## Your environment
* gridstack.js rev 1.1.0
* mac Chrome 80.0.3987.132, Safari 13.0.5

## Steps to reproduce
https://gridstackjs.com/demo/column.html -- click on 3 Column button and try either dragging or resizing a widget with your mouse.

## Expected behaviour
Dragging and reszing widget should follow mouse position exactly. Also I never used gridstack before but I also expected the columns to fill the width of the parent container. 

## Actual behaviour
 The mouse position and location of where gridstack thinks it is will be way off when dragging/reszing.

**Comment by awjae** [comment]
There is an error in console
"https://gridstackjs.com/dist/gridstack-extra.css net::ERR_ABORTED 404"

In local, If you built it properly, you should be fine.
1.`npm install`
2.`npm run build`
Then, "../dist/gridstack-extra.css" file will be exist.

But, page:  'https://gridstackjs.com/demo/column.html' It didn't build properly.

**Comment by adumesny** [comment]
oops, problem copy/pasting from dev branch... fixing it now. thanks!
