### ISSUE TITLE
jQuery conflict

### ISSUE THREAD

**Issue by icemouton** [gridstack/gridstack.js#1191]
Including gridstack >= 1.0 in our app which already has jquery causes the jquery object to behave in a weird way.

I've seen this happen with other libs who had to use jquery in "compatibility/no conflict" mode.

I've tested and with the old versions everything works fine.

Commenting out the inclusion of gridstack.all.js fixes my problem.

It's not incredibly relevant but we are using jQuery v3.2.0 and jquery-ui 1.12.1

We get TypeError when using jquery ex:
```
jquery.min.js:2 Uncaught TypeError: $(...).dropify is not a function
```

**Comment by adumesny** [comment]
so 1.x `gridtstack.all.js` now bundles the latest jquery (3.4.1) and a trimmed jquery-ui (1.12.1 with only drag/drop/resize about 1/5th the size). IFF you app already brings those (and older versions) and you don't want to rely on ours then include `gridstack.min.js` + `gridstack.jQueryUI.js` and you should be fine.

all.js is to hide the fact we are still jquery dependent for now.
I guess I need to spell that out in the doc better while we transition...
