### ISSUE TITLE
push Forks back to main gridstack repo

### ISSUE THREAD

**Issue by adumesny** [gridstack/gridstack.js#1194]
Hello, 
you are getting pinged because you have forked gridstack.js

You may not have noticed but the main branch is active, had many releases and hundreds of commits since you likely branched. I would like to ask for the community to contribute back any fixes/changes you may have done.

1. use the latest build - it may have already fixed what you needed
2. if you have local changes, please consider doing a PR with those changes for other to benefit
3. if changes are too specific, consider patching the official lib instead of forking (see https://github.com/gridstack/gridstack.js#extend-library)

Noteworthy changes (and many many more)
* v0.5.x **lodash removal** (450k), **minimal jquery-ui.js** (55k vs 248k)
* v0.6.x huge responsive improvements with implementation of `setColumn(N)` and oneColumnMode options. Also much fewer unnecessary `change` callbacks
* v1.x jquery was removed from the API and external dependencies (you can still use if you wish)

upcoming... converting to Typescript cleanup and looking at native HTML5 drag&drop. I could use some help!

sorry for the wide reach - wasn't sure best way to do this. If you have any questions please ping away... thank you!

-Alain

UPDATE: I added all 950 people then deleted them so hopefully you won't get bombarded with all replies unless you choose to track this issue. Hopefully the initial ping go out. Sorry if too many initial ones..

**Comment by adumesny** [comment]
@tsijercic1 @goofybnu @hacklboro @vaibhavghevde @myml @EduTicianelli @perpetualtraveler @Evotionce @cdaria @damianpolak @NetBarDJ @aniuniugege @Girish022 @toptanayse @worthapenny @vikasrana87 @xhwyli @CptGuo @hiteck88 @ramy-ahmed @kwanchai03 @pananat @morley42 @msantelices @meyruiz @gaollard-feKit @sfigueroam88 @rc1021 @kisshua @Autoflow @dohuta @Ahmett65 @amon-italtel @cameronrose28 @moralesf1 @koyemanaung @GSBassi @ugurmutlucan15 @DesignsByRay @danymill @suckkay @erdincay @Digital-Brownie @fewbadboy @ulissepress @PerspectiveILM @nikocraft @noonenew @phenomejo @ligoo

**Comment by adumesny** [comment]
@oybekmuzropov @yfro @neon12345 @maxsegovia @wkrea @scottporter @thorstenschiller @saum7800 @stevefabian @iseeu2016 @Rayveni @Tim-MCC @fe-codist @moon4dreams @wzs28150 @traeH-Heart @aedoop @cstodor @Aliraminkarimi @mishrarajesh @jaeil-wiki @gnjo @Animalejourbano @hazdik @hoangmt @viethien @xjx79 @MaxLaska @ZedLiu @laprus @thanhdevapp @td777 @Kosik-Chris @JoshuaDeanEssium @isaaczhengturnkey @goenchan @akash-semlr @codenetw @crazyrex @wemod123 @fedesnieg @tomintex @huangch @dragonxu @guruhkharisma @jsding @topwebstudio @dlineg4 @FrederickChan @andreo-k

**Comment by adumesny** [comment]
@wiiler @pandyarudra @garvank @temo-o @iyerananth @SmallShrimp @whbjob @sociablesasha @mkornel @gooeyideas @wobal @canvs @nws-jstorm @psyafter @yanzhichao2017 @CracKerMe @fmshun @tretapey @tobias-grasse @tianyi2015 @tecte @korakanchan @Jarvis-JunZhu @kodesain @TheCutter @khituras @juandelato @natalan @huyquocmai @forkforever @MicrophoneBen @babakhani @devsubhani @sguti @ajohansson @franckarthur @lambrou @webbieram @ericksonsv @715568923 @kamolpech @heapgood @Ryan-Karanja @AdvancedClimateSystems @eswdevplus @saddam497 @ErgoSphere @Deftwun @Justin-zhang @breezes1

**Comment by adumesny** [comment]
@23creative @mkklab @Ndiithi @pdgramajo @tristanrose @bdphil86 @RafikHaceb @jotauses @janindu3 @mdehaan51 @751754949 @eajoya86 @mjsaims @casgraphic @warhotdog @chenzhiming @tuanthinh137 @JeffYoungL @itvart @bahadrdsr @techmaster-web-frontend @ReseTTim @jasonnguyenvn @Cupid-c @Az1122 @kjw864864 @gyzo @gilupu @AlexanderLoshkarov @blubbll @minhhungit @PratikBali @rafael-trevisan @jerrychu888 @MedicalIT @alc32 @njeudy @00aj99 @naverstay @alephjunio @kmap-io @hari9908 @kofiav @clientlab @alipasakaratas @hepark @kirovas @bistin @abhilashGuru @fabienDaou

**Comment by adumesny** [comment]
@arluismx @yasirersoy @flowerjun @amelojunior @BoschJordi @DnJealt @zhugongmei @ShashankRama @1995navinkumar @BenjaminZekavica @ramyzbeidy @ronan-ezops @IvaRoSoft @squirro @StefanM98 @kongotron @GerHobbelt @flyingliang @farruhmirisoev @vikasrana1987 @kim1124 @aibao @datapharmer @songzcn @bashmohandes @vqquoc @mithublue @JamesXia23 @SMwika @rayxcl @drappier-charles @SnowHot @blueti1007 @giammarcovergara @LEEVE @Fusyon @Basovich @kotovden @lancetipton @Nyrris @joelvandal @eity0323 @mwz1991 @mikalv @Volem @MariApps-PAL @anjanasilva @arcameli @scitechno @IanWold

**Comment by adumesny** [comment]
@justcfx2u @trevorgreenleaf @oromand @DraugDev @devenc @ArendJan @Tenderfield @sergey-spivakov @pringgojs @hoeni @gorobey @joegr @doctorcode-co @avlasof @plentymarkets @Owlbertz @netkoala @FilipeCavalcante @dysenre @azzahrah @fengweijp @correaecastro @bipin244 @xia325 @ws-gui @ws-development @ws-js @ws-os @Worklio @Web-Life @YahyaaTurkmen @js-mk @reinaris @suchithmahadi @LXiong @MONDOWO @omidnasri @Denakol @AdventurerDesu @tangposmarvin @hamzahanafi11 @kumarnitz90 @myangel26 @TruongTuyen @kefir266 @ibrahimab @Erbolking @pvlamkhtn @dswitzer @1297947244

**Comment by adumesny** [comment]
@roborto444 @kidmam @Jaysonm @ik9999 @ColonelChow @fekkyDev @akatopaz @shivagurubalaji @umanda @foxytrail @kingsgobi @chenkovsky @karayakar @Giologic @smetron @thsunmy @andre-carvalho @mnlmartinez @nulen @Navpreet2289 @mikeliu1103 @benilacs @Mandox1 @mrcodings @PentaHelix @rwstoneback @kimhuy09 @medhassen @daniel100097 @michaelmruta @eli007s @nkhr7 @overload08 @mcmastermind @silverphoenix1110 @cringha @SavyParchman @lloopp-dev @poovarasanvasudevan @vadus1 @WebPro9369 @pedrumJSAS @Beatons @brendonboshell @bogazci @hulygun @puma90 @efx @annketu @gladovsky

**Comment by adumesny** [comment]
@petegibbins @HouXingYi @luyonglie @tcs-devel @lsivakumar @NANDAWEN @elyo66 @luckylooke @bh86 @jeoy @Srikanththyagarajan @hishamjaved @unregister @silverwind @edharmowongso @jungervin @NowcomCorporation @darshan047 @492580195 @veselfil @yuankl @adumesny @jaysidri @jnorthr @pradipkachhadiya @babyisun @hunglevan @yhtsnda @dhagan @amandacatraca @carmen-tang @githubakash007 @waqashaneef @Smilefounder @mindnervestech @jongacnik @Wkbaf @stalniy @telecomsoftware @serenity-r @darknessitachi @fabianvelizok @slammens @kimuraz @netzzwerg @jonapgar @ash24mish @trevisanweb @StetHD @ciprianmiclaus

**Comment by adumesny** [comment]
@andrewyoung918 @ruffiem @gracelinmumu @yimseknyCorarl @ninjakimal @lettyterres @jacob182 @umesh53 @pange123 @danilomilano @vitfri @airow @vigor-vlad @won21kr @belarfaoui-zakaria @yusufozturk @kennethliow @hypervalley @seb-legat @sunkev @askew- @dgdoblebe @itdavidhan @daoos @BeLPHeX @tsugawa @jvdanker @tt-52101 @ratanasoth @stevenkword @amar71094 @DonnchaC @axethrower @RedooNetworks @lixun910 @tacocat @erikbartlow @Maloperro @AndreCalabrez @PPMac @hcxiong @txd159 @lincolnpahwa @michaelonubogu @AntonioFerrete @Weasle @romeropixel @RobertoBiundo @dennisniederrainer @danniss

**Comment by adumesny** [comment]
@intellihr @vbinithyanandamv @adrianbzt @cobantu @jessehallam @BillTheBest @m0nfils @madisonyocum @JonasGutermuth @danyn @nnarasim @Speedriser @sujith84 @BillyGeat @izhangh @Midaxo @ouyuwo @olaszman @Frontenda @grotup @magestein @tui2tone @DarthSeppius @Schad0001 @gjavi1 @my-instantcms @tcuongtran @CMLL @resfront @Manoj-Roy @saidurwd @jpotth @crossbit @JaroslavHolan @EliZoff @rodo79 @xuanhoang90 @webmalta @MikiSayaka @hairyheron @gabouh @smetronic @cycold @gaoxuemei @KaarloosT @cube3power @gtryonp @phainv @SteelBurgher @epelc

**Comment by adumesny** [comment]
@peterzero @katastrofix @iamstormnet @Lenoiche @elenys @omidkh68 @MateuszKosek @ss34nirala34 @phpip @xlongtang @ericklima88 @ScherbakovDmitry @yepisode @adityarar @rmwever @Sven0 @bytelayer @fdrcc @xtwoend @nelsondesign @nikunjit101 @GreenPDFPaper @thandonguocmo2020 @Uolt @naveenamruth @hahacoo @sthuck @H3ld3rM3 @leaderup @jiufengdadi @astepin @kedomonzter @lizhengbo @Yueyue07 @poristo @siahr @chrisballen @Mijago @bhatmonica @srdjanmitrovic @darksider4all @dharmeshkotadiya @hiepnt93 @yatab @lpyt @azkfrm @madeITBelgium @barryceelen @punkrockio @KillerDesigner

**Comment by adumesny** [comment]
@shaharkazaz @gunjankothari @GuiAlmeida @vasanthb66 @LethOsias @ARCADISCFITS @KavenWork @sfgxuan @flying706 @emcconnell @harish511 @FinstererFred @DotNetInAction @wuyinxing @soumyadip001 @nmaurice-ts @simha95 @Igorbrands @nikcub @theInternauts @ricebeans @griphi @wenchuizyoo @redstubble @iamwelk @MobileD2 @vijeeshr @corbane @raindropco @elibawa @auswm85 @Perde1989 @merkuriospam @huiyikang @CTPlayer @hmatsuyama @edward01 @nora55974 @tophermade @Umbakrail @bilal-hanif @rlugojr @toddler4372 @joppx25 @kverawat @azharshaukat @igoralves1 @roqeem @elmiraK82 @jhonnymakis

**Comment by adumesny** [comment]
@peombwa @PascalSenn @mysky621 @wushuang5112 @palpatine1991 @Janatbek @dragon788 @xiwc @jaapz @many360 @kertonandrew @BalajiRamachandran @sanjitbhattacharjee @realronchi @JoanVt @justfixit @jacevedo @shulamyt @powerocean @pro-mik @aletorrado @fariasf @swongwc3 @thagenbeek @windyao @monkeymonk @judy-zz @stevecooperorg @eagoo @ashishact @rmulder @defc0n1 @JAW-DROP @bangnaga @flocondetoile @umaid7 @deril6 @Voxmundi @wallb @sjchoi1982 @mixinix @arhik @zsunventuretech @blu94 @iongroup @DavidKDeutsch @ndon @bZez @jbrowning @gs-psaraswathi

**Comment by RadoiAndrei** [comment]
I'd suggest rewritting the engine to use the CSS grid, depending on the implementation, it may be faster than doing the grid in js.

**Comment by adumesny** [comment]
@RSivakov @tanhuynh2000 @jfct @krema @huima80 @pmoradei @Empyrian-Art-Forms @e050110 @radiolips @thibaultboursier @emandi @MatthieuPoullin @jjykh @highread @codelounge @nulle @ltrowan @jnace-pmap @jippi @MargoJunker @RasmusTG @IIaJIeHo @joybwang @fheinze @umesh-naik @alexff91 @AYapejian @andrewr88 @litenup @disruptiveadvertising @suxuekun @edudioniz @itxd @remytesta @mstred @McQuinTrix @MartinMoizard @fationyyk @jitheshgopan @renganathan @wjfwxf @pkdevboxy @KarthiTrichy20 @dcfrancisco @parfumix @JoryUK @LomoSoft @VNBrimer @florrin @yulisys

**Comment by adumesny** [comment]
@rafasashi @enreeco @livilco @CrossLead @dandehavilland @lenardg @ansarbek @caoyuanlianni @ptgiang56 @jlowcs @kpheasey @juwilliams @zibix @aribowobob @zspitzer @mmrose @marcodejongh @mnjstwins @ManigandanS @redabakr @thanos @uedev @missing1984 @gitfran @nstr @galdiolo @azhikodan @eugene-palacios @kdietrich @indigo0086 @AndreaMorone @chardy @mctata @pkdevbox @GuannanMeng @pavurya @jalipert @timwis @greatdansby @neridonk @heidarymr @zhaoheng @ScriptorTec @yash1 @billysmt @bramwijns @andemx @DalianDragon @speedooo @swiggins

**Comment by adumesny** [comment]
@j-woods @prakulgupta @nusrettr @AdilSarwarNU @mechanicious @ryan-shaw @Pravinda @bublik007 @cryptixcoder @randoum @kenfemus @deechicago @h-nazzal @hypnoce @derekm @JQueryCollection @sascha2015 @sangkyunyoon @r4ccoon @mikehaas763 @web-work @artesanus @Yerhabe @jinavshah @Eugene-Murray @OsvaldoJ @paullindquist @dighl @msoftware @shrenikp @sebastianchill @Ruoxixi @siqueries @ashwinrayaprolu1984 @sliberali @mochu329 @bharatpatil @lukeed @eimihar @jzxyouok @umarmughal @miguelmaquino @ukris @landsurveyorsunited @Tropicalista @namerci @benjie-collab @coterfield @Swiftwork @iamedu

**Comment by adumesny** [comment]
@arun99178 @slauyama @b4thestorm @skiman @mautematico @shermax @martynsmall @FreshXOpenSource @wprelic @hugovm @wmak @Fuseit @maximderbin @alangunning @alberto-alonso @fiddler @tobiaskl88 @yubrajpokharel @lopezcjf @Ryan-PEK @abologna-r7 @jochenstu @hartez @rosspi @SilverFox8588 @hiteshaaecor @PierreReliquet @mgwidmann @lorenzopub @alroco @keyzf @coreix @Skefill @indriemarius @acadamicprojects @A973C @EladBezalel @massimiliano76 @niksaint @nonagon-io @marciocamello @benjjy @xulong2005 @sbgreene1307 @enrichthenet @cfwin @jonatasjj @thstarshine @kobea132 @CN-Sean

**Comment by adumesny** [comment]
@nitin41 @strongholder @enslee @Perkosrak @ldacruz @lodev09 @nathanjmorton @yellowelise @BenK22 @crashnick16 @mvecbralis @rakeshmakam @janiilmari @cloozis @zachshallbetter @jcborras @zhangbg @oldfu @mickelfeng @mrzhang @dj31416 @smadalin @djass @vtnplus @brunofcs @jacknm @renebrain @JavedAhmad @illia1 @kenuan @choquo @ishields @qaisarirfan @adon988 @luisbrito @Sympho @Roverok @atteeela @carabina @yashiel

**Comment by blubbll** [comment]
Ugh, so many notifications

**Comment by yusufozturk** [comment]
@adumesny Thanks for all the effort.

**Comment by adumesny** [comment]
very sad... over 950 people ping and less than a handful of feedback (ok I have 5 fingers or each hand). Geeeh.... 👎

**Comment by RadoiAndrei** [comment]
> very sad... over 950 people ping and less than a handful of feedback (ok I have 5 fingers or each hand). Geeeh.... 👎

I think most people came here, did one thing, PRed it so they can continue their main project, and then they left.

**Comment by KillerDesigner** [comment]
Sorry, I received your ping, but had no viable input to ping back. I guess I'm pinging for ping's sake, and so that you don't feel so lonely or unappreciated. Certainly not the case. Please keep up the great work!

**Comment by fiddler** [comment]
I checked my branch from 2015 and it had no commits made at all. Looks like I figured how to get things working without any modifications/fixes after all. Deleted the fork.

Big thanks for all the work here, definitely appreciated! :)

**Comment by jaapz** [comment]
> very sad... over 950 people ping and less than a handful of feedback (ok I have 5 fingers on each hand). Geeeh.... -1

It's only been a few days...

Thanks for the effort, I'll check it out when I have the time

**Comment by Autoflow** [comment]
I only forked for backup reasons. The only thing i changed is adding some css for a 24 column layout.

**Comment by adumesny** [comment]
> I only forked for backup reasons. The only thing i changed is adding some css for a 24 column layout.

@Autoflow I noticed some other project building with the sass file to generate 32 columns layouts, so starting next release I will be including the source sass files again.

**Comment by adumesny** [comment]
if anyone with build/packing expertise can help me with #1243 that would be great!
(in my angular app I also get issues importing 1.x)

**Comment by adumesny** [comment]
well little contribution, and 2.0.0 (typescript version with no jquery in main code) is out. closing...
