### ISSUE TITLE
Resizable options no longer working with ember hash helper Object.create(null)

### ISSUE THREAD

**Issue by btecu** [gridstack/gridstack.js#1195]
After upgrading from 0.6.0 to 1.x, looks like setting the resizable options is no longer an option.
Using `yahoo/ember-gridstack`, although I suspect the issue is not with the addon but GridStack itself.

Here is how being invoked:
```
<GridStack @options={{hash resizable=(hash handles="e")}}>
  // items here
</GridStack>
```

Here is GridStack being initialized in the addon:
![image](https://user-images.githubusercontent.com/7517745/76164758-cda54280-6127-11ea-8312-6fe56d4f91d5.png)

The error is not very useful:
![image](https://user-images.githubusercontent.com/7517745/76164684-2c1df100-6127-11ea-8192-8b131325ca7e.png)

If I remove `resizable` it works fine, except I can't change the `handles` value.

**Comment by btecu** [comment]
Disregard, it appears to be an issue with the object being created by the `hash` helper.

**Comment by btecu** [comment]
Appears to work when constructing the `options` in JS and passing them:
![image](https://user-images.githubusercontent.com/7517745/76164850-7b185600-6128-11ea-96b0-512b3180b7b3.png)

However the `hash` just creates an object as you can see in the debug.  Maybe still worth looking into it?

**Comment by adumesny** [comment]
hey can you post a jsfiddle showing the issue (with hash or whatever triggers the issue)? as I don't have access to ember to debug this. weird that it would work in 0.6.x but not 1.x on my side...

cool I see you are using the new `oneColumnModeDomSort` option. Curious how you are using the improved

**Comment by btecu** [comment]
@adumesny not quite a JSFiddle, but close:
https://ember-twiddle.com/b319aa6e99171e6038ce17bd02d0fdc9?openFiles=templates.application%5C.hbs%2C

Notice the error in the console and how removing the `@options/resizable` fixes the issue.

**Comment by btecu** [comment]
@adumesny It appears that the issue is that the passed in object doesn't have `hasOwnProperty`.

**Comment by adumesny** [comment]
hey let me know if you find a fix or idea on how to fix it.
I'm focusing on 2.x now but could do a 1.x release if you have an idea...

**Comment by btecu** [comment]
The issue is here:
https://github.com/gridstack/gridstack.js/blob/78ad209f1084ed7da2abb31d4382302f71cdd8ea/src/gridstack.js#L171

The Ember helper creates an object using `Object.create(null)` therefore not having a prototype. However, the code here relies on the prototype to call `hasOwnProperty`.

There are a few solutions here:
- Check if the value directly: `source.hasOwnProperty(prop)` -> `source[prop] !== undefined`
- Use the Object prototype: `Object.prototype.hasOwnProperty.call(source, prop)`
- Do nothing, seems like an edge case

**Comment by adumesny** [comment]
1) field missing vs being undefined are different though I don't think we depend on `undefined` to set/clear a field.
2) that might be safest fix
3) do you need that fix ? seems weird your object doesn't have a prototype. Should be {} based no ?
