### ISSUE TITLE
Dropped event does not fire

### ISSUE THREAD

**Issue by tupham9506** [gridstack/gridstack.js#1197]
## Subject of the issue
`dropped` event does not fire. I want to know grid position after dropped. I don't want to use `change` event because it fire when resize and dropped.

## Your environment
* version of gridstack.js: gridstack@1.1.0
* which browser and its version: Chrome v80.0

## Steps to reproduce
Please view this demo https://jsfiddle.net/tupham9506/qL8dhe1z/4/
- Step 1: Drag a block.
- Step 2: Drop that block and waiting `dropped` event fire (Console log and Alert with `dropped!!!` message will show)
```
// Listen dropper event
grid.on('dropped', function(event, previousWidget, newWidget) {
  console.log('dropped!!!');
  alert('dropped!!!')
});
```

## Expected behaviour
After I dropped, `dropped` event will fire.

## Actual behaviour
`dropped` event doen't fire.

**Comment by roldeguz** [comment]
I don't think the 'dropped' event will work on your example since it only fires when a widget was dragged out of a grid and dropped into another grid.

If you would like to capture, the 'drop' within the same grid, you can use the dragstop event.

**Comment by adumesny** [comment]
I'm not familiar with the dropped event myself and will need to take a look, but that sounds right.

Not that 'added|removed' event should fire (does in two.html) when moving from one grid to the other, as well as from the outside. Not sure why we have 'dropped' actually...
