### ISSUE TITLE
Where to find gridstack.min.js?

### ISSUE THREAD

**Issue by matthiaswohlmann** [gridstack/gridstack.js#1199]
## Subject of the issue
Hello, 
at the bottom of your Github mainpage, there is a paragraph about JQuery that says that I need gridstack.min.js, gridstack-poly.min.js and gridstack.jQueryUI.min.js when I am already using JQuery UI in my project.
Where do I get those files? Can't find them here on Github...

Thanks,
Matthias

**Comment by adumesny** [comment]
the latest npm images have all the files (ex: https://github.com/gridstack/gridstack.js/releases/tag/v1.1.0) as well as CDN links.
