### ISSUE TITLE
init after destroy(false) doesn't work

### ISSUE THREAD

**Issue by syfgkjasdkn** [gridstack/gridstack.js#1204]
## Subject of the issue

A grid initialised on the DOM left by `grid.destroy(false)` doesn't seem to work: widgets are not draggable.

## Your environment
* version of gridstack.js **1.1.0**
* which browser and its version **Chrome Version 80.0.3987.132 (Official Build) (64-bit)**

## Steps to reproduce

```js
grid = GridStack.init() // works well
grid.destroy(false)
grid = GridStack.init() // widgets are no longer draggable
```

https://jsfiddle.net/n4f2dpv5/

## Expected behaviour

Initialising a new grid (`GridStack.init()`) on the DOM of the destroyed one (`grid.destroy(false)`) should work the same way as initialising a "fresh" grid.

**Comment by adumesny** [comment]
Hey thanks, 
did this ever worked before ? 
I assume this is a valid user case - what are you trying to do ? 
FYI you can disable grid drag/resize by making the grid fixed as well instead of 'destroying it' and re-creating, in case you didn't know.

**Comment by syfgkjasdkn** [comment]
@adumesny Hi!

> did this ever worked before ?

I haven't tried it before.

> I assume this is a valid user case - what are you trying to do ?

I'm trying to use gridstack.js with [phoenix liveview](https://github.com/phoenixframework/phoenix_live_view) through so called [hooks](https://hexdocs.pm/phoenix_live_view/Phoenix.LiveView.html#module-js-interop-and-client-controlled-dom). The only way I have found for it to work so far is to destroy gridstack before update, and then reinit it after liveview patches the widgets in the DOM.

**Comment by adumesny** [comment]
simple possible workaround for now (there might be more issues as I discovered stuff we didn't do during `destroy(false)` is to call `grid.enable();` after you init the second time.

still a bug that it doesn't work out of the box.

**Comment by adumesny** [comment]
fixed in next release.

**Comment by syfgkjasdkn** [comment]
@adumesny thank you!
