### ISSUE TITLE
Dragged items shift down relatively of the mouse pointer when dragging between 2 vertical grids

### ISSUE THREAD

**Issue by btry** [gridstack/gridstack.js#1210]
## Subject of the issue

Hi

Consider that you have 2 gridstacks : the first is on top of the second. If you drag a item from the 2nd grid to the 1st one then the 1st grid will grod to make room for the dragged item. The dragged item moves down and is not under the mouse pointer anymore. 

## Your environment
* gridstack 0.6.0
* Firefox 73.0.1 64 bits (Debian Sid)

## Steps to reproduce

Here is an example: https://jsfiddle.net/wjdhn6uy/

Try to pick the item **content 3** or **content 4** and drop it in the first grid. See how the item captured by the drag and drop moves down when the first grid grows.

## Expected behaviour
The dragged item should stay under the mouse pointer when the source grid (the 2nd) moves down due to the increased height of the first one.

## Actual behaviour
The dragged item moves down relatively of the mouse pointer.

**Comment by adumesny** [comment]
you are using a very old gridstack 0.2.5. Please update to the latest rev and re-open if it still happens.

**Comment by btry** [comment]
Hi

Here us an example forked from the template for issues : https://jsfiddle.net/t4suec3d/

**Comment by adumesny** [comment]
thanks, here's a better tweak (float true, spaced out to see) on it https://jsfiddle.net/adumesny/63c7e4ps/

it appears the drag is relative to the (bottom) grid which gets pushed down when upper grid grows, instead of absolute global position.

Note that we have (known) issues trying to drag items back to bottom grid (can't if float=true of course without a maxRow).

**Comment by btry** [comment]
> Note that we have (known) issues trying to drag items back to bottom grid (can't if float=true of course without a maxRow).

Yes I noticed this also, but this is somewhat workaround-able if the user moves fast the item to the bottom.

**Comment by btry** [comment]
Hi

Issue still there with version 2.2.0

https://jsfiddle.net/moc5v3uy/

**Comment by adumesny** [comment]
updated to v3 html5. behavior is different now.  https://jsfiddle.net/adumesny/63c7e4ps/

**Comment by adumesny** [comment]
closing this issue as fixed in 3.1.3 (follows cursor in v3 Html5) and will open remaining issue.
