### ISSUE TITLE
If I set cellHeight to some vh, only first grid will take vh, rest will use px

### ISSUE THREAD

**Issue by RadoiAndrei** [gridstack/gridstack.js#1217]
## Subject of the issue
If I set `cellHeight` to a vh measure, like `7vh`, only the first grid will be initialized with 7vh, others will use 7px for some reason.

## Your environment
1.1.0 Newest, served from CDN
Brave Version 1.4.96 Chromium: 80.0.3987.132 (Official Build) (64-bit)

## Steps to reproduce
1. Make multiple grids.
2. Gridstack options should contain a vh unit for the `cellHeight` property, like `'7vh'`
3. Initialize them with Gridstack.initAll(options).

## Expected behaviour
All grids should have a height of 84vh.

## Actual behaviour
First grid has a height of 84vh, others have 84px.

**Comment by RadoiAndrei** [comment]
#1218 Should fix it

**Comment by adumesny** [comment]
thank you for the fix!
