### ISSUE TITLE
Addition of a "keepHeightWhileDragging" option for the grid

### ISSUE THREAD

**Issue by RadoiAndrei** [gridstack/gridstack.js#1227]
This will prevent the grid from shrinking while you are dragging an element. I am trying to make an endless dashboard and I find it annoying on how hard it is sometimes to move elements when the grid keeps shrinking and getting bigger. The grid will shrink after you drop the widget back into the grid.

**Comment by adumesny** [comment]
I think you can accomplish that today with the `minRow` attribute which you can adjust based on how many rows you need/have. Also dragging items shouldn't be so hard, and there is already #1094 to improve on that (I have a couple ideas now I looked into the collision code)

**Comment by RadoiAndrei** [comment]
```js
    grid.on('dragstart', () => {
        const originalMinRow = grid.opts.minRow;
        grid.opts.minRow = grid.engine.getRow();
    })

    grid.on('dragstop', () => {
        grid.opts.minRow = 0;
    })
```
this is how i kinda achieved what I wanted, but how would I make the grid keep it's highest point until the `dragstop` event fires?
