### ISSUE TITLE
staticGrid disables one column mode

### ISSUE THREAD

**Issue by pettno** [gridstack/gridstack.js#1229]
## Subject of the issue
staticGrid disables one column mode.

## Your environment
* gridstack.js version 1.1.0
* Chrome

## Steps to reproduce
One column mode is disabled here:
https://jsfiddle.net/ur81se2n/2/
...but should be enabled?

Disable staticGrid like this:
https://jsfiddle.net/ur81se2n/3/
...to enable oneColumnMode.

How do I enable staticGrid AND oneColumnMode?
(it worked in gridstack 0.4.0)

**Comment by adumesny** [comment]
yep, staticgrid prevent user changing, but oneColumn should still work (and calling by code) - will fix that. thanks.

**Comment by adumesny** [comment]
fix in next release.

**Comment by 71GA** [comment]
Static grid still does not behave as it should... https://github.com/gridstack/gridstack.js/issues/1340

**Comment by adumesny** [comment]
@71GA #1340 is NOT about staticGrid (which prevents users drag/resize) but about fixed maxRow=6 and yet you want more rows when in 1 columns! totally different issues...
