### ISSUE TITLE
update() should also take the options object

### ISSUE THREAD

**Issue by jkusa** [gridstack/gridstack.js#1235]
## Subject of the issue

Currently, [update()](https://github.com/gridstack/gridstack.js/tree/develop/doc#updateel-x-y-width-height) only takes a few positional option params. Just like [addWidget()](https://github.com/gridstack/gridstack.js/tree/develop/doc#addwidgetel-options), `update()` should take an options object containing any `item` option.

## Your environment

n/a

## Steps to reproduce

n/a

## Expected behaviour

n/a

## Actual behaviour

n/a

**Comment by adumesny** [comment]
see https://github.com/yahoo/ember-gridstack/pull/62

**Comment by adumesny** [comment]
in upcoming 3.0 release!
