### ISSUE TITLE
Support Direct Element Attributes Updates

### ISSUE THREAD

**Issue by jkusa** [gridstack/gridstack.js#1236]
## Subject of the issue

Currently, after initial render, direct element attribute updates are not kept in sync with the internal gridstack state.

## Your environment
n/a

## Steps to reproduce

1. Create grid with an item with a width of `2`
2. Update the width attribute to `5` via element attribute (`data-gs-width=5`)
3. Manually reposition/drag item
4. Item will then resize back to a with of `2`

## Expected behaviour

Item options can be updated via element attributes

## Actual behaviour

Item options updated via element attributes do not work/stick

**Comment by adumesny** [comment]
I fixed `GridStack.update()` to take all options (more work than I expected) but not sure how I should track external DOM changes to update internal state... is that something you still need and can suggest code ?

**Comment by adumesny** [comment]
closing unless I hear back with code as I don't have bandwidth. thanks
