### ISSUE TITLE
Example on how to use GS alongside jQueryUI? [solved]

### ISSUE THREAD

**Issue by plueschpruem** [gridstack/gridstack.js#1247]
## Subject of the issue
GS and jQueryUI colliding

## Your environment
* latest version of GS and jQueryUI
* latest Chrome on OSX

## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://jsfiddle.net/adumesny/jqhkry7g) as a base.

## Expected behaviour
GS and UI working alongside

## Actual behaviour
Building a WordPress plugin.
Adding GS _after_ the WP internal jQueryUI parts leads to a jQuery error when trying to open a dialog: _Uncaught TypeError: $(...).dialog is not a function…_
Using the latest jQueryUI manually added gives the same error.
Adding GS _before_ UI declares the dialog ok, but when I open it (it's hidden by default), I get another error, this time from GS: _Uncaught TypeError: n.getClientRects is not a function_
I also noticed that the dialog is not modal as declared.

I saw that there is a file names _src/gridstack.jQueryUI.js_ - but I have no cue what it is or how to use it.

EDIT: Tried to include _src/gridstack.js_ instead of the _dist/gridstack_111.js_ makes the UI dialog() work again, but then I don't get any GS drag/drop/resize anymore…

**Comment by plueschpruem** [comment]
OK, solved it myself…
You need to include _gridstack.js_ before jQuery/UI.
And _not_ the crappy/incomplete WordPress version, but a full one (at least that worked for me).
So in your WP-PHP it has to be something like this:
```
wp_enqueue_script('gridstack', <url>/gridstack_111.js);
wp_enqueue_script('jquery');
wp_enqueue_script('jquery-ui', <url>/jquery-ui.min.js);
```

**Comment by adumesny** [comment]
the readme should spell exactly what you need https://github.com/gridstack/gridstack.js#jquery-application

not sure also adding an example, which needs to be found as well, would really help more.

**Comment by plueschpruem** [comment]
Ah crap, I was looking at the /doc/ section of the git.
Thanks!

**Comment by plueschpruem** [comment]
Just tried the "readme way" and it gives me other errors.
tired of searching for now, the .min. files in the readme also don't exist.

**Comment by adumesny** [comment]
> Query Application
We're working on implementing HTML5 drag'n'drop through the plugin system. Right now it is still jquery-ui based. Because of that we are still bundling jquery (3.4.1) + jquery-ui (1.12.1 minimal drag|drop|resize) internally in gridstack.all.js. IFF your app needs to bring it's own version instead, you should instead include gridstack-poly.min.js (optional IE support) + gridstack.min.js + gridstack.jQueryUI.min.js after you import your libs.

I extracted the 1.1.1 zip (content used in npm image) and get
![image](https://user-images.githubusercontent.com/3496166/78053524-93e5e700-7335-11ea-9ece-9695b3e47eb9.png)

am I missing something ?

**Comment by plueschpruem** [comment]
AH alright, I downloaded the git version _gridstack.js-develop_
That just has the non minified files in the src folder.

**Comment by adumesny** [comment]
you must use the npm images (or at least the release .zip folder) as you will be missing the .css and other files required.
