### ISSUE TITLE
[BUG] Demo, "Nested grids demo" is broken.

### ISSUE THREAD

**Issue by andreElrico** [gridstack/gridstack.js#1257]
## Subject of the issue
Demo, "Nested grids demo" is broken.

## Your environment
tested on chome and firefox with the current Demo: "Nested grids demo".

## Steps to reproduce
1. resize 6 (`nested1`) to the right until it spans 3 cols.
2. drag it SLOWLY to `nested2`.
3. at somepoint you will have **TWO** drop placeholders.
4. now drop, when there are 2 placeholders.
5. the old drop placeholder of `nested1` will interfere with the element and destroys the UX.

## Expected behaviour
+ There should only be one "drop here placeholder"
+ "old" Placeholder needs to vanish after it has been established in "nested 2".

## Actual behaviour
its described in `point 4`.

**Comment by adumesny** [comment]
dup of #393 - thank you. yeah it bugs me too...

**Comment by andreElrico** [comment]
sorry overlooked that.
