### ISSUE TITLE
Dragging outside the area shows an error

### ISSUE THREAD

**Issue by cxm3264** [gridstack/gridstack.js#1259]
## Subject of the issue
shows an error

## Your environment
* gridstack.js 1.1.1-dev
* Chrome 80.0.3987.106

## Steps to reproduce
When the number of rows in my grid is 12, I set the grid item data-gs-height="12", and i drag it outside the area, the grid item shows an error, it only occupied one row
you can see this [sample](http://jsrun.net/cjfKp), and drag it to trash area

**Comment by adumesny** [comment]
hey, can you provide a jsfidle example so I can see your code ? 

also your test case shows an error just running:
"adsbygoogle.push() error: Page-level tag does not work inside iframes."

**Comment by adumesny** [comment]
closing due to no info.
