### ISSUE TITLE
package.json missing "main" in v0.2.3

### ISSUE THREAD

**Issue by helfer** [gridstack/gridstack.js#1260]
## Version 0.2.3 broken due to missing "main" field in package.json
The package.json file in version 0.2.3 is missing the "main" property, so it can't be imported. Is there any chance you could publish a 0.2.4 patch version that includes the "main" field?

**Comment by helfer** [comment]
nvm, I see there is already a 0.2.4 that has a `main` field. Not sure how I missed that earlier.

**Comment by adumesny** [comment]
may I ask why you are using a 5 years old version ? (and 19+ releases since then)
