### ISSUE TITLE
"ui-droppable-hover" is triggered by center of draggable block. How to change it to full dimensions?

### ISSUE THREAD

**Issue by kolykhalov** [gridstack/gridstack.js#1264]
## Subject of the issue
Removable is triggered by some center of a block. Gif video [by link ](https://yadi.sk/i/jINN18sfKgiqGg). So when this center crosses the trash div or another grid it triggers "ui-droppable-hover" class in target element. But I want it be triggered by outer boundaries of the draggable block or a mouse pointer holding the block. Otherwise this mechanic is counter intuitive if the target is small like tab or button.

Is it possible to use the whole block dimensions as trigger not just the center?

## Steps to reproduce
just drag and drop package examples

## Actual behaviour
removable is triggered somewhere in the center of the widget

## Expected behaviour
I would like the outer border of the widget to trigger "ui-droppable-hover" or the mouse cursor

**Comment by adumesny** [comment]
hey, I'm not seeing a video, just a still. If i understand you are saying that a dragged div center is used for source , which if your trash div is small target can be counter intuitive ?

using the drag outlines can be problematic (see #1094) as well as you can easily have multiple hits and then you need to figure out the winning one - likely the cause of #393 as well. Mouse pointer is unique and small and could solve these issues, though when placing a block without other blocks, it's nicer to see the outline match where the item will be placed (especially is tighter space).

Anyway, you may want to look at jquery-ui options... I wouldn't be surprised if you couldn't customize that.

**Comment by kolykhalov** [comment]
@adumesny  Hello Alain, thanks for quick reply. Link leads to gif which doesn't have an auto play function, you would have to download it. If that is inconvenient please tell me I will find another hosting. I believe mine is quite secure, so nothing to worry about downloading it.

So you're saying that it's not possible? 

I just want to move block to a tab and make it disappear in grid 1 and appear in grid 2. In my scenario I transfer blocks between grids via tabs, like linux desktops, so I have to drop a block on a small tab on top of the screen, so my user will not understand that a center of the block has to be there and I presume will not understand how to drop it there, that's what I call counter intuitive.

Maybe you can advice me on any other path to go?

**Comment by adumesny** [comment]
yeah I don't want to download 3rd party app (never heard of) for video playing...

all I'm saying is see if jquery-ui draggable have that option - that's what we use internally.

**Comment by kolykhalov** [comment]
That's not an app, that's a gif file, but nevermind you've got the point.

Thanks for your help, I'll look deeper into jquery-ui.
