### ISSUE TITLE
How to move all widgets to one grid?

### ISSUE THREAD

**Issue by songthamtung** [gridstack/gridstack.js#1265]
## Subject of the issue
How to move all widgets to one grid?

## Example
I have 2 grids:
- Grid0
- Grid1

I have a form that adds new widgets to Grid0. I drag some widgets to Grid1.

How might we easily move all the widgets back to Grid0?

## Your environment
* Gridstack 1.1.1
* Chrome Version 81.0.4044.113 (Official Build) (64-bit)

**Comment by adumesny** [comment]
have you tried removing them from one grid and adding them to the other in code ? you'll probably want auto-position unless you expect them to stay at same place (and don't have conflicts).
there isn't a `moveToGrid()` method if that's what you are asking for.

**Comment by songthamtung** [comment]
> have you tried removing them from one grid and adding them to the other in code ? you'll probably want auto-position unless you expect them to stay at same place (and don't have conflicts).
> there isn't a `moveToGrid()` method if that's what you are asking for.

Thanks for your quick response @adumesny 

No, I have not tried removing them from one grid and adding them to the other in code. This would fulfill my purpose though. 

- Which method(s) is this?
- Auto-position is okay with me.

**Comment by adumesny** [comment]
did you bother looking at the doc ? `addWidget()` and `removeWidget()` should do it.
also use slack channel for asking questions, don't just post "bugs"
