### ISSUE TITLE
Resizing smaller beyond a point breaks sizing

### ISSUE THREAD

**Issue by wtf911** [gridstack/gridstack.js#1267]
## Subject of the issue
I'm using the software Shinobi
https://shinobi.video/

When I make my browser my camera feeds will nicely resize and they maintain their aspect ratio/proportions fine until a point. After I've resized the browser window "too small" then the images in iframes inside gridstack dividers breaks. So the mjpeg camera feed instead of the image being resized it then displays full size inside the iframe cutting some of the image off.... where before I made it too small it would refit the entire image to correctly be responsive with resizing and fit the whole image sized to the current frame size.

## Your environment
Using Google Chrome on Windows 10 to view site
gridstack is being used in Shinobi running on my Ubuntu vm

Here is an example:
Showing cam size properly before resizing browser window:
![image](https://user-images.githubusercontent.com/5151430/80895218-78615980-8cb0-11ea-835a-c8a9feac4063.png)

After resizing browser window the camera feed no longer is resized to fit the iframe:
![image](https://user-images.githubusercontent.com/5151430/80895235-8adb9300-8cb0-11ea-8de9-68bea9f4745b.png)

**Comment by adumesny** [comment]
how is this a gridstack lib issue ? sounds like your video feed has issue with div being too small - you're not saying gridstack fails to resize the item manually down. Might want to also be aware of oneColumnMode when going small, and you fail to list what version you're using or have a jsfiddle reproduceable step. reopen if you do and it's lib issue. thanks.

**Comment by wtf911** [comment]
You're right it is not an issue with gridstack as I now see. :) I've been able to determine this only happens when the mode switches from "normal multi column mode" to the "onecolumnmode" that you mentioned. When it switches a piece of added styling gets lost.

https://gitlab.com/Shinobi-Systems/Shinobi/-/blob/dev/web/libs/js/dash2.socketio.js#L475

`liveStreamElement.contents().find("body").append('<style>img{width:100%;height:100%}</style>')`

That section of code around line 475 says if the camera is outputting MJPG then it needs to add that styling to the iframe: `<style>img{width:100%;height:100%}</style>`

I'm not a coder but if I understand it correctly when the width of the browser goes below 768x then the CSS gets switched to the one-column-mode and in doing so the added styling is lost. If I wanted to fix this so whenever the CSS changes it will refresh or "call again the liveStreamElement to add the styling back" could you tell me which file of gridstack I would need to edit?

Thank you!

**Comment by adumesny** [comment]
you should not be editing gridstack. Instead disable oneColumnMode or let show an example where the lib removes an external style you dependent on (shouldn't happen but it does add gridstack-1 or something (you didn't say what rev you are using and that code changed in 0.6.x)
