### ISSUE TITLE
Can´t get it to work with svelte

### ISSUE THREAD

**Issue by benjamin79** [gridstack/gridstack.js#1268]
Using latest gridstack version i get: 

> gridstack_dist_gridstack_all_js__WEBPACK_IMPORTED_MODULE_1___default.a.init is not a function

```
<script>
import GridStack from 'gridstack/dist/gridstack.all.js';
var grid = GridStack.init(); 
grid.addWidget('<div><div class="grid-stack-item-content">Item 1</div></div>', {width: 2});
</script>

<div class="grid-stack"></div>
```

Any idea?

**Comment by adumesny** [comment]
it would help if you could point to a module that works importing that way, this was I can take a look at the difference. I'm not familiar with svelte.

possible dup of #1243
