### ISSUE TITLE
align feedback lines when resizing objects

### ISSUE THREAD

**Issue by leorigaudeau** [gridstack/gridstack.js#1269]
## One proposal feature: Symmetric outline

This feature can make lines appear during drag to help the user to position these elements well aligned. 
Can help for the resize too ?  

We have little step between our size an sometime is not easy to align two element at the same height

## Your environment
We mainly work on chrome, we use gridStack in polymer components

## Expected behaviour

Something like that when placeholder is aligned with the side of another element .

![image](https://user-images.githubusercontent.com/33526057/81167566-b652cc00-8f95-11ea-9a4d-20e82beae768.png)
--
![image](https://user-images.githubusercontent.com/33526057/81167624-d1254080-8f95-11ea-9706-8f99566f9af9.png)

## Actual behaviour
![image](https://user-images.githubusercontent.com/33526057/81167602-c5d21500-8f95-11ea-975f-79a7a33fcdb0.png)

**Comment by adumesny** [comment]
you must have some really small cell height (like <5 pixels) for this to be an issue... unlikely to get added unless someone wants to contribute it.

**Comment by adumesny** [comment]
closing due to age and priorities
