### ISSUE TITLE
mouse drag out of sync with div scale

### ISSUE THREAD

**Issue by hzjux001** [gridstack/gridstack.js#1275]
When I change the target div's SCALE, just like "transform: scale(0.457292) translate(0px, 0px);",the movement or dragging in the gridstack is out of sync with the real mouse movement

**Comment by adumesny** [comment]
you need to create a reproduceable test case if you want us to take a look. look at the jsfiddle template

**Comment by hzjux001** [comment]
Because In many cases we need to zoom the page，
in the example https://gridstackjs.com/demo/advance.html,
I change the style in grid-stack div 
just like 
<div class="grid-stack grid-stack-instance-9799 grid-stack-animate ui-droppable" data-gs-animate="yes" data-gs-current-row="6" style="height: 460px;transform: scale(0.7, 0.7) translate(0px, 0px);">
and when we drag or resize by mouse,
the movement or dragging in the gridstack is out of sync with the real mouse movement

**Comment by hzjux001** [comment]
The same is true even if you put the zoom style on the outer DIV

**Comment by hzjux001** [comment]
Who can help me solve this problem,Please.

**Comment by adumesny** [comment]
browser zooming works just fine, so not sure why you would manually scale the div in code...

if you are such in need of a fix, and don't want to fix it yourself, maybe you should consider donating $ to this effort.

**Comment by hzjux001** [comment]
How can I donate

**Comment by adumesny** [comment]
github page has donate links https://github.com/gridstack/gridstack.js

**Comment by vishaldodiya** [comment]
@adumesny Is there any workaround for this? Like we can calculate position according to scale and pass it to gridstack.

**Comment by adumesny** [comment]
unlikely to get fixed as not a priority and I don't understand the use case why you would scale a div (so many things break when scaling in my experience).

HTML5 drag&drop is a lot worse than the JQ version which seems only off by scale factor relative to parent (0,0)

**Comment by adumesny** [comment]
fixed in next release.

**Comment by adumesny** [comment]
will be in next 9.5 relase.
