### ISSUE TITLE
The 'addWidget' function ignores data attributes

### ISSUE THREAD

**Issue by AlexanderSokolov1** [gridstack/gridstack.js#1276]
## Subject of the issue
The data attributes are ignored during adding new widgets through the `addWidget` function with specified coordinates.

## Your environment
* gridstack version: 1.1.1
* browsers: any

## Steps to reproduce
https://jsfiddle.net/Alexander_Sokolov/tu03kbgv/24/
- initialize the Grid with `column=4`
- prepare the widget HTML with an attribute `data-gs-width="3"`
- use the `addWidget` function to add new widget to the grid container with `x` and `y` coordinates:
`grid.addWidget(htmlElement, 0, 0);`

## Expected behaviour
The widget `width` is initialized from the HTML attribute (like it was in v0.4)

## Actual behaviour
The `data-gs-width` attribute is ignored

**Comment by Wenish** [comment]
Yeah i have the same problem but with `data-gs-min-width="4"`
The grid gets i a really buggy state. the item is width 1 but it displays it as it would be 4. so items overlap.
![bug](https://user-images.githubusercontent.com/18367963/82086812-612e5d00-96ef-11ea-9165-4e8c3affc829.png)

**Comment by adumesny** [comment]
fixed in 1.1.2
