### ISSUE TITLE
Issue when drag and drop from nested grid

### ISSUE THREAD

**Issue by k4st0r42** [gridstack/gridstack.js#1282]
## Subject of the issue
Issue when drag from nested grid

## Your environment
v1.1.2

## Steps to reproduce
https://jsfiddle.net/sx7dga5n/1/

Demo video : https://drive.google.com/open?id=1bOrOqgn41qi3j-F5rDZMrbailXPYAjlf
Try to drag between child and parent
There are an overlap
Bad drop zone
Edit: And I have this error : `Cannot set property 'isOutOfGrid' of undefined`

## Expected behaviour
Drag and drop between child and parent grid

**Comment by k4st0r42** [comment]
I think it is necessary to use the greedy option of jquery ui droppable to resolve that : https://api.jqueryui.com/droppable/#option-greedy

But it impact the collision algorithme too.

**Comment by adumesny** [comment]
hey thank you - dragging between child and parent is not well supported - for one thing it may move a nested item out of the way so you can't drop into - and would need a modifier key to drop in vs move out of the way ?

wonder if at all related to #393 two drop shadows.

**Comment by adumesny** [comment]
dup of #992 and also related to #1009 and #1210 when dragging between 2 V grids. closing
