### ISSUE TITLE
Load grid layout not working

### ISSUE THREAD

**Issue by Rvds1983** [gridstack/gridstack.js#1284]
## Subject of the issue
I'm just getting started with Gridstack, looks awesome!
I think I got the save part down, but the load from the generated JSON just won't work.
Via a load button I call the load function with (for now) a hardcoded JSON string.
The widget's dimensions etc. are not how I saved them.

Basically what i need is when the page is loaded, the widgets are rearranged to the stored JSON value. The function in the docs clears all widgets and then creates new ones. If it's possible it just has to rearrange the current widgets to their stored place and dimensions.

## Your environment
Version 1.1.1
Chrome (latest)

## Steps to reproduce
https://www.smilejet.net/app/js/dashboard-grid/test.html

```js
function loadData() {
  var serializedData = [{ "x": "0", "y": "0", "w": "2", "h": "2", "id": "chart1" },
  { "x": "2", "y": "0", "w": "4", "h": "2", "id": "chart2" },
  { "x": "6", "y": "0", "w": "4", "h": "2", "id": "chart3" },
  { "x": "0", "y": "2", "w": "12", "h": "3", "id": "chart4" }];

  // I remove the "grid.removeAll"
  var data = JSON.parse(serializedData); //Getting the content
  var items = $('.grid-stack').find('.grid-stack-item'); //An item is now a grid-stack-item
  $.each(items, function (key, gridItem) { //Foreach item, i'll set the attributs as saved
    $(gridItem).attr('data-gs-x', data[key].x);
    $(gridItem).attr('data-gs-y', data[key].y);
    $(gridItem).attr('data-gs-width', data[key].width);
    $(gridItem).attr('data-gs-height', data[key].height);
  }, this);
};
```

## Expected behaviour
When click on LOAD button, the current widgets should rearrange to the right positions and dimensions. No delete all widgets and then recreate them like the example.

## Actual behaviour
When clicking on LOAD, something happens but it's not the right position/dimensions.

**Comment by adumesny** [comment]
many issues. 
1) you are looping through your found items, but not checking for id matching (order might be different) 
2) don't update the HTML directly (gridstack has internal info as well) as that will break things. Use `GridStack.update()` **with** `batchUpdate()/commit()` so thing don't update in-between, otherwise you might get temporary collision (might need to reserve sort first).
Note: that placing widget at new location can be tricker if you don't have float=true and things will re-arrange once you commit.

**Comment by adumesny** [comment]
this reminds me I need to update the demo

**Comment by qlibp** [comment]
> many issues.
> 
> 1. you are looping through your found items, but not checking for id matching (order might be different)
> 2. don't update the HTML directly (gridstack has internal info as well) as that will break things. Use `GridStack.update()` **with** `batchUpdate()/commit()` so thing don't update in-between, otherwise you might get temporary collision (might need to reserve sort first).
>    Note: that placing widget at new location can be tricker if you don't have float=true and things will re-arrange once you commit.

@adumesny 
I find it hard to figure out the reason why I can't get my layout render in correctly.
![image](https://user-images.githubusercontent.com/43082379/124732970-50b9f100-df46-11eb-9103-f59eb591c320.png)

```
        // I just ignore my self-defined config here.
        // it looks like this: {'html-id-name': {'xs': {"x": 0, "y": 0, "w": 12, "h": 15,}}}}
       let gridItemLayoutConfig = {...}; 
       let size = 'xs';       

       let options = {'float': true,
                       'cellHeight': '2vh',
                       'margin': '10px',
                       'resizable': 'all',
                       'alwaysShowResizeHandle': false,
                       'disableOneColumnMode': true,
                       };
        grid = GridStack.init(options);
        gridItems = grid.getGridItems();

        grid.batchUpdate();
        for (const gridItem of gridItems) {
            gridItemLayoutConfig = selfDefinedLayout[gridItem.id][size];  
            gridItemLayoutConfig['id'] = gridItem.id;
            grid.update(gridItem, gridItemLayoutConfig);
            // console.log(gridItem);
            // console.log(gridItem.clientHeight); // not every grid-stack-item gets the right height
        }
        grid.commit();
        
        for (const gridItem of grid.getGridItems()){
            gridItemLayoutConfig = selfDefinedLayout[gridItem.id][size];  
            gridItemLayoutConfig['id'] = gridItem.id;
            console.log('desired position', gridItemLayoutConfig);
            console.log('actual position', gridItem.getAttribute('gs-x'), gridItem.getAttribute('gs-y'), gridItem.getAttribute('gs-w'), gridItem.getAttribute('gs-h'));
        };
```
