### ISSUE TITLE
Search on Grid nodes?

### ISSUE THREAD

**Issue by Nagendra080389** [gridstack/gridstack.js#1285]
## Subject of the issue
Is there any functionality to search on the grid nodes?

## Your environment
* gridstack@1.1.1
* Chrome

I tried filtering it on nodes but it does not work, is there any functionality via which we can filter on nodes on GridStack.

            `var $searchField = $('#idFieldSearch');
            $searchField.val('');
            // Search field binding.
            let searchFieldValue = $searchField.val().toLowerCase();
            $searchField.on('keyup', function () {
                var newSearch = $searchField.val().toLowerCase();
                if (searchFieldValue !== newSearch) {
                    searchFieldValue = newSearch;
                    dragZone.engine.nodes.filter(function (item) {
                        var element = item.el.firstChild;
                        return !searchFieldValue ? true : (element.getAttribute('data-strFieldLabel') || '').toLowerCase().indexOf(searchFieldValue) > -1;
                    });
                }
            })`

**Comment by adumesny** [comment]
I don't know you will have to debug your code. Assuming `dragZone` is a GridStack, then yeah `dragZone.engine.nodes` will let you iterate over the nodes which have `.el` DOM element.

**Comment by Nagendra080389** [comment]
Yes dragZone is a gridstack, but even after filtering with above code, and returning true and false property,  the grid does not get filtered. Is thre any example, or have anyone tried this before.
