### ISSUE TITLE
Incompatability between Bootstrap 4.5 and latest gridstack.js

### ISSUE THREAD

**Issue by tsnork** [gridstack/gridstack.js#1288]
## Subject of the issue
Collapse events don't work if gridstack.js gets loaded after Bootstrap 4.5 main js.

## Your environment
Latest gridstack.js (1.1.1 from CDN)
Chrome 81.0.4044.138
Bootstrap 4.5 from CDN

## Steps to reproduce
Working example: https://codepen.io/tsnork/pen/qBOGpam
Not working example: https://codepen.io/tsnork/pen/PoPvEpy

Only the loading order of JS files is changed in the examples.

## Expected behaviour
The events which bootstrap emits should fire the alert on the two events included in JS

## Actual behaviour
Depending on loading order the events are ignored. Only if gridstack.js gets loaded BEFORE Bootstrap js the events work.

Thanks for the project and your support!

**Comment by adumesny** [comment]
you should not include `https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js` with `gridstack-all.js` as that already includes it, so you have 2 copies. if you need to get your own version, see https://github.com/gridstack/gridstack.js#jquery-application

**Comment by tsnork** [comment]
Wow, my bad. Sorry,  I double-checked everything (...or so I thought). Sorry for wasting time and thanks for the fast response.
