### ISSUE TITLE
cellHeight and aspect ratio

### ISSUE THREAD

**Issue by nuno-q** [gridstack/gridstack.js#1289]
## Subject of the issue
aspectratio 16/9 not working in one column mode (column grid-stack-1).

## Your environment
gridstack.js 1.1.2-dev
Google chrome version 81.0.4044.138 (Official Build) (64-bit)

## Steps to reproduce
I'm trying to use 16/9 aspect ratio and it works fine till resizing to gridsatck minWidth (one column grid-stack-1) and the height messes up with aspect ratio.

## Expected behaviour
the grid-stack-item height should be equal to (9*100/16)vw or 56.25vw (viewport width) mantaining the 16/9 aspect ratio

## Actual behaviour
the grid-stack-item height is lot heigher than expected.

[aspectratio.zip](https://github.com/gridstack/gridstack.js/files/4736310/aspectratio.zip)

**Comment by adumesny** [comment]
I'm not sure what you are trying to do - can you please show pictures/movie and/or a running sample ?
the code you attached uses 
```js
"resizable": {
                "handles": "e, se, s, sw, w",
                "aspectRatio": 16 / 9
            },
```
aspectRatio is not supported by the grid (I assume it's a jquery-ui thing but won't stick when released to snap to grid sizing) and not sure if you are trying to set the gridHeight on GridStack to `56.25vw` (which wouldn't suprised my doesn't work - see other posted bug on supporting % for example).
`"cellHeight": "auto",` only means to to initialize the cells to be square
many other attributes not sure where you get them from (width is now column, acceptPanes ??, etc...)

**Comment by adumesny** [comment]
closing due to non reply.
