### ISSUE TITLE
Is it possible to achieve animation during drag-n-move?

### ISSUE THREAD

**Issue by yccheok** [gridstack/gridstack.js#1291]
Hi,

Thank you for open sourcing gridstack.js. It provides a good foundation, for me to create a card-liked dashboard UI.

Currently, I'm planning to port the following Android app to Electron desktop app.

I wish to achieve the following animation during drag-n-move - https://youtu.be/aRvM64dBNA0

May I know, is it possible achieve animation during drag-n-move? Can you provide me some hint on where I should start from?

Thanks.

**Comment by adumesny** [comment]
there is an animation grid option flag, but it may not work anymore (recall seeing a bug posted). I've never tried so not sure what it did... Also slack is better for questions than posting a "bug"
