### ISSUE TITLE
Utils.sort() corner case

### ISSUE THREAD

**Issue by antoineluong** [gridstack/gridstack.js#1292]
## Subject of the issue
GridStackUI.Utils.sort() gives an unpredictable result (depending on the browser) when the passed `nodes` parameter contains data without `x` and `y` defined.
As it was not the case with older versions, I guess the behaviour changed when lodash was replaced (see 49ad47dde21d08d9cdd8e19da9c3749040289c66).
Is it working as designed and should I check the array before trying to sort?

## Your environment
* GridStack 0.6.4
* Firefox 68 / Chrome 71

## Steps to reproduce
```
GridStackUI.Utils.sort([
    {id: "foo", width: 1, height: 1},
    {id: "bar", width: 1, height: 1}
]);
```

## Expected behaviour
Ideally, the same behaviour across different browsers.

## Actual behaviour
With Firefox the array is kept as is; with Chrome it gets reversed.

**Comment by adumesny** [comment]
can't sort (by x,y) if you have undefined values. not worth fixing IMO.
