### ISSUE TITLE
Height is set to 140px on element

### ISSUE THREAD

**Issue by dAnjou** [gridstack/gridstack.js#1293]
## Subject of the issue
Something is setting a height of 140px directly to the root element so that I can't override it.

## Your environment
* gridstack.js 1.1.2
* Google Chrome Version 83.0.4103.97

## Steps to reproduce
https://jsfiddle.net/okpbn750/1/

## Expected behaviour
I can set the height in my CSS definition

## Actual behaviour
My CSS has no effect because something sets the height on the root element.

**Comment by adumesny** [comment]
this is not a bug but as designed. There is a cellHeight grid options you can specify - the code will size the grid to fit the number of items instead. % may not work as you wouldn't be able to manually move items below...
