### ISSUE TITLE
issue with moving items between nested grids

### ISSUE THREAD

**Issue by zgilewski** [gridstack/gridstack.js#1295]
Hi,

we are using nested grids between which we need to move items like it is showed in nested grids demo.
Problem is that there is issue which can be reproduced when elements of these two nested grids are near. Then when moving element from one nested grid to another, is not removing placeholder in first nested grid. That causing an issue with placing other elements in that placeholder in grid.
This can be reproduced in Nested grids demo like it is showed in that screenshot:

![image](https://user-images.githubusercontent.com/28985410/85225122-32329780-b3cf-11ea-948a-705a4af98838.png)

We using gridstack 1.1.1.

Correct behaviour should be, that when element is moved from one gridstack to another, in first gridstack placeholder should be removed.

Actually in described situation it is not removed.

**Comment by adumesny** [comment]
dup of #393
