### ISSUE TITLE
grid from serialize

### ISSUE THREAD

**Issue by elvir92** [gridstack/gridstack.js#13]
Hi ,
Again me ,could you please make  method that will build a new grid from previously stored positions , like gridster:  http://gridster.net/demos/grid-from-serialize.html
Thank you

**Comment by Japes** [comment]
Hi,

For some reason my widgets dont get placed in the correct position when I add them as shown.  Their sizes are right, but the positions are all messed up?
I have tried setting auto_position to false but widgets still seem to do their own thing when I add them
But if I do a batch_update(), it works fine.
