### ISSUE TITLE
Documentation and src missmatch

### ISSUE THREAD

**Issue by 71GA** [gridstack/gridstack.js#1301]
## Documentation and src missmatch

Documentation says if we want to use gridstack, we have to use CDN: 

```
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gridstack@1.1.2/dist/gridstack.min.css" />
<script src="https://cdn.jsdelivr.net/npm/gridstack@1.1.2/dist/gridstack.all.js"></script>
```

or include it localy like:

```
<link rel="stylesheet" href="gridstack.min.css" />
<script src="gridstack.all.js"></script>
```

CDN variation works, but if I want to include it localy I get confused because your [source files](https://github.com/gridstack/gridstack.js/tree/develop/src) dont have `gridstack.all.js` and `gridstack.min.css`... Is it possible documentation is wrong? How do I include it then?

**Comment by faccia107** [comment]
https://github.com/gridstack/gridstack.js/releases

**Comment by 71GA** [comment]
Ah okay! Thanks!

**Comment by adumesny** [comment]
actually you npm install the release
