### ISSUE TITLE
grid.moveWidget does't work

### ISSUE THREAD

**Issue by ritox842** [gridstack/gridstack.js#1305]
## Subject of the issue
I'm migrating from 0.5.3 to 1.1.2 and I've noticed that moveWidget stopped working.

## Your environment
1.1.4
chrome

## Steps to reproduce
No special use case. Ordinary move doesn't work.
Reproduce it https://jsfiddle.net/05L79kab/31/

## Expected behaviour
Element should move to the supplied coords

## Actual behavior
Element doesn't move at all. To error is thrown.

**Comment by adumesny** [comment]
not a bug. use `grid.move(element.parentElement, 0, 0)` as you can't call that on item content. needs to be `.grid-item`

**Comment by ritox842** [comment]
Got it. Thanks.
