### ISSUE TITLE
Can't manually move locked widget

### ISSUE THREAD

**Issue by ritox842** [gridstack/gridstack.js#1307]
## Subject of the issue
I'm migrating from 0.5.3 to 1.1.2 and I've noticed that move() **for locked widgets** had stopped working.
The way it was in 0.5.3 is that calling move() on a locked widget did in fact moved it (https://jsfiddle.net/8b6acgn7/2/).
Currently, on version 1.1.2 the locked widget doesn't move at all (https://jsfiddle.net/k0h4nvqw/9/).
This is possibly a regression from version 1.1.1 https://github.com/gridstack/gridstack.js/issues/1181. While the original issue was solved it caused locked widgets to not move anymore.

## Your environment
gridstack 1.1.2
chrome

## Steps to reproduce
Create a grid with locked a locked widget and try to move it using the method move()
https://jsfiddle.net/k0h4nvqw/9/

## Expected behaviour
While locked widget shouldn't be moved by other widgets, I'm still expecting that applying new coords using move() will affect it as it was.

## Actual behaviour
Locked widget ignore move() and stay in its place.

**Comment by adumesny** [comment]
I'm reluctant to change this as calling move on a locked item should not change it (it is locked after all) - noMove and noResize means no user interactions. Locked is lock for API and other nodes pushing it around. you can easily unlock it before calling move on it directly anyway.... I think it was incorrect before.
```js
  GridStackEngine.prototype.moveNode = function(node, x, y, width, height, noPack) {
    if (node.locked) { return null; }
```

won't fix.

**Comment by ritox842** [comment]
In our use case, we use locked widgets as separators between sections. If I'll unlock the widget it will automatically move up until it reaches a widget. I need to pin the widget to its row but still be able to move it around.
I think its a common scenario when using locked widgets.

**Comment by adumesny** [comment]
then you need to turn on float=true (so widget don't gravitate to top), unlock it so you can move it, and reset things back. You are asking for very specific use case, so checking for locked above you still move and gravitate it to top available space...
