### ISSUE TITLE
Grid stack not working properly on div under tabs when not active

### ISSUE THREAD

**Issue by bangkalog** [gridstack/gridstack.js#1310]
## Subject of the issue
This is what happen when I click the 2019 tab then resize the browser then go back to 2020 tab. The grid become very small but the chart inside is still there as you can see the resize icon is on the right when i hover my mouse on it. Only the active tab works fine when browser resize. Is there a way to refresh the grid sizes on tab click?

## Your environment
 gridstack.js 0.4.0

![image](https://user-images.githubusercontent.com/67732517/88768128-352e5e00-d1ad-11ea-9ade-49b5f9b431cf.png)

here is what it should look like. is there a way to reset the gridstack base on the size of its content
![image](https://user-images.githubusercontent.com/67732517/88768142-3b243f00-d1ad-11ea-9b2a-0a1dba60d6d8.png)

**Comment by adumesny** [comment]
can't do anything without a simple reproducible test case, but to be honest I would check you CSS and dom elements sizing that contains the grid - the grid lays things as % of column and looks to me that the grid item itself is sized incorrectly by you.

Closing unless you can show that is a gridstack lib issue with a sample.
