### ISSUE TITLE
Reattaching gridstack element causes _styles to lose ownerNode

### ISSUE THREAD

**Issue by gregid** [gridstack/gridstack.js#1314]
## Subject of the issue
When gridstack element is part of the DOM that has moved in any way, e.g. Drag and Drop, it will be displayed incorrectly (or rather disappear from view). This is caused by gridstack._styles losing its reference to `ownerNode` ie. `style` element that holds the stylesheet.
With the addition of styleInHead in #1313 the consequences can be mitigated as `head` is unlikely to be reattached. But the underlying issue can cause problems in the future and need to be looked into.

BTW: #1313 should be viewed separately from this issue.
 
## Your environment
* version of gridstack.js 1.1.2
* which browser and its version (chrome, firefox, edge)

## Steps to reproduce
Here is a sample to reproduce: https://jsfiddle.net/2v0kdzgh/
Just drag the gridstack to Drop Here.

## Expected behaviour
After reattaching the gridstack should display the same/correctly

## Actual behaviour
The gridstack loses its style and all widgets are squashed into 1 pixel line

## Possible solutions
In the jsfiddle sample uncommenting `grid._updateStyles()` will rebuild the style but this assumes you will have a handle to grid while the problem with this issue is that any parent of the grid could change the DOM and it's unlikely you will have control over this. 
One idea is the `_styles` could be monitored for change of its `ownerNode` and if it is null then run `_updateStyles()`. Could it be done with Mutation Observer?

**Comment by adumesny** [comment]
hey thank you for the great bug report and sample app. Didn't think of the grid itself (or a parent) being dragged and re-parented!

I see you are using HTML5 dragg&drop... maybe I can enlist you to help with 3.x version to remove jqueryui drag/drop/resize :)
(once I get 2.x out which only needs build setting to export ES6 compatible modules)

**Comment by gregid** [comment]
It looks like gridstack will become important part of my application, so I have vested interest in it and will try to help as much as possible albeit I am no expert at D&D, just learning it.

**Comment by gregid** [comment]
Another idea to explore is to use shadow DOM to store the style.

**Comment by adumesny** [comment]
do you have a recommended fix review for this in the latest code base ? with the option to put the CSS in the head rather than grid parent, this doesn't seem like worth fixing with a simple workaround, and would like to close. thanks.

**Comment by gregid** [comment]
Some update - I couldn't make Mutation Observer to fire on this change so the only possible solution I see is to try the Shadow DOM route. This would be much bigger change and I don't expect to work on this in the next few months, so if you would rather clean the issues we can close and eventually reopen it later?

**Comment by adumesny** [comment]
isn't using the HEAD solve moving the grid to a new location anyway ? yeah, I trimming my bug list, and this doesn't make the cut...

**Comment by gregid** [comment]
Head solves the problem but also pollutes the DOM outside of the grid "component" - but we are talking about ideal scenario so I agree with the decision to close for now.
