### ISSUE TITLE
Drag widget to bottom doesn't scroll 

### ISSUE THREAD

**Issue by ritox842** [gridstack/gridstack.js#1322]
## Subject of the issue
I have a very long grid. When I try to drag widget from top to bottom the grid doesn't scroll down and I'm unable to move the widget properly.
I saw the draggable option in the documentation but setting scroll: true didn't change anything.

## Your environment
gridstack 1.1.2
chrome

## Steps to reproduce
https://jsfiddle.net/9f817a60/2/
Add some widgets until thre's a scrollbar and try to drag widget from top of the grid to the bottom.

## Expected behaviour
Grid scroll down while dragging the widget and the cursor is near the edge of the page

## Actual behaviour
Grid doesn't scroll, Cant move widget from top to bottom.

**Comment by ritox842** [comment]
Any updates?

**Comment by adumesny** [comment]
fixed in v3 with html5 version (scroll is always true). see https://jsfiddle.net/adumesny/cskdxuv9/
