### ISSUE TITLE
How to reduce the left and right spacing of layout blocks？

### ISSUE THREAD

**Issue by ztanglin** [gridstack/gridstack.js#1325]
How to reduce the left and right spacing of layout blocks？

**Comment by ztanglin** [comment]
How to reduce the left and right spacing of layout blocks？

**Comment by adumesny** [comment]
please use slack channel for questions. this is for reproduceable bugs only...
Hint: in 1.x you have to use CSS, in 2.x (which I recommend) I added a 'margin' params which effects all 4 sides from code.
