### ISSUE TITLE
How to resize the tiles using resize handles on mobile

### ISSUE THREAD

**Issue by 71GA** [gridstack/gridstack.js#1326]
## Subject of the issue
I commented out the resize handle image so that it can't be seen, but resize handles are working and it is possible to resize tiles inside a grid with a mouse. But on mobile I don't know how to resize the tiles... No mather how I press or what gesture I use, I can't resize the tile. 

Does anyone know why this doesn't work or, how to resize tiles on a phone?

## Your environment
Gridstack - v. 1.1.2
Google chromium - v. 83.0.4103.116 (Developer Build) built on Debian 10.4, running on Debian 10.5 (64-bit)

**Comment by adumesny** [comment]
did you read https://github.com/gridstack/gridstack.js#touch-devices-support ?
I suggest you use the slack channel to ask Q for others. I have not used on mobile yet...

**Comment by 71GA** [comment]
Thank you. This solved my issue.

**Comment by dennisat** [comment]
> did you read https://github.com/gridstack/gridstack.js#touch-devices-support ?
> I suggest you use the slack channel to ask Q for others. I have not used on mobile yet...

Touch move in now supported.
`document.body.addEventListener('touchmove', () => console.debug('touchmove'))`

**Comment by adumesny** [comment]
@dennisat v3.3 JQ version works out of the box (what the website uses) as I now compile in touch support. H5 version does not as HTML5 drag isn't on mobile so I will have to ad touchmove
