### ISSUE TITLE
uncaught reference error 'mobile' of undefined

### ISSUE THREAD

**Issue by jneilliii** [gridstack/gridstack.js#1333]
## Subject of the issue
Trying to embed gridstack into my project and getting uncaught reference error. If I load the javascript file via CDN everything works as expected. I'm sure I'm just missing some stupid dependency. 

## Your environment
GridStack 1.2.0
Google Chrome Version 84.0.4147.125 (Official Build) (64-bit)

## Steps to reproduce
Because the js files are getting bundled by a framework in the plugin I'm developing I cannot provide a jsfiddle to show you an example. Unfortunately this system doesn't use node/npm and I can't just import.

## Expected behaviour
GridStack to load without errors.

## Actual behaviour
```
Uncaught TypeError: Cannot read property 'mobile' of undefined
    at main.js:106
```

**Comment by adumesny** [comment]
"system doesn't use node/npm and I can't just import"

you are not giving anything to work with... the error above  is in your code. Are you including gridstack.all.js (what the cdn example do ?) - you need to list what you are including.

**Comment by jneilliii** [comment]
Yes, I'm doing exactly that. The framework I'm using bundles all js and css together, and I've included gridstack.all.js and gridstack.min.css downloaded from CDN directly as part of my bundle and it is loading in the page, which is how I'm getting the error. I was under the impression there were no other dependencies in the newer versions, but maybe I missed something in the docs?
