### ISSUE TITLE
option to not scale items during column(n) change

### ISSUE THREAD

**Issue by lozah** [gridstack/gridstack.js#1338]
## Subject of the issue

Hello gridstack. I got a problem with grid's columns update.

## Your environment

1.1.2

## Steps to reproduce

- Create a grid with 3 columns. 
- Create items, some with a width of 2, some with a width of 1.
- Add event listener on window resize.
- On resize under a certain window width change the grid number of columns to 2.

## Expected behaviour

I was expecting items to keep their width, and just reajusting their positions inside the grid.

## Actual behaviour

Items with width of 2 change to width of 1.

Items width resizing should happen only if there is not enough space inside the grid. Inside a grid with 2 columns, items with 2 columns width should keep their size. Is this a normal behaviour ? Is there a way to not resize the items ?

**Comment by adumesny** [comment]
you are the second person asking for this - see #1332 which I believe wants the same thing.

You might want different behaviors, but adding a flag to scale or not when changing column() might do the trick and should be easy to implement.

**Comment by lozah** [comment]
> You might want different behaviors, but adding a flag to scale or not when changing column() might do the trick and should be easy to implement.

This would be amazing 👍

**Comment by adumesny** [comment]
@lozah do you still need this ? I didn't get an answer from the other user which has a more generic request.

**Comment by adumesny** [comment]
fixed in next release
