### ISSUE TITLE
Is simultaneously having (a) static grid and (b) one-column mode even possible? 

### ISSUE THREAD

**Issue by 71GA** [gridstack/gridstack.js#1340]
I have a question regarding the Gridstack initialisation. What our team strives to do is a **fixed grid with 12 columns & 6 rows** but also with a support for **one-columnm mode**. 

I wonder if this is even possible. If I initialise Gridstack with `maxRow: 6, minRow: 6, disableOneColumnMode: false` then on desktop, grid is fixed and no row is added at the bottom when I drag tiles to the bottom of the grid. This works as expected. But in  one-collumn mode if I have more than 6 tiles _(12 x 6 grid can have max 72 tiles)_ then only 6 tiles are shown... Is it possible to make gridstack increase row number for one-column mode? Is what I want even possible?

**Comment by adumesny** [comment]
look at the responsive sample demos and manage when gridstack goes into 1 column mode (you can prevent automatically going into 1 column) and when you want to go 1 column, just increase the maxRow to what you need (or set to 0 to turn off) and call set column to 1. simple!
