### ISSUE TITLE
TS2307: Cannot find module 'gridstack'.

### ISSUE THREAD

**Issue by lennysg** [gridstack/gridstack.js#1342]
## Subject of the issue
import { GridStack } from 'gridstack'; 
I get an error TS2307: Cannot find module 'gridstack'.

## Your environment
* version of gridstack.js: 2.0.0-rc

## Steps to reproduce
Install gridstack and attempt to include it in my typescript. It appears to referencing the correct node_module/gridstack directory, but I did notice package.json: "main": "./dist/index.js", (this file does not exist. Could this be an issue?)

**Comment by adumesny** [comment]
thank, forgot to change that... How did you resolve your issue ? also make sure to use .rc2 and let me know how it goes.
