### ISSUE TITLE
2.0.0-rc & 2.0.0-rc2 pacakage.json main file （dist/index.js） not found 

### ISSUE THREAD

**Issue by rhlin** [gridstack/gridstack.js#1344]
npm install gridstack@2.0.0-rc2
in package.json 
{
 ...
"main: './dist/index.js'  // file not exist
...
 "typings": "./dist/index.d.ts", // file not exist
...
}
I am usting typescript 3
it means I can't import like this  `import { GridStack, GridstackOptions } from ‘gridstack’.  
must import through every specific file like `import { GridStack } from ‘gridstack/dist/gridstack`.  `import { GridstackOptions } from ‘gridstack/dist/types`. 

holp module import can be supported

**Comment by adumesny** [comment]
fixed yesterday with #1343. will publish rc3 this weekend...
