### ISSUE TITLE
"cellHeight=8rem" breaks during resize in 2.0.0

### ISSUE THREAD

**Issue by 71GA** [gridstack/gridstack.js#1356]
I migrated to Gridstack 2.0.0 and I noticed that relative units do not work for "cellHeight" anymore. Here is the minimal working example: https://jsitor.com/YYbJFy7UY

To reproduce... First run with line `cellHeight: "8rem"` comented and everything seems to work. But then uncomment it. You will see that positioning / placeholder don't work if line is not commented out.

**Comment by adumesny** [comment]
here's the default example with `cellHeight: "8rem"`  set which shows the issue when resizing (renders ok initially).
v 2.0.0
https://jsfiddle.net/adumesny/jqhkry7g/50/

vs 1.2.1 version which works during resize
https://jsfiddle.net/adumesny/jqhkry7g/51

thanks for posting this!

**Comment by adumesny** [comment]
fixed in 2.0.1
