### ISSUE TITLE
Saving grid with text?

### ISSUE THREAD

**Issue by Wolfleader101** [gridstack/gridstack.js#1357]
## Subject of the issue
i cannot save or load a grid with text.

## Your environment
* version of gridstack.js
2.0.0
* which browser and its version
Chrome Latest

## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template]
```html
    <div class="grid-stack-item" data-gs-x="0" data-gs-y="0" data-gs-width="4" data-gs-height="2">
      <div class="grid-stack-item-content">my first widget </div>
    </div>
```

```js
  loadGrid = function () {
    grid.load(serializedData, true);
  }

  // NEW 2.x method
  saveGrid = function () {
    serializedData = grid.save();
    document.querySelector('#saved-data').value = JSON.stringify(serializedData, null, '  ');
  }
```

## Expected behaviour
when saving and loading content should be shown.

## Actual behaviour
content is empty

**Comment by adumesny** [comment]
we can't save the content of your widgets as it very application specific... in your sample it's just simple text, but in real app likely to be custom HTML or runtime widgets. It's up to the app to save their content using the content id (if provided). The lib can only do the layout, the rest is up to you...
