### ISSUE TITLE
Problem with migrating to 2.0.0

### ISSUE THREAD

**Issue by mariuszkrzaczkowski** [gridstack/gridstack.js#1358]
## Subject of the issue
I am trying to migrate from 1.2.1 to 2.0.0 but it fails.
When loading dist/gridstack.all.js 
I have collisions with my JS scripts and when loading dist/gridstack.js it shows me this error:

Firefox 80.0.1
![image](https://user-images.githubusercontent.com/10198654/93051664-291b3480-f665-11ea-8d57-0a53e7d61a9a.png)

Chrome 85.0.4183.102 
![image](https://user-images.githubusercontent.com/10198654/93051679-2ddfe880-f665-11ea-9443-71d474116871.png)

## Your environment
* version of gridstack.js - 2.0.0
* which browser and its version Chrome 85.0.4183.102 , Firefox 80.0.1

## Steps to reproduce
Include dist/gridstack.js with jquery , jquery-ui loaded

jquery = 3.5.1
jquery-ui-dist = 1.12.1

**Comment by adumesny** [comment]
Please provide a simple reproduceable case (use the https://jsfiddle.net/adumesny/jqhkry7g or similar) as I do not have the time to debug your enviroment.

Note that in 2.0 I have NOT figured out how people can bring their worn jquery/jquer-ui version (we compile in the latest) unlike 1.x having different files.
