### ISSUE TITLE
v2.0.0 griditem change minWidth won't pass to engine

### ISSUE THREAD

**Issue by rhlin** [gridstack/gridstack.js#1359]
## Subject of the issue
walk through the code, found that  only `maxWidth()`  in `GridStack` class api for modifing griditem min max data wound update the `node.maxWidth` . (see [maxWidth](https://github.com/gridstack/gridstack.js/blob/1af43bd0c3ac2b4897bf90025c3b243f0c133c30/src/gridstack.ts#L726))
maxHeight/minHeight/minWidth funtion call  do not update the node.maxHeight/minHeight/minWidth, which might cause engine not cacluate right.
(see [minWidth](https://github.com/gridstack/gridstack.js/blob/1af43bd0c3ac2b4897bf90025c3b243f0c133c30/src/gridstack.ts#L745))

## Your environment
* version of gridstack.js: v2.0.0
* which browser and its version: doesn't matter

## Expected behaviour
`node.minWidth = (val || undefined)`

## Actual behaviour
the node.minWidth wouldn't update

**Comment by rhlin** [comment]
and another minor issue, `GridstackOptions`, the first letter of 'stack' , s should be capitalized

**Comment by adumesny** [comment]
thank you for finding the issues. feel free to make a code suggestion next time. fix coming now.
