### ISSUE TITLE
Unable to use jquery droppable/draggable events in v2.0.0

### ISSUE THREAD

**Issue by zlatkolakisic** [gridstack/gridstack.js#1363]
## Subject of the issue
Unable to use jquery droppable/draggable events in v2.0.0

## Your environment
gridstack v.2.0.0
chrome 85

## Steps to reproduce
Try to bind to events dropactivate/dropdeactivate/dropover/dropout

## Expected behaviour
Events are called as they are valid jquery drag/drop events

## Actual behaviour
gridstack says the event is not supported

**Comment by adumesny** [comment]
please provide a working example (I give a template) - keep in mind that jquery ui will be removed in a future release, but should still work for now.

**Comment by zlatkolakisic** [comment]
Hi @adumesny 

Thanks for the very prompt response.

Here is my example:
`<html>
    <head></head>
    <body>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gridstack@2.0.0/dist/gridstack.min.css" />
        <script src="https://cdn.jsdelivr.net/npm/gridstack@2.0.0/dist/gridstack.all.js"></script>

        <div class="grid-stack">
        <div class="grid-stack-item" data-gs-x="0" data-gs-y="0" data-gs-width="4" data-gs-height="2">
            <div class="grid-stack-item-content">my first widget</div>
        </div>
        <div class="grid-stack-item" data-gs-x="4" data-gs-y="0" data-gs-width="4" data-gs-height="4">
            <div class="grid-stack-item-content">another widget!</div>
        </div>
        </div>

        <script type="text/javascript">
        var grid = GridStack.init();
        grid.on('dropactivate', function (event, ui) {
            //Do Something
        });

        grid.on('dropdeactivate', function (event, ui) {
            //Do Something
        });

        grid.on('dropover', function (event, ui) {
            //Do Something
        });

        grid.on('dropout', function (event, ui) {
            //Do Something
        });
        </script>
    </body>
</html>`

**Comment by adumesny** [comment]
right, so 2.0 API doesn't support all jq ui events, if you want those (while we still use jqueri ui) then you need to to the `$('.grid-stack').on(...)` or whatever it used to be.

**Comment by zlatkolakisic** [comment]
Thanks a bunch, this does the trick!
