### ISSUE TITLE
Dragging from parent grid to child and vice versa doesn't work

### ISSUE THREAD

**Issue by zlatkolakisic** [gridstack/gridstack.js#1364]
## Subject of the issue
Dragging from parent grid to child and vice versa doesn't work

## Your environment
- v2.0.0
- google chrome 85

## Steps to reproduce
Please go to [https://gridstackjs.com/demo/nested.html](https://gridstackjs.com/demo/nested.html) to view, am able to reproduce the same result locally.

## Expected behaviour
Grid tiles should be transferrable from child to parent grid and vice versa

## Actual behaviour
Grid tiles are not transferrable from child to parent grid and vice versa

**Comment by adumesny** [comment]
this has never worked (move heirachy) and is a dup of #992 - closing

**Comment by adumesny** [comment]
> I notice that you have marked my issue #1364 as a duplicate and not supported. I have got it to work on version 1.11 and I would much rather not downgrade your great product. Does the drag-out feature not work?

you saying that dragging green "regular item" into "nested 1" as pink item worked in 1.11 ?
please provide a working (and non working with 2.0) running example as I've never seen that, but might have missed something.
re-open when you do. thanks

**Comment by zlatkolakisic** [comment]
Hi Alain

Thanks for the prompt response. The code is integrated in a much larger angularjs project so segregating it will be a bit difficult. In essence, I would use the dropover and dragover events to modify the acceptWidgets property to accept a specific class of the element when it's over a subgrid and vice versa over the parent grid, but now, the drag out functionality is not working.

I think the drag out functionality not working is limiting this.

Zlatko

**Comment by adumesny** [comment]
use the nested.html as a starting point to add the bare minimum (working and not). Don't expect me to create an example for you!

**Comment by zlatkolakisic** [comment]
Hi Alain

Ok, will try and look at it closer and possibly get you my concept, not asking you to create examples by any means.

Thanks,
Zlatko
