### ISSUE TITLE
Item attributes not preserved when moving across/dropping into grid for saving

### ISSUE THREAD

**Issue by patrickkusebauch** [gridstack/gridstack.js#1367]
## Subject of the issue
If I have an item in another grid or an item outside of the grid dragged into a new grid, it's attributes are not preserved.
 
## Your environment
Version of gridstack.js: 2.0.0 
Browser: Chrome on Ubuntu (Version 83.0.4103.61 (Official Build) (64-bit))

## Steps to reproduce
1. Open https://gridstackjs.com/demo/two.html
2. Drag item with text "has maxWidth=3" from the left grid to the right grid
3. Open console and type "grids[1].save()" (saves/serializes the right grid item data)

## Expected behaviour
The moved item should have its ID attribute saved in the serialized JSON.

## Actual behaviour
The moved item does not have its ID attribute saved in the serialized JSON.

**Comment by adumesny** [comment]
very good! you are using my own test beds to find bugs... I should have caught that one, if only I had unit testing for drag&drop.

**Comment by adumesny** [comment]
fixed in 2.0.1
