### ISSUE TITLE
alwaysShowResizeHandle does not work anymore in v2.0.0

### ISSUE THREAD

**Issue by loedeman** [gridstack/gridstack.js#1373]
## Subject of the issue
Since v2.0.0, the option _alwaysShowResizeHandle_ does not work anymore. I looked up the code and assume this functionality has been deleted when JQuery (UI) was deleted from the codebase.

## Your environment
* v2.0.0
* Any browser (mine is the latest Chrome version)

## Steps to reproduce
This also occurs in your own demos. The easiest way to reproduce is to open own of your own examples using this option, like the [advanced demo](https://gridstackjs.com/demo/advance.html).

## Expected behaviour
Auto hide of resize handles should work.

## Actual behaviour
Auto hide of resize handles does not work, handles are always being shown.

**Comment by adumesny** [comment]
I'm not seeing this issue on Chrome/Windows 10. please provide what browser and with 1.21.1 vs 2.0.0 as maybe your browser doesn't support these
```js
    var grid = GridStack.init({
      alwaysShowResizeHandle: /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
        navigator.userAgent
      ),
      resizable: {
        handles: 'e, se, s, sw, w'
      },
```
![image](https://user-images.githubusercontent.com/3496166/94354549-04459a80-0031-11eb-92ad-f9392f689566.png)

**Comment by loedeman** [comment]
Sorry, but your screenshot shows the problem exactly. In my screenshot, I circled all resize handles which should NOT be visible, unless HOVERED. 

![image](https://user-images.githubusercontent.com/355132/94420992-336d2080-0185-11eb-91eb-07a6e31807cd.png)

Imho, immediately closing an issue is not that friendly too by the way. I will think twice now before reporting another issue.

**Comment by loedeman** [comment]
BTW, I am using the latest version of Chrome (85.0.4183.121) on the latest version of Windows 10. I already explicitly stated that I was using Gridstack 2.0.0 and that the issue applies to all browsers.

**Comment by adumesny** [comment]
Please re-read your bug report. You said "alwaysShowResizeHandle does not work anymore" then you point to my example which **does show** the resize handles in all corners **as stated in the code**, while other demo do show on hover only (don't have that flag turned on). 

You didn't bother copying the bug template and modifying to show an actual bug, but expect me to debug it for you ???
a lot of people file bugs when it's user error, then don't get back to me, and I don't have the bandwidth to debug it. It's simple enough to re-open when you actually have a reproduceable case.

then in your later comment you say "In my screenshot, I circled all resize handles which should NOT be visible, unless HOVERED." then you must be turning that feature off - how am I supposed to know what you mean ?

note to self: apparently this flag define if the handles are always visible or not. Not sure if new in 2.x
```js
resizable: { handles: 'e, se, s, sw, w' }
```

**Comment by adumesny** [comment]
fixed in next release

**Comment by loedeman** [comment]
Thanks!
