### ISSUE TITLE
Getting  $el.draggable is not a function with new gridstack version

### ISSUE THREAD

**Issue by ritox842** [gridstack/gridstack.js#1374]
## Subject of the issue
After upgrading to version 2.0 I'm getting `$el.draggable is not a function` for all of my widgets 
![image](https://user-images.githubusercontent.com/7280441/94169510-91ed8280-fe97-11ea-8f27-a19b1724c61e.png)

I saw some similar issue https://github.com/gridstack/gridstack.js/issues/1363
I wasn't able to reproduce it in jsFiddle. Tried to import jquery and jqyertUI and its working so I don't really knows why in my app Im getting this error.

## Your environment
* gridstack 2.0
* all browsers

## Expected behaviour
Widgets should be draggable.

## Actual behaviour
Getting error that gridstack's addWidget doesn't recognised $.draggable

**Comment by adumesny** [comment]
I need more info, like how you include gridstack (what version before) and how/why do import jquery directly as well - order might matter. Can't fix something I can't reproduce. try hard in jsFiddle, or fix your app. re-open when you have a test
