### ISSUE TITLE
Don't let grid widget overflow

### ISSUE THREAD

**Issue by Wolfleader101** [gridstack/gridstack.js#1375]
## Subject of the issue
Hello, i am currently using a gridstack within a gridstack so each "widget" can be customised further, however I am trying to find a way to limit an item from containing more widgets than it can carry. I cant seem to find a way within gridstack that if the content is too big for the widget it will resize the widget to fit the content.
Right now when the inner gridstack becomes full it overflows and creates a scrollbar.

## Your environment
* version of gridstack.js
2.0
* which browser and its version
latest chrome version

## Expected behaviour
resize widget accordingly.

## Actual behaviour
it overflows

**Comment by adumesny** [comment]
please use slack channel for questions - only bugs with reproduceable test case here. Not clear what you are trying to do, but might want to look at maxRow or setting cellHeight as % or something...
