### ISSUE TITLE
v2 does not work in IE11

### ISSUE THREAD

**Issue by creage** [gridstack/gridstack.js#1389]
## v2 does not work in IE11
I'm trying to upgrade to v2 now, but it does not work in IE11, and I can't find any dropped support notice.

## Your environment
* version of gridstack.js: 2.0.1
* which browser and its version: IE11

## Steps to reproduce
Just visit https://gridstackjs.com/#demo using IE11

## Expected behaviour
GridStack should work as in other browsers (Chrome)

## Actual behaviour
The grid on the demo page is completely broken.

P.S. Trying to use `gridstack.all.js` does not work either. Precompiling v2 using `babel` does not help.

**Comment by rhlin** [comment]
add an 'append' polyfill would help
https://developer.mozilla.org/en-US/docs/Web/API/ParentNode/append#Polyfill

**Comment by adumesny** [comment]
Not sure we will be supporting such an old brower - I know for sure not in 3.x  with html5 native  drag&drop, which I'm focusing on...
Looks like webpack might need to generate something older, or add missing operators.

![image](https://user-images.githubusercontent.com/3496166/94448637-f9d5ee80-015f-11eb-8b90-42ab54939a64.png)

![image](https://user-images.githubusercontent.com/3496166/94448701-107c4580-0160-11eb-9c9f-54af0d9c7d5f.png)

**Comment by adumesny** [comment]
explicit drop for IE11 and no longer compile polyfill
(size increase and still issue don't ewarrant such a obsolete support - use 1.x instead).
