### ISSUE TITLE
vue 3 support

### ISSUE THREAD

**Issue by manang** [gridstack/gridstack.js#1394]
Hi,
I'm trying to use your library in a project written in vue3.
my problem is when I use the parameter "float". if false, the gravity is in direction of the top side, if I declare float=true all the widgets are anchored to the bototm side and they are overlapped.
do you know how I can solve this issue?
Thank you
Angelo

**Comment by adumesny** [comment]
I'm not a vueJs person, but sounds like maybe you are missing gridstack.css or something not putting correct -y postiions before you init the grid... ask the slack channel for help.

**Comment by manang** [comment]
thanks

**Comment by manang** [comment]
I tried on a vue2 project created with vue-cli, with the same code...and it works.
the slack channel seems abandoned.

**Comment by manang** [comment]
In general it is not compatible with vue3.
the behavior is different between vue2 and vue3.

**Comment by adumesny** [comment]
@tobias-grasse might know (see on slack his replies as well)
Not a gridstack issue though... and by slack being abandoned meaning it not active as you kid's tiktok channel :)

**Comment by manang** [comment]
tanks for the name.
I hope that I can create a little example for vue3 that you can share in this repo.
Thank you again (never used tiktok...does it have channels?)
