### ISSUE TITLE
Issue with Widget Overlap

### ISSUE THREAD

**Issue by ishields** [gridstack/gridstack.js#14]
I've discovered an issue with an overlapping widget.  My configuration is 

"[{"x":0,"y":0,"width":4,"height":3},{"x":4,"y":0,"width":2,"height":4},{"x":6,"y":0,"width":6,"height":5},{"x":0,"y":3,"width":4,"height":2},{"x":0,"y":5,"width":6,"height":3},{"x":6,"y":5,"width":6,"height":2},{"x":0,"y":8,"width":4,"height":6},{"x":4,"y":8,"width":8,"height":5},{"x":4,"y":13,"width":8,"height":2},{"x":0,"y":14,"width":4,"height":2},{"x":4,"y":15,"width":8,"height":3},{"x":0,"y":16,"width":4,"height":2},{"x":0,"y":18,"width":4,"height":2},{"x":4,"y":18,"width":8,"height":2},{"x":0,"y":20,"width":4,"height":1}]"

Essentially when you resize the top left most widget to be higher, the bottom left most widget gets pushed to the top and the two overlap.  It seems like the bottom left most widget can not be pushed into another lower row, so it get's push to row 0.  Going to look into this, but also wondering if you've seen it or have any suggestions.

**Comment by tglines** [comment]
Still seeing this issue.  Looking at the CSS for the item that jumps up to the top it doesn't have a rule  that matches its y value even after this fix.
