### ISSUE TITLE
Unable to load grid layout content from localstorage

### ISSUE THREAD

**Issue by Souvikray** [gridstack/gridstack.js#1405]
I have already posted a question in stackoverflow where I have described my issue. Here is the link https://stackoverflow.com/q/64219336/5550284

Basically I have a layout (some widgets of varying sizes) which I am able to save the information (size and coordinates) to a localstorage but I am unable to fetch the information back from the localstorage. I am specifically having issue with this piece of code  `$('.grid-stack').data('gridstack')` which gives **undefined**. I have mentioned the problem in detail in my stackoverflow post so please refer the link above.

I am using gridstack.js npm version: 2.0.2

**Comment by adumesny** [comment]
`$('.grid-stack')` is the old 0.6 and before code, look at the documentation for current 1.x/2.x code (`GridStack.init()`).
Also when posting 'bugs' here you need to follow direction and post reproduceable case, not have me hunt for your other post...

**Comment by Souvikray** [comment]
Oh I see. Thanks for pointing me out in the right direction.
