### ISSUE TITLE
Select/Copy to clipboard

### ISSUE THREAD

**Issue by marknelson** [gridstack/gridstack.js#1406]
I'd like to be able to copy text from a gridstack widget using the normal mouse gestures. I guess what is normally handled by the browser is not working because mouse events are captured for drag and drop. I was thinking that perhaps selecting with a shift/alt/option key might be employed. I'm hoping that some other users have already solved this problem.

## Your environment
Gridstack 2.0.2

## Steps to reproduce
You can reproduce this with the default fiddle base. I had thought that perhaps disabling drag and resize would allow mouse events to go through to the browser, but haven't had any luck with that.

Interestingly, on Chrome the cursor changes to IBar when I'm over text, as if the browser is expecting me to select text, so it seems like maybe I'm halfway there.

## Expected behaviour
This is not a bug report, just looking for more information on how to better use the library.

**Comment by marknelson** [comment]
Okay, I see that if I disable drag and disble resize, I can copy - I think this will solve my problem.

**Comment by adumesny** [comment]
Mark, the way I handle in my apps it to use a 20px header bar to drag grid items around (where I also put on title and toolbar) leaving the rest of the card for the content to be interacted with (say a graph). Resize takes over in the corner 10px or so.
I should probably have that as an example - the demos are very simple entire grid drag...

**Comment by marknelson** [comment]
@adumesny That actually sounds very promising to me. I already have a header bar in my widgets, and I think the UI experience of using that to drag would work pretty well.

I haven't even tried to look at the internals of gridstack - are you able to do this with just CSS or do you need to intercept events? Yeah if you had an example that would be awesome.

**Comment by adumesny** [comment]
```js
GridStack.init({
handle: '.card-header', // this will add 'ui-draggable-handle' style to header
resizable: { autoHide: true, handles: 'e, s, w, se, sw' });
```
is what I use. and my items have a 20px or so dive header.

FYI, slack channel is best for asking those kind of questions (so others can respond or learn). Don't forget to contribute if you find this lib useful. Cheers

**Comment by marknelson** [comment]
Thanks @adumesny was unaware of the slack channel.

**Comment by adumesny** [comment]
for better UX I also change the cursor (cross hair) and backgound of the header on mouse over to make it clear that can be used to drag around.
