### ISSUE TITLE
How to get overlapping grids

### ISSUE THREAD

**Issue by enricol96** [gridstack/gridstack.js#1408]
Hello,
I'm using overlapped grids (with different z-indexes) but I'm experiencing strange behaviors: when I put an element in the upper grid (with bigger z-index), elements get dropped on both grids.

The grids should both have the drag and drop enabled since in my use case I would like to move from one grid to another and to add gridItems in the selected one.

Is it possible to do something like that using this library?
Thanks

**Comment by enricol96** [comment]
I think I got it, I just make only one grid (at a time) able to receive dragged elements.
I hope it will be useful for others facing the same problem.

**Comment by adumesny** [comment]
if you submit a reproduceable test case (use the template jsfiddle example) then we might be able to take a look...

**Comment by enricol96** [comment]
It is difficult for me to share the code since it is embedded in a larger codebase, but these are the steps I followed:
1. Use multiple overlapping grids (through CSS);
2. Select the one on which you you want to drag and drop items by appropriately setting the ```z-index``` and setting ```grid.opts.acceptWidgets``` to ```false``` for all the hidden grids.   

By doing this it is easy to reproduce my solution.

I take advantage of your reply to thank you for this very useful library :)

**Comment by adumesny** [comment]
| It is difficult for me to share the code since it is embedded in a larger codebase

again asking for simple test showing the issue (2 grid should suffice), not your solution, if you expect a fix. Don't foget to contribute or donate back...
