### ISSUE TITLE
Change in collision algorithm

### ISSUE THREAD

**Issue by azza0091** [gridstack/gridstack.js#141]
Hi,

The default algorithm works like this:
- if I start dragging an element on top of its upper element, the two elements gets instantly swapped
- if I start dragging an element on top of its lower element, the two elements gets swapped only after the dragged element is completely below the second element

i would like to modify it in order to make the two elements swap instantly also in the second situation (so, when the dragged element starts overlapping another element, they should swap)

do someone know how can I accomplish this, or what I should change in the code?

**Comment by papalaza** [comment]
You need to look into the _fix_collisions function. I begun to do the same thing as you want, but didn't get around to finishing it... I don't think it's the easiest thing to get going unfortunately... I could be wrong though.

**Comment by azza0091** [comment]
Yes, i tried to look there, but as you said it seems quite hard to modify... Because the same algorithm is used also to display elements on startup, so if I change something I will break everything...

**Comment by calvin-evans** [comment]
:+1:

**Comment by adumesny** [comment]
part of #1094

**Comment by adumesny** [comment]
consolidating into #1094
