### ISSUE TITLE
Could not find a declaration file for module './jquery-ui'. 'Project/node_modules/gridstack/dist/jq/jquery-ui.js' implicitly has an 'any' type.

### ISSUE THREAD

**Issue by RaminderRandhawa91** [gridstack/gridstack.js#1410]
Error related to missing typescript files for jquery and jquery-ui

## Your environment - Visual Studio 2019
* version of gridstack.js  - 2.0.2
* which browser and its version - Google Chrome

## Steps to reproduce
On building node modules, I am getting error 
Could not find a declaration file for module './jquery-ui'. 'D:/ClientApps/node_modules/gridstack/dist/jq/jquery-ui.js' implicitly has an 'any' type.

 ```    9 | import * as $ from './jquery';
    10 | export { $ };
  > 11 | export * from './jquery-ui'; ```
Could not find a declaration file for module './jquery'. 'D:/ClientApps/node_modules/gridstack/dist/jq/jquery.js' implicitly has an 'any' type.
  ```7 | import { GridStackDD, DDOpts, DDKey, DDDropOpt, DDCallback, DDValue } from '../gridstack-dd';
     8 | import { GridItemHTMLElement, DDDragInOpt } from '../types';
  >  9 | import * as $ from './jquery';
       |                    ^
    10 | export { $ };
    11 | export * from './jquery-ui';
```

## Expected behaviour
Can you please provide me typings for these files

## Actual behaviour
Can these typings be provided in the npm gridstack package

**Comment by adumesny** [comment]
just add these to your package ?
```  
"@types/jquery": "^3.5.1",
"@types/jqueryui": "^1.12.13",
```

are you building a npm package that uses gridstack or an app ? wasn't clear...

**Comment by adumesny** [comment]
please re-open if my suggestion doesn't work and you still have issues.
