### ISSUE TITLE
Change gridstack placeholder width and height

### ISSUE THREAD

**Issue by ronak-zymr** [gridstack/gridstack.js#1411]
## Subject of the issue
We are using nesting grid feature of gridstack in angularjs. It is working fine and its a great tool for resizing and drag & drop widgets.
But we are facing an issue to change the height and width of the widget placeholder while resizing.

We are using 4\*4 widget by default(data-gs-min-height=4, data-gs-min-width=4), and we want our user to resize the widget in 4\*4 dimention only. So for that when user starts resizing, we want gridstack placeholder to show border directly to 4\*4 dimention instead of default 1\*1 dimention. 

You can see the default behaviour of gridstack placceholder in below image this we want to change to 4/*4 dimention.

<img width="1369" alt="Screenshot 2020-10-16 at 12 23 29 PM" src="https://user-images.githubusercontent.com/70004339/96223180-1f118c00-0fab-11eb-94ce-352fa71f5950.png">

## Your environment
* Angularjs - v1.7.2
* Gridstack - v2 (https://github.com/gridstack/gridstack.js)

## Steps to reproduce
It is the default behaviour of gridstack placeholder

## Expected behaviour
What we exact want to do is when we resize any widget it will show us placeholder border (next to widget border). We want to change the height and width of that placeholder border to 4\*4 dimentions, we believe by default it is taking 1\*1 dimentions.
We also want default block in background as you can see in below image, that will provide hint to the user while resizing.

Find the image below for the expected behaviour.

<img width="1138" alt="Screenshot 2020-10-16 at 11 22 41 AM" src="https://user-images.githubusercontent.com/70004339/96220638-b45e5180-0fa6-11eb-9c13-8c43ffc63343.png">

We checked google for some solution and found this issue [#914](https://github.com/gridstack/gridstack.js/issues/914) but did not find any luck in our case.

Thanks In Advance :)
Ronak Pandya

**Comment by adumesny** [comment]
don't understand what you are asking. If you have min width/height of 4x4 it will not let you resize lower, but will 5x4, 6x4, etc...
if you are asking about doing only in increment of 4s (4x4, 8x4, 12x4) then you can achieve that by have a 3 column grid instead (so 1x1 = 4x4 of a 12 column grid).

Either way you need to provide a sample code showing the issue. can't debug your app.

**Comment by adumesny** [comment]
closing due to no response
