### ISSUE TITLE
How to get a 'GridStackNode' from addWidget() 

### ISSUE THREAD

**Issue by enricol96** [gridstack/gridstack.js#1415]
Hello,
I see in the documentation that events (like "dropped", "added") when triggered allow accessing the ```GridStackNode``` structure. Instead ```addWidget()``` returns only the HTML element (i.e. the ```<div>```) of the item inserted. 

My problem is that if I have a ```GridStackNode``` and I modify/add properties to it, then I am able to retrieve them when using the built-in ```save()``` function for the serialization of the grid. I'd like to do the same for the item returned by ```addWidget()```. 

So my question is: is it possible to get a ```GridStackNode``` for the added item when using ```addWidget()```?

I hope I was clear. Thanks

**Comment by adumesny** [comment]
`addWidget()` returns a `GridItemHTMLElement` which **is** an html element but with that extra field
```js
export interface GridItemHTMLElement extends HTMLElement {
  /** pointer to grid node instance */
  gridstackNode?: GridStackNode;
..}
```

also slack channel is better for questions. this is for bug reports...

**Comment by enricol96** [comment]
Thanks, exactly what I wanted. You're right, I'll ask on slack next time.
