### ISSUE TITLE
How to prevent grid item from resizing when the size of the container change

### ISSUE THREAD

**Issue by candrewtemenoscom** [gridstack/gridstack.js#1416]
## Subject of the issue
I would like to follow up with the issue "How to disable the responsiveness of gridstack #977" that was closed last year. I would like to see if it is still not possible with the latest gridstack. 

## Your environment
* latest version
* Chrome

## Steps to reproduce
Resize the browser size to make the grid smaller or bigger, the grid items inside the grid will adjust the size automatically (responsive).

## Expected behaviour
I would like to prevent the grid item from resizing itself when the container of the whole grid changes. This is different from explicit resize by dragging the resize handle. I would like to allow explicit resize and move but I do not want the grid item from changing size when the container size change.

## Actual behaviour
Grid item change size when the grid size change.

I understand that the gridstack was designed with this responsive behaviour in column based layout. I am just trying to see if you can suggest any work around to the behaviour that I trying to achieve. Thank you so much for any information you can provide.

**Comment by adumesny** [comment]
Posting another 'bug' doesn't help... 

gridstack is column based and there is no way around that - if the grid itself changes size (you can control that - the div doesn't have to be 100% width and could be hard coded - and use horizontal scroll bar when too big) **and you don't change the number of columns on the fly** using `setColumn()` then of course each column will shrink and therefore your items unless you adjust their column count to try to stay about the same width (ex: if grid is half the size, then you need to make each item twice as big, or half as many column with same count).

Not sure what you are trying to accomplish. if pixel perfect widths (how would someone access items outside the view and how do you set the grid overall width anyway), then this isn't the lib for you.

**Comment by candrewtemenoscom** [comment]
Thanks so much for your comments and pointer which is very helpful.

**Comment by adumesny** [comment]
don't forget to contribute time or $ to help support the lib. cheers...

**Comment by syed-asim** [comment]
I somehow made to grid partially non-responsive. Let say we have the grid element (div) which inside another element (outer div):
- Grid elemt (div): Set the min-width to the desired value (in my case 850 px) and set width to 100% 
- Outer element (div): Set overflow-x to scroll, and set max width equal to window.size using javascript i.e. 
`<div class="row visuals-container" id="visuals-container">
    <div id="visuals" class="grid-stack grid-stack-desktop"></div>
</div>`

 ` var minGridWidth = 850
    var visualContainerOuterDivEl = document.getElementById('visuals-container');
    window.addEventListener('resize', function () {
        let width = document.body.clientWidth;
        if (width <= minGridWidth) {
            visualContainerOuterDivEl.style.overflowX = "scroll";
        } else {
            visualContainerOuterDivEl.style.overflowX = "hidden";
        }
        visualContainerOuterDivEl.style.maxWidth = width + 'px';
    });`
I hope this will help!
