### ISSUE TITLE
maxRow not preventing dragIn from pushing past max limit

### ISSUE THREAD

**Issue by zeeh** [gridstack/gridstack.js#1419]
With maxRow:1 its possible to drag widgets into slots also when this slot isn´t empty. Eksemple: https://zeeh.no/vismeg/bug.html

**Comment by adumesny** [comment]
thanks. dragging in that grid works correctly (won't let you replace and push and item down) but dragging from the outside doesn't respect `maxRow`

**Comment by adumesny** [comment]
fixed in next release. not only does it prevent from being dropped over (and hide original) it then tries to append the item. ideally it would allow to push item to the right, but that's is what #149 is
