### ISSUE TITLE
gridstack.js version 2.0.2 - $el.draggable is not a function

### ISSUE THREAD

**Issue by DevHachi** [gridstack/gridstack.js#1420]
## Subject of the issue
Describe your issue here.

## Your environment
* Rails 6
* Webpacker
* GridStack 2.0.2
* google chrome(86.0.4240.111)

## Steps to reproduce
* install new rails app (optional)
* `import { GridStack } from 'gridstack';`
* call `GridStack.init()`

## Expected behaviour
It should add ui-draggable to the .grid-stack-item

## Actual behaviour
Whenever I call `GridStack.init()` I get the following error:
```
application.js:250 Error connecting controller

TypeError: $el.draggable is not a function
    at GridStackDDJQueryUI.draggable (gridstack-dd-jqueryui.js:103)
    at GridStack._prepareDragDropByNode (gridstack.js:1665)
    at GridStack._prepareElement (gridstack.js:1715)
    at gridstack.js:241
    at Array.forEach (<anonymous>)
    at new GridStack (gridstack.js:240)
    at Function.init (gridstack.js:2258)
    at Controller.connect (grid_controller.js:9)
    at Context.connect (context.js:23)
    at Module.connectContextForScope (module.js:39)
```

I use the Grid inside a stimulus controller.

```
import { GridStack } from 'gridstack';

import { Controller } from 'stimulus';

export default class extends Controller {
  connect() {
    GridStack.init({
      column: 3
    });
  }
}
```

It seems like the import of the jquery inside your library is not working correctly, because I can call `$('.grid-stack').draggable();` inside my application.js without any problems.

**Comment by adumesny** [comment]
wondering if it's a timing issue ? can you call `$('.grid-stack').draggable()` right before you call `GridStack.init()` ?
I import jq-ui this way in `GridStackDDJQueryUI.ts`
```js
// TODO: TEMPORARY until can remove jquery-ui drag&drop and this class and use HTML5 instead !
// see https://stackoverflow.com/questions/35345760/importing-jqueryui-with-typescript-and-requirejs
import * as $ from './jquery';
export { $ };
export * from './jquery-ui';
```

**Comment by DevHachi** [comment]
yes I can call it right before `GridStack.init()`

**Comment by adumesny** [comment]
you need to post a reproduceable test case... can't debug it remotely.

**Comment by janus007** [comment]
I can confirm that I experience the same thing. I import GridStack in Typescript

`import { GridStack } from 'gridstack';
import 'gridstack/dist/gridstack.css';

export class PageDesigner {

    constructor() {

        alert('PageDesigners');


        //this.initEventHandlers();
    }
    initGridStack() {

        GridStack.init();
    }
    initEventHandlers() {
        window.addEventListener('load', function () {
            let gs = GridStack.init();
        })
    }

}
`
I should mention that I've a jquery included as script on my page.

And in $.ready I call initGridStack, I did this to see if it could be a timing issue.

I noticed however that $el.draggable is using 
![image](https://user-images.githubusercontent.com/1786020/97501652-efcb2980-1971-11eb-8acb-2fb13257b5c5.png)

which I included in as s script reference. After that I took the jQuery-file that is included in Gridstack and referenced that from script reference, but that changed nothing either.

**Comment by adumesny** [comment]
you can't have multiple copies of jquery, I think jquerui-ui then doesn't add itself to the correct one... and I have not enaled you to bring your own jq in 2.x yet.

**Comment by janus007** [comment]
Okay, I understand.
Thank you for a fast reply :)

**Comment by adumesny** [comment]
[dist.zip](https://github.com/gridstack/gridstack.js/files/5475995/dist.zip)

@janus007 @DevHachi Can you guys this this patched version and let me know if it works ? you WILL need to include jq and jq-ui yourself (or have another project bring it in, files are under gridstack/src/jq/ otherwise)

I include jq/jq-ui using standard way, reverted any changed made to them and changed webpack to find those "module", ut not ready to push as karma test still can't find jq.

gridstack-dd-jqueryui.ts
```js
// export jq symbols see
// https://stackoverflow.com/questions/35345760/importing-jqueryui-with-typescript-and-requirejs
// https://stackoverflow.com/questions/33998262/jquery-ui-and-webpack-how-to-manage-it-into-module
import * as $ from 'jquery';
export { $ };
import 'jquery-ui';
```
webpack.config.js
```json
  resolve: {
    extensions: [ '.ts', '.js' ],
    alias: {
      'jquery': '/src/jq/jquery.js',
      'jquery-ui': '/src/jq/jquery-ui.js',
    }
  },
```

**Comment by adumesny** [comment]
@janus007 @DevHachi any update ^^^ ? if not I will close this as 3.0 now has HTML5 drag&drop so not focusing on JQ anymore unless it's a simple fix above...

**Comment by janus007** [comment]
@adumesny Thank you very much for this follow up.
We chose to develop our own solution from scratch without jQuery, using Typescript.

**Comment by adumesny** [comment]
kinda like v3 - no jquery, all typescript and html5 drag&drop...

**Comment by adumesny** [comment]
closing unless I hear back from @DevHachi
