### ISSUE TITLE
 An example that can utilize gridstack.js in Vue.js

### ISSUE THREAD

**Issue by gurgus0189** [gridstack/gridstack.js#1440]
## Subject of the issue

There seems to be not a lot of examples or explanations of gridstack js using Vue.js.
Even at https://gridstackjs.com/demo/index.html, there are no examples other than Vue2.js and Vue3.js.

Is there any way to get an explanation or example using Vue? If so, would you know where it is?

## Your environment
* version of gridstack.js
  - 2.1.0
* which browser and its version
  - Chrome browser latest

**Comment by adumesny** [comment]
you mean explanation on how to use VueJS ? that would not be on their site and others...
As for examples with gridstack, we have 2 examples now (did you read the source code ?) which is a lot MORE than any other frameworks (you don't see any Angular or React example - which are much more popular).

closing, unless I'm misunderstanding you.
