### ISSUE TITLE
Drop blank rows?

### ISSUE THREAD

**Issue by austinwbest** [gridstack/gridstack.js#1447]
Not an issue but a question (possible request)

Lets say i have 6 rows of boxes, i grab # 5 and push it down. If you do this slow it also pushed # 6 at the same time instead of jumping it. Now when this happens it leaves a gap in there which brings me to my question, can this gap be purged? a dropBlankRows: true|false on the grid init

The y was 2, 4, 6, 8, 10, 12 and after the move it became 2, 4, 6, 8, 14, 16 so essentially i would have dead space that i now need to manually move 14 up to 10 and 16 up to 12.

Hopefully that is clear enough and be even better if there is a way to do it and i simply overlooked it.

**Comment by adumesny** [comment]
have you tried `float: false` to essentially swap row 5 and 6 together (won't let you have dead space vertically) ?
also slack channel is best for questions and you should post a pic/running code next time. `dropBlankRows: true|false` would e very specific to your need and likely not scale out.
