### ISSUE TITLE
Get the position before oneColumnMode

### ISSUE THREAD

**Issue by thomasv04** [gridstack/gridstack.js#1459]
Hello everyone, I will try to make myself understood as clearly as possible.

In the plugin I understood that there were two positions (x and y) for each widget, a normal position and one for the oneColumnMode. But I would like to know if it was possible to get the "desktop" position of the widget all the time ? A bit like "_beforeDragX" and "_beforeDragY" when dragging a widget.

I hope I have been precise enough in what I have been able to write.

Thank you very much in advance for your help.

**Comment by adumesny** [comment]
please use the slack channel for questions - this is for bugs only.
