### ISSUE TITLE
Scrollbar in widget behaves oddly in Safari

### ISSUE THREAD

**Issue by marknelson** [gridstack/gridstack.js#1461]
## Subject of the issue
Attempting to create a widget with embedded scrollbars

## Your environment
Gridstack 2.2.0
Chrome 86
Safari 14.0

## Steps to reproduce
https://jsfiddle.net/snorkelman/9517g0ay/7/

## Expected behaviour
One of the three widgets has horizontal and vertical scrollbars. They should both be present and usable.

## Actual behaviour
On Safari, the horizontal scrollbar is rendered at the very bottom of the widget - out of the visible area. To get to it, you have to perform vertical scrolling. This is problematic behavior, and the question I have is whether this is me, the library, or the browser.

Note also that on Firefox the three widgets are initially laid out differently, which is also problematic.

**Comment by adumesny** [comment]
no idea - but Edge renders ok like Chrome, and yeah in FF windows the order is reversed (unlike other grids I've seen that render ok). You will will have debug by removing styles and see what triggers this...

Please re-open if a gridstack bug. thanks.
