### ISSUE TITLE
Widget disappear when moving to a grid below

### ISSUE THREAD

**Issue by zgilewski** [gridstack/gridstack.js#1463]
## Subject of the issue
I have two grids one below other. When trying to move widget from one grid to other, in normal case when dragging we see gridstack placeholder, and when dropping widget is moved from one grid to second.
But, It is possible to drag widget on second grid, and move it in a way when gridstack placeholder is not showed, then dropping that widget causing issue, that this widget is lost (removed from first grid but not added to second grid nodes array).

## Your environment
Gridsdtack 2.2.0
Chrome

## Expected behaviour
Widget should be not removed from first grid till it will not be correctly added to second grid or it should be not possible to drop widget when there is no placeholder.

## Actual behaviour
Actually I can drop widget when there is no placeholder and this widget is loosed (not available anymore).

This issue can be reproduced also in Two grids demo with small change that two grids are placed one below other.
![image](https://user-images.githubusercontent.com/28985410/99360534-0568aa80-28b1-11eb-8146-649128a11ee3.png)
widget which is somehow outside of grid is not anymore in nodes array,

**Comment by zgilewski** [comment]
Adding also view of prevItems and newItems parameters from dropped event where we can see that in both nodes are empty:
![image](https://user-images.githubusercontent.com/28985410/99361434-562cd300-28b2-11eb-839c-d095c75dd2f7.png)

**Comment by adumesny** [comment]
dup of #909 - if the top grid changes height as you move down, it will mess the grid below reception.
