### ISSUE TITLE
I drag a non-resizeable `newWidget`, but it can still be resized

### ISSUE THREAD

**Issue by youcanping** [gridstack/gridstack.js#1472]
## Subject of the issue
I drag a non-resizeable `newWidget`, but it can still be resized

## Your environment
* 2.2.0
*  Google Chrome 86.0.4240.198

## Steps to reproduce
https://jsfiddle.net/youcanping/671qm5tc/6/

## Expected behaviour
`newWidget`  non-resizeable

## Actual behaviour
`newWidget`  resizeable

**Comment by adumesny** [comment]
I see the problem, but your sample didn't have `data-gs-no-resize: true` but false! it's also nice to trim to are minimum so you can focus on the bug...

https://jsfiddle.net/adumesny/2cjvutdx/

**Comment by youcanping** [comment]
> I see the problem, but your sample didn't have `data-gs-no-resize: true` but false! it's also nice to trim to are minimum so you can focus on the bug...
> 
> https://jsfiddle.net/adumesny/2cjvutdx/

![image](https://user-images.githubusercontent.com/30832864/100042426-64e13000-2e46-11eb-8c09-0ce1296238a5.png)

**Comment by youcanping** [comment]
> > I see the problem, but your sample didn't have `data-gs-no-resize: true` but false! it's also nice to trim to are minimum so you can focus on the bug...
> > https://jsfiddle.net/adumesny/2cjvutdx/
> 
> ![image](https://user-images.githubusercontent.com/30832864/100042426-64e13000-2e46-11eb-8c09-0ce1296238a5.png)

I try setting `data-gs-no-resize: true`， dragIn `newwidget` also can resize

**Comment by adumesny** [comment]
right, it's a bug (why I didn't close it) but the sample you provided didn't really show the bug, mine does...

**Comment by youcanping** [comment]
> right, it's a bug (why I didn't close it) but the sample you provided didn't really show the bug, mine does...

This is a good library. My project is using this library. Are there any plans to resolve this bug?

**Comment by adumesny** [comment]
you can try fixing it yourself, or contribute $$ to help this effort as I can't address every single bugs...

**Comment by adumesny** [comment]
fixed in upcoming 3.1.1
