### ISSUE TITLE
Issue with Nested Grid - v.3.30

### ISSUE THREAD

**Issue by GFree4Me** [gridstack/gridstack.js#1501]
The grid components on a nested grid seem to have full width rather than their respective sizing. It seems almost as if the custom stylesheet created is not properly being applied to the elements.

* (3.3.0) gridstack-h5.js AND HTML5
* Chrome

https://gridstackjs.com/demo/nested.html

**Comment by adumesny** [comment]
sorry I just fixed that... CSS was missing.

**Comment by GFree4Me** [comment]
Wow that was fast! Thank you!
