### ISSUE TITLE
3.0.0 HTML5 drag'n'drop initial GridStack.enable() Error

### ISSUE THREAD

**Issue by infime** [gridstack/gridstack.js#1505]
## Subject of the issue

Calling enable() with the new native drag'n'drop throws an Error.

## Your environment
* v3.0.0 HTML5
* Chrome 86.0.4240.111

## Steps to reproduce

Will follow up with a reproduction

## Expected behavior

Calling enable should not throw an error

## Actual behavior
Stack trace
```
gridstack-dd-native.js?9be6:33 Uncaught (in promise) TypeError: Cannot read property 'enable' of undefined
    at eval (gridstack-dd-native.js?9be6:33)
    at Array.forEach (<anonymous>)
    at GridStackDDNative.resizable (gridstack-dd-native.js?9be6:31)
    at eval (gridstack-dd.js?a66a:484)
    at Array.forEach (<anonymous>)
    at GridStack.gridstack_1.GridStack.resizable (gridstack-dd.js?a66a:473)
    at eval (gridstack.js?7e36:558)
    at Array.forEach (<anonymous>)
    at GridStack.enableResize (gridstack.js?7e36:558)
    at GridStack.enable (gridstack.js?7e36:527)
```

**Comment by adumesny** [comment]
thanks for the effort! let find a reproduceable case and I will fix it!

looks like you are calling enable on a static grid maybe ? (no DD created and jumping to enabling on null DD)

ironically https://gridstackjs.com/demo/static.html is exactly to test this BUT it uses setStatic(true/false) which is the same as enable()/disable(). I need to refresh my memory why we have both method but only one works in your case...

**Comment by infime** [comment]
Nope no static grid involved, I think it's potentially related to using `load()`. I'll get a reproduction going.

**Comment by infime** [comment]
https://jsfiddle.net/anzojxum/19/ reproduces the issue. It's being triggered when calling `enableResize` when at least one of the widgets is `locked`

**Comment by adumesny** [comment]
ha, that makes sense... taking a look.
