### ISSUE TITLE
v3.0.0 Dragging new widget broken when switching JQ -> H5 

### ISSUE THREAD

**Issue by Mopster** [gridstack/gridstack.js#1507]
Very excited to see removal of jQuery dependency, my project is running an old jQuery version and was getting conflicts with the newer embedded jQuery version. So I upgraded to v3.0.0 and migrated the code (`data-gs-width` -> `gs-w` etc...).

## Subject of the issue
New widget not being recognized when dragging into grid. Works with `gridstack-jq.js` but not with `gridstack-h5.js`. 

## Your environment
* v3.0.0 HTML5 
* Symfony 3.4
* jQuery 2.2.4
* Firefox 83.0 (on Ubuntu 20.04) 
* Using 24 columns, updated the custom CSS with the correct classes

## Steps to reproduce

I have a `.newWidget`  div which has its content dynamically replaced by a dropdown select field with `jquery.on('change')` which fetches the html content using ajax. I have a couple dozen widgets our users can drag onto the grid to build their own dashboard.

```
        <div id="report-new-block" style="margin-bottom: 15px;" class="col-sm-4 panel text-center">
            <div class="newWidget grid-stack-item" gs-w="6" gs-h="10">
                <div class="card-body grid-stack-item-content">
                    {{ 'select a block on the right'|trans({}, 'reporting') }}
                </div>
            </div>
        </div>
```

My grid init : 

```
            var grid = GridStack.init({
                animate: true,
                float: true,
                alwaysShowResizeHandle: /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(
                    navigator.userAgent
                ),
                resizable: {
                    handles: 'e, se, s, sw, w'
                },
                removable: '#trash',
                removeTimeout: 100,
                column: 24,
                cellHeight: '20px',
                acceptWidgets: function(i, el) { return true; }
            });
```
and the jQuery.on('change') listener : 

```
                $('#report-block-select').on('change', function () {
                    var value = $(this).val();
                    if (value) {
                        var url = Routing.generate('reportblock_preview', {'widget' : value, 'user' : '{{ user|default }}', 'group' : '{{ group|default }}', 'period' : '{{ period|default }}'});
                        $.get(url, function(data) {})
                            .done(function(data) {
                                $('#report-new-block .card-body').html(data);
                                $('#report-new-block .grid-stack-item').draggable({
                                    revert: 'invalid',
                                    handle: '.grid-stack-item-content',
                                    scroll: false,
                                    appendTo: '#report-grid',
                                    helper: 'clone'
                                });
                            })
                            .fail(function(data) {
                                alert("{{ 'failed'|trans|escape('js') }}");
                            })
                        ;
                    }
                });
```

Does the HTML5 version require a different 'draggable' in order to work ?

## Expected behavior
When dragging the new widget onto the grid, it snaps the widget onto the grid and allows it to be dropped and stick to the grid.

## Actual behavior
When dragging the new widget, it is being dragged, but the grid doesn't recognize it. It doesn't behave like it snaps to the grid and it doesn't allow me to place the widget inside the grid. Dropping the widget doesn't do anything.

**Comment by adumesny** [comment]
you can't use a mix of JQ and html5 for the drag and drop. you need to have GrisStack enable draging on your external items (similar to setting `removable: '#trash'` which it will find and make it drop target!)
look at the sample https://github.com/gridstack/gridstack.js/blob/develop/demo/two.html or others. Your grid options should have:
(this is how I isolate JQ vs HTML5)

```js
      dragIn: '.newWidget .grid-stack-item', // class that can be dragged from outside
      dragInOptions: { revert: 'invalid', scroll: false, appendTo: 'body', helper: 'clone' }, // not sure it matters for HTML5 actually...
      acceptWidgets: true // I was showing a method but true/false also works
```

**Comment by Mopster** [comment]
@adumesny thanks! That helped me on the way to making it work!
