### ISSUE TITLE
How to add component to addWidget in react?

### ISSUE THREAD

**Issue by gurgus0189** [gridstack/gridstack.js#1508]
## Your environment
* gridstack.js version 2.1.0
* Chrome browser latest

## Subject of the issue
I am using gridstack.js in React

Create a widget component in React and want to insert the widget component in the el part using addWidget(el,option).

example)
addWidget( <Widget />, node)

However, it seems that only the html element is possible for the el part.

Is it possible to solve the problem by inserting the component in the el part or using another method?

**Comment by adumesny** [comment]
please use slack channel for question and also look at the React section that likely will answer your Q. https://github.com/gridstack/gridstack.js#gridstackjs-for-specific-frameworks
