### ISSUE TITLE
V3 h5 not draggable when content is table/span

### ISSUE THREAD

**Issue by gondias** [gridstack/gridstack.js#1511]
Hi,
Was checking the latest version and found an issue  when the content of the tile is a table using 100% of width and height of the available space. In this case the drag does not happen, therefore it will not work. Was going through older versions and that is not an issue. In the case of the content being a div it works

I am using V3.0.0 and not using the jquery.
I am referencing gridstack.css and gridstack-h5.js

I am using chrome Version 87.0.4280.66
and also tested it with firefox version 82.0.2

Here you should be able to reproduce it:
https://jsfiddle.net/gondias/2b5hxnvm/2/

If you comment line 28 and uncomment line 25 you will notice it is not possible to drag the tiles in the grid.
If you comment line 25 and uncomment line 28 you will notice it is possible to drag the tiles in the grid.

Kind regards

**Comment by adumesny** [comment]
thanks I simplified the test
https://jsfiddle.net/adumesny/wuj69dcL/

it works IFF you click outside the div/table content (in both cases.. clicking on div text will NOT work either (eats the event).
but with that said, **switching to jq version works**, so something we might be able to do. Need to research native drag event  propagation...

**Comment by typescriptguru** [comment]
> but with that said, **switching to jq version works**, so something we might be able to do. Need to research native drag event propagation...

@adumesny  in jq version, dragging input type element does not work.
