### ISSUE TITLE
Input type elements cannot be dragged when it has parent div (ex. text, select, numeric types)

### ISSUE THREAD

**Issue by typescriptguru** [gridstack/gridstack.js#1514]
## Subject of the issue
I am building form builder using gridstackjs, so users can drag form element from outside inside the form, and move/resize inside the form. 
`<input type="text"/>` cannot be draggable if it has parent `div`, 
I also noticed normal `div` cannot be dragged if it has parent `div`.

## Your environment
I am using v3.0.0, and tested on html5 native dnd.

## Steps to reproduce
Here's demo you can reproduce - [https://jsfiddle.net/cwrjq5z3/9/](https://jsfiddle.net/cwrjq5z3/9/)

## Expected behavior
Input should be able to be draggable no matter it has div as parent or not.

## Actual behavior
Input is not dragged when it has parent div

**Comment by adumesny** [comment]
thanks for good example. same issue as #1511

**Comment by adumesny** [comment]
you say: " in jq version, dragging input type element does not work." so did this *ever* worked on any version or is that a feature request then ?

re-opening since separate issue.

**Comment by typescriptguru** [comment]
Dragging input never worked with jq version.
So I tried html dnd, and it seemed working at first time, but when I add parent div to input element, it stopped working

**Comment by adumesny** [comment]
did you use older version of gridstack before where it used to work or are you new to using it ?

**Comment by typescriptguru** [comment]
I tried v2.2.0 which only supports jquery ui dragging, and input dragging did not work.
I tried to set `cancel: null` in `draggable` option, and input seemed working, but then input stopped focusing

**Comment by typescriptguru** [comment]
@adumesny Do we have any ETA for this to be fixed?

**Comment by adumesny** [comment]
whoa, you just filed it and asking when it will be fixed already ? you are welcome to make a fix suggestion or contribute $ to help this project...

**Comment by adumesny** [comment]
fixed in upcoming 3.1.1

**Comment by typescriptguru** [comment]
Thank you, @adumesny
