### ISSUE TITLE
Dragging and resizing issues

### ISSUE THREAD

**Issue by krishnavyas3497** [gridstack/gridstack.js#1533]
I have many grids. some can be resizable and some not. I provided data-gs-no-resize="true" data-gs-no-move="true" data-gs-locked="yes" these attributes in my element but it is resizable when i call grid.movable method in version 0.3.0. 

grid.movable(id,true)

in movable method node.noMove value is not getting from node instead value set from parameter which is passed 2nd.

node.noMove=!(parameter || false) 

Can you please provide solution from this?

**Comment by adumesny** [comment]
first off are you using latest 3.1.2 or did you mean 0.3.0 ? (which I don't support)
also you need to provide a reproduceable test case (see instructions). re-open when you do...
