### ISSUE TITLE
两个网格（grid）之间不能互相拖动，被拖动的item被删除了

### ISSUE THREAD

**Issue by panfengyuan** [gridstack/gridstack.js#1539]
## Subject of the issue
Describe your issue here.

## Your environment
* version of gridstack.js AND if using HTML5 vs Jquery plugin (v3+)
* which browser and its version

## Steps to reproduce
MUST provide a working demo (keep it simple!) ad steps, you can use 
https://jsfiddle.net/adumesny/jqhkry7g as a base.

## Expected behavior
Tell us what should happen

## Actual behavior
Tell us what happens instead

**Comment by adumesny** [comment]
no subject I can understand, and no info/same code. closing issue until you add file a proper bug please.
