### ISSUE TITLE
H5 Delay on dropping elements on latest Chrome MacOS Big Sur

### ISSUE THREAD

**Issue by kevinlandsberg** [gridstack/gridstack.js#1541]
## Subject of the issue
Disturbing delay on dropping grid item after they were dragged around

## Your environment
* Gridstack.js version: 3.1.2 with HTML5
* Google Chrome Version 87.0.4280.88 (Official Build) (arm64)

## Steps to reproduce
Visit homepage of library and drag any grid-item of any example. 

## Expected behavior
No delay on dropping grid-items after they were dragged around

## Actual behavior
Delays 1-2 seconds on dropping grid-items after they were dragged around

**Comment by adumesny** [comment]
what browser is that for and do you see the same slowdown in other browsers (which I don't see on chrome/Win10)

**Comment by kevinlandsberg** [comment]
Hi @adumesny ,

this slowdown happened to me on Googles Chrome and Firefox on MacOS Big Sur latest version, also latest versions of both browsers. In Safari gridstack does not seem to work anyway...
I cannot reproduce these issues on Windows on any browser also...

**Comment by adumesny** [comment]
no longer seeing the issue with Chrome and 3.1.3-dev build (appears fixed), BUT still seeing on Safari! (it animates back to original location (if I force a clone copy I can see old+new), then to new location - hence the 300msec delay before animating to dropped location.

**Comment by kevinlandsberg** [comment]
@adumesny , correct. Still seeing delays on dropping elements.

**Comment by adumesny** [comment]
fixed in next 3.1.4 release
