### ISSUE TITLE
两个grid-stack之间移动item，多次来回移动后，两边出现联动的样式变化;环境是angular11.0.0版本使用的是gridstack-h5.js  3.1.2

### ISSUE THREAD

**Issue by panfengyuan** [gridstack/gridstack.js#1542]
## Subject of the issue
两个不是嵌套的网格，grid1给的w=12,h=5,grid2给的是w=4,h=40，两个grid之间移动item，多次来回移动后，两边出现联动的样式变化，grid1里面的item移动grid2，grid2里面有至少一个item，跟着变化一样的w=4和h=40，同样的grid2里面的item移动到gird1，grid2里面至少有一个item跟着变化w=12和h=5。

## Your environment
* version of gridstack-h5.js 3.1.2
* Google Chrome 87.0.4280.88（正式版本） （64 位）

## Steps to reproduce
MUST provide a working demo (keep it simple!) ad steps, you can use 
https://jsfiddle.net/adumesny/jqhkry7g as a base.

## Expected behavior
（1）grid1的item移动到grid2，设置w=4,h=40,并正确展示在grid2以及其他item的大小不变；
（2）grid2的item移动到grid1，设置w=12,h=5,并且置顶显示刚刚移动进来的item以及其他item的大小不变。

## Actual behavior
（1）在两个grid之间移动时，有时候item会莫名消失；
（2）在来回移动多次后出现左右两边item样式有联动变化，只是设置被移动的item大小，但是其他的item也跟着变化，而且还没有变化触发出来的事件。

https://user-images.githubusercontent.com/28857216/102840190-45392980-443d-11eb-9d2a-576112919ca0.mp4

**Comment by panfengyuan** [comment]
环境是angular11.0.0版本使用的是gridstack-h5.js  3.1.2

**Comment by adumesny** [comment]
sorry, I don't understand Chinese, nor is there an example showing issue. closing you provide example.
