### ISSUE TITLE
Move an item between two Grids, and after moving back and forth for many times, the two sides have a linkage style change

### ISSUE THREAD

**Issue by panfengyuan** [gridstack/gridstack.js#1543]
## Subject of the issue
Two not nested grids, grid1 to w = 12, h = 5, grid2 is w = 4, h = 40, between two grid mobile item, after moving back and forth many times, both sides appear linkage style changes, grid1 item inside mobile grid2 grid2 there is at least one item, along with the changes of w = 4 and h = 40, the inside of the same grid2 item moved to gird1, grid2 inside at least one item to follow change w = 12 and h = 5.

## Your environment
* version of gridstack-h5.js 3.1.2  and angular 11.0.0
* Google Chrome 87.0.4280.88

## Steps to reproduce
MUST provide a working demo (keep it simple!) ad steps, you can use 
https://jsfiddle.net/adumesny/jqhkry7g as a base.

## Expected behavior
(1) Item from Grid1 is moved to Grid2, set W =4, H =40, and display correctly in Grid2 and other item size unchanged;

(2) The item from Grid2 is moved to Grid1, set W =12, H =5, and the top displays the size of the item just moved in and other items unchanged.

## Actual behavior
(1) When moving between two grids, sometimes the item will inexplicably disappear;

(2) After moving back and forth for many times, the item styles on the left and right sides have linkage changes, only setting the size of the item to be moved, but other items also change accordingly, and the event triggered by the change has not been changed.

https://user-images.githubusercontent.com/28857216/102840190-45392980-443d-11eb-9d2a-576112919ca0.mp4

**Comment by adumesny** [comment]
you must provide an example showing the issue. showing my your code in video doesn't help me reproduce and fix it. It's very likely a bug in your code, but I'm not going to debug it for you.

**Comment by panfengyuan** [comment]
> 您必须提供一个显示问题的示例。在视频中显示我的代码并不能帮助我复制和修复它。这很可能是您代码中的错误，但我不会为您调试它。
> 
> 它是否在two.html示例中复制？


<div class="topBox">
	
	<div class="leftBox">
		<div class="leftNavTitle"> 图表目录</div>
		<div class="leftGrid">
			<div class="grid-stack text_grid" id="text_grid">
				<div class="grid-stack-item sub" draggable="true" *ngFor="let item of this.leftnav" [attr.data-id]="item.Id" gs-w="12" gs-h="5">
					<div class="grid-stack-item-content">
						<div class="listItemTitle">{{item.Title === " "?item.Id:item.Title}}</div>
						<app-standard-chart class="app-standard-chart" [eleId]='item.Id' [paramHeight]='height' *ngIf="item.Status === true"></app-standard-chart>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="rightBox">
		<div class="rightGrid">
			<div class="grid-stack chart_grid" id="chart_grid">
				<div class="grid-stack-item sub" draggable="true" *ngFor="let item of this.gridstackList" [attr.data-id]="item.Id" gs-w="4" gs-h="40">
					<div class="grid-stack-item-content">
						<div class="listItemTitle">{{item.Title === " "?item.Id:item.Title}}</div>
						<app-standard-chart class="app-standard-chart" [eleId]='item.Id' [paramHeight]='height' *ngIf="item.Status === true"></app-standard-chart>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	
// gridstack 初始化
  textGrid;
  chartGrid;
  gridInit() {
    const self = this;
    let nestOptions = {
      alwaysShowResizeHandle: /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),
      cellHeight: 10,
      resizable: { handles: 'e, se, s, sw, w' },
      acceptWidgets: '.sub',
      disableOneColumnMode: true,
      margin: 10,
    };
    self.textGrid = GridStack.init(nestOptions, '.text_grid');
    self.textGrid.enableResize(false);//禁止手动调大小
    self.chartGrid = GridStack.init(nestOptions, '.chart_grid');
    // 监听事件
    self.addEvents(self.textGrid, 1);
    self.addEvents(self.chartGrid, 2);
    
  }

  // 监听事件
  addEvents(grid, id) {
    let self = this;
    let g = (id !== undefined ? 'grid' + id + ' ' : '');

    grid.on('added removed change', function (event, items) {
      console.log(event.type);
    });

    // 拖动\拉伸
    grid.on('dragstart dragstop resizestart resizestop', function (event, el) {
      console.log(event.type);
      if(event.type === 'resizestop'){
        console.log(el.dataset.id);
        self.echartConfig.resizeChart(el.dataset.id);
      }
    });

    // 从某一网格移除
    grid.on('dropped', function (event, previousWidget, newWidget) {
      if (previousWidget) {
        console.log(g + 'dropped - Removed widget from grid:', previousWidget);
      }
      if (newWidget) {
        console.log(g + 'dropped - Added widget in grid:', newWidget);
        let _el = newWidget.el;
        if (id === 1) {
           grid.update(_el, {x:0, y:0, w:12, h:5});
        } else if (id === 2) {
          grid.update(_el,{x:0, y:0,w:4,h:40});
          grid.resizable(_el, true);
          self.echartConfig.resizeChart(newWidget.el.getAttribute('data-id'));
        }
      }
    });
  }

**Comment by panfengyuan** [comment]
`
<div class="topBox">
	
	<div class="leftBox">
		<div class="leftNavTitle"> 图表目录</div>
		<div class="leftGrid">
			<div class="grid-stack text_grid" id="text_grid">
				<div class="grid-stack-item sub" draggable="true" *ngFor="let item of this.leftnav" [attr.data-id]="item.Id" gs-w="12" gs-h="5">
					<div class="grid-stack-item-content">
						<div class="listItemTitle">{{item.Title === " "?item.Id:item.Title}}</div>
						<app-standard-chart class="app-standard-chart" [eleId]='item.Id' [paramHeight]='height' *ngIf="item.Status === true"></app-standard-chart>
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="rightBox">
		<div class="rightGrid">
			<div class="grid-stack chart_grid" id="chart_grid">
				<div class="grid-stack-item sub" draggable="true" *ngFor="let item of this.gridstackList" [attr.data-id]="item.Id" gs-w="4" gs-h="40">
					<div class="grid-stack-item-content">
						<div class="listItemTitle">{{item.Title === " "?item.Id:item.Title}}</div>
						<app-standard-chart class="app-standard-chart" [eleId]='item.Id' [paramHeight]='height' *ngIf="item.Status === true"></app-standard-chart>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
	
// gridstack 初始化
  textGrid;
  chartGrid;
  gridInit() {
    const self = this;
    let nestOptions = {
      alwaysShowResizeHandle: /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),
      cellHeight: 10,
      resizable: { handles: 'e, se, s, sw, w' },
      acceptWidgets: '.sub',
      disableOneColumnMode: true,
      margin: 10,
    };
    self.textGrid = GridStack.init(nestOptions, '.text_grid');
    self.textGrid.enableResize(false);//禁止手动调大小
    self.chartGrid = GridStack.init(nestOptions, '.chart_grid');
    // 监听事件
    self.addEvents(self.textGrid, 1);
    self.addEvents(self.chartGrid, 2);
    
  }

  // 监听事件
  addEvents(grid, id) {
    let self = this;
    let g = (id !== undefined ? 'grid' + id + ' ' : '');

    grid.on('added removed change', function (event, items) {
      console.log(event.type);
    });

    // 拖动\拉伸
    grid.on('dragstart dragstop resizestart resizestop', function (event, el) {
      console.log(event.type);
      if(event.type === 'resizestop'){
        console.log(el.dataset.id);
        self.echartConfig.resizeChart(el.dataset.id);
      }
    });

    // 从某一网格移除
    grid.on('dropped', function (event, previousWidget, newWidget) {
      if (previousWidget) {
        console.log(g + 'dropped - Removed widget from grid:', previousWidget);
      }
      if (newWidget) {
        console.log(g + 'dropped - Added widget in grid:', newWidget);
        let _el = newWidget.el;
        if (id === 1) {
           grid.update(_el, {x:0, y:0, w:12, h:5});
        } else if (id === 2) {
          grid.update(_el,{x:0, y:0,w:4,h:40});
          grid.resizable(_el, true);
          self.echartConfig.resizeChart(newWidget.el.getAttribute('data-id'));
        }
      }
    });
  }`

**Comment by panfengyuan** [comment]
> you must provide an example showing the issue. showing my your code in video doesn't help me reproduce and fix it. It's very likely a bug in your code, but I'm not going to debug it for you.
> 
> does it reproduces in two.html example ?

It is not convenient to provide examples, only this part of the code is provided, HTML and TS
[new 13.txt](https://github.com/gridstack/gridstack.js/files/5733441/new.13.txt)

**Comment by adumesny** [comment]
looks like you are using angular... by the way you don't need `this.` in the ngFor loop (implicitly uses that class members) `*ngFor="let item of this.leftnav"`
