### ISSUE TITLE
Installing Issue

### ISSUE THREAD

**Issue by ArunRK-Finsurge** [gridstack/gridstack.js#1544]
## Subject of the issue
Error: HostResourceLoader: loader(D:/sample/node_modules/gridstack/dist/gridstack.min.css) returned a Promise

## Your environment
* version of gridstack.js is 3.1.2 AND if using HTML5 vs Jquery plugin (v3+)
* Chrome and Version 2020 up to date (Official Build) (64-bit)

**Comment by adumesny** [comment]
I don't know what to make of your 'bug'. make sure you do have that file and that it looks like a CSS file and that it's 3.1.2
closing until you can show issue.
