### ISSUE TITLE
Enable / Disable Move does not really disable move :-)

### ISSUE THREAD

**Issue by cyril-iselin** [gridstack/gridstack.js#1545]
## Subject of the issue
Enable / Disable Move does not really disable move :-)

## Your environment
H5

## Steps to reproduce
https://jsfiddle.net/unrdcs89/

- Run Sample
- Re-Enable this line (//grid.enableMove(false, true);)
- You can still drag  (not so easy, but possible, first click won't drag, second click you can start drag)

## Expected behavior
You should not be able to drag

## Actual behavior
You can drag

**Comment by adumesny** [comment]
I can't reproduced this (being able to drag second click) on Chrome mac. What browser are you on ?

**Comment by cyril-iselin** [comment]
Tested on Windows Chrome -> Version 87.0.4280.88 (Offizieller Build) (64-Bit)
Tested on Windows Edge -> Version 87.0.664.66 (Official build) (64-bit)
(not tested on firefox)

**Comment by adumesny** [comment]
ha, I can see on windows now (platform I usually on, was on mac to fix stupid Safari oddities :)
