### ISSUE TITLE
Issue Cannot destructure property 'clientX' of 't' as it is undefined

### ISSUE THREAD

**Issue by minhhungit** [gridstack/gridstack.js#1546]
Hello team, 
The error appear when we drag widget item by fast click and throw mouse

Error message

```
Uncaught TypeError: Cannot destructure property 'clientX' of 't' as it is undefined.
    at i._hasMoved (dd-resizable-handle.ts:106)
    at i._mouseMove (dd-resizable-handle.ts:80)
```
Attached gif image to reproduce 

![drag-error1](https://user-images.githubusercontent.com/2279508/103390688-69d18780-4b48-11eb-8037-122e93364986.gif)

**Comment by minhhungit** [comment]
Or we can reproduce it by left-click one time on the drag icon (don't hold the click), drag mouse and left click again.
Sometime it will throw error

**Comment by minhhungit** [comment]
more gif

![drag-error-reproduce](https://user-images.githubusercontent.com/2279508/103391857-f5014c00-4b4d-11eb-84bf-3095d4557e84.gif)

**Comment by adumesny** [comment]
fixed in next 3.1.3 release. Don't forget to contribute, especially since you are selling dashboard based on my code...

**Comment by minhhungit** [comment]
Thank you for your fixing @adumesny, I'm still new on this library so still lack of knowledge. I will try to contribute in future !

One more question,  like you said I am going to sell dashboard feature which is using gridstack as core, I want to ask if I can do it or any requirements I need to complete, thank you and happy new year !

Jin

**Comment by minhhungit** [comment]
Hi @adumesny I'm trying to donate gridstack as promise but pay.pal fee is too high, donate 10$ but take ~5$ fee (~50%), is there another way to donate like "buy me a coffee". I also see "venmo" donate link but it also does not work for me. Thank you

**Comment by minhhungit** [comment]
![image](https://user-images.githubusercontent.com/2279508/122177924-46a95300-ceb0-11eb-9bb4-1da8a7862426.png)

**Comment by adumesny** [comment]
you should be able to done as gift/friend in paypal which has no fees (other than conversion fees ?) if linked to your bank accound (instead of credit card). I'm not familiar how it works from overseas.
Usually I recommend venmo (owned by paypal) as they do no have fees (here is the USA at least) as it's between friends.

**Comment by minhhungit** [comment]
@adumesny  See, it's 5$ pay.pal fee, also I am not USA I can not registry a venmo account

Can you please create new donate account like "buy me a coffee" or "ko-fi" I guess it's easier for global users

![image](https://user-images.githubusercontent.com/2279508/122280130-1050ef80-cf13-11eb-9f1d-17ff174e7377.png)

**Comment by adumesny** [comment]
what do you mean by: new donate account like "buy me a coffee"
you mean another paypal account ? not sure how it would be different and if I can can create multiple accounts to my name/bank. Let me research oversea fees, as I had others have issues as well (though it wasn't fixed $5 which seems steep).

**Comment by adumesny** [comment]
@minhhungit I've added github sponsor - so yet another way to donate
