### ISSUE TITLE
How to add vue.js component in widget content?

### ISSUE THREAD

**Issue by wanghan-js** [gridstack/gridstack.js#1547]
## Subject of the issue
How to add vue.js component in widget content?

## Your environment
* latest gridstack.js using HTML5
* latest chrome

## Steps to reproduce
N/A

## Expected behavior
When using gridstack with vue, I want to insert a vue component in the widget.

## Actual behavior
But as per the docs of gridstack, I can only construct a dom string on the fly, and use the string as the 'content' property value to make a widget. That's too constrained, since I can't make a dom string in the vue framework.
Does anybody know how to achieve something like <slot> in vue, to make a vue component or a dom element in the vue template as a widget in gridstack?
Many thanks!

**Comment by adumesny** [comment]
use slack channel for question, this is for bugs. as with other frameworks you can use them to create the items/components and call `makeWidget()` to convert to gridstack
