### ISSUE TITLE
Separate 'change' event for browser window resize and drag/resize

### ISSUE THREAD

**Issue by Mopster** [gridstack/gridstack.js#1559]
## Subject of the issue

I'm using the `change` event to update all items of my grid in the database (x, y, w, h) when things are dragged or resized. But I just noticed the event also gets triggered when resizing the window to a 1-column size (and back to normal size). All widgets have their x, y, w, h changed to 1-column data (width = 1 for example).

Since I use an ajax call to update the widgets in database with the new data in the event, all the widgets get their data based on the 1-column grid. When another user visits the same grid, that user will get a long list of widgets of only width of 1 instead of the intended grid with widgets spread over 12 (or more) columns.

The `dropped` event doesn't get triggered when moving, `dragstop` and `resizestop` only give one element (that has been dragged/resized). but not the other affected elements (that get moved around). 

## Your environment

* v3.1.2 and v3.1.3
* Ubuntu 20.04, Firefox 84.0

## Steps to reproduce

https://gridstackjs.com/demo/advance.html

Resize the browser window to have the grid switch to 1-column, see the Console :

```
change 11 items: (x,y)=0,0 (x,y)=0,4 (x,y)=0,6 (x,y)=0,8 (x,y)=0,10 (x,y)=0,12 (x,y)=0,16 (x,y)=0,18 (x,y)=0,20 (x,y)=0,22 (x,y)=0,24 advance.html:87:15
change 11 items: (x,y)=0,0 (x,y)=4,0 (x,y)=8,0 (x,y)=10,0 (x,y)=0,2 (x,y)=2,2 (x,y)=8,2 (x,y)=0,4 (x,y)=4,4 (x,y)=8,4 (x,y)=10,4 advance.html:87:15
```

## Expected behavior

To have a separate event trigger for browser resize and widget changes by drag/resize. Having one dedicated for drag/resize changes allows me to keep the intended grid coordinates and dimensions in the DB and not have them updated every time someone resizes the browser window.

## Actual behavior

`change` gets triggered on window resize giving all widgets new coordinates and dimensions.

**Comment by adumesny** [comment]
this is as designed. it would be trivial for you to ignore saving the `change` events if the `grid.getColumn() === 1`

> The `dropped` event doesn't get triggered when moving

that's because you didn't drop it (from somewhere else)!

> `dragstop` and `resizestop` only give one element (that has been dragged/resized). but not the other affected elements (that get moved around)

that's because the others did get resized or directly moved around, but will be listed in the `change` list. This is all correct and let you decide how to handle the details to support all cases one might need.

**Comment by Mopster** [comment]
Understood.

I can add a conditional to not update the database when `grid.getColumn() === 1`, but when resizing back to big screen it'll trigger queries to update the widgets with the original values.

Would adding a `triggerChangeEventOnParentResize` option to the `column` function a possibilty (example below) ?

```
            var grid = GridStack.init({
               triggerChangeEventOnParentResize: false
            });
```

```
    onParentResize() {
        if (!this.el || !this.el.clientWidth)
            return; // return if we're gone or no size yet (will get called again)
        // make the cells content (minus margin) square again
        if (this._isAutoCellHeight) {
            utils_1.Utils.throttle(() => {
                let marginDiff = -this.opts.marginRight - this.opts.marginLeft
                    + this.opts.marginTop + this.opts.marginBottom;
                this.cellHeight(this.cellWidth() + marginDiff);
            }, 100);
        }
        if (!this.opts.disableOneColumnMode && this.el.clientWidth <= this.opts.minWidth) {
            if (this._oneColumnMode) {
                return this;
            }
            this._oneColumnMode = true;
            this.column(1, 'moveScale', this.opts.triggerChangeEventOnParentResize);
            this._resizeNestedGrids(this.el);
        }
        else {
            if (!this._oneColumnMode) {
                return this;
            }
            delete this._oneColumnMode;
            this.column(this._prevColumn, 'moveScale', this.opts.triggerChangeEventOnParentResize);
            this._resizeNestedGrids(this.el);
        }
        return this;
    }
```

```
    column(column, layout = 'moveScale', triggerChangeEvent = true) {
        if (this.opts.column === column) {
            return this;
        }
        let oldColumn = this.opts.column;
        // if we go into 1 column mode (which happens if we're sized less than minW unless disableOneColumnMode is on)
        // then remember the original columns so we can restore.
        if (column === 1) {
            this._prevColumn = oldColumn;
        }
        else {
            delete this._prevColumn;
        }
        this.el.classList.remove('grid-stack-' + oldColumn);
        this.el.classList.add('grid-stack-' + column);
        this.opts.column = this.engine.column = column;
        // update the items now - see if the dom order nodes should be passed instead (else default to current list)
        let domNodes;
        if (column === 1 && this.opts.oneColumnModeDomSort) {
            domNodes = [];
            this.getGridItems().forEach(el => {
                if (el.gridstackNode) {
                    domNodes.push(el.gridstackNode);
                }
            });
            if (!domNodes.length) {
                domNodes = undefined;
            }
        }
        this.engine.updateNodeWidths(oldColumn, column, domNodes, layout);
        // and trigger our event last...
        this._ignoreLayoutsNodeChange = true; // skip layout update
        if (triggerChangeEvent){
            this._triggerChangeEvent();
        }
        delete this._ignoreLayoutsNodeChange;
        return this;
    }
```

Or would it be possible to have an identifier in the event object to know when it's a window resize event so it can be skipped ?

**Comment by adumesny** [comment]
again trivial for you to ignore the FIRST change event in 12 column after you've detected you've been in 1 column mode, and only save later 'real' changes...

the only thing that could make sense is to have a columnChanged event. but again you can deduct that yourself since you will always have a change event and can check the before (cached) and after column count... so not something I will be adding.

**Comment by Mopster** [comment]
Ok, I'll work on a way around it :+1:

**Comment by Cosbgn** [comment]
I had the same issue. The best way I found was to listen to `dragstop` and `resizestop` not `change`. The first two don't get called when the window resizes.

**Comment by Cosbgn** [comment]
But `drag/resize` would tell me that the layout has changed, then I have my own function to get the new layout:
```
getLayout(){
	const lay = []
	for (const block of this.items){
		const r = this.$refs[block.id]
		if (!r || !r[0]){return;}
		const block_att = {id:block.id}
		for (const name of ['x','y','h','w']){
			block_att[name] = r[0].getAttribute(`gs-${name}`)
		}
		lay.push(block_att)
	}
	return lay			
},
```
So whenever a user resize or drags the layout I call this and I have the latest layout. It seems to work so far

**Comment by adumesny** [comment]
oh sure. also don't forget you have simpler `grid.saveLayout()` method to return all props (not just (x,y,w,h)

**Comment by Cosbgn** [comment]
Hi the `saveLayout()` should work?

I tried with:

```
if (this.grid){
	console.log(this.grid)
	const layy = this.grid.saveLayout()
	console.log(layy)
}
```
But I get that saveLayout() is not a function.

![image](https://user-images.githubusercontent.com/17546283/106255244-140cff80-621a-11eb-9566-f6abc0d640c7.png)

I've also searched the code of this repo for saveLayout() but it doesn't return anything. Thanks.

**Comment by Cosbgn** [comment]
![image](https://user-images.githubusercontent.com/17546283/106255441-56364100-621a-11eb-863b-fbe9cb8b05a2.png)

This is `this.grid`

**Comment by adumesny** [comment]
sorry just `save() / load() `
