### ISSUE TITLE
collapsed in save/load

### ISSUE THREAD

**Issue by c0deheld** [gridstack/gridstack.js#1560]
The .load() and .save() methods do not allow the "collapsed" state of grid items to be persisted. Any plans to add this?

**Comment by adumesny** [comment]
what do you mean by 'collapsed' ? do you mean oneColumnMode ? please provide an example showing the issue, and re-open when you do.

**Comment by c0deheld** [comment]
I'm an idiot. I implemented that by myself and forgot ;-) It's meant to show grid-items with height=1 and no content visible, similiar to an accordion control.

I'll have to handle save/load by myself. Sorry for the confusion. This issue may be deleted.

**Comment by adumesny** [comment]
:) 
no delete I'm afraid. just closing... you'll want to use the `save()` or at least `grid.engine.save()` and make a second pass to save extra info (`load()` support callback function for creating items)
