### ISSUE TITLE
Vue components in content aren't compiled

### ISSUE THREAD

**Issue by DariuszKralewski** [gridstack/gridstack.js#1569]
## Subject of the issue
When you fill the content with a component, it is not compiled, it shows up as plain HTML, e.g. <Test />

## Your environment
* newest version of gridstack.js
* Chrome browser

## Expected behavior
content that is a component should be compiled and reactive

**Comment by adumesny** [comment]
closing this as you give no code sample or example to reproduce (marked as required in template!). Also 'latest version" doesn't tell me if 3.1.4 H5 vs JQ when it gets looked at a month or a year from now.

By content do you mean setting `GridStackWidget.content` and having that be compiled by Vue? (likely similar issue with Angular/React) - no idea how framework decide to run on new html template to be honest...

re-open once you have a proper bug please.
