### ISSUE TITLE
Dragging item out to bottom does not remove with maxRow

### ISSUE THREAD

**Issue by NealonF** [gridstack/gridstack.js#1570]
## Subject of the issue

you can drag out to remove) from every side but bottom even though you have maxRow=6 (you can see drop feedback stays inside in that case)

## Your environment
gridstack v3.1.3 with gridstack-jq-js and gristack.min.css as only references.
Chrome  v87.0.4280.141 (Official Build) (64-bit)

## Steps to reproduce
https://jsfiddle.net/adumesny/ks8gmqo4/

## Expected behavior
Should remove item when dragged out from bottom of grid (as it does with every other side)

## Actual behavior
Extends browser window and upon drop, goes back to spot where picked up.

**Comment by adumesny** [comment]
3 separate bugs please...

**Comment by adumesny** [comment]
if you don't have `maxRow` the grid grows to fit so you never get the leave event, but it looks like we don't get leave even when max...

https://user-images.githubusercontent.com/3496166/104849558-28a6da80-589f-11eb-86c1-2f2cfbc24603.mp4

works correctly when you have `float:false` (removes placeholder) though it requires being past the bottom by a lot

https://user-images.githubusercontent.com/3496166/104849642-baaee300-589f-11eb-86f5-44fe909108e9.mp4
