### ISSUE TITLE
Elements vanish when dragging/dropping fast

### ISSUE THREAD

**Issue by yassine-ah** [gridstack/gridstack.js#1578]
## Subject of the issue
Elements vanish when dragging/dropping fast.

## Your environment
gridstack.js H-5 v3.1.4
Mozilla Firefox 84.0.2 and Microsoft Edge 87.0.664.75

## Steps to reproduce
Just drag/move/drop fast, you can use the official demo: https://gridstackjs.com/demo/two.html  
Here a video: https://www.loom.com/share/008049b00f344f55ba8e3df90e17a50a

## Expected behavior
The element will appear in the other grid

## Actual behavior
The element vanish from the two grids

**Comment by jezaman** [comment]
Any idea on what is causing this? any known workarounds?

**Comment by adumesny** [comment]
yeah there is a 2sec delay to remove (`removeTimeout:2000` grid options default). Try setting this to 0. not sure why there is a delay at all...I suspect that is causing issues and not sure why it's there.

**Comment by jezaman** [comment]
Thanks for your reply, but removeTimeout: 0 does not fix this. 

removeTimeout also seems to be about something else, aka how long to leave an element outside the grid for it to be removed.
This issue is about quickly dragging elements between grids, the drag time is way less than 2000ms anyway.

**Comment by adumesny** [comment]
| Items seems to disappear when in drag-mode limbo. when you drag an item, but the drop location hasn't appeared yet

that could be the key. thanks will take a look.

**Comment by adumesny** [comment]
took a long time to figure out timing issue. added console.log() (commented out) next time I need to track event orders... fix in v4
