### ISSUE TITLE
Angular Wrapper

### ISSUE THREAD

**Issue by LeviWenzel** [gridstack/gridstack.js#1590]
## Angular Wrapper
Just wanted to ask if there is a schedule regarding the Angular Wrapper as I would be interested in this one.

## Your environment
gridstack.js 3.X

**Comment by adumesny** [comment]
not likely for a long time, if ever (my own Ang10 wrapper is component based and not an open source candidate) as I have 2 big task I want to do before (drag using mouse event, support for mobile, and possible collision re-write which I started).

**Comment by adumesny** [comment]
closing - we have angular and other examples instead...
