### ISSUE TITLE
H5 resize down from left side will move item to the right

### ISSUE THREAD

**Issue by riccardinhocala** [gridstack/gridstack.js#1599]
## Subject of the issue
If the GridItem is in the 12th (and last) column, when resize with sw handler, this action trigger both drag and resize. In this way the GridItem go out from the gridstack

## Your environment
gridstack v3.2.0, HTML5

## Steps to reproduce
demo: https://jsfiddle.net/rob4e7z6/
resize from bottom left the last GridItem
![chrome-capture](https://user-images.githubusercontent.com/23438707/106304639-e2b52380-625b-11eb-9f44-3daa9eb90e87.gif)
.

## Expected behavior
What happens with resize from bottom right. The GridItem may set his width and not drag

## Actual behavior
It will trigger both drag and resize. In this way the GridItem go out from the gridstack

**Comment by adumesny** [comment]
funny I fixed a similar issue when resizing from the left past the maxWidth did also move the object couple weeks ago. Guess I didn't take a look sizing it below minWidth (1 in this case).

one of the reason I changed to only resize bottom right in the demos - always though left side resize was odd anyway and can have all sort of harder to fix side effects.
