### ISSUE TITLE
that's shame that i can'\t see dist folder here in this repo

### ISSUE THREAD

**Issue by oncebuilder** [gridstack/gridstack.js#1601]
## Subject of the issue
Describe your issue here.

## Your environment
* version of gridstack.js AND if using HTML5 vs Jquery plugin (v3+) - DON'T SAY LATEST as that doesn't mean anything a month/year from now.
* which browser and its version

## Steps to reproduce
MUST provide a working demo (keep it simple!) and steps, you can use this as a base:
https://jsfiddle.net/adumesny/jqhkry7g

## Expected behavior
Tell us what should happen

## Actual behavior
Tell us what happens instead

**Comment by adumesny** [comment]
/dist is build time only. use npm to install it.

**Comment by oncebuilder** [comment]
nice one, quick response, i will do it thru node but i don't understand why make it so complicated for newbies.

**Comment by adumesny** [comment]
we had a /dist folder checked in but it was a PAIN in the  butt when you have more than 1 dev working as it ALWAYS conflicted and could not be auto-merged (minified files) so I nuked it. Then I manually used to upload a zip folder of dist/ for a release but have better things to do... Honestly don't know what the big deal of running `npm install --save gridstack`.  npm packages are supposed to be used that way (and there is CDN as well but we don't get stat usage so I don't expose it).

**Comment by oncebuilder** [comment]
Fair play man, I got it working, I'm just not big fan of node, anyway you are doing good job with this project, I was using your grid before and its really cool library. I'm quite excited as new version works without jQuery. Btw. It would be be nice if there was a row separator.. or something like that in the grid... Anyway keep going with your great job, thank you so much :) Well done!

**Comment by adumesny** [comment]
removing jquery and going Typescript H5 drag&drop was a long time pet peeve of mine. but was a LOT of work (complete re-write of an existing system, which likely took longer than starting from scratch! and I'm not close to being done...

if you don't use node, what do you use and how do you install npm packages ?

as for row separator you could create a non movable/resizable item that taken entire row (would have to make cellHeight small) or even fixed if you didn't want sections to grow, and CSS style it differently.

don't forget to contribute if you find lib useful!
