### ISSUE TITLE
Its not possible to move item A at bottom of item B

### ISSUE THREAD

**Issue by zgilewski** [gridstack/gridstack.js#1605]
We are not able to correctly move one element below another one.

gridstack version: 2.1.0

![image](https://user-images.githubusercontent.com/28985410/106481851-25216f00-64ad-11eb-8450-e162bc49c270.png)

We should be able to move element 1 below element 2.
Currently its not possible. The only way is to drag element 2 above element 1.

**Comment by adumesny** [comment]
dup of #1094, and you need to use latest rev before posting bugs as well. thanks.

**Comment by zgilewski** [comment]
Its not about latest rev, as this is also happening in gridstack demos public available as you can see on attached screen, which I think using latest version of gridstack. And it is not duplication of 1094 as this describes different behaviour, or every problems with placing elements in the grid is treated as drag heuristic issue.

**Comment by adumesny** [comment]
then you need to provide a jsfiddle or other example and not expect me to replicate this for you. There are other opene bugs about hard to place below - so you not possible. which is it. again post a specific example and I will re-open.

**Comment by zgilewski** [comment]
Hmm, but I didnt write any custom code. To check if this issue exist in gridstack lib - not in my code, I just played with demo from https://gridstackjs.com/demo/float.html. In that page just float to **false**, add one more widget and try to move one below other. Nothing else is needed to reproduce this issue.

**Comment by adumesny** [comment]
ha yes I can see it now, likely cause by another recent fix I made about dragging out (likely #1580).
would have been nice to see running video or steps you just gave me.

**Comment by pcardinaliFTX** [comment]
https://user-images.githubusercontent.com/78551686/106914664-86437f80-6705-11eb-83f6-7083c4c60b6f.mov

here is the video as per zgilewski instructions
