### ISSUE TITLE
Not able to create "grid-stack-item" with ngFor in the html (angular)

### ISSUE THREAD

**Issue by SeanKimNYC** [gridstack/gridstack.js#1611]
## Subject of the issue

``
    <div class="grid-stack">
        <ng-container *ngFor="let widget of report.widgets">
            <div class="grid-stack-item"
                 gs-x="{{widget.dimensions.x}}"
                 gs-y="{{widget.dimensions.y}}"
                 gs-w="{{widget.dimensions.cols}}"
                 gs-h="{{widget.dimensions.rows}}">
                <div class="grid-stack-item-content">
                    <app-widget></app-widget>
                </div>
            </div>
        </ng-container>
    </div>
``

above code gives the below error:

![Screen Shot 2021-02-02 at 5 39 31 PM](https://user-images.githubusercontent.com/77445963/106753451-ae45bc80-65f9-11eb-93ec-dd219e0b7e83.png)

It works only if hard coded as below:
``
    <div class="grid-stack-item" gs-x="0" gs-y="0" gs-w="4" gs-h="3">
``

## Environment
gridstack v3.2.0
HTML5
Angular 8

**Comment by adumesny** [comment]
this is an angular error (not gridstack) thankfully I know Ng! 
for custom attributes you need to do something like this (a simple google search would have return this)

`[attr.gs-x]="{{widget.dimensions.x}}"`

**Comment by SeanKimNYC** [comment]
thank you for taking a look very quickly, but I still see an issue with it.. opened up another issue here.  https://github.com/gridstack/gridstack.js/issues/1614

**Comment by adumesny** [comment]
FYI, I created an `ngFor` sample under https://github.com/gridstack/gridstack.js/blob/master/demo/angular-ngFor.ts
**BUT it doesn't track** `ngOnChanges()` correctly so updates to the list is not reflected correctly.

My personal usage of Angular uses componentFactoryResolver to dynamically created components, so I know when to gridstack makeWidget()/removeWidget() - but it's not opened sourced.
