### ISSUE TITLE
displaying gridstackItem with Angular

### ISSUE THREAD

**Issue by skxnyc** [gridstack/gridstack.js#1614]
Below is my code to display the widgets with gridstack.

![Screen Shot 2021-02-03 at 3 05 31 PM](https://user-images.githubusercontent.com/77445963/106802916-9722c100-6631-11eb-8f32-243930dfb199.png)

However as below, the gs-y and gs-h are getting ignored, and it causes the items to get overlapped on each other on the top level. 

![Screen Shot 2021-02-03 at 3 05 07 PM](https://user-images.githubusercontent.com/77445963/106802992-ae61ae80-6631-11eb-9522-c6320e504bb8.png)

**Comment by skxnyc** [comment]
I don't see any issue when the gs-x, gs-y, gs-w, gs-h are hardcoded.

![Screen Shot 2021-02-03 at 3 33 04 PM](https://user-images.githubusercontent.com/77445963/106805896-4319db80-6635-11eb-8284-62df263bc98f.png)
![Screen Shot 2021-02-03 at 3 28 09 PM](https://user-images.githubusercontent.com/77445963/106805898-444b0880-6635-11eb-9d81-dc4c31c336c4.png)

**Comment by adumesny** [comment]
please don't open another 'bug'!
read the react/vue examples where you have to init gridstack AFTER the DOM items have all been created. ngFor is tricky as it updates live and I don't recall the hooks to be notified on top of my head.... makeWidget()/removeWidget() are what you'll need.

**Comment by skxnyc** [comment]
I was able to display it by initializing gridstack with ngAfterViewInit hook.  However, when I try to add a new widget with ngFor, the new created widget is not draggable/resizable.

Now, the problem with the dynamic way is to display a component inside of the content.  When I pass in a component as a content, I see [object HTMLElement] where I want to see the component.

**Comment by skxnyc** [comment]
Just an FYI...
The hook is ngAfterViewInit and with the hook, it displays the initial items fine.  But, when adding more items, newly added items are not getting properly displayed (they are getting overlapped, and not draggable/resizable).  So I would say it doesn't really work with ngFor at the moment.

Now, I sort of made it work with makeWidget() by creating component dynamically with componentFactoryResolver.  But I said "sort of" because this is not very stable.  once in a few times, on initialize, the h and y of the items are not respecting what's passed in like below.

![Screen Shot 2021-02-04 at 11 31 50 AM](https://user-images.githubusercontent.com/77445963/106962074-82672b80-670c-11eb-86c5-e03e4ff67f5e.png)

**Comment by andrea-spotsoftware** [comment]
@skxnyc do you have any plunkr? I'm working on this problem too

**Comment by adumesny** [comment]
FYI, I created an `ngFor` sample under https://github.com/gridstack/gridstack.js/blob/master/demo/angular-ngFor.ts
**BUT it doesn't track** `ngOnChanges()` correctly so updates to the list is not reflected correctly.

My personal usage of Angular uses componentFactoryResolver to dynamically created components, so I know when to gridstack makeWidget()/removeWidget() - but it's not opened sourced.
