### ISSUE TITLE
GridStack drag/drop reordering does not work if everything is inside the Shadow DOM

### ISSUE THREAD

**Issue by nborelli** [gridstack/gridstack.js#1615]
## STATUS

**RESOLVED** - See my note below.  I found that simply adding the following to the options solves the problem.  I need to RTFM!

```js
     draggable: {
    	appendTo: 'parent'
     },
```

I have updated the original fiddle to work here: <https://jsfiddle.net/nborelli/jk5d2bso/13/>

## Subject of the issue

If GridStack is used with the Shadow DOM, styling and resizing work fine, but dragging to reorder does not.  It seems that the item bein floated is being appended to the document body rather than the shadow root.  This is a place where using the `Node.getRootNode()` function on the nodes might help.  See <https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode>

## Your environment

Gridstack: version 3.3.0
Browser:  Google Chrome version 88.0.4324.150 (Official Build) (64-bit)
No jQuery

## Steps to reproduce

Here is a working demo that loads the CSS and Gridstack within a custom element that has a shadow root.

<https://jsfiddle.net/nborelli/jk5d2bso/6/>

Here is what it looks like after the drag:

![After Drag](https://user-images.githubusercontent.com/7409413/107098966-5c519200-67c5-11eb-96c2-e730cb0be49b.png)

## Expected behavior

I would expect it to work.  As I said earlier, using the getRootNode() function to get the root to append to should help keep the item that is being dragged inside the shadow root.

## Actual behavior

I can see the item that is being dragged get appended to the document body and it does not drag properly.  See the jsfiddle for the behavior.

**Comment by nborelli** [comment]
I started to read the source to try and fix this and see that I need to understand the options better!

Simply adding the following to the options fixes the problem:

```js
      draggable: {
    	appendTo: 'parent'
      },
```

I guess this issue can be closed.

**Comment by adumesny** [comment]
@nborelli thank you for your post - would you mind creating that example for others to see and put it next to the ones we have, like 
https://github.com/gridstack/gridstack.js/blob/develop/demo/web-comp.html
call it shadow-dom.html and add it to index.html list ?

I added grid option `styleInHead` (default false, so CSS go to parent now) I think to solve the web-component usage (and style your case correctly), but didn't  have someone bring this issue before. Wondering if we shouldn't always call `Node.getRootNode()` instead, or change the default `draggable` & `dragInOptions` which both have `appendTo: 'body'`
to parent instead... which came from jquery original implementation and likely out of date these days...

What do you think ?

**Comment by nborelli** [comment]
Hi @adumesny,

Yes I can create an example as a web component that does not use a framework like this.  I guess I would just write this as a PR then.  

I could see changing the default value of `appendTo` from "body" to "root" and then using `Node.getRootNode()` to get the root node.  However, the root node returned when not in a shadow DOM is the document, not the body element.  When in a Shadow Root, it will be the shadow root. which I guess would be fine.  I guess you could use something like the following to resolve what "root" means given a reference node:

```ts
function  getRoot(node: Node): Node {
    const root = node.getRootNode();
    return root instanceof Document ? root.body : node;
}
```

**Comment by adumesny** [comment]
I'm sure what JQ does (did you even try your example with it ?) or if it even support 'root', but if we're the one inserting that object we can do anything we want, including changing to 'parent' and have it just work...

**Comment by nborelli** [comment]
Hi @adumesny,

I did not try jQuery as it is not something we use in our stack or inside our web components. We tend to use Stencil for web components and Svelte for building sites. We have our own design system, so no Bootstrap either.

I guess I am stuck a bit on the terminology.  When I think of "parent" I think about the immediate parent of the `div` with the `grid-stack` class or the one passed though the `init` function.  I think of "root" as the document root element (body) or shadow root. This may just be the way my brain works though. I am hard-pressed to think of a case where I would need "parent" as I described it above, but adding elements to the "root" as I described it would be useful.

I will try to issue a PR with an example later this afternoon.  I believe we are in the same time zone, It is just a lot colder up here.

**Comment by adumesny** [comment]
yes we're on the same page (root vs parent). as I mentioned I didn't look at JQ (which I have to unfortunately continue supporting - at least until full parity with h5 code) if they handle 'root' or what they do for shadow dom.

I think 'parent' to the grid, was useful to someone who wanted to be able to move the grid around (not sure how) and have the CSS styling follow along, but then again they would share the same document unless the use web component and still inside... but then 'root' as described above would work... anyway let's get an example in and we can check the different options and what the default should be.

**Comment by adumesny** [comment]
ping @nborelli - still waiting on that sample. thanks.
