### ISSUE TITLE
Show horizontal scrollbar on gridstack div when browser shrinks

### ISSUE THREAD

**Issue by markarupert** [gridstack/gridstack.js#1620]
## Subject of the issue
When the browser is resized I need the horizontal scroll bar to appear at the bottom of the gridstack div. I have tried to setting the overflow to "overflow: scroll!important" on both the gridstack and the containing div.

## Your environment
* version of gridstack.js AND if using HTML5 vs Jquery plugin (v3+) - DON'T SAY LATEST as that doesn't mean anything a month/year from now.
* which browser and its version

h5, using HTML5, Chrome Version 88.0.4324.150

## Expected behavior
Scrollbar should show

## Actual behavior
No Scrollbar

Before resizing:
![gridstack1](https://user-images.githubusercontent.com/2731994/107965656-c7932500-6f78-11eb-8f97-68f6dd9b6b80.png)

After resizing
![gridstack2](https://user-images.githubusercontent.com/2731994/107965664-ca8e1580-6f78-11eb-9c5c-708445d226af.png)

**Comment by adumesny** [comment]
this is not a lib issue - you have complete control of the .grid-stack div width (content is column based to fit but YOU are the one doing the container layout...
