### ISSUE TITLE
Cannot load gridstack[.min].js with own jquery/jqueryui

### ISSUE THREAD

**Issue by mnlipp** [gridstack/gridstack.js#1623]
## Subject of the issue
Cannot get gridstack 3.3.0 to work with own jquery/jqueryui

## Steps to reproduce
Documentation says 
> IFF your app needs to bring your own version instead, you should instead include gridstack-poly.min.js (optional IE support) + gridstack.min.js + gridstack.jQueryUI.min.js after you import your JQ libs

## Expected behavior
gridstack.min.js should load. However, it isn't included in `dist/`, so using `gridstack.js` instead.

## Actual behavior
Error
```
Uncaught ReferenceError: exports is not defined
    <anonymous> https://localhost:5443/vjconsole/page-resource/gridstack/gridstack.js:6
```

Quiet obvious if you look at gridstack.js.

**Comment by adumesny** [comment]
and right below it says:

| NOTE: v2.x / v3.x does not currently support importing GridStack Drag&Drop without also including our jquery + jquery-ui. Still trying to figure how to make that bundle possible. You will have to use 1.x for now...

was that not clear enough ? can you make a suggestion ?

**Comment by mnlipp** [comment]
> and right below it says:
> 
> > NOTE: v2.x / v3.x does not currently support importing GridStack Drag&Drop without also including our jquery + jquery-ui. Still trying to figure how to make that bundle possible. You will have to use 1.x for now...
> 
> was that not clear enough ? can you make a suggestion ?
> you can alternatively use v3 HTML5 version (which doesn't use jq)

How about:

> IFF your app needs to bring your own version instead (only possible with v1.x),...

Problem with the note is that is has two negations ("... does NOT support WITHOUT including ..."). And it refers to something different "does not currently support importing GridStack Drag&Drop", while what I want to do is "replace" the built-in jqueryui with my own. It doesn't say "... does not support using gridstack with your own version of jqueryui."
