### ISSUE TITLE
[3.3.0] Widgets not returning to original location after hovering new widget over the widget but not dropping

### ISSUE THREAD

**Issue by Mopster** [gridstack/gridstack.js#1627]
## Subject of the issue

This could be related to https://github.com/gridstack/gridstack.js/issues/1626

When dragging a new widget onto the grid, existing widgets would reposition to make room for the new widget, but they don't return to their original location (occasionally).

Before dragging : 

![Screenshot from 2021-02-19 12-38-25](https://user-images.githubusercontent.com/155956/108454420-b36c6200-72af-11eb-9831-64f89bbaa38b.png)

After dragging and dropping the new widget on the right side. I did not drop the widget anywhere else.

![Screenshot from 2021-02-19 12-38-46](https://user-images.githubusercontent.com/155956/108454456-c2531480-72af-11eb-80fc-2f14d6024d8d.png)

You can see the widgets in the left column have been displaced. No "change" even has been triggered: 

![Screenshot from 2021-02-19 12-43-51](https://user-images.githubusercontent.com/155956/108454694-32619a80-72b0-11eb-962b-cbc59f0de61e.png)

## Your environment

* v3.3.0 using HTML5
* FireFox 85.0.1 (on Ubuntu 20.04)

## Steps to reproduce

https://gridstackjs.com/demo/advance.html

I removed all widgets and then started populating as seen on the above screenshots.

## Expected behavior

Widgets return to their original location after the dragging a widget over it.

## Actual behavior

Widgets occasionally do not return to their original location and stay displaced. N

**Comment by adumesny** [comment]
likely a dup of #1626 - but I need to see as I can't reproduce.
