### ISSUE TITLE
Angular DrugNDrop - new widget

### ISSUE THREAD

**Issue by akeske** [gridstack/gridstack.js#1631]
I implement your gridstack in my angular project.
when I dnd an element inside the grid it is working as expected. The problem is when i wrap the new widget element in a ngIf.

```
<ng-template *ngIf='show'>
    <div class="col p-0">
      <div class="grid-stack-item p-1 element newWidget"
           gs-content="Test">
        <div class="grid-stack-item-content p-2">
          <div>Test</div>
        </div>
      </div>
    </div>
</ng-template>
```

Can you inform which function I have to call to enable again dnd?

Thank you very much, nice work

**Comment by adumesny** [comment]
please use slack for questions and not post 'bugs'
