### ISSUE TITLE
Wrong handling drag&drop in firefox

### ISSUE THREAD

**Issue by zgilewski** [gridstack/gridstack.js#1632]
When trying to drag new item into grid, placeholder is showing incorrectly, other elements moved wrongly.
See recorded wideo from your demo (https://gridstackjs.com/demo/advance.html) runned on firefox version 85.0.2.

https://user-images.githubusercontent.com/28985410/108640684-6b119780-749b-11eb-8550-8c9ddddce232.mp4

**Comment by adumesny** [comment]
weird, this works just fine on Chrome, but yeah I can see the issue on FF windows 10 (might be V scrollbar issue as it shows up and supposed to be in the computation.

**Comment by zgilewski** [comment]
Hmm, but on Chrome this V scrollbar is also there, but on chrome there is no issue.

**Comment by zgilewski** [comment]
I did also one small test by removed that scrollbars from page, but that didnt help, so I guess its not a problem of scrollbars.
![image](https://user-images.githubusercontent.com/28985410/108962852-a23d9f80-7679-11eb-983d-38fa789e7c08.png)

**Comment by adumesny** [comment]
fixed in the current build (re-wrote how drag-in works). will be in v4
