### ISSUE TITLE
widgets dissapearing when moving fast between two grids

### ISSUE THREAD

**Issue by zgilewski** [gridstack/gridstack.js#1647]
Widgets randomly are dissapearing when moving fast between two grids.
Please take a look at attached wideo recorded on your demo page for two grids (https://gridstackjs.com/demo/two.html).
This issue happening also in version 2.2.0.

Widgets should be correctly moved between grids or at least go back to its original position.

https://user-images.githubusercontent.com/28985410/109637533-3366b780-7b4d-11eb-93d2-1973e1dec4ed.mp4

**Comment by adumesny** [comment]
dup of #1578

**Comment by zgilewski** [comment]
Hi, 
Is there any new release planned in very near future which will include latest fixes ?

Regards
Zbigniew Gilewski

Od: Alain Dumesny
Wysłano: wtorek, 2 marca 2021 15:53
Do: gridstack/gridstack.js
DW: Zbigniew Gilewski; Author
Temat: Re: [gridstack/gridstack.js] widgets dissapearing when moving fast between two grids (#1647)

Closed #1647.

**Comment by adumesny** [comment]
I'm trying to get 4.0 out but still some bigger chunks to figure out... don't forget to contribute if you find lib useful!

**Comment by gnamurftx** [comment]
Hi Alain,

We are using your lib and find it very useful. However we need to decide if we can continue using your lib or need to go to another one as we are close to a critical delivery go live.

We need to understand if we can receive this fix before our go live and do some regression tests. If you do need any kind of support from us just let me know.

Ideally we need it into the next week.

rgds,
Guillaume

**Comment by adumesny** [comment]
@gnamurftx, I just spend ~20h over the weekend and last week fixing this bug and 1578 (and 3 older legacy ones). I sure didn't see any contribution from you to help support this, so not sure why you feel the right to ask for a release now.
That said I'm close to releasing v4 but still have some collision fixes... the amount of work is enormous so contributions are much appreciated.

**Comment by gnamurftx** [comment]
Hi Alain,

Contribution or support was for me same word. Would be good to know exactly how we can help you exactly ?

I can imagine very well all your efforts and my message was really to find any type of agreement to support you.

Those said, again sorry if you find my email aggressive or inappropriate, it was clearly not my attention but exactly the way round. We used your library and like it so again it was a question to help/support you to be sure as you can imagine we can continue using it or if we have to find an alternative solution.

Regards,
Guillaume



Guillaume Namur
Email    : guillaume.namur@finantix.com<mailto:guillaume.namur@finantix.com>
Mobile : +41 79 605 57 98
Office   : Rue des Maraichers, 36 – 1205 Geneva - Switzerland
[signature_831264352]
2020 Outstanding Front Office Digital Solutions Provider
Private Banker International

2020 Best Integrated Front Office Solution
Asian Private Banker

2020 Best Front Office Solution
WealthBriefing (Switzerland and Asia)

CONFIDENTIALITY NOTICE - The information contained in this communication is intended solely for the use of the individual or entity to whom it is addressed, and others authorised to receive it. It may contain confidential or legally privileged information. If you are not the intended recipient you are hereby notified that any disclosure, copying, distribution or taking any action in reliance on the contents of this information is strictly prohibited and may be unlawful. If you have received this communication in error, please notify us immediately by responding to this email and then delete it from your system. Finantix is neither liable for the proper and complete transmission of the information contained in this communication nor for any delay in its receipt.

**Comment by adumesny** [comment]
@gnamurftx please PM or email me directly. thanks.
