### ISSUE TITLE
HTML5 vs JQuery

### ISSUE THREAD

**Issue by jhsct** [gridstack/gridstack.js#1648]
## Subject of the issue
Issue with Pick for dragging items

## Your environment
Version 3.3 of HTML vs JQ
Edge (Chrome Based Browser)
1. The Html version pick grid item does not function when jquery components (like a Kendo Grid or Toolbar) exist in the gridstack element. Had to switch back to the Jquery Version.  Unfortunately, that means Jquery is included in the jq version and therefore must be loaded first.
2. The Html drag and drop is a little to sensative and you can easily end up swapping components when trying to move an item up when the grid stack is scrolled down a bit.  In fact, it swaps with the component above it before that component is even shown on the screen.

Let me know if you need anything.

**Comment by adumesny** [comment]
2 bugs here! (file separately please next time)
2) should be handled by the almost complete re-write of collision (see #1094)

as for 1) you must submit a working example if you want me to event try debugging this. I don't have time to re-create every cases...
