### ISSUE TITLE
Save and Restore

### ISSUE THREAD

**Issue by jhsct** [gridstack/gridstack.js#1649]
## Subject of the issue
Save and Restore

## Your environment
*  HTML5 and Jquery plugin (v3.3) -
* Edge

We are saving and restoring the gridstack.  On restore, the grid is different from the save.  It works in the demo but i believe the reason is that the gridstack we use is over a page high and the scroll bar is shown.  We are showing charts in a 7 charts in 2 column configuration.  The charts are 800px high by 1 column and therefore the gridstack is located inside a div so we can scroll down to see the other charts.  The restore is just off.

**Comment by jhsct** [comment]
On web page entry, I Initialize the Grid Stack with the HMTL and then reload the stored positions.  

pseudo html for brevity:
 <div class="container-fluid p-t-15" style="height: 80vh; overflow: scroll;">
<div class="grid-stack">  
// Repeat 7 times.  Ids are 1-7 and initial positions are changed accordingly.  
<div id="stackitem1" gs-id="1" gs-x="0" gs-y="0" gs-w="1" gs-h="15" class="grid-stack-item d-none ui-draggable ui-resizable">
    <div class="grid-stack-item-content">
                             // Content 
    </div>
  </div>

</div>
</div>

In code - I init grid on page entry:
```
let options = {
            column: 2,
            verticalMargin: 5,
            minRow: 0, // don't collapse when empty
            cellHeight: gridheight,
            resizable: { autoHide: false, handles: 'se,sw' },

            disableOneColumnMode: true,
            float: true
        };
        gridStack = GridStack.init(options, '.grid-stack'); 
```
then load the deserialized saved grid layout from html localStorage if available by performing the following:
```
var gridstackinitialpositionlist = JSON.parse(localStorage['dashboardgridstacklayout'] )
gridStack.batchUpdate();
 gridStack.load(gridstackinitialpositionlist, false);
 gridStack.commit();
```
Anytime there is a resize, change, drag I perform the following:
  function SaveGridStackState() {
        localStorage['dashboardgridstacklayout'] = JSON.stringify(gridStack.save(false));
    }

I've double-checked and the save serialized data is the same on page entry.  Items 1 to 5 get loaded correctly but item 6/7 are the wrong height and not in the correct x,y position.

**Comment by adumesny** [comment]
you don't want to wrap load() with batch/commit - it already does and could cause issues...
I didn't have time to read through but make sure the save json looks correct to start, then post the json if loading is the issue.

**Comment by jhsct** [comment]
I've not been able to reproduce on a Fiddle.  Closing for now.
