### ISSUE TITLE
Issue when initializing grid from html and dragging in templates on smaller screen (1080p) it changes "gs-w=" property

### ISSUE THREAD

**Issue by Stefanmle** [gridstack/gridstack.js#1650]
## Subject of the issue
Issue when initializing grid from html, it changes the width of the elements

## Your environment
HTML5 Jquery  3.5.1 
Both chrome and Safari

## Steps to reproduce
I have a grid that i load with html, i have saved the state previusly like gs-w=12 etc.

Everything works great and it shows up correctly. But when i call:

It resizes the template element. So the 10 above becomes a 1 (gs-w="1") but it still takes the full width.

The issue mainly appears when having saved my "Template" in 4k and then opens the template on a 1080p screen. Then it does this strange behavior. If i save it my 4k screen and reopens it on the same screen this issue doesn´t happen.

And if i create a new Grid with lower resolution (like have the browser in half screen on my 4k screen) and add a new element (drag it in) and the element has a gs-min-w="6" i cant resize it, only if a make the screen bigger i can resize it. And the same issue comes here, it sets the width to  "gs-w=1" instead of 6 that i have on the template that i drag in.

Ok, so what i have is like this:

```js
            <div class="row">

      <div class="col-3">
Some stuff here
   </div>

      <div class="col-6">
                    <div class="col-12" style="padding: 5px;">
                        <div style="min-height: 200px" id="pdf-preview-header" class="grid-stack">
        <div class="grid-stack-item" gs-w="@item.width" gs-h="@item.height" gs-x="@item.posX" gs-y="@item.posY" gs-min-w="6">
            <div class="grid-stack-item-content dashed-outline-small" style="padding: 5px;">
                <div class="data-ccontainer" data-elementtype="Title">
                    <i class="delete_element nc-icon nc-scissors"></i>
                </div>
                <div class="text-center">
                    <h2 class="editable-label clickable-label">@item.textValue <i style="margin-left: 10px;" class="fa fa-pencil"></i></h2>
                 I have more stuffs in here, just removed it for clarity
                </div>
                         </div>
                    </div>
   </div>

      <div class="col-3">
        Some other stuff here
   </div>


            </div>

```

and init like this:
```js
    initGrid: function (elementId) {

        var grid = GridStack.init({
            resizable: { handles: 'e, se, s, sw, w' },
            dragInOptions: { revert: 'invalid', scroll: false, appendTo: 'body', helper: 'clone' },
            removable: '#trash', // drag-out delete class,
            acceptWidgets: true,
            dragIn: '.newWidget'  // class that can be dragged from outside
        }, "#" + elementId);

        return grid;`
```

And what happens is that it looses the "gs-w=" when the screen is small (1080p) but if i reload it with a 4k screen it works fine. And i also can´t resize the grid-items on a small screen (when the gs-w gets set to 1 on a small screen). 

Notice: I also set the gs-w to like 6 or 12 and it looks right until after i call init, after that it gets resized wrongly
## Expected behavior
Since i only use bootstrap col-12 and don´t have any hardcoded widths and heights it should not change the gs-w property that i have set.

## Actual behavior
It changes the size of my predifend widths on Initialize

**Comment by Stefanmle** [comment]
<div class="grid-stack-item" gs-w="@item.width" gs-h="@item.height" gs-x="@item.posX" gs-y="@item.posY" gs-min-w="6">
            <div class="grid-stack-item-content dashed-outline-small" style="padding: 5px;">
                <div class="data-ccontainer" data-elementtype="Title">
                    <i class="delete_element nc-icon nc-scissors"></i>
                </div>
                <div class="text-center">
                    <h2 class="editable-label clickable-label">@item.textValue <i style="margin-left: 10px;" class="fa fa-pencil"></i></h2>
                 
                </div>
            </div>
        </div>

It looks like it cut my code i pasted in half

**Comment by Stefanmle** [comment]
<div class="col-6">
                    <h4 style="padding-left: 15px;">Header</h4>
                    <div class="col-12" style="padding: 5px;">
                        <div style="min-height: 200px" id="pdf-preview-header" class="grid-stack">@{await Html.RenderPartialAsync("_gridDataFromJson", Model.PageHeaderEditModel.Elements); }</div>
                    </div>

                    <h4 style="padding-left: 15px; padding-top: 15px;">Main Pdf</h4>
                    <div class="col-12" style="padding: 5px;">
                        <div style="min-height: 1000px" id="main-pdf-preview" class="grid-stack">@{await Html.RenderPartialAsync("_gridDataFromJson", Model.Elements); }</div>
                    </div>
                    <h4 style="padding-left: 15px; padding-top: 15px;">Footer</h4>
                    <div class="col-12" style="padding: 5px;">
                        <div style="min-height: 200px" id="pdf-preview-footer" class="grid-stack">@{await Html.RenderPartialAsync("_gridDataFromJson", Model.PageFooter.Elements); }</div>
                    </div>
                </div>

**Comment by adumesny** [comment]
please update your initial comment (click edit) and delete the rest... can't follow. also can use ```js for code

**Comment by Stefanmle** [comment]
> please update your initial comment (click edit) and delete the rest... can't follow. also can use ```js for code

Ok, updated comment

**Comment by adumesny** [comment]
you didn't merge your comments and formatted as asked. Just di it for you!

1)  you need to post a reproduceable case. use the provided template example. closing until you do.
2) you have `gs-w="@item.width"` on the item, are you SURE those are resolved to actual 1-12 values before you call `GridStack.init()` ???
3) both 1080p and 4k are considered large screen (>768px minWidth which forces oneColumnMode, unless your grid is smaller than screen. Try `disableOneColumnMode: true` and see if that changes what you see.
