### ISSUE TITLE
addWidget in oneColumnMode and then resize to 12 -> width is always 1

### ISSUE THREAD

**Issue by capc0** [gridstack/gridstack.js#1655]
## Subject of the issue
When I add a widget in oneColumnMode with e.g. width of 4, it will be converted to 1.
Resizing the window so that we flip to 12 col mode and the widget will still have the width of 1 (expected 4)

## Your environment
3.3.0 with HTML5

## Steps to reproduce
* https://jsfiddle.net/46my3k2p/2/
* make fiddle window small => 1 col mode
* add widget (width 4, height 4)
* make fiddle window large => 12 col mode
* element has width of 1 instead of 4

## Expected behavior
widget should resize to the width it was created with

## Actual behavior
always width of 1

**Comment by adumesny** [comment]
FYI, your example was creating w:2 but still shows the issue... https://jsfiddle.net/adumesny/by60g4zd/

**Comment by adumesny** [comment]
fixed in next release. this was harder than I expected... don't forget to donate if you find this lib useful!
