### ISSUE TITLE
lock grid on dragstart doesn't work

### ISSUE THREAD

**Issue by ReseTTim** [gridstack/gridstack.js#1656]
## Subject of the issue
When I start dragging an item ('grid-stack-item') I would like to block/ lock the other items so everything stays on the same place.

I used as well
- on `dragstart`: grid.enableMove(false)  or grid.enableMove(false).movable(id, true)

## Your environment
* gridstack.js 3.3.0
* dist/h5/gridstack-dd-native

No jQuery or jQuery-ui!

## Example code
https://jsfiddle.net/ReseTTim/nkga1fst/

## History
https://github.com/gridstack/gridstack.js/issues/539

**Comment by ReseTTim** [comment]
I created a fiddle with my example code, hoping it's more clear.

**Comment by adumesny** [comment]
that is not possible to disable move (what you are calling) while an item is being dragged - you CAN however make every other node as 'locked' which will do what you want (don't forget to reset afterward). this should do it
```js
grid.on('dragstart', function(event, el) {
    grid.engine.nodes.forEach(n => n.locked = n.el !== el);
  });
 ```
