### ISSUE TITLE
enableMove() removes snapping on existing items

### ISSUE THREAD

**Issue by NealonF** [gridstack/gridstack.js#1658]
## Subject of the issue
When you call enableMove on a drag-disabled grid with existing items, the existing items will have drag unlocked but will not snap into grid cells as normal. Instead they just stay exactly wherever you drag them to. However, if you add a new item to the grid while enableMove is used this way, then the new item will have normal snapping behavior. This is for the JQ version. On the h5 version, the existing items will stay undraggable instead of the floating behavior. The rest of the results seem to be the same as JQ. The difference between versions should probably be verified just to make sure what I found is true.

## Your environment
* JQ 3.2 and JQ 3.3 and h5 3.3
* Version 88.0.4324.190 (Official Build) (64-bit) and firefox 86 (64 bit)

## Steps to reproduce
https://jsfiddle.net/q904xvfu/12/

push add button to add widget.
try dragging and see that it's locked.
press toggle button (confirmed in console output)
(JQ) drag existing widget and see that it does not snap into a cell. (h5) drag existing widget and see that it is still locked
add another widget and drag that one to see that it DOES snap into cell.
can click toggle again to lock the grid, then again to see that the issue applies to all existing items.

## Expected behavior
Items should be snapping into cells when dragged, when drag is enabled this way

## Actual behavior
on JQ, items wont snap and will float instead. on h5 they stay undraggable.

**Comment by adumesny** [comment]
can you be more specific (actual demo or video) because this works for me

https://user-images.githubusercontent.com/3496166/111890640-95764800-89a8-11eb-9089-cd9829035253.mp4

**Comment by adumesny** [comment]
hey I can't access your demo anymore (502 bad gateway) but realized we do have an example that works
https://gridstackjs.com/demo/static.html

so you must be doing something different...

**Comment by NealonF** [comment]
That's strange, it still works for me, and I sent it to some other people to see if it works for them too and it does. Maybe if I link it again? Worth a shot!
https://jsfiddle.net/7s694twh/3/

Took a little video of what I'm talking about. For some reason the capture program I used has the mouse misaligned, but notice when I toggle the grid to allow dragging by the method I explained, the items in the grid no longer attach to cells, you can just drag them to any spot. However, if you add a new item WHILE the dragging is already enabled, they will snap to cells when you drag them. Then, that same item will stop snapping to cells if you toggle off dragging and toggle it back on. A little hard to explain, hopefully this makes some sense.
https://drive.google.com/file/d/1qwWewDb198IQTOGhFbV_c2R9uese4ryr/view

And if for some reason you still can't view the code, i'll paste it here.

HTML -----------------------------------------------------
<button onclick="lockToggle()">toggle</button>
<button onclick="grid2.addWidget()">add</button>
<button onclick="grid2.removeAll()">clear</button>
<div class="container">
    <div class="main-grid-container">
      <div id="main-grid" class="right-grid grid-stack" >
      </div>
    </div>
 </div>

JAVASCRIPT -------------------------------------------------
let options2 = {
    disableResize: true,
    cellHeight: 150,
    cellWidth: 150,
    float: true,
    row: 6,
    disableDrag: true
  };

  let grid2 = GridStack.init(options2, '#main-grid');


  // functions - - - - - - - - -

  
  let lockState = true;
  
  function lockToggle() {
  	if (lockState) {
    	grid2.enableMove(true);
      lockState = false;
    }
    
    else {
    	grid2.disable();
      lockState = true;
    }
    
    console.log('clicked');
  }


CSS -------------------------------------------------------
*,
*::before,
*::after {
    margin: 0;
    padding: 0;
    box-sizing: inherit;
}

html {
    height: 100vh;
    width: 100vw;
    margin: 0;
    box-sizing: border-box;
    font-size: 62.5%;
    background-color: white;
    display: flex;
    align-items: center;
    justify-content: center;
    overflow: hidden;
    background-color: rgb(216, 216, 216);
}

.container {
    height: 70vh;
    width: 70vw;
    
    background-color: rgb(252, 252, 252);

    display: grid;
    grid-template-rows: 100%;
    grid-template-columns: 10% 90%;
    grid-row-gap: 0px;
    grid-column-gap: 0px;
}


.main-grid-container {
    grid-column: 2;
    height: 100%;
    width: 100%;
    background-color: gray;
    overflow-y: auto;
}


.grid-stack-item-content{
    background-color: rgb(206, 214, 167);
    font-size: large;
}

.right-grid{
    background-color: gray;
}

.drag-border {
    border: solid 5px cyan;
}

.grid-stack-placeholder {
    display: block;
}

**Comment by adumesny** [comment]
I can access the links again... looking...

**Comment by adumesny** [comment]
fix in 4.0.2 - took a little longer than I though... if you find lib useful, don't forget to donate!
