### ISSUE TITLE
Is it possible to drag a widget from side menu, but don´t copy.

### ISSUE THREAD

**Issue by Stefanmle** [gridstack/gridstack.js#1659]
I want to be able to drag items from a sidebar. This works perfectly. BUT! What i wonder is if you can specify something like a mapper. So that if i drag an item from the sidebar with a dataattribute (or whatever) i can choose a mapper that will create the an element that looks the way i want in the grid.

Was this clear and understandable?

Btw, i´m using React, so i would really need some way to be able to drag in an element from the side, and then change it´s content when it´s been added (or before) to the gridstack.

And i´m new to React  :D

Maybe this feuture allready exist?

Thank you for a great product

**Comment by adumesny** [comment]
best to ask those Q on slack (hint look at the helper routine to clone your shape to whatever you need).

**Comment by nexpromedia** [comment]
Is there already a solution or example for this?
