### ISSUE TITLE
Gridstack Item containing Iframe is not draggable

### ISSUE THREAD

**Issue by AkanshaP12** [gridstack/gridstack.js#1660]
## Subject of the issue
I have a requirement to use the iframe as content for grid stack items, it works fine, however, the grid stack items are not draggable. 

## Your environment
gridstack.js 3.1.2
jQuery UI - v1.11.0
browser- Chrome (89.0.4389.82) and Firefox (86.0)

## Steps to reproduce
https://jsfiddle.net/jhyd5obs/

## Expected behavior
Gridstack items containing Iframe should be draggable

## Actual behavior
Gridstack items containing Iframe are not draggable

**Comment by adumesny** [comment]
the problem is there is no area to drag, and I don't think there is a way for the parent to receive events targeted at the Iframe, but I could be wrong as I have not looked... 
this works:
```js
    <div class="grid-stack">
      <div class="grid-stack-item">
        <div class="grid-stack-item-content"><p>drag me here</p><iframe src="https://www.example.com"></iframe></div>
      </div>
    </div>
```

**Comment by AkanshaP12** [comment]
Thank you so much it worked.
