### ISSUE TITLE
Two grids demo not working from local files, getting GridStack.on(drag) and GridStack.on(resize) event not supported errors

### ISSUE THREAD

**Issue by sc17j2h** [gridstack/gridstack.js#1662]
## Subject of the issue
Trying to replicate the drag in and trash functions of the [Two Grids](https://gridstackjs.com/demo/two.html) demo locally, having trouble getting it working. 

## Your environment
Version of gridstack.js: 3.3.0 using HTML5
Which browser and its version: Chrome, version 89.0.4389.90

## Steps to reproduce
Using files copied from the git:
[two.html](https://github.com/gridstack/gridstack.js/blob/develop/demo/two.html)
[events.js](https://github.com/gridstack/gridstack.js/blob/develop/demo/events.js)
[demo.css](https://github.com/gridstack/gridstack.js/blob/develop/demo/demo.css)

but using `node_modules/gridstack/dist/` versions of the files (`gridstack@3.3.0` stated when using `npm list`) instead of `../dist/` as in the git examples, I run into the error detailed below.

## Expected behavior
Behaves like the [two grids demo](https://gridstackjs.com/demo/two.html) on the gridstack website.

## Actual behavior
The following errors display, and the 'Drag me' '2x1, max=3' and trash areas do not work.
`GridStack.on(drag) event not supported, but you can still use $(".grid-stack").on(...) while jquery-ui is still used internally.`
`GridStack.on(resize) event not supported, but you can still use $(".grid-stack").on(...) while jquery-ui is still used internally.`

Currently attempting to figure out how the 'Drag me' '2x1, max=3' and trash areas in the two grids demo are operating. Are they dependant on `events.js`, or might I be missing something crucial? Many thanks.

**Comment by adumesny** [comment]
this isn't a bug. please use slack channel for questions.

**Comment by sc17j2h** [comment]
Ah my mistake, apologies - the other example code `grid.on()` functions in the given `event.js` file were logging to console without issue when activated so I incorrectly thought it might have been a bug.

Didn't realise there was a gridstack slack, I will check it out, thank you! :)
