### ISSUE TITLE
Resizing does not work anymore with v4 JQ version

### ISSUE THREAD

**Issue by Guite** [gridstack/gridstack.js#1669]
## Subject of the issue
Trying to resize a widget causes a JS error:

> cannot call methods on resizable prior to initialization; attempted to call method 'option'

## Your environment
* release version 4.0.0
* tested with both Firefox and Chrome browsers

## Steps to reproduce
- Open https://gridstackjs.com/
- Try to resize widget with label `1`

## Expected behavior
Resizing works without problems.

## Actual behavior
The operation is not completed.

![grafik](https://user-images.githubusercontent.com/277531/111867962-a8245900-8977-11eb-8697-fed890421466.png)

![grafik](https://user-images.githubusercontent.com/277531/111867976-b6727500-8977-11eb-9f22-99bb300622e2.png)

**Comment by adumesny** [comment]
Sight, looks like the jquery ui version is busted, which the website uses for mobile reason (of course all my testing was h5)

**Comment by adumesny** [comment]
fix in upcoming 4.0.1 - don't forget to donate if you find lib useful!
