### ISSUE TITLE
first grid item is not animated when swapping positions with second same-size grid item

### ISSUE THREAD

**Issue by kevinlandsberg** [gridstack/gridstack.js#1678]
## Your environment
* 4.0.1 html 5
* chrome latest

## Steps to reproduce
Just go to gridstack demo page and deactivate float and try to move first griditem

## Expected behavior
Show show nice sliding animation like when you move all other grid items...

## Actual behavior
when you swap first and second grid item it seems to not trigger animation effect

**Comment by adumesny** [comment]
can you be more specific (actual demo or video) because this works for me

https://user-images.githubusercontent.com/3496166/111890640-95764800-89a8-11eb-9089-cd9829035253.mp4

**Comment by kevinlandsberg** [comment]
@adumesny , i am talking about only the **FIRST** and **SECOND** grid-item. As soon as you move the **FIRST** grid-item onto the **SECOND** positition to swap the positions, there will be no animation triggered. **ALL OTHER SWAP ANIMATIONS WORK FINE.**

https://user-images.githubusercontent.com/46755225/111908863-20177f80-8a5b-11eb-94e2-900dbdf2f738.mp4

**Comment by adumesny** [comment]
whoa, that is weird... wonder if it has to do with 1 column mode CSS... the only thing I can think of that make column 0 'special'.

**Comment by adumesny** [comment]
fixed in next release. turns out this never worked as CSS always did 1-12 styles skipping `gs-x:0` attribute!

Kevin, still waiting on that donation....

**Comment by kevinlandsberg** [comment]
Yes, you will get this donation. Still no answer from financial office...
