### ISSUE TITLE
Resizable handles "w / sw" moves wrong item down the grid

### ISSUE THREAD

**Issue by kevinlandsberg** [gridstack/gridstack.js#1679]
## Subject of the issue
When you are using resizable handles to handle "se", resizing the grid item to the left causes the right grid item to be pushed down. strange behaviour

## Your environment
* 4.0.1 and html5
* chrome latest

## Steps to reproduce
https://jsfiddle.net/kevinlandsberg/tpLhq0jk/26/

## Expected behavior
it should push down the left side next grid item and not the item on the right side.

## Actual behavior
when you resize the gird item to the left size by using handles "se", it pushed down the grid item on the right side instead of pushing down the grid item in the left side of the resized gird item. strange behaviour...

**Comment by adumesny** [comment]
again no idea what you are seeing. include a link and video or pictures... works fine to me.

https://user-images.githubusercontent.com/3496166/111890716-72986380-89a9-11eb-8a8f-6456d5120182.mp4

**Comment by kevinlandsberg** [comment]
@adumesny , sorry for wrong information. Please use `resizable: { handles: "sw" }` and try to resize it properly to the left side. Hoe my attached video helps to explain the issue.

https://user-images.githubusercontent.com/46755225/111909148-65887c80-8a5c-11eb-9f1d-7cc793a6350c.mp4

**Comment by adumesny** [comment]
please provide a jsfidle sample as the template require.

**Comment by kevinlandsberg** [comment]
> please provide a jsfidle sample as the template require.

https://jsfiddle.net/kevinlandsberg/tpLhq0jk/24/

Please try to resize e.g. third item in direction "sw". Do you see what is happening? Other way round if you resize the item into direction "se", it behaves as expected and looks clean... is it enough?

**Comment by adumesny** [comment]
fixed in next release
