### ISSUE TITLE
Loading the layout based on ids does'nt render the layout as defined in the layout positioning.

### ISSUE THREAD

**Issue by giannik** [gridstack/gridstack.js#1683]
Hello, 
I am trying to build  dashboard widgets where Im storing the layout without the content , only  ids for each grid-stack-item.

But when Im reloading the content and layout it does'nt render as defined in the saved layout and is randomly placed.

Here is my code :

1. On save I collect the layout defined from the designer omitting the content 

```
  var  serializedDatawContent = gridstack.save(false);
 var strSerializedData = JSON.stringify(serializedDatawContent);
   //save to db 
//my layout is save like below with 2 widgets and their id's

strSerializedData = "[
 {"id":"4aevj48vdw3d868mnn1ae35acm","x":0,"y":0,"w":4,"h":5},
 {"id":"4rmv2mn359hb5zbv64rya8cbc2","x":5,"y":0,"w":6,"h":6}
 
 ]" 

```

2. Later  i load the layout from a database 

2.1.  I populate the appropriate html with gs-id attributes that map to  the ids in strSerializedData in previous step

```
 <div class="grid-stack">
    <div class="grid-stack-item   gs-id=" 4aevj48vdw3d868mnn1ae35acm" >
         <div class="grid-stack-item-content">
            all my widget content goes here based on id that gets data from a service
          </div>
    </div>
    <div class="grid-stack-item  gs-id=" 4rmv2mn359hb5zbv64rya8cbc2" >
    
        <div class="grid-stack-item-content">
        
            all my widget content goes here based on id that gets data from a service
        </div>
    </div>
</div>

```

2.2 At the end of my page I bind the layout to the gridstack based on the aboive html using 
```
     gridstack.load(JSON.parse( strSerializedData), true)
```

But this renders my 2 widgets in random order and not how it was stored in step 1.

As a test if i store my data with the content stored in the content property it works as expected.
But if i dont store content inside the layout and use the approach above the rendering messes up.

Thanks

**Comment by giannik** [comment]
Hello, 
I am trying to build  dashboard widgets where Im storing the layout without the content , only  ids for each grid-stack-item.



But when Im reloading the content and layout it does'nt render as defined in the saved layout and is randomly placed.

Here is my code :


1. On save I collect the layout defined from the designer omitting the content 

```
  var  serializedDatawContent = gridstack.save(false);
 var strSerializedData = JSON.stringify(serializedDatawContent);
   //save to db 
//my layout is save like below with 2 widgets and their id's

strSerializedData = "[
 {"id":"4aevj48vdw3d868mnn1ae35acm","x":0,"y":0,"w":4,"h":5},
 {"id":"4rmv2mn359hb5zbv64rya8cbc2","x":5,"y":0,"w":6,"h":6}
 
 ]" 

```


2. Later  i load the layout from a database 

2.1.  I populate the appropriate html with gs-id attributes that map to  the ids in strSerializedData in previous step

```
 <div class="grid-stack">
    <div class="grid-stack-item   gs-id=" 4aevj48vdw3d868mnn1ae35acm" >
         <div class="grid-stack-item-content">
            all my widget content goes here based on id that gets data from a service
          </div>
    </div>
    <div class="grid-stack-item  gs-id=" 4rmv2mn359hb5zbv64rya8cbc2" >
    
        <div class="grid-stack-item-content">
        
            all my widget content goes here based on id that gets data from a service
        </div>
    </div>
</div>

```


2.2 At the end of my page I bind the layout to the gridstack based on the aboive html using 
```
     gridstack.load(JSON.parse( strSerializedData), true)
```


But this renders my 2 widgets in random order and not how it was stored in step 1.



As a test if i store my data with the content stored in the content property it works as expected.
But if i dont store content inside the layout and use the approach above the rendering messes up.

Thanks

**Comment by adumesny** [comment]
there is a space in your html ID, so not the same ??
`gs-id=" 4aevj48vdw3d868mnn1ae35acm"`

also before 2.2 do you call GridStack.init() to load your html ? (which will be dom ordered and size 1x1, then you should call `grid.update()` instead (to change layout, grid already init).

best to use slack for question as this doesn't appear to be a bug and you didn't provide a reproduceable case showing a lib bug.

**Comment by giannik** [comment]
sorry for the typo in the id. The original code is without space.

this is my complete client side code : 

```
(function (){
     var options = {
        animate: true, 
          };
     var gridstack=  GridStack.init(options);
     gridstack.load(JSON.parse(strSerializedData));  
     gridstack.update(options);
})();
```
Also tried without   gridstack.update(options);
and also with gridstack.load(JSON.parse(strSerializedData), true);  

but same result.


This first image shows how I save my layout (2 widgets with a text area as content) and the second image how its rendered when reopened.

![image](https://user-images.githubusercontent.com/1516981/112190934-28fc8280-8c0e-11eb-946d-92b6c6448299.png)

![image](https://user-images.githubusercontent.com/1516981/112190984-3580db00-8c0e-11eb-8942-c9e463d47db4.png)

**Comment by adumesny** [comment]
all bugs require a reproduceable case please...

**Comment by giannik** [comment]
ok. thanks . I will try to create a js fiddle.
