### ISSUE TITLE
safari: 4.0.1 Widgets no longer drag

### ISSUE THREAD

**Issue by wurambo** [gridstack/gridstack.js#1684]
## Subject of the issue
On Safari, the widgets are no longer draggable within their own grid. I am able to reproduce this issue with a few demos - https://gridstackjs.com/demo/two.html https://gridstackjs.com/demo/web2.html

edit - I had assumed it was only when multiple grids were rendered, but there are demos where there is a single grid and drag and drop stop working

## Your environment
Safari Mac Version 14.0.3 (15610.4.3.1.7, 15610)
Gridstack `v4.0.1`

## Steps to reproduce
Attempt to drag a widget to another spot in the grid
![Screen Recording 2021-03-23 at 3 08 51 PM](https://user-images.githubusercontent.com/17258798/112211846-47e91d80-8bea-11eb-91e7-9ee648998978.gif)

## Expected behavior
Should let you drag to another spot in the grid

## Actual behavior
Does not allow user to drag the item to another spot

**Comment by adumesny** [comment]
so even the simple https://gridstackjs.com/demo/float.html doesn't let you drag (see placeholder) correctly ?
(nothing to do with multiple grids if that the case)

**Comment by wurambo** [comment]
Looks like that demo is fine. The only two I'm running into so far is these two demos

https://gridstackjs.com/demo/two.html https://gridstackjs.com/demo/web2.html

Not exactly sure what these two have in common though - maybe having more than one droppable area?

**Comment by adumesny** [comment]
so https://gridstackjs.com/demo/float.html you can see the dash-line placeholder when moving the item around just fine and it moves there ?
but doing exactly the same within the FIRST grid in https://gridstackjs.com/demo/two.html does not ? (don't try to drag between or from the new items yet)

I don't have easy access to safari for testing.

**Comment by wurambo** [comment]
For (https://gridstackjs.com/demo/float.html), everything is working as is. You can see the dash-lines and you and move the item around

https://gridstackjs.com/demo/two.html Does not show lines or let you move the item to another spot

https://gridstackjs.com/ both examples are working

Still not entirely sure what could be the culprit of these safari issues

**Comment by adumesny** [comment]
https://gridstackjs.slack.com/archives/C0LPPLXJR/p1618509471143600

**Comment by adumesny** [comment]
can you try latest (4.2.1) and let me know if still happens ?

**Comment by adumesny** [comment]
does your bug only happens in H5 or JQ as well? you didn't say...
