### ISSUE TITLE
Migration from v1 to v4

### ISSUE THREAD

**Issue by kavyabeerval** [gridstack/gridstack.js#1686]
## Subject of the issue
request some help in migrating from v1 to v4.

## Your environment
* using - gridstack.js 1.1.2 (gridstack.all.js and gridstack.css), HTML5 and jquery 3.3.1
* chrome Version 88.0.4324.182

## Expected behavior
Now, v4 is totally converted to Typescript and I can't use these files. Please guide me on how to use v4 for my project.

## Actual behavior
My project is built on .net framework, Javascript and Jquery. Gridstack v1 was perfectly fine because it had "javascript" file (gridstack.all.js).

**Comment by ReseTTim** [comment]
it's still javascript compiled, so I don't see the problem.

**Comment by kavyabeerval** [comment]
> it's still javascript compiled, so I don't see the problem. See the underneath the header `Include`.

Thank you for your reply. 
Can I go ahead and use "gridstack.js-4.0.0\src\gridstack.ts" and "gridstack.js-4.0.0\src\gridstack.scss" these 2 files in my project? anything else necessary?

**Comment by adumesny** [comment]
use the slack channel for questions - this is for bugs only. 
and read the doc! https://github.com/gridstack/gridstack.js#migrating
