### ISSUE TITLE
Loading the layout based on ids does'nt render the layout as defined in the layout positioning. 

### ISSUE THREAD

**Issue by giannik** [gridstack/gridstack.js#1693]
I am trying to build a dashboard with widgets where inside the grid layout I am only storing Ids  for the related widgets (not the content). Later When loading the page I prepopulate the html with the ids in the page.
At the end I bind the layout retreveived from the databased to the html .
But the layout is not rendered as stored in the database .
The x co-ordinates of the 2 widgets are different but not reflected in the layout

sample :
https://jsfiddle.net/f05b817u/

## Expected behavior
Should render layout as described in json layout file.

## Actual behavior
Generates radnom layout

slack discussion here :
https://gridstackjs.slack.com/archives/C0LPPLXJR/p1616872260059300
related issue #1683

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find lib useful.

**Comment by giannik** [comment]
ok, alain. will do next time.
small donation made.
