### ISSUE TITLE
Scroll speed

### ISSUE THREAD

**Issue by vendaagil** [gridstack/gridstack.js#1703]
Hello how are you?
I really liked your lib, I am using it in my project, but my clients are having difficulty scrolling.

When you drag an element down, for example, the scroll is very fast, is there any way to decrease the scroll speed when you drag?

Thanks!

**Comment by adumesny** [comment]
dup of #1576 
you should consider donating if you want that feature...

**Comment by vendaagil** [comment]
@adumesny Ok, How many do you need to do this for me?
