### ISSUE TITLE
4.x: style="position: sticky" messing up Dragging

### ISSUE THREAD

**Issue by Dodger77** [gridstack/gridstack.js#1704]
## Subject of the issue
I am trying to make a lot of custom widgets to add to multiple grids. In order to access all of the widgets these stay in a sticky positioned `<div>` (`position: fixed` behaved the same way). Regardless of using float option true/false in the second grid it is not possible to position the dragged in widget under the other widgets.

## Your environment
* Version 4.0.3 tested in HTML5 and jQuery versions
* Browser tested: Firefox (Linux), Chrome (Linux), Edge (Windows 10)

## Steps to reproduce
https://codepen.io/Dodger77/pen/KKaaaJN (HTML5 version with `float: true`)
https://codepen.io/Dodger77/pen/qBRRvEm (jQuery version with `float: false`)

## Expected behavior
Get new dragged in widgets positioned under the existing widgets.

## Actual behavior
New dragged in widgets will always be on top of the second grid when dragged in.

https://user-images.githubusercontent.com/255767/113271935-5e266600-92db-11eb-9920-a2ee06de2838.mp4

**Comment by Dodger77** [comment]
Here as a comparison the same code with gridstack.js 3.3.0:

https://codepen.io/Dodger77/pen/GRrrevw

**Comment by adumesny** [comment]
I see the issue https://jsfiddle.net/adumesny/esyLr4hf/
looks like ` <div style="position: sticky; top: 0;">` is messing up the scroll bar computation for the second grid.

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find lib useful!

**Comment by Dodger77** [comment]
Thank you very much!
