### ISSUE TITLE
Gridstack and Bootstrap Studio

### ISSUE THREAD

**Issue by Imcon** [gridstack/gridstack.js#1707]
## Subject of the issue
Newbie needs guidance

I'm trying to integrate Gridstack into Bootstrap 4/5 and having no luck.
Since this is an include deployment I can't use NPM but don't know how exactly to get a simple grid in place to start testing.
Need to know what files to include in the project, both .js, and .css, as well as the HTML code to call, all attempts have been fruitless.
Any guidance would be greatly appreciated.
Thanks, Dan
dan.horn@icloud.com

**Comment by adumesny** [comment]
please use slack channel for questions.
