### ISSUE TITLE
VUE - jquery.ui was not found

### ISSUE THREAD

**Issue by SeydX** [gridstack/gridstack.js#1709]
## Subject of the issue
Hi all, I am trying to import "**gridstack-dd-jqueryui**" into my vue project as described in the readme, but I always get the error message that "jquery.ui" could not be found. What am I doing wrong?

**Note:** 

With ``gridstack-dd-native``everything works, but i need the mobile touch support.

## Your environment
OS: macOS v10.15.7
Gridstack version: v4.0.3
Browser: Google Chrome v89.0.4389.90
vue: v2.6.11

![Bildschirmfoto 2021-04-03 um 15 39 08](https://user-images.githubusercontent.com/34152761/113480076-cc615900-9492-11eb-969d-dcab8f449d7a.png)

## Steps to reproduce
```js
import "gridstack/dist/gridstack.min.css";
import { GridStack } from "gridstack";
import "gridstack/dist/jq/gridstack-dd-jqueryui";
```

## Expected behavior
Should find jquery.ui

## Actual behavior
![Bildschirmfoto 2021-04-03 um 15 26 31](https://user-images.githubusercontent.com/34152761/113479752-13e6e580-9491-11eb-83b0-c43053211b62.png)

**Comment by Justin99b** [comment]
Same here
I tried to fix it but did not work
using Vue 3.x

**Comment by SeydX** [comment]
> Same here
> I tried to fix it but did not work
> using Vue 3.x

Which version? and how do u added it to your project?

**Comment by Justin99b** [comment]
I am using Vue CLI
i used `yarn add gridstack` to add it to my project
tried everything on google but i guess im to stupid to fix it.

**Comment by SeydX** [comment]
> I am using Vue CLI
> `vue 3.0.9`
> i used `yarn add gridstack` to add it to my project
> tried everything on google but i guess im to stupid to fix it.

nvm, with following code it works also with latest version

```js
import "gridstack/dist/gridstack.min.css";
import GridStack from "gridstack/dist/gridstack-jq.js";
```

**Comment by Justin99b** [comment]
````
src/components/StorageContainer.vue:13:23
TS7016: Could not find a declaration file for module 'gridstack/dist/gridstack-jq.js'. 'c:/Users/Justin/Desktop/FiveM/BetterDevelopment/Neuer Ordner/test/node_modules/gridstack/dist/gridstack-jq.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/gridstack` if it exists or add a new declaration (.d.ts) file containing `declare module 'gridstack/dist/gridstack-jq.js';`
    11 | <script lang="ts">
    12 | import {Options, Vue} from 'vue-class-component';
  > 13 | import GridStack from "gridstack/dist/gridstack-jq.js";
       |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    14 | import {StorageContainer} from "@/classes/StorageContainer";
    15 | import GridStackItemComponent from "@/components/GridStackItem.vue";
    16 |
````


Weird i only get this error

**Comment by adumesny** [comment]
NO-WHERE does it say to include `gridstack-dd-jqueryui` or `gridstack-dd-native` - read the F documentation! geeh...

ES6 or Typescript
```js
import 'gridstack/dist/gridstack.min.css';
import GridStack from 'gridstack';
// THEN to get HTML5 drag&drop
import 'gridstack/dist/h5/gridstack-dd-native';
// OR to get legacy jquery-ui drag&drop (support Mobile touch devices, h5 does not yet)
import 'gridstack/dist/jq/gridstack-dd-jqueryui';
// OR nothing to get static grids (API driven, no user drag&drop)
```
and https://github.com/gridstack/gridstack.js#jquery-application

also use slack for question, not a bug.

**Comment by Justin99b** [comment]
I actually have this issue even tho i did it like in the documentation
````
Failed to compile.

./node_modules/gridstack/dist/jq/jquery.ui.touch-punch.js
Module not found: Error: Can't resolve 'jquery.ui' in 'c:\Users\Justin\Desktop\FiveM\BetterDevelopment\Neuer Ordner\test\node_modules\gridstack\dist\jq'
````


![image](https://user-images.githubusercontent.com/17692991/113498782-569bd280-9510-11eb-9fb2-3234fcc142df.png)

**Comment by Justin99b** [comment]
I tought we would took it straight from the documentation therefore i wrote "i did it like you" sorry for the confusion

**Comment by Justin99b** [comment]
> NO-WHERE does it say to include gridstack-dd-jqueryui or gridstack-dd-native - read the F documentation! geeh...

I dont want to be a smart ass or something but he actually did what you wrote in the documentation AND as an answere.

Maybe im understanding your answere wrong if so im sorry.

But you cant say not to include it just to poste an example on how to include it xD

**Comment by Justin99b** [comment]
> Update: I was in the wrong mood last night when I saw this. I see the doc (which I pasted below) mentions this... never mind, I'll take a look.
> 
> Also there are Vue 3 examples if you didn't see them.

We all have those kind of days no worries :)

Yes i saw the Vue3 Examples in Javascript

The only problem is that we cant import the Typescript Gridstack lib because of the mentioned error

* I deleted my previous answeres to keep it clean!

**Comment by adumesny** [comment]
also do you need to use jquery at all ? (mobile and nested constrain are the only things missing in h5) if not I would recommend using the html5 version.

**Comment by adumesny** [comment]
@Justin99b `index-jq.d.ts` contains what you need, but I need to change filenames...

Also could you guys post a reproduceable folder for me to test ? my Angular app uses h5 (which as you mention works) and not sure it would compile the same way (can't recall if I tried the JQ or not).

**Comment by Justin99b** [comment]
I Actually need it yes

Im using Gridstack for an Inventory system for FIveM (GTA V Multiplayer)

And They use CEF (Chromium Embedded Framework) which does not support HTML5 Drag & Drop

Therefore its pretty important to use the JQ Variant

**Comment by adumesny** [comment]
I'm finding the html5 drag&drop less than idea, especially implemented quite differently on mac Safari... so I've been starting a new mouse only (and mobile pointer which is same) events instead. But that still a lot of work left.

**Comment by Justin99b** [comment]
Here is an example

Quickly created with vue cli

I did not add a working gridstack

but its enough to reproduce
Execute in this order

1 `yarn`
2 `yarn serve`
[reproduce.zip](https://github.com/gridstack/gridstack.js/files/6261889/reproduce.zip)

**Comment by adumesny** [comment]
the doc include has been updated with info and I have verified that it works on my angular app (v4 and V3) with webpack include directives.
