### ISSUE TITLE
Further Attributes on dragging from outsite

### ISSUE THREAD

**Issue by Bastilla123** [gridstack/gridstack.js#1717]
Hello,

i have on left side a draggable div. When a drag it in grid widget is add with attributes: 

{
    "x": 0,
    "y": 0,
    "w": 2,
    "h": 2,
    "id": "0"
  },

HTML Code from draggable div:

<div class="text-center card text-white grid-stack-item ListWidget ui-draggable" >
                    <div class="card-body grid-stack-item-content ui-draggable-handle">
                        <div>
                            <ion-icon name="add-circle" style="font-size: 400%" role="img" class="md hydrated"
                                      aria-label="add circle"></ion-icon>
                        </div>
                        <div>
                            <span>Insert Listwidget</span>
                        </div>
                    </div>
                </div>

i want to set further attributes like:

<div class="text-center card text-white grid-stack-item ListWidget ui-draggable" widgetmodule="Listwidget" >

and when HTML ist drag on grid this new attribute is set on object:

'widgetmodule':'Listwidget' 

How can implement this?

**Comment by adumesny** [comment]
please use the slack channel for questions.
