### ISSUE TITLE
When resizing direction north changing Y-axis is not working anymore [with movie]

### ISSUE THREAD

**Issue by ReseTTim** [gridstack/gridstack.js#1728]
## Subject of the issue
When I want to resize direction North / North west the item is not changing the Y-axis anymore.

The issue is occurred when I updated version from 4.0.1 to 4.0.2.
(I went back to 3.3.0 to pinpoint the precise version)

https://youtu.be/t2IqaDoAgs0

## Your environment
* Gridstack 4.2.0

## Steps to reproduce
Get to version 4.0.1 and use the drag handles `North` or `North west`.

## Expected behavior
When resizing `North` or `North west` you expect that the resizing item will be set on a lower Y-axis.

## Actual behavior
Item gets higher on the start position and after releasing

## For now
I went back to v4.0.1.

**Comment by adumesny** [comment]
can't say that I ever tried 'n' resizing ! (doc says not to use as unpredicted but don't see why) but if it works in 4.0.1 and not 4.0.2 then something we can look at.

next time provide an example (I mod float.html to have `resizable: { handles: 'se,sw,ne,nw,n,e,s,w'}}` and see the issue)

**Comment by adumesny** [comment]
fixed in next release. don't forget to contribute if you find lib useful
