### ISSUE TITLE
Drag preview of a custom widget is very slow

### ISSUE THREAD

**Issue by Etiake** [gridstack/gridstack.js#1729]
## Description
Hi, I created a dashboard with custom widgets, using the method "makeWidget", but I did not use "append" method because I have alredy the divs in the DOM. When I try to move one of those widgets very fast, it seems difficult for the drag preview to follow the mouse cursor. This did not happen with the previous version I used (Gridstack 2.0.2)

## Your environment
Gridstack version: 4.2.0 using HTML5, jquery free
Browser: Chrome Version 89.0.4389.114 (Official Build) (64-bit) / Windows10 10.0.19042

## Steps to reproduce
https://stackblitz.com/edit/js-xcy48w?file=index.js
Pick one of the widgets and move it fast in circle. The cursor movement will be replied slower and in a broken way by the drag preview. 

## Expected behavior
The UI should be more fluid while dragging the widget.

## Actual behavior
The UI for the preview of the dragged widget is slow.

**Comment by adumesny** [comment]
you want to set `{ disableOneColumnMode: true, float: true}` to better see this.

| This did not happen with the previous version I used (Gridstack 2.0.2)

sounds like this may be an html5 drag vs jquery (mouse event) difference. try the jq version to verify...

I'm not seeing much of a slow down, though it does lag a bit (chrome win10 as well) maybe post a video ? the long term is to re-write to native mouse event (and touch for mobile) as HTML5 drag has issues on Mac Safari and doesn't work on mobile anyway... and maybe slower after all.

**Comment by Etiake** [comment]
Thank you for the replay! I changed the configuration as you suggested. Here a video: 

https://user-images.githubusercontent.com/46519278/114516637-e1ca4600-9c3d-11eb-94ed-cc67ae85afcf.mp4

As you said, there's some lag.

**Comment by adumesny** [comment]
something else is going on in your browser as I'm NOT seeing that. Try another browser and also the JQ version...

https://user-images.githubusercontent.com/3496166/114575579-2995a100-9c2f-11eb-8f51-5fdb96c6f8e7.mp4

**Comment by Etiake** [comment]
I tried with Firefox (85.0), Edge(89.0.774.76 ) and Canary(92.0.4476.0 just for fun :P ) and the issue does not appear only with Firefox. So it's something with (my?) chrome-based browsers. With JQ version, gridstack works well in all browsers.

**Comment by adumesny** [comment]
closing as I'm not seeing that with Chrome or Firefox win10 - you said chrome at first, but then happens only in FF... guessing something with your browser.

**Comment by Etiake** [comment]
I didn't write that the slow does not work on Firefox.

**Comment by Etiake** [comment]
If you need any help for the future about this issue (maybe some future reports from other users), please feel free to write me via pm.

**Comment by adumesny** [comment]
"and the issue does not appear only with Firefox." I misunderstood your English then...

as I said it works fine on Chrome win10 for me, so you need to narrow down or see if others are seeing this as it may be an extension or a setting you have.
