### ISSUE TITLE
v3.1.5 JQ: New widgets get rejected for no obvious reason, leaving placeholder in DOM

### ISSUE THREAD

**Issue by riccardolardi** [gridstack/gridstack.js#1732]
## Subject of the issue
Beginning with 3.1.5 (jQuery) after having filled the grid with a certain amount of widgets, at a certain point new widgets will get rejected for no obvious. reason (they should fit since there is free space available). It seems that something then breaks within GridStack since the placeholder (dotted line) will stay in place in the DOM and not go away anymore. Only happens in jQuery GridStack, not in H5.

## Your environment
Mac, all browsers, issue appears starting from 3.1.5 jQuery, 3.1.4 works fine.

## Steps to reproduce
See video here: https://streamable.com/u092t0

## Expected behavior
The grid should accept the widget. 

## Actual behavior
The grid rejects the widget but leaves the placeholder staying in the DOM.

Any help is greatly appreciated.

**Comment by adumesny** [comment]
thanks for narrowing it down to 3.1.5 JQ version (all the way to 4.2.0 ?) and OK with h5 version (where my focus has been)

But you need to post a simple plain JS example showing the issue as I cannot go and debug your Vue code as it could be app specific... might want to use the demos web2.html or two.html as starting point until you see the issue there.

**Comment by adumesny** [comment]
closing due to no running example.
