### ISSUE TITLE
Set a static height

### ISSUE THREAD

**Issue by marwan-nwh** [gridstack/gridstack.js#1747]
I want to change the default heights, say `130px`, for `h: 1` for example, and `260px` for `h:2`.

Version: V3

**Comment by marwan-nwh** [comment]
I was trying to set `cellHeight` on the widget, not in the grid options. The docs is not obvious about it.

**Comment by adumesny** [comment]
what part of the doc made it sound like `cellHeight` was a per item setting ??
the doc has it clearly under GRID options, not widget options
![image](https://user-images.githubusercontent.com/3496166/115947997-45dfdc00-a480-11eb-9aeb-154044fc0f99.png)

**Comment by marwan-nwh** [comment]
The `Docs` link on the website refer to https://github.com/gridstack/gridstack.js/blob/master/README.md
I don't know the page you are referring to.

**Comment by adumesny** [comment]
the main doc above does not refer to `cellHeight` other than v2 migration for setting on the grid, so where did you get the idea it was a per item option ?

I was referring to the API doc https://github.com/gridstack/gridstack.js/issues/1747#api-documentation which is linked off the main general doc.
