### ISSUE TITLE
Adding Additional Classes 

### ISSUE THREAD

**Issue by Flexin1981** [gridstack/gridstack.js#1750]
## Adding Additional Classes 
Describe your issue here.

Hi guys, not sure if this has been broached before but I cant see it in the docs, I want to add bootstrap classes to the stack items but it is not clear in the docs if this is possible and how to do it in the JS or HTML.

I wanted to add bootstrap shadows to the elements do you have a quick example of this ?

**Comment by adumesny** [comment]
please use slack channel for questions.
