### ISSUE TITLE
Question: Is a native HTML5 version with mobile support planned? If yes when?

### ISSUE THREAD

**Issue by ManuelHaas** [gridstack/gridstack.js#1757]
Hi, is a native HTML5 version with mobile support planned? If yes when?

Thanks!

**Comment by adumesny** [comment]
Manuel, that is on my todo list as the next big thing for v5 - but I spent so much time and effort on 4.0 re-writing the collision code heuristics, with very little financial support (even from 2 people who promised to donate but never did) that I'm taking a break until I can figure out how to move forward, and not kill all my free time for peanuts and very little support...

**Comment by ManuelHaas** [comment]
Alain, I have just donated $50. Keep up the good work with this great library!

**Comment by adumesny** [comment]
Update: I am trying to tackle this and have updated my 'mousemove' branch to the latest code, and simple dragging (within a grid, no in/out) is working with raw move events now.

**Comment by adumesny** [comment]
fixed in just released v6!
