### ISSUE TITLE
Not possible to display confirmation before dropping widget into trash

### ISSUE THREAD

**Issue by SodyM** [gridstack/gridstack.js#1758]
## Subject of the issue
It's not possible to display confirmation dialog before delete of widget (or before dropping widget into trash)

## Your environment
HTML5

## Steps to reproduce
No need to provide it, this feature is not supported

## Expected behavior
Display confirmation dialog before delete of widget (or before dropping widget into trash)

## Actual behavior
Tell us what happens instead
It's not possible to display confirmation dialog before delete of widget (or before dropping widget into trash)

**Comment by adumesny** [comment]
most user will have an [X] button to remove a widget, which you have complete control over. But if you drag onto a trash, I agree there is no easy way to intercept and ask the user for confirmation...

feature request. Not high priority so unlikely to happen anytime soon. If you need this, please contribute.

**Comment by adumesny** [comment]
clsing as old and no traction...
