### ISSUE TITLE
h5: Items that contain a canvasJS chart cannot be dragged.

### ISSUE THREAD

**Issue by iNomad23** [gridstack/gridstack.js#1759]
## Subject of the issue
Hey,

First of all my compliments for this amazing library.
I love it and use it since v0.6.

I run into a problem though.

Please take a look at the .html file in the following _Steps to reproduce_ sector and try dragging the grid item that has the canvasJS chart in it. Somehow inside the canvas area the item cant be dragged. I used v1 before and it worked there. (used with jquery).

## Your environment
I am using the gridstack-h5.js (v4.2.3)
Chrome

## Steps to reproduce

[GridWithCanvasJS_demo.zip](https://github.com/gridstack/gridstack.js/files/6522636/GridWithCanvasJS_demo.zip)
Just copy the extracted canvasJS.html in your demo folder.

## Expected behavior
The grid item should be able to be dragged within the canvas area as in v1 + jquery

## Actual behavior
Inside the canvas area the item cant be dragged.

**Comment by adumesny** [comment]
still works in the JQ version. the graph must be preventing html5 drag events but to be honest, I have similar needs in my app and I use an explicit title area where the move (with cursor feedback) and close and other actions happen, as you want user to be able to interact with the graph (which might itself have drag behavior). I think that's a better UX behavior anyway (make it explicit area to move vs interact.

**Comment by iNomad23** [comment]
Hey,

thank you for your fast response.
Our project has two states. _Edit_ mode and _View_ mode, so we dont have a need for a explicit area to move the chart.

**Edit Mode**:
User can create his dashboard, add/delete/move items etc. 
**View Mode**:
User can only interact with created items (zoom, pan etc.).

Hope this is on your very long todo list. (and hopefully in the next or after next release ;) )

Best regards.

**Comment by iNomad23** [comment]
Some information i observed (reduce potential debug time)

CanvasJS creates two canvases
![image](https://user-images.githubusercontent.com/80402122/119162108-4c02b180-ba5a-11eb-8f69-9163161820c4.png)

If you delete the interaction canvas (second one) you can drag the grid item again but obviously no interaction is possible anymore.

**Comment by adumesny** [comment]
my next long term item is to remove html5 drag and use raw mouse/pointer events (similar to what JQ does) so we can support mobile natively - so this bug would go away, and therefore unlikely to be looked at.

**Comment by iNomad23** [comment]
okay good point,

do you have a plan for when you will start this implementation?

**Comment by adumesny** [comment]
sorry I do not. while I have started, I need to take a break and see if I can turn this into a commercial product as it's a huge time sync with very littler reward...

**Comment by iNomad23** [comment]
okay - no problem - take your time

we will try to use the JQ version instead.

**Comment by adumesny** [comment]
not using draggable in v6 so closing (hope it's fixed)
