### ISSUE TITLE
Custom layout doesnt work

### ISSUE THREAD

**Issue by qbunia** [gridstack/gridstack.js#1765]
## Subject of the issue
Using custom layouts doesnt change x position of items

## Your environment
- 4.2.3 version of  gridstack
- Firefox 88.0.1

## Steps to reproduce
https://jsfiddle.net/kverwscx/7/

## Expected behavior
My items should be next to eachother. 2 columns, so 1st item in 1st column and 2nd item in 2nd column.

## Actual behavior
Items are placed in the same 1st column having x = 0

**Comment by adumesny** [comment]
I cleaned up your example and it's working 'correctly' (side by side - but your logic assume they come in a predefined order which is not the case).
see https://jsfiddle.net/adumesny/nuwax6t7/

**Comment by qbunia** [comment]
I see I didnt set width to 0 to make it work. Thanks!
I`m thinking to donate some money for this project. Still testing it out tho.

**Comment by adumesny** [comment]
width not set means 1, not 0 (not valid). didn't think that matters

**Comment by qbunia** [comment]
Ok I see now, I had width 2 and wanted to set 2 columns so it was obvious it was taking space of 2. If I set width to 1 and set 2 columns it works.
