### ISSUE TITLE
Resizing widget.

### ISSUE THREAD

**Issue by Seregapolygon** [gridstack/gridstack.js#1775]
When I resize widget, screen scroll down too fast and mouse cursor don't match the real place where it have to be. Any bit moving of mouse cursor resizes the widget it two or three times.

I don't know the version of gridstack because I use 
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
+ vue js 
+ yandex/chrome browser

Steps to reproduce
https://youtu.be/F02MLOZ0RJA 

Expected behavior
The mouse cursor don't have to run to the bottom.

**Comment by adumesny** [comment]
I seem to recall committing a fix for that, and if you use the latest build example (see https://gridstackjs.com/ or https://gridstackjs.com/demo/web1.html) the resize scroll behaves as expected.

closing as you don't specify the version or have a reproduceable simple example.
