### ISSUE TITLE
How can i load a Vue component inside of an item?

### ISSUE THREAD

**Issue by Jacks349** [gridstack/gridstack.js#1776]
First of all, thank you for working on GridStack, it works flawlessly and it's very easy to use. I'm trying to integrate it with my Vue 2 app, but i'm having a lot of problems loading a component from inside a grid item. I'm using GridStack 4.2.5 and Vue 2.

I know how to create new items with some HTML dynamically from Vue, but i'm struggling to load a component, since it just won't load. I created a sandbox with my code here: https://codesandbox.io/s/weathered-grass-nue08?file=/src/App.vue

In the example i tried to compile the component with `makeWidget`, but nothing happens. The examples are very clear and extensive, but i didn't manage to find one where instead of just html, a component is loaded inside of the item. Any kind of advice is appreciated!

**Comment by adumesny** [comment]
please post this to the slack channels as others might have solution for you (I don't use Vue)... with frameworks (I use angular) it's usually best to use that framework to create the entire HTLM/DOM and just call makeWidget() to add gridstack functionality to an existing div in a grid...
