### ISSUE TITLE
MinWidth prevents from retrieving old dashboard's widgets sizes and positions

### ISSUE THREAD

**Issue by lozah** [gridstack/gridstack.js#1778]
Hello,

I'm using gridstack (v4.2.5) for quit a while now with angular (v12).
I'm facing today a strange issue, let me explain.

My grid is composed of multiple widget loaded in the HTML page. The grid has 12 columns and transform to 1 under a certain width. I calculate the change manually since the default `oneColumnMode` of gridstack behaved strangely. 

Until now I only used params `w`, `h`, `x` and `y` for the widgets and the draggable option. I wanted to add the resize option and it worked like a charm. With this new feature added to my gridstack it felt like it was a good idea to add a minimum width and height to the widgets. 

But since I added these new params, the grid can't retrieve previous width of my widgets after the transition between 1 column and 12 column mode. Before when the grid changed to 1 column and then again to 12 columns every widgets had the same size and same position than before the transition to the one column mode. Now after going back to 12 columns every widget keep the position of the one column mode (one widget per line) AND their width take the value of the `minW` attribute. All widget lose their state they had before the one column mode.

The only change I made was to add: `[attr.gs-min-w]="stat.minW" [attr.gs-min-h]="stat.minH"`, but it breaks everything. 

Do you now what can be the source of this issue ?
Thank you

EDIT: I made a stackblitz to illustrate my issue https://stackblitz.com/edit/angular-ivy-ni4gh3?devtoolsheight=33&file=src/app/app.component.html
You can see when you resize the window that widgets don't go back to their original position. 
Now try removing in the html the property for `min-w` and `min-h` and everything works fine again

**Comment by adumesny** [comment]
Hey first, since you're on Angular, would you mind creating a demo file like https://github.com/gridstack/gridstack.js/blob/master/demo/react.html and https://github.com/gridstack/gridstack.js/blob/master/demo/vue3js.html ?

| I calculate the change manually since the default oneColumnMode of gridstack behaved strangely.

Humm... please explain as one column should happen only with grid itself is < `minWidth`

I see the issue. good thing I use angular, but it's best to post a pure gridstack example so I don't have to debug UI frameworks as well...

**Comment by adumesny** [comment]
FYI, you should use `ngAfterViewInit()` instead - and not some dummy timer... see https://github.com/gridstack/gridstack.js/blob/master/demo/angular-ngFor.ts#L36

**Comment by lozah** [comment]
Hey, sorry for late response, I'm under a massive amount of work.


> Hey first, since you're on Angular, would you mind creating a demo file like https://github.com/gridstack/gridstack.js/blob/master/demo/react.html and https://github.com/gridstack/gridstack.js/blob/master/demo/vue3js.html ?

Ok, I'll try to find some time to do this

> Humm... please explain as one column should happen only with grid itself is < `minWidth`

The smooth animation is lost when into the default one column mode. While it works well when changing columns dynamically

> I see the issue. good thing I use angular, but it's best to post a pure gridstack example so I don't have to debug UI frameworks as well...

Do you want me to post a pure js example ? Or you mean for next time ? 

> FYI, you should use `ngAfterViewInit()` instead - and not some dummy timer... see https://github.com/gridstack/gridstack.js/blob/master/demo/angular-ngFor.ts#L36

Yup, I used `setTimeout` because in my project implementation I need it for some other reason. But you're right, for this basic example `ngAfterViewInit()` do the job. I updated My angular demo so the code is more concise with `oneColumnMode` and without the dummy `setTimeout`

**Comment by adumesny** [comment]
no need for angular demos, I created 2 (thought I did not finish/find a solution to track changes in the ngFor case).

| The smooth animation is lost when into the default one column mode. While it works well when changing columns dynamically

weird, it should call setColumn(1) when width < minWidth. file a bug please...

| Do you want me to post a pure js example ?

yes please, as I can't debug your angular example without a lot of hassle (re-create locally and copy full debug libs)

**Comment by lozah** [comment]
Hello, I finally managed to find some time to create the demo file: https://jsfiddle.net/pLhgnbwv/2/
Hope it will help !

**Comment by adumesny** [comment]
thanks, I can see the issue https://jsfiddle.net/adumesny/deay8o5p/

**Comment by lozah** [comment]
Hello ! Just wanted to know if you're planning to fix this issue soon or not ?

**Comment by adumesny** [comment]
did you wan to make a donation for this fix ? not something common I will address anytime soon otherwise.

**Comment by Chris-KCIT** [comment]
> Hello, I finally managed to find some time to create the demo file: https://jsfiddle.net/pLhgnbwv/2/
> Hope it will help !

I'm so glad you found the source of this bug, I'm having the exact same issue since upgrading!

**Comment by adumesny** [comment]
I believe this got fixed and dup of #1835 - will be in next release today.
if you find lib useful, don't forget to donate.
