### ISSUE TITLE
Drag sensitivity / positionning issue

### ISSUE THREAD

**Issue by studio-indelebil** [gridstack/gridstack.js#1781]
Hi,
We encounter some issues with drag & drop, blocks seem to move too soon / too late depending on if we are dragging upward or downward, as illustrated below :
![ice_video_20210607-164146](https://user-images.githubusercontent.com/10560501/121038472-a026c900-c7b0-11eb-9381-2aaf6b0aac8d.gif)
It kinda look the same at [https://github.com/gridstack/gridstack.js/issues/1094](url), but strangely on your demos it works pretty well, like moving at 50% reach of width/height. 
Could it be related to some CSS problem in our side? 
Thanks for your help & great work btw

**Comment by adumesny** [comment]
could be CSS, or could be the DOM and internal node values (used for collision) bein out of sync.. you don't say how you create your grid. You will need to post a simple reproduceable case for it to be considered... thanks.

**Comment by studio-indelebil** [comment]
Thank you for your quick answer. Here's a very simple example :
[https://indelebil.dev/gridstack/test.html](url)

**Comment by adumesny** [comment]
you have `column:24` but you don't include the custom CSS for it - see https://github.com/gridstack/gridstack.js#custom-columns-css

**Comment by adumesny** [comment]
can't easily see the styles... also you have `cellHeight:10` with default padding of 10 meaning your cells content are 0 sized. try a larger value (or no padding) and see if that fixes the issue.
