### ISSUE TITLE
Removable true doesnt work

### ISSUE THREAD

**Issue by qbunia** [gridstack/gridstack.js#1784]
## Subject of the issue
I set removable to true and when moving item outside grid the item is not removed.

## Your environment
- gridstack v4.2.4
- firefox, windows 10

## Steps to reproduce
https://jsfiddle.net/3nazp2Lb/3/

## Expected behavior
Item is removed when dragged outside grid

## Actual behavior
Item is not removed

**Comment by adumesny** [comment]
weird, because I thought I fix it in #1760

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful!

**Comment by qbunia** [comment]
Thanks, just sent money. Paypal is horrible, It cost me like 6$ to send money to paypayl. Then Paypal charged me with bad conversion rate of currencies. Then Paypal took around 3$ to send you money. I think it would be cheapier if you would have cryptocurrency option enabled.

**Comment by adumesny** [comment]
thank you. I don't use cryptocurrency (too volatile) but maybe there is another cheaper service (I use venmo for that reason as well, but US only ?) that works better in other parts of the world as many customers seems to be in Europe or Asia
