### ISSUE TITLE
Bootstrap breakpoints not working when resize grid-item

### ISSUE THREAD

**Issue by kraussjo** [gridstack/gridstack.js#1790]
## Subject of the issue
Bootstrap Layout not working, when resize an gridstack item. If you change the browser window it works.

## Your environment
4.2.5 HTML5
all Browser, all OS

## Steps to reproduce
https://jsfiddle.net/d3kz4j1a/5/

## Expected behavior
When resizing the item, the bootstrap grid should position itself as if you change the browser window

## Actual behavior
The bootstrap grid changes correctly only when the browser window changes

**Comment by adumesny** [comment]
can you add a video and I'm not seeing the issue (and color your regions to make it easier).

**Comment by kraussjo** [comment]
I have made two files:

Grid resize

![gridResize](https://user-images.githubusercontent.com/38663002/122342692-342d2900-cf45-11eb-8cd1-a98125938008.gif)

Browser resize

![windowResize](https://user-images.githubusercontent.com/38663002/122342761-427b4500-cf45-11eb-8ce7-5af1c07d9af4.gif)

The Bootstrap breakpoints  only work when changing the browser size.

Thanks

**Comment by brambekkers** [comment]
I would also like to know the solution if it exists!

**Comment by adumesny** [comment]
ha, that is because I use window resize event to detect when things change (the ONLY event generated) and there is no `my parent resized me down` that I know of... you would need to catch that and call `grid.onParentResize()`
