### ISSUE TITLE
How to allow collisions between nested elements on a widget

### ISSUE THREAD

**Issue by santiagoamo** [gridstack/gridstack.js#1796]
## Subject of the issue
How to allow collisions between nested elements on a widget

## Your environment
*  I'm using gridstack-h5.js, I don't know the version, is 4.x, on the file don't appear (I downloaded it on march 2021)
* Chrome on Windows 10

## Steps to reproduce
A way or option to allow overlap some elements on a widget

## Expected behavior
Can put a element over other or others one (avoid collisions)

## Actual behavior
I don't find an option to do this

**Comment by adumesny** [comment]
please use slack for questions. You can't allow overlapping of widgets, but I've seen people put 2 grids on top of each other offsetted to make 'groups of overlapping widgets).
