### ISSUE TITLE
Limit to full screen / cell height

### ISSUE THREAD

**Issue by sdraper69** [gridstack/gridstack.js#1797]
I would like to have a full screen grid. Im happy with 12 columns, and am happy to define a number of rows, for sakes of argument lets say 12. I would like it to remain 12x12 no matter my screensize.

First thing i did was set the grid div to be 100% width and 10% height....

First I would like it so the top edge of an item on the top row, touches the top of the browser window and the  bottom edge of an item on the bottom row aligns with bottom of my browser window, hence the cell height is calculated as a % of the container div height -  is this possible?

I would like to be able to position my items anywhere in the grid - float seems to do the job, but then I can move them off the screen, creating overflow. I just want to limit to the screen  - is this possible??

**Comment by adumesny** [comment]
please use slack channel for questions.
