### ISSUE TITLE
Gridstack.js stops responding after moving some newly added widgets

### ISSUE THREAD

**Issue by bnisevic** [gridstack/gridstack.js#1798]
## Subject of the issue
After adding some new widgets and changing their positions gridstack.js stops working. Drag and drop is not working anymore. 

## Your environment
* gridstack.js v4.2.5 AND using HTML5
* FireFox 89.0.1 (64-bit), Ubuntu 20.04

## Steps to reproduce
Screencast here: https://drive.google.com/file/d/1XIwlbmUy4iI2E_Pb5T3G35iPiMSNrfWd/view?usp=sharing

## Expected behavior
Drag and drop should continue working

## Actual behavior
Drag and drop does not work

**Comment by adumesny** [comment]
you need to provide running code example as the bug template asks. I'll re-open once you do.
