### ISSUE TITLE
After adding new widgets gridstack.js ignores columns in the last row

### ISSUE THREAD

**Issue by bnisevic** [gridstack/gridstack.js#1799]
## Subject of the issue
After adding new widgets if there is empty space in the last row, it is not possible to position widgets in columns in that last row. Look at the screencast attached.

## Your environment
* gridstack.js v4.2.5 AND using HTML5
* FireFox 89.0.1 (64-bit), Ubuntu 20.04

## Steps to reproduce
Screencast here: https://drive.google.com/file/d/1Pmdw1Zgf0HSTU99jxDaGKoDhXflyse5_/view?usp=sharing

## Expected behavior
Widgets should stick to the positions in the new row when hovering over them.

## Actual behavior
Widgets fly to the next closest cells.

**Comment by adumesny** [comment]
you need `float:true` to position anywhere.

**Comment by bnisevic** [comment]
Thanks. float: true helped.

**Comment by bnisevic** [comment]
Actually `float: true` does not solve this issue. I need widgets to stick into column positions and not to be able to be dropped anywhere. So, it should work like on the screencast, but also to be able to drop in the new last row which now is not possible.

**Comment by bnisevic** [comment]
`float:true` solves dropping into a new last row, but it does not solve equal space between widgets.
