### ISSUE TITLE
H5???

### ISSUE THREAD

**Issue by Bastilla123** [gridstack/gridstack.js#1800]
## Subject of the issue
I loading last zip file. Html demo/nested.html will loading file:///home/sebastian/Downloads/gridstack.js-4.2.5/dist/gridstack-extra.min.css but /dist directory is not avalaible. Also in Github Repo. Where can i loading gridstack-h5.js???

## Your environment
* version 0.2.5
* 
* which browser/OS
Windows 10 Pro/Chrom lasted version
## Steps to reproduce
You loading from https://github.com/gridstack/gridstack.js/#install zip extract all files and open /demo/nested.html and in network view you see that several js/css are not loading

## Expected behavior
Tell us what should happen

## Actual behavior
Tell us what happens instead

**Comment by adumesny** [comment]
h5 is v3+ and you need npm install to get the build.
