### ISSUE TITLE
How to do multi level nesting in gridstack js

### ISSUE THREAD

**Issue by aubrijesh** [gridstack/gridstack.js#1803]
Hi I was trying to do multilevel nested in this plugin. I was not able to find any solution to this. I tried using https://gridstackjs.com/demo/nested.html and making to some modification to it but looks like multilevel nesting not working properly. Any Suggestion ?
**EDIT:**
I have created this codepen to show this issue.. I can't drag nested child to outside current parent and append in main droppable area. I have tried putting acceptWidgets: '.grid-stack-item' in parent init but after that placeholder position is showing very far away from cursor. 
https://codepen.io/aubrijesh/pen/VwbwEbZ

**Comment by adumesny** [comment]
sounds like a dup of #992, which was scheduled to be implemented with a donation, but didn't go through...

**Comment by aubrijesh** [comment]
Thank you @adumesny for your reply
