### ISSUE TITLE
set gs-x,gs-y unsuccessful

### ISSUE THREAD

**Issue by HeiYanjing** [gridstack/gridstack.js#1804]
## Subject of the issue
 in react-hook
```
const [arr,setArr] = useState([]);
...
render(
   arr.map((item:any)=>{
      return <div className='grid-stack-item' gs-x={item.x} gs-y ={item.y} gs-w={item.w} gs-h={item.h} id={item.code} 
                 ref={refs.current[item.code]}>
                       {my content}
                 </div>
   })
)
```

when first time render,  I sort arr and set suitable x,y,w,h .
when i change the node,  I sort the arr,setArr a new vlaue,   and set suitable x,y,w,h ,I checked  x,y,w,h,all is suitable.
buti it not work,  some nodes gs-x ,gs-y  value reassignment .
so ,the sor disorderly arrangement

## Your environment
chrome,react-hook
``

**Comment by adumesny** [comment]
I can't debug or reproduce your issue without a running simple code... if you update values, you will need to call update() instead, if you re-create the grid from scratch you need to properly destroy() and init() or load() again. I assume you looked at the react examples..

closing until you can provide a running example showing lib issue and not your code.
