### ISSUE TITLE
Initialize HTML-DOM with nested grid

### ISSUE THREAD

**Issue by EinAWELehrer** [gridstack/gridstack.js#1805]
## Subject of the issue
When I try to initalize a HTML-DOM with nested Grid and GridStack.initAll() it is not working correct.
But when i resize parent item (more than half of the page) then suddendly it is working fine (see fiddle).

## Your environment
gridstack 4.2.5

## Steps to reproduce
https://jsfiddle.net/jcxunrsv/1

## Expected behavior
I think the problem is that the subgrid starts always with grid-stack-1. When i resize parent item then it switch to grid-stack-12 and it is working fine.

Is this a bug or is GridStack.initAll() not the right way to deal with nested grids?

**Comment by adumesny** [comment]
thanks for the demo but it's not a bug, if the size is less than `minWidth` a grid (nested or not) will got to 1 column. you can turn that off `disableOneColumnMode` or change the `minWidth`. 

See https://github.com/gridstack/gridstack.js/blob/master/demo/nested.html#L42 (those are available as dom attributes as well).

**Comment by EinAWELehrer** [comment]
Hi adumesny,
thank you for your quick answer.
I will try it. Important for me to know, that it is possible to work with a given HTML-DOM structure and GridStack.iniAll().

**Comment by adumesny** [comment]
you're welcome. don't forget to donate if you find this lib useful.
