### ISSUE TITLE
how to set gs-x gs-y successful

### ISSUE THREAD

**Issue by HeiYanjing** [gridstack/gridstack.js#1806]
## Subject of the issue
set gs-x gs-y unseccessful

## Your environment
* gridstack 4.2.5 
*  react-hoook
* chrome

## Steps to reproduce
I have a array.
```
const [arr,setArray] = useState<any>([]);
return(
 arr.map(item:any)=>{
    return  <div className="grid-stack-item" gs-x={item.x} gs-y={item.y} gs-w={item.w} gs-h={item.h} id={item.id} resf= 
                     {refs.current[item.id]}>
                  {my component}
               </div>
     }
)
```
In grid.on("change",myChange);
I reorder the item. and Set new x position ,y position value for gs-x,gs-y. but it unsuccessful.
gridstack reassign gs-x,gs-y.

## Expected behavior
how to set gs-x gs-y successful.

## Actual behavior
Tell us what happens instead

**Comment by adumesny** [comment]
dup #1804
filling the same bug again doesn't help. update the original one with needed info and we can re-open it.
