### ISSUE TITLE
How to stop GridStack elements becoming wider after a sreen size decreasing (less than 830px)

### ISSUE THREAD

**Issue by private-doggo** [gridstack/gridstack.js#1815]
I want to implement iOS keyboard using this library. I faced 2 problems so far. Minimal height and width of an element are too big even if I can change columns number and make width smaller I can't do this with element height (I need cell height and width to be equal). The second problem is that if I make my screen width less than 830 px then all the elements get width: 100%. How do I stop this behaviour?

## Your environment
v4.2.5
Chrome, Windows

## Steps to reproduce
https://gridstackjs.com/#demo Just make the screen width 829px and the blocks will become wider up to 100%.

## Expected behavior
I want them to remain of the same width and height (not in px but in %).

## Actual behavior
Instead element width and height are changed by the library.

**Comment by adumesny** [comment]
use slack channel for questions please. you need to use `disableOneColumnMode:true` and then you can have as many columns as you need (see https://github.com/gridstack/gridstack.js/blob/master/spec/e2e/html/810-many-columns.html as an example, don't forget custom CSS) with `cellHeight:'auto'` (the default) to have them square.
