### ISSUE TITLE
fixed size item and Media Breakpoints Options?

### ISSUE THREAD

**Issue by agnemedia** [gridstack/gridstack.js#1818]
## Subject of the issue
Looking for Options / col*calc for fix width size

## Your environment
gridstack.js 4.2.6, jQUERY, VUE 3, TypeScript, SCSS with update mixing to .px

## Steps to reproduce
setup with 9 column (each container fix 180x180 px) all  grid col update to fix width 180px + 5px padding
{ x: 0, y: 0, width: 1, height: 1 },

if screen smaller can't fit 9 items only 8+1 (no scaling) task:  1-item*9 = 180px media screen 1440px / issue 1 container can't fit (media browser view ~1710px)  currently creat wide scroller

## Expected behavior
grid setup with 9 column
1 row will show 8 items (9th items/column move to row 2 because (fixed .px oversize to fit) 8 col with is maximum occupied)
2 row add +1 (9) +1 (10) .....11, 12, 13, 14, 15, 16 >17 will start from 3 row
is it possible?

## Actual behavior
Tell us what happens instead

**Comment by adumesny** [comment]
please use the slack channel for questions, or provide a running example to sow your issue/request. If you are looking for fixed column sizing, this isn't the lib for you...
