### ISSUE TITLE
Programmatically Close Up Gaps

### ISSUE THREAD

**Issue by iamseanduffy** [gridstack/gridstack.js#1819]
v4.2.3

Scenario:
I have a grid of tiles, however due to a runtime condition one or more of the tiles should not be rendered:

![Screenshot 2021-07-26 191725](https://user-images.githubusercontent.com/1789160/127038709-aa8c1790-a284-459c-bc6d-ff1acd50bddb.png)

I am looking for a way to programmatically 'refresh' the grid stack and close up the gaps.

Any suggestions? Is this possible?

**Comment by adumesny** [comment]
please use slack channel for questions
