### ISSUE TITLE
Gridstack with native HTML5 drag&drop in a translateX parent

### ISSUE THREAD

**Issue by lacroixdavid1** [gridstack/gridstack.js#1820]
## Subject of the issue

Did anyone ever managed to get Gridstack working in a parent container styled with `transform: translateX(280px);`?
 Our application side menu / main content is working using transform CSS property to ensure optimal animation performance. When I drag an item, it starts dragging incorrectly 280px left. I have found a similar issue https://github.com/gridstack/gridstack.js/issues/1275 but this one is about `transform: scale()`. Layouts using CSS transform: translateX()  are pretty used everywhere AFAIK. 

Also, I failed trying to reproduce https://plnkr.co/edit/YhKLL6xqidoBGMdl using this plunker. Might it be because it's using an older version of Gridstack with jQuery UI?

## Your environment

Gridstack 4.2.6
Chrome
Native HTML 5 Drag and drop

## Steps to reproduce

https://jsfiddle.net/tj6pn2ux/

## Expected behavior
Dragging an item should start from where the item actually is

## Actual behavior
Begin to drag an item break its location.

**Comment by lacroixdavid1** [comment]
I'm mostly sure the issue comes from https://github.com/gridstack/gridstack.js/blob/master/src/h5/dd-draggable.ts#L301.

Method `_getDragOffset` seems to try to handle that scenario, reading to code it looks to only work when then `transform` is applied directly to Gridstack. If the style applies to a parent, it doesn't work as expected. Am I missing something?  

I currently dealt with it by hacking CSS in my application.

```
    ef-gridstack-item + div:not(.grid-stack-item):not(.grid-stack-placeholder) {
      // https://github.com/gridstack/gridstack.js/issues/1820
      transform: translateX($distance * -1);
    }
```

**Comment by adumesny** [comment]
| Layouts using CSS transform: translateX()  are pretty used everywhere AFAIK

and yet this is the first mention of this bug, so no I don't think it's common or it would have come before and have multiple votes. as you mentioned #1275 is likely similar issue (but with scale) and not planning on looking at those unless someone wants to donate or submit a fix. thank you

**Comment by lacroixdavid1** [comment]
The point isn't about how common it is or not. That scenario was handled fine by using jQueryUI and an older Gristack version. For this reason, it should be addressed in my opinion.

**Comment by adumesny** [comment]
H5 is a total re-write, and of course it will have different bugs... I don't have the bandwidth to fix everything, so how common is important criteria... you can always use an older jq version or donate to get it fixed...

**Comment by lacroixdavid1** [comment]
I understand. I could submit a PR that would fix my case, but it would remove completely that code.

```   
 let xformOffsetX = 0;
    let xformOffsetY = 0;
    if (parent) {
      const testEl = document.createElement('div');
      DDUtils.addElStyles(testEl, {
        opacity: '0',
        position: 'fixed',
        top: 0 + 'px',
        left: 0 + 'px',
        width: '1px',
        height: '1px',
        zIndex: '-999999',
      });
      parent.appendChild(testEl);
      const testElPosition = testEl.getBoundingClientRect();
      parent.removeChild(testEl);
      xformOffsetX = testElPosition.left;
      xformOffsetY = testElPosition.top;
      // TODO: scale ?
    }
    ```
  
I don't know why it's there. Is there any issue you know I can relate to? 

I won't do money donation but I have a neat Angular 12 wrapper for this library that I could share that could replace https://github.com/gridstack/gridstack.js/blob/master/demo/angular.ts.

**Comment by adumesny** [comment]
I actually didn't write _getDragOffset() code - rhlin did, so I'm not clear how/why it being used but it appears to be there to fix eactly the offset (and eventually scale) issue... but apparently doesn't. Might be good to look at old jqui code and see how they handled offsets/scales, though they don't use 'fixed' positionning if I recall (was issue clipping between nested grids, which I do difefrently now)

```js
style.position = 'fixed'; // let us drag between grids by not clipping as parent .grid-stack is position: 'relative'
```

**Comment by adumesny** [comment]
working as ecpected in latest rev (suspect 6.+ but checked 7.1.1) - added demo example. closing.
