### ISSUE TITLE
How to set widget maximum height ?

### ISSUE THREAD

**Issue by houynarun** [gridstack/gridstack.js#1821]
I want to set the maximum height of widget during resizing, is here an option I can do that? For example: I want to limit max height of widget to h:5, Thanks

**Comment by WongYueKeung** [comment]
https://github.com/gridstack/gridstack.js/tree/master/doc#item-options
option: maxH
or add 'gs-max-h' in ur item html attribute
example: <div gs-w="2" gs-h="15" gs-max-w="3" gs-max-h="5" class="grid-stack-item sub ui-draggable ui-resizable ui-resizable-autohide" gs-x="2" gs-y="1" >

**Comment by adumesny** [comment]
maxH is the gridOption. Please use slack channel for questions.
