### ISSUE TITLE
If button tag is assigned to node.content in react.html code file for gridstack, on website [object, Object] is being rendered which is incorrect.

### ISSUE THREAD

**Issue by atharvkulkarni1998** [gridstack/gridstack.js#1822]
## Subject of the issue
If I am assigning a "button tag" to node.content, the value being rendered on the website app is [object Object].

## Your environment
Gridstack used in react application 
"react": "^17.0.2",
    "react-dom": "^17.0.2",

## Steps to reproduce
1. install and import Gridstack in react application.
2. Use "react.html" file from the demo folder present on github. Make necessary changes in the react application to run the gridstack project.
3. Navigate till function addNewWidget() and set the value of "node.content" to "button tag".
4. Run the application and click on "add widget" button to add a widget.
5. After the widget is added not able to view the button instead [object Object] is being displayed.

## Expected behavior
After clicking on add widget, button should be rendered as the content of the widget.

## Actual behavior
After clicking on add widget [object Object] is being displayed for the content part of the node.

Attachments:
![image](https://user-images.githubusercontent.com/47672353/127486884-9472900d-999a-4528-9f27-c47537e89f5a.png)

![image](https://user-images.githubusercontent.com/47672353/127486953-70beb24e-5128-4ccc-a9db-825fef42111c.png)

**Comment by adumesny** [comment]
first of all node.content is a string (to be inserted as innerHtml), not a tag, second you don't provide a working example. Closing until you show that's a lib bug and not user error.
