### ISSUE TITLE
Angular ngFor example not complete, can't drag newly added items

### ISSUE THREAD

**Issue by lingling-ding** [gridstack/gridstack.js#1823]
https://github.com/gridstack/gridstack.js/blob/72d8239337b3ca43bebe1528e473d71f39ea2f93/demo/angular-ngFor.ts#L45

**Comment by adumesny** [comment]
well Duh, I added comments in there that angular wasn't behaving the way I expected and hoping someone could take a look...

I don't use ngFor in my angular wrapper (user dynamic components) .

**Comment by lacroixdavid1** [comment]
Hi @lingling-ding. See PR https://github.com/gridstack/gridstack.js/pull/1824. This is the wrapper I'm using. It's compatible with ngFor even when using a trackByFn and no tracked value changed.

**Comment by lingling-ding** [comment]
> Hi @lingling-ding. See PR #1824. This is the wrapper I'm using. It's compatible with ngFor even when using a trackByFn and no tracked value changed.

@lacroixdavid1 thank you so much, it works quite well now.

**Comment by stevehaneytrailblazer** [comment]
Hi @lacroixdavid1 or @lingling-ding  , I tried using the PR you referenced but for some reason nothing inside my ef-gridstack is rendering at all.  I tried to just pre-load 2 items and in the DOM the ef-gridster-item does not render at all.  I believe I'm using your PR almost 100% as I'm just trying to get it working before tweaking.  Do you recall if you ran into this issue?  I'm guessing I'm missing something obvious but I'm a bit new to Angular.  Thanks!

**Comment by adumesny** [comment]
fixed by #1961
