### ISSUE TITLE
Snap to grid not working when moving widgets inside of grid after v2 upgrade

### ISSUE THREAD

**Issue by BradErickson** [gridstack/gridstack.js#1827]
## Subject of the issue
We are using dynamically loaded angular components that are placed on gridstack. When we call enableMove() the snap to grid no longer is working after we went to v2. We have followed all of the instructions that were on the main github page for migrating from v1 to v2. Everything was working great in V1 but now in v2 we lost functionality to edit our grid. If we initialize the grid stack instance with the enable drag property it seems to work as expected, but we need to have an edit move so it has to start off as being set to false. We call enableMove() and you are able to drag stuff around, but it allows overlapping and dragging off grid. 

## Your environment
We are trying to go to version 2. Everything was working fine when we had it at v1.
Angular 10
* which browser/OS
* google chrome

**Comment by adumesny** [comment]
you need to provide a running example showing the issue as the bug template mentions. I would also test it against v4 as it's likely to be fixed (if no file away), closing until you do.
