### ISSUE TITLE
makeWidget documentation - appendChild() takes a node not a string

### ISSUE THREAD

**Issue by abulka** [gridstack/gridstack.js#1830]
The `makeWidget` [documentation](https://github.com/gridstack/gridstack.js/tree/master/doc#makewidgetel) seems to wrongly pass a string to the DOM's `appendChild()` which actually needs a node object. Is the documentation correct?

```js
  grid.el.appendChild('<div id="gsi-1" gs-x="0" gs-y="0" gs-w="3" gs-h="2" gs-auto-position="true"></div>')
  grid.makeWidget('#gsi-1');
```

The above official example doesn't work. I got this to work instead:

```js
    var textnode = document.createTextNode("Water");
    var node = document.createElement("LI");                 // Create a <li> node
    var textnode = document.createTextNode("Water");         // Create a text node
    node.appendChild(textnode);                              // Append the text to <li>
    grid.el.appendChild(node)
    grid.makeWidget(node);
```

which creates and passes nodes.

## Your environment
* gridstack.js 4.2.6
* Edge / Chromium Version 92.0.902.67 on Mac Mojave

## Steps to reproduce
```js
  function addWidgetUsingMakeWidget() {
    grid.el.appendChild('<div id="gsi-1" gs-x="0" gs-y="0" gs-w="3" gs-h="2" gs-auto-position="true"></div>')
    grid.makeWidget('#gsi-1');
  }
```

## Expected behavior
Widget should be added

## Actual behavior
Console error `Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.`

**Comment by adumesny** [comment]
string (selector) should work - that means `GridStack.getElement(selector)` didn't return your div. will have to take a look...

**Comment by adumesny** [comment]
`grid.el.appendChild('<div id="gsi-1" gs-x="0" gs-y="0" gs-w="3" gs-h="2" gs-auto-position="true"></div>')` doesn't work, that is YOUR issue, not the lib...

**Comment by spuyet** [comment]
@adumesny I don't understand why this is issue has been closed.

There is clearly an issue in the documentation and @abulka took time to explain that's documentation is wrong: https://github.com/gridstack/gridstack.js/tree/master/doc#makewidgetel

Code from the doc:
```js
let grid = GridStack.init();
grid.el.appendChild('<div id="gsi-1" gs-x="0" gs-y="0" gs-w="3" gs-h="2" gs-auto-position="true"></div>')
grid.makeWidget('#gsi-1');
```
is just not working with the error reported:
```
Uncaught TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
```

**Comment by adumesny** [comment]
oops, I missread that it was a doc issue.
