### ISSUE TITLE
how to stop grid items from resize when the container resize

### ISSUE THREAD

**Issue by candrewtemenoscom** [gridstack/gridstack.js#1834]
## Subject of the issue
Describe your issue here.
I would like to stop the grid items within the grid from resizing when the container resizes. I use setStatic(true) but it just stops the item from resizing by dragging but not the container resizes.

## Your environment
* version of gridstack.js = 4.2.6
* 
* browser/OS = chrome 92.0.4515.131 on windows 10

## Steps to reproduce
You **MUST** provide a working demo (keep it simple!) you can use 
https://jsfiddle.net/adumesny/jqhkry7g

## Expected behavior
The size of grid items stay the same

## Actual behavior
The size of grid items change when the container of the grid changes

**Comment by adumesny** [comment]
it is not possible as the grid items are % based by design - you would need to prevent the parent div (grid itself) from resizing (done in CSS).
