### ISSUE TITLE
Layout incorrectly restored when node has a minimum width and layout changes from 12 -> 1 -> 12

### ISSUE THREAD

**Issue by hssm** [gridstack/gridstack.js#1835]
Nodes with a minimum width that is larger than the transitioning column count (e.g: minW=2 when moving to 1-column mode) do not survive a layout change when the column count is restored.

I'll have a pull request with a fix shortly :)

[Reproducible example](http://jsfiddle.net/L08bq76e/2)

## Steps to reproduce

1 - Start with a large window so the grid begins in 12-column mode
2 - Reduce the window size until it resizes into 1-column mode
3 - Expand the window to return to 12-column mode

## Expected behavior
The original 12-column layout is restored.

## Actual behavior
The widgets appear to be stuck in the 1-column placement with the wrong width.

## Your environment
I've observed the issue on version 4.2.6 and 4.0.2.

**Comment by adumesny** [comment]
fix in next release!
