### ISSUE TITLE
don't move other items permanently while an item is being dragged

### ISSUE THREAD

**Issue by jedwards1211** [gridstack/gridstack.js#1837]
## Subject of the issue

Gridstack's worked out pretty well for me!  But I have one chief problem.

Gridstack permanently changes the layout during dragging, which causes contrary outcomes.
In the below example, let's say the user has just placed items 1, 2, and 3, and wants to place a new item to the right of them.  But they inadvertently drag the new item across 1, 2 and 3, which moves them away from where they had just placed them (in my app, this is happening constantly because the new item element is to the left of the dashboard):

![drag across](https://user-images.githubusercontent.com/1448194/130728081-8e0ca607-b835-4523-984f-098603f4c04f.gif)

Now the user has to tediously put items 1, 2, and 3 back in their original position.

Since none of the existing items needed to move out of the way of where the new item was finally dropped, the end result should have been the same as if the user happened to drag the new item around the existing ones:

![drag around](https://user-images.githubusercontent.com/1448194/130728211-2017a08f-64fa-4989-82e0-4322d2453b38.gif)

Gridstack could easily avoid this by remembering the layout at the time the drag operation was started, and always computing the next layout based upon that drag start time layout and the drag hover location.  That way, all items that don't need to be moved to accommodate the hovered drop location would retain their starting position.  I'm confident this would be a much more user-friendly behavior.

A competing library, [Packery](https://packery.metafizzy.co/), seems to behave the way I'm proposing.  If I had known about this at the time I might have chosen it, though it's kind of expensive.

At the very least, I wish it were an option, in case some people for some reason think the current behavior is more expected.

Maybe the existing behavior is more convenient for moving an existing item around in the grid, but I doubt it.

Is there any workaround way I can accomplish this?
I may eventually fork to see if I can solve this for my app, so let me know if you'd be open to a PR.

## Your environment
* gridstack version - 4.2.6 + HTML5
* browser/OS - probably irrelevant, but Chrome 92.0.4515.159, macOS 11.5.1

## Steps to reproduce
https://jsfiddle.net/mr5y2c9d/3/

1. Grab the "Drag me into the dashboard" item
2. Move it over item 1
3. Move it over item 2
4. Move it over item 3
5. Drop it to the right of there item 3 was before you grabbed it

## Expected behavior
1, 2, and 3 should move out of the way while the grabbed item is hovering over them, but move back into their original place once the grabbed item is no longer in their way (as long as they don't need to move for anything else the grabbed item is directly in the way of)

For example, what I'd expect to see during the repro steps is:

![Screen Shot 2021-08-25 at 12 01 21 AM](https://user-images.githubusercontent.com/1448194/130729557-9d8b8e07-35bd-49dd-84fc-7647644752c0.png)

![Screen Shot 2021-08-24 at 11 51 12 PM](https://user-images.githubusercontent.com/1448194/130728618-37ebe5b4-ea80-4225-a7e9-b1c3cae0d9d4.png)

![Screen Shot 2021-08-25 at 12 01 39 AM](https://user-images.githubusercontent.com/1448194/130729563-eb122248-5827-40ba-91ae-8f5ee300f092.png)

![Screen Shot 2021-08-25 at 12 01 59 AM](https://user-images.githubusercontent.com/1448194/130729572-2cb152de-4c36-4371-a52d-5a46990bbff7.png)

## Actual behavior
1, 2, and 3 get moved permanently while grabbed item passes over them, and never move back to their original positions, looking like this:

![image](https://user-images.githubusercontent.com/1448194/130729645-b24d2aab-0fec-4f80-bd9a-3dcff09bc6bd.png)

**Comment by adumesny** [comment]
I agree, using the starting layout and resetting it each time we collide would be better - ironically we already save the starting layout. But don't think it's 'easy' as you mention as you still want to optimize and not hit the same node 1 (in your very first example) on every pixel move and re-do the same full layout....

Funny you think packery at $25/dev is expensive... if you only knew the amount of time I spend on this lib (also thinking on making it commercial as very few people donate).

**Comment by jedwards1211** [comment]
I know it's not expensive in the grand scheme of things, it's just that the company I work for is small and doesn't have much budget, and unfortunately one gets used to having tons of free libraries available.

It seems like we would only need to recompute the layout when the "snapped" drop location or resize dimension changes, not on every pixel move, which in my example would just be one recomputation for each step pictured.

**Comment by adumesny** [comment]
yep, it's all do-able. just time and money. If you want to take a stab at it that would be great. If you need me to do this, be prepare to donate to cover the time...

**Comment by adumesny** [comment]
fixe in later builds
[recording-2022-09-17-17-50-23.webm](https://user-images.githubusercontent.com/3496166/190880974-c667aa38-1d21-4d87-8d75-0fcbe0f22efe.webm)

**Comment by jedwards1211** [comment]
@adumesny the particular case in my OP is fixed but I'm afraid the problem persists; we've still had users complain that their layout gets messed up when they try to drag a new widget in, because the widgets they dragged across get moved:

https://github.com/gridstack/gridstack.js/assets/1448194/a7801f63-4929-47ba-b119-7ebd31bf3937

I can only see one way to get layout behavior that users are happy with: the layout needs to be a pure function of the layout before dragging plus the (pending) drop location.

```

   Layout before drag                     Drop location                        Updated layout

  +------------------------+             +------------------------+           +------------------------+ 
  |                        |             |                        |           |                        | 
  | AAAAAAA                |             |                        |           | AAAAAAA                | 
  | AAAAAAA                |             |                        |           | AAAAAAA                | 
  | AAAAAAA                |             |                        |           | AAAAAAA                | 
  |                        |      +      |                        |     =     |                        | 
  | BBB CCC                |             |     DDD                |           | BBB DDD                | 
  | BBB CCC                |             |     DDD                |           | BBB DDD                | 
  |                        |             |                        |           |                        | 
  |                        |             |                        |           |     CCC                | 
  |                        |             |                        |           |     CCC                | 
  +------------------------+             +------------------------+           +------------------------+ 


   If the user moves D off of C before dropping, then the layout should recompute like this,
   so that it preserves C's original location.

   Layout before drag                     Drop location                        Updated layout

  +------------------------+             +------------------------+           +------------------------+ 
  |                        |             |                        |           |                        | 
  | AAAAAAA                |             |            DDD         |           | AAAAAAA    DDD         | 
  | AAAAAAA                |             |            DDD         |           | AAAAAAA    DDD         | 
  | AAAAAAA                |             |                        |           | AAAAAAA                | 
  |                        |      +      |                        |     =     |                        | 
  | BBB CCC                |             |                        |           | BBB CCC                | 
  | BBB CCC                |             |                        |           | BBB CCC                | 
  |                        |             |                        |           |                        | 
  |                        |             |                        |           |                        | 
  |                        |             |                        |           |                        | 
  +------------------------+             +------------------------+           +------------------------+ 

```

I'll probably solve this issue in our fork by cloning the layout before drag started into a new GridStackEngine on each drag event.  I think the engine is too stateful, and pure functional layout calculations would provide a better UX.  If nothing else it should probably `restoreInitial` and solve collisions on each drag event.

**Comment by adumesny** [comment]
honestly you haven't made any donations even thouhg I apparently fixed the intial problem, so I'm not going to be looking at this, even though it makes sense... my time isn't free, and too busy.
