### ISSUE TITLE
Update() on resizeHandles of item is not working

### ISSUE THREAD

**Issue by matheusbenedet** [gridstack/gridstack.js#1842]
## Subject of the issue
resizeHandles of item is not working

## Your environment
 "gridstack": "^4.2.6",
 "jquery": "^3.5.1",
Firefox: 91.0.2

## Steps to reproduce
`grid.on('dropped', function(event, previousWidget, newWidget) {
    setTimeout(function () {
        grid.update(newWidget.el, {resizeHandles: "e,w"});
    }, 200);
    
});`
## Expected behavior
If i put another item option works, but resizeHandles not work.

## Actual behavior
the resizes continues the default.

**Comment by adumesny** [comment]
not really surprise that attributes isn't handled...

**Comment by matheusbenedet** [comment]
> 
> 
> not really surprise that attributes isn't handled... is that only on dropped (possibly another element than originally dragged ? just want to point since you didn't post a running sample!

Here is a sample: https://jsfiddle.net/wy4vm6pd/3/

**Comment by adumesny** [comment]
most attributes can be set on the .newWidget ahead of time and will be re-used during drag+drop, though resize handles is a GRID option, not a per item option so this isn't a valid bug... closing.

**Comment by matheusbenedet** [comment]
> though resize handles is a GRID option, not a per item option so this isn't a valid bug... closing.

"though resize handles is a GRID option, not a per item option so this isn't a valid bug... closing."

See docs:

![image](https://user-images.githubusercontent.com/55722495/133910598-c5fc6991-d849-4227-9a5a-66324aa1c1a9.png)

**Comment by adumesny** [comment]
I never knew items could have their own resize handles... will have to add or update doc.

**Comment by adumesny** [comment]
so the doc is there, and code to read/write those fields is there, but there is no code (nor do I recall running into it) to set a per widget resize handler differently from the grid option. Only a widget can be resizable or not (no handles). 
Will remove this never implemented feature out...
