### ISSUE TITLE
How to use Save() and retrive the saved grid json in Angular

### ISSUE THREAD

**Issue by ArunRK-Finsurge** [gridstack/gridstack.js#1843]
Hey, 

I using Angular11, I am using gridstack js but how can we save the gridstack in session or local storage? need to change the local storage value while drag&drop and resize the panel.  I used ngmodelChange to save but couldn't change in localstorage

**Comment by adumesny** [comment]
questions are for slack. closing

**Comment by ArunRK-Finsurge** [comment]
@adumesny  I have posted a question in slack but not yet got reply
