### ISSUE TITLE
able one column problem

### ISSUE THREAD

**Issue by lingling-ding** [gridstack/gridstack.js#1844]
## Subject of the issue
when window.width < 768px, the column changed to 1, so the `gs-w` resized to 1, which is great, but the height of the grid item did not change, so the content inside was twisty, is there any way to also resize the `gs-h` to 1 ?

## Steps to reproduce
You **MUST** provide a working demo (keep it simple!) you can use 
https://jsfiddle.net/adumesny/jqhkry7g

**Comment by adumesny** [comment]
we do not currently have a mode to also resize the gs-h attributes, only options on `cellHeight:auto,initial,70px`, settings. is that not enough ?

**Comment by adumesny** [comment]
closing due to non response.
