### ISSUE TITLE
How to detect drop on grid children?

### ISSUE THREAD

**Issue by Albert-Gao** [gridstack/gridstack.js#1852]
I want to drag and drop elements to the already-added-grid-children, anyway to detect it? I am using React.

I tried added the `onDrop` on the rendered already-added-grid-children, but it never triggers, I think the control has been taken over by the `import 'gridstack/dist/h5/gridstack-dd-native'`. Anyway I can check dropping on a grid children?

Thanks

**Comment by adumesny** [comment]
use slack for questions.
