### ISSUE TITLE
Grid item diagonal expansions have different "bottom" values

### ISSUE THREAD

**Issue by GeneralPeaceful** [gridstack/gridstack.js#1853]
Pretty simple, the `.grid-stack>.grid-stack-item>.ui-resizable-sw` class has `bottom: 0` whilst the `-se` variant has no constraint. Imo it is negatively eye-catching that the sw variant has a left margin but no bottom margin. Would it not make sense to have them the same?

## Existing code
```
> .ui-resizable-se { cursor: se-resize; width: 20px; height: 20px;}
...
> .ui-resizable-sw { cursor: sw-resize; width: 20px; height: 20px; bottom: 0; }
```
## Proposed
```
> .ui-resizable-se { cursor: se-resize; width: 20px; height: 20px;}
...
> .ui-resizable-sw { cursor: sw-resize; width: 20px; height: 20px;}
```
The code is [here](https://github.com/gridstack/gridstack.js/blob/1cb5715f9ca2a737ae9e09087be32d0827d2ad24/src/gridstack.scss#L90)

Example: 
![image](https://user-images.githubusercontent.com/40724586/133451311-dbe17c47-e177-492e-84fa-de934340f48a.png)

**Comment by adumesny** [comment]
with absolute positioning, don't you need to set top or bottom for them to be located correctly ?
not sure why se and sw are different, but maybe se happens to flow after the shape... anyway you are welcome to try and make those changes and post a review - just make sure to test different browsers and content.

**Comment by GeneralPeaceful** [comment]
> with absolute positioning, don't you need to set top or bottom for them to be located correctly ?
> not sure why se and sw are different, but maybe se happens to flow after the shape... anyway you are welcome to try and make those changes and post a review - just make sure to test different browsers and content.

There is another css class referencing these that specifies `bottom: 4px;` so I'm not sure why sw has been specified to be different - as you say.

**Comment by adumesny** [comment]
thanks!
