### ISSUE TITLE
The 1st of grid size(gs-w/gs-h) issue

### ISSUE THREAD

**Issue by uiueux** [gridstack/gridstack.js#1856]
## Subject of the issue
For a normal webpage with existing HTML DOMs, the 1st grid always be rendered as gs-w=1 gs-h=1
it ignores the gs-w/gs-h attribute on the item DOM, please check the below codepen demo

## Your environment
* I don't know the version, I link the js address from the demo website https://gridstackjs.com/node_modules/gridstack/dist/gridstack-h5.js
* which chorome 93.0.4577.82 /macos 10.15.7

## Steps to reproduce
https://codepen.io/uiueux/pen/NWgYVPz

## Expected behavior
```
<div class="container">
  <div class="grid-stack">
  <div class="grid-stack-item">
    <div class="grid-stack-item-content" gs-x="0" gs-y="0" gs-w="2" gs-h="2" >Item 1</div>
  </div>
  <div class="grid-stack-item" gs-w="4" gs-h="2" gs-x="2" gs-y="0">
    <div class="grid-stack-item-content">Item 2 </div>
  </div>
  <div class="grid-stack-item"  gs-w="3" gs-h="3" gs-x="6" gs-y="0">
    <div class="grid-stack-item-content">Item 3 </div>
  </div>
</div>
</div>
```
Thanks for the great plugin. I made a simple webpage.
The item1 is rendered as with gs-w="1" gs-h="1" always, it ignores the gs-w/gs-h attribute on the item DOM itself. It only happens on the 1st grid, other items work fine. Please check the video: https://www.dropbox.com/s/01ys45t9jp9loj6/QQ20210920-124103-HD.mp4?dl=0
I don't know if it is a bug, or I didn't use it correctly, any suggestions are greatly appreciated!

Thanks

**Comment by adumesny** [comment]
not a bug - you have the sizing on grid-stack-item-content instead of grid-stack-item on first item!
