### ISSUE TITLE
Nuxt ssr problem

### ISSUE THREAD

**Issue by rakibhoossain** [gridstack/gridstack.js#1857]
## NUXT ssr rendering issue
* The highlighted code makes problem on my nuxt ssr app. Please fix it!

**Comment by adumesny** [comment]
deleting due to suspicious malware link...

**Comment by timegawhat** [comment]
I have the same problem

**Comment by adumesny** [comment]
file a proper bug please.

**Comment by kchjxxgh** [comment]
I have the same problem...
