### ISSUE TITLE
'gridstack' custom DOM property intermittently  unavailable

### ISSUE THREAD

**Issue by rafalsk** [gridstack/gridstack.js#1861]
We're facing an issue with unavailability of the what seems to be a custom 'gridstack' property when accessing nested grids.

To reproduce it we've forked the nested.html example.

Interestingly clicking the "Add Widget Grid1" button when accessing the page from your server works but not with the recent version (?).

In our copy, attached to recent H5 version and min.css the gridstack property is not available i.e. it is undefined.
![image](https://user-images.githubusercontent.com/9338163/135750112-6c6abd35-c1eb-43d0-8b4b-f1eef736611b.png)

it is all fine however when accessing the second or even third container which we've added (through the "Add Widget Grid2" button)

We can't seem to be find and discrepancies between how stack 1 and 2 or 3 are defined.

Reproducible example attached (it's basically nested.html example with changed source files for css and js and one additional grid added). 

Also, out of topic but, how would one approach attaching events to nested grids? 
[nestedDemo.zip](https://github.com/gridstack/gridstack.js/files/7273162/nestedDemo.zip)

We've tried iterating over the engine->nodes[] (of the main gridstack object, supposedly containing all the child grids) and then accessing corresponding 'grid' object by registering for their on() methods (available, verified) i.e. just like we would be signing-up for events from the main GRID, but no events are fired. In other words, we need to be notified when for instance items in a nested grid are re-arranged. Events for the main grid work just fine.

**Update:** in our case, after retrieving sub-grids after their attributes (hey.. finding elements by their class feels sort of strange, thus we look-up by the id, i.e. the gs-id attribute), the 'gridstack' custom parameter turns out not to be set for to the sub-grids' divs (yes of class 'grid-stack', one representing the sub-grid verified that, it's also sort of strange that the library assigns the  gs-id attribute to a DIV one level higher in the hierarchy..). So we went forward trying to add elements to sub-grids by traversing the internal objects of the main grid in hopes of using the API calls of these. Turn out the engine->nodes[i]->grid is just a REFERENCE to the main grid which explains why events were not being fired as we were simply re-adding events for the main grid.......

so the question is - how to access the sub-grids' objects and how to access their API for whatever purpose. The example uses custom DOM parameter but in our case it seems to be very unreliable (check the reproducible example).  Are there truly these objects somewhere under the hood or is it just the main-grid taking care of everything and only view-representations of sub-grids....
  

Now now the most reliable way we could come up with for retrieving sub-grids is below (by the id param), still curious why the reproducible example above above doesn't work.
`  getGroupByID(id) {

    if (!id || this.mGrid == null)
      return null;

    let group = document.querySelectorAll('[gs-id="' + id + '"]');
    if (!group)
      return null;

    let gsContainer = $(group).find('.grid-stack'); //group.getElementsByClassName('grid-stack');

    if (gsContainer.length==0)
    return;

    gsContainer = gsContainer[0];

    let gridstack = gsContainer.gridstack;
    return gridstack;

    return null;
  }`

**Comment by adumesny** [comment]
one bug at a time please - file the other separately if needed.. nested.html works for me just fine locally (latest + incoming fixes) clicking "add Widget 1" Not sure how to repro your case since you did not provide a broken example. closing.

![image](https://user-images.githubusercontent.com/3496166/135780146-e6ce0c7b-74d6-458f-bbf9-5109a09b9823.png)
