### ISSUE TITLE
'click' events not propagating to DOM objects within content

### ISSUE THREAD

**Issue by rafalsk** [gridstack/gridstack.js#1862]
OK, we've tried a couple of approaches and we can't seem to be able to get simple mouse events to work for DOM objects within the content fields to work. Probably something is capturing those events above in hierarchy and not letting these to bubble down the hierarchy, could anyone confirm?

**Comment by adumesny** [comment]
this isn't a proper bug report. Please re-open with running example showing issue or ask the slack channel.
