### ISSUE TITLE
Subgrid not being initialized when dragging HTML

### ISSUE THREAD

**Issue by RdeWilde** [gridstack/gridstack.js#1866]
## Subject of the issue
Subgrid is not being initialized when dragging HTML elements.

## Your environment
HTML5
v4.2.3
Any browser

## Steps to reproduce
When I drag the HTML onto the grid, the subgrid is not being initialized. You can try dragging this HTML onto a grid:
```
<div class="layout-sidebar">
<div class="grid-stack-item ui-draggable" draggable="true" gs-x="2" gs-y="1" gs-w="4" gs-h="1"> 50-50
	<div class="grid-stack-item-content">
		<div class="grid-stack grid-stack-nested row">
			<div class="grid-stack-item col-6 ui-draggable" gs-w="6" draggable="true">
				<div class="grid-stack-item-content"> 6</div>
			</div>
			<div class="grid-stack-item col-6 ui-draggable" gs-w="6" draggable="true">
				<div class="grid-stack-item-content"> 6</div>
			</div>
		</div>
	</div>
</div>
</div>
```

Drag-in options are like this:
```
		GridStack.setupDragIn( // FIXME zou via dragInOptions moeten werken
			'.layout-sidebar .grid-stack-item', {
				revert: 'invalid',
				scroll: false,
				appendTo: 'body',
				handle: '.grid-stack-item',
				helper: (event) => {
					var $target = $(event.target);
					var $el = $target.clone(true, false);
					$el.data($target.data());
					return $el[0];
				}
			}
		);
```

## Expected behavior
Expecting the div with grid-stack(-nested) to be initialized as a subgrid.

## Actual behavior
Subgrid isn't being initialized from what I can see. No instance-id for example

**Comment by adumesny** [comment]
closing due to no sample. also I don't think it's right for the lib to parse the content on your element and somehow detect that you have a nested grid automatically. you should be able to call addGrid() or init() after the drop event to let it know...
