### ISSUE TITLE
Unexpected behavior when resizing equal elements not fitting in the grid

### ISSUE THREAD

**Issue by Voodu** [gridstack/gridstack.js#1868]
## Subject of the issue
When resizing element A with width equal to element B and dragging it over B, gridstack tries somehow to fit everything in a container which is already full and shifts elements in a strange way. Also, when 'reverting' the change and going back to the previous size, the elements aren't placed in the same way they were (although that's probably related to https://github.com/gridstack/gridstack.js/issues/1837)

https://user-images.githubusercontent.com/24680898/137323247-fb6c2dbf-104b-462b-a1ea-7aa3a3bfa9e6.mp4

## Your environment
* version of gridstack.js : 4.2.7
* which browser/OS: Chrome, Ubuntu 20.04

## Steps to reproduce
Any grid with two elements with the same width and gridstack with fixed row number.
Place one element exactly above another and try to resize the upper of them as much as possible.
https://jsfiddle.net/hbdka6ge

## Expected behavior
Either of the two:
1) Don't allow resizing over other items. So for this one https://jsfiddle.net/hbdka6ge/1/ if user wants to make upper div 3 rows large, they have to move manually the lower one first
2) Allow resizing over other items only if they can be moved. Again, for this one https://jsfiddle.net/hbdka6ge/1/ when resizing upper it can be made taller up to 3 rows and the lower one will shift correctly, but after that it shouldn't allow to make it bigger at all.

## Actual behavior
Upper item can be resized to any size and when it's made too big it starts shifting with the lower one.

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful!
