### ISSUE TITLE
How to change content of item on dropped?

### ISSUE THREAD

**Issue by webb24h** [gridstack/gridstack.js#1876]
Take this item
```
<div class="newWidget grid-stack-item">
<div class="grid-stack-item-content" style="padding: 5px;">
<div>
<ion-icon name="add-circle" style="font-size: 300%"></ion-icon>
</div>
<div>
<span>Drag me in the dashboard!</span>
</div>
</div>
</div>
```
example from advanced demo [here](https://gridstackjs.com/demo/web2.html)

Let's say I want to remove the content (icon, span and text ) from the block when dropped inside the grid. How does one achieve this? The idea would be to display something different than the dropped item inside the grid.

**Comment by webb24h** [comment]
I'm new to gridstack. I found my answer in the [two grids](https://gridstackjs.com/demo/two.html#) [example](view-source:https://gridstackjs.com/demo/two.html) in the docs. 

My understanding write your own function in the initialization
```
//initialize grid stack
var grid = GridStack.init({
minRow: 1, // don't collapse when empty
cellHeight: 70,
acceptWidgets: true,// acceptWidgets - accept widgets dragged from other grids or from outside (default: false).
dragIn: '.newWidget',  // class that can be dragged from outside
dragInOptions: { revert: 'invalid', scroll: false, appendTo: 'body', helper: makeWidget }, // clone or can be your function
removable: '#element-trash', // drag-out delete class
});
```

Then your function will check and create content based on needs

```
 function makeWidget(e){
  console.log(e.target);
  console.log(e.target.className); 
  console.log(e.type); 
  console.log(e.offsetY); 
  console.log(e.ctrlKey); 
    
if(e.target.className == 'whatever'){

//create widget here
grid.makeWidget();

}
    
}
```

**Comment by adumesny** [comment]
use the slack channel for questions.
