### ISSUE TITLE
Nested grid demo with draggable DIV

### ISSUE THREAD

**Issue by patsuhiko** [gridstack/gridstack.js#1882]
Hi,
i took the example from nested.html and wanted to drag-in existing div into two or more grids instead of clicking on a button. All files are loaded yesterday from github, including the demos using Firefox 93.

The drag-in of the DIV as a nesting element of the grid is of course working, but it happens at some point that the console is reporting an error, if i hover with pressed mouse and the DIV-element over the grids:
**Uncaugt TypeError: s is undefined**

> Uncaught TypeError: s is undefined
>     _setupAcceptWidget gridstack-dd.ts:219
>     on gridstack-dd-native.ts:118
>     triggerEvent dd-base-impl.ts:40
>     _dragLeave dd-droppable.ts:123
>     _dragEnter dd-droppable.ts:96
>     n dd-droppable.ts:38
>     setupDroppable dd-element.ts:89
>     droppable gridstack-dd-native.ts:93
>     droppable gridstack-dd-native.ts:83
>     _setupAcceptWidget gridstack-dd.ts:127
>     h gridstack.ts:366
>     init gridstack.ts:124
>     addGrid gridstack.ts:174
>     addWidget gridstack.ts:438
>     load gridstack.ts:550
>     load gridstack.ts:535
>     addGrid gridstack.ts:178
>     <anonymous> nested.html:69

After that, the grid where the error was reported is somehow "broken".
The best to reproduce this is to place 3-4 divs with the lightblue background and "Hello World DIV" text in it into each grid and then take the div element and hover with the element between the two grids:

https://jsfiddle.net/9wj13s7g/

Did i understand something wrong with the dragging?
Thank you for your help!

**Comment by adumesny** [comment]
sorry I missed this post. I'm not able to see the error in your given demo. can you post a video how to reproduce ?
Also might try the latest (5.1 as of this writing).
