### ISSUE TITLE
Update skips changes in height even tho a change has been made

### ISSUE THREAD

**Issue by radovanobal** [gridstack/gridstack.js#1884]
In this bit of code w has it's parameters removed and copied over to m, but in the process it sometimes looses the width (maybe others as well) parameter and it results in some items not having their width* updated.

Shouldn't line 1018 loop trough m?

https://github.com/gridstack/gridstack.js/blob/16feded0719d73b64d77123118e7c70af482e778/src/gridstack.ts#L994-L1018

**Comment by adumesny** [comment]
no, line 1025 handles the move later..
```js
      // finally move the widget
      if (m) {
```
if you find an issue post a reproduceable example.
