### ISSUE TITLE
Resizing above "locked" items

### ISSUE THREAD

**Issue by otamiotto** [gridstack/gridstack.js#1885]
Hello! First of all, thanks for this awesome library.

I'm trying to use it for project where I have a resizable full viewport grid. My only issue is that I would like to have the elements locked in their positions, no matter how you resize the other elements of the grid.

* using gridstack@4.3.1, html5 and Jquery 3.5.1 / Windows / Chrome

Here's the default issue demo with the items set as "locked". In my project I'm also using the % cellHeight and maxRow options:
https://jsfiddle.net/ten387sw/

## Expected behavior
When resizing over another item, it should snap to the usual grid position, above the other item, which wouldn't move, staying hidden bellow the resized block.
![image](https://user-images.githubusercontent.com/24676954/142935238-585b0c80-6869-48f2-a59f-80149ca97cd3.png)

## Actual behavior
The resized item is pushed to the row bellow.
![image](https://user-images.githubusercontent.com/24676954/142936788-b0e50c14-e199-4646-b879-402043b36184.png)

**Comment by adumesny** [comment]
'locked' items means they will not get moved by others, but since you are resizing 0 (doesn't have noSize) then it has to move down to be the size you are asking for. Not a bug, as designed.

**Comment by otamiotto** [comment]
I understand it's not a bug, just wanna know if it would be possible to include it as a new feature.

**Comment by adumesny** [comment]
"elements locked in their positions" so do you mean `noMove` on element 0 while trying to resize it ? that doesn't currently work though it could. that means you could ONLY resize elements and never move any of them (manually or by another trying to push it out as it resizes).

Is that what you want ?
yeah new features can always be added if you are willing to donate for them...
