### ISSUE TITLE
Gridstack update function is not working properly

### ISSUE THREAD

**Issue by ratan-tirkey-dreamorbit** [gridstack/gridstack.js#1886]
In my coding
grid.update('widgetNameLsp', {x: '0', w:' 6'})

it's not updating as per console.
gridstackNode:
el: div#widgetNameLsp.grid-stack-item.ui-draggable.ui-resizable
grid: h {_gsEventHandler: {…}, _extraDragRow: 0, el: div.grid-stack.grid-stack-instance-4299.grid-stack-animate, opts: {…}, _isAutoCellHeight: false, …}
h: 4
maxH: 4
maxW: 12
minH: 4
minW: 6
w: 12
x: 0
y: 0
_id: 5

and if we update like this grid.update('widgetNameLsp', {x: '0', width: 12})
in console it will show update like this

gridstackNode:
el: div#widgetNameLsp.grid-stack-item.ui-draggable.ui-resizable
grid: h {_gsEventHandler: {…}, _extraDragRow: 0, el: div.grid-stack.grid-stack-instance-2678.grid-stack-animate, opts: {…}, _isAutoCellHeight: false, …}
h: 4
maxH: 4
maxW: 12
minH: 4
minW: 6
w: 6
width: "12"
x: 0
y: 0
_id: 2
_initDD: true

I want to update x value.

**Comment by ratan-tirkey-dreamorbit** [comment]
I think I got the answer.
the value should be integer to update ;)
here is the link the way it works https://jsfiddle.net/Neo_1997/o0gwxh7L/83/

**Comment by adumesny** [comment]
Not a bug - GridStackPosition clearly states those are integers.
