### ISSUE TITLE
Browser tab locks up with nested widgets when 'column' is set to 1

### ISSUE THREAD

**Issue by masterchiefaragorn** [gridstack/gridstack.js#1888]
## Subject of the issue
I built a single parent widget (with the 'column' option set to '1'), with two child widgets nested inside it.  When I resize the parent, the browser tab locks up.  However, if I set 'column' to 2 or more, GridStack works.

## Your environment
Version: 4.3.1
Browser: Brave (Chromium)
Kind: Occurs in both the HTML5 and Jquery versions

## Steps to reproduce
1) Go to https://jsfiddle.net/98o6pcqw/
2) Grab the gray (parent) widget and resize it larger than it currently is.

## Expected behavior
The parent widget should simply resize.

## Actual behavior
The browsers tab locks up.

**Comment by adumesny** [comment]
thanks for reporting this.

**Comment by jledentu** [comment]
Hi,

I updated the fiddle in order to use the 5.0.0 version. The bug seems to have been fixed.

https://jsfiddle.net/oj80r14p/

**Comment by adumesny** [comment]
Great. Don't forget to donate if you find this lib useful!

**Comment by adumesny** [comment]
as mentioned it is fixed in the current v5.0.0 release (I just tried both), so what is the issue ? still didn't get that promised donation...

**Comment by masterchiefaragorn** [comment]
Sorry for mis-communicating.  A development slot opened up for us to try to use gridstack again, so we're currently playing with it to see if it will work in our use-case.  Yes, this bug particular is fixed...we're just waiting to see if we'll encounter any more issues as we dive deeper into embedding it.  We'll be happy to donate if we can get gridstack fully working in our use-case.
