### ISSUE TITLE
Button click event issue inside a widget

### ISSUE THREAD

**Issue by basimw** [gridstack/gridstack.js#1889]
## Subject of the issue
I am implementing Gridstack on Angular framework. 
I am able to add widgets dynamically and now I want to add a button inside every widget. Able to add a button but I am not able to get the button click event control in my TS file.

` addWidget() {
    var grid = GridStack.init(this.options);
    grid.addWidget('<div class="grid-stack-item" ><div class="grid-stack-item-content"><button class="btn btn-outline-primary" (click) = "selectKPI()">Add KPI</button></div></div>', { w: 3 })
  }

  selectKPI() {
    console.log("success");
  }`

![image](https://user-images.githubusercontent.com/62746316/143763504-89a479db-7ba6-44ad-94b8-0b62abd2a8dd.png)

Any help would be appreciated.

**Comment by adumesny** [comment]
please use slack channel for questions... this is for lib bugs only. 
my guess is that Angular parser need to be run on the string/generated DOM and not sure how to do that.
