### ISSUE TITLE
Grid drag & drop stops working after quickly dragging an item back and forth between grids.

### ISSUE THREAD

**Issue by bcbuddy** [gridstack/gridstack.js#1890]
## Subject of the issue
An unhandled exception occurs within Gridstack that breaks all drag & drop features within a grid when dragging an item back and forth between them.

## Your environment
-Gridstack v4.3.1, using Html5 lib.
-Using Chrome

## Steps to reproduce
Use the 2 grid demo: https://gridstackjs.com/demo/two.html

Start **quickly** dragging a grid item back and forth between 2 grids(without dropping the item). You'll notice that one of the grids stop working after 3 or 4 times dragging between grids. It could take a few more times depending on your speed.

## Expected behavior
All drag & drop events should occur without any issues while dragging an item between 2 grids

## Actual behavior
Eventually an unhandled exception occurs in Gridstack. After this error occurs, the grid stops working for all drag & drop effects.
![image](https://user-images.githubusercontent.com/17886202/144242631-f9e993b8-4f2d-4f80-a57a-2268f1bf703a.png)

**Comment by adumesny** [comment]
thanks, I can see that error...
