### ISSUE TITLE
Question: How to drag item above each other while using float: false?

### ISSUE THREAD

**Issue by mitow7821** [gridstack/gridstack.js#1891]
## Steps to reproduce
https://gridstackjs.com/demo/float.html#
Try to place box 0 above box 2
Click on float button and try the same thing

![image](https://user-images.githubusercontent.com/34492112/144825470-60144a81-8453-40e1-81a3-92ea2e015885.png)

## Expected behavior
I need that float false gravity behaviour (to pull x axis to top) and float:true ability to place items above each other.
How could I do so? 

## Your environment
    "gridstack": "^4.3.1", using HTML 5
chrome 96.0.4664.45

**Comment by adumesny** [comment]
you can't place items on top of each other by design. You could possibly create multiple grids that are slightly shifter from one another to stack items (multiple layers).

**Comment by mitow7821** [comment]
@adumesny I dont want to place them on top but ABOVE .
More precisely I need top gravity (from float:false) without left and right gravity

**Comment by adumesny** [comment]
oh I see... 0 above 2, then 1 below them all (drawing a picture would help). sounds like the old behavior we used to have - try v3.3.0 (v4 has new swap behavior) and let me know if that is what you are saying, and/or draw a picture...

can't please everyone... if you don't want the swap behavior, maybe that could be an option on the grid. You would need to donate to support that large feature...

**Comment by mitow7821** [comment]
Thats exactly behaviour which I am trying to achieve. 
Downgrade to 3.3 doesn't work as expected. 

If i place B above C it works as I wanted but while trying to do so with box A (which has same height as C) they swap places with each other.
![image](https://user-images.githubusercontent.com/34492112/145178558-ee05fefe-2986-44a9-954d-0acda3bd325f.png)

**Comment by mitow7821** [comment]
With v3.3 it works as I expected. Thanks ;)

**Comment by adumesny** [comment]
great, don't forget to contribute if you find this lib useful!

also let us know if you need this supported in v4+

**Comment by mitow7821** [comment]
Support for v4 would be awesome because of performance bost ;)

**Comment by adumesny** [comment]
this would have to be added as an optional flag (push vs swap) - keeping in mind that if the grid is full or has maxRow you might no longer be able to move items around - an issue users had. This will require a donation if you want it added...
