### ISSUE TITLE
How to update from 2.0.1 to 4.2.6

### ISSUE THREAD

**Issue by ricenoddle** [gridstack/gridstack.js#1892]
## How to update from 2.0.1 to 4.2.6
As my title described, I'm now updating gridstack from 2.0.1 to 4.2.6. And I found there are a lot of break changes that I cannot find from your changelog. So that's the reason why I'm here to ask for help.

## Some example of error
- GridStack.column(column: number, layout?: ColumnOptions): the following is how I used before
![image](https://user-images.githubusercontent.com/13479751/145343551-f1ba6250-2fb2-4eb6-91c4-2e806e5bbbb9.png)
- Some methods are removed like:
![image](https://user-images.githubusercontent.com/13479751/145343617-65d998d0-648b-4759-9367-0cd132fa4df7.png)
there are more examples like `maxWidth`, `maxHeight`, `minWidth`, `minHeight`.

*Since you guys are very familiar about the great gridstack, so if you have any suggestion please let me know. I'd be very appreaciated.*

**Comment by ricenoddle** [comment]
## UPDATE

For now what I have modified, there are only two main errors which are:
- The use of `$` sign, I have done this `import { $ } from 'gridstack/dist/jq/gridstack-dd-jqueryui'`, but there comes the error `Property 'draggable' does not exist on type 'JQuery<HTMLElement>'`
- Property 'dd' does not exist on type 'GridStack'. I'm still looking for how to fix it

**Comment by adumesny** [comment]
use the slack channel for question - see doc about migrating to 3 and 4

**Comment by ricenoddle** [comment]
> 

Sorry I cannot join slack channel from company network. 

BTW, I do have checked how to migrating to 3 and 4, but still cannot find out how to replace the GridStack.dd
