### ISSUE TITLE
GridStack - Make Widget- Dynamic component widget not working (Resizing and drag)

### ISSUE THREAD

**Issue by vijaymandave** [gridstack/gridstack.js#1903]
## Subject of the issue
I am using grid stack library in angular, I have 2 components which are injected dynamically using make widget  but  not resizing and dragging also not working properly.

## Your environment
Angular v12
GridStack v4.4.0
Browser: chrome and Firefox

## Steps to reproduce
Please find demo app link at ### https://stackblitz.com/edit/angular-gridstack-make-widget-example?file=src%2Fapp%2Fapp.component.ts

## Expected behavior
Inject component into widget dynamically which can be resizable and should not overlap on other widget.

## Actual behavior
Component can inject into widget but not resizing and overlapping on another widget.

**Comment by radovanobal** [comment]
it looks to me like you are missing quite a bit of critical css. For example you are missing the grid stack item sizes.

**Comment by adumesny** [comment]
@vijaymandave can you remove/reduce your app.component.scss as it may conflict with lib CSS, which you already include in
import 'gridstack/dist/gridstack.min.css';

Also I don't see where you size/position your widgets (you don't call addWidget() but make which should convert one, but not sure it will auto-place it next available spot (I think it does).

**Comment by vijaymandave** [comment]
Hello @adumesny,
I have removed scss related to gridstack in stackblitz  https://stackblitz.com/edit/angular-gridstack-make-widget-example?file=src%2Fapp%2Fapp.module.ts.
Still I am unable to resize widget as per expected, resizing widget but little extend.
Widgets start overlapping after widget resized little or attempt to resize.
How to set size(height, width) and position of widget using makeWidget?
How to set widget priority?

Please suggest.

**Comment by adumesny** [comment]
your DOM tree is messed up after adding the element but before calling `makeWidget()` which fails - you have a 'grid-stack' within a 'grid-stack'
![image](https://user-images.githubusercontent.com/3496166/154987653-e195ada3-f929-4c75-9b86-cd044bf348c2.png)

the immediate child of the outer grid should have grid-stack-item class (no element in between) as well.
