### ISSUE TITLE
main grid height issue, while adding subGrids

### ISSUE THREAD

**Issue by santoshofc** [gridstack/gridstack.js#1907]
## Subject of the issue

please check the below screen shot

![image](https://user-images.githubusercontent.com/94838747/147658923-6aff4a0d-ec52-42c6-b963-68d5993a12b1.png)

## Your environment
* version of gridstack.js AND if using HTML5 vs Jquery plugin (v3+) - DON'T SAY LATEST as that doesn't mean anything a month/year from now.
* which browser/OS

## Steps to reproduce
You **MUST** provide a working demo (keep it simple!) you can use 
https://jsfiddle.net/adumesny/jqhkry7g

## Expected behavior
Tell us what should happen

## Actual behavior
Tell us what happens instead

**Comment by adumesny** [comment]
file a proper bug if lib issue. else use slack channel for questions
