### ISSUE TITLE
makeWidget moves item by y-axis automatically

### ISSUE THREAD

**Issue by yohirusyo** [gridstack/gridstack.js#1914]
Hello, i'am using gridstack in my app.
I am facing the problem:
When I drag item from one grid to another I must register this item using makeWidget, but it immediately increments item y by 4 and in my app history registers moving event:
![moving](https://user-images.githubusercontent.com/97410077/148700529-7b7a090d-1f3f-4b37-90e3-782b38aeba6b.png)

**Comment by adumesny** [comment]
you must provide a reproduceable test case as I have no idea what your issue it. closing until you do so, then I can re-open.

**Comment by yohirusyo** [comment]
> you must provide a reproduceable test case as I have no idea what your issue it. closing until you do so, then I can re-open.

Hello, here is sample.
You have two pages, try to drag addition from sidebar to page, then drag this addition to start of second page.
https://codesandbox.io/s/romantic-christian-p27wt

**Comment by yohirusyo** [comment]
I think solution in gs-auto-position, but I do not understand how to use it properly.
And yes, I read https://github.com/gridstack/gridstack.js/tree/master/doc

**Comment by yohirusyo** [comment]
Fixed self. 
If someone has same problem with makeWidget, before this use grid.removeWidget instead native removing element from dom
