### ISSUE TITLE
Gridstack widget couldn't be hidden completely.

### ISSUE THREAD

**Issue by AnanduSuresh** [gridstack/gridstack.js#1922]
I have created a pie chart widget using chart.js and gridstack. Then I implemented a button to show or hide the chart inside the gridstack(arrow-up symbol on top right side). I was able to hide/show the chart according to the button click. But when hiding the chart, there is still some area visible inside gridstack component.

**image 1**
![Screenshot 2022-01-17 193756](https://user-images.githubusercontent.com/51982568/149785959-0960800c-0e38-43fd-b66b-4d2c6c0d9a56.png)

I set the height value to 0 when initializing the component data for the gridstack.
Example(not my original code)
`var items = [
    {w:10, h:0, content: 'my first widget'}
  ];
  var grid = GridStack.init();
  grid.load(items);`

But still the space is taken.

**image 2**
![Screenshot 2022-01-17 193832](https://user-images.githubusercontent.com/51982568/149786877-eedb0041-8611-4af2-b4d2-1640928a8c30.png)

Is the space taken by the resize-handler of the gridstack?
How to avoid the space shown in image 2.

**Comment by adumesny** [comment]
you should `removeWidget()` instead of hidding the chart as there is a minimum of 1x1 for grid items (0 is not a valid number)
