### ISSUE TITLE
please update MIT Expiry Date.

### ISSUE THREAD

**Issue by SmileLifeIven** [gridstack/gridstack.js#1926]
## Subject of the issue
please update MIT Expiry Date.

## Your environment
null

## Steps to reproduce
null

## Expected behavior
null

## Actual behavior
null

**Comment by adumesny** [comment]
I don't see an expire date. please be specific.

**Comment by SmileLifeIven** [comment]
“v4+ Copyright (c) 2021 Alain Dumesny
under MIT license”

Could I user gridstack.js in 2022? Or the license should update to 2022?

“v4+ Copyright (c) 2022 Alain Dumesny
under MIT license”

**Comment by adumesny** [comment]
you only update the copyright when you make changes to the code, which I should have done, but that doesn't prevent you from using 'old' copyrighted code.
