### ISSUE TITLE
Height of widgets is very large in tablet mode and drag-drop, resize not working in iPad

### ISSUE THREAD

**Issue by nutansinh** [gridstack/gridstack.js#1927]
## Subject of the issue
Height of each widget is becoming so large approximately 2400px for each widget in iPad.  Also drag-drop and resizable are not working on iPad even after adding jquery, jquery-ui and jquery.ui.touch-punch according to documentation.

## Your environment
* version of gridstack.js is 4.4.1 
* iPad, Responsive mode of chrome, firefox, safari (below 986px width)

## Steps to reproduce
Desktop mode:
![desktop](https://user-images.githubusercontent.com/87705781/151819240-b072d0bc-b509-488b-abe7-b2899caa17df.png)

IPad mode
![iPad](https://user-images.githubusercontent.com/87705781/151819252-f9200dc2-eb59-49c8-ae8e-702cf27f9ea4.png)

Below is my widgets config.
const widget1Config = {
    x: 0,
    y: 0,
    w: 12,
    h: 4,
    minW: 6,
    maxW: 12,
    minH: 4,
    maxH: 6,
  };
  const widget2Config = {
    x: 0,
    y: 6,
    w: 6,
    h:  3,
    minW: 6,
    maxW: 12,
    minH: 3,
    maxH: 6,
  };
  const widget3Config = {
    x: 6,
    y: 6,
    w: 6,
    h:  3,
    minW: 6,
    maxW: 12,
    minH: 3,
    maxH: 6,
  };

```
<div className="grid-stack"
<div class="grid-stack-item"  gs-w="1" gs-h="4" gs-x="0" gs-y="0" gs-min-w="6" gs-max-w="12" gs-min-h="4" gs-max-h="6" margin="20px"><div class="grid-stack-item-content" draggable="true">1</div></div>
<div class="grid-stack-item"  gs-w="1" gs-h="3" gs-x="0" gs-y="4" gs-min-w="6" gs-max-w="12" gs-min-h="3" gs-max-h="6" margin="20px"><div class="grid-stack-item-content" draggable="true">2</div></div>
<div class="grid-stack-item"  gs-w="1" gs-h="3" gs-x="0" gs-y="7" gs-min-w="6" gs-max-w="12" gs-min-h="3" gs-max-h="6" margin="20px"><div class="grid-stack-item-content" draggable="true">3</div></div>
</div>
```

I have used above html in react component.

## Expected behavior
All widgets should have height similar to desktop mode.

## Actual behavior
Height of widget is becoming large in iPad mode. Issue is also replicable in desktop responsive mode in dimension (768px X 1080px)

**Comment by adumesny** [comment]
look at `disableOneColumnMode` and/or `minWidth`. the jq version (with touch) should work on mobile, but I don't have an ipad to test on but others had no issues.
