### ISSUE TITLE
Window events while drag is active

### ISSUE THREAD

**Issue by ExKaiser** [gridstack/gridstack.js#1930]
I need to listen right click event after started item drag. Unfortunately, any event, that I tried to listen, is not emitted by window. Has anyone encountered this problem? Is there some way to do it correctly?

Using gridstack v5.0.0 with HTML5 in vue3 project

This is what I tried to do
```
grid.value.on('dragstart', (event, el) => {
  window.addEventListener('contextmenu', someFunc)
}

grid.value.on('dragend', (event, el) => {
  window.removeEventListener('contextmenu', someFunc)
}
```

`someFunc` is not executed, no matter what I do. Can't find any gridstack option to disable this behavior. Any solution for this?

**Comment by adumesny** [comment]
sounds like a question - please move to slack channel.
