### ISSUE TITLE
vue3.js example does not animate like float example

### ISSUE THREAD

**Issue by gusdn0828** [gridstack/gridstack.js#1936]
## Subject of the issue
If unsure if library bug, or questions use slack channel instead: https://gridstackjs.troolee.com/

-----------------------------------------------------------------------------------
I want to use this library in vue3.
After I dragged a item, it got the attr like this
```javascript
style="transition: none 0s ease 0s;"
```
The animation of item's behind the dragging item does not work.
Vue demo also same, but basic demo is working.

vue demo's link:
https://gridstackjs.com/demo/vue3js.html
basic demo's link:
https://gridstackjs.com/

Please fix this bug.

## Your environment
* gridstack.js 5.0.0
* HTML5 plugin
* Chrome/Windows 10
* Vue 3.2.25,
* Vite 2.8.0

## Steps to reproduce
1. Enter this demo page
https://gridstackjs.com/demo/vue3js.html

2. Drag 0 item over 1 item
3. Drag 1 item over 0 item
4. So 0 item's animation doesn't work.

## Expected behavior
Please fix the bug.

**Comment by adumesny** [comment]
https://gridstackjs.com/demo/float.html animates when bottom object is pushed to grow the grid, but not in the vie demo https://gridstackjs.com/demo/vue3js.html

not sure where you see `style="transition: none 0s ease 0s;"`

**Comment by arg-1138** [comment]
`style="transition: none 0s ease 0s;"` is applied to every item after dragging it once. The first time it animates correctly but then after that inline style is applied it stops transitioning.
- Happening on: https://gridstackjs.com/demo/float.html and vue3 & vue2 demos. (not tested others)
- Chrome 96.0.4664.110
- macOS 11.6

**Comment by adumesny** [comment]
not seeing this issue anymore in 7.1.2
the only styles I see left after a drag are those, which is armeless
```css
element.style {
    min-width: 0px;
    will-change: left, top;
}
```
