### ISSUE TITLE
Setting minW property for a grid doesn't work, it still using default 768 breakpoint to wrap in one column

### ISSUE THREAD

**Issue by dvenediktova** [gridstack/gridstack.js#1937]
## Subject of the issue
Setting minW property for a grid doesn't work, it still using default 768 breakpoint to wrap in one column.

## Your environment
gridstack version 5.0.0
browser Chrome 96

## Steps to reproduce
demo: https://jsfiddle.net/dvenediktova/bjwzf8d0/7/

## Expected behavior
minW property sets the width for one column mode

## Actual behavior
minW property has no effect, grid wraps to one column on 768px

**Comment by adumesny** [comment]
that's because the grid options is called `minWidth` (the short hard is for items only) - deally it would be renamed to have oneColumn as part though to be honest...
