### ISSUE TITLE
Performance problem 

### ISSUE THREAD

**Issue by mitow7821** [gridstack/gridstack.js#1944]
## Subject of the issue
My grid items have pre-defined height set in pixels. Only way to achive pixel perfect grid I've found is to set cellHeight to 1. 
Unfortunately it leads to huge purformance issue but only when I open chrome devtools. 
Is there any better way to do so? 

## Your environment
gridstack 5.0.0
jquery plugin
chrome

## Steps to reproduce
https://jsfiddle.net/sjc3zynp/15/
Even on this fiddle after opening devtools this performance problem is visible.
Similar problem: (since it was close there is still no other option than to use cellHeight:1) https://github.com/gridstack/gridstack.js/issues/125

## Expected behavior
Provide more performant method to use exact height in pixels.

**Comment by adumesny** [comment]
related to #1942 ?

**Comment by mitow7821** [comment]
To be more precise my goal is not to set 1px height to all items I am trying to set that height to inherit from children height. 
In my case I have 3 variants of heights that could occur (img below). Do you have any tips hould could I make it the most performant way?
(I've used 1px becasuse I could then set precise gs-h values which can't be float)

![image](https://user-images.githubusercontent.com/34492112/160757159-b53d83bc-6643-46e6-8b65-a84fcc211629.png)

**Comment by adumesny** [comment]
cellHeight:1 is the issue, don't use that. make all you 3 items a multiple of the same number (say 10) PLUS the margin you are setting (5 of each side by default). so h1= 10-10, h2=20-10, h3=30-10, etc...
gridstack is NOT meant to be a pixel precise pixel library as it is column/row based for responsive design, not hardcoded pixels. Might need to look elsewhere or control you container size to make the math work...
