### ISSUE TITLE
Responsive grid with static elements

### ISSUE THREAD

**Issue by camilandre** [gridstack/gridstack.js#1946]
Responsive grid with static elements 

I am making an application for exclusive use on large screens and the user wants that when the screen is enlarged, the widgets that are on his dashboard do not change size to fit more.
I already got the elements to not change size, but I can't make more space when the screen is bigger

I am using these links to access the library:

```
    <link rel="stylesheet" href="https://gridstackjs.com/node_modules/gridstack/dist/gridstack-extra.min.css" />
    <script src="https://gridstackjs.com/node_modules/gridstack/dist/gridstack-h5.js"></script>
```

This is how it works now
![image](https://user-images.githubusercontent.com/75325895/160837824-acffd368-df7d-44ce-9831-e01c516cacc9.png)

And this is what happens when the container gets bigger

![image](https://user-images.githubusercontent.com/75325895/160837952-3f02586e-84bd-41f5-92d6-a79b590fd62c.png)

I want the elements to stay the same size, while they reorganize at the same time taking up less space in between so that more elements can fit into the container 

Thanks for the help, I've been reading a lot and nothing that I can solve it

**Comment by adumesny** [comment]
first of all don't use gridstack website to host your libs - get the npm images and host them yourself please!
as for your question, did you look at `column(N, 'none')` rather than the default 'moveScale' (it's moving above, and maybe not scaling due to rounding off) ? you didn't provide any code so I have no idea what you are using when the grid 'grows' (I would go from 6 columns to 10 for example above maybe)...

**Comment by camilandre** [comment]
I have already changed the links for npm images 

Here is my code. 
My grid container grows when the widgets container is hidden using this function: 

```
minimize.addEventListener('click', hideWidgets);
downsize.addEventListener('click', showWidgets);

function hideWidgets() {
  widgets.classList.add('hide');
  downsize.style.transition= "ease 5s all";
  downsize.style.display = "block";
  enlargeDashboard();
}

function showWidgets() {
  widgets.classList.remove('hide');
  downsize.style.display = "none";
  downSizeDashboard();
}

function enlargeDashboard() {
  inf.style.width= "80vw";
}

```

Here the rest of code.
https://jsfiddle.net/camilandrea/6z0gbaxc/32/

**Comment by adumesny** [comment]
don't have time to debug your code, but https://gridstackjs.com/demo/nested.html resizing the dark yellow nested grids likely does what you want.
