### ISSUE TITLE
jquery-ui 1.12.1 (prior versions of 1.13.0)  have multiple Security Vulnerabilities (XSS)

### ISSUE THREAD

**Issue by julio-tinajero** [gridstack/gridstack.js#1947]
jQuery-ui versions prior 1.13.0 have a Security Vulneravilities listed in CVE website:
https://www.cvedetails.com/vulnerability-list/vendor_id-6538/product_id-31126/Jquery-Jquery-Ui.html

List of Vulnerabilities:

jQuery-UI is the official jQuery user interface library. Prior to version 1.13.0, accepting the value of the `of` option of the `.position()` util from untrusted sources may execute untrusted code. The issue is fixed in jQuery UI 1.13.0. Any string value passed to the `of` option is now treated as a CSS selector. A workaround is to not accept the value of the `of` option from untrusted sources.

jQuery-UI is the official jQuery user interface library. Prior to version 1.13.0, accepting the value of various `*Text` options of the Datepicker widget from untrusted sources may execute untrusted code. The issue is fixed in jQuery UI 1.13.0. The values passed to various `*Text` options are now always treated as pure text, not HTML. A workaround is to not accept the value of the `*Text` options from untrusted sources.

jQuery-UI is the official jQuery user interface library. Prior to version 1.13.0, accepting the value of the `altField` option of the Datepicker widget from untrusted sources may execute untrusted code. The issue is fixed in jQuery UI 1.13.0. Any string value passed to the `altField` option is now treated as a CSS selector. A workaround is to not accept the value of the `altField` option from untrusted sources.

Cross-site scripting (XSS) vulnerability in jQuery UI before 1.12.0 might allow remote attackers to inject arbitrary web script or HTML via the closeText parameter of the dialog function.

Cross-site scripting (XSS) vulnerability in jquery.ui.dialog.js in the Dialog widget in jQuery UI before 1.10.0 allows remote attackers to inject arbitrary web script or HTML via the title option.

**Comment by adumesny** [comment]
thank you for the info - it may be hard to get 1.13.x as I had to manually build JQ UI locally since we are using only a subset (1/5th the size) and last time I tried their website to get subset was no longer maintained... it's been a while.

my focus is on h5 (and soon raw mouse event + touch for mobile) and no longer offer JQ as an option and greatly simplify the code. see #1757

**Comment by julio-tinajero** [comment]
Thank you,
Is this their site to download subsets?

https://jqueryui.com/download/#!version=1.13.1&components=000000000000000000000000000000000000000000000000

**Comment by adumesny** [comment]
yes and it looks like it's working again...great.

**Comment by julio-tinajero** [comment]
If you could  update the jquery-ui dependencies with it. I'd truly appreciate it. Thanks. in advance

**Comment by adumesny** [comment]
will be in next release.
