### ISSUE TITLE
Update the height of the widgets proportionally

### ISSUE THREAD

**Issue by Tamara2365** [gridstack/gridstack.js#1951]
## Subject of the issue
Hello, I wanted to create a dense grid so that the widgets move in smaller steps horizontally and vertically. I figured out that by creating a grid from 12 to 60 columns, I need to increase the widget's width 5 times. However, I cannot figure out the height ratio to preserve the same widget size as before, since the rows are added dynamically. I added the argument cellHeight: 'auto' to create square cells. This made my widgets smaller. Can you figure out how many times should I increase the height to obtain the same widget size? (Example: if the height was 5 squares for 12 columns, how many squares should it take for 60 columns, increasing by 5 does not give the same results.) The horizontal movement works as desired.

I increased the number of columns with the following code:
`
min-width: 1.67%;
$gridstack-columns: 60;
  @for $i from 1 through $gridstack-columns {
    &[data-gs-width='#{$i}'] { width: (100% / ($gridstack-columns)) * $i; }
    &[data-gs-x='#{$i}'] {  left: (100% / ($gridstack-columns)) * $i; }
    &[data-gs-min-width='#{$i}'] { min-width: (100% / ($gridstack-columns)) * $i; }
    &[data-gs-max-width='#{$i}'] { max-width: (100% / ($gridstack-columns)) * $i; }
  }`

The .xhtml code for the cell height: 
`jqr('.grid-stack').gridstack(
                            {alwaysShowResizeHandle: dashboardEditMode, staticGrid: !dashboardEditMode, width: 60, cellHeight: 'auto',float: true});`

## Your environment
* version of gridstack.js ------------> v4
* which browser/OS ---------> Google Chrome/Linux

**Comment by adumesny** [comment]
please use the slack channel for questions.
