### ISSUE TITLE
min file and sourcemap

### ISSUE THREAD

**Issue by PureDevelopers** [gridstack/gridstack.js#1956]
I have downloaded your nuget package, which includes a minified version of the js file. It's called: gridstack.min.js and it references a map file called: sourceMappingURL=gridstack.min.map but you don't include the map file in the download.
How is this supposed to work?

**Comment by adumesny** [comment]
I don't see a gridstack.min.js anywhere in the latest package - what version are you using ?
![image](https://user-images.githubusercontent.com/3496166/165368387-64283c50-fd8c-42d0-9d42-b36f7c06fc84.png)
