### ISSUE TITLE
Can't add last item to fixed grid (jq)

### ISSUE THREAD

**Issue by Pixmar17** [gridstack/gridstack.js#1962]
## Subject of the issue
Trying to make fixed grid with 3 cells (jq version), but when trying to add last item to grid, item is not added.
With h5 version works correctly.

## Your environment
5.0.0, jq

## Steps to reproduce
https://jsfiddle.net/3mdn8xhj/1/

## Expected behavior
add last item to grid (3/3)

## Actual behavior
item can not be added

**Comment by adumesny** [comment]
closing as JQ is now gone in v6. if still happens please re-open
