### ISSUE TITLE
Grids not allowing accept elements dragged into grid without calling Gridstack.setupDragin

### ISSUE THREAD

**Issue by zgilewski** [gridstack/gridstack.js#1964]
Imagine page where we have grid and a toolbar from which user can drag and drop elements.
This toolbar is reusable component which can be used in many other projects/libraries and it implements its own toolbar items dragging. Now we want to use this toolbar to drag elements into Gridstack grid. But the problem is that we are not able to do it without calling Gridstack.setupDragin method which configuring gridstack drag&drop for elements.
Problem is that Gridatack drag&drop conflicts with our drag&drop so we would like to use only our drag&drop.
So, is there any posibility, that Gridstack will accept and recognize dragging/dropping elements without use of Gridstack.setupDragIn method ?

We are using gridatack version 4.2.7 without jquery.

Expected behaviour is that Gridstack should allow dropping elements without need of calling Gridstack.setupDragIn. It should be enough to return true from acceptWidgets property/function of grid configuration.
Actually, if Gridstack.setupDragIn will not be called, then grid is not accepting any elements dragged and dropped on it.

**Comment by adumesny** [comment]
| Problem is that Gridatack drag&drop conflicts with our drag&drop so we would like to use only our drag&drop.

I'm confused on what you are asking. 
``` 
GridStack.setupDragIn('.sidebar .grid-stack-item', { revert: 'invalid', scroll: false, appendTo: 'body', helper: myClone });
```
is only called on the toolbar to have our D&D handlers, but if you provide your own dragging, I believe the grid will accept those events and items if they have the right format (.grid-stack-item) and grid has `acceptWidgets` defined, and same drag events we use (happen to be html5 draggable but will change overtime). There are no plan to make this more expandable...

**Comment by adumesny** [comment]
closing due to lack of response
