### ISSUE TITLE
All divs stacked on top of one another and won't drag or resize

### ISSUE THREAD

**Issue by harrington101** [gridstack/gridstack.js#1974]
## Subject of the issue
I am trying to install this without using NPM, just the .js files. I don't get any console errors but the widgets won't drag or resize and are all stacked on top of each other. 

## Your environment
* Jquery 3.5.1
* Jquery Event Move
* Jquery Event Swipe
* Chrome Windows 10

## Steps to reproduce
I tried to follow the instructions by installing with NPM. That didn't work. I tried adding the alias. That didn't work. It seemed like Jquery might have been installed twice because my other jquery functions threw console errors. I tried downloading the .js files from the examples and that didn't work either. I added console.log(hello) to the files and saw that they were in fact loading. 

## Expected behavior
I should be able to copy the sample code and move the elements around. 

## Actual behavior
The divs all stack on top of each other. When I drag them and let go they snap back to their original position.

**Comment by adumesny** [comment]
if you are using jquery, either use the h5 version, or you must use jquery that is included with our jq version. Read the doc https://github.com/gridstack/gridstack.js#jquery-application and https://github.com/gridstack/gridstack.js#install
