### ISSUE TITLE
subgrid's title and scrollbar handling 

### ISSUE THREAD

**Issue by cht132** [gridstack/gridstack.js#1984]
## Subject of the issue
show scrollbar if it has content in subgrid

## Steps to reproduce
https://jsfiddle.net/yarwn7e5/

## Expected behavior
no scrollbar

## Actual behavior
has scrollbar

**Comment by adumesny** [comment]
please fix your example and re-open. h scrollbar don't show by design (content better fit in column based layout), V scrollbar does show.
