### ISSUE TITLE
addWidget() or DOM read in single column mode will not adjust to multicolumn mode

### ISSUE THREAD

**Issue by ericpool** [gridstack/gridstack.js#1985]
When a grid is loaded for the first time in single column mode instead of multicolumn mode, it will remain a single column when resizing to multicolumn mode. Multicolumn mode toggles on, but all the items remain in their left-aligned positions.

Using gridstack 4.6.2, but since it is happening in the demo too, doubt it is relevant.

You can see this happening in the demo page here:
https://gridstackjs.com/demo/nested_advanced.html

Just load the page with the browser at a small enough size to trigger single column mode, then adjust window size.

**Comment by adumesny** [comment]
Only a problem with nested grids, regular ones work (as I recall fixing that issue a while back) https://gridstackjs.com/demo/web1.html

**Comment by ericpool** [comment]
> Only a problem with nested grids, regular ones work (as I recall fixing that issue a while back) https://gridstackjs.com/demo/web1.html

Do you recall when this issue was resolved (i.e. maybe I should update?)? I am having this issue while not using nested grids.

**Comment by ericpool** [comment]
I looked through those and they seem to address similar issues that I am having, however, it does not appear to be working as intended for me.

Here is a very plain example of the issue I am having: https://jsfiddle.net/ericpool/7k2jya48/6/

As you can see, when initializing it in single column mode, it forgets all positioning:

![ezgif-3-5e4a17e604](https://user-images.githubusercontent.com/46460854/175394299-5fead930-9944-459d-ba28-40020666244a.gif)

**Comment by adumesny** [comment]
ok, see the issue with simpler https://jsfiddle.net/adumesny/2r3tjnds/
adding 1 item at a time doesn't work, while load() does...

**Comment by decelis** [comment]
Any workarounds for this issue? The same thing happens if you declare the grid items in the DOM:
[https://jsfiddle.net/oqasp04y/1/](https://jsfiddle.net/oqasp04y/1/)

**Comment by adumesny** [comment]
don't know of a workaround unless you patch the code, or add the items while in 12 columns, then go back to 1.

But you are welcome to submit a fix, or donate to get it fixed...

**Comment by PPP01** [comment]
@decelis 
You can use a MutationObserver as a workaround:
https://jsfiddle.net/4n93fzwr/
