### ISSUE TITLE
Grid items not displaying in correct order

### ISSUE THREAD

**Issue by harrington101** [gridstack/gridstack.js#1986]
The tiles are not loading or maintaining their correct order. There are 2 issues happening here:
1. Notice that on page load, tile 9 shows up before tile 8. 
2. When resizing the pane the tiles get all mixed up and are no longer in numerical order (left to right top to bottom).

Here is a sample of my code on JS Fiddle.  [JSFiddle](https://jsfiddle.net/3r4kp8dn/9/)

_Originally posted by @harrington101 in https://github.com/gridstack/gridstack.js/issues/1975#issuecomment-1158192145_

**Comment by adumesny** [comment]
don't open another bug...

**Comment by harrington101** [comment]
Sorry, couldn't figure out how to update the status to remove the needs more info tag.

**Comment by adumesny** [comment]
that's for me to manage
