### ISSUE TITLE
Unable to emit events from child components to parent component in vuejs

### ISSUE THREAD

**Issue by shibisuriya** [gridstack/gridstack.js#1987]
## Subject of the issue
I want to emit events from components wrapped inside of gridstack-item-content to the parent component rendering the entire gridstack layout in the DOM in vuejs. 

## Your environment
* Installed gridstack ^5.1.1 from npm registry into my vue2 project. I am using the HTML5 version of gridstack.
* Google chrome

## Steps to reproduce
https://github.com/shibisuriya/vue-gridstack/blob/vue-gridstack-event-not-working/src/App.vue 
You can use this link to look at the code, look at line 25 and line 39.

## Expected behavior
Want to get the ability to emit events from components wrapped inside gridstack-item-content to parent component.

## Actual behavior
Not getting events from components wrapped inside gridstack-item-content to parent component.

**Comment by adumesny** [comment]
I don't believe this is a gridstack lib issue - doesn't deal or prevent any events as it's just CSS classes on regular doms -  but how the vue components are initialized.

**Comment by shibisuriya** [comment]
I am so sorry, I didn't check the vue code properly, the components wrapped inside gridstack classes emits events perfectly... I made a lame mistake, sorry for wasting your time, thank you for replying...
