### ISSUE TITLE
Question: initializing a subgrid from html

### ISSUE THREAD

**Issue by v1talii-dev** [gridstack/gridstack.js#1991]
The documentation describes how to initialize gridstack from html, but I don't understand how to describe subgrid in html.
I tried to make such a structure, but the subgrid elements are not interactive:

```html
<div class="grid-stack">
  <div class="grid-stack-item">
    <div class="grid-stack-item-content">Item 1</div>
  </div>
  <div class="grid-stack-item" gs-w="2">
    <div class="grid-stack-item-content">
       
       /** Subgrid section **/
       <div class="grid-stack grid-stack-nested">
          <div class="grid-stack-item">
            <div class="grid-stack-item-content">Item 1</div>
          </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by v1talii-dev** [comment]
Yes, of course, here is a demonstration of an example https://codepen.io/iron_vd/pen/OJvJKaZ

**Comment by adumesny** [comment]
I wouldn't expect `GridStack.init({}, '#gridstack')` to work since you are explicitly init just the top one (there is no reason for it to search through content and find other grids. use `GridStack.initAll()` instead, which works.
