### ISSUE TITLE
Question: how set auto height for nested grid?

### ISSUE THREAD

**Issue by v1talii-dev** [gridstack/gridstack.js#1992]
There is a grid that contains a subgrid. The grid is initialized from html. I could not find in the documentation how to automatically calculate the height of a subgrid based on its contents. I would appreciate an answer. Thanks.

![image](https://user-images.githubusercontent.com/12966923/176692681-3fcc1e21-3eb0-4489-8a52-4d6fa39ad562.png)
Demo - https://codepen.io/iron_vd/pen/OJvJKaZ

**Comment by adumesny** [comment]
use slack for questions, stop posting 'bugs'. see the nested example that answers your question too...
