### ISSUE TITLE
resizing a square near another square creates weird behavior 

### ISSUE THREAD

**Issue by mark3448** [gridstack/gridstack.js#1994]
## Subject of the issue
resizing a grid item near another grid item minimizes the other grid item and creates weird behavior

## Your environment
* version of gridstack.js
5.1.1
* which browser/OS
chrome on windows

## Steps to reproduce
https://codesandbox.io/s/heuristic-leftpad-teoq21?file=/package.json:283-288
or 
https://teoq21.csb.app/

1. take 'b' square and drag it to the right creating a 2 width square
2. take 'a' square and drag it to the right creating a 2 width square

## Expected behavior
b should be 2 width square and under it a should be a 2 width square.

## Actual behavior
'a' becomes a 2 width square
'b' goes under 'a' and becomes a 1 width square

**Comment by adumesny** [comment]
sorry but codesandbox.io doesn't show anything and I don't follow custom link urls for the other. please post a simple code sample like the bug template for me to check...
![image](https://user-images.githubusercontent.com/3496166/177352465-ddcfbcc1-d116-4559-aa91-baa50d42466e.png)

**Comment by mark3448** [comment]
after further checking, the behavior stops when i set auto:false.

**Comment by adumesny** [comment]
don't know what `auto:false` is. sorry but can't be debugging your react app. closing unless you can post a plain js example showing a lib issue.
