### ISSUE TITLE
support for 'zoom' css

### ISSUE THREAD

**Issue by brodrigz** [gridstack/gridstack.js#1995]
## Subject of the issue
drag & drop, and resize does not work as expected when applying 'zoom' css on grid wrapper or any parent div 

## Your environment
* 3.5.1
* Chrome 103

## Steps to reproduce
on https://gridstackjs.com/demo/web2.html
apply 'zoom:0.5' at the col containing the grid

## Expected behavior
on resize or drag & drop, widget should move along with the cursor

## Actual behavior
widget moves at slower pace than cursor

**Comment by adumesny** [comment]
dup of #1275 (same issue)
