### ISSUE TITLE
Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node' in version 5.1.1

### ISSUE THREAD

**Issue by xinnai** [gridstack/gridstack.js#1996]
Hi, great job!!! I have an error when using custom 'helper'  with the code bellow. And this block my dragging from one grid to another. I had searched a lot, some demo can work fine with lower version. Is this a bug on version 5.1.1?

```code
let destopOption: any = {
    maxRow: 6,
    minRow: 6,
    margin: '20px',
    oneColumnSize: 400,
    staticGrid: true,
    acceptWidgets: true,
    // disableResize: true,
    float: true, 
    // dragIn: '.drag-item',  // class that can be dragged from outside
    // dragInOptions: {
    //   revert: 'invalid', scroll: false, appendTo: 'body', helper: () => {
    //     console.log("dragInOptionsdragInOptionsdragInOptions")
    //   }
    // }, // clone or can be your function
  };
  grid = GridStack.init(destopOption, "#GridContainer");
  GridStack.setupDragIn('.drag-item', { revert: 'invalid', scroll: false, appendTo: 'body', helper: addWidget });
```
![Snip20220715_2](https://user-images.githubusercontent.com/23135336/179182676-908ddfc3-a28a-4b88-843d-153bd4187382.png)

**Comment by adumesny** [comment]
you need to post a full working example (make it as simple as possible! just bare minimum to show bug) if you want me to even take a look... you don't show what your `addWidget()` does either!

**Comment by adumesny** [comment]
closing due no response

**Comment by ht89** [comment]
@xinnai  I had the same issue. Ensure you don't return **null** or **undefined** in your custom helper method
