### ISSUE TITLE
v5.1.1 JQ version - Nested Grid Drag out...

### ISSUE THREAD

**Issue by albowler** [gridstack/gridstack.js#1998]
## Subject of the issue
In version 5.1.1 - the jQuery version - it is not possible to drag a widget out of a nested grid. Also, drag and drop inside of a nested grid does not work as expected.

Similar to the bug reported here: https://github.com/gridstack/gridstack.js/issues/1700

## Your environment
Jquery version gridstack - 5.1.1
* Windows 10, Chrome 103.0.5060.114 (Official Build) (64-bit), Edge Version 103.0.1264.49 (Official build) (64-bit)

## Steps to reproduce
Try and drag a widget out of the nested "sub" grid into the main grid:

https://jsfiddle.net/ra2vnky6/2/

## Expected behavior
Drag widgets out of a nested grid

## Actual behavior
Widgets cannot leave the grid

**Comment by adumesny** [comment]
unlikely to get fixed as I'm switching away from jq and going native only in the future (once I can get mouse+touch for mobile).

**Comment by albowler** [comment]
Could you fix it for a donation please? 🙏🤞

**Comment by albowler** [comment]
Hi Alian, I see from other messages now that other people have offered to make donations to have bugs fixed - and just disappeared. So I’m sorry if my above message sounded like I wasn’t being serious.

We’d be willing to pay you to fix this bug, and add some other features to gridstack - I’ve sent you a little donation to show you we’d like to contribute to the fix/development 🫣😃

> @Prid13 only @ataft has donated $50 so far which is very much appreciated. heck, if most people that use gridstack would even give 'beer money', someone could possibly make this a fulltime gig... never heard from @ranjeettamil again.
> If a few people are willing to back this one, I'll take a look. I'm pretty sure this is not an easy one at all... been tried before (a reason same bug #141 has been sitting for 5.5 years!)

**Comment by adumesny** [comment]
@albowler ping me directly on slack (https://gridstackjs.troolee.com/) to continue this... I already spent 4h saturday trying to even get the drag items to not be clipped for nested grid, and trying to work around jquery is a major pain...

I sent you email, but why do you even need to use the JQ version ? as I said it will go away someday as I don't want to support multiple plugging going forward, and is old tech/no longer actively supported.

**Comment by adumesny** [comment]
fixed in v6 with new native (not more jq)
