### ISSUE TITLE
GridStackEngine.nodeBoundFix(node, resizing) has no access to attributes (e.g. id)

### ISSUE THREAD

**Issue by jojoxd** [gridstack/gridstack.js#2006]
## Subject of the issue
While trying to create a custom Engine (`class CustomEngine extends GridStackEngine/GridStack.Engine {}`), I got stuck on fetching an "allowed size" for an node. I was trying to read node.id, which does not exist after initial loading. Looks like something, somewhere clears that data?
I looked a bit through the code but could not find the culprit.

## Your environment
gridstack 5.1.0/5.1.1 using vivaldi on fedora 35. I'm using the es5+h5 build.

## Steps to reproduce
See this jsfiddle: https://jsfiddle.net/dmz2t6oy/ (Try moving an item)

## Expected behavior
I expect that i can access node.id in `GridStackEngine#nodeBoundFix(node, resizing)` so I can locate the correct "allowed size" in my application

## Actual behavior
I cannot access node.id in `GridStackEngine#nodeBoundFix(node, resizing)`.

**Comment by adumesny** [comment]
https://jsfiddle.net/adumesny/cs19qfja/

you assume the method is only called with a full `GridStackWidget` or subclass, but during dragging the clone  only has x,y,w,h values (might be dependent on drag&drop features as well) - so as designed.

I made it possible to have engine subclass but out of my scope to explain the functionality to be honest. Closing.

![image](https://user-images.githubusercontent.com/3496166/182744098-60fbb29a-f075-493b-8072-298a21432ed5.png)
