### ISSUE TITLE
Image as a children is not updating when trying to update grid Item. ( rotate )

### ISSUE THREAD

**Issue by harshitsan** [gridstack/gridstack.js#2007]
## Image orientation is not aligning with the parent when using grid.update()
When I am trying to rotate ( update the item ) the parent is rotating but the children aren't
1. The highlighted one is the rotated item, which is actually cropped to 1 cell when it should take 3 cells vertically.

![image](https://user-images.githubusercontent.com/30543655/182986845-cd84898e-85c7-49e1-97ea-6fe0db24066e.png)

2. This is the expected output
![image](https://user-images.githubusercontent.com/30543655/182987059-5c602d26-ea8b-4842-aead-0a4096709c0f.png)

## Your environment
* version of gridstack.js : 5.1.1
*Jquery - 3.6.0
* which browser/OS: Chrome / Windows 10

## Steps to reproduce
Here's the Working Demo 
https://rotationbug.netlify.app/
the square items are rotating properly, but when I am updating the width and height of the rectangular item, It's not 

## Expected behavior
The children should take the space of the parent element automatically.

## Actual behavior
The square items are rotating properly, but when I am updating the width and height of the item, It's not

**Comment by adumesny** [comment]
`grid.update()` only changes the grid-stack-item Gridstack properties (like gs-x, etc...), nothing to do with children CSS or Dom attributes properties. if rotate attriute doesn't do what you want, that's a CSS issue.

closing unless you can show it's a lib issue in a plain example (not your app)

**Comment by harshitsan** [comment]
Thanks for the response, I was able to fix it

I was already manipulating dom using 
`element.style.transform` on each rotation.
but it was not getting saved with grid.save()
but now as I am using 
`element.style.webkitTransform`
It's getting saved in grid.save() 

And I want to seriously thank you for creating such an amazing library, it just saved me weeks,
Once this project is over, I will be contributing to your sponsored link.
Cheers
