### ISSUE TITLE
Move many grid stack items

### ISSUE THREAD

**Issue by arturstream** [gridstack/gridstack.js#2017]
I need implement a scenario where we can select and move more than 1 grid stack item simultaneously.
Is there possibility to do this?  Select 2 or more elements and dragging a group. 
Something like virtual elements' group, not nested components.

**Comment by adumesny** [comment]
there is not (only nested grid) - also the collision placement for multiple items at once would not be trivial and may conflict between items so not sure it would be possible in the general case.
