### ISSUE TITLE
Save Grid and float prop

### ISSUE THREAD

**Issue by bhowell2-fleetio** [gridstack/gridstack.js#2020]
I'm not sure if this is intentional?

But, when you set `float` it does not set it on the options, but on the engine: https://github.com/gridstack/gridstack.js/blob/master/src/gridstack.ts#L792
. 

Then, when you `save` (https://github.com/gridstack/gridstack.js/blob/master/src/gridstack.ts#L510) it makes a copy of `opts` but this only includes the initial float setting and not what may have been set by calling `float(true|false)`.

I'll submit PR if it is desired to include the later set float values.

**Comment by adumesny** [comment]
please do, looks like a bug. I guess set should set on options as well (problem with you have >1 source of 'truth' :)

**Comment by adumesny** [comment]
fixed in 6.0.1
