### ISSUE TITLE
The internal input box of the component cannot focus

### ISSUE THREAD

**Issue by ManbasJi** [gridstack/gridstack.js#2038]
I used gridstack in vue3, but the input box inside the component cannot focus. I commented out the gridstack, and the input box can be used normally. So I wondered whether the focus event was blocked

## Your environment
pc web,vue3

## Steps to reproduce
```js
export function initGridStack() {
  const gridstackOpts = {
    animate: true,
    float: true,
    cellHeight: 20,
    column: 36,
    dragInOptions: { revert: 'invalid', scroll: false, appendTo: '.grid-stack', helper: 'clone' } 
  };

  grid = GridStack.init(gridstackOpts);

  grid.on('resizestop', (event, ui) => {
  });

  grid.on('dragstop', (event, ui) => {
  });

  grid.compact();
}
```
render dom structure
![Snipaste_2022-09-14_10-37-49](https://user-images.githubusercontent.com/20039217/190046386-51873dfc-c4b9-4743-bb2e-9d19eb225300.png)
## Expected behavior
The input box inside the component can be used normally

## Actual behavior
 the input box inside the component cannot focus

**Comment by adumesny** [comment]
please post a reproduceable example. I recommend using the default one and adding an input field to see if that still fails, if not it's likely your issue...

**Comment by ManbasJi** [comment]
> please post a reproduceable example. I recommend using the default one and adding an input field to see if that still fails, if not it's likely your issue...

**Comment by ManbasJi** [comment]
> please post a reproduceable example. I recommend using the default one and adding an input field to see if that still fails, if not it's likely your issue...

Yes, it's my issue, although I haven't found the issue yet
