### ISSUE TITLE
Jittering when swapping elements with the same width/height

### ISSUE THREAD

**Issue by Voodu** [gridstack/gridstack.js#2043]
## Subject of the issue
When there are two elements with the same height placed next to each other (horizontally) and I want to swap them (i.e. drag one over the another so they switch places), there's visible jittering of both of them.

The same happens for same width and swapping elements placed vertically.

## Your environment
* version of gridstack.js: 6.0.1
* which browser/OS: tested on Chrome and Firefox, Ubuntu 20.04

## Steps to reproduce
You **MUST** provide a working demo (keep it simple!) you can use 
https://jsfiddle.net/ogm3L8q1/1/

## Expected behavior
The swap should happen smoothly

## Actual behavior
Both elements jitter. The slower the movement/the bigger the elements, the more visible it is.

**Comment by adumesny** [comment]
that's so bizzar as it works locally... and not supposed to swap until you hit 50% (with margin) preventing possible back-and-forth.

need to investigate. thanks.

**Comment by PPP01** [comment]
I had this behavior as well - with v5 and v6.
It happens, when you add the "row" parameter. Without, everything works smooth.

**Comment by adumesny** [comment]
oh, that's great info! thank you. I had not seen it before...

**Comment by adumesny** [comment]
fixed in 6.0.2 - don't forget to donate if you find this lib useful!
