### ISSUE TITLE
After removeWidget(el)  the resize button disappeared

### ISSUE THREAD

**Issue by bruce-teng** [gridstack/gridstack.js#2044]
## Subject of the issue
the office demo，after clicking the X in the upper right corner, the resize button in the lower right disappeared
https://gridstackjs.com/demo/serialization.html

## Your environment
* version of gridstack.js 6.0.1
* browser:  Chrome/105.0.0.0
* OS: Windows 10 21H2

## Steps to reproduce
https://gridstackjs.com/demo/serialization.html
![reproduce](https://user-images.githubusercontent.com/24269297/191192839-f3542ea5-7321-4275-9e97-838e7bc9de4a.gif)

## Expected behavior
after removeWidget the resize button should still show may be

## Actual behavior
after clicking the X in the upper right corner, the resize button in the lower right disappeared

**Comment by adumesny** [comment]
dup of https://github.com/gridstack/gridstack.js/issues/2034 fixed in upcoming 6.0.2
