### ISSUE TITLE
Resize handles disappear after the action with grid is invoked from the widget content

### ISSUE THREAD

**Issue by WellBload** [gridstack/gridstack.js#2045]
## Subject of the issue
Resizing handles disappear after the action with grid is invoked from the widget content. For example removeWidget(). If alwaysShowResizeHandle is set to true everything works fine. It seems to me that this only happens if the mouse cursor is over the widget from which the action is called.

## Your environment
* 6.0.1
* Chrome/Windows 10

## Steps to reproduce

https://jsfiddle.net/5z3cat6L/
Just click on "delete" content of any widget.

## Expected behavior
Keep resize handles

## Actual behavior
Resize handles disappear

**Comment by adumesny** [comment]
dup of https://github.com/gridstack/gridstack.js/issues/2034 fixed in upcoming 6.0.2
