### ISSUE TITLE
Can't enter text in textarea/input

### ISSUE THREAD

**Issue by sbkobaidze** [gridstack/gridstack.js#2054]
Can't enter text on textarea/input 

Using gridstack.js - 6.0.2v
Browser: Google Chrome
OS: Windows 10

https://jsfiddle.net/sabakobaidze/sqv0acgx/2/
## Expected behavior
Should be able to write text when clicking textarea/input
## Actual behavior
Not being able to type when clicking on textarea/input

**Comment by adumesny** [comment]
thank for posting.

**Comment by adumesny** [comment]
fixed in 6.0.3 - don't forget to donate if you find this lib useful!
