### ISSUE TITLE
Grid elements can be resized outside of the bound defined by `row` option.

### ISSUE THREAD

**Issue by Voodu** [gridstack/gridstack.js#2055]
## Subject of the issue
`row` setting is not respected and elements can be resized outside of grid bounds defined by `row` setting.

The bug was introduced in version 6.0.2. The previous one, 6.0.1, seems to be working just fine.

## Your environment
* gridstack@6.0.2
* tested on Chrome and Firefox, Ubuntu 20.04

## Steps to reproduce
https://jsfiddle.net/pkyjg2sw/
This can be reproduced in two ways:
1) Resize the upper element downward, pushing the bottom one down.
2) Resize the bottom element downward. Might need some wigging with the mouse at the bottom of the screen, but it's also possible.

## Expected behavior
Resizing the upper element vertically shouldn't be possible due to fixed `rows` option

## Actual behavior
Resizing is possible, the bottom element is pushed downwards and everything gets out of defined `rows` bounds.

**Comment by adumesny** [comment]
| bug was introduced in version 6.0.2. The previous one, 6.0.1

thank you, that makes it easier to track. You fix some bugs, and apparently introduce new ones :)

**Comment by adumesny** [comment]
fixed in 6.0.3
