### ISSUE TITLE
How can I join to your slack?

### ISSUE THREAD

**Issue by luisampuerovalenzuela** [gridstack/gridstack.js#2057]
## JOIN to SLACK
Hello, I can't find the way to join to your slack channel, I hope I can enter.

Regards

**Comment by adumesny** [comment]
https://gridstackjs.slack.com/

**Comment by luisampuerovalenzuela** [comment]
Hi @adumesny with that link I can not enter, maybe you can share the invitation link please.

When I use the link above this appear:
<img width="768" alt="image" src="https://user-images.githubusercontent.com/96737011/193299027-3941655b-ffde-4b84-a4ec-8afc85467d0a.png">

I have already tried multiple times.

Regards and thanks

**Comment by adumesny** [comment]
can you translate for me the error message ? what happens when you connect with Google instead ? seems like a generic error with login into gridstack (can you for other channels ?)

**Comment by luisampuerovalenzuela** [comment]
I have been connecting through Google all the time. The translation for the error message is: 'You do not have an account on this workspace yet'

**Comment by luisampuerovalenzuela** [comment]
I believe that the link that you should share is like this: https://join.slack.com/t/gridstack.js/shared_invite/SOME_ID

You can find this in the workspace->'Invite people to gridstackjs' -> 'Copy link below'. 🤟🏾

**Comment by jonathancounihan** [comment]
+1 please. I have a few questions as well, and I would like to join the slack workspace before creating issues.
The invite code I found in the repo has expired: 
https://github.com/gridstack/gridstack.js/blob/47b3992874d6feef739a273fc7bcb4ae81d8cd6e/demo/website.html#L114

**Comment by adumesny** [comment]
https://join.slack.com/t/gridstackjs/shared_invite/zt-1hb1k3mhh-WR6YyYjkUbMw7J6RqDwPRQ

but that's for 30 days. never heard of having to create an invite. it's open and anybody can register on their own (unless there is a limit for free account we're reached)
