### ISSUE TITLE
[Vue 2] - addWidget with Vue components

### ISSUE THREAD

**Issue by luisampuerovalenzuela** [gridstack/gridstack.js#2060]
## How correctly add a widget with a Vue Component
Hello, I have been struggling with add Vue components to the grid. I have a code that add the element to the grid, but this have not gridstack redimension or drag/drop.

## Your environment
gridstack.js: 6.0.2, jquery: 3.6.0
browser: Google Chrome, OS: Mac Big Sur version 11.6.1
Vue: 2.6.10

## Steps to reproduce
This is my code:
```
addNewWidgetToGrid(container) {
      const App = Vue.extend(AppFloating);
      const instance = new App({ store: this.$store });
      const options = {
        container,
        appType: container.appType,
        appsEditable: true,
      };
      const props = Vue.observable({
        ...instance.props,
        ...options,
      });
      instance._props = props;
      const mountedInstance = instance.$mount();

      window.grid.addWidget(mountedInstance.$el, {
        x: container.position.x,
        y: container.position.y,
        w: container.position.w,
        h: container.position.h,
      });
},
```

## Expected behavior
Here you can see the elements in the browser:

<img width="362" alt="image" src="https://user-images.githubusercontent.com/96737011/194097012-a547526d-e4ab-4a72-8712-966f85419e84.png">

The list until the 149 element is correct, because I have added this ones through html like this:
```
<section
  class="grid-stack"
  id="wrapper-grid"
>
  <div
    v-for="(container, index) in appContainersFiltered"
    :key="index"
    :gs-x="container.position.x"
    :gs-y="container.position.y"
    :gs-w="container.position.w"
    :gs-h="container.position.h"
    :id="container.id"
    class="grid-stack-item"
  >
    <app-floating
      :id="container.id"
      :container="container"
      :app-type="container.appType"
      :apps-editable="appsEditable"
      :is-new="container.app ? container.app.isNew : false"
      class="grid-stack-item-content"
    />
  </div>
</section>
```
All this elements have a correct behavior, so if I refresh the page after adding the element through .addWidget all seems good.

## Actual behavior
This is what have the correct ones elements:
<img width="495" alt="image" src="https://user-images.githubusercontent.com/96737011/194097788-ae7a54b2-133a-4e53-aeba-d175981e13bd.png">

And this the added with addWidget method:

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/96737011/194098184-aaa7134e-59bb-4477-92fe-92eec7923397.png">

I have already tried multiple solutions on internet and issues but I have never could add a widget through this way with my components and have redimension or movility in Widgets, unless I refresh the page 🤔

**Comment by adumesny** [comment]
this is not a lib bug (from glance), there are posted examples on how to use Vue https://github.com/gridstack/gridstack.js/blob/master/demo/
