### ISSUE TITLE
how can I generate a sub-grid in html directly

### ISSUE THREAD

**Issue by ZOUJIELynn** [gridstack/gridstack.js#2071]
<div class="grid-stack">
     <div class="grid-stack-item">
       <div class="grid-stack-item-content">
           normal content
        </div>
     </div>
     <div class="grid-stack-item">
       <div class="grid-stack-item-content">
          <div class="grid-stack"></div>
        </div>
     </div>
</div>

For Example,  I want to use the structure before to generate a sub-grid, but it seems not work
what do I need to do ?

**Comment by adumesny** [comment]
nest the dom stuctures like they are at runtime. if it doesn't load, file a bug with running example.
