### ISSUE TITLE
Dragging node not activating scrolling inside container

### ISSUE THREAD

**Issue by TheAndre980** [gridstack/gridstack.js#2074]
## Subject of the issue
I want to use gridstack in a small dialog on a angular project but the dialog does not scroll when needed.

## Your environment
Project in angular 14
Gridstack version: gridstack 7.0.0 (also tested with 6.0.1)
Browser: Google chrome 105
OS: Windows 10

## Steps to reproduce
Just drag a node on the edge of the container and then at the edge of the page.
https://jsfiddle.net/aypdz1ex/

## Expected behavior
Dragging node on the edge of container makes the container scroll

## Actual behavior
Only scrolls with a node on the edges of page/window.

**Comment by adumesny** [comment]
wonder if that works in v5 (h5 or jq version)... likely dup of #2032 #1905

**Comment by TheAndre980** [comment]
> wonder if that works in v5 (h5 or jq version)... likely dup of #2032 #1905
I think it works on jq version.

I dont' think it's a duplicated since the container just doesn't scroll while on the edge of the container but on the edge of the page does...

**Comment by insilications** [comment]
Weeks ago I probably had this same problem. have you checked the overflow css style in your container/body? Using anything else other than auto broke the autoscrolling it seemed. I was using the latest es6 version (7.0~)

**Comment by TheAndre980** [comment]
> Weeks ago I probably had this same problem. have you checked the overflow css style in your container/body? Using anything else other than auto broke the autoscrolling it seemed. I was using the latest es6 version (7.0~)

Container has overflow:auto
It's a dialog with a fixed height

**Comment by adumesny** [comment]
please run the v5 jquery version and let me know if auto scrolling works there - if it does then *maybe* I can make it work (I use different style of the dragged object to work with nested grid, unlike jq which always clipped incorrectly...

**Comment by TheAndre980** [comment]
> please run the v5 jquery version and let me know if auto scrolling works there - if it does then _maybe_ I can make it work (I use different style of the dragged object to work with nested grid, unlike jq which always clipped incorrectly...

The auto-scrolling while dragging item works well in the v5 jquery version

**Comment by TheAndre980** [comment]
@adumesny Is there any prediction to fix this in the near future ?

**Comment by adumesny** [comment]
Note: you need `float:true` to drag and scroll (or resize past down otherwise which does work in both case) to move them below.

**Comment by adumesny** [comment]
fixed in next release
