### ISSUE TITLE
Vue reactivity (feature request)

### ISSUE THREAD

**Issue by stephenjason89** [gridstack/gridstack.js#2076]
It would be nice to have the grid react to vue reactive changes like v-for

gridstack v7.0

## Steps to reproduce
1. Create a vue app
2. Do a v-for loop
<img width="607" alt="image" src="https://user-images.githubusercontent.com/3810177/195393098-35872d70-7a2d-4c63-824e-429ecd4f3960.png">

3. In the given example, push another item here activeCollection.charts
4. It will rerender everything but the last item is not in the grid

Temporary fix:
I just destroy the grid and re initialize the grid everytime there's a new item in activeCollection
<img width="666" alt="image" src="https://user-images.githubusercontent.com/3810177/195393426-267eac2f-4269-4813-ba34-afd076c970d0.png">

I know that there's 
    grid.addWidget({w: 2, content: 'item 1'});
But it would be better to have it react to data changes

**Comment by adumesny** [comment]
use makeWidget()/removeWidget() after the dom item is created instead

**Comment by stephenjason89** [comment]
@adumesny Thank you, i did look at makeWidget. 
For me to be able to use makeWidget, I would have to watch for the changes in activeCollection then call makeWidget(el).
I also need to put an id to it so i can getElementById or something else to be able to pass the element in makeWidget.

Then i would have to handle removingWidget, for me personally, It is much easier to just destroy and reinit the grid.
This even becomes more complex if you are not just adding and removing stuff in activeCollection but completely changing the collection itself.

**Comment by adumesny** [comment]
| (but i believe this is not required in vue because the element is being removed by vue already)

but the grid would still have an internal description of that item (node pointing to the removed dom element as well) so yes you need to tell it too.

How would you suggest the grid would detect items being added/removed and automatically do the right thing ? I'm not even sure how to tackle this...

**Comment by stephenjason89** [comment]
@adumesny In vue, we can make composables and have watchers to trigger side effects. I am not so certain how to implement this here though.

**Comment by adumesny** [comment]
and in Angular there is also a way to trigger when DOM items you are watching changes... just don't know if there is such a thing in plain HTML/TS
