### ISSUE TITLE
[Method is not defined in nested demo]

### ISSUE THREAD

**Issue by luisampuerovalenzuela** [gridstack/gridstack.js#2077]
Hello,

I have been trying to use your new demo but my console get an undefined error for addEvents.

https://github.com/gridstack/gridstack.js/blob/5bb583bcb53a957256cbd3dc29943a7026c05795/demo/nested.html#L66

Regards and thanks in advance

**Comment by adumesny** [comment]
https://gridstackjs.com/demo/nested.html works just fine for me. 

you must be running out of the source tree or something ?
