### ISSUE TITLE
Set `license` of `package.json` to MIT?

### ISSUE THREAD

**Issue by WarheadsSE** [gridstack/gridstack.js#2086]
## Subject of the issue

The `package.json`'s statement of [license](https://github.com/gridstack/gridstack.js/blob/master/package.json#L54) is set to `see GridStack root license`. This causes issues with dependency license validation, such as [used by GitLab](https://docs.gitlab.com/ee/user/compliance/license_compliance/)'s CI automation.

The official [specification for `license`](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#license) indicates several methods, to be used in the event that there is not already an associable SPDX license ID that applies. This includes indicating explicitly _where_ to find the license content that applies to the code.

The [LICENSE](https://github.com/gridstack/gridstack.js/blob/master/LICENSE) file clearly indicates that this package has been MIT for years. The change was placed within `v4.0.1` ([this commit](https://github.com/gridstack/gridstack.js/blob/v4.0.1/package.json#L49)), but we have been unable to locate any specific reasoning for this phrase.

Can we set this back to `MIT`?

## Expected behavior

`license` matter is clear.

## Actual behavior

`license` matter is non-deterministic.

**Comment by adumesny** [comment]
hey thanks for the detail reporting. I had plan to take this lib commercially but haven't done yet. so will restore package fields.
