### ISSUE TITLE
disable/enable method is not recursive

### ISSUE THREAD

**Issue by ptorrent** [gridstack/gridstack.js#2105]
Hello !

It seems that disable/enable method is not recursive ?

If I call thoses methods on the main grid, subgrid will not be affected. 

```
grid.enable()
grid.disable()
```

Maybe i'm doing something wrong ?

Thanks

**Comment by ptorrent** [comment]
yes, It's what I was thinking. Actually I'm doing it manualy.

Thanks for your answer !

**Comment by adumesny** [comment]
turns out not trivial as I also need to update enableMove(), enableResize(), setStatic() as well to deal with recursions... so 5+ methods. agrr.

**Comment by adumesny** [comment]
fixed in next release.
