### ISSUE TITLE
itemClass Causes Malformed Item

### ISSUE THREAD

**Issue by jasondalycan** [gridstack/gridstack.js#2110]
When dropping a widget into a grid, setting itemClass causes the dropped widget to land at the top of the grid and the widget becomes malformed.  For example, the following grid does this:

```
let myGrid = GridStack.init(
            {   acceptWidgets: ".my-widget-class",
                itemClass: "my-widget-class-with-gridlines"
            }, document.querySelector(`#myCanvasId`));
```

The class contents are simple:

```
.my-widget-class-with-gridlines
{
    border: 1px dotted #cccccc;

}
```

Removing the itemClass parameter from GridStack.init() resolves the issue, and adding it back causes the issue again.

**Comment by adumesny** [comment]
can you post a running example (use bug template please).

**Comment by adumesny** [comment]
fix in next release - pease donate if oyu find this lib useful!
