### ISSUE TITLE
Ubuntu + Chrome: Dragging allow to drop item on top on another one

### ISSUE THREAD

**Issue by almond-qms** [gridstack/gridstack.js#2117]
## Using the dragging function allow to drop item on top another
When trying to drag-in new item on the first drag the item not "pushing" the other item and allowed to drop on top of exiting element, after first dropped it work fine. 
This video take from the original example: https://gridstackjs.com/demo/web2.html
https://user-images.githubusercontent.com/26832894/209536171-a169869f-e025-4615-84ff-3b15a72829b1.mp4

## Same environment of demo site
https://gridstackjs.com/demo/web2.html
* Using chrome 108
* Using ubuntu 22.04

## Steps to reproduce
https://gridstackjs.com/demo/web2.html
See the video above

## Expected behavior
On first drag the item will behave in the same way as allways

## Actual behavior
On the first drag item is not pushing the other elements and allow to be dropped on top of other items

Thanks

**Comment by adumesny** [comment]
I'm not able to see this issue using Chrome 108 as well but on windows - either it's an issue with ubuntu (which I don't have access to) or maybe you have installed some extension that somewhow messes with raw mouse events in the browser...

can you try another browser and/or disable all extrension to see ?

**Comment by almond-qms** [comment]
Looks like you're right.
It works fine in windows.
It works fine on Ubuntu with Firefox.
But Ubuntu and Chrome also without add-ons,
Both in incognito and as a guest user, both without add-ons, it doesn't work.

**Comment by adumesny** [comment]
so you're saying it only breaks Ubuntu + Chrome + no adds on (either incognito or guest - which shouldn't matter).
it's gonna be hard to debug this for me... would be good to hear others having this issue and not your setup somehow...
