### ISSUE TITLE
Reload DOM based grid items

### ISSUE THREAD

**Issue by jfrs** [gridstack/gridstack.js#2145]
I use Vue to show/hide components based on filtering an array, and so far the best approach I've found is to use the DOM created items. My template looks like this:
```vue
  <div class="grid-stack">
    <div
      v-for="item in items"
      :key="item.id"
      class="grid-stack-item"
      :gs-id="item.id"
      :gs-x="item.x"
      :gs-y="item.y"
      :gs-w="item.w"
      :gs-h="item.h"
      :gs-min-w="item.minW"
      :gs-min-h="item.minH"
      :gs-max-h="item.maxH"
    >
      <MyComponentA v-if="item.id === A" class="grid-stack-item-content" />
      <MyComponentB v-if="item.id === B" class="grid-stack-item-content" />
      <MyComponentC v-if="item.id === C" class="grid-stack-item-content" />
    </div>
  </div>
```
This works well, but the only way I have found in order to add/remove items is to wait for Vue to update the DOM based on the array, and then `destoy()` and `init()` the whole grid again.
This is fine, except the grid will scroll back to the top.

I've looked at `load` and `update` but only `init` seems to be able to manage DOM based items, is there a way to reload the grid based on the DOM without recreating it entirely?

**Comment by adumesny** [comment]
please move this discussion to the slack channel for others to see/comment.
