### ISSUE TITLE
Nested-Grids: grid.save() and grid.load() behaviour 

### ISSUE THREAD

**Issue by mbsouth** [gridstack/gridstack.js#2171]
## Subject of the issue
A grid is stored as an object using grid.save() for further use. If the same grid is reloaded with grid.load() and then saved again, the object grows recursively, even if no changes have been made to the grid.
This happens with nested grids and gets worse with nested-nested grids (subGridDynamic=true).

A working example is available here: [https://dev4.wdns.at/](https://dev4.wdns.at/)

This example is based on the original **Advanced Nested Grids demo**, which has been extended by two textareas - nothing else. 
The behavior I described can be understood by multiple save and load attempts and monitoring the content of the textareas. 

## Your environment
* Version of Gridstack: v7.01, HTML5
* Firefox v108, Chromium (ungoogled) v102

## Steps to reproduce
* Visit [https://dev4.wdns.at/](https://dev4.wdns.at/)
* Save / Load the grid multiple times
* Check the grid object (textarea)

## Expected behavior
Even with multiple save and load processes, only changes to the grid may be applied

**Comment by adumesny** [comment]
good find!

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful!

**Comment by mbsouth** [comment]
@adumesny 
Thanks for the quick bugfix. 
Unfortunately, the save/load behavior of nested-nested-grids has not improved. 
Attached an example that does not work (Gridstack demo/doc page):

![angrid-demo](https://user-images.githubusercontent.com/84234150/212955424-1a535a84-72a2-4048-a6c5-58ed4733f6f7.PNG)

**Comment by adumesny** [comment]
not sure what you are pointing to (image doesn't tell me the issue). I already spent more time on this than I have...
