### ISSUE TITLE
Can't easily drag widgets below widgets on the bottom border of a grid

### ISSUE THREAD

**Issue by derekm** [gridstack/gridstack.js#219]
Gridster pops a few blank rows at the bottom of a grid, making it easy for your drag to scroll the window downward. When a gridstack grid has filled the window, it is impossible to drag a widget below any widget that touches the bottom border. Turning on float causes drags to add extra rows as needed. With float off, it could do the same then let the block fall upward into position.

**Comment by svdb** [comment]
Just wrap your gridstack DIV inside a parent DIV, then give the parent DIV a padding-bottom >= the stackgrid row height.
So when you move a widget down you always have extra space and stackgrid will add a new row.

<div style="padding-bottom: 100px">
  <div class="grid-stack"></div>
</div>

**Comment by radiolips** [comment]
@derekm did adding padding work? It should. I'm closing this issue, but please feel free to reopen it if you still have a problem.

**Comment by frankadrian** [comment]
Hey @radiolips, This does not seem to work for items that are being dragged from another grid. I will try create a example for this!

**Comment by frankadrian** [comment]
The behaviour can be seen here: http://troolee.github.io/gridstack.js/demo/two.html

Try dragging an item from one grid below an item in the other grid!

**Comment by trongletps** [comment]
i had same issue with @frankadrian. When I set float equal false, to difficultly to drag the widget below one from the grid to the another grid.

**Comment by trongletps** [comment]
Everything work well except this case but it's very important with user experience, so uncomfortable when drag and drop item from sidebar to main grid (drag item from sidebar below the other items in main grid).

**Comment by stevenliebregt** [comment]
What is the status off this issue?

**Comment by adumesny** [comment]
see #1094 as well

**Comment by adumesny** [comment]
this might get fixed along #1001 as we will add an extra temporary row the moved/resized item is at the bottom.

**Comment by adumesny** [comment]
it is now possible, though a little rough with fix to #1001 to auto-scroll

https://user-images.githubusercontent.com/3496166/103484677-93d3b580-4da5-11eb-904f-02bff4e43eba.mp4

**Comment by adumesny** [comment]
should work a lot better now in next release.

we now automatically insert extra rows when dragging an item at the bottom below others to make it easier to insert below.

https://user-images.githubusercontent.com/3496166/113513223-708fe200-951d-11eb-967b-6ddd3670804e.mp4
