### ISSUE TITLE
Native Drag Events workaround 

### ISSUE THREAD

**Issue by QadiymStewart** [gridstack/gridstack.js#2199]
@adumesny 

When moving panels around, currently in Maui Blazor the ondrag/drag events are broken. Anyway to override your library to listen to on mouse move events as a workaround instead? Does gridstack v5 depend on the native browser drag events?

Maui Blazor 
https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/tutorials/maui?view=aspnetcore-7.0&pivots=windows

**Comment by adumesny** [comment]
I would mnot use v5 (draggable) but use the latest v7 which uses plain mouseevent and touchevent.
