### ISSUE TITLE
Safari mobile: Can not drag item between 2 grids

### ISSUE THREAD

**Issue by TrinhLe123** [gridstack/gridstack.js#2203]
## Subject of the issue
I tried to drag the item between 2 grids, but it didn't work in touch device
I tested in gridstack two grids demo

https://user-images.githubusercontent.com/47844727/216576025-7e026057-5dbe-421f-a0bc-48817797a093.MP4

## Your environment
* version of gridstack.js - latest version in gridstack demo page.
* Safari 12 / macOS 12.5.7

**Comment by adumesny** [comment]
yep, never got to test this as cell phone is too small for this and didn't have tablet available then to debug... bet we're not getting enter/leave events - we may have to do that intersection ourself...

Did you try chrome and does it behave the same way ?
would be interesting to see if the previous jquery-ui version v5 with touch events even supported that

**Comment by TrinhLe123** [comment]
Thanks for your response.
It also didn't work in chrome browser ( I used Ipad air to test).
Do you know any way that I can modify or make change so I can have it working for this case? Thank you.

**Comment by adumesny** [comment]
it's a big feature request at this point to support mobile dragging between grids/trash (i.e. do intesection and generate enter/leave events to use existing code path). If you're willing to donate I could add it.

**Comment by TrinhLe123** [comment]
Can you give me your contact info? I already sent an email to alaind831+github@gmail.com but didn't receive your reply yet.

**Comment by adumesny** [comment]
responded...

**Comment by adumesny** [comment]
this is yet another Safari only issue (I hate that browser). works totally fine in Chrome on Android as you can see the code was written to support enter/leave from the get go https://github.com/gridstack/gridstack.js/blob/master/src/dd-touch.ts#L171

Safari desktop didn't handle draggable well, one one the reason I went for plain mouse (and touch) events. now this... Agrrr.

**Comment by adumesny** [comment]
according to this https://stackoverflow.com/questions/27908339/js-touch-equivalent-for-mouseenter it should be fixed in iOS 13 - closing

----------
Works in Chrome at least. Not so much in Mobile Safari 13 beta though... According to the w3c specs, I'm fairly certain it should work this way. Maybe when iOS 13 is officially released we'll be in the clear. [I've filed a bug and looks like it's being attended to.]

[Update: iOS 13 issue fixed. Should work in Chrome/FF/Safari]

**Comment by adumesny** [comment]
don't forget to donate if you find this lib useful!
