### ISSUE TITLE
Verticalmargin is not available in Version 7. How to add space between the widgets 

### ISSUE THREAD

**Issue by lakshmi2716** [gridstack/gridstack.js#2204]
## Subject of the issue
Describe your issue here.
If unsure if lib bug, use slack channel instead: https://join.slack.com/t/gridstackjs/shared_invite/zt-1jobnclsy-FqGGeLX5dFPM_ZQzTunBsw

## Your environment
* version of gridstack.js - DON'T SAY LATEST as that doesn't mean anything a month/year from now.
* which browser/OS

## Steps to reproduce
You **MUST** provide a working demo - keep it simple and avoid frameworks as that could have issues - you can use 
https://jsfiddle.net/adumesny/jqhkry7g

## Expected behavior
Tell us what should happen. If hard to describe, attach a video as well.

**Comment by adumesny** [comment]
it's called 'margin' - and next time use slack to ask Q
