### ISSUE TITLE
Vue3 demo issue

### ISSUE THREAD

**Issue by Zen33** [gridstack/gridstack.js#2215]
Page url: https://gridstackjs.com/demo/vue3js_v-for.html

When I add two grids, then remove one of them, the rest could not draggable.

**Comment by Zen33** [comment]
I add await nextTick() after "items.value.splice(index, 1);", then it works.

**Comment by adumesny** [comment]
can you please update the demo. thanks.

**Comment by Zen33** [comment]
After trying several times, I resume that current version is not compatible with vnode lib.

**Comment by adumesny** [comment]
of course it is. there are plenty of people who use it - just need to call the right API...
