### ISSUE TITLE
Thank you for all your hard work!!!!!

### ISSUE THREAD

**Issue by artknight** [gridstack/gridstack.js#2216]
## Subject of the issue
I have selected GS for this project due to some very steep requirements for the layout builder. I must admit that GS has delivered on the expectations and more. So, I just wanted to take a moment and say a big THANK YOU to @adumesny and the rest of the amazing contributors of this project!!!!!

I am leaving you with this tiny video of how I am using GS to get the job done :)

https://user-images.githubusercontent.com/157762/219694558-e77699b5-ff02-447e-a152-0fd1657de4ab.mp4

**Comment by adumesny** [comment]
looks great! thanks for the kinds word, and don't forget to donate to help it!
