### ISSUE TITLE
Collapse only empty rows

### ISSUE THREAD

**Issue by ivanatreblle** [gridstack/gridstack.js#2217]
## Grid options
I made a grid that functions the same as this demo: https://gridstackjs.com/demo/column.html

These are my options: 
`var grid = GridStack.init({`
`	width: 12,`
`	column: 3,`
`	disableResize: true,`
`	dragOut: false,`
`	handle: '.widget-drag',`
`	cellHeight: 390,`
`	float: true,`
`	marginBottom: 50,`
`});`

### Environment
* version of gridstack.js - 7.2.3
* which browser/OS - Any/Any

## Goal
After `dragstop()` or  `removeWidget()` I need to check for empty rows and if any are found move up widgets so the gap is closed.
I dont want to use `compact()` as that would tighten everything up.

### Changing the Attribute
I have tried changing the attribute `gs-y` to move it up a row but grid didnt know about the change, which opens the possibility to put one widget over the other. So the grid layout needs to be updated.

### Remove and Re-add Widget
I tried removing the widget and then adding it again and it works perfectly as long as all widgets have the height of 1. 
Taller widgets bring utter chaos to my grid, as one cant move them up at all and instead they end up one row below from starting point.

### Methods That Might Update the Grid Layout
I tried `save()`, `load()`, `update()` and `batchUpdate()` methods and none of them made a difference.

**Any ideas on what might work?**

**Comment by adumesny** [comment]
please use slack for questions. did you try turning float true which will move things up and take any empty space back, without reordering things unlike compact() ?

**Comment by ivanatreblle** [comment]
Float is already set to true, yes. If I turn it to false, everything will move up and I don't want that. I just need the empty row to collapse.

**Comment by adumesny** [comment]
you need to provide running code showing the issue then - should work.

**Comment by ivanatreblle** [comment]
### With the _options from the first post_ here is my first try:

	grid.on('dragstop', function (event, ui) {
		// Get number of rows and cols
		var numRows = grid.getRow();
	
		var numEmptyRows = 0;
		var currentIsTall = false;

		// Find the empty row and collapse it
		for (var i = 0; i < numRows; i++) {
			var currentRow = $(".grid-stack-item[gs-y=" + i + "]")

			if($(".grid-stack-item[gs-h=2][gs-y=" + i + "]").length > 0) {
				currentIsTall = true;
			}

			if(numEmptyRows > 0){
				$.each(currentRow, function(index, val) {
					var el = $(this);
				
					el.attr("gs-y", i-numEmptyRows);
					el.data("gs-y", i-numEmptyRows);
				})
			}
			
			//if a row is empty increment numEmptyRows
			if(currentRow.length < 1) {
				if(currentIsTall) {
					currentIsTall = !currentIsTall;
					break;
				}
				numEmptyRows++;
			}
		}

	});

This produced a result that seemingly works, but the 'grid' doesn't know about the change in layout.

My tries with:

			if(numEmptyRows > 0){
				$.each(currentRow, function(index, val) {
					grid.removeWidget(val);
					grid.addWidget(val);
				})
			}
Work only if all of the widgets have height of 1. Taller widgets just get thrown to the bottom.

I tried `grid.save();` with no effect whatsoever.

The closest I got to my goal was with this:

	grid.on('dragstop', function (event, ui) {
		// Get number of rows and cols
		var numRows = grid.getRow();
	
		var numEmptyRows = 0;
		var currentIsTall = false;

		// Find the empty row and collapse it
		for (var i = 0; i < numRows; i++) {
			var currentRow = $(".grid-stack-item[gs-y=" + i + "]")

			if($(".grid-stack-item[gs-h=2][gs-y=" + i + "]").length > 0) {
				currentIsTall = true;
			}
			
			//if a row is empty increment numEmptyRows
			if(currentRow.length < 1) {
				if(currentIsTall) {
					currentIsTall = !currentIsTall;
					break;
				}
				numEmptyRows++;
			}
		}

		
		// if empty rows were found
		if(numEmptyRows > 0){
			grid.float(false);
			grid.float(true);
		}
	});

But that is still not the desired effect, because I need to keep the layout as it is, except for the empty row.

**Comment by adumesny** [comment]
please post a running jsfiddle example as the bug form requires. I don't have time recreating bugs for people..

**Comment by ivanatreblle** [comment]
Sure.

1. The one where `gs-y` gets changed, _but grid didnt know about the change, which opens the possibility to put one widget over the other_: https://jsfiddle.net/rkwn71pf/
2. The one where widgets gets removed and added again to update the grid, _but layout gets reordered randomly_: https://jsfiddle.net/n5akx718/
3. And the closest working one, but it will not only collapse an empty row, _it will bring a block all the way up which is not wanted_: https://jsfiddle.net/k06274a9/

**Comment by adumesny** [comment]
1. is not a bug, never worked that way. you are supposed to call `update()` as we don't track DOM changes - suppose we could but never have

**Comment by adumesny** [comment]
@austinwbest if you are willing to pay for it, it can be added....

**Comment by austinwbest** [comment]
It isnt as efficient as it could be i'm sure since i dont know this library and code well but others might find it useful and can improve on it if they choose. Works well enough and saves the next person time/money on it.

```
GridStack.prototype.compactEmpty = function() {
    //-- Get all the unique rows
    let rowsWithData = [];
    $.each(this.engine.nodes, function(){
        if (rowsWithData.includes(this.y)) {
            return;
        }

        rowsWithData.push(this.y);
    });

    //-- Find any rows that are skipped (an empty row)
    let emptyRows = false;
    for (let i = 0; i < rowsWithData.length; i++) {
        if (rowsWithData.indexOf(i) == -1) {
            emptyRows = true;
        }
    }

    if (!emptyRows) {
        return this.engine;
    }

    //-- Re-index the y to remove the empty row
    for (let r = 0; r < rowsWithData.length; r++) {
        $.each(this.engine.nodes, function() {
            if (this.y == rowsWithData[r]) {
                this.y = r;
            }
        });
    }

    //-- Rebuild the grid, similar to compact()
    let copyNodes = this.engine.nodes;
    this.engine.nodes = [];
    copyNodes.forEach(node => {
        this.engine.addNode(node, false);
        node._dirty = true;
    });

    return this.engine.batchUpdate(false); 
};
```

**Comment by adumesny** [comment]
yep, not only very inefficient (touches every items, re-adding them) but also doesn't take h into account. anyway glad it works enough for you...
