### ISSUE TITLE
ne nw resize handle

### ISSUE THREAD

**Issue by mdellanave** [gridstack/gridstack.js#2223]
It's me or there's an issue displaying the upper resize handles?

https://codesandbox.io/s/frosty-snow-hs48oq?file=/index.html

If I use
```
resizable: {
    handles: "all"
  }
```
I can see only the bottoms left and right; Am I missing something?

**Comment by adumesny** [comment]
never rendered upper resize (that I recall) as resize top used to be very wonky - it works (but also moves) now.

**Comment by mdellanave** [comment]
ah ok, I noticed that the resize works in the upper corners and to me it works fine, the handles exists in the dom so it miss only the css style to show the double arrows.
I would like the upper arrows to be shown as well if enabled from the options (as active in the dom)

Thank you for your quick answer  @adumesny

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful.
