### ISSUE TITLE
one column mode initial sorting problem

### ISSUE THREAD

**Issue by NicolasVI2** [gridstack/gridstack.js#2224]
## Subject of the issue
Hello,

Left to right sorting doesn't work when starting in "one column mode". 
See jsfiddle, the first Item ( 6 height ) should be normally the first displayed if sorting is from left to right. 
Thanks for job !

Best regards,

Nicolas

## Your environment
gridstack 7.2.3
debian

[## Steps to reproduce

https://jsfiddle.net/2q40n7u6/

## Expected behavior

Normally the items should be displayed in the same order as the initial array object.

Thanks a lot

**Comment by adumesny** [comment]
picture looks right to me (6x6 at (0,0) and (6,4) - and I don't know what you mean by sorting... youa re the one creting the objects one at a time (really should do a load() or batch() your calls,a nd use w/h instead in the array to pass.
Also for bugs demo it helps to have content in each cell, and ideally not use a framewrok (jq).

Closing unless you can show the issue.

![image](https://user-images.githubusercontent.com/3496166/223469807-07827042-85b2-417c-be47-632d2b7a3086.png)

**Comment by NicolasVI2** [comment]
Thanks for reply. If you start it in one colomn mode,  sorting is not ok ( see screenshot below )  But if you start in full screen and then reduce to one column, sorting is ok. In the screenshot below you can see the first item is not the big one (6 height )

![image](https://user-images.githubusercontent.com/90465633/223477546-51015a76-f53d-42b6-a191-156a89b19f0c.png)
