### ISSUE TITLE
Drag Item not automatically adding to array list

### ISSUE THREAD

**Issue by ronnybaba** [gridstack/gridstack.js#2226]
Drag Item not automatically adding to array list
Describe your issue here.
https://angular-ivy-xefl3n.stackblitz.io/
can anyone please tell me why array is not updating after dragging the wid 1 and wid 2 ? 

## Your environment
* version of gridstack.js - 7.2.3
* which browser/OS - Chrome

## Steps to reproduce
You **MUST** provide a working demo - keep it simple and avoid frameworks as that could have issues - you can use 
https://angular-ivy-xefl3n.stackblitz.io

## Expected behavior
{x: 0, y: 0, w: 2, h: 2, content: 'wid 1'}

array to get this record when i drag new item into dashboard

**Comment by lucasquin** [comment]
Your gridstack version is 4.2.6 in the available demo

**Comment by adumesny** [comment]
thanks @lucasquin - closing due to old rev.
