### ISSUE TITLE
Slack link leads to private slack instance

### ISSUE THREAD

**Issue by busti** [gridstack/gridstack.js#2230]
The slack link in the readme does not allow me to join. Upon entering an email-address I get an email telling me that I do not have an account on that slack instance and that I cannot join. The privacy settings are probably at fault.

**Comment by fredericrous** [comment]
Actually when you create a new issue, the issue template reference the correct link to join slack. I opened this PR to put the link on the readme https://github.com/gridstack/gridstack.js/pull/2233
