### ISSUE TITLE
Can't set an id to a widget through setupDragIn

### ISSUE THREAD

**Issue by fredericrous** [gridstack/gridstack.js#2231]
## Subject of the issue
I rely deeply on grid stack IDs (gs-id), I need a way to track the widgets

## Your environment
* gridstack version: v7.2.3

## Steps to reproduce

Here is my helper function:

```js
 GridStack.setupDragIn('.gridstack-add-widget', {
      appendTo: '.gridstack-widget-dragged',
      helper: function (event: Partial<DragEvent>) {
        const id = nanoid();
        // ...
        // some code to store metadata of a widget based on its id
        // ...
        const target = event.target as GridItemHTMLElement;
        const clone = Utils.cloneNode(target.parentElement!);
        clone.setAttribute('gs-id', id);
        return clone;
      },
    });
```

## Expected behavior
I expect to set an id with `GridStack.setupDragIn` function

**Comment by fredericrous** [comment]
actually I spent an hour yesterday on this and got it working in few minutes this morning

```ts
 GridStack.setupDragIn('.gridstack-add-widget', {
      appendTo: '.gridstack-widget-dragged',
      helper: function (event: Partial<DragEvent>) {
        const id = nanoid();
        const target = event.target as GridItemHTMLElement;
        const correctTarget = target.parentElement!.classList.contains('grid-stack-item-content') ? target.parentElement!.parentElement! : target.parentElement!;
        correctTarget.setAttribute('gs-id', id);
        const clone = Utils.cloneNode(correctTarget);
        return clone;
    },
});
```

**Comment by adumesny** [comment]
actually if you care about id (as you should) set the initial gs-id (or id optoin when creating from json) and NOT when the drag happen. the node gs-is is ONLY the dom used for layout. the internal node.id is what is used during actual code collision...

and next time post a slack question - this isn't a lib bug per say.

**Comment by fredericrous** [comment]
I didn't understand :/  Let me give more details on the use case:
- I have a grid that has been created via JSON, each tiles has IDs
- I drag a tile that is outside of the grid into the grid
- the tile gets added with an ID I chose. Choosing the ID beforehand is handy because I manage in parallel a datastructure outside gridstack

@adumesny I tried to connect to slack. But I couldn't, I'm getting the same issue as https://github.com/gridstack/gridstack.js/issues/2230

**Comment by adumesny** [comment]
don't have time to read this now... re-opening so I can check later.

**Comment by adumesny** [comment]
ok, I've taken the time to take a look... the clone should be used for creating the constrain (agree it's cleaner to set on clone rather than original master item) and it should also insert that content as is (with some check for required .grid-stack-item + .grid-stack-item-content)

won't be small change and might break some user who were working around the issue...
