### ISSUE TITLE
GridStack autoposition bug with version > 7

### ISSUE THREAD

**Issue by stephenjason89** [gridstack/gridstack.js#2232]
## Your environment
* version of gridstack.js -7.2.3
* which browser/OS microsoft edge macos

## Steps to reproduce
Create this a grid-stack with grid-stack-item

like this
<img width="1384" alt="image" src="https://user-images.githubusercontent.com/3810177/225865009-62e19223-2215-445a-9368-f921b7a42d76.png">

notice the last div with id='Products' it has no gs-x or gs-y props

then call 
```
GridStack.init(
{	cellHeight: 240,
	styleInHead: true,
	margin: '2.5px'
})
```

You will notice that instead of placing the div with id='Products' beside div with id='Inventory Stock Value', 
It places it on the next row. Like so
<img width="1690" alt="image" src="https://user-images.githubusercontent.com/3810177/225866590-75293ed2-5ce9-490c-91b1-2598a28a0c26.png">

I downgraded to vs 6.0.3 for the meantime which fixes this issue

## Expected behavior
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/3810177/225866411-85db2af9-1016-416e-8ac2-090f1ab124b5.png">

**Comment by fredericrous** [comment]
I remember I seen this bug as well at some point when I was playing with gridstack and media queries.
just throwing a question to maybe help narrow the issue: do you have a custom number of columns?

**Comment by stephenjason89** [comment]
@fredericrous hello thanks for looking in to this.
No I don't,
I only have these in my gridOptions
```
{	cellHeight: 240,
	styleInHead: true,
	margin: '2.5px'
}
```

**Comment by adumesny** [comment]
please post a bug with a simple running example as the template requires... do't expect me to crete one for you, then fix any issues...

**Comment by stephenjason89** [comment]
@adumesny sorry about that.
Here's a stackblitz
https://stackblitz.com/edit/nuxt-starter-weppuk?file=app.vue
Press the add button and you'll see what is happening.
Downgrade to 6.0.3 to see the correct behavior.

Also, you'll notice that i do dynamic import
const { GridStack } = await import('gridstack')
in my local project, it throws me an error during serverside rendering if i import like
import {GridStack} from 'gridstack'


Thank you so much

**Comment by adumesny** [comment]
will have to dup this in a simple js example. you are destroying and recreating the grid, which is odd. makeWidget() or load() is what you should call instead...

**Comment by ildarkayumov** [comment]
Hello
I had the same issue - https://jsfiddle.net/ildarkayumov/05Lthmpx/

<img width="790" alt="Monosnap gridstack js issue base - JSFiddle - Code Playground 2023-03-24 13-12-14" src="https://user-images.githubusercontent.com/1931756/227475910-bd7334ae-5a67-45b2-9388-72dd09058223.png">

As you can notice first 2 items (`1` and `2`) have `x` and `y` attributes but last one (`3`) does not have `x` and `y`. So I expected last item to appear on right after `2`. But something weird happens and `3` appears between `1` and `2`.

I investigated the problem a little bit and found that it started after these changes https://github.com/gridstack/gridstack.js/blob/master/src/gridstack.ts#L361

```js
this.getGridItems().forEach(el => { // get dom elements (not nodes yet)
  let x = parseInt(el.getAttribute('gs-x'));
  let y = parseInt(el.getAttribute('gs-y'));
  elements.push({
    el,
    // if x,y are missing (autoPosition) add them to end of list - but keep their respective DOM order
    i: (Number.isNaN(x) ? 1000 : x) + (Number.isNaN(y) ? 1000 : y) * column
  });
});
elements.sort((a, b) => b.i - a.i).forEach(e => this._prepareElement(e.el)); // revert sort so lowest item wins
```

So elements from example are eq to

<img width="628" alt="Monosnap gridstack js issue base - JSFiddle - Code Playground 2023-03-24 13-28-44" src="https://user-images.githubusercontent.com/1931756/227480554-11538a97-30d3-429c-9483-a1b8777ded38.png">

`this._prepareElement` calls `this.engine.addNode` -> `this.engine.findEmptyPosition` is called only for item `3` and is called before first 2 items are added to engine.nodes.

I resolved the problem with small 'hack' like here - https://jsfiddle.net/ildarkayumov/ruzc9g3x/
I added `gs-y="-1000"` to last element

<img width="786" alt="Monosnap gridstack js issue base - JSFiddle - Code Playground 2023-03-24 13-36-33" src="https://user-images.githubusercontent.com/1931756/227482594-e112c26a-ffaa-47ec-b330-ae462505042d.png">


that allows to make calculated `i` for last elemet to be eq `1000 + -1000 * 12 = -10000`

**Comment by adumesny** [comment]
thank you @ildarkayumov that example makes it easy to debug and fix now https://jsfiddle.net/adumesny/yt4ghjdn/

**Comment by stephenjason89** [comment]
> will have to dup this in a simple js example. you are destroying and recreating the grid, which is odd. makeWidget() or load() is what you should call instead...

Oh, i believe it is due to Gridstack not being able to detect vue 3's reactive v-for changes.
https://github.com/gridstack/gridstack.js/issues/2076

Thank you for providing a better example @ildarkayumov

**Comment by adumesny** [comment]
fixed in next release - this turned out to be more work than I expected as I need to make sure loading into 1 or 12 column acted the same, and bunch of new stuff needed to happen.

don't forget to donate if you find this lib useful!

**Comment by stephenjason89** [comment]
Thank you @adumesny 
Will do.
