### ISSUE TITLE
Placeholder doesn't move while dragging an item over large items

### ISSUE THREAD

**Issue by ruslauz** [gridstack/gridstack.js#2237]
## Subject of the issue
While dragging an item over large items either vertically or horizontally the placeholder doesn't move

https://jsfiddle.net/sergeifomin/3j5f80bm/

## Your environment
* GridStack 7.2.3
* MacOs 13.0/Chrome Version 110.0.5481.177 (Official Build) (arm64)

## Steps to reproduce
Drag a small item over a big one. The placeholder appears above or below the big item but it does not move while the small item moves on.

### Horizontally
https://user-images.githubusercontent.com/59659358/227304351-5f13ca50-5c5d-434e-98e5-a4b4d399449c.mp4

### Vertically
https://user-images.githubusercontent.com/59659358/227314901-588805a9-049b-4e0f-8645-dfc8bc01aaf5.mp4

## Expected behaviour
Drag a small item over a big one. The placeholder appears above or below the big item and it also moves while the small item moves on.

I have slightly updated the method `moveNode()` (lines 65-72) of the GridStack engine class to achieve such kind of behaviour, but I don't know whether it is the right way or not. If it is ok, I may propose a PR with that.

https://jsfiddle.net/sergeifomin/wsh4mnf9/

### Horizontally
https://user-images.githubusercontent.com/59659358/227307926-822e203e-8f34-43fa-8027-fd2968f837c4.mp4

### Vertically
https://user-images.githubusercontent.com/59659358/227315450-f88011c3-93d4-4297-9b10-f6a8cfb85bdb.mp4

**Comment by adumesny** [comment]
yeah seems like a resonnable thing, please submit a PR so I can take a look at the code. thanks.

**Comment by ruslauz** [comment]
> yeah seems like a resonnable thing, please submit a PR so I can take a look at the code. thanks.

Done

**Comment by adumesny** [comment]
the root cause is actually #1677 (need to pass 50% point to collide) and fact we don't try sliding (keep same Y, new X) as you are over the large item...

this is a harder fix to correctly fix it. thanks for trying.

**Comment by ruslauz** [comment]
> 

Hi, @adumesny. Will you fix it yourself then or should I keep trying to find the right solution?

**Comment by adumesny** [comment]
@ruslauz I don't have the bandwidth right now to look at it, so it may take a while... if you need it sooner, I would look into making sure 50% boundary of the large one, OR 90%+ of the small one to start collision should work.

**Comment by adumesny** [comment]
Or you can donate to have to fixed correctly
