### ISSUE TITLE
responsive dynamically 

### ISSUE THREAD

**Issue by ptorrent** [gridstack/gridstack.js#2248]
Hello !

Is there a way to recompute oneColumnSize  manualy ? Seems that if I'm on big window size > 768 and I resize it to a small one < 768 oneColumnSize  is ignored.

How can I make the grid responsive dynamically ?

**Comment by adumesny** [comment]
this isn't a proper bug without running example. works fine for me 
![image](https://user-images.githubusercontent.com/3496166/229248599-2241377c-f780-4830-9461-6b2d066483fd.png)
![image](https://user-images.githubusercontent.com/3496166/229248632-2b157d22-10a4-46b0-89d6-eced06259a31.png)

**Comment by ptorrent** [comment]
Yes it's working only if you resize the window. But if you resize the parent div, witch method do I have to call ?
