### ISSUE TITLE
About makeWidget method change gs-x attribute with a value of 0

### ISSUE THREAD

**Issue by MapleWithoutWords** [gridstack/gridstack.js#2262]
## Subject of the issue
I add a element to gridstack and use 'makeWidget' method add to gridstack's nodes.  my added's element 'gs-x' attribute with a value of 4, but it change 0 after calling the 'makeWidget'. (remark: I disable gs-auto-position.)
But I don't want it to change the value of my gs-x attribute.

## Your environment
* version of gridstack.js - 7.2.1
* chrome 111.0.5563.148

## Expected behavior
I don't want it to change the value of my gs-x attribute.

**Comment by adumesny** [comment]
post  a running re-produceable test as the bug template asks for.

**Comment by adumesny** [comment]
closing due to lack of response
