### ISSUE TITLE
Cannot read properties of undefined (reading 'gridstackNode')

### ISSUE THREAD

**Issue by AdamGold** [gridstack/gridstack.js#2264]
## Subject of the issue
Hey folks! 👋🏽 
I am using gridstack with React, and everything is working beautifully, except one thing: while an input box is focused, trying to drag widgets results in an error: `Cannot read properties of undefined (reading 'gridstackNode') at DDDraggable._mouseMove (dd-draggable.ts:200:1)`. These are the troublesome lines:
```javascript
    } else if (Math.abs(e.x - s.x) + Math.abs(e.y - s.y) > 3) {
      /**
       * don't start unless we've moved at least 3 pixels
       */
      this.dragging = true;
      DDManager.dragElement = this;
      // if we're dragging an actual grid item, set the current drop as the grid (to detect enter/leave)
      let grid = (this.el as GridItemHTMLElement).gridstackNode?.grid;
```

`this.el` is undefined for some reason - maybe it tries to get the input box? This is how it’s defined:
```javascript
      <div className="grid-stack-item-content">
        <div className="grid-stack-item-content__header">
          <span className="grid-stack-item-content__header__title">
            <input
              type="text"
              value={title}
              onMouseDown={(event) => {
                event.stopPropagation();
              }}
            />
          </span>
```

This is how the grid is initialized:
```javascript
      GridStack.init({
        handleClass: "grid-stack-item-content__header",
      });
```

Thanks!
## Your environment
* `"gridstack": "^7.2.3"`
* Chrome

## Steps to reproduce
1. Click on input box
2. Try dragging widgets

## Expected behavior
1. Click on input box
2. Try dragging widgets - it should drag

Thanks!

**Comment by adumesny** [comment]
please post a non react simple running example (see bug template) to debug this.

**Comment by adumesny** [comment]
closing since no response....

serialization.html works just fine with focus inside text field and dragging parent.
