### ISSUE TITLE
Offset between detached item and grid in Angular

### ISSUE THREAD

**Issue by dbvcode** [gridstack/gridstack.js#2277]
## Items biased to left when snapping and resizing

I'm using the `gridstack.component.ts` wrapper component as per the suggestion. 
I have isolated the component that works with stackgrid so it's not polluted by the app's css.
Also removed all the styles(Telerik Angular Kendo) from my app so I'm sure they are not doing weird stuff.
I'm importing `@import "gridstack/dist/gridstack.min.css";`

## Your environment
* version of gridstack.js - 7.3.0
* which browser/OS - Windows 11, Firefox and Chrome has same behavior
* Version of `gridstack` and `gridstack-item` is the one it was here, https://github.com/gridstack/gridstack.js/pull/2265

## Steps to reproduce
It happens when:
- I try to resize an item. The item gets pushed to the left as if it's been moved instead of just resized.
- I try to drag items. It seems that it takes more overlap to the right than to the left for the reordering to happen.

As you can see below, the item that's popped out of the grid is not aligned with it's 'shadow'(grid position)

I don't have a working demo just this gif of how things are working.
![firefox_jhkOFvQDXZ](https://user-images.githubusercontent.com/19186078/233937733-8c389921-eac0-4444-a709-a5a083f8334c.gif)

## Expected behavior
I would expect the grid to work as it does in the demo in the page where I can 'realign' the popped item over it's 'shadow'(current position in grid).

I would be very happy to be pointed in the right direction to where I might find the issue. I don't know if it's CSS, Angular or 
Gridstack code related.

**Comment by adumesny** [comment]
I can't do anything with this bug report... please make a simple running demo (like the many I have - no Angular needed) with the same layout (trivial to have array with content) showing the lib issue.

**Comment by dbvcode** [comment]
Can't replicate at but with your latest update and the latest Angular wrapper I found where the issue was coming from.
Long story short, I copied `gridstack-extra.scss` into my styles and imported it.
Initially I was importing there styles `@import "gridstack/dist/gridstack.min.css";`

Now I am importing both and the issue is gone.
At this point I am happy with this.
Tried to import `gridstack.scss` instead of the `min` one but it doesn't work the same unfortunately.

**Comment by adumesny** [comment]
extra.css and normal gridstack.css are totally different - see https://github.com/gridstack/gridstack.js#change-grid-columns

**Comment by dbvcode** [comment]
Thanks for the reply! I got it working dynamically now.
Here is the TS function to generate the same CSS as `extra.scss`

```
  private generateGridStackItemsCSS(
    gridstackColumnsStart: number = 2,
    gridstackColumns: number = 30
  ): string {
    let css = '';
    const fixed = (float: number) => `${Math.round(float * 1000) / 1000}%`;

    const gridStackItems = (columns: number) => {
      css += `.grid-stack-${columns} > .grid-stack-item {\n`;
      css += `  min-width: ${fixed(100 / columns)};\n}\n`;

      for (let i = 1; i <= columns - 1; i++) {
        css += `.grid-stack-${columns} > .grid-stack-item[gs-x='${i}'] { left: ${fixed((100 / columns) * i)}; }\n`;
        css += `.grid-stack-${columns} > .grid-stack-item[gs-w='${i + 1}'] { width: ${fixed((100 / columns) * (i + 1))}; }\n`;
      }
    }

    for (let j = gridstackColumnsStart; j <= gridstackColumns; j++) {
      gridStackItems(j);
    }

    return css;
  }
```

Cheers
