### ISSUE TITLE
Some questions about gridstack-all.js

### ISSUE THREAD

**Issue by RemVas** [gridstack/gridstack.js#2278]
1. What is included in gridstack-all.js? I could not find any documentation about that. Why "all"? What is "all"?

2. And the "gridstack-all.js" file seems to be a minimized JS file? Why is it not called "gridstack-all.min.js"? Where can I find the normal (unminimized, readable) version of the JS file?

Any pointers are much appreciated!

**Comment by adumesny** [comment]
use slack channel for questions...
doc has info https://github.com/gridstack/gridstack.js#include
