### ISSUE TITLE
scrollbar nofollow

### ISSUE THREAD

**Issue by MrYua** [gridstack/gridstack.js#2302]
## Subject of the issue
I want the grid-stack initial container to fill the entire screen { height: 100VH } , and when I drag the grid-stack-item to the bottom, the scroll bar doesn't follow the bottom, it stays where it is

## Your environment
* gridstack: "^8.0.1"
* Windows  Edge

## Expected behavior
I expect the widget to bottom out and the scroll bar to follow the scroll to the end

**Comment by adumesny** [comment]
please provide a running example as the bug template requires it. re-opening when you do.
