### ISSUE TITLE
Export Angular module that uses gridstack components

### ISSUE THREAD

**Issue by lasharn** [gridstack/gridstack.js#2310]
## Subject of the issue
The Angular components available in 8.0+ should be part of a module that can be imported by external Angular projects.

Currently we can not use the gridstack and gridstack-item components in a template since they are not declared in a module that is available externally.

## Your environment
gridstack 8.1.0
Windows 11

**Comment by adumesny** [comment]
yep, I haven't tried them yet in my project at work... not surprised I missed something. 
but couldn't you import them in your module by path 'gridstack/dist/ng/' instead ?

**Comment by lasharn** [comment]
I get an error trying to import it that way:
`Class GridstackItemComponent is neither an Angular component nor directive nor pipe`

I had a quick go at creating the module in a fork but I ran into another error when trying to import it. Haven't spent more time on it since this isn't a blocking issue for us (we are still using a copied version for now).

> This likely means that the library which declares GridstackModule has not been processed correctly by ngcc, or is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

Side note, that photo is from many seasons ago so its definitely time to update it :)
Our ski season in NZ last year was a record low so I'm very jealous!

**Comment by adumesny** [comment]
| I had a quick go at creating the module in a fork but I ran into another error when trying to import it.

having the same issue... it's almost here. I'm not a build/package guy...

**Comment by adumesny** [comment]
fixed in v8.1.2 just released... took me 2 days to get build right. 

don't forget to donate if you find this lib useful!
