### ISSUE TITLE
Placeholder shadow is showing if the dragged item is not placed on the grid.

### ISSUE THREAD

**Issue by lakshman0369** [gridstack/gridstack.js#2311]
### Describe the bug
Grey shadow of the placeholder is retaining even if the item is not dropped on the grid.

### Your Example Website or App

(https://gridstackjs.com/demo/web2.html)

### Steps to Reproduce the Bug or Issue

1. Drag the droppable item on to the grid.
2. Hold that item on the grid without dropping and a grey shadow is observed on the grid.
3. Drag the item out of the grid and drop it outside the grid.
4. The grey shadow is still is observed on the grid.

### Current behavior

The grey shadow of the placeholder still exists on the grid if the item is not placed on it.

### Expected behavior

The grey shadow of the placeholder should be removed if the item is not placed on the grid.

### gridstack version

7.2.3

### Operating System Version

Windows

### Browser

Chrome

### Screenshots or Videos

[issue.webm](https://user-images.githubusercontent.com/54270674/236776352-ebe2d0a7-d600-413e-833e-60b52e364114.webm)

**Comment by adumesny** [comment]
humm, working fine for me (windows 11 Chrome as well) - its v8.1.0 by the way. probably an extension or something in your browser - try another one.

https://user-images.githubusercontent.com/3496166/236849119-a84edd87-8000-4519-96bf-9e7b6230eca3.mp4

**Comment by lakshman0369** [comment]
I have observed this issue in various browsers. Can you please check why this happening.
[Edge and firefox issue.webm](https://github.com/gridstack/gridstack.js/assets/54270674/0e8d4dc7-704a-4ca4-aa5a-dd9139870b2e)

**Comment by adumesny** [comment]
can't reproduce it I can't fix it... something about your machine...

**Comment by lakshman0369** [comment]
![image](https://github.com/gridstack/gridstack.js/assets/54270674/ceff5ac8-8b9c-4c15-9b04-3cc492ebbb10)

We are able to figure out the cause of the issue. When moving out of the grid, this.engine.removeNode(node) needs to be executed. But for me node._temporaryRemoved is set to be true instead of the undefined. 

node._temporaryRemoved is being removed in addNode in gridstack-engine.ts. But for some reason addNode is being called twice (from _onStartMoving in gridstack.ts). This is causing the node._temporaryRemoved not being removed. It's value is still being set to be true when gone to  _leave method in gridstack.ts. Can you provide any guidance on how to resolve this?

**Comment by lakshman0369** [comment]
Hi @adumesny,

I see you marked it as need more info. Can you please provide on what more information are you looking for?

**Comment by adumesny** [comment]
well can't reproduce it, I can't fix it... need step to reproduce.
