### ISSUE TITLE
Customizing snapping/anchoring/docking grid dimension distance.

### ISSUE THREAD

**Issue by gvvineet** [gridstack/gridstack.js#2313]
## Subject of the issue
When the grid is resized, the grid dimensions are snapped or docked at a certain length.  Usually at one of the 12 default columns. Is there a way to dock at a more granular distances?

## Your environment
* version of gridstack.js - v0.6.3
* Chrome

## Steps to reproduce
https://jsfiddle.net/adumesny/jqhkry7g

## Expected behavior
When resized, the grid dimensions are set at anchor point where the mouse click leaves.

**Comment by adumesny** [comment]
use slack for questions. it's in the doc too https://github.com/gridstack/gridstack.js#change-grid-columns
