### ISSUE TITLE
Grid-stack-instance-1 class name removed when browser theme applied

### ISSUE THREAD

**Issue by Nomulacharitha** [gridstack/gridstack.js#2322]
### Describe the bug
Grid-stack-instance-1 class name not getting applied.
### Your Example Website or App
(https://gridstackjs.com/demo/web2.html)
### Steps to Reproduce the Bug or Issue
1. Change the theme
2. Grid-stack-instance-1 class name is not getting applied
### Current behavior
Grid-stack-instance-1 class name not getting applied.
### Expected behavior
Grid-stack-instance-1 class name should be applied.
### gridstack version
7.2.3
### Operating System Version
Windows
### Browser
Chrome
### Screenshots or Videos
https://github.com/gridstack/gridstack.js/assets/65599587/2d00c926-3d0c-4ec3-bb77-82522e888ff6

**Comment by adumesny** [comment]
I'm not able toa dd themes to Chrome (unzip error) so I can't check it... nor fix it.

**Comment by Nomulacharitha** [comment]
Could you please tell me in which scenarios the grid-stack-instance class name gets applied and in which scenarios it won't get applied?

**Comment by adumesny** [comment]
the only place I remove that class is in `destroy()`, so I don't think it is GS making it go away...
```ts
  public destroy(removeDOM = true): GridStack {
...
    if (!removeDOM) {
      this.removeAll(removeDOM);
      this.el.classList.remove(this._styleSheetClass);
````

**Comment by Nomulacharitha** [comment]
when i change the theme, the grid stack instance class is removed. I checked whether the destroy () is getting called or not. It was not getting called. Even though the function is not getting called still the class is not applied. Could you please help me with this?

**Comment by adumesny** [comment]
I don't have the bandwidth to look at every bug, unless you want to pay for it, but then again I can't reproduce it and likely not a GS bug. My best guess is the browser is deleting the custom CSS sheet and removing any DOM element with that name (our grid) but unless they send us some event it happened, not sure I can do much to re-create it....
