### ISSUE TITLE
dataTransfer is undefined (v6+ uses MouseEvent not DragEvent anymore)

### ISSUE THREAD

**Issue by ZOUJIELynn** [gridstack/gridstack.js#2327]
https://github.com/gridstack/gridstack.js/blob/5f6c8de638a2519fbc8ffc18171810671c4e3e93/demo/drag-and-drop-dataTransfer.html#L69

**Comment by adumesny** [comment]
that's a 21 months old demo that never been updated per say, nor is it actually published on the index list. So wonder why I didn't remember what it was... unlikely to be looked at anytime soon...

angular code likely very outdated along the rest. Unlike
```cmd
SHA-1: f5ba6d59f49bd7822b323989dfeb59369949e270

* Enable passing of DragEvent to gridstack dropped event (#1841)

Modification done to allow the passing of DragEvent to gridstack dropped event, allowing access to dataTransfer property. A demo in Angular has been included to showcase this new capability.

Co-authored-by: Samuel Lim <samuel.lim@finantix.com>
```

**Comment by ZOUJIELynn** [comment]
> that's a 21 months old demo that never been updated per say, nor is it actually published on the index list. So wonder why I didn't remember what it was... unlikely to be looked at anytime soon...
> 
> angular code likely very outdated along the rest. Unlike
> 
> ```batchfile
> SHA-1: f5ba6d59f49bd7822b323989dfeb59369949e270
> 
> * Enable passing of DragEvent to gridstack dropped event (#1841)
> 
> Modification done to allow the passing of DragEvent to gridstack dropped event, allowing access to dataTransfer property. A demo in Angular has been included to showcase this new capability.
> 
> Co-authored-by: Samuel Lim <samuel.lim@finantix.com>
> ```

thanks for your reply ， any way for me to transfer data when drag a widget outside now ?

**Comment by ZOUJIELynn** [comment]
> > that's a 21 months old demo that never been updated per say, nor is it actually published on the index list. So wonder why I didn't remember what it was... unlikely to be looked at anytime soon...
> > angular code likely very outdated along the rest. Unlike
> > ```batchfile
> > SHA-1: f5ba6d59f49bd7822b323989dfeb59369949e270
> > 
> > * Enable passing of DragEvent to gridstack dropped event (#1841)
> > 
> > Modification done to allow the passing of DragEvent to gridstack dropped event, allowing access to dataTransfer property. A demo in Angular has been included to showcase this new capability.
> > 
> > Co-authored-by: Samuel Lim <samuel.lim@finantix.com>
> > ```
> 
> thanks for your reply ， any way for me to transfer data when drag a widget outside now ?

By the way , I use vue3 ~

**Comment by uporot1k** [comment]
Any news?

**Comment by adumesny** [comment]
we are no longer using `DragEvent` but simple `MouseEvent` (and `TouchEvents` on mobile) so we don't get `dataTransfer` per say. suppose I could maybe create/fake it...

Why do you use it and couldn't the info be stored other ways anyway ?

![image](https://github.com/gridstack/gridstack.js/assets/3496166/0e4fb8fe-fd8d-4da8-a7aa-56b8b60de7dd)

**Comment by adumesny** [comment]
closing since old and no updates, and not something we support.
