### ISSUE TITLE
Cannot read properties of undefined (reading 'marginRight') -- triggered when trying to init grid after destroying grid

### ISSUE THREAD

**Issue by programthis** [gridstack/gridstack.js#2340]
## Subject of the issue
This issue seems to be triggered when trying to initialize the grid after destroying it. I've attached the useEffect hook to show how this is being executed.

```
useEffect(() => {
        const initializeGrid = () => {
            let windowWidth = window.innerWidth,
                numOfColumns = Math.floor(windowWidth / 100);
            var grid = GridStack.init({
                float: true,
                gridBackground: true,
                column: numOfColumns
            });
            gridRef.current = grid;
        }

        const resizeWindow = () => {
            let windowWidth = window.innerWidth,
                numOfColumns = Math.floor(windowWidth / 100),
                backgroundCalculation = windowWidth / numOfColumns;
            setBackgroundSize(backgroundCalculation);
            let grid = gridRef.current;
            if (grid) {
                grid.destroy(false);
                initializeGrid();
            }
        }
        initializeGrid();
        window.addEventListener('resize', resizeWindow);
    });
```

Here is the full error:

```
Cannot read properties of undefined (reading 'marginRight')
TypeError: Cannot read properties of undefined (reading 'marginRight')
    at GridStack.cellHeight (http://localhost:3000/static/js/bundle.js:5863:35)
    at http://localhost:3000/static/js/bundle.js:6605:100
    at http://localhost:3000/static/js/bundle.js:7766:11

```

## Environment
"gridstack": "^8.1.1",
"react": "^18.2.0",
"react-dom": "^18.2.0",
"react-scripts": "5.0.1",
"web-vitals": "^2.1.4"

Chrome browser
Linux Mint

**Comment by programthis** [comment]
@adumesny Here is my **[reproducible example](https://github.com/programthis/grid-app)**.

The reason I opted not to use grid.column(n) is because (as you'll see if you download the repo), it doesn't seem to properly update the grid class "gs-x" when resizing said window. But let me know what I am missing because I would much rather use that approach than reinitializing the entire grid.

Also my bad, that gridBackground variable is just to update the css grid lines in the background...

**Comment by adumesny** [comment]
I need a simple html/js example showing the issue, not your applicaiton, like all the demo/*.html examples.

Also if grid.column(n) has issue not updating gs-x then you should post that instead.

**Comment by programthis** [comment]
@adumesny Ok I will post a separate issue for the grid.column then.

**Comment by adumesny** [comment]
FYI, I tried this in a demo and ot works fine - so likely your issue
```ts
  <script type="text/javascript">
    let grid = GridStack.init();
    grid.destroy(false);
    grid = GridStack.init();
  </script>
```
