### ISSUE TITLE
grid.enableMove(true) overrides local item values

### ISSUE THREAD

**Issue by koljada** [gridstack/gridstack.js#2349]
## Subject of the issue
When I initialize the grid from html `gs-no-resize` and `gs-no-move` attributes are ignored

## Your environment
* version of gridstack.js - 8.2.0
* which browser/OS - Edge, windows 11

## Steps to reproduce
https://jsfiddle.net/pt1jbnr2/

## Expected behavior
`gs-no-resize` and `gs-no-move` attributes should be respected and widget should not be movable or resizable

**Comment by adumesny** [comment]
thanks, the issue isn't that it's ingored, but that it's overriden when calling grid.enableMove(true)
https://jsfiddle.net/adumesny/wyg72c0b/

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful!
