### ISSUE TITLE
Gridstack modal clone issue

### ISSUE THREAD

**Issue by DigitagDev** [gridstack/gridstack.js#2352]
Hello, I am working on a project where I need to drag items from a palette to the grid. This project is inside a Bootstrap modal, and from what I've noticed, when we use the 'clone' helper or even customize it, the cloned item being transferred to the grid does not appear. This is different from what we see when we perform the same process outside of a modal. Unfortunately, I have not been able to find an answer to this problem in the documentation, let alone a workaround for it. Here is a code example on JSFiddle. it seens to be a z-index issue

https://jsfiddle.net/bodinho97/Lakroyus/27/
![Sem título](https://github.com/gridstack/gridstack.js/assets/135129255/55f916b1-56a3-4423-8c13-82dbff948a73)

**Comment by DigitagDev** [comment]
WorkAround , take me sometime to discover that bootstrap modal has a z-index of 1050; even placing a z-index of 999 on gridstack content wont work. u can close the issue

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful!
