### ISSUE TITLE
max-w cloning issue

### ISSUE THREAD

**Issue by DigitagDev** [gridstack/gridstack.js#2354]
Hello. It seems that I have found a bug in the object cloning area from a template to the grid. Following the example from the documentation, it is possible to observe that an element containing the attribute gs-max-w or gs-max-h, when cloned to the grid and then deleted from the grid using .trash or another class, any elements cloned by the same grid lose the gs-max-w or gs-max-h attribute. This can be observed even in the example documentation for two grids.

Bring the element to the grid and confirm that it has the max3 attr(on the dom the element lose this attr, but seems to work fine without it)
![Sem título2](https://github.com/gridstack/gridstack.js/assets/135129255/298c49e1-7d44-4859-aee1-d0527eb2034a)

Removes the element from the dom dropping over a .trash class
![Sem título3](https://github.com/gridstack/gridstack.js/assets/135129255/855fb258-e87a-42af-ae88-8d7145c60b40)

Bring the same element to the grid again , and its lose the max-w.
![Sem título4](https://github.com/gridstack/gridstack.js/assets/135129255/5d588afe-a2fc-4a05-95e7-42ce026fc74d)

**Comment by adumesny** [comment]
good catch. yeah we don't write gs-max-w to dom as it's not used for rendering (only creation initial value).

**Comment by adumesny** [comment]
teh issue was caused by this in 8.x `if (n.maxW) el.removeAttribute('gs-max-w');` but I don't know why we don't clone the entire griditem and just the content below (likely #2231) and will need to look at that first

**Comment by adumesny** [comment]
fixed in next release. don't forget to doinate if you find this lib useful!

**Comment by adumesny** [comment]
better fix in v11
