### ISSUE TITLE
HTML attributes dont seem to do anything

### ISSUE THREAD

**Issue by austinwbest** [gridstack/gridstack.js#2355]
## Subject of the issue
The docs say `most of the above options are also available as HTML attributes` however i have tried like a half dozen and they do nothing. I have tried (off the top of my head)

gs-
- draggable
- resizable 
- disableResize (and disable-resize)
- cellHeight (and cell-height)

None of them do anything. If i put them in the init options it works but i would like to just do this on an item by item basis. Is there somewhere that actually shows these attributes working and which ones do work that i can reference?

## Your environment
* version of gridstack.js - 6.14.17
* which browser/OS - Chrome

## Steps to reproduce
My code is simple as i am just testing things...
```
<link href="node_modules/gridstack/dist/gridstack.min.css" rel="stylesheet"/>
<link href="node_modules/gridstack/dist/gridstack-extra.min.css" rel="stylesheet"/>
<script src="node_modules/gridstack/dist/gridstack-all.js"></script>

<style>
.gs-3 > .grid-stack-item[gs-w="1"] { width: 33%; height: 20px; }
.gs-3 > .grid-stack-item[gs-w="2"]  { width: 66% }
.gs-3 > .grid-stack-item[gs-w="3"]  { width: 99% }
</style>

<div id="content" class="app-content">
    <div class="row">
        <div class="col-lg-4">
            <div class="grid-stack">
                <div class="grid-stack-item" gs-w="1">
                    <div class="grid-stack-item-content">Item</div>
                </div>
                <div class="grid-stack-item" gs-w="1">
                    <div class="grid-stack-item-content">Item</div>
                </div>
                <div class="grid-stack-item" gs-w="3">
                    <div class="grid-stack-item-content">Item</div>
                </div>
                <div class="grid-stack-item" gs-w="3">
                    <div class="grid-stack-item-content">Item</div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    let options = {
        column: 3,
        minRow: 1,
        disableOneColumnMode: true,
        float: true,
        cellHeight: 50,
        disableResize: true
    };
    GridStack.init(options);
</script>
```

## Expected behavior
Would be nice if the attributes worked

EDIT: Think i figured it out. Grid options vs Item options

**Comment by austinwbest** [comment]
![image](https://github.com/gridstack/gridstack.js/assets/8321115/aab327d3-a5ab-4a43-8803-8cb570dd022f)

So had some time to try and get it working with the item options. 

`gs-no-resize="yes" gs-no-move="yes" gs-locked="yes"` are all set and yet i can move it around without any issues. I can move other items under it, above it, etc.

**Comment by dev-at-sevenlab-nl** [comment]
Did you find a solution i've tried `gs-no-drag="'yes'"` `gs-no-drag="true"` or `gs-no-drag="1"` but none work
