### ISSUE TITLE
Gridstack from v8  "maximum call stack size exceeded" crash error when cellheight is set with "rem" value 

### ISSUE THREAD

**Issue by zsolt-horvath** [gridstack/gridstack.js#2357]
## Subject of the issue
From version 8 and above gridstack produces a weird, hard to debug "maximum call stack size exceeded" error and crashes the whole page when cellHeight is set with "rem". It is working properly with v7

## Steps to reproduce
You can reproduce it in with the gridstack repo.

In the Gridstack repo go to: angular -> projects -> demo -> src -> app -> app.component.ts
Add for example:` cellHeight: '23rem'` to gridOptions in line # 36 
Run the app locally, select the proper demo and try to drag&drop one of the grid items

**Comment by adumesny** [comment]
I'm not seeing any issue with 8.2.1 - I can drag items just fine (they don't resize though)
![image](https://github.com/gridstack/gridstack.js/assets/3496166/e6624060-d232-46c2-8bde-c9a8cf31c3ff)

**Comment by adumesny** [comment]
Oh never mind - draging the first item to push the other does cause issues...

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful!

**Comment by adumesny** [comment]
took a while to debug - though simple 1 liner fix.

fixed in next release. don't forget to donate if you find this lib useful!

**Comment by zsolt-horvath** [comment]
Thank your for your quick response!
