### ISSUE TITLE
Expose a new event named 'shouldDrop' when moving an item from one grid to another.

### ISSUE THREAD

**Issue by shibisuriya** [gridstack/gridstack.js#2359]
Need a new event named 'shouldDrop', which would be invoked before the 'removed' and 'dropped' event when a user  manually (using mouse) moves a grid item from one grid to another...  The user should have the ability to return a boolean, like
```js
grid.on('shouldDrop', (event, item) => {
        if(item.w > 10) {
             return true
        } else {
            return false
        }
})
```
If true is returned the DOM node of grid item is physically moved into the grid inside which the user has dropped it...
If false is returned nothing happens.
This is extremely useful when integrating with virtual DOM based js libs... Since when you physically move a HTML node (or accessing the DOM in general is not a good practice) most js lib can't sync states properly... Thank you.

**Comment by shibisuriya** [comment]
If the shouldDrop callback function returns false, no 'removed' and 'dropped' event would be called... Everything will remain in its place... This could be similar to the acceptWidget key (a callback function) that we supply to the lib when initialising a grid... But that function only decides if an item should be accepted inside the grid or not... It can't do any type of compute after the item has been dropped (mouse released).

**Comment by adumesny** [comment]
first of all vitual DOM js lib (Angular, React, Vue, etc...) we have specific instructions how to deal with them as it's not a good idea to have them track griditem when GS will also do dom editing (see angular wrapper for reason). those framework can control the content or do what I do in Angular wrapper...

second `GridStackOptions.acceptWidgets` also ready exist as callback function to prevent dropping in the first place (will not get a placeholder to follow if you can't drop). 

closing this as not valid.
