### ISSUE TITLE
Expose an event that gets invoked when a grid item is dragged and dropped into the trash

### ISSUE THREAD

**Issue by shibisuriya** [gridstack/gridstack.js#2360]
## Expose an even that gets invoked when a grid item is dragged and dropped into the trash
I want a event that will be emitted when a grid item is dropped into the trash.

Required API:
```js
const grid = GridStack.init({removable: '#trash'})
grid.on('removable', (event, item) => {
          if(item.id == '7') {
               return true 
          } else {
               return false
          }
})
```
This way we can allow people to only selectively drop grid items into trash, in the case above only grid item with id 7 can only be dropped into the trash. Thank you.

**Comment by adumesny** [comment]
you can already do that using `removableOptions: { accept: '.grid-stack-item' }` and use a class only some elements have instead of the default.

beside it wouldn't be an event - but a callback - as events don't return a valud (other than propading up) that can be used.
