### ISSUE TITLE
Draggable handle not working as expected

### ISSUE THREAD

**Issue by cca-developer** [gridstack/gridstack.js#2372]
## Subject of the issue
When specifying the draggable..handle in the options, it does not seem to respect only that class name for dragging.  Instead, anything on the item can still be used to drag it.

## Your environment
gridstack v ^7.0.0
tested on both Windows and Linux

This is also a problem with v8, but is not a problem when rolling back to v6

## Steps to reproduce
In the fiddle below, note that the options are set with
```
  draggable: {
    handle: ".drag-handle"
  }
```
Since that class does not exist in the html, I would expect that the grid items could not be dragged anywhere.  Instead, they are draggable by clicking and dragging anywhere in the item.

https://jsfiddle.net/ryvbk4j5/1/

## Expected behavior
The draggable option should respect the header class if provided.

**Comment by adumesny** [comment]
that is by design (fallback). set noMove|noSize if you don't want to drag

**Comment by cca-developer** [comment]
The point is not that I don't want to drag.  The point is that I do want to be able to drag, but only with the class specified in the `handle` option.  I was trying to provide a minimalist example in the fiddle.  Right now, we have the draggable handle specified, but clicking anywhere in the item allows dragging.  If I understand it correctly, it should only be draggable based on the handle provided.  We are using Angular components, so maybe that has something to do with it?  I'll try to come up with a fiddle that better illustrates the problem.  But we have a configuration that works as expected with v6 (can only drag from the class specified), and that same configuration can be dragged from anywhere if we're using v7 or v8.

**Comment by adumesny** [comment]
So your saying the class exist but it's dragging entire item instead of
that div? Yeah then it's a bug.

sent from phone. excuse any typ-oh!

**Comment by adumesny** [comment]
@vishaalagartha try disable drag `grid.static(true)` and re-enable it to the new class to have it use that instead...

**Comment by vishaalagartha** [comment]
@adumesny , I believe you mean `grid.setStatic(true)`? And then I'm confused by what you mean by 

> re-enable it to the new class to have it use that instead

How can I re-enable to use the new class? I can't pass in options to the `setStatic` function.

**Comment by vishaalagartha** [comment]
@adumesny - you're a wizard. Thank you so much.

**Comment by vishaalagartha** [comment]
@adumesny - do you think there is room for a clearer external API that gridstack could expose here? A function like `resetDragHandles` or something would make things clearer for developers I think.

**Comment by adumesny** [comment]
Too special case imo.

**Comment by hspaay** [comment]
@cca-developer are you using htmx?

I found that when delayed-loading 'grid-stack-item-content' with htmx, that the handle selector (.drag-target) doesn't work.
A workaround that does work for some reason is to use the cancel handle to exclude the body of the content from dragging. Oddly enough the html with the  cancel selector is also loaded with htmx so that is a bit odd.

Example delayed-loading tile content using htmx:
```
<div class="grid-stack-item "gs-id="{{$k}}"
                 gs-min-h="4"
                 gs-size-to-content="false">
    <div class="grid-stack-item-content" style="overflow:unset">

        <div  hx-trigger="intersect once"
            hx-swap="outerHTML"
            hx-params="none"
            hx-get="{{.ReRenderTilePath}}"
        >
	  <p>reloading tile fragment...</p>
  	  <h-loading></h-loading>
        </div>
    </div>
</div>
```
Where after loading this would contain a header with class="drag-target" and a body. In this case drag-target is not re-evaluated.

**Comment by adumesny** [comment]
| Grid-stack probably locates the drag-handle element on initial load and isn't aware that the content is swapped out

@hspaay yes of course. how would GS know ? even if possible to track children DOM canges, redoing drag target everytime something changes (cached at best) would be pretty expensive for eveyone to occure because some framework coders are init the grid before content is there...

**Comment by hspaay** [comment]
Indeed, that sounds pretty expensive. Just curious, why does the cancel handler not have this problem?

htmx has a nice callback handler 'hx-on::after-request' which could be used to invoke the API to refresh the handlers. In my use-case only a single tile refreshes when its contents changes so shouldn't be too bad.

Initial testing however shows that using the 'cancel' handler on the body works quite well. So-far it looks like a good solution when using htmx. Maybe useful to include this as a suggestion in the docs. Something along the lines of: "When using htmx to refresh tiles and using the drag-handle, consider using the cancel handler instead as the drag-handle doesn't update after a swap".

Thanks again,
