### ISSUE TITLE
How the rightmost grid fits to the left as the width increases？

### ISSUE THREAD

**Issue by no-simple** [gridstack/gridstack.js#2374]
## Subject of the issue
When the item in the last column increases the width, how to adapt the layout to the left instead of the width unchanged?

## Your environment
* gridstack.js - v8.3.0
*  chrome/window

## Steps to reproduce
Click the change size in the example to observe that the width does not fit
https://jsfiddle.net/zyxee/bg4qyjmc/8/

## Expected behavior

https://github.com/gridstack/gridstack.js/assets/22831736/fe9fa4b4-6a0e-44a5-b0d4-87a3b0c4dea8

**Comment by adumesny** [comment]
You certainly can do that shown behavior yourself with some UI to expand the panel. Not sure it would make sense for the lib to do that anyway, during manual resize? donation would be required for it. Thanks.
