### ISSUE TITLE
updating the grid items after drop crashes the grid (angular version)

### ISSUE THREAD

**Issue by arnoudb** [gridstack/gridstack.js#2375]
## Subject of the issue
We are having 2 grids with their own items data provider set in angular in the template. Changing those providers with script is not a problem. But what we want is after a cross grid drop is to sync the data providers for each grid. this crashes the grid. See video and. An example branch is attached in which the code example is present.

## Your environment
* version of gridstack.js -8.3.0, angular
* which browser/OS- mac os ventura 13.4

## Steps to reproduce
see video and branch https://github.com/arnoudb/gridstack.js/tree/bug-drag-update-model
the branch creates an extra button in the angular demo project to show what goes wrong.

## Expected behavior
the branch and demo should describe clearly what is happening
![bug-drag](https://github.com/gridstack/gridstack.js/assets/2396055/d128b805-5e7e-4229-a800-0b5b627ea0ac)

**Comment by adumesny** [comment]
where is your modified ng demo ? I'm not seeing it in https://github.com/arnoudb/gridstack.js/blob/master/angular/projects/demo/src/app/app.component.html

**Comment by arnoudb** [comment]
You can find it in the the branch: bug-drag-update-model

**Comment by adumesny** [comment]
I don't have time to debug your code. beside looking at you grid wrapper (not sure why you are even wrapping my ng components at all) you have
```js
<gridstack-item
    *ngFor="let item of items; trackBy: trackWidget"
```

which I mention in the doc is is NOT the right way to do especially for multiple grids. Let GS do all the dom and use the `GridStack.addRemoveCB = gsCreateNgComponents` as shown instead.

**Comment by arnoudb** [comment]
About the wrapping: I just wrapped the chart components to initialise them and give some default behaviour, which should not be a problem. 

So  used the example 4. `Most complete example that uses Component wrapper for grid and gridItem'
Nice and declarative.
```
<gridstack [options]="gridOptions" (changeCB)="onChange($event)" (resizeStopCB)="onResizeStop($event)">
    <gridstack-item *ngFor="let n of items; trackBy: identify" [options]="n">
       <!-- added our complex  custom widget with many inputs here -->
    </gridstack-item>
  </gridstack>
```

I think this is the comment you are referring to:
'ngFor case: TEST TEMPLATE operations - NOT recommended unless you have no GS creating/re-parenting'. 

Some context: What our app does, is separating layout and widget content (we will have multiple layouts for different screen sizes and just want GS deal with the layout).  So the idea is to let angular create the widgets instead of delegating this to GS. And reparenting we do manually by updating the options for the grids the ngFor loops over (after the drop is complete). Our models drive the UI and are kept in sync with what you see.

Anyway i found out that GS uses `setTimeout` to finalize the drop after the event is already emitted. This causes my problem. Executing our logic a bit later (although ugly) works fine. 

What i would expect from the `(droppedCB)= "<handler>"` api is that it emits the event after the drag is really complete, not while still doing related finishing up logic in a setTimout(). Hence i'm still convinced its a bug.

**Comment by adumesny** [comment]
I think you are refering to this code - yeah `setTimeout()` seems like a hack here. the only other places are for restoring animation or drag delay which do have a timing to wait on...
```ts
        // wait till we return out of the drag callback to set the new drag&resize handler or they may get messed up
        window.setTimeout(() => {
          // IFF we are still there (some application will use as placeholder and insert their real widget instead and better call makeWidget())
          if (node.el && node.el.parentElement) {
            this._prepareDragDropByNode(node);
          } else {
            this.engine.removeNode(node);
          }
          delete node.grid._isTemp;
        });
```

the problem with *ngFor is you are telling me Angular is the owner/creator of the list, but GS also have a list of widgets and will directly add/move/delete them so keeping them in sync is hard (and not something I did in the examples).
One option if you want full Ng support for creating your widgets, is to create your own <gridstack-item> so it's template has the logic you wanted above, and let GS handle all creation from json instead.
