### ISSUE TITLE
Limiting dragging to grid container

### ISSUE THREAD

**Issue by mit579** [gridstack/gridstack.js#2376]
I want to limit the movement of grid elements to the container containing the grid.

I am trying to limit the movement of items in grid to the parent container using 

this.grid.opts.draggable.containment = '.classnameOfGridContainer' but still user is able to drag items outside the above class.

When grid elements gets dragged outside to container , it makes the page messy.

Gridstack Version: 4.4.0
Testing on chrome

Expected outcome :  Grid elements should be draggable to outside container

**Comment by adumesny** [comment]
`draggable.containment` is a jquery ui option that has not been implemented in the latest no jq version - sop you will have to use an old JQ version or donate to have the feature added to tge current code base. The old code is not supported anymore.

**Comment by adumesny** [comment]
again 4.4 is no longer supported
