### ISSUE TITLE
Gridstack gs-id styles getting lost on editing the page

### ISSUE THREAD

**Issue by mit579** [gridstack/gridstack.js#2377]
**Subject of the issue**
Items in gridstack losing height when some other component(outside gridstack) is changed or edited on page.

**Environment**
Version: 8.3.0
Chrome Browser

 **Steps to reproduce**
On a page with react, gridstack is working as expected. When changed something outside gridstack, grid-stack-item is losing its height

.gs-id-4 > .grid-stack-item[gs-h="2"] {
    height: 140px;
}

OR 

.gs-id-4 > .grid-stack-item > .grid-stack-item-content {
    inset: 10px 0px 10px 10px;
}

Above css rule doesn't get applied on editing the page

 **Expected behavior**
Gridstack items should not lose their height

**Comment by adumesny** [comment]
that means the CSS file we create dynamically for heights is getting deleted - you  have options on where to put header.
