### ISSUE TITLE
 nested_contraint in Angular ngFor

### ISSUE THREAD

**Issue by leemoria** [gridstack/gridstack.js#2383]
How to implement subGridOpts internally in NgFor，I want to achieve the effect of nest container，
      Are there any demos or some ways to drag a container to created new nested grids methods available

     
      <gridstack
            class="gateway-gridsrack"
            [options]="gridOptions"
          >
            <gridstack-item *ngFor="let widget of items; let i = index; trackBy: identify" [options]="widget">
              <div
                class="grid-stack-item-content-box"
              >
                <i class="delete-icon" (click)="deleteItems(widget, i)"></i>
                <dynamic-widget [widget]="widget"></dynamic-widget>
              </div>
            </gridstack-item>
          </gridstack>

**Comment by adumesny** [comment]
please use slack for questions. 
while you could have nested ngFor base on options, that wouldn't convert the parent into a nested grid automatically...
