### ISSUE TITLE
Nested grid removed from Widget when updating contents

### ISSUE THREAD

**Issue by akosfekete** [gridstack/gridstack.js#2384]
## Subject of the issue
When I update a widget with a nested grid using `update(els: GridStackElement, opt: GridStackWidget)`, and provide `content` in the `opt` parameter, the nested grid is also removed (even though the subGridOpts field is not present in the `opt` parameter).

## Your environment
* version of gridstack.js: tried on 8.3.0-dev, 8.3.0, 8.2.3, 7.3.0
* which browser/OS: Firefox / Chrome, Linux / Windows

## Steps to reproduce
- Create a nested grid
- Call update() on it with an `opt` parameter like this: `{content: '<div>some content</div>'}`
- JSFiddle: https://jsfiddle.net/1yr8ngju/

![firefox_jpo6N51YpN](https://github.com/gridstack/gridstack.js/assets/36549157/4aee14fb-6edb-41bf-b3d9-b9d26fb29a0e)

## Expected behavior
The nested grid should not be removed, only the content that has been set originally when creating the widget. 
![firefox_GisVZ5Pvqk](https://github.com/gridstack/gridstack.js/assets/36549157/140d70e2-d037-484e-9545-06e836d370cd)

I created a fork with a quick "fix": https://github.com/gridstack/gridstack.js/compare/master...akosfekete:gridstack.js:sub-grid-update-issue
I'm not sure if this is intended in some way, but since the documentation says that "Only those set will be updated", I'd epect the nested grid to remain.

**Comment by adumesny** [comment]
this isn't really a bug - if the item has a subgrid content, and you explicitly say `update(el, {content: 'foo'})` then of course it's going to override whatever content you had with 'foo' - content and subGridOpts are emutually exclusive if you have them both json today I think... will have to check. the above case incrementally has both though....

**Comment by adumesny** [comment]
actually you code seems clean enough, please create a code review (so you can get credit) with that comment addressed
https://github.com/gridstack/gridstack.js/pull/2385

**Comment by adumesny** [comment]
fixed the right way - don't forget to donate if you find this lib useful!
