### ISSUE TITLE
When h is set to 1, there is no attribute for h on the label, and there is no field for h in the call to the save() method

### ISSUE THREAD

**Issue by vela666** [gridstack/gridstack.js#2392]
## Subject of the issue
When h is set to 1, there is no attribute for h on the label and there is no field for h in the call to the save() method
![1689476258517](https://github.com/gridstack/gridstack.js/assets/69613314/f664d227-7aa0-43ee-98c4-6f2845caa84e)

## Your environment
gridstack.js - v8.3.0
chrome/window

## Steps to reproduce
Please check that the printing of this example and the console does not include h
https://jsfiddle.net/vela37/6xjsfa52/16/

## Expected behavior
Can correctly obtain the value of h

**Comment by adumesny** [comment]
that is by design in v8 to significantly reduce dom attributes for 1x1 object (very common) and CSS
