### ISSUE TITLE
Angular example for drag and drop an element from outside to the grid

### ISSUE THREAD

**Issue by shyam1992** [gridstack/gridstack.js#2393]
## Subject of the issue
Angular example for drag an element from outside to the grid

## Your environment
* version of gridstack.js - ^8.3.0

**Comment by adumesny** [comment]
two.html example shown in the angular demo - see https://github.com/gridstack/gridstack.js/blob/master/angular/projects/demo/src/app/app.component.html#L73

Don't forget to donate if you find this lib useful!

**Comment by shyam1992** [comment]
Thanks for the help.

Of course, I am evaluating this library for a bigger cause and if we decide to go ahead with this then I have decided to donate a portion of my day's salary to help keep the community alive.
