### ISSUE TITLE
How to represent a large work space

### ISSUE THREAD

**Issue by HeathDillon** [gridstack/gridstack.js#2400]
## mapping a grid stack to a real world dimension.

Hi,
So I have a desire to use grid stack to represent a storage shelf which can vary from say 2.4metres wide and 1metre deep to be as wide as 5m wide and 1.6metres deep.

Being a shelf a storage box can be placed anywhere on the shelf. We have present box sizes so we have that level of control, but if say a box is 10cm x 10cm in size, on a 5metre wide, 1 metre deep shelf then we have a lot of possible spots for that box, and then 100's of other boxes.

Is there a way to have the grid stack 'surface' represent a real world shelf in terms of size so we can then start placing boxes on the shelf, and having the exact location of each box accessible ? By that I mean I click on a box on the grid stack surface and it can tell me of thats at this grid location, and a grid location is 1mm x 1mm in size so the box is at 40mm from the left and 73mm from the front of the shelf...

thanks

**Comment by adumesny** [comment]
use slack channel for questions. grid item have x,y,w,h which are row/column based, and you can map to anything you want.
