### ISSUE TITLE
Is there some way to insert a virtual dom by acceptWidgets？

### ISSUE THREAD

**Issue by leookun** [gridstack/gridstack.js#2402]
```js
 acceptWidgets: el=>true 
```
 this only defines whether the dragged element can be placed on the page
It would be perfect if we could place the return value of acceptWidgets into the GridStack
```tsx
 const acceptWidgets=()=>{
      const virtuaElement = document.createElement('div')
      const divVnode = <div >placeholder</div>
      virtuaElement.className = 'grid-stack-item-content'
      Vue.render(divVnode, virtuaElement)
      return virtuaElement.cloneNode(true) as HTMLElement
 }
```
The above code works fine in 'GridStack.setupDragIn[appendTo]'

<img width="1060" alt="image" src="https://github.com/gridstack/gridstack.js/assets/131544788/3a4ea9a3-3ebc-4d1f-b44e-0bcd2a2430bd">

**Comment by leookun** [comment]
I was looking for a way to make elements look different when dragged into the grid
In a typical scenario, the sidebar has only ICONS, which are dragged into the grid and rendered as other components

**Comment by leookun** [comment]
https://github.com/gridstack/gridstack.js/issues/2279

**Comment by adumesny** [comment]
| make elements look different when dragged into the grid

look at `DDDraggableOpt.helper: 'clone' | HTMLElement | ((event: Event) => HTMLElement)`

**Comment by leookun** [comment]
> any news?

I implemented this  myself by interactjs, this repo is currently not suitable for production
