### ISSUE TITLE
Inquiring About Emitting Output Events from Child Components in Angular

### ISSUE THREAD

**Issue by rolandsoh96** [gridstack/gridstack.js#2403]
Hello Gridstack maintainers and community,

I've been exploring the Gridstack library with **Angular** and have found the demonstrations quite helpful, especially regarding how to render child components using selectors. I also appreciate the guidance provided on passing variables into children components using the `input` method via the **`NgGridStackWidget`** interface. 

However, I've been unable to find an example in the documentation or demos that shows how to emit an output event from a child component. This led me to a few questions:

**1. Is it possible to emit an output event from a child component within this library's current implementation?
2. If this capability exists, could you kindly direct me to a demonstration or part of the documentation that details how to use it?
3. If this is not currently implemented, could you let me know if there are plans to include this in future updates?** 

If I have overlooked this in the current documentation, my apologies for the oversight. I look forward to your feedback and am excited to continue exploring the capabilities of this robust library.

Thank you for your time and dedication to this project.

**Comment by adumesny** [comment]
closing since more QA than bug/request.
