### ISSUE TITLE
Infinite Loop, browser freeze when using autoPosition: true, resizing columns

### ISSUE THREAD

**Issue by ExusAltimus** [gridstack/gridstack.js#2406]
## Subject of the issue
I am adding widgets to the grid (autoPosition:true) and have the ability to resize the columns.
The resizing columns may not be necessary to reproduce this bug but I'm showing the scenario  in which I encountered it
When I add a widget, resize the columns, then add another widget, the application / browser window crashes completely
I noticed when not using autoPosition that it behaved normally

## Your environment
Gridstack version: 8.4.0
Chrome / Edge / Firefox

## Steps to reproduce
Click add widget, then click resize column, then add another widget, browser should freeze
https://jsfiddle.net/zsm039xo/7/

## Expected behavior
The infinite loop is caused by findEmptyPosition, the real scope of the issue may extend beyond this function
```ts
    for (let i = start; !found; ++i) {
      let x = i % column;
      let y = Math.floor(i / column);
      if (x + node.w > column) {
        continue;
      }
      let box = {x, y, w: node.w, h: node.h};
      if (!nodeList.find(n => Utils.isIntercepted(box, n))) {
        if (node.x !== x || node.y !== y) node._dirty = true;
        node.x = x;
        node.y = y;
        delete node.autoPosition;
        found = true;
      }
    }
    return found;
  }
  ```

**Comment by adumesny** [comment]
your example is missing extra.css (to show 2 columns) but I see the inf loop. thanks

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful!

**Comment by ExusAltimus** [comment]
Thank you so much for the speedy response / fix. I'll surely send a dontation as I have found it extremely useful. Keep up the good work
