### ISSUE TITLE
Nextjs  or  Nuxtjs

### ISSUE THREAD

**Issue by MsBeiBei** [gridstack/gridstack.js#2409]
## Subject of the issue
I don't know how to make gridstack support Nuxt.js or Next.js. I would like to generate the entire grid layout as a skeleton screen on the server-side and then load each individual widget on the client-side.
@hairyheron @adumesny @troolee

**Comment by adumesny** [comment]
dup of #2244

**Comment by fredericrous** [comment]
@MsBeiBei could you please vote on https://github.com/gridstack/gridstack.js/issues/2244
