### ISSUE TITLE
Gridstack not working with lit web component

### ISSUE THREAD

**Issue by ytcodes** [gridstack/gridstack.js#2410]
## Subject of the issue
Gridstack (https://gridstackjs.com/) is not working in lit when placed in nested web component. I have tried disabling shadow dom of all the parent components of gridstack component. By doing this, the styling of entire application will be distorted. 

## Your environment
* version of gridstack.js - ^8.4.0
* Chrome Windows, Stackblitz

## Steps to reproduce
https://stackblitz.com/edit/vitejs-vite-dwaupx?file=index.html,src%2Fwui-gridstack.ts,src%2Fwui-navbar.ts&terminal=dev
If gridstack component is directly called from index.html, gridstack loads. If called from nested, it will fail and throw error in console,
GridStack.initAll() no grid was found with selector ".grid-stack" - element missing or wrong selector ? 

## Expected behavior
 gridstack should load when called from nested component.

**Comment by adumesny** [comment]
well you can always pass in the element when calling GridStack.init() instead of hoping it can find outside a webcomponent. clsoing.

**Comment by h4de5** [comment]
@ytcodes: have a look here: https://stackblitz.com/edit/vitejs-vite-zmjd89?file=index.html,src%2Fwui-gridstack.ts,src%2Fwui-navbar.ts&terminal=dev
