### ISSUE TITLE
public _styleSheetClass

### ISSUE THREAD

**Issue by MsBeiBei** [gridstack/gridstack.js#2411]
I'm trying to add some custom CSS to a Grid using addCSSRule, and I noticed _styleSheetClass in the code. I want to add a unique identifier to the CSS, but it is currently marked as protected. Can it be changed to public?

**Comment by adumesny** [comment]
not a good idea (and why it's private) as the sheet get recreated dynamicaly (when column, ore cellHeight changes for example).
you should create your own external CSS styles for it.
