### ISSUE TITLE
Issues with devices that have a touchscreen and using a mouse

### ISSUE THREAD

**Issue by ginobili** [gridstack/gridstack.js#2413]
## Subject of the issue
There is an issue with the advanced Demo two.hml with devices that have a touchscreen and using a mouse.  There is an issue when you drag an item and then abort the drag. The drop placeholder still remains at the same place.

## Your environment
Dell XPS 15 with touchscreen. Win 11 Pro with Chrome 116

## Steps to reproduce
In the Advanced Demo two.hml Start dragging an element and then aborting the drag

https://github.com/gridstack/gridstack.js/assets/2326083/be61a504-892a-4051-bb02-dcfad702a74f

## Expected behavior
Should have the same behaviour as regular desktop users

**Comment by Ruslan207** [comment]
## Steps to reproduce
In common laptop you can

1. open Chrome devtools
2. enter to emulation mode
<img width="240" alt="Screenshot 2023-08-25 at 00 40 58" src="https://github.com/gridstack/gridstack.js/assets/3863452/51d31b34-4c49-45c6-a3fa-6f978058f413">
3. then choose "Desktop (touch)"
<img width="749" alt="Screenshot 2023-08-25 at 00 42 04" src="https://github.com/gridstack/gridstack.js/assets/3863452/a03f808e-c101-4afa-830d-cc04f0d665ff">
4. refresh demo page (it will init `const isTouch` as `true`)
5. then choose "Desktop"
6. repeat dragging from video above

**Comment by Ruslan207** [comment]
@adumesny select "Responsive" and click here
<img width="605" alt="Screenshot 2023-08-25 at 15 45 04" src="https://github.com/gridstack/gridstack.js/assets/3863452/de1bafe6-fbec-40c4-a8d2-ca60d460a1c8">

**Comment by adumesny** [comment]
fixed in next release (soon as I also need fixes)

**Comment by BananaAcid** [comment]
> 4. refresh demo page (it will init `const isTouch` as `true`)

oookaaaay ... wos wondering, if there is a bug ... could not find anything in the docs (except enabling resize-arrows) and thought touch was broken ... @adumesny I REALLY see a need for it to be added to the docs, boxed, underlined, bold and italic ;)

**Comment by adumesny** [comment]
@BananaAcid you mean that resize handle is shown by default on mobile (isTouch=true) devices ?
already has it's own paragm on the main page...
https://github.com/gridstack/gridstack.js?tab=readme-ov-file#touch-devices-support

Maybe that banana needs to do less acid :)

**Comment by BananaAcid** [comment]
@adumesny no, just what to do, to be able to test it in the browser - and to make clear, it would work if one reloads the page. The only hint I could find for touch support was the handle related info in the docs/readme.md
