### ISSUE TITLE
Adjust the height of the last element, first increase the height and then decrease the height, which will quickly restore the original size

### ISSUE THREAD

**Issue by vela666** [gridstack/gridstack.js#2420]
## Subject of the issue
![动画](https://github.com/gridstack/gridstack.js/assets/69613314/9e768eae-0b03-4802-9676-519f9a542bae)

## Your environment
gridstack.js - v9.0.0
chrome/window

## Steps to reproduce
https://jsfiddle.net/cvxu267g/

## Expected behavior
Can adjust the height normally

**Comment by adumesny** [comment]
likely a dup (or at least related) to #2388

**Comment by gongxi0307** [comment]
> likely a dup (or at least related) to #2388

May I ask if there is any way to solve this problem

**Comment by adumesny** [comment]
not without spend the time to debug and fix it. this is low on my priority these days... if critical to you then cosinder a donation, but I really don't have time.

**Comment by adumesny** [comment]
dup of https://github.com/gridstack/gridstack.js/issues/2388

**Comment by adumesny** [comment]
https://github.com/gridstack/gridstack.js/issues/2388
