### ISSUE TITLE
Easier Support/Payment options (Feature Request)

### ISSUE THREAD

**Issue by makis-x** [gridstack/gridstack.js#2426]
Hello,

Awesome work. We are about to launch a new version of our platform and for 3 years we battled react grid layout to no avail. Your library just worked for the complex scenarios that what we needed in a few hours... 

Can you provide an easier way to support your work cause I don't wanna create accounts to paypal or venmo to drop you some $

Again sincere thanks for your work

**Comment by adumesny** [comment]
Hey thanks, yeah I need to set something up as others have asked for this as well...

**Comment by adumesny** [comment]
| for 3 years we battled react grid layout to no avail
@makis-x which lib was that ? I know there is a very popular react lib. but intersted in knowing what we solved that they couldn't. I would love to have a good React wrapper as well (like I did with Angular that I use at work) but don't know React/Vue.

**Comment by adumesny** [comment]
@makis-x finnaly added github support on the page - support away!

**Comment by makis-x** [comment]
Hello sorry for the late reply crazy busy. A react wrapper would be perfect. React Grid Layout is only good if you have a very basic dashboard. The worst thing about it was the internal state was flaky and had to run circles to get it to update with props, requiring us to manage multiple sets of the same data in state.

Besides it being terrible (my opinion) yours worked seamlessly in a few minutes even with no react wrapper. 

But the biggest winner which you kill RGL is drag and drop between grids. I am sure RGL has its uses but for serious stuff your lib kills.

**Comment by adumesny** [comment]
good to hear as RGL has 4x the downloads GS has and was wondering why - need React wrapper and more snazzy demos. Large companies like I work have github cache so it likely only shows 1 download instead of the many places it is used, so download number are not everything...
