### ISSUE TITLE
Bugs with new fitToContent (1rem, calling cellHeight)

### ISSUE THREAD

**Issue by ExusAltimus** [gridstack/gridstack.js#2427]
## Subject of the issue
**Issue 1:** fitToContent / misbehaving not working when cellHeight is not an integer (1rem support)

**Issue 2:** Starting with column 2,  then changing the cellHeight, then changing the column to 1 will revert it back to 2 column

<s>**Issue 3:** Changing cellHeight will not auto size the cell to content height
NOTE: This may not be a bug and may be intended behavior, i.e call resizeToContent on cellHeight() call</s> **FIXED**

<s>**Issue 4:** Clicking add widget will not auto size the cell to the content height (added makeWidget version too because this is my typical flow)
NOTE: This may not be a bug and may be intended behavior, i.e call resizeToContent on widget add (addWidget or makeWidget)</s> **FIXED**

## Your environment
Gridstack Version 9.0.1 (using gridstack.extra.css)
Google Chrome, Edge

## Steps to reproduce

https://jsfiddle.net/zxwg5j7m/101/
Issue 1  + 3
![36b59a30de7c6c75bfe704f54d8347a9](https://github.com/gridstack/gridstack.js/assets/6841481/03f4548b-85a2-4600-ae6e-dad8f731af8b)

Issue 2
![4000c84651a8817f6bbd5c04b1ea4c41](https://github.com/gridstack/gridstack.js/assets/6841481/6b7674cb-1940-4c97-8825-d31551de1c57)

Issue 4
[![Image from Gyazo](https://i.gyazo.com/74247681b52fb54fdfd0ee03f6c43980.gif)](https://gyazo.com/74247681b52fb54fdfd0ee03f6c43980)

## Expected behavior
Cell should fit to content,
addWidget / makeWidget should auto size the cell
cellHeight should auto size the cell

**Comment by adumesny** [comment]
not surprised 1rem doesn't work. as for 3 & 4 changing cellHeight (with a px number) and adding widget/,akeWIdget should call resizeToContent ()

**Comment by ExusAltimus** [comment]
This is by far the best project I have found for dashboard-style widgets, other libraries don't have nearly all the features that this one does. I was also using a custom solution for resizing right before this came out so I decided to swap over and try it out. I've been slowly getting familiar with the code base so next time I run into something I'll put some effort into looking into a fix

**Comment by adumesny** [comment]
yeah, fitToContent is something my current project at work was needing (all previous were stretch to fit gridItem instead as mostly graphs) and after having it solved there I decided move the code to GS as I will possibly make live resizing be aware of fitToContent.

I actually need to support having a user size vs fitting to content as sometimes content is smaller so no need to waste space, but them max at user settable size when the content is too big (dynamic content), so big new feature still comming...

**Comment by adumesny** [comment]
3 and 4 are now fixed. others will have to wait...

**Comment by adumesny** [comment]
closing. # 2 is separate issue and should be filed if still present.
