### ISSUE TITLE
Wrong order of items when initialised from DOM elements in one column mode

### ISSUE THREAD

**Issue by rubjo** [gridstack/gridstack.js#2434]
## Different item order
Ordering is different when initialized with DOM elements in one-column mode.

## Your environment
* 9.1.0, any env

## Steps to reproduce
(Very) minimal reproduction:
https://jsfiddle.net/7pftvj0g/25/#run

A
1. Run the code with output window narrow enough to trigger one-column mode
2. Order is wrong

B
1. Resize the output window so it changes from multi to one-column mode
2. Order is correct

## Expected behavior
Order should be predictable and the same.

**Comment by adumesny** [comment]
don't think this ever worked... tricky as adding a second widget after the fact that will be forced to x:2 -> 0 doesn't know if it would be places after or before the exiting x:0 one. would have to go to some other 12 column layout to compare any order hitn as to which one wins...

this works fine though as they are placed together and can be ordered as expected:
```
var items = [
  {x: 0, y: 0, w: 2, h: 2, content: '0'},
  {x: 2, y: 0, w: 2, content: '1'},
}
var grid = GridStack.init().load(items);
```

**Comment by rubjo** [comment]
Going to close this one and make another issue with a minimal StackBlitz showing more precisely my scenario.

**Comment by rubjo** [comment]
So as per you request in #2443, this case was reworded and updated with more specific details and a more minimal reproduction.

**Comment by adumesny** [comment]
ok, different flow (from DOM) so now proper bug and likely regression from something I did...

**Comment by MasumMollik** [comment]
@rubjo Could you find any fix?

**Comment by rubjo** [comment]
No quick workarounds explored as of yet, no.

In my use case, I have three grid items with
```
gs-x="0" gs-y="0" gs-h="7" gs-w="4"
gs-x="4" gs-y="0" gs-h="7" gs-w="4"
gs-x="8" gs-y="0" gs-h="7" gs-w="4"
```
...and they always appear in reverse order when UI is loaded and GridStack initialized in mobile width.

My hopes are up, as @adumesny has marked this with `severity:important`. If no fix is possible, I'll probably initialize the grid in a different way or use alternatives.

**Comment by adumesny** [comment]
I'm sorry but you are all over the place on this one.
* first you added one widget at a time in 1 column and expected order in 12 to be retained (tricky)
* second (jsfiddle) above has them in DOM so we could fix the order as we can try to read them all at once and order.
* third above shows an array of them, and as I said ` GridStack.init().load(items);` should work (or used to).

Which is which ? all of the above ?
