### ISSUE TITLE
directionCollideCoverage doesn't find most overlapping node

### ISSUE THREAD

**Issue by jedwards1211** [gridstack/gridstack.js#2435]
Found while working on the code...

`overMax` needs to be moved outside of the `forEach` so that `directionCollideCoverage` returns the node with the most overlap, rather than the last node with >50% overlap

https://github.com/gridstack/gridstack.js/blame/32337b63be0799161f9fd2a763db901c569c3383/src/gridstack-engine.ts#L165

**Comment by adumesny** [comment]
hey thanks, yep makes sense.
