### ISSUE TITLE
Init with DOM elements: wrong initial order in one-column mode

### ISSUE THREAD

**Issue by rubjo** [gridstack/gridstack.js#2443]
## Different item order
Ordering is different when initialized with DOM elements in one-column mode.

## Your environment
* 9.1.0, any env

## Steps to reproduce
(Very) minimal reproduction:
https://jsfiddle.net/7pftvj0g/25/#run

A
1. Run the code with output window narrow enough to trigger one-column mode
2. Order is wrong

B
1. Resize the output window so it changes from multi to one-column mode
2. Order is correct

## Expected behavior
Order should be predictable and the same.

**Comment by adumesny** [comment]
please don't create another one. update the original.

**Comment by rubjo** [comment]
Done.
