### ISSUE TITLE
Can't shrink item when grid is full (when using max row size)

### ISSUE THREAD

**Issue by ashawthing** [gridstack/gridstack.js#2449]
## Subject of the issue
I have set row = 34 and added enough items to fill the screen. The next one I add is off the screen. I then try to shrink the previous items to make room for the new one to move onto the screen. 

However, resizing seems to be disabled. 

## Your environment
9.0.2

## Steps to reproduce
You **MUST** provide a working demo - keep it simple and avoid frameworks as that could have issues - you can use 
https://jsfiddle.net/adumesny/jqhkry7g

## Expected behavior
I would expect reducing the size of an item to still work. Seems reasonable that you can't make anything bigger.

**Comment by ashawthing** [comment]
I've added a very crude fix which gets me going for now. Updated moveNodeCheck() to do the simple case moveNode if the size is smaller - because we know it will be no worse making it smaller. 

  public moveNodeCheck(node: GridStackNode, o: GridStackMoveOpts): boolean {
    // if (node.locked) return false;
    if (!this.changedPosConstrain(node, o)) return false;
    o.pack = true;

    // simpler case: move item directly...
    if (!this.maxRow) {
      return this.moveNode(node, o);
    }

    // if shrinking can do simpler case
    if (o.x === node.x && o.y === node.y && o.w <= node.w && o.h <= node.h) return this.moveNode(node, o);

**Comment by adumesny** [comment]
| The next one I add is off the screen
that is the real problem - after that all bets are off and not surprised things fail... your workaround is just a bandaid.

Please provide a running example as bug requires to validate and debug the underlying issue.

**Comment by ashawthing** [comment]
This will do it. Use the button to add a widget and it will break the max row restriction. I'd then like to shrink the width of panel 1 so I can move the new panel into a valid position. 

https://jsfiddle.net/bxk2g9zr/

**Comment by adumesny** [comment]
again a bandaid. the out of bound widget should never have been added in the first place...

**Comment by ashawthing** [comment]
I've created a pull request for my change. I hope that is what you wanted. I'm not an expert when it comes to GIT my team uses TFS.

**Comment by adumesny** [comment]
it's ok thanks. I pushed in the fix as that was a commit and not a review for me to approve.
