### ISSUE TITLE
sizeToContent doesnt work for declarative Grid (setting attr. and classes before initialization)

### ISSUE THREAD

**Issue by Crismon96** [gridstack/gridstack.js#2452]
## Subject of the issue
sizeToContent is such a sweet feature that I am missing on all other grid solutions. Unfortunatly it doesn't seem to work on declarative grids (setting html attributes and classes). When using react setting the grid via classes and attributes is the most comfortable way. I also see no other way in rendering my Components and then applying them to the Grid afterwards, looking at the examples this seems to be the recommended approach in React.

## Your environment
  "gridstack": "9.1.0",
Firefox, Linux Mint => Happens everywhere

## Steps to reproduce
[Working Demo](https://jsfiddle.net/Crismon/4mtgs5wq/)
As you see in the demo Grid-Items are setup declarative. When the grid is initialized with `sizeToContent: true ` the grid is collapsed to items of w=1, the size of the content is disregarded.
It would be great to allow sizeToContent to work with this declarative approach.

## Expected behavior
The Grid should be initialized with each item sized to its contents like in the programmatic approach.

**Comment by Crismon96** [comment]
I just started using this awesome library. If there is another approach to make it work in React I would be delighted.

**Comment by adumesny** [comment]
your example is wrong. attr have to be on the grid-item, and yes `sizeToContent` is not currently an attr as I've been focusing on options as DOM layout really don't scale up nicely with frameworks (Ang/React/Vue) as you ned to sync between that framework and GS doing direct manipulation IMO - see https://github.com/gridstack/gridstack.js/blob/master/angular/README.md
https://jsfiddle.net/adumesny/w3741mpo

Also don't forget to donate as `sizeToContent` was a big V9 effort with no support from the community.

**Comment by Crismon96** [comment]
@adumesny Thanks for your quick response. You are right that my example was messed up, I fixed it up now. My problem is not that `sizeToContent` is not an attribute on the grid itself but that it doesn't size the grid-items to its content size if they are declared via the DOM. You can see that the height is correctly set by the grid but the width is not: https://jsfiddle.net/Crismon/4mtgs5wq/7/

I have taken a look at your linked solution for Angular. The problem is that the recommended approach in the docs is the DOM declaration for react and there are no working examples (as far as I have looked) to render a grid in another way, with or without sizeToContent.

My suggestion would be:
- ideally: to make `sizeToContent` work with a DOM defined Grid (height seems to work already, width doesn't)
- document on the property `sizeToContent` that it doesnt work with a DOM defined Grid
- produce a react example that loads a Grid programmatically so that `sizeToContent` works and link it in the examples.

@adumesny WDYT?

**Comment by adumesny** [comment]
did you look at my fixed version of your example, because it does size from the dom 150px attributes... I don't have the bandwidth to look at evey bug.
