### ISSUE TITLE
Modified sidebar items not draggable 

### ISSUE THREAD

**Issue by keymood** [gridstack/gridstack.js#2462]
## Subject of the issue
While drag and drop initially works well, any changes made to the sidebar items, such as applying filters, can cause the functionality to stop working correctly.

## Your environment
* version of gridstack.js: 9.2.0
* Chrome Version 116.0.5845.140 (Official Build) (arm64)/MacOs 13.2.1

## Steps to reproduce
[Working demo without framework](https://jsfiddle.net/6wy0ueqr/)
[Working demo using Vue 3.x](https://codesandbox.io/p/sandbox/cranky-cherry-xl8x6c?file=%2Fsrc%2Fcomponents%2FGsDD.vue%3A1%2C1-209%2C1)
In both demo, you have the capability to drag an item from the **Sidebar** and simply drop it into the right white space. This functionality operates fine. However, as soon as you attempt to update the Sidebar list by applying a filter, the drag-and-drop feature becomes unavailable.

## Expected behavior
The drag-and-drop functionality should persist even after filtering the Sidebar list.

**Comment by adumesny** [comment]
most likely your bug - whenever the list of item changes you need to call GridStack.setupDragIn() again for new items.
