### ISSUE TITLE
Can't listen any event of grid-item in nested like resize or dnd ...?

### ISSUE THREAD

**Issue by duonglong1911** [gridstack/gridstack.js#2463]
**Angular:**
I tried to create a nested grid. But all events of `<gridstack>` only are called when I affect in direct child, nested item is not.
I accessed lib and don't see any function event in `<gridstack-item>` component

**Comment by adumesny** [comment]
yeah I would need to add nesting of events to the lib, then fix the ng wrapper, which is currently not supported but could be added for the right donation.

**Comment by calebmgshort** [comment]
@adumesny What would the right donation be?

**Comment by adumesny** [comment]
PM me directly on slack. for one thing the CB signatures will have to change to now pass the grid instance, and recursively go up until outmer most grid is found and call that handler instead. and do I fix that just in angular (simpler but not correct for others) or in GS as well, but then the two will conflict and might get called twice... likely half a day of work.

**Comment by calebmgshort** [comment]
I managed to do it manually, but thank you for being responsive.

**Comment by duonglong1911** [comment]
> I managed to do it manually, but thank you for being responsive.
How do you do it? Can you show me your solutions pls!

**Comment by calebmgshort** [comment]
> > I managed to do it manually, but thank you for being responsive.
> > How do you do it? Can you show me your solutions pls!

Yeah sure. 

```
  public recursiveAddEventHandlers(grid: GridStack) {
    this.addEvents(grid);
    for(let node of grid.engine.nodes) {
      if('subGrid' in node) {
        this.recursiveAddEventHandlers(node.subGrid!);
      }
    }
  }

  private addEvents(grid: GridStack) {
    grid.on('change', (event: any, items: any) => {
      console.log('changed');

      // This is for if an item within a nested grid is relocated or resized, you have to check if the grid is over-extended
      let itemOverextension = containerOverextendedNumberOfRows(items);
      if(itemOverextension > 0) {
        this.extendItemRows(items[0].grid.parentGridItem, itemOverextension);
      }
    })
    .on('dropped', (event: any, previousNode: any, newNode: any) => {
      console.log('dropped');

      // This is if an item is moved into a nested grid
      let itemOverextension = itemOverextendingContainerBy(newNode);
      if(itemOverextension > 0) {
        this.extendItemRows(newNode.grid!.parentGridItem!, itemOverextension);
      }
    })
    .on('resizestop', (event: any, el: any) => {
      console.log('resizestop');

      // This is if an item which itself contains a nested grid is resized
      let n = el.gridstackNode;
      if(n.subGrid) {
        let itemOverextension = containerOverextendedNumberOfRows(n.subGrid.engine.nodes);
        if(itemOverextension > 0) {
          this.extendItemRows(n, itemOverextension);
        }
      }
    });
  }

  private extendItemRows(gridItem: GridStackNode, numberOfRows: number) {
    this.grid!.update(gridItem.el!, {h: gridItem.h! + numberOfRows})
  }

function containerOverextendedNumberOfRows(items: GridStackNode[]) {
  let extendAmount = 0;
  for(let item of items) {
    let itemOverextension = itemOverextendingContainerBy(item);
    if (itemOverextension > extendAmount) {
      extendAmount = itemOverextension;
    }
  }
  return extendAmount;
}

function itemOverextendingContainerBy(item: GridStackNode) {
  if(!item.grid!.parentGridItem) {
    return 0;
  }
  return item.y! + item.h! - item.grid!.parentGridItem.h!;
}
```

Note that I only have one grid at the topmost level. You'll have to call recursiveAddEventHandlers for every top-level grid.
Also note this solution only works with the first layer of nested grids. It stopped working 2 layers in because there is a bug in the repo in which the GridStackItem h property is incorrect (I think it's a bug). In my application it isn't important to allow a second layer of nested grids, so I just prevented nested grids:

```
  private customSubGridOptions: NgGridStackOptions = {
    column: 'auto',
    acceptWidgets: (element: Element) => {
      let el = element as any;
      if('subGrid' in el.gridstackNode) {
        return false;
      }
      return true;
    },
    ...this.customBaseOptions
  }
```

**Comment by duonglong1911** [comment]
> > > I managed to do it manually, but thank you for being responsive.
> > > How do you do it? Can you show me your solutions pls!
> 
> Yeah sure.
> 
> ```
>   public recursiveAddEventHandlers(grid: GridStack) {
>     this.addEvents(grid);
>     for(let node of grid.engine.nodes) {
>       if('subGrid' in node) {
>         this.recursiveAddEventHandlers(node.subGrid!);
>       }
>     }
>   }
> 
>   private addEvents(grid: GridStack) {
>     grid.on('change', (event: any, items: any) => {
>       console.log('changed');
> 
>       // This is for if an item within a nested grid is relocated or resized, you have to check if the grid is over-extended
>       let itemOverextension = containerOverextendedNumberOfRows(items);
>       if(itemOverextension > 0) {
>         this.extendItemRows(items[0].grid.parentGridItem, itemOverextension);
>       }
>     })
>     .on('dropped', (event: any, previousNode: any, newNode: any) => {
>       console.log('dropped');
> 
>       // This is if an item is moved into a nested grid
>       let itemOverextension = itemOverextendingContainerBy(newNode);
>       if(itemOverextension > 0) {
>         this.extendItemRows(newNode.grid!.parentGridItem!, itemOverextension);
>       }
>     })
>     .on('resizestop', (event: any, el: any) => {
>       console.log('resizestop');
> 
>       // This is if an item which itself contains a nested grid is resized
>       let n = el.gridstackNode;
>       if(n.subGrid) {
>         let itemOverextension = containerOverextendedNumberOfRows(n.subGrid.engine.nodes);
>         if(itemOverextension > 0) {
>           this.extendItemRows(n, itemOverextension);
>         }
>       }
>     });
>   }
> 
>   private extendItemRows(gridItem: GridStackNode, numberOfRows: number) {
>     this.grid!.update(gridItem.el!, {h: gridItem.h! + numberOfRows})
>   }
> 
> function containerOverextendedNumberOfRows(items: GridStackNode[]) {
>   let extendAmount = 0;
>   for(let item of items) {
>     let itemOverextension = itemOverextendingContainerBy(item);
>     if (itemOverextension > extendAmount) {
>       extendAmount = itemOverextension;
>     }
>   }
>   return extendAmount;
> }
> 
> function itemOverextendingContainerBy(item: GridStackNode) {
>   if(!item.grid!.parentGridItem) {
>     return 0;
>   }
>   return item.y! + item.h! - item.grid!.parentGridItem.h!;
> }
> ```
> 
> Note that I only have one grid at the topmost level. You'll have to call recursiveAddEventHandlers for every top-level grid. Also note this solution only works with the first layer of nested grids. It stopped working 2 layers in because there is a bug in the repo in which the GridStackItem h property is incorrect (I think it's a bug). In my application it isn't important to allow a second layer of nested grids, so I just prevented nested grids:
> 
> ```
>   private customSubGridOptions: NgGridStackOptions = {
>     column: 'auto',
>     acceptWidgets: (element: Element) => {
>       let el = element as any;
>       if('subGrid' in el.gridstackNode) {
>         return false;
>       }
>       return true;
>     },
>     ...this.customBaseOptions
>   }
> ```

I really appreciate that. Thanks! @calebmgshort

**Comment by fredericrous** [comment]
this issue actually highlights a regression. It was possible to listen to events on nested grids on v7. It was a bit tricky I admit, basically, you needed to add listeners on each subgrid. I was using a recursive function to do that and it worked pretty well. Also, we had to keep track manually if an item was added to a new parent or moved

**Comment by adumesny** [comment]
clsoign since there is a workaround and no-one wanted to donate to get this out of the box...
