### ISSUE TITLE
"Invalid height" error when inside flex container after updating 9.2.0 -> 9.2.1

### ISSUE THREAD

**Issue by elwynelwyn** [gridstack/gridstack.js#2469]
## "Invalid height" error when inside flex container after updating 9.2.0 -> 9.2.1

After applying update to 9.2.1 (from 9.2.0) in our project, we started getting a crash when initialising the dashboard.

> Uncaught Error: Invalid height

It seems a value of `'auto'` is being passed to `parseHeight`, which fails to match the regex, which is only looking for specific height values.

After a little digging, this seems to happen when the gridstack element is inside a flex container, which is how we're laying things out in our application.

## Your environment
* 9.2.1
* Chrome 117.0.5938.92, Debian

## Steps to reproduce
https://jsfiddle.net/qnx6pwL1/

(view devtools console)

## Expected behavior
Dashboard should behave like it did in 9.2.0, rendering correctly and not crashing out.

**Comment by Jopie01** [comment]
Since PR #2464 you must have `min-height` in your CSS for the `.grid-stack` class.

**Comment by adumesny** [comment]
yeah I made that change (back to what is always was) as my app needs to set min-height in CSS rather than minRow, but this shoudl work. will check the broken example.
