### ISSUE TITLE
Invalid drag offset when page scrolled after 9.3

### ISSUE THREAD

**Issue by AdrienClairembault** [gridstack/gridstack.js#2491]
## Subject of the issue

Trying to move widgets while the page is scrolled down lead to unexpected behavior.
It seems there is a noticeable vertical offset between the mouse position and the widget position, which get worse the lower you scroll down the page.
While at the top of the page (no scroll), there is no issue.

Example:

![gridstack](https://github.com/gridstack/gridstack.js/assets/42734840/612dfac0-1385-4e28-a779-8271b63c613e)

## Your environment
Official demo: https://gridstackjs.com/demo/
Latest release is 9.3.0 at this date, which I suppose the demo is using.

## Steps to reproduce
* Open https://gridstackjs.com/demo/float.html
* Move or expand the existing widget toward the bottom of the page to expand the available height as much as possible 
* Add another widget 
* Move the new widget around while the page is not scrolled, which should work as expected without issues
* As soon as you start scrolling down the page, moving the widget around no longer work as expected (there is a noticeable vertical offset between the mouse position and the widget position).

**Comment by AdrienClairembault** [comment]
Possibly related to change in b559a6f33c985475f6a9afe0f5d08bc28e64c814 ?

**Comment by adumesny** [comment]
@VincentMolinie can you please take a look. yeah scrolled content is something I didn't try before...

**Comment by VincentMolinie** [comment]
I do reproduce, I will try to check what's going on

**Comment by adumesny** [comment]
great thank you, as I was going to revert your changes until we have time to fix it otherwise. It's holding other changes I need for work and depend on scroll so can't use 9.3.0 right now

**Comment by AdrienClairembault** [comment]
I confirm that the fix is effective and solve the issue.
Thanks @VincentMolinie

**Comment by adumesny** [comment]
@Jenny3107 you manually pulled Vincent fix and tried that ? I'm not sure it's the right fix anyway, but away this week so limited access to work on this.

**Comment by Jenny3107** [comment]
No indeed sorry, I thought it had been put on the "master" branch, I just redid an "npm install" thinking the fix had been added. I tried directly on the site: https://gridstackjs.com/demo/web2.html 
No worries, I'll wait, thanks.
