### ISSUE TITLE
facing resize and overlap issues between items

### ISSUE THREAD

**Issue by adarsh-sourcefuse** [gridstack/gridstack.js#2494]
## Your environment
* version of gridstack.js - 8.3.0
* which browser/OS-chrome

## Steps to reproduce
Widgets getting overlap overlap each other and when items at last are dragged they reach above

## Expected behavior

https://github.com/gridstack/gridstack.js/assets/84174223/c2ef010f-7185-47de-aa4a-85943abe8b69

**Comment by adumesny** [comment]
looks like a CSS issue. also you need to use the latest (or 9.2 as 9.3 has known scroll drag issue) AND provide reproduceable test case for bug reporting.
