### ISSUE TITLE
"Invalid height" issue in Jest after 9.2.1 update

### ISSUE THREAD

**Issue by evgeniyefimov** [gridstack/gridstack.js#2497]
## Subject of the issue
After upgrading gridstack from version 9.2.0 to 9.3 "Invalid height" issue started throwing when we try to detect changes for our component in our spec file. It was working fine before 9.2.1 update.

## Your environment
* version of gridstack.js - 9.3.0
* which browser/OS - Chrome, Windows 10, NodeJS 18.15, npm 9.4

## Steps to reproduce
https://github.com/evgeniyefimov/gridstack_tests_issue
Just run tests. And you will see an issue on line `fixture.detectChanges();` with this error.

## Expected behavior
Should work fine as it was before 9.3.0

**Comment by adumesny** [comment]
@VincentMolinie another one for you...

**Comment by VincentMolinie** [comment]
Hey @evgeniyefimov,
How am I supposed to run your tests ? `npx jest .` throws that there is missing libraries 🤔

**Comment by VincentMolinie** [comment]
This one seems relted to this one: https://github.com/gridstack/gridstack.js/issues/2469

**Comment by adumesny** [comment]
@evgeniyefimov can you verify when this actually started showing up ? (i.e. 9.2.2) so we can narrow it down - I don't have time to debug it right now.
@VincentMolinie you may be right, the title I assumed it was 9.3 only (only your changes)

**Comment by evgeniyefimov** [comment]
@adumesny 
9.2.0 works fine
![image](https://github.com/gridstack/gridstack.js/assets/11611433/e3e1789e-90e0-4a7e-a416-68a796054585)

looks, like the issue is in 9.2.1
![image](https://github.com/gridstack/gridstack.js/assets/11611433/219d100d-b855-4e84-ae6a-a2c3ae55e389)

I upgraded my Gridstack from 9.2.0 directly to 9.3.0, so I was thinking that the issue is in the 9.3.0. Sorry.

**Comment by adumesny** [comment]
@evgeniyefimov  next time please  including the callstack to I don't have to pull in your change, yarn install and run the test myself (big time sync).
And don't forget to donate if you find this lib useful!
