### ISSUE TITLE
Drag and drop a widget on top of a locked widget

### ISSUE THREAD

**Issue by rsalcedo6** [gridstack/gridstack.js#2503]
## Subject of the issue
It is possible to drag one item and drop it such that it overlaps with a locked widget.

## Your environment
GridStack 9.3.0
Windows 10
Chrome browser

## Steps to reproduce
Please check out the jsfiddle. There are reproduction steps and grid items to reproduce
https://jsfiddle.net/richsalcedo6/c142owne/

## Expected behavior
I would expect that the drop would not be possible

**Comment by adumesny** [comment]
good demo. you'll notice 3 & 4 cannot be placed on the locked one, but when moving 2 it does multiple collision and the logic fails there. complex case.

**Comment by rsalcedo6** [comment]
> good demo.

Thanks! 

>  it does multiple collision and the logic fails there.

I spent some time looking at the code last night seeing if I could find where the issue occurs. It was my first time in the code base so it's very unfamiliar to me. I will help as much as I can.

**Comment by adumesny** [comment]
likely a hard one to fix unless you know the code and side effects... might be best to donate to have me fix it and unlikely I will do this corner case otherwise...
