### ISSUE TITLE
vue3 failed to run

### ISSUE THREAD

**Issue by Chen-Yong-Jie** [gridstack/gridstack.js#2510]
## Subject of the issue
vue3 + TS  Use "gridstack" to report errors

If unsure if lib bug, use slack channel instead: https://join.slack.com/t/gridstackjs/shared_invite/zt-1jobnclsy-FqGGeLX5dFPM_ZQzTunBsw

## Your environment
* gridstack.js 9.4.0 
* Chrome

## Expected behavior
![image](https://github.com/gridstack/gridstack.js/assets/52515060/3fe93bb2-4425-4366-a514-305a6c1c120b)

**Comment by Chen-Yong-Jie** [comment]
7.3.0 there is no problem with the version. After 8.0.0, it will report an error.

**Comment by azusa5526** [comment]
It works for me in Vue3 with Typescript.
Live Demo: https://stackblitz.com/edit/vue3-vite-typescript-starter-y6b1ds?file=src%2FApp.vue

So...what's your problem?

**Comment by adumesny** [comment]
closing since others are fine and you are not providing running example. use slack for Q
