### ISSUE TITLE
sizeToContent issue on layout init. Unexpected resizing behaviour

### ISSUE THREAD

**Issue by AlexanderFalk** [gridstack/gridstack.js#2519]
## Subject of the issue
I am working on a Widget system for my application. Everything works smooth but I have come across a weird issue and I am lost on how to fix it. Therefore, I am reaching out for help.

When I init my layout, my widgets are not sizing to the content. If I then resize my browser window by just an inch, everything works as expected. Checkout the two videos in **Steps to Reproduce**.

**Additional information:**
I have two grids:
One functioning as a toolbox of widgets the user can drag from
_OPTIONS:_
```
gridOptions: NgGridStackOptions = {
    margin: '5px 5px 15px 5px',
    column: 3,
    cellHeight: 20,
    float: false,
    sizeToContent: true,
    acceptWidgets: true,
    disableOneColumnMode: false,
    disableResize: true,
    disableDrag: true,
    removable: '.widgets-action-tool-container-right',
  };
```
One functioning as a main grid
_OPTIONS:_
```
widgetToolGridOptions: NgGridStackOptions = {
    margin: '5px 5px 15px 5px',
    column: 1,
    cellHeight: 40,
    disableOneColumnMode: true,
    sizeToContent: true,
    removable: '.widgets-action-tool-container-right'
  };
```

## Your environment
* version of gridstack.js - 9.2.2
* MacOS Sonoma 14.0
* The application uses Angular 16 as framework

## Steps to reproduce

(Sorry for the danish)

The `sizeToContent` issue:
https://github.com/gridstack/gridstack.js/assets/8970495/7ffd492f-2712-40cb-b4ce-fffbeeab7bbb

When adding from one grid to another:
https://github.com/gridstack/gridstack.js/assets/8970495/d981c9d1-707e-4146-a170-26c1f9a957c4

## Expected behavior
I expect the content to size properly on init and not only when resizing my browser window.

This may be misconfiguration and I hope someone out there can help me out.

**Comment by adumesny** [comment]
please use slack channel for Q since this isn't a reproduceable lib bug posted...
