### ISSUE TITLE
NG0912: Component ID generation collision detected. Components GridstackItemComponent / GridstackComponent'

### ISSUE THREAD

**Issue by ringo-anva** [gridstack/gridstack.js#2526]
Describe your issue:

Switching between different pages is given us the following warnings:

NG0912: Component ID generation collision detected. Components 'GridstackItemComponent' and 'GridstackItemComponent' with selector 'gridstack-item' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912

NG0912: Component ID generation collision detected. Components 'GridstackComponent' and 'GridstackComponent' with selector 'gridstack' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912

We also have a few gridstack related bugs and we expect that these warnings are the root cause of that.

We have a Module Federation setup and gridstack (angular version) is used in different remotes.

In our code we use like:
import { GridstackComponent } from 'gridstack/dist/angular';

## Your environment
Version 9.1 
Chrome/Mac

## Expected behavior
No warnings

Hope you can give us some hint.

Cheers,
Ringo.

**Comment by adumesny** [comment]
no idea. you need to post the simplest possible case showing the issue if the bug is in the lib.

**Comment by ringo-anva** [comment]
@adumesny simplest possible case can be found here:
https://github.com/ringo-anva/gridstack

I created one host and two remotes. 

When you  switch between remote 1 and remote 2 you will get the 'warning' (which causes some issue for us):

NG0912: Component ID generation collision detected. Components 'GridstackItemComponent' and 'GridstackItemComponent' with selector 'gridstack-item' generated the same component ID. To fix this, you can change the selector of one of those components or add an extra host attribute to force a different ID. Find more at https://angular.io/errors/NG0912

Cheers,
Ringo.

**Comment by ringo-anva** [comment]
@adumesny 

Steps to Reproduce:
checkout main at repo https://github.com/ringo-anva/gridstack
npm install
npm run start
open devtools console
click on menu option 'remote 1'
click on menu optioni 'remote 2'

**Comment by csgentile** [comment]
Hi @ringo-anva. I saw that you marked as solved in your problem in this issue >>> [#20430](https://github.com/nrwl/nx/issues/20430).

I checked your repo but you haven't posted yet the changes you made to make it work. Could you share your solution to see what approach did you follow? I need to see what should I change in my project configuration in order to get rid of this problem.

Thanks in advance.

**Comment by ringo-anva** [comment]
@csgentile 
At file module-federation.config.ts in each remote and host add:

+  additionalShared: [
+    {
+      libraryName: 'gridstack/dist/angular',
+      sharedConfig: { singleton: true },
+    },

So something like:

import { ModuleFederationConfig } from '@nx/webpack';

const config: ModuleFederationConfig = {
  name: 'apps/gridstackmf/remote1',
  exposes: {
    './Routes': 'apps/gridstackmf/remote1/src/app/remote-entry/entry.routes.ts',
  },
+  additionalShared: [
+    {
+      libraryName: 'gridstack/dist/angular',
+      sharedConfig: { singleton: true },
+    },
  ],
};

export default config;

Good luckj.
