### ISSUE TITLE
Incorrect layout on grid load in one column mode

### ISSUE THREAD

**Issue by Jacccop** [gridstack/gridstack.js#2527]
## Description
Loading the saved layout in one column mode does not correctly display the layout, however the layout gets fixed on additional default mode load.

## Environment
* gridstack.js 9.5
* Chrome - reproduced on the serialization demo

## Steps to reproduce
![gridstack-load-bug](https://github.com/gridstack/gridstack.js/assets/56170241/43c5e0bc-a64d-4f6f-9639-2a4e06a15de0)

## Expected behavior
The layout that was saved is correctly loaded in both one-column and default mode

**Comment by adumesny** [comment]
much harder than I expected to debug and fix... will be in next release.

don't forget to donate if you find this lib useful!
