### ISSUE TITLE
Custom Column CSS Documentation

### ISSUE THREAD

**Issue by DoisKoh** [gridstack/gridstack.js#2528]
## Custom Column CSS Documentation
The current documentation on Custom Column CSS seems to be lacking a lot of information:
https://github.com/gridstack/gridstack.js#custom-columns-css

The required CSS change is clear, but it's not mentioned which CSS needs to be excluded. It looks to me that we still need the rest of the `gridstack.css` styles, but we need to replace the `left` and `width` CSS values, which means we'll want to have more specific CSS selectors to override these values.

Once you do that, you'll then find that there's min-width CSS that's overriding your new CSS width that might also need to be overridden.

Alternatively, you could view that as a bug if you actually don't intend for users to have to deal with the min-width CSS.

I know this might be a low priority item but I believe it should also be pretty low-hanging fruit; it would be great if there's more detail on this as it seems to me the steps on replacement are incomplete.

Thanks!

**Comment by adumesny** [comment]
the 4-column example is correct and only thing you need to include with regular gridstack.css with does 1 and 12 and other css.
gridstack-extra.css has this for 2-11 column and already documented.
