### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by gtb104** [gridstack/gridstack.js#2536]
In a test environment (testem), I'm seeing null pointer exceptions.
```
gridstack.js:419 Uncaught TypeError: Cannot read properties of undefined (reading 'nodes')
    at eval (gridstack.js:419:152)
```
https://github.com/gridstack/gridstack.js/blob/0f3456f28afa5cafffb0c84c7ba7326cd301cfce/src/gridstack.ts#L1704
My guess is that this happens due to the quick setup/destroy cycle of tests. Is there a way to safeguard against this? Or could we change that line to be `this.engine?.nodes`?

**Comment by adumesny** [comment]
fixed in 9.5.1 (you didn't say what rev)
