### ISSUE TITLE
Inconsistency in setting height of grid-stack-item

### ISSUE THREAD

**Issue by sharmaa-a** [gridstack/gridstack.js#2537]
## Subject of the issue
I am using the gridstack library in my react app to load remote apps (using the module federation arch). We want to give users the flexibility to see whatever they want based on a list of options but for now just starting with one remote app, so only one `.grid-stack-item` and one `.grid-stack-item-content` class.
The div in which I am using gridstack is of a fixed height, I can't go beyond that so I have fixed the height of 
`.grid-stack`  and `.grid-stack > .grid-stack-item` to be the same as the main div height with `!important` and this solves my issue  temporarily but it is not sustainable in the long run. 
On the initial load of the app, everything is fine but the app has multiple tabs and if I switch between them and come back to the page containing gridstack then the height of the `.grid-stack-item` class changes and I am also able to resize it beyond the container - the actual content doesn't go beyond the container but when you hover over it, you can see that the grid-stack-item goes beyond and even the resize handle appears outside the div.  
I am sure there is a way but I don't know how to set the height of the items dynamically in such a way that they don't go beyond the max height of the container and also occupy the full height on initial load and can then be resized however the user desires because right now I am only able to resize width-wise and not height-wise.
I have attached the js-fiddle below where you can see that the content is spilling outside the grid-stack container and the resize handle is way below the containter
(Please un-comment the commented lines to see how I am getting it to work currently but that's not correct, you can also comment out line 16 in the css file)
I noticed that on every switch between apps the `gs-id` value changes (attaching screenshots of the same element) - why are the gs-id values being changed for the same grid on every reload?
<img width="360" alt="Screenshot 2023-11-15 at 14 33 21" src="https://github.com/gridstack/gridstack.js/assets/109473909/8173a672-3fc5-4fa2-ad55-28c494007bd7">
<img width="348" alt="Screenshot 2023-11-15 at 14 35 49" src="https://github.com/gridstack/gridstack.js/assets/109473909/cce477c7-40b6-43f4-ab80-48488a4acee0">

## Your environment
* version of gridstack.js - ^9.3.0
* which browser/OS - Chrome

## Steps to reproduce
https://jsfiddle.net/guk2nsfj/

## Expected behavior
The grid-stack-item resize should not spill beyond the container div and the user should be able to resize height-wise as well as width-wise

**Comment by adumesny** [comment]
you edxample is not showing anything (missing extra.css for 3 column for one thing). I don't have time to read all your text, get to the point and make it simple. closing until you do.
![image](https://github.com/gridstack/gridstack.js/assets/3496166/48f66171-21ab-4b69-a2ca-edf601474e9d)

**Comment by sharmaa-a** [comment]
When I click on the link, I am able to see the example
<img width="1503" alt="Screenshot 2023-11-15 at 16 01 33" src="https://github.com/gridstack/gridstack.js/assets/109473909/95a0b04a-be6e-4de6-890c-383d5cf14e9c">

**Comment by adumesny** [comment]
make it wider or `disableOneColumnMode:true` and it disapear (3 column require extra.css - see the doc)

**Comment by sharmaa-a** [comment]
Attaching the video here:

I need to manually set the height of `.grid-stack-item` so that it doesn't overflow but I am unable to resize it vertically as can be seen in the video either way. 
Manually setting the height is not sustainable because soon we will add more widgets and want the users to position/resize however they like

https://github.com/gridstack/gridstack.js/assets/109473909/ed2ce8d0-34e0-4029-8ec3-365865806b27
