### ISSUE TITLE
Header Selection Widget (Placeholder) for Dashboard Complex Grid-Stack-Item

### ISSUE THREAD

**Issue by nexpromedia** [gridstack/gridstack.js#2541]
Is it possible to offer about 20-30 widgets through the dashboard, which are small and possibly accompanied by an image, and show complex content when dragged and dropped into the dashboard:

The goal is to have a selection (thumbnail view) where you can drag and drop into the dashboard, and there it will display its actual size and content, including dynamic content.
Is it also possible to remove a widget from the selection once it has been moved into the dashboard, and make it available again in the selection if it is deleted???

Thank you, hope this works.

For example, an MP4

https://github.com/gridstack/gridstack.js/assets/90003430/06f405c3-f314-46ad-852c-ec3f8d7ff9fa

**Comment by adumesny** [comment]
once again, use slack channel for questions. this is for bug reports only.

**Comment by nexpromedia** [comment]
Yes, I would like to, but I don't know Slack and on the homepage gridstackjs.com -> Slack
the following error message appears:

SLACK
The link is no longer active

To join this workspace, you must ask the person who originally invited you to send you a new link.


what happens next???

Best regards, Gert

**Comment by adumesny** [comment]
try now. had not pushed some changes...

**Comment by nexpromedia** [comment]
no works Slack

**Comment by adumesny** [comment]
if the generic link doesn't work then I need to go back to an invite link (which is only good for 30 days... which really sucks.
https://join.slack.com/t/gridstackjs/shared_invite/zt-27q0rwf80-5vCt81Z_hfVgpRW7L17MnQ let me know if you HAD to use this instead.
