### ISSUE TITLE
Gridstack cuts bottom off content when using sizeToContent

### ISSUE THREAD

**Issue by Duberry** [gridstack/gridstack.js#2551]
## Subject of the issue
When using sizeToContent, Gridstack is cutting the bottom 20px (approx) off my content.

I'm pulling div content via an ajax call, and then inserting it using addWidget.

Content is inside divs with the bootstrap card class.

## Your environment
10.0.0
Bootstrap 5.3

## Steps to reproduce

(Example)

`
<div class="grid-stack"></div>

                    <script type="text/javascript">
                        var items = [];
                        var options = { 
                            column: 2,
                            cellHeight: 1,
                            resizable: { handles: 'none'} // do all sides for testing
                        };
                        var grid = GridStack.init(
                            options
                        );
                        grid.load(items);

 layouts = [{
                            function: "html_return_element"
                        }]

function get_grids() {
                            $(layouts).each(function(i, e) {
                                $.post("/my_ajax_getter.php", {
                                        function: e.function,
                                    },
                                    function(response) {
                                        grid.addWidget({content: response.html, sizeToContent: true});
                                    })
                            });
                        }

get_grids();
</script>
`

## Expected behavior

Should have the size of the widget automatically set to contain the whole of the html. Instead, the element vertical size is too small.

Seen:
![image](https://github.com/gridstack/gridstack.js/assets/22213699/89d451a5-7012-4cc6-9dc6-58d58516e569)

Expected:
![image](https://github.com/gridstack/gridstack.js/assets/22213699/ead76b29-8736-4f0f-826d-5d3a15a77589)

**Comment by adumesny** [comment]
you need to provide a running example (simplest possible) to debug it, or debug it yourself looking at resizeToContent()
