### ISSUE TITLE
sizeToContent is not triggered when initializing from HTML

### ISSUE THREAD

**Issue by vmihailenco** [gridstack/gridstack.js#2552]
## Subject of the issue

When initializing GridStack from HTML, the items are not automatically resized to content. As a workaround, you can still manually resize the item or add `grid.cellHeight(50);` to trigger an update.

For example:

```
      let grid = GridStack.init({
        handle: ".card-header",
        sizeToContent: true,
        cellHeight: 49,
      });
      // Uncomment the following line.
      //grid.cellHeight(50);
```

## Your environment

Can be reproduced on Chrome with GridStack 9 and 10.

## Steps to reproduce

1. Run https://jsfiddle.net/owzvb79t/
2. Uncomment `grid.cellHeight(50)` to get the desired behavior.

## Expected behavior

The item should be automatically sized to content after initialization.

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful!

**Comment by vmihailenco** [comment]
@adumesny thanks, but nothing really changed... Here is the updated fiddle for v10.0.1: https://jsfiddle.net/19mj7r5o/

**Comment by thadguidry** [comment]
You need to use the correct URL in the JSFiddle Resources?  If you hover over it, you will see tt's pointing to 10.0.0
https://cdn.jsdelivr.net/npm/gridstack@10.0.0/dist/gridstack-all.js
and should be
https://cdn.jsdelivr.net/npm/gridstack@10.0.1/dist/gridstack-all.js

**Comment by vmihailenco** [comment]
@thadguidry I did just that, but somehow messed it up. All seems to be good now: https://jsfiddle.net/927om8he/2/

**Comment by adumesny** [comment]
I used the official demo to fix html init (second grid of https://gridstackjs.com/demo/sizeToContent.html)
