### ISSUE TITLE
[Bugs] Add a new widget in one column mode will affect the layouts after you switch back to multiple columns.

### ISSUE THREAD

**Issue by yesterdaytime** [gridstack/gridstack.js#2559]
## Subject of the issue
When I try to add a new widget in one column, it will reset all the nodes in one modal and doesn't change back them the correct position in multiple columns mode. 

## Steps to reproduce
1. start the gridstack.js angular example, and select component ngFor example. 
2. Add 3 widgets. 
3. Change the chrome width and make the widget show in one column.
4. Add a widget and change the chrome width to back multiple columns mode. 

## Expected behavior
The 3 widgets should be at the top.

## Actual behavior
The 3 widgets at the left.

**Comment by adumesny** [comment]
depends on where you add that 4th widget in 1 column. post a video or picture of what you are doing...

**Comment by yesterdaytime** [comment]
The first time, item 1, item 2, and item 20 at the top, I wanted to keep them at the top after I added a new one in the one column mode, but they changed to the left.  I need to change them to the top again. I think the new widget position only affects item 20, it doesn't affect item 1 and item 2. 

https://github.com/gridstack/gridstack.js/assets/14917134/ec6bce95-858c-4b1e-a508-f941e5051b4c

**Comment by adumesny** [comment]
I changed the demo to append new item at the end rather than specific location which is hard to predict when doing in 1 column vs 12 anyway.
don't forget to donate if you find this lib useful!
