### ISSUE TITLE
Unknown option: responsive

### ISSUE THREAD

**Issue by vmihailenco** [gridstack/gridstack.js#2568]
The documentation mentions `responsive` option in several places, but it does not do anything. The [example](https://gridstackjs.com/demo/responsive_break.html) you have actually uses `columnOpts`.

![responsive](https://github.com/gridstack/gridstack.js/assets/290976/4185e4e5-dd3b-4e02-9c62-51c4aeeb31d4)

**Comment by adumesny** [comment]
oops, renamed to after initial version. will fix doc.
