### ISSUE TITLE
How to drag between 2 grids in react 18

### ISSUE THREAD

**Issue by liqiuqiui** [gridstack/gridstack.js#2586]
## Subject of the issue
I encountered a problem using gridstack in React18. When two grid stacks are dragged and released between each other, the update of the grid item will throw an error of "Failed to execute 'removeChild' on 'Node'". I don't know how to solve this problem so that the grid stack can be used normally in React18

## Your environment
* version of gridstack.js  v10.0.1
* which browser/OS  Chrome 120.0.6099.109

## Steps to reproduce
The reproducing step is to directly change the react and react dom versions in the react books controlled multiple demo from 16 to 18, and then change the ReactDOM.render(<ControlledExample/>, document. getElementById ('controlled-stack')to ReactDOM.createRoot (document.getElementById ('controlled-stack')).render(<ControlledExample/>) and drag a widget to the other side to trigger the bug
![Uploading 2023-12-19 10.36.54.gif…]()

**Comment by adumesny** [comment]
please provide a running example - don't have me follow your steps to create one...

**Comment by liqiuqiui** [comment]
Sorry for my mistake, this is the online link: https://jsfiddle.net/74xzgkdc/

**Comment by fredericrous** [comment]
what is working for me on react is to assign each node an id and replace the content of each node by the content of a react portal. That way I let gridstack manipulate the dom

**Comment by QiuYiLiang** [comment]
You can use wrapper element

`<div className="grid-stack" ref={gridContainerRef}>
        {items.map((item, i) => {
          return (
            <div key={item.id}>
              <div
                ref={refs.current[item.id]}
                className="grid-stack-item"
                gs-id={item.id}
                gs-w={item.w}
                gs-h={item.h}
                gs-x={item.x}
                gs-y={item.y}
              >
                <div className="grid-stack-item-content">
                  <Item {...item} />
                </div>
              </div>
            </div>
          );
        })}
      </div>`

**Comment by QiuYiLiang** [comment]
You can use wrapper element
![企业微信截图_17031431141041](https://github.com/gridstack/gridstack.js/assets/49298714/7ab717a0-5cd0-4882-a25f-0051d31860a6)
@liqiuqiui

**Comment by Suesanz** [comment]
> You can use wrapper element ![企业微信截图_17031431141041](https://private-user-images.githubusercontent.com/49298714/297586583-7ab717a0-5cd0-4882-a25f-0051d31860a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NTU3NzIsIm5iZiI6MTcwNTU1NTQ3MiwicGF0aCI6Ii80OTI5ODcxNC8yOTc1ODY1ODMtN2FiNzE3YTAtNWNkMC00ODgyLWEyNWYtMDA1MWQzMTg2MGE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDA1MjQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZDE5OGNjNzBiOWJkMzU4Mjk3M2EyMjQxYzQ5OWJhM2Y4YzAzMWRiNmUyODZkYTk5NjJkNGZlMmI5NWY0NmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S6jG7VL29KHLylT_cEce6hFVDoNfnbMfWA0ubaIO_h0) @liqiuqiui

@QiuYiLiang Is this working for you? It's not working for me, because the issue remains the same here as well. When you drag and drop across grids, your element parent has changed in real DOM but not in virtual DOM and when react tries to delete it, because of parent mismatch it throws the error.

**Comment by QiuYiLiang** [comment]
@Suesanz Yes, this is my example
[https://codesandbox.io/p/github/QiuYiLiang/test-gridstack/main](https://codesandbox.io/p/github/QiuYiLiang/test-gridstack/main)

**Comment by Suesanz** [comment]
@QiuYiLiang I was referring to moving items across 2 grids. Your example has 1 grid and another subgrid inside it.

**Comment by QiuYiLiang** [comment]
@Suesanz 2 grids also work fine

**Comment by QiuYiLiang** [comment]
@Suesanz grid.load will move the grid-stack-item element below grid-stack, and the packaging element will be retained for deletion by react to avoid errors.

**Comment by QiuYiLiang** [comment]
grid.load will move the grid-stack-item element below grid-stack, and the wrapper element will be retained for deletion by react to avoid errors.

**Comment by adumesny** [comment]
heads up - in Angular I don't use ngFor loop to layout the widgets and create the grid - for exactly the reason above (keeping Angular GS in sycn is a pain). instead I let angular create the CONTENT of those gridItem with custom components/tags/etc... the grid itself is created using `load()` from a complete JSon (which gets saved to backend). dragging between grids (and also not wanting to re-create things) is much easier that way. React/Vue (which I don't know) woudl benefit the same...

**Comment by adumesny** [comment]
can one of you React dev update the demos to showcase the way to do it ? I don't know React

closing as there are way to get it working, as clearly demonstrated by my Angular version (same virtual DOM issues)
