### ISSUE TITLE
Rearangement when dropping

### ISSUE THREAD

**Issue by tomaswallentinus** [gridstack/gridstack.js#2589]
Hi, I would like to sponsor this update and have sent an gift through Paypal from ekonomi@filmcafe.se, tell me if you need more time to work on this particular problem. Regards Tomas
PS. Awesome work with this product by the way. Will be using it to generate our newsletters. DS.

## Subject of the issue
When I drag a new items into grid, previous items get rearranged event though they don't have to.

## Your environment
NVM build date 29:th of december
MacOS 14.2 Chrome 120.0.6099.129 and Safari 17.2

## Steps to reproduce
https://jsfiddle.net/fn2xkbad/
https://github.com/gridstack/gridstack.js/assets/6619684/b8d3420c-940f-4d2b-9158-bbea574da940

## Expected behavior
I would like it if the previously dropped elements stay in place when I drop the new element in a non conflict area.

**Comment by adumesny** [comment]
thank you for the donation. You can do what you want: ability to pause drag&drop collision until the user stops moving - see `DDDragOpt.pause` (used for creating nested grids on the fly based on gesture).
so `GridStackOptions.draggable.pause:true` should do it
