### ISSUE TITLE
load or save incorrect in nested grid example

### ISSUE THREAD

**Issue by fredericrous** [gridstack/gridstack.js#2595]
## Your environment

* version of gridstack.js - v10.0.1
* which browser/OS

## Steps to reproduce

- go to https://gridstackjs.com/demo/nested.html
- click "Save List"
- click "Clear"
- click "Load"

## Expected behavior

Instead of the expected grid
<img width="1262" alt="image" src="https://github.com/gridstack/gridstack.js/assets/702227/0f661b6e-3c11-44b7-8e90-2f7376ee0f92">

I get the following

<img width="1248" alt="image" src="https://github.com/gridstack/gridstack.js/assets/702227/e4f8abb2-075b-4e0a-9514-daa51525ec19">

**Comment by adumesny** [comment]
not a bug. there is the entire save that saves all the setting including nested grid options (like 4 column instead of 12). save list jsut saves widget x,y
