### ISSUE TITLE
5版本升级10问题（gridstack/dist/h5/gridstack-dd-native找不到）和点击事件问题；Version 5 upgrade 10 problem (Gridstack/Dist/H5/Gridstack-DD-Native not found) and click event problem.

### ISSUE THREAD

**Issue by numbrun** [gridstack/gridstack.js#2597]
# 我是从"gridstack": "^5.1.1",升级到"gridstack": "^10.0.1",之后，我过去引入的 import 'gridstack/dist/h5/gridstack-dd-native';在10版本中失效了，这个文件主要是响应式的 适用于移动端，现在10版本不支持响应式了吗 我想移动端也可以看 改变布局应该怎么做
# 此外，这个框架的点击事件怎么没有啊，我用的vue3版，主要通过js的for循环去动态拼接html，虽然我可以写原生的dom点击事件，但是对当前行的数据想要得到，是不太容易的，这种情况该怎么解决呢

期待你的回复以及指导

# I upgraded from "gridstack": "^5.1.1" to "gridstack": "^10.0.1", and then I introduced Import' Gridstack/Dist/H5/Gridstack-DD-Native'; It failed in version 10. This file is mainly reactive and suitable for mobile terminals. Now version 10 doesn't support reactive? I think the mobile terminal can also see what to do when changing the layout.
# In addition, why isn't there a click event in this framework? I use version vue3 to dynamically splice html mainly through js's for loop. Although I can write native dom click events, it is not easy to get the data of the current line. How to solve this situation?

Looking forward to your reply and guidance.

**Comment by adumesny** [comment]
see https://github.com/gridstack/gridstack.js?tab=readme-ov-file#migrating-to-v6
the file name changed.

**Comment by numbrun** [comment]
Ok, thank you. It has been solved. If the click event is added by addWidget, is there any relevant api?
