### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by leocharrua** [gridstack/gridstack.js#2598]
Hello. I have a grid with image buttons (like a menu of buttons).

I need a responsive behaivor, like this:

Xs: 6 cols (two items in a row)
Sm: 3 cols (four items in a row)
Xl: 2 cols (six items in a row)

How I can do that with gridstack?

How I can set the width and the height of the grid-stack-item to the width and the height of the button (image inside)? Actually, when I resize the windows to lower size, the buttons get smaller (cropped), I don't wanna that, I need the buttons change the row.

Can you help me?

PS: I'm using ionic 7 with angular 17

Thanks

**Comment by adumesny** [comment]
use slack channel for questions.

**Comment by leocharrua** [comment]
Hello. Thanks, but I can't find the gridstack slack channel, can you invite me? leocharrua@hotmail.com. Thanks

**Comment by adumesny** [comment]
on landing page: Join us on Slack: [https://gridstackjs.slack.com](https://join.slack.com/t/gridstackjs/shared_invite/zt-27q0rwf80-5vCt81Z_hfVgpRW7L17MnQ)

**Comment by gazhay** [comment]
You can't see very much on slack if you don't pay though ?
