### ISSUE TITLE
Issue with Angular Gridstack Wrapper: Unable to Integrate into Project

### ISSUE THREAD

**Issue by usrAnk** [gridstack/gridstack.js#2616]
I hope this message finds you well. I am new to both Angular and Gridstack and am currently working on an Angular 12 project. I am facing challenges in integrating the Gridstack Angular wrapper and implementing specific functionalities.
I am seeking guidance on how to integrate the Gridstack Angular wrapper into an Angular 12 project. Additionally, I am aiming to create a draggable grid with the ability to dynamically add new widgets using a "Add Grid" button.
If anyone could provide step-by-step instructions or code examples for achieving this functionality, it would be immensely helpful. I greatly appreciate your expertise and assistance in this matter.
Thank you for your time and support.

**Comment by adumesny** [comment]
responded in slack.
