### ISSUE TITLE
"autoPosition" is not working correctly

### ISSUE THREAD

**Issue by hatta-takuya** [gridstack/gridstack.js#2631]
## Subject of the issue
In the `react-hooks-controlled-multiple.html` demo, when x, y are unspecified
widget is not added in the correct position.

## Your environment
* version of gridstack.js - 10.1.1
* which browser/OS - win11/edge, chrome

## Steps to reproduce
Just removed x, y options.
https://codepen.io/hjerhfqj-the-solid/pen/dyLMJpW

## Expected behavior
New widget should be placed in the empty area.
(v8.2.0 works well)

**Comment by hatta-takuya** [comment]
v10.1.2 fixed this issue. thanks.
https://codepen.io/hjerhfqj-the-solid/pen/ExJomzo

**Comment by adumesny** [comment]
glad. don't forget to donate if you find this lib useful!
