### ISSUE TITLE
full grid crashes on drop of new item

### ISSUE THREAD

**Issue by piotretm** [gridstack/gridstack.js#2633]
## Subject of the issue
If the grid is full and I try to drop an item from outside there is an unhandled error, which crashes the grid.

![image](https://github.com/gridstack/gridstack.js/assets/143094148/5e00371c-be84-475e-ae39-78459d9325a9)
![image](https://github.com/gridstack/gridstack.js/assets/143094148/48acc784-cbbf-44f5-aa5b-1d97fd8dbe4d)

## Your environment
* version of gridstack.js - GridStack 10.1.1
* Chrome Version 122.0.6261.112 (Official Build) (64-bit)
* Windows 10 Enterprise

## Steps to reproduce
1. Drag and drop the item from outside the grid - it works.
2. Try to do the same second time - it crashes.

[Link with demo](https://jsfiddle.net/m4s9a35w/9/)

## Expected behavior
The grid should not crash.

**Comment by adumesny** [comment]
fixed in teh next release. don't forget to donate if you find this lib useful!
