### ISSUE TITLE
[BUG] New widgets added by .load() displace existing widgets 

### ISSUE THREAD

**Issue by jilow** [gridstack/gridstack.js#2639]
## Subject of the issue

New widgets created by the `.load()` method are rendered in the middle of the grid and displace existing widgets.

This behavior doesn't match `.addWidget()` which places new widgets in the next available slot without displacing.

## Screenshots

| `.addWidget(newItem)`  | `.load(items + newItem)` |
| ------------- | ------------- |
|  ![image](https://github.com/gridstack/gridstack.js/assets/17846372/e39a3dc2-b368-483b-804e-74765b88722d) |  ![image](https://github.com/gridstack/gridstack.js/assets/17846372/c8c18003-e788-45f1-9ed3-2d847222aa8e) |

## Your environment

Version: `10.0.1` & `10.1.1`
Browser/OS: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:124.0) Gecko/20100101 Firefox/124.0`

## Steps to reproduce

Demo: https://jsfiddle.net/2g4zarb8/

1. Create a new node with auto position (no `w` or `h`). 
1. Add the widget using `.addWidget()` and observe it in the next open horizontal spot.
1. Add the same widget using `.load()` and observe it in the middle of the grid.

## Expected behavior

New widgets are placed consistently regardless of which method was used. In this case I'd expect new widget added with `.load()` to be placed in the same location `.addWidget()` would.

**Comment by adumesny** [comment]
yeah, that case should work but load() was written expecting complete layouts (doing just the diffs) but since that item is new it should addWidget() that last one not found...

**Comment by adumesny** [comment]
fixed in the next release. don't forget to donate if you find this lib useful!

**Comment by jilow** [comment]
Thanks for fixing this so quickly @adumesny! I can confirm that this is no longer an issue as of v10.1.2.
