### ISSUE TITLE
Change disableResize and disableDrag on Angular on user interaction

### ISSUE THREAD

**Issue by mcrodriguezb** [gridstack/gridstack.js#2653]
## Subject of the issue
I'm trying to update the grid options in angular. First I create a grid with the disableDrag and disableResize options set to true. Then I want to change the options so that the grid will be draggable and resizable. This is the same as https://github.com/gridstack/gridstack.js/issues/898, but now in angular.

## Your environment
* version of gridstack - 10.1.2
* which browser/OS: OSX and Chrome

## Steps to reproduce
https://stackblitz.com/edit/stackblitz-starters-ep5dpv

## Expected behavior
Allow to resize and drag items.

**Comment by adumesny** [comment]
use static: true to start, then call grid.setStatic(false) to enable editing...

**Comment by mcrodriguezb** [comment]
Thanks for your quick response. What do you mean by static? I wasn't able to find such attribute. Are you refering to GridOptions.staticGrid?

**Comment by mcrodriguezb** [comment]
Please, remember this is for angular wrapper and not plain JS
