### ISSUE TITLE
[Bug] After load(), in some cases the Y position is determined incorrectly & sizes are not restored.

### ISSUE THREAD

**Issue by IgorA100** [gridstack/gridstack.js#2669]
## Subject of the issue
I save current layout and then load it. In some cases, elements are assigned the value `gs-y="0"` instead of the stored `gs-y="3"`
This is also confirmed at https://gridstackjs.com/demo/serialization.html

## Your environment
* version of gridstack.js - 10.1.2
* which browser/OS - Windows 8.1. Chrome 109.0.5414.168

## Steps to reproduce
https://github.com/gridstack/gridstack.js/assets/5006170/19029c64-dc81-4825-a4a3-e3e42ee6f624

## Expected behavior
After load() element's Y position should always match the stored `gs-y="3"`, not `gs-y="0"`

**Comment by IgorA100** [comment]
There is also a problem with the sizes of elements when Load()

https://github.com/gridstack/gridstack.js/assets/5006170/9621fe5d-f077-4821-9fbd-85888b880248

**Comment by adumesny** [comment]
the bug culd be in the demo itself (fail to load the saved data) or the lib, but a bug reguardless...

**Comment by IgorA100** [comment]
No, this is not an error reading saved data. This shows up in my development environment as well.
Initially I looked for the problem in my development environment, and only then I started checking on the demo page.
What lib are you talking about?

**Comment by adumesny** [comment]
@erdoganfurkann that is a good hint! likely repacking after each item instead of after all info is read in then...

**Comment by erdoganfurkann** [comment]
I have a temporary solution that worked for me. I always initialize the grid stack with float: true option, then change float to false using gridstack's float() method. I call float(false) in the dragstart and resizestart event handlers, but I guess this can also be called in a callback function that runs after the DOM is loaded.

**Comment by adumesny** [comment]
if someone wants to donate I could take a look but I'm really busy these days, else make a fix. thanks.

**Comment by brian-patrick-3** [comment]
I'm seeing cases where `.save()` is missing values like `h` for individual widgets, which causes the entire page to freeze when you try to call `.load()`

**Comment by adumesny** [comment]
@brian-patrick-3 that's likely a different issue. please file a bug with runninge example.

**Comment by IgorA100** [comment]
The bug I described appears both with float: false and with float: true

**Comment by adumesny** [comment]
@IgorA100 the video are not playing for me (pays 5 secn then stops). coul you show using picture the state you need to save + laod showing the issue ? can't debug wihtout steps.

**Comment by IgorA100** [comment]
@adumesny I'm sorry I didn't answer for a long time.

You need to move element No. 2 and save.:
![1](https://github.com/gridstack/gridstack.js/assets/5006170/882fb0a6-8111-4cb8-bf73-89aa03fa2515)

Then move element #2 again
![2](https://github.com/gridstack/gridstack.js/assets/5006170/965c9dca-75f7-4119-8bcc-900b3d0069a3)

And Load. The position of element No. 2 after Load will not be the same as before Save.
![3](https://github.com/gridstack/gridstack.js/assets/5006170/b41c5850-19f4-4517-bde5-8776b1f00aeb)

**Comment by adumesny** [comment]
thanks, I can see the issue now. doing a clear shows the item correctly loading though.

**Comment by IgorA100** [comment]
I also wrote about the second error https://github.com/gridstack/gridstack.js/issues/2669#issuecomment-2074927746
But perhaps it is interconnected with the first one.

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful!
