### ISSUE TITLE
Angular wrapper doesnt have fitToContent option

### ISSUE THREAD

**Issue by mcakici** [gridstack/gridstack.js#2673]
## Subject of the issue
Angular wrapper doesnt have fitToContent option

## Your environment
Angular 17.3.7
GridStack 10.1.2

## Steps to reproduce
![image](https://github.com/gridstack/gridstack.js/assets/3582208/817bee13-0c59-4b26-996e-7d56c2742b45)

## Expected behavior
It should be seen.

https://github.com/gridstack/gridstack.js/issues/404

**Comment by lukebrider-woolard-cgi** [comment]
`fitToContent` was renamed `sizeToContent` in 9.1.0

`sizeToContent` is also an Item Option, so you should be using it when you define the children of GridStackOptions (or when you add a widget tot he grid).

**Comment by adumesny** [comment]
can be set on children or grid (to affect all children). closing as NAB
