### ISSUE TITLE
Demo for lit is not working (https://gridstackjs.com/demo/web-comp.html)

### ISSUE THREAD

**Issue by navalamol** [gridstack/gridstack.js#2674]
## Subject of the issue

Demo for gridstack with lit element is not working.  Does it supports lit element. If yes, can demo be fixed.
Also, do we have any docs related to that

https://gridstackjs.com/demo/web-comp.html

## Your environment
* version of gridstack.js - DON'T SAY LATEST as that doesn't mean anything a month/year from now.
* which browser/OS

## Steps to reproduce
You **MUST** provide a working demo - keep it simple and avoid frameworks as that could have issues - you can use 
https://jsfiddle.net/adumesny/jqhkry7g

## Expected behavior
Tell us what should happen. If hard to describe, attach a video as well.

**Comment by adumesny** [comment]
fixed in recent CL (forced rev 3)
