### ISSUE TITLE
Custom drag element of type button doesn't work

### ISSUE THREAD

**Issue by gili-lumigo** [gridstack/gridstack.js#2677]
## Subject of the issue
When using a custom handler to be an element of type button, The drag doesn't work at all.
It used to work on version 7.3.0 and stopped working on version 8.0.0.
From what I'm seeing, It's only for buttons... If I'm using other kinds of element (For ex. a span) it does work.

## Your environment
* version of gridstack.js - 8.0.0
* which browser/OS -  Chrome

## Steps to reproduce
An example can be found here:
https://jsfiddle.net/gili_lumigo/t7vuycoL/3/

When the handler is of type button, The drag doesn't work and when it's of type span, It does

## Expected behavior
Should work as prior to version 8 where the drag element works regardless of the element type.

**Comment by adumesny** [comment]
fixed in the next release. don't forget to donate if you find this lib useful.
