### ISSUE TITLE
Scale & Different Resolution Question

### ISSUE THREAD

**Issue by dassum03-BH** [gridstack/gridstack.js#2682]
## Subject of the issue
Resolution - 1920 x 1200
Aspect Ratio - 100%

![image](https://github.com/gridstack/gridstack.js/assets/118821419/1229a617-ba81-45b2-afcd-cf3b43ad4dc5)

Resolution - 1920 x 1200
Aspect Ratio - 125%

![image](https://github.com/gridstack/gridstack.js/assets/118821419/c98ade0c-3e40-49df-911d-c71809ea7cbd)

When in different aspect ratio, gridstack cuts the widget and adds scroll to it, any way to resolve this? Notice the "6% from last year" line been cut off..

This happens for screens with different resolution

I have tried sizeToContent: true attribute (both to grid & chidlren), it cuts off the widget:

without sizeToContent:

![image](https://github.com/gridstack/gridstack.js/assets/118821419/d0a5db38-fca4-4b71-adbd-0fe2cdc045d9)

Without the attribute:

![image](https://github.com/gridstack/gridstack.js/assets/118821419/65bd98ba-178d-410d-bcaf-8f9b3c0ea00b)

When resized, it behaves weirdly and increases the height

**Comment by adumesny** [comment]
I think you mean scale 1.25% not aspect ration (width/height). Are you saying sizeToContent doesn't handle div scaling (or detecting when you change it) ? not clear and you don't provide example showing issue.

**Comment by dassum03-BH** [comment]
@adumesny with scale, I meant this:

![image](https://github.com/gridstack/gridstack.js/assets/118821419/6051d0a0-9119-44d3-bf3f-a896bbac7b42)

sizeToContent is cutting off widgets and unable to resize them vertically. Is there any alternative to the issue?

Btw, I'm using angular wrapper..

**Comment by adumesny** [comment]
looks like sizeToContent is not handling scale,  not surprised as I don't use scale. is that browser or OS level or ?? - you are NOT providing a proper bug report with steps to reproduce - see template.

**Comment by adumesny** [comment]
not  bug the way you posted it. see the error messages....

![image](https://github.com/gridstack/gridstack.js/assets/3496166/99ae7a27-2002-44ee-b8bd-094f6f3fa700)
