### ISSUE TITLE
Scrollbar flickering issue when widget matches window height

### ISSUE THREAD

**Issue by lrnicoka** [gridstack/gridstack.js#2704]
## Subject of the issue
I am using a grid where the widgets do not have a predefined size. When the widget exactly matches the height of the window, there is an issue with the scrollbar appearing and disappearing, which causes an infinite flickering effect.

## Your environment
* version of gridstack.js - 10.2.0
* which browser/OS - Chrome / Windows 11

## Steps to reproduce
Reproduced on the demo "Float grid demo" with float = false
https://github.com/gridstack/gridstack.js/assets/173177247/55f0d978-9292-427b-a959-e45f9a7c9970

## Expected behavior
It should not be flickering

**Comment by adumesny** [comment]
not seeing this on mac (travel machine) so will need to try on windows when I get home...

**Comment by adumesny** [comment]
not seeing this on windows either, so closing until you can provide video showing the issue...
![image](https://github.com/user-attachments/assets/fd674b98-7d8e-420c-b449-38e1884a1f9c)

**Comment by lrnicoka** [comment]
Still having this issue, with float: false

https://github.com/user-attachments/assets/c197cea7-e608-4b54-b435-f47c8fa33296

**Comment by lrnicoka** [comment]
@adumesny Any updates about this issue ?

**Comment by abdurriq** [comment]
This appears to be related to the scrollbar appearing and disappearing causing resizing (https://stackoverflow.com/a/21563741). The solution I found was just to use `overflow: scroll` to allow the scrollbar to remain:
```
        body {
            overflow: scroll;
        }
```

**Comment by adumesny** [comment]
I see it now. it has to do with with `cellHeight:'auto'` keeping items square (so available width affect cellHeight, which in turns affects entire height, which affects showing the scrollbar, which reduces width -> reduces cellHeight which which shrinks the total height, again and again....

there isn't a 'fix' per say. Either you set `cellHeight:'initial'` or a fixed size so it doesn't change dynamically, or you always show scrollbar.

**Comment by adumesny** [comment]
actaully I take that back: grid size could include not available space (reduced by scrollbars) but entire width so scrollbar showing/disapearing wouldn't affect cellHeight:auto

**Comment by lrnicoka** [comment]
I used `cellHeight:'initial'` and it fixed my problem, thank you !
