### ISSUE TITLE
Cant find dragOut property

### ISSUE THREAD

**Issue by gosongying** [gridstack/gridstack.js#2708]
## Subject of the issue
'dragOut' does not exist in type 'GridStackOptions', i cant prevent grid item from being dragged from parent grid.

## Your environment
* version of gridstack.js - 10.2.0
* google chrome on Mac M1

## Steps to reproduce
Initialize a GridStack instance with GridStack.init() and specify value for dragOut key.

## Expected behavior
The property should exist based on GridStack Api Doc, turns out that the key does not exist in type 'GridStackOptions'

**Comment by adumesny** [comment]
removed old `dragOut` from doc since it is no longer supported (jquery UI feaure)
