### ISSUE TITLE
Grids With < 12 Columns Will Accept Widgets Greater Than Set Column Size And Resize Them

### ISSUE THREAD

**Issue by Xilophinum** [gridstack/gridstack.js#2726]
## Subject of the issue
When using grids that are less than 12 columns, and then having widgets with widths greater than the column number, it will accept the widget as long as row variables are correct. It will also resize the widget to the grids max columns, causing the widget to be a new width.

## Your environment
* version of gridstack.js -v10.2.0 (Thanks for my rotational widgets, I was the sponsor!)

## Steps to reproduce
https://jsfiddle.net/odtm6x5b/17/

## Expected behavior
Respect the column size of the grid being dragged into. If the column size is smaller than the widgets width, reject the widget.

Im not good with PRs (literally have never done one before), but here is what I did to fix the issue. No idea if this would cause issues. But it fixes the issue for me. Under `gridstack-engine.ts`

![image](https://github.com/gridstack/gridstack.js/assets/44152393/dd26f8ca-5296-4e09-a863-202d8d0e81a4)

**Comment by adumesny** [comment]
so you're saying that dragging a w:2 widget into a 1 column grid should never work ? it depends... you could make a case that it should shrink to fit (which it does), like we do during responsive design... relunctant to force a reject, not clear we need an option either.

| Thanks for my rotational widgets, I was the sponsor!
the name and email doesn't match, but thank you if you work together...
