### ISSUE TITLE
Gridstack Horizontal resize issue when grid item placed to extreme right

### ISSUE THREAD

**Issue by RAJASH0412** [gridstack/gridstack.js#2730]
Gridstack Horizontal resize issue when grid item placed to extreme right
When we place a gridstack widget to extreme right , unable to resize the widget towards left.

Angular 15.2.9
* version of gridstack.js - 10.1.2
* which browser/OS - Google Chrome

## Steps to reproduce
Place widget to extreme right and try to resize it horizontally towards left.

## Expected behavior
We should be able to resize widget towards left horizontally.

**Comment by adumesny** [comment]
Step (since report missing!) https://gridstackjs.com/demo/float.html and move item to column 12, left resize.

**Comment by RAJASH0412** [comment]
> Step (since report missing!) https://gridstackjs.com/demo/float.html and move item to column 12, left resize.

Still not able to resize towards left if placed to the rightmost position

**Comment by dassum03-BH** [comment]
@adumesny - any timelines for this bug?

**Comment by adumesny** [comment]
no plans, unless someone wants to donate to have it fixed - low priority.

**Comment by adumesny** [comment]
fixed in next release. don't forget to donate if you find this lib useful!
