### ISSUE TITLE
Layout issues (style sheet missing) when used with RouteReuseStrategy (Angular)

### ISSUE THREAD

**Issue by bschaeublin** [gridstack/gridstack.js#2733]
## Subject of the issue
I'm using Angulars ReUseStrategy to cache Angular Components. In the case of my widgets they are able to refresh their inner content themselfes and it takes some time to build them up.

Unfortunately it seems that this library does have issues getting cached by Angulars ReUseStrategy - when navigating to a page and back, the layout gets corrupted.

Any tries to update / refresh the view using this libraries api methods fails (for example, using a resizeObserver and trigger `updateAll` or remove them from the dom and re-add them` - only a full reload of the application helps.

## Your environment
* version of gridstack.js: gridstack-10.3.0
* which browser/OS: Chrome, Windows 11

## Steps to reproduce
See video:
<video src='https://github.com/gridstack/gridstack.js/assets/11610660/49d7db36-ead8-48c2-99ba-448470660707' width=180/>

See code-sample:
https://stackblitz.com/edit/stackblitz-starters-zcvamz?file=src%2Fcomponents%2Fdashboard%2Fdashboard.component.ts

## Expected behavior
The libraries angular component should correctly align the grid when getting reused by angular or provde a method to refresh the view.

**Comment by adumesny** [comment]
would be good if you trimmed the example to bare minimum (use default 12 column, non responsive, a few widgets) and does it happen if you don't use DOM for loop but the gridOptions.children (which is recommended - see many ng examples)

**Comment by adumesny** [comment]
it appears the CSS file GS created dynamically is not re-created (at the root dom) so `gs-y | gs-h` are ignored.. maybe try `styleInHead:false`
![image](https://github.com/gridstack/gridstack.js/assets/3496166/1ec0debe-38fe-4cad-906c-b81bcb4ce667)

**Comment by bschaeublin** [comment]
@adumesny firstly, thank you for maintaining this library and immediate response to my issue.
You're right, I updated the sample to use as less special treatment as possible - even if I am using it differently. It still can be reproduced (with 12 columns, gridOptions.children, etc.).

I'm not sure if you really meant `styleInHead:false` as it should be the default value accordingly to the [config](https://github.com/gridstack/gridstack.js/tree/master/doc#savesavecontent--true-savegridopt--false-gridstackwidget--gridstackoptions) - but thanks to your hint, i tried setting it to true and it fixed the issue!

I think this is a good enough workaround for me :-).

**Comment by adumesny** [comment]
ok by default I recall we create the custom CSS style sheet right before the grid (same parent). would be interesting to see what happens in this case and if GS could possible be notified to check and re-create if missing... but guess you have a workaround.

don't forget to donate if you find this lib useful!

**Comment by adumesny** [comment]
no time to look, closing with workaround...
