### ISSUE TITLE
Rotation causes an error in the console (10.2.1+)

### ISSUE THREAD

**Issue by thamblin** [gridstack/gridstack.js#2734]
## Subject of the issue
When rotating an item there is an error swapping the axis:
```
utils.ts:593 Uncaught TypeError: Cannot read properties of undefined (reading 'w')
    at t.swap (utils.ts:593:76)
    at e._keyEvent (dd-draggable.ts:311:13)
```

This also results in the grid becoming locked when dropping the item.

## Your environment
* version of gridstack.js - starts being an issue in 10.2.1
* which browser/OS - checked chrome/firefox

## Steps to reproduce
Go to the docs (currently on version 10.3.0) start dragging any non equal width/height item and hit 'r'.

## Expected behavior
The grid should not lock, and no error should be produced.

**Comment by adumesny** [comment]
this was introduced by this fix https://github.com/gridstack/gridstack.js/pull/2712
