### ISSUE TITLE
Can't be used in mobile debugging mode? Cannot drag

### ISSUE THREAD

**Issue by gitzhangshenglin** [gridstack/gridstack.js#2739]
## Subject of the issue
Describe your issue here.
If unsure if lib bug, use slack channel instead: https://join.slack.com/t/gridstackjs/shared_invite/zt-27q0rwf80-5vCt81Z_hfVgpRW7L17MnQ

## Your environment
* version of gridstack.js - DON'T SAY LATEST as that doesn't mean anything a month/year from now.
* which browser/OS

## Steps to reproduce
You **MUST** provide a working demo - keep it simple and avoid frameworks as that could have issues - you can use 
https://jsfiddle.net/adumesny/jqhkry7g

## Expected behavior
Tell us what should happen. If hard to describe, attach a video as well.

**Comment by adumesny** [comment]
file a proper bug please.
