### ISSUE TITLE
Can not drag an item after moving it out of subgrid

### ISSUE THREAD

**Issue by artemas** [gridstack/gridstack.js#2740]
## Subject of the issue
The item can not be moved after moving it out of a subgrid.

## Your environment
I've got the issue after upgrade from 10.2.0.
It is reproducible on [demo page](https://gridstackjs.com/demo/nested.html)
* version of gridstack.js - 10.3.0
* chrome/linux

## Steps to reproduce
https://gridstackjs.com/demo/nested.html

1. Click **Add Nested Grid**
2. Move just created **Nested Grid** to another subgrid
3. Move an item (_world_ in the video below) out of the created **Nested Grid**
4. Try to move this item (_world_)
5. The created **Nested Grid** is moving instead the item (_world_)

## Expected behavior
The item should move as usual

[gridstack_demo.webm](https://github.com/user-attachments/assets/0dafa923-74c0-488e-b1b7-9d7c084e669b)

**Comment by adumesny** [comment]
weird. wonder if this was another 10.2.1 introduced issue like #2737

**Comment by adumesny** [comment]
fixed in next release, don't forget to donate if you find this lib useful!
