### ISSUE TITLE
sizeToContent not working in ReactJs

### ISSUE THREAD

**Issue by iaminamcom** [gridstack/gridstack.js#2750]
## Subject of the issue
I want to make grid item to height as much as there's content exactly what `sizeToContent: true` is meant for. But unfortunately, it's not working for me.  I am doing in React but it's not working in the JS fiddle you shared.

## Your environment
`gridstack": "10.3.1`
Chrome Windows

## Steps to reproduce
https://jsfiddle.net/vf7pzmns/

## Expected behavior
I want to see each item expand in height to match the height of content. I want it to be responsive but it's not working for even simple example yet.

**Comment by adumesny** [comment]
clearly it is working here https://gridstackjs.com/demo/sizeToContent.html and I don't know React nor have time to debug your case... the content HAS to be there when initializing GS for it to size, or you need to call `resizeToContent()` when you do.
