### ISSUE TITLE
Angular Memory leak

### ISSUE THREAD

**Issue by jrebecchi** [gridstack/gridstack.js#2753]
## Subject of the issue
There is a memory leak with GridStack when you rerender it on Angular.

https://github.com/user-attachments/assets/75ac6e3a-5c12-472e-8488-11aaba48f002

## Your environment
* version of gridstack.js - 10.3.1-dev
* Browser: Firefox v128.0.3 | Chrome v127.0.6533.72 

## Steps to reproduce
I did this [PR](https://github.com/gridstack/gridstack.js/pull/2752) where I adapted the Angular demo to reproduce it

**Comment by godind** [comment]
I see the same problem with my project. It's pretty severe if you app repeatedly load grid items. Like swapping from dashboard to dashboard.

**Comment by adumesny** [comment]
you guys need to give me a simple example to reprodude... the above review has a widget with undred on nested div and not clear why it changed so much code... I don't want to debug your issue.

does it happen when you call load(layout1) + load(layout2), with or without removeAll() in between ?

**Comment by adumesny** [comment]
![image](https://github.com/user-attachments/assets/2dfa9bda-e197-42ae-aac8-e446577f4a4d)

**Comment by godind** [comment]
In my case I call this every time I load a new layout. No `removeAll()` prior

`protected loadDashboard(): void {
    const dashboard = this.dashboard.dashboards()[this.dashboard.activeDashboard()];
    this.gridstack.grid?.load(dashboard.configuration as NgGridStackWidget[]);
  }`

**Comment by adumesny** [comment]
![image](https://github.com/user-attachments/assets/f5040f95-e10a-4f30-a193-8bf3cee710d8)
![image](https://github.com/user-attachments/assets/796fd104-9081-4cb0-a4eb-f1faaecd2239)
