### ISSUE TITLE
Responsive grid coordinates system for layout values list or compact doesn't restore original layout

### ISSUE THREAD

**Issue by kardeepak77** [gridstack/gridstack.js#2754]
## Subject of the issue
If you choose layout of list or compact with responsive breakpoints, it's expected to have original widgets position are restored when screen/window size is back to it's max size.
## Your environment
* version of gridstack.js - 10.0.1
* which browser/OS - Chrome/Windows 11 pro

## Steps to reproduce
[Responsive Breakpoint](https://gridstackjs.com/demo/responsive_break.html#)

1. Select Layout as list or compact.
2. Ensure you have browser width is maximized.
3. Observe the layout of widgets on the grid
![image](https://github.com/user-attachments/assets/68acfa42-6140-4c5d-9bbb-459cf2227965)

4. Reduce browser width so that single column layout appears.
![image](https://github.com/user-attachments/assets/b78151d2-d1c1-48c3-b7e1-b8b31c18464a)

5. Change the browser width back to maximum.
6. notice all the widgets position is different from step 3
![image](https://github.com/user-attachments/assets/189f3e29-cffc-40b4-b816-cfe11f655e86)

## Expected behavior
After screen resize to maximum, my original grid's widgets position should be restored.

**Comment by adumesny** [comment]
Yes and no. when you pick 'list' the layout should really change at that point (it's just a demo so has a bug) and then yes I would expect to go back to that layout when sizing back up - that would be a bug otherwise.

Closing as demo 'bug'

**Comment by kardeepak77** [comment]
Thank you for your prompt reply. 
Could you please help point the issue you see in the demo?
I am getting same issue in my code, which is very similar to the the [demo ](https://gridstackjs.com/demo/responsive_break.html#) page mentioned above.

**Comment by adumesny** [comment]
as soon as you pick 'list' it should reflow the 12 column content, since that is not list looking to start with. then maybe going to 1 and back would restore properly. I don't know. didn't try.
