### ISSUE TITLE
[BUG] In versions 8.0 and above, only values ​​1 and 12 of the column attribute can display the width normally. Other values ​​cannot display normally.

### ISSUE THREAD

**Issue by wenzhenqing** [gridstack/gridstack.js#2755]
In versions 8.0 and above, only values ​​1 and 12 of the column attribute can display the width normally. Other values ​​cannot display normally.

**Comment by adumesny** [comment]
read the doc! https://github.com/gridstack/gridstack.js?tab=readme-ov-file#custom-columns-css. you need the gridstack-extra.css file
