### ISSUE TITLE
empty space instead of grid

### ISSUE THREAD

**Issue by mourad-boussiouf-epitech** [gridstack/gridstack.js#2758]
## Subject of the issue
The lib donest show anything even when i try to put the div inside or outside the body, i tried all styles everything but still i just get some empty space.

## Your environment
    "gridstack": "^10.3.1"
Chrome & firefox same output

demo : 
https://jsfiddle.net/fn89zqpg/4/)

## Expected behavior
The lib donest work there is nothing to drag and drop

**Comment by adumesny** [comment]
you have column:7 but not gridstack-extra.css to handle custom count (only 1 & 12 are supported by default).
