### ISSUE TITLE
Widgets are removed from the sidebar upon dragging and cannot be dragged again.

### ISSUE THREAD

**Issue by bernardkas** [gridstack/gridstack.js#2764]
Hello guys, I have a problem I create left sidebar and widget two grid but when I start dragging from the left side it remove that and I can't drag that anymore

function initGridStack() {
  if (grid.value) {
    grid.value.destroy(false);
  }

  grid.value = GridStack.init({
    column: 1,
    cellHeight: "100px",
    minRow: 10,
    float: false,
    disableResize: true,
    class: ".preset-grid-stack",
    handle: ".drag-btn",
    acceptWidgets: false,
    draggable: {
      handle: '.grid-stack-item-content', 
    },
  }, ".grid-stack.preset-grid-stack");

  grid.value.on('dragstart', (event: any) => {
    console.log('event in sidebar', event);
    newComponents.value.forEach((widget) => {
      if (event.target.id === widget.id){
        onDragStart(widget, event)
      }
    })
  })

  grid.value.on('change', (event: any) => {
    console.log('on change event', event);
 
  })
  nextTick(() => {
    newComponents.value.forEach((preset) => {
      makeWidget(preset);
      emit('refresh');
    });
  });
}

function makeWidget(preset: any) {
  const elSelector = `#${preset.id}`;
  const element = document.querySelector(elSelector);
  if (element) {
    grid.value.makeWidget(element);
  } else {
    console.error(`Element with selector ${elSelector} not found`);
  }
}

Has anyone experienced similar behavior where dragging a widget from a sidebar causes it to be removed and prevents further dragging? Any advice on how to resolve this issue would be greatly appreciated.

Expected Behavior
The widget should be cloned and added to the GridStack layout, while the original widget should remain in the sidebar, ready to be dragged again.

Actual Behavior
When dragging a widget from the sidebar, the widget is removed from the sidebar and cannot be dragged again. This behavior prevents further dragging of the widget.

**Comment by adumesny** [comment]
The examples work fine so look there.
Make sure you have helper clone() so a copy gets dragged not original sidebar.

**Comment by bernardkas** [comment]
Can you tell where to call this helper clone() because I am trying in the in the draggable but not working

**Comment by lironzaa** [comment]
> Can you tell where to call this helper clone() because I am trying in the in the draggable but not working

You can use this method to add the 'clone' as argument the setupDragIn method :
    GridStack.setupDragIn('.test-item', { appendTo: 'body', helper: 'clone' });
