### ISSUE TITLE
Automatically remove spacing

### ISSUE THREAD

**Issue by AnibalDuarte** [gridstack/gridstack.js#2765]
## Subject of the issue
_As the Slack invite is invalid and I couldn't find my answer on docs:_

How to make the UI to "stack" all blocks to they fit to the left, removing the space between them and the left side of the screen?

## Your environment
* version of gridstack.js - 10.3.1
* Windows 10 - Google Chrome

## Steps to reproduce
I've build my example/test implementation based on https://jsfiddle.net/adumesny/jqhkry7g

When I move any block to the right an empty space on the left side is created.

## Expected behavior
If is there any space on left side the UI should stack the widgets together and fill that left space.

**Comment by adumesny** [comment]
What you are asking for is list support which gs does not. But you could
try calling compact() after an item is moved, or donate to have feature
supported.
sent from phone. excuse any typ-oh!
