### ISSUE TITLE
Angular demo is not working

### ISSUE THREAD

**Issue by JulienLecoq** [gridstack/gridstack.js#2769]
## Subject of the issue
Angular demo is not working.

## Steps to reproduce
Follow the steps here: https://github.com/gridstack/gridstack.js/tree/c1b091c4db9065c2bca27adc1c243b334810af33/angular#demo

And it will show the following errors after yarn start:

```
./projects/demo/src/styles.css - Error: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Failed to find '../dist/gridstack.css'
  in [
   ####################/########/#######/gridstack/demo
  ]

./projects/demo/src/styles.css - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: Failed to find '../dist/gridstack.css'
  in [
   ####################/########/#######/gridstack/demo
  ]
```

## Expected behavior
The demo should work.

**Comment by adumesny** [comment]
oops, angular trying to re-use the regular demo styling, which is build dependent. since I always have both built I never saw that. thanks, will fix.

for now do a `yarn + yarn` build in the main folder before angular wrapper.

**Comment by JulienLecoq** [comment]
Ok 👌🏻
