### ISSUE TITLE
Custom component with the "new" Angular input syntax does not work.

### ISSUE THREAD

**Issue by JulienLecoq** [gridstack/gridstack.js#2770]
## Subject of the issue
In the Angular demo, you did use this code to create a custom component:

```ts
@Component({
  selector: 'app-a',
  template: 'Comp A {{ text }}',
})
export class AComponent extends BaseWidget implements OnDestroy {
  @Input() text: string = 'foo'; // test custom input data
  public override serialize(): NgCompInputs | undefined  { return this.text ? {text: this.text} : undefined; }
  ngOnDestroy() { console.log('Comp A destroyed'); } // test to make sure cleanup happens
}
```

If I convert the code to this:

```ts
@Component({
  selector: 'app-a',
  template: 'Comp A {{ text() }}',
})
export class AComponent extends BaseWidget implements OnDestroy {
  text = input('foo'); // test custom input data
  public override serialize(): NgCompInputs | undefined  { return this.text() ? {text: this.text() } : undefined; }
  ngOnDestroy() { console.log('Comp A destroyed'); } // test to make sure cleanup happens
}
```

It throws an error at runtime because it expects text to be a signal, whereas when running the code, it appears to just be a string.

## Expected behavior
It should either work, or be mentioned in the documentation that it does not work with the Angular new input syntax.

**Comment by adumesny** [comment]
what version of Angular are you using, because it's fine initializing an @Input() with a default value at least until v16 (have not read otherwise with newer rev)

**Comment by JulienLecoq** [comment]
Yeah, it works fine with the old ``@Input()`` syntax. I was talking about the new ``input()`` syntax that came in v17.1.

**Comment by JulienLecoq** [comment]
The issue is not the default value, but that it does not behave as an ``InputSignal`` during runtime but just as a ``normal variable``.

**Comment by adumesny** [comment]
closing at what I have works. up to you if you use a newer syntax. not sure what I woud change...
