### ISSUE TITLE
Update Angular documentation

### ISSUE THREAD

**Issue by JulienLecoq** [gridstack/gridstack.js#2771]
## Subject of the issue
I think that this would be cool to update this documentation: https://github.com/gridstack/gridstack.js/tree/master/angular#more-complete-example to show how to pass the input data with:

```
input: {
    text: 'Bob',
}
```

Also, it's worth mentioning that class based input are not completely supported.
I lost several minutes to understand that class based input loose their methods once passed to a component.

## Your environment
Gridstack version:

"gridstack": "^10.3.1"
"gridstack-angular": "^0.6.0-dev"

Browser: Safari
OS: MacOS

**Comment by adumesny** [comment]
not sure I understand point 2: are you saying your input has method code instead of JSON (since it needs to be serialized, that's the all point) ?

**Comment by JulienLecoq** [comment]
Yes 👍
I didn’t know it needs to be serialized, is it mentioned somewhere and I just missed it?

**Comment by adumesny** [comment]
a user edited dashboard needs to be saved somewhere. why else would you make it editable then ?
that's why the focus of most demos are using the JSON looking data used in load()/init() rather than DOM layouts...

**Comment by JulienLecoq** [comment]
Yes I understand that. But my use case is the following:

I create a grid dynamically from photos that I fetch from my db. To load the grid widgets, I do it using the load() method.
When I create the widgets, I need to pass an object to each widget that has some methods, among them, it has the isUpdating() method.
This method is later on used in the widget to show a loading spinner if the photo is being updated. I was doing so by using an object built from a class, but the object looses all its methods once you pass it as an input.

However, I found a solution, I can pass a literal object with methods and it works. I'm not sure why, it shouldn't work since a method isn't serialisable, no?

**Comment by adumesny** [comment]
![image](https://github.com/user-attachments/assets/a49c33ef-f68f-4054-9654-c96e7afb0d35)
example shows `input { text: 'bar' }` example already. will update doc.
