### ISSUE TITLE
Is there a way to change the width of the grid so that the grids on the left and right adapt to the width instead of automatically falling down?

### ISSUE THREAD

**Issue by 9yues** [gridstack/gridstack.js#2779]
## Subject of the issue
Suppose I have three grids in a row. If I drag the width of the first grid and extend it to the right, the second and third grids will move down. How can I make the width of the second and third grids adaptive and not move down automatically?

## Your environment
 version of gridstack.js v10.3.1
* which browser/OS  Chrome/Windows

**Comment by 9yues** [comment]
You can understand that the dragging effect of the table header, including the height, is the same. Suppose I have 9 grids, 3 grids in each row, and I currently have three rows. If I drag any grid in the first row, the height of the three grids in this row will remain consistent. The same is true for the second and third rows.

**Comment by adumesny** [comment]
You mean widget not grid. You would have to write your own custom collision detection code to have one widget take the space from another.

If you're looking to push items right and keep things in a list until they run out of space and reflow next row, then it's a feature request that has been asked before and could be added with the right donation.
