### ISSUE TITLE
Prevent Drag on Item Content

### ISSUE THREAD

**Issue by elliothomerwilkinson** [gridstack/gridstack.js#2780]
## Subject of the issue
Is it possible to disable drag when interacting with an Item's content? We have a use case where the content has it's own drag controls but when used they trigger the Grid Item drag. We would like to disable drag for part of an items content, for example, a div.

This Slack link doesn't work:
https://join.slack.com/t/gridstackjs/shared_invite/zt-27q0rwf80-5vCt81Z_hfVgpRW7L17MnQ

## Your environment
* 10.2.0
* Chrome

## Steps to reproduce
https://jsfiddle.net/jmbe5wr7/15/

## Expected behavior
A way to flag that some content should not trigger drag

**Comment by adumesny** [comment]
You specify today what area(s) to drag instead of entire widget.

**Comment by adumesny** [comment]
FYI I fixed slack invite (must have reached their 400 max per link): new one is https://join.slack.com/t/gridstackjs/shared_invite/zt-2qa21lnxz-vw29RdTFet3N6~ABqT9kwA
