### ISSUE TITLE
When the resize event is executed, for example, if the width of a grid is greater than a certain value, I want to terminate the resize event

### ISSUE THREAD

**Issue by 9yues** [gridstack/gridstack.js#2782]
## Subject of the issue
Describe your issue here.
When the resize event is executed, for example, if the width of a grid is greater than a certain value, I want to terminate the resize event

## Your environment
gridstack version v10.3.1
windows / chrome

**Comment by adumesny** [comment]
You mean grid item/widget, not grid? The resize event if after not during, you mean resizing? There is already max width height so no clear what you are asking. Closing

**Comment by 9yues** [comment]
Shì wǎng gé, wǒ mùqián yǒu yīgè jiǔgōnggé, tāmen mòrèn de cānshù shì zhèyàng [{"id":"Item1","x":0,"Y":0,"W":4},{"Id":"Item2","x":4,"Y":0,"W":4},{"Id":"Item3","x":8,"Y":0,"W":4},{"Id":"Item4","x":0,"Y":1,"W":4},{"Id":"Item5","x":4,"Y":1,"W":4},{"Id":"Item6","x":8,"Y":1,"W":4},{"Id":"Item7","x":0,"Y":2,"W":4},{"Id":"Item8","x":4,"Y":2,"W":4},{"Id":"Item9","x":8,"Y":2,"W":4}] Dāng wǒ tiáozhěng dì yī gè wǎng gé de kuāndù, zhège shíhòu resize shìjiàn huì fǎnhuí w = 5, ránhòu wǒ zhíxíng update shìjiàn, gēngxīn kuāndù, wǒ xiǎng zuò de shì, dāng w = 6 de shíhòu, zhōngzhǐ diào resize shìjiàn, jiùshì bù gěi tā tuō dòngle
展开
420 / 5,000
It is a grid. I currently have a nine-grid grid. Their default parameters are as follows: [{"id":"item1","x":0,"y":0,"w":4},{"id":"item2","x":4,"y":0,"w":4},{"id":"item3","x":8,"y":0,"w":4},{"id":"item4","x":0,"y":1,"w":4},{"id":"item5","x":4,"y":1,"w":4},{"id":"item6","x":8,"y":1,"w":4},{"id":"item7","x":0,"y":2,"w":4},{"id":"item8","x":4,"y":2,"w":4},{"id":"item9","x":8,"y":2,"w":4}] When I adjust the width of the first grid, the resize event will return w = 5. Then I execute the update event to update the width. What I want to do is to terminate the resize event when w = 6, that is, to stop dragging it.

**Comment by 9yues** [comment]
It is a grid. I currently have a nine-grid grid. Their default parameters are as follows: [{"id":"item1","x":0,"y":0,"w":4},{"id":"item2","x":4,"y":0,"w":4},{"id":"item3","x":8,"y":0,"w":4},{"id":"item4","x":0,"y":1,"w":4},{"id":"item5","x":4,"y":1,"w":4},{"id":"item6","x":8,"y":1,"w":4},{"id":"item7","x":0,"y":2,"w":4},{"id":"item8","x":4,"y":2,"w":4},{"id":"item9","x":8,"y":2,"w":4}] When I adjust the width of the first grid, the resize event will return w = 5. Then I execute the update event to update the width. What I want to do is to terminate the resize event when w = 6, that is, to stop dragging it.

**Comment by adumesny** [comment]
again grid **ITEM** (language thing) and set maxW:6 on that item.
