### ISSUE TITLE
Handle not working on added widgets

### ISSUE THREAD

**Issue by damien-schneider** [gridstack/gridstack.js#2788]
## Subject of the issue
The handle grid property doesn't work for grid items added after the grid initialization.

## Your environment
* version of gridstack.js - 13.3.1
* which browser/OS - Chromium & Gecko & Webkit

## Steps to reproduce

Simply add the following button to the `title_drag.html` example (on the `gh_pages` branch)
```html
<button
    type="button"
    class="btn btn-primary"
    onclick="grid.addWidget({ w: 3, h: 3 })"
  >
    Add new item
  </button>
```

## Video

https://github.com/user-attachments/assets/fc65c0da-472e-4e35-9ad8-26b1efc3312d

## Expected behavior
The handle class should work on the items added after the grid init

**Comment by adumesny** [comment]
not a bug. `grid.addWidget({ w: 3, h: 3 })` doesn't contain the html that has a title area `<div class="card-header">- Drag here -</div>` so nothing special to drag (default to entire area - see #2790

**Comment by damien-schneider** [comment]
Oh, you're right I've tried with the className="card-header" to the added widget and it works well.

Sorry and thanks for the reply !
