### ISSUE TITLE
Gridstack makes the whole component draggable if the custom drag handle is not found at init time

### ISSUE THREAD

**Issue by BrannJoly** [gridstack/gridstack.js#2790]
## Subject of the issue
when setting a custom drag target with handle: '.custom-draggable-class', if GridStack is initialized before the div with the custom drag handle is rendered, GridStack defaults to making the whole component draggable.

## Your environment
* gridstack 10.3.1
* Chrome/MacOs

## Steps to reproduce
See example [here](https://jsfiddle.net/vishaalagartha/gvt4390e/9/) posted in [this SO question](https://stackoverflow.com/questions/78369497/gridstack-does-not-adhere-to-dynamic-drag-handles)

## Expected behavior
Gristack should respect the custom drag handle. If there's no drag handle matching the custom class, the item should not be draggable at all.

**Comment by adumesny** [comment]
yes and no. I could see it go either way... I guess if I cna detect a custom class vs the default one then I cold make the case to avoid dragging if not found as that would be a way for user to say noMove using classes...

**Comment by BrannJoly** [comment]
let me elaborate on my use case :
I'm using GridStack to display a list of plotly charts, which uses drag n droping a lot (to zoom, select, etc). So it's very important for me that the whole component is not draggable!
It almost always work, but from time to time there must be a race condition somewhere and GridStack initializes before my widgets have been rendered.

When that happens, the whole page must be reloaded.

There's no easy way to fix that problem.

On the other hand, if the user provides a custom class that doesn't exist, I would say it's on him to fix that bug (and it's very easy to fix!)

**Comment by adumesny** [comment]
Don’t init gridstack until your content is (or div you care) is fully loaded. Not being able to drag is broken as well. Not going to special case your instance…
