### ISSUE TITLE
Rotation not possible when resizing is disabled.

### ISSUE THREAD

**Issue by MadMikeyB** [gridstack/gridstack.js#2793]
## Subject of the issue
Rotation is not possible when resizing is disabled.

```
        var gridStackOptions = {
            disableResize: true, //comment / remove this and rotation works.
            float: true,
            column: 10,
            row: 68,
            minRow: 1,
            margin: 1,
            cellHeight: 50,
        };
```

## Your environment

* version of gridstack.js - 10.3.1
* which browser/OS - macOS 14.5 - Firefox 131.0b6 (aarch64)

## Steps to reproduce

https://jsfiddle.net/d87m6xbg/

## Expected behavior

When pressing R the cell/widget should rotate. However when disableResize is set to true, the cell/widget does not rotate on pressing R.

**Comment by adumesny** [comment]
This is as expected if you can change the size rotating 1x2 into 2x1 doesn't make sense

**Comment by MadMikeyB** [comment]
Apologies, not sure if I understand. Is it because the rotate system is using the resize system under the hood, and so disabling the resize system also disables the rotation system?

I understand that rotation is just switching the width by the height, e.g. if you have a width 3 and height 2 cell, and you rotate it, it is now a width 2 and height 3 cell. However when resizing is disabled, attempting to rotate a width 3 height 2 cell does nothing. Is that because it uses resize under the hood?
