### ISSUE TITLE
Loading in 1-column layout, then going to 2-column layout only triggers "change" event once, not on every transition (using columnMax: 2)

### ISSUE THREAD

**Issue by whobubble** [gridstack/gridstack.js#2795]
## Subject of the issue
Using these configuration options:
```
...
columnOpts: {
  breakpoints: [{ w: 450, c: 1 }],
  columnMax: 2,
}, 
...
```
When loading in 1-column layout (small screen), then widening the screen to show the 2-column layout, the `change` event of the grid is only triggered once. Any layout change afterwards does not trigger `change` anymore.
Loading in 2-column layout, going back and forth between 1-column and 2-column layout triggers a `change` event every time.
This does seems to only occur when using `columnMax: 2` specifically.

## Your environment
* version of gridstack.js - 10.3.1
* Mac / Chrome

## Steps to reproduce
https://jsfiddle.net/4cpmd0sw/2/

Short video illustrating the behaviour, logging `grid change` to the console using `grid.on('change', () => console.log('grid change'))`
![Kapture 2024-09-23 at 15 18 35](https://github.com/user-attachments/assets/3ad84b72-3950-4829-871c-ae14bc5b19aa)

## Expected behavior
Whenever the number of columns changes as per the `columnOpts` configuration, a `change` event should get fired.

**Comment by adumesny** [comment]
first off you are missing https://cdn.jsdelivr.net/npm/gridstack@10.3.1/dist/gridstack-extra.min.css
(why things don't render) for 2 column
