### ISSUE TITLE
Custom Components not Reloading upon Input change (even with Signals)

### ISSUE THREAD

**Issue by ScarVite** [gridstack/gridstack.js#2807]
## Subject of the issue
When having my Custom Components registered and in gridstack, now if due to a user input my component input change, it doesn't rerender and showcase the new data.
Tested it inside of Gridstack and Outside and it's working outside but now when my component is in Gridstack.

user, year and month are signals that are number based.
My Config:
```js
	private componentInputs =  computed(() => {
		return {
				user: this.user(),
				year: this.year(),
				month: this.month(),
			}
		})
		
		protected widgetOptions: Signal<WidgetOptions[]>  = 	computed(() => [ // or call load()/addWidget() with same data
		{
			minH: 3,
			minW: 4,
			selector: 'tb-customers-widget',
			input: this.componentInputs(),
			component: CustomersWidgetComponent,
			permission: this.Permissions.CONTROLLING_WIDGETS_SALES_CUSTOMERS
		}]);
		
	public gridOptions: NgGridStackOptions = {
		cellHeight: 50,
		margin: 5,
		minRow: 1, // make space for empty message
		acceptWidgets: true,
		float: false,
		children: this.widgetOptions()
	}
	
	//HTML
	<gridstack [options]="gridOptions" (changeCB)="onChange($event)" #gridwidget>
	          <div style="color: black;" empty-content>message when grid is empty</div>
        </gridstack>
	
```
When i change the input, onChange gets called with the nodesCB, which include the new data but my components dont rerender
![grafik](https://github.com/user-attachments/assets/985facd4-8773-44d8-bd5c-0c0df1cf9697)

## Your environment
    "gridstack": "^10.3.1",
    Win 11 Firefox 130.0.1

## Expected behavior
The Components where the Inputs have been passed along should rerender/acknowledge the changed Inputs

**Comment by ScarVite** [comment]
Might be Related,
[ContentChildren can't see anything inside that ng-template element because it interprets a bare ng-template tag basically the same as it would an HTML comment - there's nothing there for it to read.](https://stackoverflow.com/a/50803568/11201512)

since the gridstackItems prop always seems to be empty whenver i try to access it.

**Comment by ScarVite** [comment]
Found a Workaround, since my main issue is the gridItems being Empty

in gridstack.component.ts Line.238+
```js        
if (type) {
 const childWidget = gridItem.container?.createComponent(type)?.instance as BaseWidget;
 // if proper BaseWidget subclass, save it and load additional data
 if (childWidget && typeof childWidget.serialize === 'function' && typeof childWidget.deserialize === 'function') {
   gridItem.childWidget = childWidget;
   childWidget.deserialize(w);
 }
 gridComp?.gridItems.push(gridItem);
}
```
        
 Added a new property in gridstack.component.ts Line.238+
 ```js
   /** track list of TEMPLATE grid items so we can sync between DOM and GS internals */
  @ViewChildren(GridstackItemComponent) public gridstackItems?: QueryList<GridstackItemComponent>;
  /** Workaround since ViewChildren doesn't work with ng-content **/
  public gridItems: GridstackItemComponent[] = [];
  /** container to append items dynamically */
  @ViewChild('container', { read: ViewContainerRef, static: true}) public container?: ViewContainerRef;
  ```
  
 in the Main Parent, just call deserialize for each component with the new input data
 ```js
for (let gridItem of this.gridWidget.gridItems) {
  gridItem.childWidget?.deserialize({ input: this.componentInputs() })
}
````

**Comment by adumesny** [comment]
@ScarVite I get what you are doing here. `@ViewChildren` (or the current code  ` @ContentChildren`) doesn't work with ng-content TEMPLATE based layout, but you also don't need to store another array (that now needs to track removal as well).

Just use `grid.engine.nodes.forEach(n => n.el._gridItemComp.childWidget.deserialize(...)`

also it's not clear from your code above when you call deserialize() on all children ? it's done on creation and those should map to @Input on the widgets that can be used in their template when the value changes. Also note that `NgCompInputs` is assumed to be simple structure, not some function or Signal.

**Comment by adumesny** [comment]
all I'm saying is use engine.nodes instead of creating yet another list that will get out of sync... and I added a cast.
