### ISSUE TITLE
grid item not taking dynamic height as the component just takes  min-height

### ISSUE THREAD

**Issue by mudassirkhanShipthis** [gridstack/gridstack.js#2812]
## Subject of the issue
grid item not taking dynamic height as the component just takes  min-height.
im using grid stack for my angular project  my grid items are not taking proper height i have to give min height for each item which is causing issue of overflow

## Your environment
brave browser
 "gridstack": "^10.3.1",

## Expected behavior
it should take a dynamic height instood of adjusting min height

**Comment by adumesny** [comment]
not a proper bug filing - review the instructions. also you didn't say if you use sizeToContent:true option.

**Comment by mudassirkhanShipthis** [comment]
yes i have mentioned  sizeToContent:true option
  
  gridStackOptions: GridStackOptions = {
    margin: 5,
    removable: '.trash',
    sizeToContent: true,
    cellHeight: '3rem',
    resizable: { handles: 'e , w' },
    acceptWidgets: true,
    animate: true,
    float: true,
    columnOpts: {
      breakpointForWindow: true,
      breakpoints: [
        { w: 768, c: 1 },
        { w: 1280, c: 2 },
        { w: 4000, c: 3 },
      ],
    },
  };
