### ISSUE TITLE
Go back return a size inorder change column

### ISSUE THREAD

**Issue by gisdar** [gridstack/gridstack.js#2824]
![image](https://github.com/user-attachments/assets/a822186e-ae7f-41b8-8c7b-c078cf360655)
The line code highlight that a boolean if exist fill a list or empty when we need going to back a change column > befor column ,
read a cache layout and set all value but a read line break but not exist in nodeold values only in newNodes. I think necessay read a newOld realyout and values going to back the same position if that a custome position in diferente change column.

**Comment by adumesny** [comment]
sorry I don't understand your broken english. we try to use a higher level column count layout cached first, then above check for any new widgets that were added after we cached to position them.

what issue are you trying to fix ? post a running example showing the issue please.

**Comment by gisdar** [comment]
https://gridstackjs.com/demo/responsive_break.html  "Example in his page"

I'm working with a function in a 'Responsive' design that adjusts grid items (x, y, w, h) based on different screen sizes (in newNode change a new configuration in orde). My issue occurs when changing the number of columns, which works perfectly. However, when I switch from 3 columns to 6 columns, the grid relies on a cached layout, and when returning to 6 columns, it doesn't apply the responsive configuration because it uses the cached layout.

**Comment by adumesny** [comment]
the 6 -> 3 -> 6 works as expected in the demo. Again you are not showing what your issue is with a reproduceable case. I can't spend that much time on every single 'bug' people file.
![image](https://github.com/user-attachments/assets/ed09f530-d09f-4627-80f0-0b4b0a4965fa)
![image](https://github.com/user-attachments/assets/808fd92c-f048-480b-94f3-13cf723c829b)
![image](https://github.com/user-attachments/assets/548a651d-c6b4-44f3-bd21-93f45ab8ef36)

**Comment by gisdar** [comment]
![image](https://github.com/user-attachments/assets/43599516-9daf-44c8-ad27-123dfa8224a8)

I'm usually a the configuration in responsive the problem is when pass the 90 -> 80 that work correct change the column and the configuration inside of the "function" but when a going to back 80 -> 90 the before configuration take the save in cache layout not a the "fuction" because the line in the first comment read a current Node  and data exist in NewNode. I appreciete your comment and soluction.

**Comment by adumesny** [comment]
ok, so you're using a function() for `layout:ColumnOptions` and it's using cached version instead of calling you. Please supply a simple WORKING demo as bug report require if you have any hope of me looking at it...

**Comment by gisdar** [comment]
Thanks for you ask, my problem is my form the see, I release tests and function correct. Not issus. 
https://stackblitz.com/edit/vitejs-vite-vtzemc?file=main.js
