### ISSUE TITLE
Grid where elements have a fixed set of widths and heights

### ISSUE THREAD

**Issue by UweStolz** [gridstack/gridstack.js#2825]
## Subject of the issue

Hello, I want to make a grid where the elements have a fixed set of sizes of 100 per unit. 
(`cellHeight` is set to 100)

Is this possible at all and if so how can I achieve that?

## Your environment

* version of gridstack.js - v10.3.1
* which browser/OS - Edge/Chrome / Windows

## Steps to reproduce

There are a issues with my provided CSS override:
- If I drag an element and the further it is dragged to the right the further the placeholder differs from the actual hold element (see attachment)
- If one holds the LMB to resize the element and just moves the mouse a little the element suddenly increases its width beyond the cursor

https://jsfiddle.net/rt3zuvw1/3/

https://github.com/user-attachments/assets/33a5d04f-368f-4e8d-bd89-14ba05987faa

## Expected behavior

The element(s) should properly resize like _normal_

**Comment by adumesny** [comment]
gridstack is column based (% not px). the ONLY way to make an item 100px **width** is to force your grid to be n x 100px and have n columns, so you control the column width yourself. don't use CSS to override gridstack, just make your grid say 1200px with 12 olumns.
