### ISSUE TITLE
Angular demo app does not work

### ISSUE THREAD

**Issue by asarapas** [gridstack/gridstack.js#2833]
Angular Demo app does not compile or start. After updating gridstack version from 10.3.1 to 11.0.0 getting error:
[plugin:vite:import-analysis] Failed to resolve import "gridstack/dist/angular" from ".angular/vite-root/stacks-demo-2/main.js". Does the file exist?
src/app/app.module.ts:6:52
112|  
113|  // src/app/app.module.ts
114|  import { GridstackModule, GridstackComponent } from "gridstack/dist/angular";
   |                                                       ^
115|  
116|  // src/app/dummy.component.ts

## Using
Chrome on 

## Steps to reproduce
Download source of the project. Navigate to angular subfolder. Run "yarn install && npm run demo"

## Expected behavior
Demo app should run and everything should work

**Comment by asarapas** [comment]
Thank you for the fix! Demo app is running flawlessly and Drag&Drop is functioning as expected

**Comment by adumesny** [comment]
FYI, you should just do `yarn && yarn start`
