### ISSUE TITLE
Gridstack layout misalignment on initial load after OIDC login in Angular

### ISSUE THREAD

**Issue by jitendra-786** [gridstack/gridstack.js#2846]
## Subject
We are experiencing layout misalignment in the Gridstack component when navigating to the dashboard after an OIDC login in Angular.
OpenID Connect (OIDC) in the Angular application is causing a misalignment in the Gridstack layout (height) on first load and again if I refresh the same page working fine.

##environment
* version of gridstack.js - "gridstack": "^10.3.1",
* which browser/OS Chrome and windows 11 

## Steps to reproduce
Log in using OIDC authentication.
After successful login, OIDC redirects to the callback component.
From the callback component, navigate to the dashboard with the Gridstack layout.
Observe that the layout is misaligned (height or positioning issues).
Refresh the page and see that the layout displays correctly.

![image](https://github.com/user-attachments/assets/953be63c-a365-4507-91c7-ddde0a14ab6d)

![image](https://github.com/user-attachments/assets/60a25bdc-44c3-4576-a597-ff762643c2e8)

![image](https://github.com/user-attachments/assets/8d0a8731-3704-47fc-991d-17cd43397f6e)

![image](https://github.com/user-attachments/assets/d6b31a42-b92b-461a-adfb-16aae1eb07b4)
callback.component.html and callback.component.css is empty

https://github.com/user-attachments/assets/0b735b21-d03d-4755-be82-73a33556bd07

## Expected behavior
"layout should display correctly on the first load after OIDC login"

**Comment by adumesny** [comment]
this isn't a 'bug' I can act on, nor is it the lib itself. from the video looks like a timing issue and not loading the CSS to render widgets correctly. Might want to play with inserting the GS css into the main app. I use project.json "styles": [] to important GS css instead of components...
