### ISSUE TITLE
sizeToContent for nested grid (grow for children content)

### ISSUE THREAD

**Issue by te9ju** [gridstack/gridstack.js#2847]
## Subject of the issue
When using nested grids, is there any way to resize the first level grid item's height when items are stacked vertically inside the inner grid?

## Your environment
Gridstack.js - v 11.0.1
Arc Browser, macOS Sonoma 14.7

## Steps to reproduce

https://github.com/user-attachments/assets/0fa492d4-82e8-4e66-a59a-f6e40791c803

In the video attached above, the yellow container is an Gridstack instance accepting "section"(s) from the right hand side. Each section is then again initialized as another nested grid which accepts only "field"(s) from the right hand side.
Now, the behavior I'm trying to achieve is: When "fields" are stacked vertically inside sections, is there any way to automatically increase the height of the parent grid stack item (the section 1 which is added as the first item)?

**Comment by te9ju** [comment]
Apologies @adumesny . The last time I checked, the Slack invite link was broken/expired so I resorted to raising my query as an issue. And yes I think your understanding is right. I'd want the first level parent grid items to grow in height as each of their respective sub grids grow in height (due to addition of "fields", in this case).

**Comment by adumesny** [comment]
https://github.com/gridstack/gridstack.js/pull/2863 fixes this. you can see nested.html showing sizeToContent (first sub-grid) working.
