### ISSUE TITLE
willItFit returning incorrect value with custom nodes

### ISSUE THREAD

**Issue by zacwebb** [gridstack/gridstack.js#2873]
## Subject of the issue
When creating "custom" DOM nodes and calling `makeWidget`, the `willItFit` method seems to always return true for one additional widget outside of the `maxRows`. 

## Your environment
* gridstack.js v11.1.0
* Macos Sonoma, Chrome 130

## Steps to reproduce
~~https://jsfiddle.net/ve9j5xtm/1~~ Edit: https://jsfiddle.net/cnLzpymo/2/

Adding four widgets works as expected, however a fifth widget is able to be added despite it not technically fitting. Once the fifth widget is added `willItFit` correctly returns false

## Expected behavior
`willItFit` should be returning false in this example on the fifth widget

**Comment by zacwebb** [comment]
I've done some digging – `cleanupNode` called in `gridstack-engine.ts:656` seems to strip out any of the `x` and `y` data for the node passed in, which means it defaults to `x: 1, y:1` before adding it to cloned grid.

I believe fixing this would resolve the issue. Happy to open a PR if that seems right

**Comment by adumesny** [comment]
you can simplify you example to have just maxRow:5 and your items h:2 (if you think having +1 for the 4 is what shows the issue) and not have grid style properties... then it siolate the issue to gs placement. cellHeigh and margin are irrelevant here.

**Comment by zacwebb** [comment]
> you can simplify you example to have just maxRow:5 and your items h:2 (if you think having +1 for the 4 is what shows the issue) and not have grid style properties... then it siolate the issue to gs placement. cellHeigh and margin are irrelevant here.

Good point, have an [updated example here](https://jsfiddle.net/cnLzpymo/2/) and the issue still persists

**Comment by adumesny** [comment]
`willItFit(node: GridStackWidget)` does not take a dom element. that's likely your problem.
