### ISSUE TITLE
Drag is supported in all eight directions

### ISSUE THREAD

**Issue by jujingyi520** [gridstack/gridstack.js#2884]
![image](https://github.com/user-attachments/assets/7f0a7927-4e22-4870-8bfb-65ece385c978)

Will there be an API that allows these points to be dragged?

**Comment by jujingyi520** [comment]
Can you think about it? All eight of these points support drag and drop to change the size of the box

**Comment by adumesny** [comment]
demo/float.html already does that. `resizable: { handles: 'all'} // do all sides for testing`
