### ISSUE TITLE
sizeToContent property is not initialized from gs-size-to-content

### ISSUE THREAD

**Issue by schwarzwald** [gridstack/gridstack.js#2886]
## sizeToContent property is not initialized from gs-size-to-content
The sizeToContent property of the gridstack items is not initialized from the gs-size-to-content attribute when gridstack is created from existing HTML content.

## Your environment
* version of gridstack.js <= 11.1.0
* any browser

## Steps to reproduce
Initialize the gridstack from existing HTML, set gs-size-to-content="true" to some item.

https://jsfiddle.net/mntg136x/1/

## Expected behavior
Based on the documentation all item properties should be initialized from the HTML attributes.
See https://github.com/gridstack/gridstack.js/blob/master/doc/README.md#item-attributes

**Comment by adumesny** [comment]
honestly I stopped using dom attr a long time ago. tons of new feature are JSON/API only as for real apps you need to save data to json anyway, and doing a grid.load() is so much better....

**Comment by schwarzwald** [comment]
Thank you for the quick fix, I appreciate it.
