### ISSUE TITLE
Bug in Gridstack Version 11 - load Method Does Not Render HTML

### ISSUE THREAD

**Issue by dani110397** [gridstack/gridstack.js#2888]
## Description:
In Gridstack version 11, the load method fails to render the provided HTML structure within grid items. Instead of correctly displaying the content.

## Steps to Reproduce:
- Initialize a grid using Gridstack version 11.
- Attempt to load a grid configuration using the load method, with predefined HTML content inside grid items.
- Inspect the DOM to find that the grid's HTML content is not rendered.

## Expected behavior
When using the load method, the grid should correctly render the provided HTML content inside each grid item. The structure and content should appear as defined in the configuration, with all nested elements visible and interactive within the grid.

![Screenshot 2024-12-05 090357](https://github.com/user-attachments/assets/aa41d6c4-281a-484f-9f1d-5f513e2d6cfc)
![Screenshot 2024-12-05 090250](https://github.com/user-attachments/assets/46704d7d-6a84-4d22-9123-209139b5f73a)

**Comment by adumesny** [comment]
not a bug. v11 change - see https://github.com/gridstack/gridstack.js?tab=readme-ov-file#migrating-to-v11
