### ISSUE TITLE
When using compact , dragging a widget and placing it at a certain position is not placing it there. 

### ISSUE THREAD

**Issue by DIBSAAA** [gridstack/gridstack.js#2897]
[screen-capture (2).webm](https://github.com/user-attachments/assets/0cb934e2-8734-453b-abab-2fab9688dfd2)
## Subject of the issue
I have used gridInstance.compact() whenever the grid is getting initiated 

## Your environment
* version of gridstack.js - DON'T SAY LATEST as that doesn't mean anything a month/year from now.
* which browser/OS

## Steps to reproduce
You **MUST** provide a working demo - keep it simple and avoid frameworks as that could have issues - you can use 
https://jsfiddle.net/adumesny/jqhkry7g

## Expected behavior
Tell us what should happen. If hard to describe, attach a video as well.

**Comment by DIBSAAA** [comment]
Misclicked and posted it before completing the issue.

**Comment by adumesny** [comment]
this is not a proper bug filling. follow the required steps...
