### ISSUE TITLE
When using compact , dragging a widget and placing it at a certain position is not placing it there.

### ISSUE THREAD

**Issue by DIBSAAA** [gridstack/gridstack.js#2899]
## Subject of the issue
I have been following the react demo as presented here [https://github.com/gridstack/gridstack.js/tree/master/react](url). And I'm using compact after initializing the grid. This is to achieve a snaping UI and remove empty spaces in my Grid. 
But when I move a widget from one position to another the main feature should be that the dragged element should take the position it is being dropped at and the other elements should re-position to compact the grid. But, in my case, the dragged widget is being moved to fill the space. 
[screen-capture (2).webm](https://github.com/user-attachments/assets/7d7477a2-fcb9-4d1f-92cc-c7731958093c)

## Your environment
**gridstack**: "^11.0.1"
**react**: "^18.3.1"
## Steps to reproduce
Clone the react demo from this [https://github.com/gridstack/gridstack.js/tree/master/react](url) and then add gridInstance.compact('compact',false); in the initGrid function after grid initialization  . 

## Expected behavior
The expected behavior should be that the widget that gets moved into any position when compact is being applied should still take the position where it is being dropped and the other elements should switch places to fill empty spaces.

**Comment by adumesny** [comment]
from the video, this isn't a bug. compact() sort all elements and moves them in that order to fill the space starting at (0,0) - in your case you will have to write a custom version (simple code) that would lock the item already dragged and force the others to re-position.

ultimately you might be looking for an entire different collision flow.
