### ISSUE TITLE
Expanding grid-stack-item from any corner

### ISSUE THREAD

**Issue by harris2001** [gridstack/gridstack.js#2901]
It would be great to add an option that allows expanding each grid-stack-item from any corner.

While I understand this might involve changes to the core logic of the library, I believe the effort would be worthwhile, as it would make the entire library much more intuitive and user-friendly.

**Comment by adumesny** [comment]
you mean resize from any corner ? you can already do that. see https://gridstackjs.com/demo/float.html

don't forget to donate if you find this lib useful!
