### ISSUE TITLE
当我的小部件内为iframe的html页面,拖拽和调整尺寸大小都非常的卡顿,如何解决

### ISSUE THREAD

**Issue by Saskueeeee** [gridstack/gridstack.js#2903]
## Subject of the issue
Describe your issue here.
If unsure if lib bug, use slack channel instead: https://join.slack.com/t/gridstackjs/shared_invite/zt-2qa21lnxz-vw29RdTFet3N6~ABqT9kwA

## Your environment
* version of gridstack.js - DON'T SAY LATEST as that doesn't mean anything a month/year from now.
* which browser/OS

## Steps to reproduce
You **MUST** provide a working demo - keep it simple and avoid frameworks as that could have issues - you can use 
https://jsfiddle.net/adumesny/jqhkry7g

## Expected behavior
Tell us what should happen. If hard to describe, attach a video as well.

**Comment by adumesny** [comment]
closing. please post in english and describe the issue with example as required.

**Comment by Saskueeeee** [comment]
When my widget is an iframe html page, it is very stuck
