### ISSUE TITLE
Ability to specify left right padding on columns as well As vertical margin between rows

### ISSUE THREAD

**Issue by ishields** [gridstack/gridstack.js#33]
@troolee In some cases you want to be able to define the padding on columns and rows.  By default currently rows have a padding of 20px and columns have a padding of 10px on both left and right sides.  These values should be options.  This will allow users to have grid items touch if so desired.

**Comment by gustavomick** [comment]
just out of curiosity. Why is it 20 and not 0 by default.. or configuratble anyway, it seems to me a usual need.. any thoughts welcome in advance.

**Comment by tomgallagher** [comment]
I'm slightly stumped why there's no horizontal margin setting. Over-riding the horizontal margin settings in CSS does not seem to work for me. So I have a nice 20px gap between rows and no gap at all between columns.

**Comment by DavidKDeutsch** [comment]
I found that I had to add a class to the selector to get a high enough specificity: 

```
.grid-stack .grid-stack-item .grid-stack-item-content,
.grid-stack .grid-stack-item .placeholder-content {
    left: 10px;
    right: 10px;
}
```
