### ISSUE TITLE
acceptWidgets between nested grids

### ISSUE THREAD

**Issue by Coopyrightdmin** [gridstack/gridstack.js#386]
Hi,

I am using the `acceptWidgets: '.grid-stack-item'`option but I am not able to drag and drop from nested grids to others. Any suggestion?

```
<div class="row">
  <div class="grid-stack grid-stack-6">
    <div class="grid-stack-item">
       <div class="container grid-stack-item-content">
         <div class="row"> 
           <div class="grid-stack grid-stack-1"><!-- From Here! -->
             <div class="grid-stack-item">
               <div class="container grid-stack-item-content">Content</div>
             </div>
           </div>
        </div>
      </div>
      <div class="grid-stack-item">
        <div class="container grid-stack-item-content">
          <div class="row"> 
            <div class="grid-stack grid-stack-1"><!--To There! -->
          </div>
        </div>
      </div>
    </div>
  </div>
```

![nested containers](https://cloud.githubusercontent.com/assets/17612661/13524518/efc770ae-e1fb-11e5-9ec1-c0322713a0f8.png)

**Comment by radiolips** [comment]
I cannot speak for @troolee, who implemented this very cool feature, but I haven't personally tested doing this with nested grids. I appreciate the HTML you've included, but could you provide a `jsfiddle` for us to take a look at? I'm almost certain that it's a "bug," but it wouldn't hurt to verify that there's nothing amiss in the code you've got prepped!

-d

**Comment by Coopyrightdmin** [comment]
Sorry for the delay, here a sample.
https://jsfiddle.net/vbqn5tL8/

**Comment by filipevb** [comment]
Hi there,

Any news about this enhancement?

Thank you.

**Comment by mishrarajesh** [comment]
Hi,
I still see this issue in the gridstack version 0.4.0. Any updates?

**Comment by adumesny** [comment]
fix is in the next release ! the latest nested.html shows how to get it working between 2 nested grids.
Note: there is still a clipping of child during drag I need to figure out later...
