### ISSUE TITLE
Typings for _gridstack_node

### ISSUE THREAD

**Issue by DavidKDeutsch** [gridstack/gridstack.js#388]
I am working on fixing up the [TypeScript definition](https://github.com/DavidKDeutsch/DefinitelyTyped/blob/gridstack-0.2.5/gridstack/gridstack.d.ts) file for GridStack, and was planning on exposing the member types of the object stored in "_gridstack_node". At first glance the gridstack node object would appear to be an implementation detail, but since it is documented in the section on [serialization](https://github.com/troolee/gridstack.js#save-grid-to-array), I think it is appropriate for it to be typed as part of the public API. Anyway, looking at the code, it seems that sometimes the "numeric" types such as `x`, `min_width`, etc. are indeed numeric, but sometimes they are strings, as when they are set by `_prepare_element()`. So, I will need to type them as `string | number`. Are there any plans to change the code so that they are always numbers, like is currently done for the boolean members (via `Utils.toBool`)? This would make for a nicer interface.

**Comment by radiolips** [comment]
Very cool!

Are you referring to the `data-gs-_` attributes? If so, these are set on the DOM as strings. During all manipulation of them, though, they should be int. `parseInt(x, 10)` is slowly making its way into more of the code. We'll try to get these all done for the next release, `v0.3.0`. I'll leave this issue open until that time. Please let me know if this is/not what you're referring to!

**Comment by DavidKDeutsch** [comment]
Well, I am referring to is the direct assigning of those `dat-gs-` attribute values to properties of what you pass to `grid.addNode` in `_prepareElement`, i.e.

```js
           var node = self.grid.addNode({
            x: el.attr('data-gs-x'),
            y: el.attr('data-gs-y'),
            width: el.attr('data-gs-width'),
            height: el.attr('data-gs-height'),
            maxWidth: el.attr('data-gs-max-width'),
            minWidth: el.attr('data-gs-min-width'),
            maxHeight: el.attr('data-gs-max-height'),
            minHeight: el.attr('data-gs-min-height'),
```

It would be great if you could convert them to numbers before assigning them to the properties, i.e.
```js
            x: Number(el.attr('data-gs-x')),
            y: Number(el.attr('data-gs-y')),
            width: Number(el.attr('data-gs-width')),
            height: Number(el.attr('data-gs-height')),
            maxWidth: Number(el.attr('data-gs-max-width')),
            minWidth: Number(el.attr('data-gs-min-width')),
            maxHeight: Number(el.attr('data-gs-max-height')),
            minHeight: Number(el.attr('data-gs-min-height')),       
```

**Comment by radiolips** [comment]
@DavidKDeutsch I believe these should actually be `parseInt` and not `Number`, because they should all be integers, while `Number` allows for floats and doubles, as per https://developer.mozilla.org/en-US/docs/Glossary/Number

**Comment by adumesny** [comment]
closing. typedef is now part of gridstack (since I personally use TS) and been updated.
