### ISSUE TITLE
2 drop shadows when drag large widget between grids

### ISSUE THREAD

**Issue by troolee** [gridstack/gridstack.js#393]
There is a bug while dragging between two grids: http://take.ms/maoFv

**Comment by eagoo** [comment]
would u like fix this bug first?

**Comment by eagoo** [comment]
var dragOrResize = function(event, ui) {
             ...
                var n = el.data('_gridstack_node');

                //add if widget had been added to outer grid
                if (x < 0 || x >= self.grid.width || y < 0 || (n && n._added)) {

**Comment by eagoo** [comment]
#435

**Comment by adumesny** [comment]
that issue shown in the video is still there in 0.5.2-dev latest build (2 drop shadow showing, with one phantom left behind on drop).

**Comment by SolarEclipz** [comment]
To add a note on to this, I will receive phantom items with an outline, but when I try and move an item from a Grid below to the one above (or even above to below) the outline disappears and I am not able to put an item in that spot. Almost as if there is an invisible item-placeholder there. 

Currently running 1.0.0-dev I believe.

**Comment by k4st0r42** [comment]
The problem seems to be still there ?
V1.1.2

**Comment by adumesny** [comment]
yes, hasn't been looked at...

**Comment by zgilewski** [comment]
Any change to fix that issue in very near future ??

**Comment by adumesny** [comment]
How much is it worth to you? Feel free to contribute time or $ as I'm swamped these days...

**Comment by adumesny** [comment]
finally fixed in 2.0.1

**Comment by adumesny** [comment]
I can still see it sometimes... re-opening

**Comment by adumesny** [comment]
finally fixed in v4!
