### ISSUE TITLE
Dragging between nested groups

### ISSUE THREAD

**Issue by notbear** [gridstack/gridstack.js#395]
I'm trying to make an application where items can be copied from the palette to the canvas. 
After adding 'acceptWidgets' option the layout gets messed when I try to rearrange nested elements. A placeholder appears outside the nested grid, and dragged item also lands outside without possibility to move it back.

http://codepen.io/NotBear/pen/XdKWpr

**Comment by joemorcullo8** [comment]
is this fixed already?

**Comment by radiolips** [comment]
This is the same as #386
