### ISSUE TITLE
Different vertical margins for nested grids?

### ISSUE THREAD

**Issue by mattjneuber** [gridstack/gridstack.js#425]
I have a large parent grid with many nested grids within it. It seems that changing the vertical margin of any of them results in the vertical margin for all of the other grids being updated with the same vertical margin.  What I'd really like is for the vertical margin at the top level to be one value (say 50) and the nested grids to have a much lower one (say 8). Is this possible, am I missing something?

**Comment by mattjneuber** [comment]
As a followup to this, examining the Gridstack code in detail revealed that the "opts" object inside a Gridstack instance appears to be a reference that is shared across all instances. I was tipped off to this when I looked at opts.is_nested and it was true for everything, even the top-level grid.

Changing line 513 from

this.opts = _.defaults(opts || {}, {

to

this.opts = _.defaults({}, opts || {}, {

addresses that problem.  That alone doesn't completely address the issue in my post above, because it seems like setting vertical margin at the top level still cascades down to child grids, but I can set one level at the top level and then set different ones at lower levels and sort of get the effect I want. A temporary kludge solution.

**Comment by radiolips** [comment]
@mattjneuber This has been updated in the latest build. Could you take a look to see if it works now? We resolved several bugs, including the ones causing `_.defaults` to modify `this.opts`.

**Comment by mattjneuber** [comment]
The this.opts issue is fixed, however defining different vertical margins for nested grids still doesn't seem to be working for me. In the end, they all take what was defined at the top level.

**Comment by kool-kat** [comment]
It is picking up the change in verticalMargin for me in build 0.3.

Outer grid is verticalMargin=3 and inner grid is verticalMargin=0. 

[View Screenshot](https://drive.google.com/open?id=0BzZCxcWL5OdXZjJJN1FGZkNFZVU).

BUT changes of vertical margin between parent grid and child are affecting widget height calculations.

I expected the inner grid to stretch/adjust vertically to absorb the vertical margin (+-) difference of the parent grid AND inner widget heights would then line up to the parent grid boundary.

See orange spacing below inner1 and inner2 widgets in screenshot.

This wouldn't be visible in an ideal situation as the inner grid would incorporate the verticalMargin gap spacing of the parent grid AND inner widget heights would adjust accordingly.

**Comment by adumesny** [comment]
closing as the original issue has been fixed. sounds like @kool-kat is wanting % height to take available space (which changes as parent margin is affected) which is posted bug - if not create new one.
