### ISSUE TITLE
Locked items move when dropping an external item

### ISSUE THREAD

**Issue by aletorrado** [gridstack/gridstack.js#433]
Locked items work OK while dragging in the same GridStack instance, but when I drag and drop an item from another GridStack instance, or a plain jQuery draggable object, GridStack doesn't seem to recognise any of the locked items.

**Comment by aletorrado** [comment]
#434

**Comment by wrenn** [comment]
Any solution for this yet?

**Comment by radiolips** [comment]
@aletorrado @wrenn I'll try to take a look at this today. If I'm unable, it won't make `v0.3.0`, which will be released today, but I'll try to get this in today!

**Comment by macgyver76** [comment]
Any updates on this?

**Comment by radiolips** [comment]
When dragging from one grid to another, while still dragging, the held widget will only move unlocked widgets in released `v0.4.0`.
