### ISSUE TITLE
Dragging between gridstack issues: Disappearing gridstack-item, duplicate gridstack-item, resizing gridstack-item.

### ISSUE THREAD

**Issue by Gnewbie** [gridstack/gridstack.js#451]
Hi Gridstackers.

I've found a couple of bugs regarding moving gridstack-items from one gridstack to another:
1. Disappearing gridstack-items
   
   > https://gyazo.com/dd73e460f8b931ea6cfde71065d6f2b2
2. Creates "Invisible object" / duplicate object
   
   > https://gyazo.com/b884f98970411fe77e56e3766a8ba73b
   > 
   > eagoo comes up with a fix for this inhere:
   > https://github.com/troolee/gridstack.js/issues/393
   > 
   > However that causes for gridstack-items to sometimes lock in place inside a grid: 
   > https://gyazo.com/d49221dff820cb1ed17f07c6f8e7586b
3. Unable to resize
   
   > https://gyazo.com/f73d9831d429f55bfcfecb89d94e62b9
   > 
   > eagoo comes up with a fix for this inhere:
   > https://github.com/troolee/gridstack.js/issues/416
   > 
   > Doesn't seem to have any flaws, but dont know if there's a reason why it isnt in source distribution.

Any comments, hints or fixes are highly appreciated.
- Lasse.

**Comment by radiolips** [comment]
All of these should be resolved in released `v0.4.0`.

**Comment by roborto444** [comment]
![gridstack-dissapearing-components](https://user-images.githubusercontent.com/29983427/41431690-b21584d0-700b-11e8-9fca-52f11f02696c.gif)

I am experiencing disappearing components using v0.4.0.

**Comment by andrei-gheorghiu** [comment]
Here's a fiddle displaying the issue, using:

- Gridstack 0.4.0
- jQuery 2.2.4
- jQuery.UI.1.12.1
- Bootstrap 3.3.7
- lodash 4.17.10

https://jsfiddle.net/websiter/vubf817p/6/

**Comment by radiolips** [comment]
Wow, that's really strange. Thanks for letting me know. I'll take a look and will take a look at your PR. Could you open a new ticket for this? You can reference this ticket, but it'll be easier to identify that most of the issues here are fixed (just not all).

**Comment by radiolips** [comment]
@andrei-gheorghiu @Gnewbie This is resolved in the `develop` branch and will be included in the next release later this week.
