### ISSUE TITLE
mouse events not being captured

### ISSUE THREAD

**Issue by bsutton** [gridstack/gridstack.js#474]
We are inserting an iframe into a tile and having problems resizing the tile.

If you try to grow the tile there are no problems.

If you try to shrink the tile and move your mouse too fast then the mouse 'lets go' of the resize icon and the resize fails. If you move slow enough the resize works.

I'm wondering if you have failed to do a mouseCapture on the click event to ensure that you get all mouse moves until the mouse is released.

e.g.

```
function mouseDown(e) {
  e.target.setCapture();
  e.target.addEventListener("mousemove", mouseMoved, false);
}
```

The above ensures that all mouse events are captured.

Sorry but I'm not a good enough javascript programmer to submit a patch.

**Comment by radiolips** [comment]
It sounds like the iframe might be capturing the clicks, as you've mentioned. Could you provide a jsfiddle for us to see the bug in action, please?

**Comment by rlsutton1** [comment]
JSFiddel that reproduces the problem
https://jsfiddle.net/rlsutton1/j5m811zx/

**Comment by radiolips** [comment]
Though I haven't tried, this might help: http://api.jqueryui.com/draggable/#option-iframeFix -- will look into adding this to the next update.

**Comment by epelc** [comment]
Just ran into this.

I noticed you can make it smaller if you move your mouse outside of the iframe content so that the main window can capture your events.

**Comment by epelc** [comment]
An easy css only approach.

```
  .grid-stack-item.ui-resizable-resizing iframe {
      pointer-events: none;
  }
```
