### ISSUE TITLE
Drag down item not swapping but pushing cells below in floating mode

### ISSUE THREAD

**Issue by ds009** [gridstack/gridstack.js#519]
Hello, thank you for your great project gridstack.
I met a problem using it, when floating mode is activated(I need it to be float), all items(B,C,D...) below the currently dragged item(A) are pushed down, I hope they(B,C,D...) can be swapped up when A is dragged by some distance (e.g. B's height),How can I do it ?
I tried this example, https://troolee.github.io/gridstack.js/demo/float.html, it has the same problem.
![image](https://cloud.githubusercontent.com/assets/3932024/17847217/6bc7c49c-687f-11e6-8f15-10e6cd7081b2.png)

**Comment by Mijago** [comment]
I also run into this problem.
But got no fix yet, sorry.

**Comment by matoxxx** [comment]
I'm stuck too.
Is somebody working on it?

**Comment by wolfgangj** [comment]
I also have this problem.

**Comment by DevStrefa** [comment]
I thought that is intended behavior but since this issue is here, I also find this strange to work in this way.

**Comment by napoleaofw** [comment]
that's not happen when you set options like "data-gs-width" and "data-gs-height" (just that, in this case) to the element ".gridstack". But... even with that options, the drag feature seems a little limited... to test this, just populate all the element ".gridstack" with child elements. The objective of that, is occup all the space of the father element ".gridstack". Observe: it's almost impossible to drag the elements, in that case. Suggestions?
Sorry for my limited English... I'm brazilian.

**Comment by adumesny** [comment]
this is no longer happening - we save origY and restore as needed - see float demo:
![image](https://user-images.githubusercontent.com/3496166/71331806-8de79b00-24e8-11ea-95fa-28fff3755e9b.png)
![image](https://user-images.githubusercontent.com/3496166/71331816-98099980-24e8-11ea-8cce-6181b4ef6743.png)
![image](https://user-images.githubusercontent.com/3496166/71331826-a1930180-24e8-11ea-8c4c-dab5fa9a86ad.png)
![image](https://user-images.githubusercontent.com/3496166/71331838-aa83d300-24e8-11ea-88b0-a13106a4e1b1.png)

**Comment by antoine92190** [comment]
@adumesny Hey! Thank you for your great library it's such a great work 🙏
It seems this issue still exists to this day. The item is pushed down first, before being swapped when we continue pushing. Is it expected?

https://github.com/user-attachments/assets/d06661e3-8437-4c5a-bef6-33af37cfd0f3

**Comment by adumesny** [comment]
@antoine92190 yeah that is correct and matches what I show above. in float mode the gesture always uses check where the drag item can be placed vs the original layout. when you move 2 to second row, it has to push 1 out of the way to fit. in 3rd row it fits without moving anything so the original layout is restored but only what you drag changes. as designed.

**Comment by antoine92190** [comment]
@adumesny Actually the issue is more with big items (see the video). It's difficult to move items around, especially with the high speed of the scroll than enhances this behavior.
Do you consider that this behavior can be improved?

If yes I'm happy to support you on this, either trying to fix it or send you a donation for your time.
Let me know!

https://github.com/user-attachments/assets/9cc50be3-967b-4e28-a8e7-5539c9f5eddd

**Comment by adumesny** [comment]
@antoine92190 totally different thing (please don't hijack this thread) with scroll speed - see #2188 and few others... and yes donation would be needed for me to take a look at this time.
