### ISSUE TITLE
Resize the grid make the items collapsed.

### ISSUE THREAD

**Issue by jpremkumar** [gridstack/gridstack.js#520]
When the page is dynamically resized, the items (nodes) inside the grid should auto adjust. 

i.e. full width (Default) [1,2,3,4,5,6], 
In 75%, it should come as 
[1,2,3]
[4,5,6]

in 50% 
[1,2]
[3,4]
[5,6]

in 30$ is should be
[1]
[2]
[3]
[4]
[5]
[6]

I've referred the [Responsive Grid demo](https://github.com/troolee/gridstack.js#resizing-active-grid).  I'm expected the above behavior. But when resize, the items are overlapping. Also, while maximize, the items are not arranging the same order. 

Check out this [example](http://troolee.github.io/gridstack.js/demo/responsive.html) and the refer the below screenshots for the issue.

![cap1](https://cloud.githubusercontent.com/assets/4466566/17853591/22ec73a6-688b-11e6-96c5-05f7233a5d40.gif)

![cap2](https://cloud.githubusercontent.com/assets/4466566/17853617/52e2cda8-688b-11e6-9f80-739eafaa43e0.gif)

**Comment by troolee** [comment]
Hi,

Thanks for reporting an issue. This feature is pretty experimental and not ready for production usage. But we will take a look on it.

//cc @radiolips

**Comment by vishakaw1** [comment]
Hi, I pulled out the latest commit from github(#786) and build a grid with 6 widgets. I want the same kind of behaviour.
100%
[1,2,3]
[4,5,6]

50%
[1,2]
[4,5]
[3,6]

one column mode
[1]
[2]
[3]
[4]
[5]
[6]

When resize, the items are collapsing to expected #of columns. But order, #of rows and positions are all wrong like following.

100%
[1,2,3]
[4,5,6]

50%
[0,2]
[3.5]
[  ,1]
[  ,4]

one column mode
[0]
[2]
[3]
[5]
[1]
[4]

Also, while maximize, the item sizes are wrong and are not arranging the same order.
[responsive-gridstack.zip](https://github.com/gridstack/gridstack.js/files/1347978/responsive-gridstack.zip)

Can we expect this behaviour from your version 1.0 release.

**Comment by radiolips** [comment]
Unfortunately, this won't make 1.0, but hopefully I'll fix up the responsive code shortly thereafter.

**Comment by radiolips** [comment]
This library is very much still in progress. The responsive feature is on the road map, but probably won't be included in the next release (which we hope to be version 1). We'll be working on the responsive grid as quickly as we can, but eliminating dependencies and tightening up grid movement currently have higher priority.

**Comment by vikasKacholia** [comment]
Hello ,

is there any update on this ?
I also see the ordering get changes on window resize.

i also have a a requirement where on resize instead of responsive behavior i.e changing the size of grid based on window size my grids should go to next row.
any idea how to achieve this?

**Comment by radiolips** [comment]
Hey @vikasKacholia . This is still in the works, but there are some other features that we're working on before this one. I'm still leaving this open, and I'll leave your other ticket (#1031 ) open as well, until we can look into that.

**Comment by adumesny** [comment]
closing this as I re-wrote on `setColumn()` handles responsive design - see  https://gridstackjs.com/demo/responsive.html
