### ISSUE TITLE
auto scroll container

### ISSUE THREAD

**Issue by iamwelk** [gridstack/gridstack.js#522]
In a container i init the grid and the grid is too long so the container has scrollbar.When i drag the item to top or bottom, it will not auto scroll. it displays like the follow picture
![image](https://cloud.githubusercontent.com/assets/6983075/18083883/aa9da728-6ed7-11e6-98f1-2cdcc44aeba2.png)

so, i want to know if there is some ways to make it can auto scroll when dragging?

**Comment by shaharkazaz** [comment]
I added scroll support for my project.
check out the script that I wrote : http://codepen.io/shaharkazaz/pen/wzgoBm
I would like to open a PR for that scroll support @troolee if you can help me with that :)

**Comment by jishanshaikh** [comment]
i have same issue,  i have many containers in grid so need auto scroll while dragging.
it will be great if gridstack provide that functionality.

**Comment by Mickel97** [comment]
add "scroll: true" in the gridstack.js

draggable: _.defaults(opts.draggable || {}, {
                handle: (opts.handleClass ? '.' + opts.handleClass : (opts.handle ? opts.handle : '')) ||
                    '.grid-stack-item-content',
                scroll: true,
                appendTo: 'body'
            }),

**Comment by radiolips** [comment]
This is now a default feature in the latest dev branch.
