### ISSUE TITLE
Speed up Rendering

### ISSUE THREAD

**Issue by amberlampsio** [gridstack/gridstack.js#525]
I was curious, is it possible to implement something like FastDom  (https://github.com/wilsonpage/fastdom) to increase page rendering.  I'm rendering approximately 300-400 widgets, causing DOM to freeze.  

Any solutions to this?

~250 grid items

<img width="1280" alt="screen shot 2016-09-07 at 5 01 58 pm" src="https://cloud.githubusercontent.com/assets/9902982/18328446/d98892a0-751c-11e6-8fa0-55b197b59139.png">

**Comment by amberlampsio** [comment]
~250 grid items

<img width="1280" alt="screen shot 2016-09-07 at 5 01 58 pm" src="https://cloud.githubusercontent.com/assets/9902982/18328446/d98892a0-751c-11e6-8fa0-55b197b59139.png">

**Comment by orgilor** [comment]
https://github.com/troolee/gridstack.js/pull/203
you got a fix there that incearse performance. i checked with 210 widgets and it was pretty smooth

**Comment by orgilor** [comment]
@troolee can you insert the 1 line fix:
`-            nn = {x: 0, y: node.y, width: this.width, height: node.height};
+            nn = {x: node.x, y: node.y, width: node.width, height: node.height};`
?

**Comment by troolee** [comment]
@orgilor I will check this

**Comment by benoitvb** [comment]
Is there any improvement regarding this issue ?
For the records changing this line improves performance but breaks the layout.

Thanks a lot !

**Comment by radiolips** [comment]
I'd love faster rendering, but this improvement won't work. Making the change listed causes a problem in floating widgets. I'm closing this, but if anyone has any more good ideas that can make gridstack more efficient, I'm happy to take a look.
