### ISSUE TITLE
nested grid not accepting the parent accept type widgets

### ISSUE THREAD

**Issue by Bhimisetty** [gridstack/gridstack.js#543]
Hi,

I just want to work with the nested grids. All the grids including nested should accept the same kind of widgets.
[http://codepen.io/anon/pen/VKVRyw/]
In the above linke, i am expecting both the drop areas should accept the widgets (greyed boxes). But the parent grid only accepting, the nested grid is not accepting.
What needs to be done in order to work with this. Is this achievable?

**Comment by radiolips** [comment]
Closing this in favor of #386 which I believe to be the same.
