### ISSUE TITLE
Drop position(placeholder) is wrong

### ISSUE THREAD

**Issue by pilisir** [gridstack/gridstack.js#566]
Hi, 
I try to drag item as a helper in a contain with "margin-left", then the drop position(placeholder) will get in wrong place.

https://jsfiddle.net/qexsp0km/

If you remove those codes about helper of draggable OR css of margin-left, everytihng is fine.
It looks like the drop position is also effected by margin-left.

Could anyone please provide some solution or workaround, thank you.

**Comment by jasonjianfr** [comment]
I found a workaroundhere, just write the the helper html codes and appen it beside the gridstack contain codes in helper function, the drop position would be fine.

**Comment by radiolips** [comment]
@jasonjianfr When I remove the margin-left, it still appears to be in a strange place. Are you seeing this as well?

**Comment by jasonjianfr** [comment]
I see fine.
I have updated the sample code and adjucted to declare the "margin-left" outter again.

https://jsfiddle.net/qexsp0km/1/
