### ISSUE TITLE
Iframe in widget relloads when resizing the window

### ISSUE THREAD

**Issue by vishakaw1** [gridstack/gridstack.js#585]
Hi,
  I have include a iframe into a widget and when I resize the window, iframe get reloads (when grid goes to one-column-mode). Looks like it is a gridstack.js bug. 
Following shows the working example.
https://jsfiddle.net/j5m811zx/2/

**Comment by joshmn** [comment]
```
.grid-stack-item.ui-resizable-resizing iframe {
      pointer-events: none;
  }
```

**Comment by gabrielalan** [comment]
Hi guys... this is till a big problem. The solution with `pointer-events: none;` does not work and I don't even know how it would... do you haves have another solution?

I'm suspecting of this line:
```self.container.append(node.el);```
On the `onResizeHandler`.

**Comment by adumesny** [comment]
@gabrielalan please create an example showing the problem with the latest 2.0.1 (the one above uses 0.2.3 which is ancient) so we can re-open if still an issue.
