### ISSUE TITLE
Destroying and re-creating a grid does not preserve row placement

### ISSUE THREAD

**Issue by graemechapman** [gridstack/gridstack.js#592]
When initialising gridstack from existing items in single column mode, the items are positioned correctly according to their x and y attributes, but the `data-gs-y` attribute is modified (usually resets to 0, but in some instances another random number). Therefore, calling `destroy(false)` and then re-initialising gridstack results in the grid being re-ordered at random. `data-gs-x` is left untouched, expected behaviour would be for the y attribute to be preserved also. 

I have created a fiddle demonstrating this [here](https://jsfiddle.net/7hw1s95y/2/).

**Comment by radiolips** [comment]
@graemechapman Again, sir, you've found a pretty neat bug. Thanks for the jsfiddle. I'll take a look.

**Comment by radiolips** [comment]
@graemechapman I think the fiddle might be busted? If you're still having a problem, could you please provide for me a working fiddle and I'll take another look?

**Comment by graemechapman** [comment]
Hi @radiolips it looks like the issue is still present - if you watch the data-gs-y attribute when you initialise the grid, they all get set to 0.

I have updated the fiddle slightly to hopefully make it a bit easier to see what's going on.
