### ISSUE TITLE
gridstack.js swapping my elements around when vue.js removes a node

### ISSUE THREAD

**Issue by nyoung697** [gridstack/gridstack.js#604]
Not sure if this is proper etiquette to post in two forums, but I originally posted this question here:
http://stackoverflow.com/questions/42311359/why-is-gridstack-js-swapping-my-elements-around-when-vue-js-removes-a-node

I am trying to setup gridstack.js to work with my vue components as it does in this knockout example: https://github.com/troolee/gridstack.js#use-with-knockoutjs/.

Here is a codepen of what I have: https://codepen.io/nyoung697/pen/BperoZ

1. Add 3 textboxes to the form by clicking 'textbox' 3 times.
2. Delete the top textbox by hovering overtop and clicking the trash can.

Deleting them from the top down works fine (so it seems). The newest element is at the top, as gridstack is adding it to the top. So this is the last element in the array.

1. Now try resizing the textboxes and deleting them in a random order.

Gridstack is getting confused and swapping elements around on the page. I have no idea why it is doing this. Can someone please help me figure this out? I have been going around in circles for weeks trying so many different things.

I added some console logging to show what id is being referenced. When you delete the elements in order of the last one added, the id in the "destroyed" method is the same as all the other methods/hooks being hit. However if you try to delete them in a random order, the id that is being printed in the destroyed method is different.

**Comment by OLRG** [comment]
I have the same issue but with angular.

**Comment by radiolips** [comment]
This is really strange. I wonder if it might be related to #592 . I'll revisit this ticket after #592 gets fixed. Thanks for reporting, @nyoung697 !

**Comment by Yarisrespect** [comment]
I wonder if you found out solution!

**Comment by adumesny** [comment]
closing due to age  and low usage - please re-open if still an issue.

**Comment by vishaldodiya** [comment]
Is there any workaround for this?
I am still facing the issue

**Comment by adumesny** [comment]
can you post a recent example with latest lib ? 
also make sure to check the vue3.html we now supply as that may answer your questions.
