### ISSUE TITLE
Jquery Version in Bower Dependencies Should be the Oldest Version Necessary 

### ISSUE THREAD

**Issue by gooeyideas** [gridstack/gridstack.js#629]
In issue #612 it is stated:
"There shouldn't be any issue using older jQuery. The primary use of jQuery is to allow for jquery-ui (in addition to some other simple functions). Make sure that you're using a version of jquery-ui that is compatible with your version of jQuery"

Your dependencies are on "jquery": ">= 3.1.0" which forces bower to update Jquery to that version (if your project's version is lower than 3.1.0) when it is not really necessary. This is a huge impediment when implementing your plugin that can be easily addressed by setting your Jquery dependency to ">=1.6".

**Comment by radiolips** [comment]
@gooeyideas Good point. We're planning on removing all dependencies in the near future, but depending on how far out that roadmap becomes, we'll consider updating this dependency to use an earlier version. I'll leave this ticket open and will update it either way.

**Comment by radiolips** [comment]
@gooeyideas Update - `v0.3.0` went out with the higher jquery dependency. However, `v1.0.0` is going to eliminate the jquery dependency altogether. Look for it on the `develop` branch next week.

**Comment by jessenieminen** [comment]
Any update on the date of the new release without the dependencies?

I'm stuck using a really old version of underscore and jQuery UI with a bunch of non-compatible custom extension built on top and would love to see this being made available.

**Comment by radiolips** [comment]
@jessenieminen lodash has been removed! jQuery and jQuery UI removals are coming, but...it's taking awhile...

**Comment by adumesny** [comment]
making the change is easy, the hard part is figuring out the lowest rev we can still run without errors... if someone could test and let us know that would be great! 
Our focus is on removal at this point...

**Comment by adumesny** [comment]
fixed in next release.
