### ISSUE TITLE
Cannot remove widget inside grid

### ISSUE THREAD

**Issue by EpsilonOrionis** [gridstack/gridstack.js#647]
Hi, I want to remove a widget inside the grid, but it returns me: `TypeError: node is undefined` in the browser console. The code that I'm using to remove the widget is: 

`this.grid.removeWidget($('#gsi-1'));`

and the code to create the widget is this:

`var node = {
                      x: 12 * Math.random(),
                      y: 5 * Math.random(),
                      width: 1 + 3 * Math.random(),
                      height: 1 + 3 * Math.random()
                   };`

`this.grid.addWidget($('<div><div id="gsi-1" class="grid-stack-item-content"/><div class="grid-stack-item-content"><button onclick="deleteWidget()">Delete me</button></div></div>'),
                            node.x, node.y, node.width, node.height, false, null, null, 0, 1);`

Thanks for your time and your help 👍

**Comment by radiolips** [comment]
Hey, @EpsilonOrionis ! Could you put together a quick jsfiddle for me? Your code looks fine, but let's get down to the bottome of this!

**Comment by EpsilonOrionis** [comment]
Sure. Here you are: [https://jsfiddle.net/endpdokg/](url)
Tell me if you need more information/code

**Comment by radiolips** [comment]
Have you tried running that? I immediately get an error.

**Comment by EpsilonOrionis** [comment]
I've never used JSFiddle. When I press "Run" I don't get anything

**Comment by radiolips** [comment]
Try opening the console. You're getting an error because jQuery isn't referenced.

**Comment by EpsilonOrionis** [comment]
Do I have to include jQuery plugin?

**Comment by radiolips** [comment]
Yeah, you'll need all of the resources that gridstack typically needs.

**Comment by EpsilonOrionis** [comment]
Oh my god... seriously?? I don't have time right now... Could you please do it for me now? Otherwise we try to solve it tomorrow

**Comment by radiolips** [comment]
I've got a full-time job as well :P whenever you have time, just get it fixed up and ping me and I'll take a look!

**Comment by EpsilonOrionis** [comment]
Ok, thank you @radiolips

**Comment by radiolips** [comment]
@EpsilonOrionis Any update on this?

**Comment by EpsilonOrionis** [comment]
No, I didn't try it anymore, because I have no time... But I will need it in the future I'm sure about this, so if you could put here a working example to let me try it so I can let you know. You could make an archive and the send me the link to the download. I know, maybe I'm asking too much, but if you could it would be great 👍

**Comment by mandys** [comment]
@EpsilonOrionis - there might have been some issue with the html you were injecting. Closing of a div tag. Anyways, I setup a jsfiddle with a working example to removeWidget.

Please take a look here:
https://jsfiddle.net/mandys/1jsj306g/2/

I agree, setting up a jsfiddle can be a bit of a pain :-)

**Comment by EpsilonOrionis** [comment]
Thank you @mandys (JSFiddle 😄)

**Comment by radiolips** [comment]
Thanks, @mandys ! @EpsilonOrionis , can this issue be closed now?

**Comment by EpsilonOrionis** [comment]
No please, I'll tell you as soon as I can try it 😄
