### ISSUE TITLE
how to add nested grids inside grids dynamically using add button

### ISSUE THREAD

**Issue by saurabhsbhatt** [gridstack/gridstack.js#654]
Hi,

Can anyone please help me to customize the default functionality of gridstack.js for bootstrap version such that I would be able to dynamically add NESTED grids inside parent grids using add button which would be on the grid itself. Something like below:

![image](https://cloud.githubusercontent.com/assets/28060104/25648727/b63d7c9e-2fec-11e7-9572-a14db22d0d28.png)

**Comment by radiolips** [comment]
@saurabhsbhatt Is there something specific you're having a problem with?
