### ISSUE TITLE
Number of columns limited by CSS

### ISSUE THREAD

**Issue by Matthew-Bonner** [gridstack/gridstack.js#658]
If I want to use Gridstack to create a customisable interface with an unlimited number of columns where people can drag and drop content I can't because I'm limited to the number of columns I define in the CSS.

**Comment by radiolips** [comment]
Hey, @Matthew-Bonner ! How could you have an unlimited number of columns? I'm not sure what you mean.

**Comment by mandys** [comment]
@Matthew-Bonner this is actually possible with a bit of extra work.
See: https://github.com/troolee/gridstack.js#change-grid-width

Gridstack by default uses 12 column grid, but you can you use the below snippet mentioned at the link above to create a 24,36,48...column grid so drag/drop placements are much better.

The below sass code might need some updating based on the new gridstack.css ( I tweaked it for my case and it works perfect for 48 column grid ).

If you dont know how to run sass locally, no issues, just try this link:
https://www.sassmeister.com/

Paste below snippet and see how it generates the css for it.
Now keep playing with it and get the new css and then either include as new css file after gridstack.css or just overwrite the ones in gridstack.css.

.grid-stack-item {

    $gridstack-columns: 12;

    @for $i from 1 through $gridstack-columns {
        &[data-gs-width='#{$i}'] { width: (100% / $gridstack-columns) * $i; }
        &[data-gs-x='#{$i}'] { left: (100% / $gridstack-columns) * $i; }
        &.grid-stack-item[data-gs-min-width='#{$i}'] { min-width: (100% / $gridstack-columns) * $i; }
        &.grid-stack-item[data-gs-max-width='#{$i}'] { max-width: (100% / $gridstack-columns) * $i; }
    }
}

**Comment by Matthew-Bonner** [comment]
The problem with that is I have to know in advance what resolution monitors will use the functionality on offer. I have a 4K monitor, have you ever tried gridstack in a 4k monitor with a grid designed to work in 1080?

**Comment by radiolips** [comment]
You can build the CSS to work for any number of columns. If you build it out for up to, say, 500 columns, you could then dynamically determine the number of columns to use by checking how much screen real estate you have access to in the client.
