### ISSUE TITLE
Need Help: nested Drop inside the widget

### ISSUE THREAD

**Issue by kingsgobi** [gridstack/gridstack.js#660]
![untitled-1](https://cloud.githubusercontent.com/assets/9959296/25887081/360eb7f8-357e-11e7-982d-48d6fff983bc.jpg)

is this nested droping option is possible?

**Comment by mandys** [comment]
Actually there is some code in gridstack.js wherein you can comment out fixcollisions function and then the above happens. But, the result is very buggy.

a) All have same z-index so whichever is dropped or created in the end, has a higher z-index ( and you can place that on top of others ). Can live with it.

b) Responsive layouts are messed up on mobile ( everything comes one below the other ).

Following this thread...

**Comment by mandys** [comment]
@radiolips @troolee could do with some help on this one.
I understand that what I am asking for might break the responsive layout, but here is the scenario.

You have some widgets in sidebar [ button, photo ]

You drag and drop the photo widget on stage ( grid ). 
Now, I would like to drag & drop the button widget on the photo. It's like a page builder.

The drag/drop needs to work in layers.

I tried commenting the fix collisions method and it worked to some extent.
Overlapping happens now, but there are only 2 options:

1. Either both overlap completely ( same x, y )
2. Or They overlap one below the other ( maybe in 80/20 ratio )

There is no other option. It's still snapping to either complete box or some portion of it.
What I would like is that wherever we drop the button on the image it stays there.

Where in the code can I find the calculations for this ? Can it be overwritten ?

Any other creative ways to handle this ?

**Comment by radiolips** [comment]
In some experimental (until I have time to get it working better) features of gridstack, you can drop a widget from one grid to another.
