### ISSUE TITLE
Grid with width higher than 50 cols make widgets overlap each other

### ISSUE THREAD

**Issue by fcoedno** [gridstack/gridstack.js#682]
I am changing the width of the grid dynamically by generating the necessary css styles in javascript. It works fine until a certain limit. When it reaches about 50 cols the widgets start overlapping each other.

Here it is the generated CSS for a grid with 52 cols:
`<style id="gridStyle">#gridBoard > .grid-stack-item[data-gs-width="1"]  { width: 1.9230769230769231%; }
#gridBoard > .grid-stack-item[data-gs-width="2"]  { width: 3.8461538461538463%; }
#gridBoard > .grid-stack-item[data-gs-width="3"]  { width: 5.769230769230769%; }
#gridBoard > .grid-stack-item[data-gs-width="4"]  { width: 7.6923076923076925%; }
#gridBoard > .grid-stack-item[data-gs-width="5"]  { width: 9.615384615384615%; }
#gridBoard > .grid-stack-item[data-gs-width="6"]  { width: 11.538461538461538%; }
#gridBoard > .grid-stack-item[data-gs-width="7"]  { width: 13.461538461538462%; }
#gridBoard > .grid-stack-item[data-gs-width="8"]  { width: 15.384615384615385%; }
#gridBoard > .grid-stack-item[data-gs-width="9"]  { width: 17.307692307692307%; }
#gridBoard > .grid-stack-item[data-gs-width="10"]  { width: 19.23076923076923%; }
#gridBoard > .grid-stack-item[data-gs-width="11"]  { width: 21.153846153846153%; }
#gridBoard > .grid-stack-item[data-gs-width="12"]  { width: 23.076923076923077%; }
#gridBoard > .grid-stack-item[data-gs-width="13"]  { width: 25%; }
#gridBoard > .grid-stack-item[data-gs-width="14"]  { width: 26.923076923076923%; }
#gridBoard > .grid-stack-item[data-gs-width="15"]  { width: 28.846153846153847%; }
#gridBoard > .grid-stack-item[data-gs-width="16"]  { width: 30.76923076923077%; }
#gridBoard > .grid-stack-item[data-gs-width="17"]  { width: 32.69230769230769%; }
#gridBoard > .grid-stack-item[data-gs-width="18"]  { width: 34.61538461538461%; }
#gridBoard > .grid-stack-item[data-gs-width="19"]  { width: 36.53846153846154%; }
#gridBoard > .grid-stack-item[data-gs-width="20"]  { width: 38.46153846153846%; }
#gridBoard > .grid-stack-item[data-gs-width="21"]  { width: 40.38461538461539%; }
#gridBoard > .grid-stack-item[data-gs-width="22"]  { width: 42.30769230769231%; }
#gridBoard > .grid-stack-item[data-gs-width="23"]  { width: 44.23076923076923%; }
#gridBoard > .grid-stack-item[data-gs-width="24"]  { width: 46.15384615384615%; }
#gridBoard > .grid-stack-item[data-gs-width="25"]  { width: 48.07692307692308%; }
#gridBoard > .grid-stack-item[data-gs-width="26"]  { width: 50%; }
#gridBoard > .grid-stack-item[data-gs-width="27"]  { width: 51.92307692307693%; }
#gridBoard > .grid-stack-item[data-gs-width="28"]  { width: 53.84615384615385%; }
#gridBoard > .grid-stack-item[data-gs-width="29"]  { width: 55.769230769230774%; }
#gridBoard > .grid-stack-item[data-gs-width="30"]  { width: 57.69230769230769%; }
#gridBoard > .grid-stack-item[data-gs-width="31"]  { width: 59.61538461538462%; }
#gridBoard > .grid-stack-item[data-gs-width="32"]  { width: 61.53846153846154%; }
#gridBoard > .grid-stack-item[data-gs-width="33"]  { width: 63.46153846153846%; }
#gridBoard > .grid-stack-item[data-gs-width="34"]  { width: 65.38461538461539%; }
#gridBoard > .grid-stack-item[data-gs-width="35"]  { width: 67.3076923076923%; }
#gridBoard > .grid-stack-item[data-gs-width="36"]  { width: 69.23076923076923%; }
#gridBoard > .grid-stack-item[data-gs-width="37"]  { width: 71.15384615384616%; }
#gridBoard > .grid-stack-item[data-gs-width="38"]  { width: 73.07692307692308%; }
#gridBoard > .grid-stack-item[data-gs-width="39"]  { width: 75%; }
#gridBoard > .grid-stack-item[data-gs-width="40"]  { width: 76.92307692307692%; }
#gridBoard > .grid-stack-item[data-gs-width="41"]  { width: 78.84615384615385%; }
#gridBoard > .grid-stack-item[data-gs-width="42"]  { width: 80.76923076923077%; }
#gridBoard > .grid-stack-item[data-gs-width="43"]  { width: 82.6923076923077%; }
#gridBoard > .grid-stack-item[data-gs-width="44"]  { width: 84.61538461538461%; }
#gridBoard > .grid-stack-item[data-gs-width="45"]  { width: 86.53846153846155%; }
#gridBoard > .grid-stack-item[data-gs-width="46"]  { width: 88.46153846153847%; }
#gridBoard > .grid-stack-item[data-gs-width="47"]  { width: 90.38461538461539%; }
#gridBoard > .grid-stack-item[data-gs-width="48"]  { width: 92.3076923076923%; }
#gridBoard > .grid-stack-item[data-gs-width="49"]  { width: 94.23076923076923%; }
#gridBoard > .grid-stack-item[data-gs-width="50"]  { width: 96.15384615384616%; }
#gridBoard > .grid-stack-item[data-gs-width="51"]  { width: 98.07692307692308%; }
#gridBoard > .grid-stack-item[data-gs-width="52"]  { width: 100%; }
#gridBoard > .grid-stack-item[data-gs-x="1"]  { left: 1.9230769230769231%; }
#gridBoard > .grid-stack-item[data-gs-x="2"]  { left: 3.8461538461538463%; }
#gridBoard > .grid-stack-item[data-gs-x="3"]  { left: 5.769230769230769%; }
#gridBoard > .grid-stack-item[data-gs-x="4"]  { left: 7.6923076923076925%; }
#gridBoard > .grid-stack-item[data-gs-x="5"]  { left: 9.615384615384615%; }
#gridBoard > .grid-stack-item[data-gs-x="6"]  { left: 11.538461538461538%; }
#gridBoard > .grid-stack-item[data-gs-x="7"]  { left: 13.461538461538462%; }
#gridBoard > .grid-stack-item[data-gs-x="8"]  { left: 15.384615384615385%; }
#gridBoard > .grid-stack-item[data-gs-x="9"]  { left: 17.307692307692307%; }
#gridBoard > .grid-stack-item[data-gs-x="10"]  { left: 19.23076923076923%; }
#gridBoard > .grid-stack-item[data-gs-x="11"]  { left: 21.153846153846153%; }
#gridBoard > .grid-stack-item[data-gs-x="12"]  { left: 23.076923076923077%; }
#gridBoard > .grid-stack-item[data-gs-x="13"]  { left: 25%; }
#gridBoard > .grid-stack-item[data-gs-x="14"]  { left: 26.923076923076923%; }
#gridBoard > .grid-stack-item[data-gs-x="15"]  { left: 28.846153846153847%; }
#gridBoard > .grid-stack-item[data-gs-x="16"]  { left: 30.76923076923077%; }
#gridBoard > .grid-stack-item[data-gs-x="17"]  { left: 32.69230769230769%; }
#gridBoard > .grid-stack-item[data-gs-x="18"]  { left: 34.61538461538461%; }
#gridBoard > .grid-stack-item[data-gs-x="19"]  { left: 36.53846153846154%; }
#gridBoard > .grid-stack-item[data-gs-x="20"]  { left: 38.46153846153846%; }
#gridBoard > .grid-stack-item[data-gs-x="21"]  { left: 40.38461538461539%; }
#gridBoard > .grid-stack-item[data-gs-x="22"]  { left: 42.30769230769231%; }
#gridBoard > .grid-stack-item[data-gs-x="23"]  { left: 44.23076923076923%; }
#gridBoard > .grid-stack-item[data-gs-x="24"]  { left: 46.15384615384615%; }
#gridBoard > .grid-stack-item[data-gs-x="25"]  { left: 48.07692307692308%; }
#gridBoard > .grid-stack-item[data-gs-x="26"]  { left: 50%; }
#gridBoard > .grid-stack-item[data-gs-x="27"]  { left: 51.92307692307693%; }
#gridBoard > .grid-stack-item[data-gs-x="28"]  { left: 53.84615384615385%; }
#gridBoard > .grid-stack-item[data-gs-x="29"]  { left: 55.769230769230774%; }
#gridBoard > .grid-stack-item[data-gs-x="30"]  { left: 57.69230769230769%; }
#gridBoard > .grid-stack-item[data-gs-x="31"]  { left: 59.61538461538462%; }
#gridBoard > .grid-stack-item[data-gs-x="32"]  { left: 61.53846153846154%; }
#gridBoard > .grid-stack-item[data-gs-x="33"]  { left: 63.46153846153846%; }
#gridBoard > .grid-stack-item[data-gs-x="34"]  { left: 65.38461538461539%; }
#gridBoard > .grid-stack-item[data-gs-x="35"]  { left: 67.3076923076923%; }
#gridBoard > .grid-stack-item[data-gs-x="36"]  { left: 69.23076923076923%; }
#gridBoard > .grid-stack-item[data-gs-x="37"]  { left: 71.15384615384616%; }
#gridBoard > .grid-stack-item[data-gs-x="38"]  { left: 73.07692307692308%; }
#gridBoard > .grid-stack-item[data-gs-x="39"]  { left: 75%; }
#gridBoard > .grid-stack-item[data-gs-x="40"]  { left: 76.92307692307692%; }
#gridBoard > .grid-stack-item[data-gs-x="41"]  { left: 78.84615384615385%; }
#gridBoard > .grid-stack-item[data-gs-x="42"]  { left: 80.76923076923077%; }
#gridBoard > .grid-stack-item[data-gs-x="43"]  { left: 82.6923076923077%; }
#gridBoard > .grid-stack-item[data-gs-x="44"]  { left: 84.61538461538461%; }
#gridBoard > .grid-stack-item[data-gs-x="45"]  { left: 86.53846153846155%; }
#gridBoard > .grid-stack-item[data-gs-x="46"]  { left: 88.46153846153847%; }
#gridBoard > .grid-stack-item[data-gs-x="47"]  { left: 90.38461538461539%; }
#gridBoard > .grid-stack-item[data-gs-x="48"]  { left: 92.3076923076923%; }
#gridBoard > .grid-stack-item[data-gs-x="49"]  { left: 94.23076923076923%; }
#gridBoard > .grid-stack-item[data-gs-x="50"]  { left: 96.15384615384616%; }
#gridBoard > .grid-stack-item[data-gs-x="51"]  { left: 98.07692307692308%; }
</style>`

## The grid with 48 cols

![non-overlapping](https://cloud.githubusercontent.com/assets/6249736/26833232/46796266-4aa8-11e7-8405-071414044297.png)

## The grid with 52 cols

![overlapping](https://cloud.githubusercontent.com/assets/6249736/26833243/4cbce83c-4aa8-11e7-930a-82a82ea8a226.png)

**Comment by radiolips** [comment]
Without looking into the problem, my guess is that this is a mathematical issue. `gridstack` CSS is set in percentages. If you work out the numbers, my guess is that it's not feasible to get to that size. With a wider container, are you able to have 52 columns that don't overlap?

**Comment by fcoedno** [comment]
The container (scrollable) also grows in width based on the number of widgets in parallalel. So i don't think that's the problem. 

The first example that i showed, i had widgets of 4 cols (fixed). With 48 cols (12 widgets) everything worked fine, and started overlap on the 13th widget. But, i tested again with widgets of 3 cols, the widgets started overlap again in the 12->13 widgets limit. 

That means, this time with a grid of width 39 (13 widgets) they started overlap. With widgets of fixed 4 cols, the magic number was 48 cols for the grid width.

So i believe that the actual problem is that more than 12 widgets in parallel, they start overlap each other.

**Comment by fcoedno** [comment]
Just some more info about this problem. As said before, i am increasing the size of the container, depending on the grid width.

Let's say that i have widgets of 2, 3 and 4 cols.

If i set the *width of the grid* higher than 24 all widgets of 2 cols start to overlap (their width grows). when i set the *width of the grid* for a number higher than 36 cols all widgets of 3 cols start to overlap (ther width grows) and so on.

Obs.: As the width of the container grows, the resolution of the percentages keep constant. The code to change the container width and set the css rules:

    function setRules(cols)
	{
		if (cols < 12)
			cols = 12;

		var width = $('#board').width();
		var percentage = cols/12;
		var gridBoardWidth = width * percentage;

		$('#gridBoard').width( gridBoardWidth );

		// var unit = (gridBoardWidth/cols);
		var unit = (100/cols);

		var styleWidth = '';
		var stylePos = '';

		for ( i = 0; i < cols; i++ )
		{
			styleWidth += '#gridBoard > .grid-stack-item[data-gs-width="'+ (i + 1) + '"]  { width: ' + ( (i + 1) * unit) + '%; }\n';
		}

		for ( i = 0; i < cols - 1; i++ )
		{
			stylePos += '#gridBoard > .grid-stack-item[data-gs-x="' + (i + 1) + '"]  { left: ' + ((i+1)*unit) + '%; }\n';
		}

		var style = styleWidth + stylePos;

		$('#gridStyle').text(style);
	}

And the HTML

			<div class="panel-body" id="board">
				<div class="grid-stack" id='gridBoard'>
				</div>
			</div>

The style element

    <style id="gridStyle">
    </style>

**Comment by fcoedno** [comment]
Just found out the problem. in the gridstack css files the min width i set to a percentage higher than the one necessary to acomplish the grid width i wanted. By now, i simply overrided this option in my own css file (set to 0).

Also, in the scss source file, this property is set to:

`$gridstack-columns: 12 !default;`

...

`min-width: 100% / $gridstack-columns;`

**Comment by radiolips** [comment]
I'm closing this. You can override SCSS and set it to whatever you'd like when you're using more columns. That should work for you (and it looks like it has).
