### ISSUE TITLE
Bugs Two Grids

### ISSUE THREAD

**Issue by trevisanweb** [gridstack/gridstack.js#696]
Hi, when you move an element from `#grid2` to `#grid1`, it does not scale any more. Another bug is when you quickly throw one element into the other grid-stack.

![bugs](https://user-images.githubusercontent.com/3501138/27304714-56d63004-5515-11e7-8ef6-c1a1ab771e2a.gif)

**Comment by radiolips** [comment]
@trevisanweb Hey there. I've noticed this bug but haven't had the chance to look into it. And you're working on the latest dev version, right? I see you have some commits - do they fix these bugs?

**Comment by radiolips** [comment]
I'm referencing #695 here also.

**Comment by radiolips** [comment]
This is fixed in released v0.4.0
