### ISSUE TITLE
Locked items can sometimes move

### ISSUE THREAD

**Issue by drgnlrds** [gridstack/gridstack.js#698]
Using the demo at: http://troolee.github.io/gridstack.js/demo/two.html

In a dev console run the following to lock all the items: 

`$(".grid-stack").each(function (idx, gsEl) { $(gsEl).data("gridstack").locked(".grid-stack-item", true);});`

Drag an item from the left grid over the top left item in the right grid.  You will see that it will push it down even though it should be locked.

**Comment by andrewhinde** [comment]
I've come across this issue as well.  A locked grid item can be moved if a moveable item is dragged above it.

**Comment by radiolips** [comment]
Two grids is the bane of my existence. It's so fun but adds so many complications. I'll take a look, thansk @drgnlrds and @andrewhinde .

**Comment by radiolips** [comment]
This is fixed in v1.0.0-dev in the `develop` branch.
