### ISSUE TITLE
Removed Widgets Reappear when browser narrows to single column

### ISSUE THREAD

**Issue by ImTheKeyMaster** [gridstack/gridstack.js#702]
Hi,
Awesome library!!! 

I'm looking for some advise.  I'm creating the grid-stack and items via a partialview in a .NET MVC project.  So, the items are not added dynamically.

I can successfully remove an item using the remove_widget() and it disappears from the DOM.  But, if I resize the browser so Bootstrap shifts to single column mode, the widget reappears (but as the last item).

I've also used jQuery to remove the item, but the same thing happens when the browser is resized.  

Any advise?  I'm hoping the answer isn't to add all the widgets via JavaScript.

Thanks in advance.

**Comment by radiolips** [comment]
Hey there, @ImTheKeyMaster ! Your issue is very strange. Could you provide a jsfiddle?

Also, I'd highly recommend using `removeWidget` rather than `remove_widget`, as the underscored functions will be removed in version 1.
