### ISSUE TITLE
how to save database data with knockout.js ?

### ISSUE THREAD

**Issue by 123Rofiq** [gridstack/gridstack.js#707]
i will save data like http://troolee.github.io/gridstack.js/demo/knockout.html in database?
any can help me?
thanks
![boxku](https://user-images.githubusercontent.com/5044384/27948901-b4f2294a-6325-11e7-9938-f0f673b5e01d.png)

**Comment by radiolips** [comment]
@123Rofiq Which part specifically do you need help with? Essentially, what you need to do is grab the widgets and send their x, y, width, and height to a database (in addition to their content).
