### ISSUE TITLE
Facing the issue in the Height while loading the chart widget dynamically inside the layout 

### ISSUE THREAD

**Issue by Pinthiya** [gridstack/gridstack.js#708]
Hi,

I have been working the gridstack using angular2. 

In the application, i set dynamic value for the position(data-gs-x, data-gs-y, data-gs-width, data-gs-height) as well as content(inside the layout). 
Here I faced the issue as before loading the data-gs-height value, container was loaded. so i got the container height value as "0px". 
For the above issue, I applied some conditions as, after loading the data-gs-height, "GridStack.prototype._updateContainerHeight" function will be loaded.

Now the first issue works fine, again am facing the another issue - I have been loaded some charts inside the cells, each chart having some default height and width(if the height and width is not given, canvas default height and width would be set).
 Reason of this issue is:
once loading the data-gs-height, chart component is loaded. In the chart component, height of the  parent component is '0'. so it takes default height and weight value.
please look into this.

Thank You in Advance

**Comment by radiolips** [comment]
Hi there, @Pinthiya ! Happy to help you out.

Could you provide a jsfiddle for me to take a look? I believe we can figure out a way to fix your problem.
