### ISSUE TITLE
Integrating collapsible and closable panels in Gridstack dashboard

### ISSUE THREAD

**Issue by AlamBique** [gridstack/gridstack.js#711]
Using the projects:

1-gridstack [LinkForGridstack.js](troolee.github.io/gridstack.js/)

2-Creating Collapsible Bootstrap Panels with jQuery [LinkForTutorialExample](www.jqueryscript.net/layout/Creating-Collapsible-Bootstrap-Panels-with-jQuery.html)

I'm trying to create a dashboard. Here is a simplified demo of what I was able to do:
[CodePen_Demo](https://codepen.io/AlamBique/pen/eRQGOm)

**The problem is that I'm controlling the panel inside the grid-stack-item, but not the grid-stack-item.** Because of this, when the panel collapses the grid-stack-item does not resize ... and when I close the panel the grid-stack-item remains open ... I am initiane in web development. I need a help to make it work as a dashboard with fact widgets.

![exemplo](https://user-images.githubusercontent.com/30054826/28032936-a9c8dbe0-6582-11e7-81e5-4e397deea162.png)

**Comment by radiolips** [comment]
Hey there, @AlamBique ! I'd be happy to help you.

What you're trying to do is actually a little tricky. You can create a listener to resize the widget's height, but it won't get the animation. Will that work for you?

**Comment by AlamBique** [comment]
Of course it will work. When I started with my project, I did not know anything about javascript or jquery. I ended up giving it up. But if it works it would be great.

**Comment by radiolips** [comment]
Are you going to try again? If so, I can try to help you. If not, I'll close the ticket.

**Comment by gentle9** [comment]
I am trying to do the same thing. I have tried to do a resize on the component to the min height so it is collapsed and this seems to work. But when I want to open the collapsed panel and resize it to the real size and there is a panel right under the collapsed panel they change the position so that the panel that was under the collapsed is now above.
