### ISSUE TITLE
Widgets squeezing instead of shifting them down to another row 

### ISSUE THREAD

**Issue by shani759** [gridstack/gridstack.js#714]
Hi @troolee,,
I am new to gridstack, and it is a fun library. I came across an issue that i need to address and maybe someone can provide best approach to do that.
Currently when you increase the size of a widget then other widgets in same row gets shift down, what if instead of shifting down you need to keep them in same row and gets shrink until their min width gets hit ??
Any suggestions would be great!

**Comment by shani759** [comment]
Hi @troolee,
I kind of a able to get the desired behavior (stop widget from moving down on resize) using **locked** property. But method exposed by API is not working properly so i have to set **locked: true** in **gridstack.js** file.
After doing that resize is not behaving properly, i.e. If i resized a widget towards another widget (provided there is free place to resize) it came back to its original place.

**Comment by radiolips** [comment]
@shani759 Thanks. Could you provide a jsfiddle? I'm not sure what you mean when you say that `locked` isn't working - if you could provide a fiddle I could take a look. Thanks!
