### ISSUE TITLE
Gridstack is not working in marionette

### ISSUE THREAD

**Issue by aviralgarg0996** [gridstack/gridstack.js#715]
I use Gridstack in simple javascript code it is working fine but when i use the same in marionette.js it is not working.Please suggest me a solution for this.if code is required then i use  https://jsfiddle.net/wmLk2ey7/7/ this,It is working fine but when i am transforming this same to marionette it is not working .
Draggable & resizable functions are not working & it is not showing any error.

**Comment by radiolips** [comment]
@aviralgarg0996 Could you please provide a jsfiddle where you're using marionette? gridstack should work fine alongside marionette.
