### ISSUE TITLE
Float Grid Items to Stick to Positions

### ISSUE THREAD

**Issue by gokhancs** [gridstack/gridstack.js#716]
Hi,

I am using gridstack layout on a large display system (~8x2meters, 15120x3840pixels). Therefore I can have hundreds of containers as gridstack items on my display at the same time. My use cases include moving items in the free space, create floating groups of items on my visual analytics software. My problem with gridstack is the following:

Say, I have 25 containers in the middle of the screen that is grouped as a 5x5 square. I have ungrouped containers (gridstack items) in the top left corner, and using them, I want to create another group in the bottom right corner by dragging them there. When I click on the mouse and drag them over the middle of the screen, they interact with the existing group of items and break their locations as they are being carried, even if they are not dropped to those locations. Those locations do not restore. That is, the dragged containers change the positions of others as they are being carried, even if they are not taking up their place. It would be totally ok that the items slide in case their positions are claimed by new ones that we are dragging; but I am expecting them to return to their positions if the action is not completed and the mouse button is not released yet. 

Is it possible to fix that? I would've loved that the items remember their locations and return to original positions if it is not filled with other items that has been dragged there. While dragging, only the dragged item and the ones that the dragged item will replace with should move from their positions. Otherwise, the placements are ruined and all the items need to be organized again, which in my case, happens for tens of times and each time it requires adjusting positions of tens of containers over and over again. 

Anyone experiencing a similar problem? Is there a solution?     
Thank you very much!

**Comment by nolanvance** [comment]
Hey Gokhancs,

I have seen/tried a couple of options. First thing I tried was to add the 'data-gs-no-move="true"' to my widgets on "dragstart" and removing it on"dragstop". Unfortunately this has not worked for me but I would recommend trying it yourself. I also tried using grid.movable(el, isMoveable) on dragstart but this does not seem to fire until after I am done dragging, which is confusing.. I am still trying to figure that out on my end. Let me know if anything works for you.

https://github.com/troolee/gridstack.js/tree/develop/doc#item-attributes
https://github.com/troolee/gridstack.js/tree/develop/doc#dragstartevent-ui

**Comment by kool-kat** [comment]
+1 for a solution to this. I agree widgets should move aside on collision but equally should resume original position if the items being dragged and dropped are no longer colliding or threatening their space/position.

**Comment by radiolips** [comment]
I don't know that this is intuitive. As you drag the widget, the other widgets are being interacted with. @gokhancs could you be more succinct about your problem, or is @kool-kat correct in what the issue is? You want to be able to move  widgets, but you don't want the tangential widgets to persist in their affected location unless necessary?

**Comment by kool-kat** [comment]
@radiolips Best way I can explain it is as follows:

Dragging a widget is a **mouse click and hold** event.

In the process of dragging/moving the widget being dragged may collide or intersect with space occupied by other widgets. This results in a **collision event**.

The widgets touched/intersected with now move and release the space they are occupying to make room for the widget being moved through it's space. 

For widget groups affected (collided with) as @gokhanc highlighted in his post, this can result in multiple widget elements within the group moving out of the way of the dragged object.

This "move out-a-way" behaviour in my opinion is fine... BUT ...

As the dragging continues the widget leaves the boundaries and space of those 'moved' widgets ... and continues on.. (mouse button still holding not released) 

The widgets collided with (those who moved out-of-our-way) should now resume their original position and arrangement on screen (the position they held before the collision event happened) once we have moved out of the original boundary area.

Only on mouse button release should the location of the dropped/released widget permanently affect the position of any widgets below or collided with.

Does that make sense.

In the current form, all layout groups and positions previously set are lost if you happen to move another widget through its space/boundary. MOVE THROUGH being a keyword...

**Comment by gokhancs** [comment]
@kool-kat is right, great description. Following the same wording, I am fine with containers interacting with each other in case of a collision as the dragged item moves through the other containers while the mouse is pressed but not released. So "moving out of way" is intuitive, and I have no problem with that. 

The problem is that, it is also intuitive to expect that those interacted containers should come back to their original position and arrangement once "we have moved out of the original boundary area (aka collision zone)" without dropping the dragged item. In other words, if the collision starts with dragging (and not dropping) and it ends after the dragged item goes away without requiring the group of containers "move away to create space", then they should get back to their positions before the interaction started by dragging (and not permanently dropping).

As a better explanation, the previous response by @kool-kat still works better in my opinion, as I am not a native speaker of English :) Thanks,

**Comment by kool-kat** [comment]
On triggering a collision (**on start collision**) gridstack needs to: 1] capture and memorise the boundary area of the element collided with (either single widget or widget group), 2] the order and sequence of each element within the parent boundary and 3] the XY position of each element... so that:

**On exit collision** (with no drop) the elements moved can be returned to their original position/s.

P.S @gokhancs you did well explaining, credit to you when english not your native tongue.

**Comment by adumesny** [comment]
I think the implementation simply needs to save the initial state on drag start to the side, and on every moves checks for collision against **that** saved state for a temporary one (not used until released). This way if user pressed say Esc to cancel a move (do we even support that ?) or drops it outside, the initial state is restored properly.

In my app I have a widget maximize feature that makes anyone of them take entire screen 912 columns and n rows) then restore it back by saving the original grid. It would be similar...

**Comment by adumesny** [comment]
@gokhancs the current release works as you describe - https://gridstackjs.com/demo/float.html
create a bunch of items in the middle, then drag a corner item through the center pile and see them displace but get back to original position as you drag through.
