### ISSUE TITLE
Nested gridstack height (Like content)

### ISSUE THREAD

**Issue by anonimo9** [gridstack/gridstack.js#717]
Hi,

Is it possible that .grid-stack-item that has inside .grid-stack would be same height as content ?
Because now the .grid-stack-item has scroll. I was search all internet, don't find any solution for this.

![nested](https://user-images.githubusercontent.com/13675696/28251135-8a0c706c-6a7f-11e7-93db-0bc0f8304946.png)

**Comment by kool-kat** [comment]
Saw this myself. Nested grid should ideally inherit the 'wrapping' parent grid element cell width and height and as such fit perfectly.

Scroll bars shouldn't appear but they do. On my grid when first loaded/initialised there are no vertical scroll bars visible on the nested grid, but as soon as I hover over or move any parent grid elements they appear and then sometimes remain on screen even though grid space is effectively unchanged.

They also appear on hover over the nested grid, if elements have resize=true. It flickers/on and off as the resize icons show. Again the size is unchanged.

**INIT/load GRID** (no scrollbars):

(Inner 1-4) is the nested 2x2 grid which occupies Columns 3-6 and Rows 3-9 of the parent 8x9 outer grid.

![image](https://user-images.githubusercontent.com/30038525/28656030-e7986c8e-72e2-11e7-93d8-0dbc9297cac3.png)

**HOVER OVER NESTED**

Hover over any element in the bottom row of the nested grid (Inner 3 or Inner 4) results in vertical scrollbar (image below:)
![image](https://user-images.githubusercontent.com/30038525/28656246-1f6c8e8c-72e4-11e7-9a4d-d09f66332c43.png)

In screenshot: Scroll SE/SW icons are visible on Inner 3 element which I had my mouse cursor over. Also SE cursor for parent grid element showing as it contains the nested grid object and hover event has passed through to the underlying layer too. NOTE: on mouse-off the vertical scrolls disappear.

**Comment by adumesny** [comment]
same idea as 
#787[ support for nested grid to take entire parent height (simulate % rows, like columns do) ](#787)

**Comment by adumesny** [comment]
closing as 787 has more info
