### ISSUE TITLE
Add tolerance parameter for droppable div

### ISSUE THREAD

**Issue by OutOfNutella** [gridstack/gridstack.js#719]
According to jQuery UI, you can add specifics tolerances on the droppable div
For example, tolerance pointer allows the user to drop any item on specific zone only if the mouse points inside the droppable div
Source: http://api.jqueryui.com/droppable/

You can see an example i've created on codepen: https://codepen.io/OutOfNutella/pen/QgRByB

So I tried to do this with gridstack, by updating the source code to test it, and it worked perfectly.
Is there a way someone can implement it ?

I'm not really used to fork and pull request to add fonctionnality, so i'm just asking if you can do this :)

Here's the code i updated to make it work

Add somewhere in the options in gridstack.js the default option value of tolerance
https://github.com/troolee/gridstack.js/blob/develop/src/gridstack.js#L605
```
tolerance: "intersect",
```

Use this option in gridstack.jQueryUI.js
https://github.com/troolee/gridstack.js/blob/develop/src/gridstack.jQueryUI.js#L84 
```
el.droppable({
     tolerance: opts.tolerance,
     accept: opts.accept
});
```

Now, in your gridstack config, overwrite the tolerance option with what you want
```
gridstackOptions = {
    float: true,
    removable: '.trash',
    tolerance: 'pointer',
    removeTimeout: 100,
    resizable: {
        handles: 'e, se, s, sw, w'
    }
}
```

**Comment by radiolips** [comment]
This is resolved in v1.0 via the PR merged and referenced in this ticket.
