### ISSUE TITLE
Containment cannot be set

### ISSUE THREAD

**Issue by ZoolWay** [gridstack/gridstack.js#720]
Is is not possible to limit move/size operations with the jQuery-UI plugin with the `containment` setting. Also there is the option `draggable` to override jQuery-UI parameters for this it will ignore the parameter `containment`. If you look at issue #695 or [gridstack.jQueryUI.js:69](https://github.com/troolee/gridstack.js/blob/develop/src/gridstack.jQueryUI.js#L69) you can see that containment is set by GridStack nevertheless.

I tried changing it to
```
containment: this.grid.opts.isNested ? this.grid.container.parent() : (this.grid.opts.draggable || null),
```
to let it override whenever possible. In theory this works, in praxis this leads to a bunch of other problems when it utilizes jQuery.

An example what I am trying to achieve can be seen here:
https://jqueryui.com/draggable/#constrain-movement

At the moment whenever I drag an element outside of the grid things just go crazy, items get moved anywhere.

**Comment by aureality** [comment]
I was looking for exactly the same Zoolway.
But it seems you made a mistake in your replacement. it should read 
containment: this.grid.opts.isNested ? this.grid.container.parent() : (this.grid.opts.draggable.containment || null),

If I do that, the containment works!

**Comment by adumesny** [comment]
thank you @aureality @ZoolWay for supplying this code! this lib would not be possible without community help. fix is in next release...
