### ISSUE TITLE
widget jumps up on drag start when page is scrolled

### ISSUE THREAD

**Issue by garthgoodson** [gridstack/gridstack.js#721]
I have a container that is taller than the page.  If I have a set of 3 tallish widgets stacked on top of each other (~height of 5) and partially scroll down the page so that the middle widget is fully on the page, but the top and bottom widgets are slightly off of the page and then grab that middle widget it will immediately jump up above the widget above it.  It looks like the scroll position may not be taken into account and it detects a collision with the widget above, which causes the widget above to become shifted down and the one I just grabbed to be moved up.  I have no problems if the page is not scrolled.

Occurs on 0.2.7 and 0.3.0.

**Comment by garthgoodson** [comment]
It may be related to a jquery ui bug:
https://stackoverflow.com/questions/5791886/jquery-draggable-shows-helper-in-wrong-place-after-page-scrolled
I'm using latest jquery-ui 1.12.1.  Position absolute is set and I've tried making parent overflow auto.

**Comment by nolanvance** [comment]
I was having a similar issue except when items were more than 10 rows apart. I fixed by updating this line in gridstack.js `self._updateStyles(maxHeight + 10)` to `self._updateStyles(maxHeight + 20)`. It was only generating the CSS for items within 10 units of the selected item.

**Comment by andrewgunn** [comment]
I was having the same issue so tried @nolanvance's fix and it did the trick. I imagine it'll break again at some point - maybe if I keep adding widgets to increase the vertical scrollbar!?

**Comment by radiolips** [comment]
Could someone put together a fiddle for this?
