### ISSUE TITLE
horizontalMargin option to match verticalMargin we have today

### ISSUE THREAD

**Issue by kool-kat** [gridstack/gridstack.js#723]
Hoping this is an easy one.

Reading the api docs I see a parameter **verticalMargin**.

Setting this to zero removes the vertical 'Y-axis' gaps between grid items but horizontal gaps remain.

I did a quick scan through all parameters etc but couldn't locate an option to drop margins on x-axis.

Pointers please.

**Comment by kool-kat** [comment]
Update:

Manually changing the LEFT and RIGHT values for the CSS classes:

```
.grid-stack .grid-stack-placeholder > .placeholder-content
.grid-stack > .grid-stack-item > .grid-stack-item-content
```

Allows for some changes in horizontal guttering between grid items but not as easy to change as with function options.

Also the visual result is different as the gutters are applied differently. Vertical margin doesn't apply any gutter at bottom or top of grid, but the classes create insert gaps at left and right of grid.

**Comment by kool-kat** [comment]
Would be great to have the gutter/margins between grid elements on X and y-axis styled and applied the same way. 

Add horizMargin parameter please and apply the margins on inside of the grid (like you did with verticalMargin). We can set grid left, top, bottom and right margins as we need in CSS. 

Thx

**Comment by adumesny** [comment]
I too find it weird we only have **verticalMargin**. I will soon need **horizontalMargin** (to set both to 0 or 1px for tight layout parent grids (inside more roomy grids)).

**Comment by radiolips** [comment]
@adumesny @kool-kat I'll add `horizontalMargin` to the list of features to add. I recall there being a reason why we didn't implement it, but for now consider it planned!

**Comment by adumesny** [comment]
maybe it should be a single **margin** field to control them both (not sure why you would want one but not the other... for now I'm able to control horizontal margin using CSS (while vertical is in code!)

**Comment by steacktartar** [comment]
In my case, simply including a left:0px in the grid-stack-item-content div element did the trick.
    
```
<div class="grid-stack-item" id="grid6" width="300" height="300" data-gs-x="9" data-gs-y="4" data-gs-width="3" data-gs-height="4">
            <div class="grid-stack-item-content" id="events" width="300" height="300" style="border-width:1px; border-style:solid dotted;left:0px"></div>
</div>
```

**Comment by ataft** [comment]
Setting the `grid-stack-item-content` css to `left:0` makes the resize handle appear 10px inside the left box. It seems like this logic needs to be fixed in the code base for all things to work properly together...

**Comment by geopamplona** [comment]
> horizontalMargin 
Is this parameter not yet added?
How could I achieve similar functionality?
Thank you

**Comment by otionstem** [comment]
.grid-stack .grid-stack-placeholder > .placeholder-content {
  left: 2px;
  right: 2px;
}
.grid-stack > .grid-stack-item > .grid-stack-item-content {
  left: 2px;
  right: 2px;
}

**Comment by crapthings** [comment]
i don't have horizontalMargin by default? what's wrong?

![image](https://user-images.githubusercontent.com/1147704/66886312-80ee8d00-f009-11e9-9a3d-b4582981b016.png)

**Comment by david-offord** [comment]
@crapthings I think one solution is to set this css:

.grid-stack > .grid-stack-item > .grid-stack-item-content {
    left: 4px !important;
    right: 4px !important;
}
 This can also be used to change the space between 2 items horizontally.

**Comment by adumesny** [comment]
now that I'm familiar with the code base I see why there isn't a `horizontalMargin` param like `verticalMargin`. The widths are all done in CSS as 100 / # column for each with inside padding done in CSS as well, whereas vertical position are pixels in code (cellHeight + verticalMargin).

that said there is no reason we can't have a param and set the CSS rule, and exclude the first and last end point from having that padding, or modify vertical to have padding on both ends to match.

not a trivial fix to fix all the logic as well...

**Comment by ataft** [comment]
Has anyone found a workaround for this yet? 

@otionstem's solution will show the horizontal resize handles in the wrong place.

**Comment by killjoy99nz** [comment]
I'm looking for an elegant solution to this, too. Just starting implementing gridStack and this is the first issue I've run into.

**Comment by susilon** [comment]
> 
> 
> ```
> .grid-stack .grid-stack-placeholder > .placeholder-content {
>   left: 2px;
>   right: 2px;
> }
> .grid-stack > .grid-stack-item > .grid-stack-item-content {
>   left: 2px;
>   right: 2px;
> }
> ```

Added this too
.grid-stack > .grid-stack-item > .ui-resizable-e {      
    &nbsp;&nbsp;right: 2px !important;
  }
  .grid-stack > .grid-stack-item > .ui-resizable-w {      
    &nbsp;&nbsp;left: 2px !important;
  }

**Comment by killjoy99nz** [comment]
Thanks for that. With those style changes, it's looking much better.

**Comment by ataft** [comment]
Thanks @susilon. I thought I had tried this and ran into problems, but the solution looks good to me.

Depending on your resizable handles, you may need to include more than just east and west. I had to do the following within .grid-stack-item:
```
.ui-resizable-e, .ui-resizable-se, .ui-resizable-ne {
    right: 3px !important;
}
.ui-resizable-w, .ui-resizable-sw, .ui-resizable-nw {
    left: 3px !important;
}

```

**Comment by adumesny** [comment]
this will be fixed in upcoming 2.0 release - as you can see parent grid has 10px margin (default), nested 1px using just the new `margin` grid option (no external CSS needed) and takes care of resize handles as well.

![image](https://user-images.githubusercontent.com/3496166/86782930-8915af00-c014-11ea-99e6-185471e9275d.png)

**Comment by husseinterek** [comment]
@adumesny how can I use the margin attribute in gridstack.all.js (V.1.1.2)?
Can you share any file or I have to wait for V.2.0 ?

**Comment by adumesny** [comment]
sorry, you will have to wait for 2.x as it was a bit of code change and not back porting to 1.x

**Comment by husseinterek** [comment]
Thanks @adumesny for the quick reply.
When can we expect the version 2.x? 
And do you have any workarround for the horizontal margin on version 1.x?
