### ISSUE TITLE
Non movable items can be moved by other items

### ISSUE THREAD

**Issue by TheoZaff** [gridstack/gridstack.js#725]
Hello,
I have 2 different type of widgets. They both are `locked` and one also has `movable: false`. But, my non movable items can actually be moved by my movable items when I'm dragging a movable item above a non movable item for example. Sometimes the non movable item even gets deleted. I've tried to set `auto-position` to false without any success.
Did I miss something or is that a bug?

Thank you

**Comment by nolanvance** [comment]
I am having this exact issue as well seems to be a bug ( #698 )

**Comment by TheoZaff** [comment]
The only difference between our issues is that you are using two grid and I'm using only one grid.

**Comment by JohnWSeeker** [comment]
I have same issue about it. Widget_A (locked: true) can be changed location by others widget hover it.

**Comment by torrao** [comment]
@TheoZaff @JohnWSeeker @nolanvance ,

if you put your _non movable widgtes_ as `data-gs-locked`, `data-gs-no-move`and `data-gs-no-resize`, they cannot be displaced by other moving widgets.

Hope it helps!

**Comment by otakueadwine** [comment]
Same issue here. Widget A keeps correct position until Widget B is completely dragged over Widget A.

**Comment by fabianvelizok** [comment]
We have a fixed item (button) on the first place, so we use the following workaround:
onDragStop event, compare fixed item position (0, 0) with new item position (0...X, 0...Y) and if they are the same, then return new item to original position (look at the properties).
I hope it could be helpful :)

**Comment by radiolips** [comment]
Closing this in favor of #698 . It's a separate grid, but I believe it's the same problem.
