### ISSUE TITLE
How to create more than one gridstack use knockout?

### ISSUE THREAD

**Issue by tanobi92** [gridstack/gridstack.js#727]
I tried to register two ko component different. But it fail. Error: "Uncaught ReferenceError: Unable to process binding "click: function (){return addNewWidget1 }"
Message: addNewWidget1 is not defined"
My demo: https://codepen.io/TaNoBi/pen/dzPweY
Help me, please! Thank you!

**Comment by radiolips** [comment]
@tanobi92 You might want to try our Slack community to see if anyone can help. I don't write any KO myself, so I won't be a good resource for you here.

**Comment by radiolips** [comment]
I'm also closing this, as it isn't actually an issue at this time, but let me know if there is a specific issue (vs just question).
