### ISSUE TITLE
peerDependencies instead of dependencies

### ISSUE THREAD

**Issue by derwaldgeist** [gridstack/gridstack.js#738]
Would it be possible to change this library to use peerDependencies instead of fixed dependencies? In some build environments, dependencies will cause the libraries to be loaded more than once, if you already use them in your other code.

**Comment by radiolips** [comment]
Thanks, @derwaldgeist . I'll take a look. We should be able to make the adjustment.

**Comment by radiolips** [comment]
Closing this now, because npm 3+ won't install the dependencies.

**Comment by adumesny** [comment]
couldn't you use the yarn "resolutions":  section to specify a single version of a lib to use across all (assuming the range of each dependent match) and have just 1 copy ?
