### ISSUE TITLE
Increase width of widget

### ISSUE THREAD

**Issue by Ghumwala** [gridstack/gridstack.js#741]
How do I increase width of widget? I have used below code
if (grid == null) {
                          grid = $(componentInfo.element).find('.grid-stack').gridstack({
                                width:12,
                                auto: false,
                                float: true
                            }).data('gridstack');
}

When I inspect in browser, data-gs-width="2" is set instead of data-gs-width="12" . Can anyone please help me out.

**Comment by radiolips** [comment]
`data-gs-width` is for sizing widgets. The code you pasted is for the actual grid. I'll need more code to help you with your problem, but without seeing the code I am guessing that you're initializing a widget without a width (or with a width of two).
