### ISSUE TITLE
Items lose "data-gs-y" styles when any item is resized horizontally.

### ISSUE THREAD

**Issue by Stratofish** [gridstack/gridstack.js#744]
This seems to happen only when the resized item is the only one on it's row. Resizing it vertically resets them.

https://jsfiddle.net/ad2e0hvm/12/

As far as I can see this is due to the fix for #600. _updateStyles() is meant to be incremental but that fix flat out deletes all the styles and only recreates the top (item height + 10) rows

**Comment by radiolips** [comment]
This is bizarre. If you resize vertically and don't let go of click, you can still resize horizontally and it works fine. In my projects, I don't have this issue. I'll investigate, but I can't think of a good reason (which only means that it's a bad reason...but aren't all bugs bad?).

**Comment by radiolips** [comment]
@Stratofish Could you try again with the latest develop branch code? I believe that an old PR that I just merged will fix this for you.

**Comment by nickxbs** [comment]
I have the same problem, it seems fixed with the last dev version

**Comment by radiolips** [comment]
Thanks, @nickxbs . I'm going to close the ticket - Let me know if you still have a problem, @Stratofish .
