### ISSUE TITLE
multiple drag is possible

### ISSUE THREAD

**Issue by kingsgobi** [gridstack/gridstack.js#750]
i want to drag 2 box same time

**Comment by radiolips** [comment]
@kingsgobi This feature is inherently out-of-scope for gridstack. However, you can certainly use some simple Javascript code in combination with gridstack to move two widgets simultaneously. If you make an attempt, I'm sure someone here will help assist you in reaching the finish line.

**Comment by kingsgobi** [comment]
@radiolips thanks
