### ISSUE TITLE
appendTo: Body not working at all

### ISSUE THREAD

**Issue by codelinks** [gridstack/gridstack.js#752]
Hi,

I am trying to use GridStack in an container set to overflow: auto.  If overflow is not set to auto, gridstack behaves as documented. When set to overflow: auto and fixed height, the widgets do not cross the container they tend to extend the height/width of overflow container.

To get around this, I am using appendToBody when setting up draggable option of gridstack, as mentioned in the fix here:
https://github.com/troolee/gridstack.js/issues/414
However, appendTo body only works if helper is set to clone or a function that returns the clone.
https://api.jqueryui.com/draggable/#option-appendTo

That seems to cause another set of problems:
 - placeholder does not follow the draggable
 - items are not removed from the grid.
 - sometimes they go out of the grid.

I have created a plunker to demonstrate the problem(based on troolee.github.io/gridstack.js/demo/two.html) . Can you please guide me on how to use appendto body with gridstack.

Here is the plunker:

https://plnkr.co/edit/g7FQNFw8znTlEwgOl3EV

Thanks for your time and your help

**Comment by radiolips** [comment]
@codelinks Are you saying that when you use `clone` you have issues as well? I was only able to successfully get it working using clone with version 1, but if there's a reason you can't use clone I'm sure we can figure out a workaround.

**Comment by codelinks** [comment]
@radiolips - Thanks for looking into this.

Yes, even with helper: 'clone' the placeholder jumps around.

I forked the previous plunker to just use **helper: 'clone'**. Here is the new plunker: 
https://plnkr.co/edit/PMwvIjq5R0EFF4IIo0du?p=preview

Try to drag the first green box from the first grid and you will see that placeholder jumps to bottom.
Also I can not drag the grid-items to trash icon any more.

The main difference between the plunker and [demo](http://troolee.github.io/gridstack.js/demo/two.html) is that the grid is inside a panel body with fixed height and overflow set to auto. 

What would be a possible workaround?

**Comment by radiolips** [comment]
@codelinks I'm aware of how late this response is, but I've verified that this does work. For an example, check out gridstackjs.com (go to the advanced demo section). I hope you were able to find a satisfactory workaround. I know this is two years late, but feel free to reopen the issue if you still have problems.
