### ISSUE TITLE
Gridstack widgets can't be moved after new widgets are added

### ISSUE THREAD

**Issue by testuserx** [gridstack/gridstack.js#755]
Application made with RactiveJS, Redux and Gridstack.

When new widgets are added, all is fine and widgets are movable/resizable as well. But when I delete all widgets and add, for example, two new, then:

    1. widgets can't be moved and can't be resized.
    2. when try to delete widget it disappear, but other widgets change their position.

You can see this in [jsFiddle](https://jsfiddle.net/buyrwacb/1/)

You can see that right widget is moved to the right side, but handle stays where it is. So **why is such behavior and how to deal with that**?

Thanks!

**Comment by radiolips** [comment]
@testuserx Hey there. It looks like even resizing is weird prior to deleting the widgets. When I have some more time I'll try to take a closer look. I haven't worked with Ractive but hopefully I'll be able to figure out what's going on here. I don't think it's a bug in Gridstack, but rather something odd going on in combination with your setup.

**Comment by testuserx** [comment]
Thanks! I will wait for more information from you!

**Comment by adumesny** [comment]
still happens with latest code
https://cdn.jsdelivr.net/npm/gridstack@0.5.2/dist/gridstack.all.js
https://cdn.jsdelivr.net/npm/gridstack@0.5.2/dist/gridstack.min.css

**But** you are doing something wrong when removing a grid-item as the parent grid stays with data-gs-current-height="4" style="height: 240px;"

please check our working samples that removes (and adjust parent) dynamically... 
closing for now - reopen if you find issue on our side.
