### ISSUE TITLE
[internal] remove `dist/` from versioning, add needed release steps

### ISSUE THREAD

**Issue by efx** [gridstack/gridstack.js#776]
Versioning `dist` adds unneeded changes for contributor PRs. Ideally `dist` should not be versioned and instead only as part of `npm publish` or a release process.
# todo 
- [ ] add to .gitignore
- [ ] modify `Gruntfile.js` with publish task, incorporate into other steps

**Comment by adumesny** [comment]
Agree, it's also error prone to have 2 source of truth. 
it's already part of 'build' steps and 'publish' should do that as pre-req.
