### ISSUE TITLE
[internal] npm run test needs to call bower install

### ISSUE THREAD

**Issue by efx** [gridstack/gridstack.js#781]
## Subject of the issue
In a fresh clone of the repo, running`npm run test` will fail due to unresolved dependencies.
<img width="1200" alt="screen shot 2017-09-14 at 1 05 42 pm" src="https://user-images.githubusercontent.com/472721/30443541-e8725e44-994d-11e7-8537-198b1102f096.png">

## Your environment
* version of gridstack.js
* which browser and its version

## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://jsfiddle.net/dweiss/dqyvh6vr/) as a base.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

**Comment by radiolips** [comment]
@efx For this, you're saying that we need to update
```"test": "grunt lint && karma start karma.conf.js",```
to be
```"test": "bower install && grunt lint && karma start karma.conf.js",```
?
If so, do you want to put in a PR for this?

**Comment by efx** [comment]
updated @radiolips . I enjoyed the PR template as well!
