### ISSUE TITLE
expose gridstackjs.com/demo on gridstackjs.com - lack of interesting samples

### ISSUE THREAD

**Issue by adumesny** [gridstack/gridstack.js#782]
Took me a while to find the wonderful examples that are under the source code demo (like demo/two.htlm and demo.nest.html) showing more advanced interesting cases.

Yes the github readme page has this listed somewhere buried, or you can sync the source code + build + run but for most casual people looking for what's available they will miss it. recommend the main site exposed that from most (like the actual DEMO link in nav, isntead of the demo right underneath...)

## Steps to reproduce
1) http://gridstackjs.com
2) look for demos/samples (click top nav link, scroll down, etc..)
--> only get the one inline.

## Expected behaviour
have a more samples link to showcase all those under http://gridstackjs.com/demo

**Comment by radiolips** [comment]
There's a link more prominently on the homepage now. I'll make it a bit flashier when we redo the demo pages.
