### ISSUE TITLE
Positioning of widget on dynamically adding on small screens

### ISSUE THREAD

**Issue by vishalnarkhede** [gridstack/gridstack.js#788]
I'm facing some issue [gridstack.js][1]. As per documentation, we use [`addWidget()`][2] function to dynamically add widget to grid. We provide the x and y position as parameters to this function. On large screens this works perfectly fine, as in widget gets added at exact location given by x and y values. But on small screens, it is getting added on bottom of stack always, even if I provide x and y as 0 and 0 respectively.

I've [codepen][3] to demonstrate my problem.

When I click on "Add Widget" button, new widget (containing incremental counter) gets added in stack. For large screens it gets added on top (which is expected), since x and y for widget being added are set to 0 and 0 respectively.

[![For large screen][4]][4]

But if I reduce screen size (viewport), as you can see, widget gets added from the bottom.
[![For small screen][5]][5]

Can someone help me resolve this or provide any solution? Thanks in advance!!

**Thanks alot for this awesome library though, I love it :)**

  [1]: https://github.com/gridstack/gridstack.js
  [2]: https://github.com/gridstack/gridstack.js/blob/c0c1e47f1c427faa8559bd43fff6eb419ccb26e5/doc/README.md#addwidgetel-x-y-width-height-autoposition-minwidth-maxwidth-minheight-maxheight-id
  [3]: https://codepen.io/vishtree/pen/WZrmmp
  [4]: https://i.stack.imgur.com/fJo4k.png
  [5]: https://i.stack.imgur.com/v6yxk.png

**Comment by adumesny** [comment]
@vishalnarkhede looks like you are doing nested grids - does that problem happens with 1 grid ?
Also looks like you are running into 1 column mode (speudo 'responsive' implementation) when with  < 768px or so, which you can control with `opts.disableOneColumnMode` or `opts.minWidth`

**Comment by vishalnarkhede** [comment]
@adumesny Simplifying nested grid didn't solve the issue. I'm not sure why, but `disableOneColumnMode` is also not working for me.

Here is the updated codepen: https://codepen.io/vishtree/pen/WZrmmp

I'm using following this version of gridstack.js on codepen: https://cdnjs.cloudflare.com/ajax/libs/gridstack.js/0.3.0/gridstack.min.js

**Comment by adumesny** [comment]
with your latest sample, notice how it goes from 3,2,1 to 1,2,3 as it turns into 1 column layout - looks like it's resorting the items based on their dom position ? @radiolips would know the inner working, but that doesn't look right.

**Comment by vishalnarkhede** [comment]
@adumesny Yeah, when I resize the window from small to large (and the to small again), positions of widgets get fixed.

**Comment by adumesny** [comment]
FYI with latest 1.0.0-dev code `disableOneColumnMode` does get used (must be new feature) and when off, 1.0.0-dev does NOT re-order the items to 1,2,3, BUT adding new items do go to the bottom so you get 3,2,1,4,5

**Comment by radiolips** [comment]
Is there something wrong with the codepen? I'm not having this problem, but I thought I was in the past.
