### ISSUE TITLE
Front Page Question

### ISSUE THREAD

**Issue by savannahchoy** [gridstack/gridstack.js#790]
This is my Front page, Is there any ways to make two side even?(left and right have white part) Thanks! I will reply asap!!! Thank you so much!
![screen shot 2017-09-20 at 11 44 03 pm](https://user-images.githubusercontent.com/31672741/30682235-aca79cc0-9e5d-11e7-96ac-50671c4e7470.png)

**Comment by vishalnarkhede** [comment]
Question description is not sufficient to be honest. Try to follow guidelines for posting issue as shown below, it will help people to understand the issue and help you.

<img width="738" alt="screen shot 2017-09-21 at 2 15 39 pm" src="https://user-images.githubusercontent.com/11586388/30695167-74bcc48c-9ed7-11e7-82aa-5bef9451817c.png">

**Comment by savannahchoy** [comment]
Ok let me organize it

**Comment by radiolips** [comment]
I don't really understand this question. I'm going to close this issue out, but if @savannahchoy or anyone else better understands what this should be, I'll reopen it.
