### ISSUE TITLE
Gridstack and vueJS 

### ISSUE THREAD

**Issue by metalheadz** [gridstack/gridstack.js#791]
Hi !

I want to know if there's a way to correctly use this grid using vueJS capabilities...

Because of the way DOM is generated, it looks like I cannot add any vue component when I add a widget, even a simple javascript function would not be recognized... It work only with plain HTML, which is useless for me..

I also tried to hide some widgets with a v-if but when theyre showed, it render a static tile (I also tried to use makeWidget(el) but in vain). Same thing if a do a v-for with an array.

Im using the latest version of this grid and vueJs 2.4.2 with webpack

Let me know if you need others informations but this should be clear since its a generic question.

Thanks!

**Comment by metalheadz** [comment]
I finally succeeded! Using this method for the one interested : https://codepen.io/nyoung697/pen/BperoZ

**Comment by Tropicalista** [comment]
I have used this approach: https://codepen.io/Tropicalista/pen/PmKajR

**Comment by chen-ABC** [comment]
> I have used this approach: https://codepen.io/Tropicalista/pen/PmKajR
I have a problem with this example
![image](https://user-images.githubusercontent.com/30097790/51230818-5600db00-199c-11e9-963d-3c19680061db.png)
