### ISSUE TITLE
Removearea doesn't work when jQuery.show() is applied

### ISSUE THREAD

**Issue by MSDevYT** [gridstack/gridstack.js#794]
Hi,
I want to make a removearea which only apears while you move a widget.
But when I apply jQuery.show() on the removearea it doesnt remove the widget.
Without .show() the area works fine.

Also there are no errors in the console.

My code:
```
var options = {
        disableResize: true,
        cellHeight: 300,
        removable: ".info-box-delete",
        removeTimeout: 100
    };
    var grid = $('.grid-stack').gridstack(options).data('gridstack');

    $('.grid-stack').on('dragstart', function(event, ui) {
        $(".info-box-delete").show(200);
        
    });
    $('.grid-stack').on('dragstop', function(event, ui) {
        $(".info-box-delete").hide(200);
    });

```

I'm using the newest version with Chrome.

I reproduced it in the [fiddle](https://jsfiddle.net/w32nx02p/).

**Comment by adumesny** [comment]
yeah I can see that. would be good to update demo app (two.html) with this auto-show behavior once this gets fixed...

**Comment by radiolips** [comment]
Hi, @MSDevYT . I think you are mistaken. `show` is fine. There are two problems with your example. Firstly, when you use `position: fixed`, it won't work. You can remove the `show` and it will still not work. Secondly, you are hiding the remove element on drag stop - so there's no collision. You should be hiding the box after the element is removed. If you do that, it will work. I made changes to your jsfiddle to verify this.

@adumesny I definitely think it's a cool feature, and I'll make sure the remove box works in this way when we update the demos (they could use some polish).
