### ISSUE TITLE
Auto-repositionning? 

### ISSUE THREAD

**Issue by metalheadz** [gridstack/gridstack.js#795]
Is there a way to auto reposition all the element after using the resize function without manually reposition each nodes? When I resize a node making it bigger in width, it always push the next node at the bottom even if theres enough space.

**Comment by DnJealt** [comment]
Do you mean adding `float: false` to the Gridstack options?

**Comment by adumesny** [comment]
I don't think that's what he means... http://gridstackjs.com/demo/two.html if you resize the first one and make it wider, it doesn't push the 2 mopre to the right to fit, it pushed #2 down... I'm guessing he wants push right, then next row if doesn't fit... (grid on right has float on, but behaves same way here)

**Comment by metalheadz** [comment]
I found a way to do it... I remove all the nodes from the grid with removeall keeping them in the DOM... I after add manually each component using the autoposition paramaters... Not so elegant... Would be nice if another option exists to do that... Pushing nodes at the bottom is very bad when you dont want to loose precious space

**Comment by adumesny** [comment]
you want a left-right gravity, where right now it's a top only gravity - there has been suggestion to support multiple style by others (and @radiolips mention this might make it in 1.0 release but I wouldn't bank on it).

**Comment by metalheadz** [comment]
I want a mix of the 2 in fact, when theres not enough space at the right, its ok to push the node at the bottom, begining at the left again.

**Comment by radiolips** [comment]
Oddly enough, #796 requests that exact feature.

**Comment by radiolips** [comment]
I'm closing this in favor of #796, but please watch 796 if you'd like to keep in the loop.
