### ISSUE TITLE
Move/Drag Tiles like iPhone Icons

### ISSUE THREAD

**Issue by sculptsoft-devs** [gridstack/gridstack.js#796]
Actually, I want to drag/move tile horizontally only.So, Tiles should always move to right "n+1" position.So whenever I try to move tile and drop, the next tile shift to +1 position.

Ex. If I have 3 columns and 3 rows and tiles numbered as A,B,C,D,E,F,G,H,I. Now, when I drop Tile-E between B and C then new formation will be like   A B E , C D F, G H I. so each tiles after B should be  shifted right side by +1.

**Comment by sculptsoft-devs** [comment]
Yeaa, should be auto-repositioning in sequence.Also, hide/show widget should be needed auto repositioning.

**Comment by radiolips** [comment]
Duplicate of #149 .
