### ISSUE TITLE
Drag to bottom of column with zero vertical margin

### ISSUE THREAD

**Issue by chrisjwilliamsuk81** [gridstack/gridstack.js#797]
## Subject of the issue
The functionality to drag a widget to the bottom of a column seems to now be impaired since the introduction in v0.3.0. From the release notes it says

"remove placeholder when dragging widget below grid (already worked when dragging left, above, and to the right of grid)."

Running the setup with a zero vertical margin, if you have 2 items in a column and try and drag the top widget below the bottom one you have to be pixel perfect otherwise the behaviour now assumes dragged out of the grid

## Your environment
Tested in 0.3.0 and v1 beta
Chrome 60

## Steps to reproduce
Set up an example here - https://codepen.io/cjw8/pen/Lzepme
To try and move the top "Top Widget" below the bottom widget. The blue grid shrinks when you move the top widget below the bottom widget so placeholder is lost.

## Expected behaviour
The placeholder should remain

## Actual behaviour
The placeholder is removed.

As per the release notes this functionality was removed. Is there any option to add this back in, or a way to override this functionality to as it was pre v0.3.0

**Comment by radiolips** [comment]
@chrisjwilliamsuk81 Are you saying it worked prior to v0.3.0 or it worked on v0.3.0?

**Comment by KennethanCeyer** [comment]
@radiolips 
it doesn't worked at `v0.3.0` and prior to `v0.3.0` either.

**Comment by radiolips** [comment]
@chrisjwilliamsuk81 @KennethanCeyer Not sure what happened here, but there are some problems in the example. I've verified that it works fine when these problems have been rectified. Namely, width and height cannot be larger than 12.
