### ISSUE TITLE
Can you have a one line draggable grid?

### ISSUE THREAD

**Issue by louman** [gridstack/gridstack.js#801]
## Subject of the issue
Hi, is it possible to have a one row draggable grid?

I can drag but can't drop an item. If I change the height to two, I can then drag them horizontally but it also allows the user to use the second row, which I don't want to.

## Your environment
gridstack 0.2.5
chrome latest

## Steps to reproduce
https://jsfiddle.net/cjq3k2k0/2/

**Comment by louman** [comment]
It also happens on 0.3.0

https://jsfiddle.net/5ecjtd76/

I noticed that if you remove one widget, leaving three of them with width = 3, then you get one more slot and then you can move the widgets around.

It seems that the grid needs room to move the other widgets around when you start dragging. Is there any way to work around that?

**Comment by radiolips** [comment]
Hey, @louman . This is a known issue. There are several open issues with it, so I'm closing this one. This will be fixed in a newer version.
