### ISSUE TITLE
Catch animation finished event

### ISSUE THREAD

**Issue by notnow123** [gridstack/gridstack.js#804]
I am creating a grid and then updating pane (node) positions from stored JSON data.  I am using batchUpdate and grid.commit() to change the positions of panes in the grid after it has been created.

My code for the re-positioning is as follows:

    jQuery.update_grid = (view_data, animate_option) ->
      grid = $('.grid-stack').data('gridstack')
      grid.setAnimation(animate_option)
      grid.batchUpdate()
      $.each view_data, (key, grid_node) ->
        switch grid_node.panel_name
          when "precedent-view"
            grid.update($("#precedent-view"), grid_node.x, grid_node.y, grid_node.width, grid_node.height)
          when "case-report"
            grid.update($("#case-report"), grid_node.x, grid_node.y, grid_node.width, grid_node.height)
          when "document-editor"
            grid.update($("#pad"), grid_node.x, grid_node.y, grid_node.width, grid_node.height)
          when "chat-window"
            grid.update($("#chat-window"), grid_node.x, grid_node.y, grid_node.width, grid_node.height)
        return
      grid.commit()

How can I run code after the grid has been moved into its final positioning - i.e. after the commit has run and the animation has finished so that all panes are in their updated positions?  I have tried the change event but this seems to fire at the start of the change rather than after the grid has arrived in its final state on screen.

Any help much appreciated.

**Comment by notnow123** [comment]
That would be fantastic if you could do that.

I have worked around the issue by implementing a Javascript wait function
for a number of seconds but it is a hack.

Thanks

Evan Brown

**Comment by xingguo3** [comment]
Hi, Any updates? 
Im also using ajax to load grids in async mode (out of performance consideration ). However, those grids 's position will be rendered by ajax finishing sequence rather than its coordinates. Is there a solution for this?

**Comment by adumesny** [comment]
@notnow123 sounds like you actually need an event when the animation finishes (final position) - (which I believe is broken now #937)  - related to `gsresizestop` isue people are seeing in #829 and others...

**Comment by adumesny** [comment]
looking the sass, it's 300ms CSS animation of the final position/size, but the gridstack properties are immediate, so are you looking at actual x,y,width,height ? you could delay by this amount, or I could add an 'animationDone' event but that is CSS driven and not code option so could be out of sync...

```css
$animation_speed: .3s !default;
.grid-stack {
  &.grid-stack-animate,
  &.grid-stack-animate .grid-stack-item {
    @include vendor(transition, left $animation_speed, top $animation_speed, height $animation_speed, width $animation_speed);
  }
}
```

**Comment by adumesny** [comment]
dup of #829 , closing
