### ISSUE TITLE
Use of reserved word "float" will break YUI and other compressors

### ISSUE THREAD

**Issue by bpottle** [gridstack/gridstack.js#806]
## Subject of the issue
The reserved word 'float' is used in dangerous context. The use of 'float' as a dot-notation property instead of a bracket-notation property will cause compressors to break and some validation checks to fail. The library needs to either assign float using obj['float'] or assign the .cssFloat property instead.

## Your environment
* gridstack 0.3.0
* Browser-independent bug

## Steps to reproduce
In all cases where the property 'float' is set using the format: obj.float =... instead of obj['float'] will cause YUIcompressor and other validation to fail because it is a reserved word. Simply assigning it using the bracket notation fixes the issue.

## Expected behaviour
'float' shouldn't be set using dot notation

## Actual behaviour
'float' is set using dot notation and cannot be parsed by a utility that expects rigid validation

I understand that there's an already-minified version of gridstack.js available, but for load-order reasons it is necessary to be able to compress it using a third-party utility. Plus, it's just best practice to not use dot notation on reserved words.

**Comment by radiolips** [comment]
`float` is technically reserved, but has not actually been used since `ECMA3`. If you feel strongly about this, @bpottle , put in a PR to update the usage. Otherwise, I'll change it when I have some time, but this one is going to have to be low priority for now.

**Comment by adumesny** [comment]
@bpottle closing due to age. this is a trivial change otherwise, so let me know if you still need this.
