### ISSUE TITLE
Hide resize handle, keep resize functionality

### ISSUE THREAD

**Issue by ViktorQvarfordt** [gridstack/gridstack.js#808]
## Subject of the issue
I want to hide the resize handle that appears on hover on the grid, but keep the 

## Your environment
* version of gridstack.js: 0.3.0
* which browser and its version: latest chrome

## Steps to reproduce
Example: https://jsfiddle.net/dqyvh6vr/4/

I have enabled resize on all edges, but I don't know how to get rid of the resize icons.

**Comment by mlbaquerizo** [comment]
You can set opacity of `.ui-resizable-se` to 0?

**Comment by ViktorQvarfordt** [comment]
That should work. `display: none` would probably be even better.

**Comment by ViktorQvarfordt** [comment]
I went for
```
.ui-resizable-se, .ui-resizable-sw {
    opacity: 0 !important;
}

.ui-resizable-se {
    bottom: -5px !important;
    right: -5px !important;
}
```
Because I have an button in the lower right corner, and I dont want the resize handle to be in the way.
