### ISSUE TITLE
float: true pushes widgets down before releasing moved/resized widget

### ISSUE THREAD

**Issue by mlbaquerizo** [gridstack/gridstack.js#811]
Moving/Resizing a widget should not affect surrounding widgets until that widget is released.

In the case where a widget is expanded or moved and then placed back to its original position (made smaller or placed out of the way) before releasing it, I would expect the surrounding widgets to move back to their original positions as well. This doesn't seem to be the case as affected widgets are pushed down and remain there.

**Comment by adumesny** [comment]
this is no longer the case with current release - see https://gridstackjs.com/demo/two.html
(I thing we use `._origY` for that).
