### ISSUE TITLE
Last grid-stack-item at bottom of the window doesn't resize 

### ISSUE THREAD

**Issue by fekkyDev** [gridstack/gridstack.js#815]
## Subject of the issue
Resize is not working at bottom of the window

## Your environment
* version of gridstack.js 0.3.0

## Steps to reproduce
Basically  re sizable is not registering to scrollbar while resize  the gridstack item
(https://jsfiddle.net/winstonchang/dfqtt/) as a base.

## Expected behaviour
Scroll bar should move and able to resize the gridstack item

## Actual behaviour
Doesn't  resize

**Comment by DnJealt** [comment]
You made it a resizable item, gridstack is not loaded in that fiddle. So I think you should look for a jQuery UI solution.
