### ISSUE TITLE
Nested Grid clickable icons

### ISSUE THREAD

**Issue by joemorcullo8** [gridstack/gridstack.js#817]
@troolee @radiolips  Hi, is there a options to enable the icons to be clickable inside a nested grid?

I have an icon on the parent grid and it's working fine, but when it comes to the icons inside nested grid it's not working anymore. When I click it nothing happens.

![image](https://user-images.githubusercontent.com/22418211/32768614-796c58d4-c953-11e7-98b0-fe05255a53aa.png)

**Comment by DnJealt** [comment]
Maybe this has something to do with your z-index?

We cannot help you unless we know the code, would you be so kind to provide a fiddle?

**Comment by joemorcullo8** [comment]
Sorry the problem is not in nested grid :) I just found out that it's not working on the widget that is added using addWidget() :) will be posting separate question for it.
