### ISSUE TITLE
gsresizestop on nested grid is affecting the parent grid

### ISSUE THREAD

**Issue by joemorcullo8** [gridstack/gridstack.js#818]
@troolee @radiolips 

Hi, I have an issue regarding the gsresizestop for the nested grid and the parent grid.

When I'm resizing the nested grid, the gsresizestop event is repeating for the parent grid.

I want to get the size after resizing the nested grid/parent grid but not at the same time.

https://jsfiddle.net/60yu4p9t/7/

**Comment by adumesny** [comment]
your sample doesn't work as you never init the nested grid.
Please update your code to the latest use [this template](https://jsfiddle.net/adumesny/jqhkry7g) as a base, and look as https://gridstackjs.com/demo/nested.html as well
