### ISSUE TITLE
Auto position setting

### ISSUE THREAD

**Issue by smrazavian** [gridstack/gridstack.js#820]
## Subject of the issue
How to set auto position align element from  right to left and from top to bottom 

## Your environment
* version 1.0.0-dev
* chrome and Firefox

**Comment by radiolips** [comment]
@smrazavian Right now, if you pass the `rtl` parameter, it still positions elements left to right?

**Comment by radiolips** [comment]
I see from #819 that this is definitely an issue. Closing, but please follow #819 for updates.
