### ISSUE TITLE
transform it to Bootstrap3 grid system code

### ISSUE THREAD

**Issue by koupeng** [gridstack/gridstack.js#821]
When I get the widgets values,such as 
`[{x: 0,y: 0,width: 6, height: 6},{x: 6,y: 0,width: 6, height: 6}]`
How can I transform it to Bootstrap3 grid system code...............

**Comment by koupeng** [comment]
I used stackgrid.js to layout my page........

**Comment by artknight** [comment]
if you need the layout not to have absolute positions and actually conform to the content you will have to write your own solution. I did write my own some time ago.. i am wondering if i should start a repo with that?

**Comment by radiolips** [comment]
@koupeng I don't understand what you're asking. You want the widgets to have breakouts for different resolutions?
