### ISSUE TITLE
Finding Drop event while moving widget from one grid-stack-container to another

### ISSUE THREAD

**Issue by Shiva4393** [gridstack/gridstack.js#823]
## Subject of the issue
I'm having multiple grid-stack-container's, now my requirement is to get event after dropping widget from one container to another.

## Your environment
* gridstack.js 1.0.0-dev
* Chrome Version 61.0.3163.100

**Comment by radiolips** [comment]
We can add this feature.

**Comment by vishalkrv** [comment]
Any updates on this?

**Comment by radiolips** [comment]
This now works in the `develop` branch. Check the docs for event info.

**Comment by dirkheijn** [comment]
Any chance of this being included in an upcoming release? I consume gridstack via npm, the latest version available does not include this event.
