### ISSUE TITLE
[New Feature][Enhancement] Grid Item Expand/Collapse

### ISSUE THREAD

**Issue by PalanivelLakshmi** [gridstack/gridstack.js#824]
## Grid Item Expand/Collapse Feature
As a User can able to expand/collapse of the Each Grid if We've More that 20 Grid's.

**Comment by radiolips** [comment]
@PalanivelLakshmi Thanks for logging this issue! Actually, I believe that this is not something the library should be responsible. It's a feature that you could certainly implement in your own code, but it's a very specific thing that won't impact enough developers.
