### ISSUE TITLE
Restrict Height of Grid Stack container when grid container is full with widgets

### ISSUE THREAD

**Issue by Shiva4393** [gridstack/gridstack.js#825]
## Subject of the issue
I have Created gridstack of 4*4 matrix. When gridstack is full with widgets(16 widgets). When i drag widget, Grid stack height is updating.

## Expected behaviour
Is there a way to  restrict height of gridstack?

**Comment by VladasC** [comment]
Same here. I create a grid of one single row, using "height" option (I tried data-gs-height="1" too). But it ignores it and still places widgets onto second row if doesn't fit (creates a second row). Thanks.

**Comment by radiolips** [comment]
Hey there, @Shiva4393 , @VladasC . Unfortunately, the way `gridstack` is built, there's no way to do a horizontal flip, which is needed for @VladasC 's case and also prevents swapping widgets in a full grid. There are a few earlier open issues, so I'm closing this one, but both of these features are on the roadmap.
