### ISSUE TITLE
Force to only single row using data-gs-height or height option doesn't work

### ISSUE THREAD

**Issue by VladasC** [gridstack/gridstack.js#826]
## Subject of the issue
I created a grid of one single row, using "height" option and data-gs-height="1" set  too. But it ignores it and still places widgets onto second row if it doesn't fit (creates a second row). When you try to move an item from second grid to first, also creates new line, when it should simply decline it and don't create second line.

There's a similar issue I believe, but with less detail: #825 

## Your environment
* gridstack.js 0.3.0 and also 1.0.0-dev
* Chrome
* jsfiddle and also localhost

## Steps to reproduce
https://jsfiddle.net/yr6uuf9h/1/
Try dragging an item from one grid to another.
Try dragging an item within the same grid onto another (drag around an element over the other element for few seconds and it will drop to a second line)

## Expected behaviour
It shouldn't create a new row when dragging over from one grid to other if it doesn't fit as height of grid is set to 1. It should decline and revert to how it was. 

## Actual behaviour
It creates a new

**Comment by radiolips** [comment]
Hey @VladasC  - I responded to you in the other issue you mentioned, but tl;dr: there's no way currently to flip horizontally, nor is there a way to rearrange a full grid. There are some open issues for this, so I'm closing this issue, but these features are on their way.
