### ISSUE TITLE
Cannot read property 'item_class' of undefined

### ISSUE THREAD

**Issue by AGuyCalledGerald** [gridstack/gridstack.js#828]
## Subject of the issue
I try to use gridstack and get the error "Cannot read property 'item_class' of undefined"
Can someone tell me where the problem may be?

Error occurres in gridstack.js:

        var GridStack = function (el, opts) {
             var self = this, one_column_mode;
             this.container = $(el);
             opts.item_class = opts.item_class || 'grid-stack-item'; //error
       ....
## Your environment
gridstack.js 0.2.3, jquery 3.2.1, lodash 3.5.0
Chrome latest

      $('.grid-stack').gridstack();

     <div class="grid-stack">
         <div class="grid-stack-item"
          data-gs-x="1" 
          data-gs-y="1"
          data-gs-width="1" 
          data-gs-height="1">
              <div class="grid-stack-item-content">test</div>
           </div>
      </div>

**Comment by vivekpandey343** [comment]
getting same error. Can you please tell me how to fix?

**Comment by adumesny** [comment]
@vivekpandey343  first of all, you should be using the latest build (which is 0.5.1, no lodash needed either) not some ancient build, which has the fix. Second if you look at the code above you can see it's referencing passed in param 'ops' so just need to pass {} to have a non null object.
