### ISSUE TITLE
Accessibility Review Required

### ISSUE THREAD

**Issue by mgifford** [gridstack/gridstack.js#830]
## Subject of the issue
The demo has basic accessibility issues, and I assume the code does too

## Your environment
Just testing with Firefox and your demo

## Steps to reproduce
Try to navigate without a mouse

## Expected behaviour
One should be able to tell where one is and also move the blocks around without using a mouse

## Actual behaviour
You can't.

See the discussion here https://www.drupal.org/project/drupal/issues/2920006

**Comment by radiolips** [comment]
@mgifford Thank you for bringing this to our attention. I'm unfortunately ignorant to this issue, so please help inform me - what's needed to get this up-to-code? There's no reason this library shouldn't be able to pass an accessibility review. Let's make it happen.

**Comment by mgifford** [comment]
Just try to navigate your site without using your mouse:
http://gridstackjs.com/

There are probably other issues, but right now I can't find a way to move the blocks without a mouse.

**Comment by adumesny** [comment]
very unlikely to get fixed. closing
