### ISSUE TITLE
Dragging Doesnt work properly when scaled via css transform

### ISSUE THREAD

**Issue by digitalml** [gridstack/gridstack.js#831]
When you scale the div that contains gridstack via css scale transform the mouse x and y drag positions are not correct. This happens with all draggable components and the css scale transform.

Ive tested with normal jquery ui draggables and can fix this issue with the following code but i dont know how to implement it within gridstack.js.

if anyone can help i'd be willing to pay as I need this change to work with css scale transforms.

drag: function(event, ui) {

              var changeLeft = ui.position.left - ui.originalPosition.left; // find change in left
              var newLeft = ui.originalPosition.left + changeLeft / (( scaleLevel)); // adjust new left by our zoomScale

              var changeTop = ui.position.top - ui.originalPosition.top; // find change in top
              var newTop = ui.originalPosition.top + changeTop / scaleLevel; // adjust new top by our zoomScale

              ui.position.left = newLeft;
              ui.position.top = newTop;
          }
        });

thank you!

**Comment by itdavidhan** [comment]
I have similar problems.I set width to 100 (default 12).
When you drag it, x increases or decreases depending on the width of the browser.

**Comment by radiolips** [comment]
@digitalml I'd love to help you out. Could you create a jsfiddle or something where I could see what you're referring to? There's no doubt in my mind that we can get this working.

**Comment by adumesny** [comment]
@digitalml @itdavidhan this was fixed in v9.3 - donate if you find this lib useful.
