### ISSUE TITLE
Grid items not getting a height with makeWidget and cellHeight auto

### ISSUE THREAD

**Issue by Thodor20** [gridstack/gridstack.js#838]
## Subject of the issue
I'm trying to render a grid using a Marionette collectionview, this collectionview is responsible for loading all the grid panes and putting them in the DOM, afterwards all the panels are added as widgets to gridstack.

However as soon as everything is done the panes have no height set to them. They are all 0 pixels high. I'm using `cellHeight: 'auto'` for height calculation of the grid panes.

## Your environment
* Gridstack 0.3.0
* Google Chrome 63

## Steps to reproduce
Demo: https://codepen.io/Thodor20/pen/eyLLVM
1. Make sure to have the debug console open before you look at the demo.
2. You can see in the element inspector that the structure of the HTML is correct, there are 3 elements which are all initialized by gridstack.
3. Close the inspector or resize the browser, only then the grid panes will finally appear.

**Comment by radiolips** [comment]
@Thodor20 I don't have this same problem. Are you able to get it to work without Marionette and without using `cellHeight: 'auto'`? I want to be sure that the code will work in a plainer situation.
