### ISSUE TITLE
How to get the information of Rows and columns.

### ISSUE THREAD

**Issue by rahulawasthi** [gridstack/gridstack.js#839]
## Subject of the issue
I need to get the track that how many elements are there and also the how many are there in row 1 and how many are there in row 2. Based on that i need to generate a pdf. The structure of pdf and the structure of the gridstack elements must be same. Do gridstack provide such kind of functionality. I came to know one method in gridstack i.e getCellFromPixel, will that function help me and how to use it.

## Your environment
* gridstack.js 0.3.0
* Google Chrome Version 63.0.3239.132 (Official Build) (64-bit)

**Comment by crazyfx1** [comment]
You can use jQuery to get all items from gridstack.
```JavaScript
var items = $(".grid-stack .grid-stack-item");
```

And for each element in that list you can get the respective data elements to get the x, y position and the size of the elements. 
```HTML
 <div class="grid-stack-item"
        data-gs-x="0" data-gs-y="0"
        data-gs-width="4" data-gs-height="2">
            <div class="grid-stack-item-content"></div>
    </div>
````

So you can get them with 
```JavaScript
width = items[0].attr("data-gs-width");
```
etc..

**Comment by rami-alloush** [comment]
I prefer accessing the grid nodes and get whatever info I need
                    var grid = $('.grid-stack').data('gridstack');
                    var grid_nodes = grid.grid.nodes;
                    var grid_count = grid.grid.nodes.length;
The `grid_nodes` var has EVERYTHING you might need and more.
