### ISSUE TITLE
How to know next free space in grid stack

### ISSUE THREAD

**Issue by sathis810** [gridstack/gridstack.js#840]
How do we get x,y axis of next free space in gridstack

**Comment by crazyfx1** [comment]
You might need to iterate through the x and y positions of your grid and check each position with the [isAreaEmpty](https://github.com/gridstack/gridstack.js/tree/develop/doc#isareaemptyx-y-width-height) method until it returns true.

**Comment by radiolips** [comment]
Hey, @sathis810 . @crazyfx1 is right (thanks!), you'll want to use `isAreaEmpty` and/or `willItFit`.

**Comment by sathis810** [comment]
Thanks @crazyfx1. working fine
