### ISSUE TITLE
gs.removeWidget() not removing node from gs object

### ISSUE THREAD

**Issue by Ruchir-zealous** [gridstack/gridstack.js#842]
## Subject of the issue
In application I have a feature to add and remove widget dynamically. But when I remove the widget I noticed the error in console 
```
Cannot set property '_id' of undefined
    at h.removeNode (gridstack.js:341)
```
While debugging I found that, when I removed the widget from gridstack using 
```javascript
 gs.removeWidget("#" + widgetId) 
```
it removes the widget but the node is still there under
 ```
gs.grid.node
```

I tried passing true to detached node but it still keeping all old widgets under node.

## Your environment
* gridstack.js 0.2.5

**Comment by Ruchir-zealous** [comment]
Resolved by using JQuery Object
```
gs.removeWidget($("#" + widgetId)) 
```

**Comment by spacehamagent** [comment]
Seem not working... if i got the grid-stak-item like that ??

I use id to put the "gs-id" in my code dynamically but when i try to remove the item it not working.


html gris-stack-item :

<div class="grid-stack-item ui-draggable ui-resizable ui-resizable-autohide" gs-x="2" gs-y="1" gs-w="7" gs-h="1" gs-id="10" style="background-color: rgb(0, 0, 255);"><div class="grid-stack-item-content"><div class="bloc" data-key="0" data-type="0" data-gs-x="0" data-gs-y="0" data-gs-width="12" data-gs-height="1"><div class="infoBloc"><span>[w, h]</span></div><div class="actionsBloc"><span><a href="#" class="pencil"><i class="fa fa-pencil fa-1x"></i></a></span><span><a href="#" class="trash"><i class="fa fa-trash fa-1x"></i></a></span></div><div class="block"><p>Block #10</p></div></div></div><div class="ui-resizable-handle ui-resizable-se" style="z-index: 100; user-select: none;"></div></div>



I try to remove it with that but the block continue to be there :'(

grid.removeWidget($('.grid-stack-item[gs-id="' + id + '"]'));
