### ISSUE TITLE
Floating Not working properly

### ISSUE THREAD

**Issue by Prasanthcs29** [gridstack/gridstack.js#844]
## Subject of the issue
Floating not working properly

Windows 10
* gridstack.js 0.3.0
*Chrome 63

While dragging the First DOM to second DOM it works fine. But again i tried to move first DOM to original x and y value second DOM not moved and i have white spaces. In that case i try to resize the DOM it calculate the empty spaces and set height as huge pixel.

Thanks,
Prasanth

**Comment by radiolips** [comment]
@Prasanthcs29 hey there. Sorry you're having a problem. Could you provide an example?
