### ISSUE TITLE
Performance IE 11

### ISSUE THREAD

**Issue by mvkampen** [gridstack/gridstack.js#845]
## Subject of the issue
Initial layout rendering of stack-items takes very long on IE 11.
Even when the number of items is not very big, e.g. 20
Not expecting miracles for older IE versions, but 11 should be doable.

## Your environment
gridstack.js 0.3.0
jquery 3
jquery-ui > 1.12
lodash > 4
IE 11

## Steps to reproduce
This attempts to reproduce the issue, because its very minimal and doesnt contain much html.
It doesnt represent the full problem, but still seems slightly slow.
https://jsfiddle.net/dqyvh6vr/12

This is a live example
https://wijvan.winkwaves.com/welcome

## Expected behaviour
Layout of widgets should have initial layout according to gs-{x,y,width} data attributes (ex. 'data-gs-x')
This should render pretty quickly, taking data-gs-width calculating height from options cellHeight and verticalMargin and determine absolute positioning from data-gs-x and data-gs-y.

We know there are some issues regarding speed of jquery draggable with many elements in IE.
However, we initialize with drag and resize disabled. The user enables it by pushing button AFTER initial rendering.
```js
disableDrag: true,
disableResize: true
```
## Actual behaviour
When gridstackjs initializes, grid-stack-item are positioned with absolute coordinates.
In Chrome, Firefox this will render all widgets on their place within half a second.
In IE 11 this will take usually atleast 5 seconds.

**Comment by DnJealt** [comment]
Aside from the website loading quite slowly overall, I'm not getting any noticeable differences between Firefox and IE11. Are you sure IE11 isn't throttling on loading the actual JavaScript?

**Comment by radiolips** [comment]
@mvkampen What other browsers did you test with? I don't have IE11 currently accessible, but will get access if need be. It sounds like @DnJealt saw consistent results, though.

**Comment by mvkampen** [comment]
I updated jquery from 2 to 3 to make sure to rule out outdated dependencies. Disabled animation in the options to rule that out. Also spend some time in browser profilers to get more detailed explanation.

I tested on Firefox 58.0.1 and IE 11 in Virtualbox. Start profiler and reloaded the page and stopped the profiler after the grid was rendered. I tested the live example and the jsfiddle, and another in the same environment as live but with other widget composition.

insertCssRule and innerWidth calls are notoriously slow, because that just how the DOM performance is. Taking up between 25% to 37% of total javascript profiling time of the page load.

These are called within updateStyle function. Here a table of results for each page in IE and Firefox (FF)
You can see the relation of insertCssRule called to updateStyle is very different in IE and across all examples. Also the jsfiddle this is the case. I dont think this has something to do with doing measurements in a VM. We have a few clients with IE11 who are reporting this performance problem.

|browser| function | live | live light | jsfiddle |
|----------|------------|------|-----------|---------|
| IE | updateStyle | 12 | 8 |  16 |
| FF | updateStyle | 3 | 5 | 3 |
| IE | insertCssRule | 2808 | 1348 | 1936 |
| FF | insertCssRule | 33 | 12  |16 |

In the live example (https://wijvan.winkwaves.com/welcome) it seems to take extra long because of the Youtube video embed into iframe. Layout seems halted (or is continuously redrawn) until this iframe is rendered? The live light example also has two flowplayer videos as content, but these seem less affected than embedding the youtube video, because that is loaded into an iframe.

Is it always the use case that grid items have a absolute height? So it could ignore the loading of content DOM subtree, to determine the positioning of other grid items. But you need to wait for DOM to load content outside of the grid to determine its position. Maybe IE DOM handles events differently for iframe content?

**Comment by mvkampen** [comment]
So updateStyle removes the generated stylesheets more often.
But also [this for loop](https://github.com/gridstack/gridstack.js/blob/ba681fc4642cdf6dee733d476a6524c7f6f7d65b/src/gridstack.js#L1007) seems to get executed everytime? As if this._styles._max variable is not set. Would explain the amount of insertCssRule calls, but I havn't debugged that so far to confirm.

**Comment by mvkampen** [comment]
The insertCssRule being called 2808 times seems correct. The Firefox number is indeed a sample and does not reflect the absolute number of calls.

In the updateStyle, the following rules are defined.
- an initial min-height.
maxHeight = the sum of all rows of widgets stacked in tallest column. (e.g. 60)
-  for each row height, 4 css rules are inserted
   (y, height, min-height, max-height)

12 widgets * 4 rules * 60 rows ('alot' of rows because we require a fine grid) + (12 * 1) initial rule
= 2892 insertRule statements

Because of the [initStyles](https://github.com/gridstack/gridstack.js/blob/8ea752ddff7973a97045849eafbe7fbd5e9c9e0d/src/gridstack.js#L944) call in updatesStyles.
The previously build stylesheet with generated rules is removed. 

updateStyles is called within GridStackEngine onchange function.
After the engine is initialized, nodes are [generated](https://github.com/gridstack/gridstack.js/blob/8ea752ddff7973a97045849eafbe7fbd5e9c9e0d/src/gridstack.js#L676) for each stack item, for which is will [prepareElement](https://github.com/gridstack/gridstack.js/blob/8ea752ddff7973a97045849eafbe7fbd5e9c9e0d/src/gridstack.js#L682)
Which cascades into addNode, _notify, onchanges, updateStyles calls.

For now I made a quick and dirty fix which improves performance.
By collecting all rules in an array and reduce them at the end to a single textNode.
Which is appended to the sheet.ownerNode (<style>)

This will reduce 4 * 60 + 1 = 241 changes to the DOM to 1.

More elegant and efficient ways to pursue.
- Create the sheet under a documentFragment dettached from the DOM. Inserting sheet into DOM after all rules are calculated.
- Using the same sheet between updates, and appending more rows when needed, when adding more items.

**Comment by nolanvance** [comment]
disabling the initStyles call in updateStyles helped my speed a lot for IE11. @mvkampen can you share your changes?

**Comment by Revo86** [comment]
@mvkampen i'm also highly interested in it

**Comment by rami-alloush** [comment]
I'm have serious performance issue! I build around 500 widgets on initialization (coming from DB).
It takes a whooping 30 seconds for the grid to be ready! 
Not sure where exactly to optimize.
@mvkampen, any code snippets are appreciated.

**Comment by radiolips** [comment]
IE 11 is only around 3% of browser market share, so I'm closing this out. If someone has a PR that they can add to speed up IE 11 load time, I will happily check it out and merge it in.

**Comment by adumesny** [comment]
might be worth adding a sample test that creates 500 widgets to profile in current browsers and see...
