### ISSUE TITLE
Resizing by borders, not the handle

### ISSUE THREAD

**Issue by MrMowji** [gridstack/gridstack.js#848]
## Subject of the idea
It would be more useful to let user resize items using their borders, instead of their handle. That way, there is no need to think about `rtl` options for this specific feature.

**Comment by radiolips** [comment]
Hey, @MrMowji . I'm unfamiliar with the issue you're insinuating - why is `rtl` an issue for this?

**Comment by MrMowji** [comment]
Hey @radiolips . When using `rtl` option for loading the `gridstack`, handles' position doesn't change. They stay at the **right-bottom** corner. As someone who works with rtl languages, it would be more user-friendly to let items grow from left-bottom corner too, or better, grow in four directions.

Actually gridstack's [rtl example](http://gridstackjs.com/demo/rtl.html) is not right.

**Comment by radiolips** [comment]
@MrMowji You can actually set where those appear, including the bottom left, but it should default to bottom left hwen you use rtl, definitely.

**Comment by MrMowji** [comment]
@radiolips Yes. But it's more about the functionality. The functionality of handles must move with them too, so we can grow items from left-bottom corner. I still recommend attaching handles to borders **and** corners :) Thanks.

**Comment by radiolips** [comment]
You can already extend widgets from the bottom-left. And from the left side, too! If that's all you're asking for, you can certainly do this already. ```$('.grid-stack').gridstack({
    resizable: {
        handles: 'e, se, s, sw, w'
    }
});```

**Comment by MrMowji** [comment]
@radiolips That's exactly what I wanted.

**Comment by radiolips** [comment]
🎉
