### ISSUE TITLE
how to get items in order they are sitting in the grid

### ISSUE THREAD

**Issue by belchandan** [gridstack/gridstack.js#849]
## Subject of the issue
Want to get items array in the order they are displaying, i.e. current position of all items to save those and reuse when load later.

Any suggestion please?

## Your environment
* version of gridstack.js = 0.3.0

**Comment by radiolips** [comment]
Hey, @belchandan . You can actually achieve this with basic Javascript. Attributes are set directly on the widgets. You can view the source of this example for more information: http://gridstackjs.com/demo/serialization.html

**Comment by belchandan** [comment]
thanks @radiolips for response and sharing demo, I found that and applied similar as well :-)
