### ISSUE TITLE
Resizing gives error: Uncaught Error: cannot call methods on draggable prior to initialization; attempted to call method 'disable'

### ISSUE THREAD

**Issue by JanRune** [gridstack/gridstack.js#851]
## Subject of the issue
When resizing with Chrome's toggle device toolbar, error appears in console:
"Uncaught Error: cannot call methods on draggable prior to initialization; attempted to call method 'disable'"
 GridStack.onResizeHandler (gridstack.js:642)

## Your environment
* gridstack.js 0.2.6
* Chrome

## Steps to reproduce
Resizing browser with toggle device toolbar (Chrome)

## Expected behaviour
No errors

## Actual behaviour
Console error

**Comment by radiolips** [comment]
Same as #858 .
