### ISSUE TITLE
draggingElement and placholder problem.

### ISSUE THREAD

**Issue by devginie** [gridstack/gridstack.js#853]
## Subject of the issue
When it is 'dropover', 'ui.draggable' element is hard to change.

## Your environment
* 1.0.0-dev of gridstack.js
* Chrome  64.0.3282.167(64bit)

## Steps to reproduce
1. A outer element drag into gridstack.
2. The 'dropover' event triggered.
3. Placeholder is calculated by handler.

## Expected behaviour
I want to use helper element as placeholder at 'dropover' event.

## Actual behaviour
Dropover event refer 'ui.draggable', (it is not helper element), for calculating placeholder size.

## My Solution
~~~javascript
// gridstack.js
// Line 960 ~
.on(self.container, 'dropover', function (event, ui) {
                    var offset = self.container.offset();
                    var el = $(ui.draggable);
                    var helper = $(ui.helper);  // Added code
                    ...
                    // Helper element fit to intent of developer.
                    var width = origNode ? origNode.width : (Math.ceil(helper.outerWidth() / cellWidth)); // Modified code
                    var height = origNode ? origNode.height : (Math.ceil(helper.outerHeight() / cellHeight)); // Modified code
                    ...
~~~

**Comment by radiolips** [comment]
@devginie What are you trying to do? I think we should be able to allow you to pass options to `dropover`, but I'm not positive that that's what you need.
