### ISSUE TITLE
Show Resize handler only when hovering on handler itself

### ISSUE THREAD

**Issue by WebPro9369** [gridstack/gridstack.js#856]
Hello, there.
I would like this feature:
Currently, resize handlers are visible whenever hovering on the grid, and can I show it only when hovering on handler(at the corner of grid) itself?
 
Thanks.

**Comment by radiolips** [comment]
Hey there, @WebPro9369 ! Yep, you can actually do this easily, with your own CSS. In a project I have, we set `.grid-stack > .grid-stack-item.ui-resizable-disabled > .ui-resizable-handle, .grid-stack > .grid-stack-item.ui-resizable-autohide > .ui-resizable-handle` to `display: none` and later change that `display` css attribute.
