### ISSUE TITLE
Set Header fixed in widget

### ISSUE THREAD

**Issue by sathis810** [gridstack/gridstack.js#857]
How to set widget Header as fixed and content can be scroll-able if exceeded the data-gs-height.

**Comment by radiolips** [comment]
Hi, @sathis810 ! Welcome to our unfortunately long list of open issues.

Regarding your own - you can do that with your own code with ease. You can create a div, as normal, and give it a header and body. Set a height and `overflow-y: scroll` on the body, and it should work as you'd like. It's nothing that's gridstack-specific.
