### ISSUE TITLE
Calling cellHeight(val) not update styles

### ISSUE THREAD

**Issue by jinich** [gridstack/gridstack.js#861]
## Subject of the issue
I faced this issue when using gridstack on develop branch: the grid didn't update it's styles when i called `cellHeight(val)` to update grid cell height, 

I checked`_updateStyles` function and this `if` statement always `true`:
```javascript
if (this._styles._max !== 0 && maxHeight <= this._styles._max) { // Keep this._styles._max increasing
  return ;
}
this._initStyles();
```
This is because  `this._initStyles()` was moved below that `if` check, as compared with gridstack v0.3.0:
```javascript
this._initStyles();
this._updateContainerHeight();
if (!this.opts.cellHeight) { // The rest will be handled by CSS
  return ;
}
if (this._styles._max !== 0 && maxHeight <= this._styles._max) {
  return ;
}
```
Was the ability to update cell height removed in v1.0.0?

## Environment
* version of gridstack.js: 1.0.0

**Comment by mxx-lxg** [comment]
Oh, damn. I hope this is a bug. I need this feature.

**Comment by radiolips** [comment]
@jinich can you provide an example? What styles aren't being applied?

**Comment by jinich** [comment]
Hi @radiolips, i created codepen demo for it:
* This demo use gridstack 0.3.0: https://codepen.io/jinich/pen/pLKzaG
* And this use gridstack on develop branch: https://codepen.io/jinich/pen/aYQWxR

When clicked Resize button, you can see that cellHeight(val) worked with gridstack 0.3.0, but it does not work with gridstack from develop branch

By saying styles aren't being applied, i meant `_updateStyles()` function has no affect.

**Comment by radiolips** [comment]
@jinich Thanks. I'll take a look.

**Comment by radiolips** [comment]
(Note: https://github.com/gridstack/gridstack.js/pull/672 is why this change was made. I've verified that in my own code I see the same problem. I'll try to resolve this while not breaking the initial fix).

**Comment by radiolips** [comment]
Great catch, @jinich . I don't have enough information right now to understand why that change was made initially. I'm reverting it. I'll try to understand why it was made and how we can better fix it, but, for now, setting `cellHeight` on-the-fly should work.
