### ISSUE TITLE
i need to resize widget to smallest height and weight than now.

### ISSUE THREAD

**Issue by mishavthomas** [gridstack/gridstack.js#863]
## Subject of the issue
i need to resize widget to smallest height and weight than now.

## Your environment
* version of gridstack.js:gridstack.js 0.2.5
* chrome

## Steps to reproduce
Tell us how to reproduce this issue. resize it to  min.then height is 60 amd width is 75.i need more lesser size
## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

**Comment by radiolips** [comment]
@mishavthomas gridstack is a cell-based system. You can make things smaller by modifying properties such as `cellHeight`.
