### ISSUE TITLE
Resizing Items causes other items to collaps

### ISSUE THREAD

**Issue by JHoerbst** [gridstack/gridstack.js#872]
## Subject of the issue
When i resize one of the item above the half of the height of the grid the other grid items collapses
![gridstack](https://user-images.githubusercontent.com/14820570/39582690-c7e698aa-4eee-11e8-8ac7-187dbcb2ded2.gif)

## Your environment
* 3.0
* Chrome 66

## Expected behaviour
Items should alway stay at the same position because of data-gs-locked
## Actual behaviour
Items arrange strangely in grid and overlay other items

**Comment by JHoerbst** [comment]
@radiolips https://jsfiddle.net/9pm38z47/1/
Here you go, thanks!

**Comment by radiolips** [comment]
Hey @JHoerbst  - Could you try using the dev branch and see if the 1.0-dev fixes it? I don't think it will, but it's possible.

**Comment by JHoerbst** [comment]
Doesn't change anything. Sorry.
Does maybe the array cause problems?

**Comment by JHoerbst** [comment]
Works now with v0.4

**Comment by radiolips** [comment]
@JHoerbst I just want to double check - when you say it works, do you mean that the problem is resolved, or do you mean that your issue still exists in 0.4?

**Comment by JHoerbst** [comment]
@radiolips The problem is resolved in 0.4! Thanks for the help.
