### ISSUE TITLE
Grid Items overlaps one another on resizing or reordering

### ISSUE THREAD

**Issue by 1995navinkumar** [gridstack/gridstack.js#879]
## Subject of the issue
Gridstack with more than 10 grid items causes overlapping on reordering or resizing 

## Your environment
* version of gridstack.js - 0.3.0

## Steps to reproduce
1) Add more than 10 widgets. 
2) Reorder the items such that only one widget is on top.
3) Now resize or reorder the top widget to see bottom widgets appear overlapping on top 
    Reproduce - https://jsfiddle.net/dweiss/dqyvh6vr/

## Expected behaviour
Widgets may maintain the position as it is. Should not overlap

**Comment by radiolips** [comment]
@1995navinkumar can you try this with the dev branch? I believe a bug was fixed there that will resolve this for you.

**Comment by 1995navinkumar** [comment]
Thanks radiolips. It is working fine now. Will test it and update the same

**Comment by 1995navinkumar** [comment]
BTW, Any update on #876 ? about jQuery version change
