### ISSUE TITLE
Widget with locked,no-move,no-resize set true is still moved by other widgets

### ISSUE THREAD

**Issue by 1995navinkumar** [gridstack/gridstack.js#882]
## Subject of the issue
A grid-item supplied with attributes "data-gs-locked=true data-gs-no-move=true data-gs-no-resize=true" is still moved by other widgets when dragged on top of it. 

## Your environment
* version of gridstack.js - 0.3

## Steps to reproduce
Drag the first widget on *top* of the second widget (locked) 
Use this fiddle - https://jsfiddle.net/dqyvh6vr/30/

## Expected behaviour
The position of the locked widget should not change . It should be locked

## Actual behaviour
Position changes only when other widget is dragged on top of it.

**Comment by radiolips** [comment]
Fixed in new `1.0.0-dev`.

**Comment by SoulesteDev** [comment]
I'm encountering this issue. Setting "yes" on all sibling widgets in dragstart, then setting to "no" in dragstop. It is setting them, however they are not working, they can still be pushed around when dragging the current widget over them...

Here is a link to my codepen where I am encountering this issue: https://codepen.io/Souleste/pen/wvvpGbE
