### ISSUE TITLE
Responsive behavior

### ISSUE THREAD

**Issue by nicoesiea** [gridstack/gridstack.js#886]
## Responsive behavior
As fare as I know, the responsive behavior is working on three different possible actions:
- Reduce the font size
- Show or hide component
- Reorganize the div in the page.

In order to manage the last point, I'm using bootstrap but this library, used for the widget layout, does not work like that. Only the minimal width, where the widgets are on top of each other, is working...

Is it possible to manage the behavior with more precision? I mean, how to accept to resize the layout in order to force my widgets to be both per line when I reduce the page width. And then, when the page width start to be very small, here the widget layout start to be on top of each others.

## Your environment
* "angular-gridstack": "^1.0.0",
* "gridstack": "^0.3.0"

## Steps to reproduce
Reduce the page with, or load the page on another device with smaller resolution. By my side, the result is forced to be as defined, OR at one point, each element are on top of each others.
 
## Expected behaviour
Manage the different page widths to be able to accepte, for example, two elements per line, and then, when the page width start to be very very small, then switch to only one element on top of each others.

## Actual behaviour
If I reduce the page width, the elements stay as defined. The pattern stays like that during a very long time when finally they are reorganized to be display the on on top of each others.

**Comment by nicoesiea** [comment]
Hello,
I discovered https://packery.metafizzy.co, it seems to work like expected with this one...
Nobody able to help me?
Regards,
Nicolas

**Comment by radiolips** [comment]
I have not heard of the library you linked to, but you may certainly use it. I do not think that it has a responsive mode, so I don't think you'll be successful in doing what you're trying to do.

Using gridstack.js normally will allow for a transition to a single column mode. The responsive mode doesn't work too well yet, but we have plans to enhance it. This bug has been reported in #520 .
