### ISSUE TITLE
How to add MVC partialview as widgets and save the layout?

### ISSUE THREAD

**Issue by jimmathew999** [gridstack/gridstack.js#888]
## Subject of the issue
I'm trying to build and application similar to this http://mvc.jdash.net/dashboard/index/2134
I've tried GridStack.js and its amazing which meets my requirment. I was able to store the layouts in localstorage and load from it. My requirement is how can i add multiple widgets (for eg: weather, calendar etc etc..) using ASP.net mvc/webform and save it.
What is the best approach. Please direct to a sample if anything available.
Thanks

## Your environment
* version of gridstack.js - gridstack.js 0.4.0
* which browser and its version - Chrome

## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://jsfiddle.net/dweiss/dqyvh6vr/) as a base.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

**Comment by jimmathew999** [comment]
Thanks for your response.
1. I have multiple DIV's with id. on save i want to save  id of each div and load each div based on saved id. How can i achieve it? currently i am saving whole html content which is not good for dynamic db 
 contents. 
Each div is a ASP.NET MVC  partial view.

2. I tried " id : el.attr('data-custom-id')" but no luck. What is that "data-custom-id"?

3. or Is there any other way to Save and Load ASP.NET MVC partial views?

**Comment by radiolips** [comment]
@jimmathew999 How do you mean? In my project, I save off meta data about widgets such that they can be fully recreated at a later time. Any time there's a change, I push the changed widgets to MySQL. Is that what you're trying to do?
