### ISSUE TITLE
Resize widget

### ISSUE THREAD

**Issue by Leoluch** [gridstack/gridstack.js#897]
## Subject of the issue
I don't know if it's possible to block the width of cell instead of block the numbero of columns.

## Your environment
Laste gridsize version
Any rowser

## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://jsfiddle.net/dweiss/dqyvh6vr/) as a base.

## Expected behaviour
I want to block the width of every widget and the number of columns change automatically

## Actual behaviour
Tell us what happens instead

**Comment by Leoluch** [comment]
i mean that if i set 100 px of grid stack item i want that it modify columns and not resize the items

**Comment by radiolips** [comment]
Could you provide an example?
