### ISSUE TITLE
Update grid Options (Is it possible?)

### ISSUE THREAD

**Issue by Jokenbol** [gridstack/gridstack.js#898]
## Subject of the issue
Hi. I'm trying to update the grid options. First I create a grid with the disableDrag and disableResize options set to true. Then I want to change the options so that the grid will be draggable and resizable.

## Your environment
* version of gridstack.js : 0.3.0
* which browser and its version : chrome version 66.0.3359.181

## Steps to reproduce
(https://jsfiddle.net/jokenbol/6ej6x7hq/2/) 

## Expected behaviour
I want to change the options so that the grid will be draggable and resizable after the grid has previously been set to non-draggable and non-resizable

## Actual behaviour
The state doesn't change even if options have changed.

Thank you.

**Comment by Jokenbol** [comment]
I find the answer. At least it's working for me. I use [this](https://github.com/gridstack/gridstack.js/tree/master/doc#enable) function to make each element with class (.grid-stack-item) movable or not movable.
`$('.grid-stack').data('gridstack').movable('.grid-stack-item', true);`
`$('.grid-stack').data('gridstack').resizable('.grid-stack-item', true);`

Exemple here : https://jsfiddle.net/jokenbol/6ej6x7hq/3/

**Comment by radiolips** [comment]
Hey, @Jokenbol ! It depends on how you disable the grid. The grid itself can be completely frozen/unfrozen, or you can deal with individual elements. It sounds like you may have done it with individual elements, as your update to make everything moveable and resizable are based on individual elements. Glad you were able to get it worked out!
