### ISSUE TITLE
aspectRatio question

### ISSUE THREAD

**Issue by alexwel** [gridstack/gridstack.js#899]
Setting resizable: { aspectRatio: "true" } sets it for all tiles in the grid; however, I can't figure out how to set this for only one of the tiles/widgets is this posible?.

**Comment by alexwel** [comment]
problem solvd

```
$(function () {

  $('#resize').resizable({
      aspectRatio: 1859/465, 
  });

    var options = {
        height:0,
        cellHeight: '1px',
        resizable:{
               
            },
        verticalMargin: 0,
    };
    $('.grid-stack').gridstack(options);
});
```

**Comment by radiolips** [comment]
Great! Glad you were able to solve that. Please feel free to log another ticket if you have any more issues.
