### ISSUE TITLE
Unable to move a widget at the bottom between two grid

### ISSUE THREAD

**Issue by ausonduweb** [gridstack/gridstack.js#900]
## Subject of the issue
Unable to move a widget at the bottom between two grid

## Your environment
* All
* Chrome

## Steps to reproduce
http://gridstackjs.com/demo/two.html
Take one widget on the left grid and try to move it under the last widget og the right grid.

## Expected behaviour
It must be add a the p:aceholder under the last element

## Actual behaviour
Nothing

**Comment by adumesny** [comment]
a little tricky because when you drop below grid B you are not dropping to that grid (from grid A) - how would we know you meant to grow and not just not drop on B ? Moving any objects inside a grid WILL grow that grid just fine...

**Comment by adumesny** [comment]
possible but very finicky (like there is only a few pixels letting you do it. related to #1094 
![image](https://user-images.githubusercontent.com/3496166/71309670-93959180-23bf-11ea-8a0f-ba2b5ba9d32a.png)

**Comment by adumesny** [comment]
closing as dup
