### ISSUE TITLE
How to use GridStackUI.Utils.sort(nodes[, dir[, width]])

### ISSUE THREAD

**Issue by dhruvangg** [gridstack/gridstack.js#902]
Any Use of GridStackUI.Utils.sort(nodes[, dir[, width]]) or any example related this..

**Comment by Jokenbol** [comment]
Exemple here : https://codepen.io/delagics/pen/ezgryg
I am not the auhor but it help me. Line 14 of the JS file. 

The only thing it does is that it put all the nodes you specified in the order you want.
In the exemple : 
{ "id": "title", "x": 0, "y": 0, "width": 8, "height": 1 }, 
{ "id": "slug", "x": 8, "y": 0, "width": 4, "height": 1 }, 
{ "id": "content", "x": 0, "y": 1, "width": 8, "height": 1 }, 
**{ "id": "time", "x": 0, "y": 2, "width": 12, "height": 1 }**, 
_{ "id": "date", "x": 8, "y": 1, "width": 4, "height": 1 }_

became

{ "id": "title", "x": 0, "y": 0, "width": 8, "height": 1 }, 
{ "id": "slug", "x": 8, "y": 0, "width": 4, "height": 1 }, 
{ "id": "content", "x": 0, "y": 1, "width": 8, "height": 1 },
_{ "id": "date", "x": 8, "y": 1, "width": 4, "height": 1 }_,
**{ "id": "time", "x": 0, "y": 2, "width": 12, "height": 1 }**

You can read the doc for more info : https://github.com/gridstack/gridstack.js/tree/develop/doc#gridstackuiutilssortnodes-dir-width
