### ISSUE TITLE
addWidget doesn't accept value more than 5 for data-gs-x

### ISSUE THREAD

**Issue by luicephillips** [gridstack/gridstack.js#904]
Here is my code

var i;

var x = 0, y = 0;

for (i = 0; i <= array.length; i++) {
  **grid.addWidget($('<div>'+array[i][0].outerHTML+'</div>'), x, y, null, 2, false);**

   x++;
  if(x > 7){
     y+=2;
     x = 0;
  }
}

**Comment by dhruvangg** [comment]
yes, I have facing same problem. X not increment after 5
