### ISSUE TITLE
How to animate each item?

### ISSUE THREAD

**Issue by eeldivad** [gridstack/gridstack.js#905]
I see on the homepage of gridstack, the animation is smooth when dragging the items around.  The items even move around the item I'm dragging smoothly.  But when I try the samples, none of them are animating.  I saw in the doc to set the options for animate = true, so I did that and now the item I'm dragging animates smoothly but the items around the dragged item doesn't animate like it does on the home page.

Here's the only change I did on the serialization sample page for animation.  Is there another option somewhere I need to set for each item?  Can someone show me how to do it right on a serialization sample page?
    var options = {
        animate: true
    };
    $('.grid-stack').gridstack(options);

## Your environment
* 1.0.0-dev version of gridstack.js
* chrome 66.0.3359.181

## Steps to reproduce
https://github.com/gridstack/gridstack.js/blob/develop/demo/serialization.html

## Expected behaviour
It should animate all items smoothly around the dragged item just like it does on gridstackjs.com homepage

## Actual behaviour
The dragged item animates into position, but the items around them do not smoothly transition into new positions around dragged item.  They move into position abruptly in the same.  This happens even though I set animate option to true

**Comment by mrpia** [comment]
see #876, maybe this helps you?

I've noticed gridstack 0.4.0 breaks animations in my case
also jquery 3.3.x plus gridstack 0.3.0 animations broken (but this time only in chrome/firefox)

so my current setup is gridstack 0.3.0 + jquery 3.2.1

**Comment by eeldivad** [comment]
@mrpia Thanks I guess this is a duplicate issue so I'll close it and use other one
