### ISSUE TITLE
willItFit doesn't Work

### ISSUE THREAD

**Issue by Kingmaddi** [gridstack/gridstack.js#906]
## Subject of the issue
Since I updated to lodash 4.* the willItFit function says, there is no more free space in the grid. But it is.

## Your environment
*  Gridstack 0.4
* Safari 11.1

## Expected behaviour
willItFit function should return true or false, then there is / is not free space in the grid for a new element.

## Actual behaviour
There is always a false return from the function.

**Comment by radiolips** [comment]
@Kingmaddi I'm closing this because we've removed the lodash dependency, so this function presumably works again. Please reopen if I'm incorrect.
