### ISSUE TITLE
(Suggestion) addWidget to accept object instead of bunch of parameters

### ISSUE THREAD

**Issue by n1ghtie** [gridstack/gridstack.js#907]
Hi, first of all THANK YOU for amazing plugin, loving it so far.
Working on a project that allows to create custom dashboards and need to create widgets dynamically (grid-stack-items).
I would be great that instead of putting each parameters separately, maybe to do an object so addWidget would look like this?

```javascript
var options = {
    x: 10,
    y: 10,
    width: 5,
    height: 5,
    ...
}
addWidget(el, options);
```
Why? Well lets say that if i want to have min-height, with current structure I need to supply min-width and max-width, and i don't really want that.

**Comment by kylehovey** [comment]
In the mean time, here is a snippet that I use in my code:

```javascript
const genId = () => Math.random().toString(36).substr(2, 9);

const widget = stack => ({
  id = genId(),
  element,
  xPos = 0,
  yPos = 0,
  width = 1,
  height = 1,
  minWidth = 0,
  maxWidth = 10,
  minHeight = 0,
  maxHeight = 10,
  autoPos = false
} = {}) => stack.addWidget(
  element,
  xPos,
  yPos,
  width,
  height,
  autoPos,
  minWidth,
  maxWidth,
  minHeight,
  maxHeight,
  id
);
```

**Comment by adumesny** [comment]
@n1ghtie I agree. We should add it soon.

**Comment by adumesny** [comment]
in the upcoming 0.5.2 release
