### ISSUE TITLE
el.el.context = undefined

### ISSUE THREAD

**Issue by filmtablette** [gridstack/gridstack.js#908]
## Subject of the issue

I have three widgets in the grid and after the user have moved them around and clicks "save," I iterate over the widgets and collect data, saved in el, like position, height, etc. I also get the style-data of every widget, stored in el.el.context
`gsHeadingMedia : $.map(gridItemsHeadMedia, function(el,k){
                            return {
									x: el.x,
									y: el.y,
									width: el.width,
									height: el.height,
									id: el.id,
									HeadingMediaBgStyle: el.el.context.childNodes[1].attributes["style"].nodeValue
									};
							}),`

This works well. But when I am adding a new widget, **the ["0"].el.context of the newly added widget is undefined.**

`var grid = $('.col-sm-9').find('.active-slide').find('.grid-stack').eq(2);
if ($(grid).hasClass('three-columns')) {
grid.data('gridstack').addWidget($('<div><div class="gridstack-panel-heading"><span class="three-columns-close-widget dashicons dashicons-no-alt"></span></div><div class="grid-stack-item-content" style="background-image: url(http://localhost/wordpress_494/wp-content/uploads/2018/04/Nord-Sued-Male-Atoll_header_1_1316594614.jpg); background-position: 50% 50%;background-size: cover;"><i class="gs-media-trash dashicons dashicons-trash" style="margin: 4px 3px 0px 0px;"></i><i class="gs-media-camera dashicons dashicons-camera"></i></div></div>'), null, null, 1, 1, true, null, null, null, null, null);
}`

Any help is appreciated.

## Your environment
* version of gridstack.js 1.0.0-dev
* which browser and its version chrome Version 66.0.3359.181 (Offizieller Build) (64-Bit)

## Expected behavior
the ["0"].el.context of the newly added widget should not be undefined.

## Actual behavior
the ["0"].el.context of the newly added widget is undefined

**Comment by radiolips** [comment]
@filmtablette do you have a fiddle I could look at? I know this response is very late, but I'd like to help you out.

**Comment by adumesny** [comment]
closing due to no response. re-open if you do still have issue.
