### ISSUE TITLE
Move widget to a grid bellow

### ISSUE THREAD

**Issue by danirueda** [gridstack/gridstack.js#909]
## Subject of the issue
In the [two grids demo](http://gridstackjs.com/demo/two.html) you can move widgets from a grid to other.
Now I'm working with various grids I realize you can move widgets between grids form left to right, right to left, bottom up but... Form a grid to other grid that is bellow you can but the moved widgets don't work after that. Is there any way to fix this?

## Your environment
* version of gridstack.js 0.4.0
* Any browser.

## Steps to reproduce
You can take the [two grids demo](http://gridstackjs.com/demo/two.html) and change the Bootstrap col-md-6 to row.

**Comment by radiolips** [comment]
Just to confirm–you're saying that if you have two grids as so:
A
B
...you cannot move a widget from grid A to grid B. You can, however, move from B to A. Is that correct?

**Comment by danirueda** [comment]
That is!!! Because of the dynamic grid height. If you set a concrete height you can. But if you put height: 0 you won't be able.

**Comment by JamesFitch3** [comment]
I was able to mitigate this somewhat by enclosing the top stack in a div which had enough bottom margin to accommodate the inner gridstack gaining a row without moving the lower one.  Gridstack seems to get confused when its TOP changes midway through a drag, and then difficult-to-predict results come about.

**Comment by adumesny** [comment]
@danirueda unlikely to get fixed given the workarounds (you can use `maxRown` or CSS to limit height, or use @JamesFitch3 margin trick (which won't work for `float: true` case as that grows indefinitely in height).

keeping open for others to find.
