### ISSUE TITLE
Question : avoid reordering of the widget when deleting

### ISSUE THREAD

**Issue by edirectorios** [gridstack/gridstack.js#912]
## Subject of the issue
I'm trying to specify the gridstack as a template fo printing purposes.
After adding the widgets i wonder if there is a way to avoid that after deleting one of the intermediate widgets all the widgets bellow comes up.

Regards

**Comment by radiolips** [comment]
https://github.com/gridstack/gridstack.js/tree/develop/doc#grid-attributes `float` allows widgets to "float" in space rather than go up-left. I think this is what you're looking for.
