### ISSUE TITLE
How to change the default width and height of grid stack placeholder?

### ISSUE THREAD

**Issue by jun1432** [gridstack/gridstack.js#914]
I'm referring to the dashed line when your dragging a widget.

**Comment by jun1432** [comment]
The below instance. The default value for now is data-gs-width="2" and data-gs-height="3". I want to change this to value. I'm thinking of having the value of grid stack item.

.grid-stack>.grid-stack-item[data-gs-width='2']

**Comment by jun1432** [comment]
Hi Guys,

For more info on the issue, below is a screenshot on the element that has this default value that I want to change.

http://www.screencast.com/t/OV3B53WBS

**Comment by radiolips** [comment]
The value is the size of the widget. What are you trying to change it to?

**Comment by jun1432** [comment]
I want to change the default value of data-gs-width="6" and data-gs-height="4"

**Comment by radiolips** [comment]
Those values are set to that because they're the values of the widget you're moving. The placeholder will always reflect the size of the widget.

**Comment by jun1432** [comment]
Thanks @radiolips.

**Comment by ygalanter** [comment]
Maybe related - how to change the granularity of "snap to" when resizing a widget?

**Comment by Hedva** [comment]
> Those values are set to that because they're the values of the widget you're moving. The placeholder will always reflect the size of the widget.

@radiolips That doesn't seem true when you use the 'sidebar' of [Two Grid Demo](http://gridstackjs.com/demo/two.html)

How can you change the size in that case?

**Comment by ermcgrat** [comment]
@Hedva Also curious about this. That "drag me" item doesn't have any sizes specified, but becomes a 2x2 when dropping into either grid.

**Comment by ermcgrat** [comment]
Given that sidebar example of the two grid demo, I'm wondering if it is possible to achieve something similar to the Azure Portal. That is, the widget that you start dragging could be a different size than what it occupies in a grid. For example, all of the items are 1x1 in the sidebar but occupy something larger in the grid. Here is a screenshot for example, notice how the Clock item while being dragged occupies 2x2 on the grid, even though its ghosted image is smaller.

https://i.imgur.com/w2YrcmB.png

**Comment by lauantai** [comment]
We do this in our application. It’s entirely possible, but I’m on vacation
so I have no way to access our code. I kind of remember we do the resizing
on the gridstack ‘change’ event, when the widget is added to the grid.
Sorry for the vague answer 😅

**Comment by Hedva** [comment]
@lauantai I would be really grateful if you can provide an example in the near featuer. Can't figure it out yet

**Comment by adumesny** [comment]
closing as dup of #413
