### ISSUE TITLE
Is there a way to track the changes of width and height before and after a widget is resized?

### ISSUE THREAD

**Issue by jun1432** [gridstack/gridstack.js#915]
1. I'm trying to check the available data but I couldn't find maybe I'm not checking the right data. I want to have it like the x and y value while dragging that I could check the _beforeDragX and _beforeDragY.
I want to check the value of width and height before resize and compare it to the value after resize.

2. I also notice that the node x and y values are not the same when I try to drag the widget outside the grid even though it reverted back to its original position. Kindly enlighten me on this.

http://www.screencast.com/t/Yiu59m8lnkU

**Comment by kstan79** [comment]
You may refer ticket #757

**Comment by adumesny** [comment]
please use upcoming 0.6.4 release. `change` event will send the node which has the current x.y.width,height as well as the original values (see _origX, etc...)
I use that internally to decide what actually changed before calling the event.
