### ISSUE TITLE
Possible bug

### ISSUE THREAD

**Issue by jun1432** [gridstack/gridstack.js#916]
I just checked it on console the value for x and y when dragging a widget [_gridstacknode]. But I notice that when I try to drag the widget out of the grid it revert back animate to its original position but the value outputted on the console doesn't seem right. Check below screenshot.

http://www.screencast.com/t/paoFHtco1Yq

**Comment by adumesny** [comment]
can you please provide an example ? see https://jsfiddle.net/adumesny/jqhkry7g

**Comment by adumesny** [comment]
closing due to no reply
