### ISSUE TITLE
Link on gridstackjs.com that points to gridster.net is redirecting to a malware site

### ISSUE THREAD

**Issue by JQProgrammer** [gridstack/gridstack.js#917]
## Subject of the issue
Please update your site so that it does not backlink to a malware site.

## Your environment
*  All browsers

## Steps to reproduce
Navigate to gridstackjs.com and click "Inspired by gridster.js" link.

## Expected behaviour
Should take you to their gitHub page.

## Actual behaviour
Sends your browser to a malicious malware site.

**Comment by radiolips** [comment]
Yeah, I saw that, thanks. The internet is a wild world. I'll leave this open until it's removed.

**Comment by adumesny** [comment]
we should fix this soon! @radiolips please point me to website location/account info. Might as well add a "More Demo" to the samples we have as well as those are pretty hidden on github readme.
