### ISSUE TITLE
how to use in angular or jhipster

### ISSUE THREAD

**Issue by PratikBali** [gridstack/gridstack.js#923]
## Subject of the issue
Describe your issue here.

## Your environment
* version of gridstack.js
* which browser and its version

## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://jsfiddle.net/dweiss/dqyvh6vr/) as a base.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

**Comment by MikeGsus** [comment]
Maybe [this](https://github.com/gridstack/gridstack.js#gridstackjs-for-specific-frameworks) could help you.

**Comment by radiolips** [comment]
Thanks @MikeGsus . Yeah, I don't maintain the angular repo, but if you've got questions about it, I'd head over there. If that doesn't work, feel free to reopen this or open a new issue. Wish I could help, but I don't have the direct experience.

**Comment by weedkiller** [comment]
this needs to be revisted on how to get it into angular

**Comment by adumesny** [comment]
@weedkiller see #1590 - you can use the React/Vue as general helper and look for angular Q on slack in the meantime. too many things to do, so little help or support...
