### ISSUE TITLE
WYSIWYG Export

### ISSUE THREAD

**Issue by lwwells** [gridstack/gridstack.js#926]
## Subject of the issue
Export possibilities for gridstack items

## Your environment
* 0.2.6
* Chrome

## Steps to reproduce
I have build a dashboarding tool using gridstack, and now I need to be able to export the dashboard to PDF or Word, WYSIWYG.  Have you done any experimenting with exports like this?

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

**Comment by blubbll** [comment]
simply clone the innerHTML and add stylesheet-sugar?
You could also just canvas-screenshot the content :P

**Comment by radiolips** [comment]
I think these are suitable answers. There's a variety of ways to export it, but it'd be just like exporting any other HTML.
