### ISSUE TITLE
gridstack doesn't play nice with Parcel

### ISSUE THREAD

**Issue by omayhemo** [gridstack/gridstack.js#929]
## Subject of the issue
Using Parcel, gridstackjs fails to initialize.

## Your environment
npm latest
all major desktop browsers tested

## Steps to reproduce
I started a simple project that has a single index.html and a single index.js.  I pulled in gridstack and sass flexbox grid with npm and ran parcel index.html

Check out the entire project.
[parcel_with_gridstack.zip](https://github.com/gridstack/gridstack.js/files/2250048/parcel_with_gridstack.zip)

## Expected behaviour
I expect parcel server to serve the index.html and to have two working widgets in gridstack.

## Actual behaviour
Looks like the styles are being applied but that gridstack.js is not working on the elements.  I receive no errors in the console.

From the get go, I found it difficult to get gridstack to work at all, it was throwing errors about it's requires.

**Comment by adumesny** [comment]
hopefully you found a solution... I don't know anything about parcel, and your 5500 files gzip is a lot to digest :(
keep in mind the jquery and jqeury-ui requirements (see doc). I have no issues using with Angular 8 for example...
