### ISSUE TITLE
The iframe is placed inside the control of gridstack

### ISSUE THREAD

**Issue by quzefeng** [gridstack/gridstack.js#931]
Hello
The iframe is placed inside the control of gridstack. The control inside the iframe can be clicked and the corresponding event can not be clicked now. How can I achieve this function?

**Comment by adumesny** [comment]
late response, but can you provide code sample (ex: https://jsfiddle.net/adumesny/jqhkry7g/) ? thank you.

**Comment by adumesny** [comment]
closing due to no response
