### ISSUE TITLE
'resizestop' event not catching current 'data-gs-height'

### ISSUE THREAD

**Issue by spitzbubchen** [gridstack/gridstack.js#932]
I am using the latest version of gridstack and it seems that:

    $(document).on('resizestop', '.grid-stack-item', function() {
	     console.log($(this).attr('data-gs-height'))
    });

catches the old 'data-gs-height'

**Comment by kstan79** [comment]
refer thus #757

**Comment by adumesny** [comment]
refer #829

**Comment by adumesny** [comment]
fixed as you can see https://gridstackjs.com/demo/float.html in console the resizestop has the right gs-w attr
(which is separate from having the final animation width/height dom sizing)
