### ISSUE TITLE
Fast resizeing stops, when widget contain iframe

### ISSUE THREAD

**Issue by bendada3** [gridstack/gridstack.js#934]
Hi,
I have iframe in my widget. When I fastly resize widget, mouse moves and hover iframe and resizeing stop. So I cant fastly resize widget, I have to resize slowly and keep mouse on resize btn. Is there any way how to fix it please?

Thank you
Daniel

**Comment by kamleshKumarVerma** [comment]
Added this CSS $('iframe').css('pointer-events','none'); in resizeStart event and add this $('iframe').css('pointer-events','auto'); in resizeStop event.
it will work. i have tested that
