### ISSUE TITLE
Disappearing grid items

### ISSUE THREAD

**Issue by ermcgrat** [gridstack/gridstack.js#935]
In the two-grid example, it is easy to make all of the elements in the two grids start disappearing by simply re-positioning them.

Go to the official demo to try: http://gridstackjs.com/demo/two.html
This happens in Chrome, Firefox, Edge, etc

On the two-grid demo:
1) Change the position of an existing item in the first grid. Keep it in the first grid. (Example, move the first 2x2 green block to the right one unit)
2) Change the position of an existing item in the second grid. Keep it in the second grid. (Example, move the 2x2 gray block to the right one unit)
3) Change the position of an existing item in the first grid again. Notice how the placeholder is no longer following the dragged item. (Example, move the first 2x2 green block back to the left one unit)
4) Move any OTHER existing item from either of the two grids. (Example, move the 2x2 gray block to the left one unite). The last block that you moved will now disappear. It is removed from the dom, but seems to occupy "space" internally to the grid. 

If you keep alternating between the two grids while just re-arranging items within them (not moving items from one grid to another) you will continue to lose grid items. 

Re-arranging items shouldn't cause other items to be removed.

If this isn't clear enough I can record a video and upload to Youtube. I'm not sure how to better explain it.

**Comment by airflyer13** [comment]
Can confirm this bug in Safari 11.1.1

**Comment by ermcgrat** [comment]
Apparently this was already reported:

https://github.com/gridstack/gridstack.js/issues/451

I'm not sure why that ticket was closed if it is still an issue.

**Comment by samisin** [comment]
It seems to happen for me when there is a fixed height. If I remove fixed height, no more disappearing acts.

**Comment by ADobrianskiy** [comment]
Any news about the issue?

**Comment by Altraya** [comment]
I have the same issue when I get back an item from JSON file (so I use make method for the item), after that, when I drag and drop an item into the grid, I have a strange behavior. 
I can move the item into the grid, but all other item react like the first one was always at the previous place.

**Comment by radiolips** [comment]
@ermcgrat This should be resolved in the `develop` branch and will be included in the next release.
