### ISSUE TITLE
Issue on droppable area grid

### ISSUE THREAD

**Issue by jun1432** [gridstack/gridstack.js#940]
Setup:
I'm using "1.0.0-dev" from the develop branch.

I have a column for the plugin/widget that I will drag onto the grid, so basically I use the jQueryUI for droppable and draggable.

Just discovered an issue while resizing and dragging of items around and after awhile trying to drag another into the grid generates and error "Uncaught TypeError: Cannot set property '_grid of undefined" line 933 "node._grid = self;". Screenshot is attached.

Also the "ui-draggable-handle" sticks on the grid with additional class named "ui-draggable-dragging" but when you check on the html structure it is outside of the "grid-stack" a direct child element of the body tag.

http://www.screencast.com/t/snK9VR1C442
http://www.screencast.com/t/4uA3puFku

Thanks and more power.

**Comment by jun1432** [comment]
Still trying to fixed this issue. "ui-draggable-dragging" sticks to its 'parent' element set up through containment: 'parent' and changed the appendTo option to '.grid-stack' instead of the 'body' tag.

Set up:
1. A slide in elements that holds all the draggables
2. The droppable grid which accepts the draggables.

Is there anyone that experienced this kind of behavior?

**Comment by jun1432** [comment]
Just an update on this issue. Issue is still recurring, issue occurred every after dragging of widget.

**Comment by kimwiii** [comment]
This issue also happen to me. Hope this will be fixed soon.

**Comment by jun1432** [comment]
@kimwiii,

Kindly explain your set up. Give us the picture or explain your use case.

I just fixed mine by not making the second grid position fixed on a slide in animation on top of the active grid.
