### ISSUE TITLE
Resizing a card messes the whole Layout

### ISSUE THREAD

**Issue by rwankar** [gridstack/gridstack.js#949]
## Subject of the issue
Resizing a card causes the layout to mess up.

## Your environment
* gridstack 0.3.0
* Google Chrome 70.0.3538.77

## Steps to reproduce
Open https://jsfiddle.net/atharva1/jh967t2b/1/
1. From Settings choose the layout with output to the right and then increase the size of the output as much as possible.
2. Increase width of topmost card (drag to the right)

## Expected behaviour
Just the width of the topmost card should increase.

## Actual behaviour
You will see that the card 4 jumps behind the topmost card.

**Comment by rwankar** [comment]
I understand this is an Open Source, Free for use project and I can't expect instant responses. But is this being actively maintained? I haven't seen a response for almost a month now.

**Comment by radiolips** [comment]
Hey @rwankar – sorry for the delay in response time. Are you seeing this issue in the demos? Without spending too much time digging into the fiddle, I would guess that there's something going on with the CSS.
