### ISSUE TITLE
Load Nested gridstacks programmatically

### ISSUE THREAD

**Issue by indriemarius** [gridstack/gridstack.js#95]
I saw that the changes for issue #53 enable the support of nested stacks.

My question would be how to add child widgets programmatically to the parent item  ? Can it be done using the current code, or are some changes required ? I tried using the add_widget method but the whole stack behaves as a single item.

I am trying to load the grid from the localstorage from a previous save.

**Comment by abologna-r7** [comment]
Interesting question. My guess is that we should be able to add widgets and group them, and gridStack should be able to make those group nested widgets...

```
var grid = $('#myGrid').grid(options).data('gridstack');

grid.add_widget(el, 0, 0, 1, 1, true, 'group_1')
```

**Comment by davidwieler** [comment]
Any updates on this? I would love to be able to add a nested widget.

**Comment by derekm** [comment]
@davidwieler - your JSFiddle "Result" viewport is falling below gridstack's collapse-to-mobile min_width threshold (768 pixels), so the grid is reverting to single-column mode. (See GridStack.prototype._is_one_column_mode() at line 600 of gridstack.js.)

**Comment by davidwieler** [comment]
I thought that too, but I honestly believe the problem is that the only way (so far) to nest a grid is to add a new "grid-stack" element, then run the function again.

Simply adding a "grid-stack-item", or appending one, doesn't work.

**Comment by StevenFlecha** [comment]
Anybody have any progress on this?

I tried to accomplish this by adding a widget with inside the widget:
`<div>
<div class="grid-stack-item-content">
<div class="sub" data-gs-x="0" data-gs-y="0" data-gs-width="12" data-gs-height="3" data-gs-min-height="2" > test</div>
</div>
</div>
`

then do:
`$('.sub').each(function(i,el){
	grid.makeWidget(el);	
/})`

but thats not working.. have a few other ideas to see if those work

**Comment by bravebox** [comment]
Hi, this is how far I got:
http://codepen.io/bravebox/pen/QdEEBd/

Im making a dashboard similar to the example above. I managed to create a nested gridstack with js. 

I make custom selectors for all just to try it out. But the nested items are not placed / do not drag/drop correctly. There seems to be a space above the first item which I can't find anywhere...

**Comment by michaellwatson** [comment]
Putting this hear in case anyone needs it, adding nested widgets
https://codepen.io/michaellwatson/pen/EvGEgM

**Comment by adumesny** [comment]
bummer, as I'm gonna need to nest grids sometimes soon, and dynamically... didn't look past the nested demo yet.

**Comment by adumesny** [comment]
working fine in current build - see #1106 nested.html
