### ISSUE TITLE
how to Change Gridstack column width in JavaScript

### ISSUE THREAD

**Issue by singhrajbeer** [gridstack/gridstack.js#951]
## Subject of the issue
I want to change Grid Column width in java script or jQuery

## Your environment
* version of gridstack.js
* which browser and its version

## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://jsfiddle.net/dweiss/dqyvh6vr/) as a base.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

**Comment by aamir1754** [comment]
Hi, you can add custom height or width to boxes while creating them, as shown below code

  var grid = $('.grid-stack').data('gridstack');

      grid.addWidget($(html), 0, 0, 3, 1, false);


in grid.AddWidget first parameter is for custom html which you want to add. 2nd paramter indicates box position in x-axis. 3rd parameter indicates box position in y-axis. 4th paramter indicates the width of box, with this paramter you can set width which you want, it can be set from 1 to 12. 5th parameter indicates the height of box which you can set from 1 to 12

**Comment by sociablesasha** [comment]
It can be handled by a function in the built-in gridstack.

**Comment by radiolips** [comment]
@singhrajbeer thanks for using gridstack and logging an issue. Are you trying to change the number of columns, or are you trying to change the width of a widget?

**Comment by singhrajbeer** [comment]
> @singhrajbeer thanks for using gridstack and logging an issue. Are you trying to change the number of columns, or are you trying to change the width of a widget?

Here I am trying to change the width of a grid column ?  I am using 12 column grid system.

**Comment by radiolips** [comment]
I'm a little confused. The width of the actual grid column is automatic based on its container. Each column will be 1/12 the allowed size. If you want to change the actual number of columns, you can use 
https://github.com/gridstack//gridstack.js#change-grid-width
