### ISSUE TITLE
How can I save and restore drag position ?

### ISSUE THREAD

**Issue by nsgalib** [gridstack/gridstack.js#953]
## Subject of the issue
Describe your issue here.

## Your environment
* version of gridstack.js
* which browser and its version

## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://jsfiddle.net/dweiss/dqyvh6vr/) as a base.

## Expected behaviour
Tell us what should happen

## Actual behaviour
Tell us what happens instead

**Comment by radiolips** [comment]
The community and I would be happy to try to help, but you didn't provide any description of what it is you're trying to do.
