### ISSUE TITLE
 A few questions about functionality...

### ISSUE THREAD

**Issue by hpd71** [gridstack/gridstack.js#955]
Hi, 

Looking for a grid designer and this is as good as I have found, but have a few questions.

1 - Can we put text into each of the 'boxes' so we can have a label. In the demo there are numbers in the top of each box, but can we use text here and can it be centred in each box ?

2 - Can each box have a color ?

3 - Can we define a fixed height and width of the 'surface'. I have like a shelf that is of a set size, and I want to use this size so that I can define the working surface I am placing all the boxes..I need to be able to limit the height of the working surface so they can just stack boxes on boxes.. 

4 - Once I have finished the placement of the boxes on the working surface can I get the number, size and position of each box ? I need to save this 'map' to our database and be able to reload this 'map' as needed.

5 - The demo has like the fixed edge at the top, and you work downwards on the page placing boxes.. can this be flipped so that the fixed edit is the bottom edge and you work upwards.. 

6 - Is there a way to apply a size/scale. for example the working surface I have is 4m wide and 2.8meters height.. I need to set the working surface to be this size, so the user is forced into placing boxes within this limited size. 

 Thanks heaps....

**Comment by aamir1754** [comment]
Hi, You can add or create boxes with your custom html inside the boxes, with that html you can do whatever you want, add content, labels, styles and much more. like example below:

   var html = '<div><div class="grid-stack-item-content">';
    html += '<div>';
    html += '<label> some text </label>';
    html += '</div>';
    html += '</div></div>';

  var grid = $('.grid-stack').data('gridstack');
      grid.addWidget($(html), 0, 0, 6, 1, false);

**Comment by radiolips** [comment]
Hey @hpd71 ! You can certainly do everything you asked about :).
