### ISSUE TITLE
Gridstack - Maximize and minimize button on widget

### ISSUE THREAD

**Issue by RanjitSRaut** [gridstack/gridstack.js#956]
## Subject of the issue
Gridstack - Maximize and minimize button on widget

## Your environment
Latest Gridstack version 

## Steps to reproduce
https://jsfiddle.net/ranjitraut/481zvcep/5/

## Expected behaviour
Hello,
I have put two button on every widget like 'Maximize' and 'Minimize in' in widget header section. I want a functionality like when I click on minimize button, my widget will minimized and all other widget will rearrange to new position accordingly and when I click on maximize button that widget will take height same as original  widget height and all other widget set to new position accordingly. 
Please help me if anyone has solution. It's very urgent.
Thanks in advance.

## Actual behaviour
Tell us what happens instead

**Comment by radiolips** [comment]
You can use Javascript to make it so that maximize and minimize adjust the width or height of the widget. The grid will always automatically rearrange itself, as long as `float: true` isn't set in the grid options.
