### ISSUE TITLE
How to restrict to drop widget from one grid to another grid

### ISSUE THREAD

**Issue by mukeshmishra996** [gridstack/gridstack.js#957]
## Subject of the issue
I have multiple grid and I am trying to restrict user to drag and drop from one grid to another grid

**Comment by dirkheijn** [comment]
I have an identical requirement and was hoping to imlement this by utilizing the 'dropped' event which triggers when dropping a widget from one grid into another, however this is not available for consumption in the currently released build of Gridstack :(

**Comment by mukeshmishra996** [comment]
Thanks.. Can you please help me to implement same.

**Comment by dirkheijn** [comment]
I'll outline the solution I'm working on:

When constructing your page:
- Decorate grid elements with data attributes which contain an identifier unique to the grids between which items that belong to them are allowed to be moved

In the 'removed' event handler:
- Identify the item being moved (working under the assumption that only one item can be moved simultaneously) by selecting all items with the class '.ui-draggable-dragging'
- Identify to which grid the item is being moved (I'm simply checking if the item has any overlap with existing grids)
- Check for a match between the data attribute of the source grid and the target grid
- "Undo" the move if there is no match by reinserting the item on the source grid and reinitializing it as a grid stack item

**Comment by adumesny** [comment]
please look at latest code and https://gridstackjs.com/demo/nested.html which should allow what you want. closing
