### ISSUE TITLE
acceptWidgets option - Discriminate which items are accepted

### ISSUE THREAD

**Issue by dirkheijn** [gridstack/gridstack.js#958]
## Subject of the issue
I have multiple instances of GridStack running on one page. Groups of grids are divided into columns. It should be possible to move items between grids which are within the same column, but not between grids across columns.

Right now I've got a slipshod implementation using the 'removed' event which performs a check and reverts the move if the check fails (In part due to the fact that the 'dropped' event has not been part of a release so far).

Suggestion: Allow for configuration of the acceptWidgets option so that the component checks if the item came from the correct instance.

**Comment by adumesny** [comment]
I believe you can do that. looking at the doc

  /**
   * if true of jquery selector the grid will accept widgets dragged from other grids or from
   * outside (default: false) See [example](http://gridstack.github.io/gridstack.js/demo/two.html)
   */
  acceptWidgets ? : boolean | string | ((i: number, element: Element) => boolean | string);

so you should be able to declare a function and check yourself.
feel free to re-open if that wasn't what you asked for.
