### ISSUE TITLE
Create item with drag and drop

### ISSUE THREAD

**Issue by mathiastm** [gridstack/gridstack.js#959]
Hi everyone, 
I would like to know if that's possible to create an item with drag and drop fonctionnality?
For exemple: When I click on a toolbar with minified items and drag one on a gridstack instance, i would like to create a new item.

PS: I don't want to clone the minified item. I want to create a new one.

**Comment by aamir1754** [comment]
Why don't you use default event of addWidget? On drag stop, get your selected item's properties and create a new item with those properties through addWidget Event

**Comment by mathiastm** [comment]
because I want to see the new item on Drag

**Comment by adumesny** [comment]
you surely can do that - the help function of draggable lets you do anything you want - I do what you describe in some apps. https://gridstackjs.com/demo/advance.html might hint you at it... look for `helper:`
