### ISSUE TITLE
a widget has bootstrap modal pop up making my serialized data to null

### ISSUE THREAD

**Issue by kavishagoel** [gridstack/gridstack.js#960]
A widget has bootstrap modal pop up making my serialized data to null

In my gridstack container, i have one of the widgets' which opens up a bootstrap modal on click of the button . 
Before the opening of the pop up, i can trace and check the coordinates of the grids, but after pop up i couldn't trace the coordinates by using:
	var coordinates=  _.map($('.grid-stack > .grid-stack-item:visible:not(".grid-stack-placeholder")'), function (el) 
				{
					el = $(el);
					var node = el.data('_gridstack_node');
					if(node != undefined || node != null)
					{
			
						//alert(el.attr('data-widget-id'));
						//alert(el.find('.header').html());
						//alert(el.find('.content').html());
						//alert(typeof(el.attr('data-widget-active')));
						return {
							x: node.x,
							y: node.y,
							width: node.width,
							height: node.height,
							name: el.find('.header').html(),
							id: el.attr('data-widget-id'),
							content: el.find('.content').html(),
							active: el.attr('data-widget-active')
							
						};
					}
					
				}, this);
it returns [null,null,null,null]
## Your environment
* version of gridstack.js
* which browser and its version

## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://jsfiddle.net/dweiss/dqyvh6vr/) as a base.

## Expected behaviour
I should get the coordinates always

**Comment by radiolips** [comment]
@kavishagoel Could you provide a fiddle or codepen?
