### ISSUE TITLE
Get updated positions of all widgets in dragstop event

### ISSUE THREAD

**Issue by iyerananth** [gridstack/gridstack.js#961]
## Subject of the issue
How can we get updated positions of all widgets in dragstop event. Getting the updated positions in change event, but change event is firing for gridstack on adding widgets dynamically. I was using the change event to save grid layout. Hence looking at getting updated positions in dragstop event.

## Your environment
Using version 0.3.0
* which browser and its version
Chrome 71
## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://jsfiddle.net/dweiss/dqyvh6vr/) as a base.

## Expected behaviour
Require updated positions of all widgets

## Actual behaviour
Getting Updated postion of only widget that has been moved.

**Comment by aamir1754** [comment]
You can use this method to get updated positions

$('.grid-stack').on('dragstop', function (event, ui) {
      GetLayout();
});

function GetLayout() {

    var Positions = [];

    $('.grid-stack-item.ui-draggable').each(function () {
        var $this = $(this);

        Positions.push({
            x: $this.attr('data-gs-x'),
            y: $this.attr('data-gs-y'),
            w: $this.attr('data-gs-width'),
            h: $this.attr('data-gs-height'),
            content: $($this).html()
        });

    });

}

**Comment by iyerananth** [comment]
@aamir1754 thanks for the reply. Will try it.

**Comment by iyerananth** [comment]
@aamir1754 apologize for the delayed response. Tried your solution. It did not give the updated position of the widgets that were moved. I called the change event within the dragstop event and that gave the updated positions. I don't know if it is the right way but issue is resolved. Thank you @aamir1754.

**Comment by radiolips** [comment]
@iyerananth Using the `change` event is definitely the best way to identify coordinates after a widget has changed position.

**Comment by iyerananth** [comment]
Thank you @radiolips :+1:

**Comment by tupham9506** [comment]
@radiolips Sorry, can I use "dropped" instead of "change" event? I just want to event fire after I dropped.
This event seem not fire.
![image](https://user-images.githubusercontent.com/30684755/76183445-f9ddc380-61fa-11ea-87ae-5307665cc417.png)

**Comment by adumesny** [comment]
@tupham9506 please file a separate bug with a jsfiddle for use to take a look, rather than append to this close one. thanks

**Comment by tupham9506** [comment]
@adumesny  Sorry. I will do it.

**Comment by jawand** [comment]
I am late in the game, but this is a promising solution.

```
grid.on('dragstop', function (event, el) {
		var serializedFull = grid.save(true, true);
		var serializedData = serializedFull.children;
		console.log(serializedFull);
		console.log(serializedData);
	});
```

This will return all the grids co-ordinates and its content.

Also, I am using the same solution of `resizestop` event.

Hope it will help someone else.

cheers!!!😎

**Comment by adumesny** [comment]
again the change event is what you want...
