### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addWidget' of undefined when loading serialized data from getJSON

### ISSUE THREAD

**Issue by baradhili** [gridstack/gridstack.js#963]
## Subject of the issue
can't load serialized data via getJSON?

## Your environment
browser independent, gridstack 0.3.0 

## Steps to reproduce
https://jsfiddle.net/baradhili/mr1a79fe/1/

## Expected behaviour
Grid should load

## Actual behaviour
browser complains "Uncaught TypeError: Cannot read property 'addWidget' of undefined"

**Comment by radiolips** [comment]
Hi, @baradhili ! I see that you're binding `this`, but it still seems like context must be lost if you're getting that error. Prior to the jQuery function, does anything return with `this.grid`?.

**Comment by baradhili** [comment]
Sorry fogot I had this open.. Stackexchange solved it for me..
correct answer should have been something like

`this.loadGrid = function () {
  this.grid.removeAll();
  debugger;
  const URL = `//${window.location.hostname}/dashboard/getDashboard`;
  const context = this;
  $.getJSON(URL, function (items) {
    _.each(items, function (node) {
      context.grid.addWidget($('<div><div class="grid-stack-item-content" /></div>'),
        node.x, node.y, node.width, node.height, true, 4, 12, 1, 8, node.id);
    }.bind(this));
  });
  return false;
}.bind(this);`
