### ISSUE TITLE
Re-size widgets in increments of 2

### ISSUE THREAD

**Issue by burgoyne** [gridstack/gridstack.js#964]
I am creating a dashboard, and I do not want to be able to size my widgets in a 1x1 square. I would like 2x2 to be the smallest. Then, when increasing the size, I do not want the widget to snap to an odd number. For example, when making my 2x2 widget longer, I don't want to be able to stop 3x2, I want 4x2 to be my next option. Same if I were to resize the height.

```
<div class="grid-stack-item" data-gs-x="0" data-gs-y="0" data-gs-width="2" data-gs-height="2">
</div>
```

That div shows my widget in the top left corner, in a 2x2 square. 

Can anyone point me in the right direction to only allow increments of even numbers?, and not allow the widget to be re-sized smaller than 2x2? 

Thank you!

**Comment by burgoyne** [comment]
I should have read the docs better, but I solved the minimum widget size by using the `min-height` and `min-width` option. 

Increasing size by increments of 2 is still stumping me though.

**Comment by sociablesasha** [comment]
It can be handled by a function in the built-in gridstack.

**Comment by radiolips** [comment]
@burgoyne glad you found the `min-` options. I can only think of a couple of ways to change the increments. Firstly, you could change the number of columns–if you have six columns, the change will be twice as much as if there were twelve. The other way would be to intercept any change and essentially revert the change if the width/height are odd.
