### ISSUE TITLE
 When will the v1.0 release?

### ISSUE THREAD

**Issue by myzhibie** [gridstack/gridstack.js#965]
when will v1.0 version realease and some breaking changes?

**Comment by ADobrianskiy** [comment]
Any news?

**Comment by radiolips** [comment]
Hey guys! We're working hard to push out a 0.5.0 release early this week (hopefully April 1–I promise it is not an April fool's joke :)). 1.0.0 will almost definitely be based off of 0.5.0, and I'll push hard to get that done ASAP. I'll provide an update as soon as I've got a better estimate of when things will be ready.

**Comment by Altraya** [comment]
Hello, any news about this new release ? I am currently using the develop version with some own merged things, but for my soul, it would be better to use a real release ! Nice job between, good luck for all.

**Comment by adumesny** [comment]
radiolips is back in action and I should soon be able to merge/publish as well, so we're hoping for that 0.5.0 push any day now. Please submit merge request for any work you find other will benefit as we have 2 people now.

**Comment by radiolips** [comment]
Closing this up! As @adumesny  alluded to, we're pushing out pre-1 versions. The latest is v0.5.1, and I encourage you to use it! We're working hard to pump out more versions.

We'll provide ample notice before pushing out a breaking-change version.
