### ISSUE TITLE
Drop Position Placeholder Displaying Incorrectly

### ISSUE THREAD

**Issue by stap123** [gridstack/gridstack.js#967]
When dragging an item it seems the further to the right you go the further out the placeholder becomes and therefore the harder to use correctly it becomes. See the codepen below:

[https://codepen.io/stap123/pen/aXNRoL](https://codepen.io/stap123/pen/aXNRoL)

Anyone got any ideas?

#566 sounds like a similar problem.

**Comment by radiolips** [comment]
@stap123 You can follow the directions here to create grids smaller than 12 columns https://github.com/gridstack/gridstack.js#extra-css

I've verified, using your codepen, that if you include the gridstack-extra css file and add the `grid-stack-6` class to the `grid-stack` DOM element, your grid works perfectly.
