### ISSUE TITLE
How grid-stack-item will take height from its inner content and create a collapsible panel

### ISSUE THREAD

**Issue by mousumipaul** [gridstack/gridstack.js#968]
I want to create a dashboard with multiple collapsible panel. But grid-stack-item is asking height. Therefore it is not expanding based on the content inside of grid-stack-item-content. Inside of item content I used the following code to create a collapsible panel. 
```
<div>
                        <div class="panel_header">Header 
                            <span class="btn btn-box-tool" onclick="hidenseek('1')">-</span>
                            <span class="btn btn-box-tool" data-widget="remove">+</span>
                        </div>
                        <div class="panel_content" id="1"><br/><br/><br/><br/><br/><br/>Panel Content 1</div>
                    </div>
```

Here on the onclick event I want to toggle the panel. But I am only able to hide and show the panel_content div but grid-stack-item-content height remain same. Here How can I implement such collapsible panel using gridstack because it is not taking height from inner content. Following is the entire code:
`<!DOCTYPE html>
<html lang="en">
<head>
    

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Responsive grid demo</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="../dist/gridstack.css"/>
    <link rel="stylesheet" href="../dist/gridstack-extra.css"/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.11.0/jquery-ui.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/3.5.0/lodash.min.js"></script>
    <script src="../dist/gridstack.js"></script>
    <script src="../dist/gridstack.jQueryUI.js"></script>

    <style>
        .grid-stack-item-content {
            color: #2c3e50;
            text-align: center;
            background-color: #18bc9c;
        }
        .panel_header{
            height:50px;
            background:#FF0000;
            color:#fff;
        }
        .panel_content{
            background:#eaeaea;
        }
    </style>
</head>
<body>
    <div class="device-xs visible-xs"></div>
    <div class="device-sm visible-sm"></div>
    <div class="device-md visible-md"></div>
    <div class="device-lg visible-lg"></div>
    <div class="device-xl visible-xl"></div>
    <div class="container-fluid">
        <div class="grid-stack">
            <div class="grid-stack-item" data-gs-x="0" data-gs-y="0" data-gs-width="4" data-gs-height="3">
                <div class="grid-stack-item-content">
                    <div>
                        <div class="panel_header">Header 
                            <span class="btn btn-box-tool" onclick="hidenseek('1')">-</span>
                            <span class="btn btn-box-tool" data-widget="remove">+</span>
                        </div>
                        <div class="panel_content" id="1"><br/><br/><br/><br/><br/><br/>Panel Content 1</div>
                    </div>
                </div>
            </div>

            <div class="grid-stack-item" data-gs-x="0" data-gs-y="0" data-gs-width="4" data-gs-height="3">
                <div class="grid-stack-item-content">
                    <div>
                        <div class="panel_header">Header 
                            <span class="btn btn-box-tool" onclick="hidenseek('1')">-</span>
                            <span class="btn btn-box-tool" data-widget="remove">+</span>
                        </div>
                        <div class="panel_content" id="1"><br/><br/><br/><br/><br/><br/>Panel Content 1</div>
                    </div>
                </div>
            </div>

        </div>
    </div>

    <script type="text/javascript">
        function hidenseek(id){
            $('#'+id).toggle();
        }
        $(function () {
            // thanks to http://stackoverflow.com/a/22885503
            var waitForFinalEvent=function(){var b={};return function(c,d,a){a||(a="I am a banana!");b[a]&&clearTimeout(b[a]);b[a]=setTimeout(c,d)}}();
            var fullDateString = new Date();
            function isBreakpoint(alias) {
                return $('.device-' + alias).is(':visible');
            }
            var options = {
                float: true
            };
            $('.grid-stack').gridstack(options);
            function resizeGrid() {
                var grid = $('.grid-stack').data('gridstack');
                if (isBreakpoint('xs')) {
                    $('#grid-size').text('One column mode');
                } else if (isBreakpoint('sm')) {
                    grid.setGridWidth(3);
                    $('#grid-size').text(3);
                } else if (isBreakpoint('md')) {
                    grid.setGridWidth(6);
                    $('#grid-size').text(6);
                } else if (isBreakpoint('lg')) {
                    grid.setGridWidth(12);
                    $('#grid-size').text(12);
                }
            };
            $(window).resize(function () {
                waitForFinalEvent(function() {
                    resizeGrid();
                }, 300, fullDateString.getTime());
            });
        });
    </script>
</body>
</html>
`

**Comment by kashifasif** [comment]
The best way of doing is to first minimize widget height like say 3 but store original height in data attributes on same widget to restore that widget in original height on toggle.

**Comment by radiolips** [comment]
There's some example code I wrote somewhere in the issue tracker that shows how you can resize a widget to the size of its content, which I think is what you're looking for. Try searching through the closed issues.
