### ISSUE TITLE
How to use bootstrap grid responsiveness with grid-stack-item?

### ISSUE THREAD

**Issue by Artemy-Matvienko** [gridstack/gridstack.js#969]
## Subject of the issue
If you change the browser window size, the grid items will only start stacking on top of each other when reaching the "col-md" equivalent of viewport width. I'd like to customize when the grid items start stacking. For example, some items I'd like to stack when reaching the "col-lg" viewport width.

## Your environment
* version of gridstack.js - 0.4.0
* which browser and its version - Google chrome 71.0.3578.98

## Steps to reproduce
When you load the demo on a maximized 1920x1080 screen, Table 1 and Table 2 grid items are shown side by side. When you decrease the rendered demo viewport a bit, the two table grid items stack on top of each other. 
https://jsfiddle.net/k6uL8pfq/

## Expected behaviour
I would like to customize the behavior in a way that the table grid items stack sooner, on higher view port widths.

## Actual behaviour
The table grid items stack only when the viewport reached bootstrap's "col-md" equivalent width.

**Comment by adumesny** [comment]
please look at latest code and https://gridstackjs.com/demo/responsive.html 
that should allow you more control. closing.
