### ISSUE TITLE
How to save Widgets in grid layout on Server side?

### ISSUE THREAD

**Issue by suffyanaziz** [gridstack/gridstack.js#970]
Hi, I want to save the user specific layout of widgets on server side. So far, the widgets layout is being saved in local storage but I am having difficulty in figuring out how we can do this also on server side.

Thanks

**Comment by kashifasif** [comment]
you have to calculate gridstack widgets coordinates and width, height of every widget. gridstack provide a method where you can get all widgets setting/styling like

` var serializedData = _.map($('.grid-stack > .grid-stack-item:visible'), function (el) {
                el = $(el);
                var node = el.data('_gridstack_node');
                return {
                    x: node.x,
                    y: node.y,
                    width: node.width,
                    height: node.height,
                    el: $(el)
                };
            });
           // var items = GridStackUI.Utils.sort(this.serializedData);
            return this.serializedData;
        }.bind(this)`
this will return in json. then store it into datatabse in json form or in columns.

**Comment by radiolips** [comment]
@suffyanaziz I think there may be a few references throughout this repo, but you'll want to store the information however you'd like into whatever database you're using. If you're using MySQL, you could store the x, y, width, height, and DOM data individually into rows. For NoSQL, you probably could store it in a simpler fashion. I'd imagine that you should be able to store the widgets in a database the same way you're storing it using local storage.
