### ISSUE TITLE
Maximum call stack size exceeded error, when loading element positions from database

### ISSUE THREAD

**Issue by singhrajbeer** [gridstack/gridstack.js#972]
![jserror](https://user-images.githubusercontent.com/37385324/52469867-97903a80-2b84-11e9-8a0b-02aa89e89169.png)

Before posting my question here, i have seen all posts regarding this issue as others also have same issue but I couldnt get my problem fixed.

I am using gridstack for a dynamic dashboard where user can drag & drop controls, can save layout in the database. 

I am setting positions from database like this :
```
function loadlayout() {
                  var parsedData = JSON.parse(str);   (str is the json data i get from database)
                  var length = parsedData.length;
                 
                  for (var i = 0; i < length; i++) {
                      $('.grid-stack-item[data-gs-id=' + parsedData[i].id + ']').attr({
                          'data-gs-x': parsedData[i].x,
                          'data-gs-y': parsedData[i].y,
                          'data-gs-width': parsedData[i].w,
                          'data-gs-height': parsedData[i].h,
                      });
                      //show/hide elements
                      if (parsedData[i].v == false) {
                          $('.grid-stack-item[id=' + parsedData[i].cusId + ']').hide();
                      }
  }
```
but for two controls I am setting position as :

```
function loadDefaultChartLayout() {
              $('.grid-stack-item[data-gs-id=systemGraph]').show();
              $('.grid-stack-item[data-gs-id=systemGraph]').attr({
                  'data-gs-x': 0,
                  'data-gs-y': 4,
                  'data-gs-width': 6,
                  'data-gs-max-width': 12,
                  'data-gs-height': 5,
                  'data-gs-min-height': 5,
                  'data-gs-max-height': 5
              });
              $('.grid-stack-item[data-gs-id=usageGraph]').show();
              $('.grid-stack-item[data-gs-id=usageGraph]').attr({
                  'data-gs-x': 6,
                  'data-gs-y': 4,
                  'data-gs-width': 6,
                  'data-gs-max-width': 12,
                  'data-gs-height': 5,
                  'data-gs-min-height': 5,
                  'data-gs-max-height': 5
              });
}
```
i believe the error is caused by any of these functions. I would be very thankful if somebody can help with this issue.

html code where i am trying to use these settings 
![htmlcode](https://user-images.githubusercontent.com/37385324/52470281-9dd2e680-2b85-11e9-856a-e3ed4463455b.png)

But setting positions manually would fix this issue like this = 
`<div class="grid-stack-item" data-gs-x="0" data-gs-y="4" data-gs-width="6" data-gs-height="5" data-gs-id="systemGraph" id="systemGraph">`

Thanks

**Comment by armujahid** [comment]
I am also getting same error with different call stack. 
Demo: https://jsfiddle.net/armujahid/v6d9t8Lg/
![image](https://user-images.githubusercontent.com/3725386/52691147-b8d89880-2f81-11e9-94c2-2fb50ec6bd95.png)

**Comment by radiolips** [comment]
Could you provide a codepen or jsfiddle for this? I'd be happy to take a look.

**Comment by armujahid** [comment]
@radiolips you can jsfiddle provided in my previous comment.

**Comment by radiolips** [comment]
Hey again–it doesn't look like you're setting a width or height on any of the widgets, and it also looks like you're using CSS to set the width, which will override the values in the library and cause issues.

**Comment by singhrajbeer** [comment]
> Could you provide a codepen or jsfiddle for this? I'd be happy to take a look.

Thank you, in my case I was saving those positions in a wrong way. Now its working alright.

**Comment by singhrajbeer** [comment]
in my case i don't give fix width, height and position in HTML : 
<div class="grid-stack-item" data-gs-locked="true" data-gs-id="moni" id="moni">

instead I am trying to set those variables through database like this : 

var str = '[{"x":"0","y":"0","w":"2","h":"2","id":"moni","cusId":"moni","v":false},{"x":"2","y":"0","w":"2","h":"2","id":"error","cusId":"error","v":true}]'

            ```
var parsedData = JSON.parse(str);
            var length = parsedData.length;
           
         for (var i = 0; i < length; i++) {
                $('.grid-stack-item[data-gs-id=' + parsedData[i].id + ']').attr({
                    'data-gs-x': parsedData[i].x,
                    'data-gs-y': parsedData[i].y,
                    'data-gs-width': parsedData[i].w,
                    'data-gs-height': parsedData[i].h
                });
          }
```
This generates Uncaught RangeError : Maximum call stack size exceeded.
in case of fix position and size, it works alright.

**Comment by radiolips** [comment]
I'm closing this issue. It looks to be very specific to your code, not to the library. If you do find the problem to be with the library itself, please reopen.
