### ISSUE TITLE
How to save Dashboard name and Serialized data in a database as well?

### ISSUE THREAD

**Issue by suffyanaziz** [gridstack/gridstack.js#973]
I am using grid stack in ASP.NET Core razor page to save widgets in locals torage. The same thing I want to do for on server side as well. For that purpose I want to store the dashboard name as key and serializedData as value in database for each user. How can this be done? Thanks

Following is the code :

     this.saveGrid = function () {
                    this.serializedData = _.map($('.grid-stack > .grid-stack-item:visible'), function (el) {
                        el = $(el);
                        var node = el.data('_gridstack_node');  
                         return {
                            x: node.x,
                            y: node.y,
                            width: node.width,
                            height: node.height,
                            minwidth: node.minWidth,
                            maxwidth: node.maxWidth,
                            minheight: node.minHeight,
                            maxheight: node.maxHeight,
                            id: node.id,
                            view: node.view,
                     
                        };
                    }, this);

                    localStorage.setItem("@DashboardName", JSON.stringify(this.serializedData));
                  

                    return true;

                }.bind(this);

                this.clearGrid = function () {
                    this.grid.removeAll();
                    return true;

                }.bind(this);

            

                $('#save-widgets').click(this.saveGrid);

**Comment by stevenliebregt** [comment]
You could make a POST AJAX request before/after you set the localStorage item.

**Comment by radiolips** [comment]
As @stevenliebregt said, just send some data to the server when you're also setting local storage.

**Comment by weedkiller** [comment]
@suffyanaziz if you post your controller and razor page I can show you how to save it
