### ISSUE TITLE
commonjs export issue is not fixed completely

### ISSUE THREAD

**Issue by andreo-k** [gridstack/gridstack.js#975]
## Subject of the issue
There are fixes in 'development' branch which try to fix commonjs export issue (you assign scope.GridStackUI there). However there is still issue

currently:
try { GridStackUI = require('gridstack'); } catch (e) {}

should be added (in bold)
try { GridStackUI = require('gridstack')**.GridStackUI**; } catch (e) {}

Pls see the fix in my fork of the project
https://github.com/andreo-k/gridstack.js
branch v0.4.0-fix-exports

## Your environment
* 0.4.0 and latest 'development' branch
* latest chrome and firefox

## Steps to reproduce
1. Build application with webpack with disabled AMD ({ parser: { amd: false } })
2. Try to run application

## Expected behaviour
Application runs fine

## Actual behaviour
Application fails with 'can not get registerPlugin of undefined'

**Comment by radiolips** [comment]
Hey @andreo-k ! Could you put in a PR for this update?
