### ISSUE TITLE
When you scroll down while dragging a widget, you can keep scrolling endlessly

### ISSUE THREAD

**Issue by bfheythem** [gridstack/gridstack.js#976]
## Subject of the issue

When I drag the widget to the bottom of the page and start scrolling down without releasing the widget.The page keeps getting extended for as long as you scroll.

## Your environment
* version of gridstack.js : 0.2.6
* which browser and its version
Google Chrome 
Version 72.0.3626.109 (64 bits)

## Steps to reproduce
Simply pick any widget and drag it to the bottom of the page and start scrolling down without releasing the widget.The page keeps getting extended for as long as you scroll.

## Expected behaviour
 It should not be able to scroll past the footer , the scrolling should be limited to the container area only
## Actual behaviour
I was able to reporoduce it on the demo int the official website
https://imgur.com/a/0HIfmsw

**Comment by jonathangriguol** [comment]
Hello,
you should use

draggable: {
          scroll: false,  // or delete this property because false is the default value
        }

More info: https://github.com/gridstack/gridstack.js/tree/develop/doc#options
