### ISSUE TITLE
How to disable the responsiveness of gridstack

### ISSUE THREAD

**Issue by candrewtemenoscom** [gridstack/gridstack.js#977]
How to disable responsiveness of the Gridstack when resizing the container

Currently, when the container of the gridstack is resizing, the gridstack items will resize accordingly as well. I would like to disable this resizing of the gridstack item when the container change size completely in order to maintain the size each div items but I would still like to be able to drag and resize each item individually and manually. I tried the staticGrid option but not working at all. May I know what is the best  way to disable the responsiveness of the grid while maintaining the individual resize? Thanks so much.

* version = v0.3.0
* browser IE 11 and Chrome 72

## Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo, you can use [this template](https://jsfiddle.net/dweiss/dqyvh6vr/) as a base.

## Expected behaviour
When the browser resize, do not resize the grid item. I can still individually resize each item

## Actual behaviour
When the browser resize, each item resize itself.

**Comment by radiolips** [comment]
gridstack automatically changes width based on the size of its container. The widgets are all based off of a 12-column grid by default (this can be changed), and expanding/contracting the container size will change the overall width, but not the number of columns.
