### ISSUE TITLE
Removing Gridstack Tile

### ISSUE THREAD

**Issue by burgoyne** [gridstack/gridstack.js#987]
So I am attempting to remove a tile, but can't figure out how to properly do it. I have a button, and when pressed, my grid area becomes editable (moving, resizing, and deleting tiles). But for some reason, the X button (to remove a tile) only appears on the first tile in the grid. Also, if I remove that one tile, then close the editing process, an X appears on the next tile when not in editing mode. 

I have attached a fiddle to make a little more sense of this. Ignore the poor formatting in the fiddle. It's not like that on my actual project... 
https://jsfiddle.net/khoq8f1b/

edit
Not sure why, but in the fiddle the tile with the X does not get removed. It actually works in my project, but like I said, only that one tile will display the X. 
end edit

Can anyone point me in the right direction to solve this?

**Comment by radiolips** [comment]
IDs should only be used once per page. Instead of using the id "closeTile" use the class "close" (you already have it in your example). I tested it using your example–the x shows up for each widget if you do that :)

**Comment by burgoyne** [comment]
That was it. Thank you!
