### ISSUE TITLE
Dynamically  created widget containing a button, with click event is not working Need Help

### ISSUE THREAD

**Issue by vishal1025** [gridstack/gridstack.js#989]
Button events are not working for the newly added gridstack item
Describe your issue here.
I am using gridstack.js in a angular project
When I am adding a button in the widget its click event is not working.

Here, the code,

  AddingWidget(fieldType: any) {

    var fieldTypeString: string = '';

    switch (fieldType) {
      case 'Text': fieldTypeString =
        `<div class="grid-stack-item">
        <div class="grid-stack-item-content" style="background-color: #18bc9c;">
          <button style="float: right;" data-bind="click: openProperties()">test
          </button>
          <div class="ms-TextField" style="margin-left:15px;">
            <label class="ms-Label">Name</label>
            <input class="ms-TextField-field" style="width:50%;" type="text" value="" placeholder="Enter Value">
          </div>           
        </div>
      </div>`
        break;
}

  openProperties() {
    let redirect = '/properties';
    this._router.navigateByUrl('/properties');
  }

Secondly, if the buttons which I am using if I replace them with angular material icons then also, buttons are not not working.

Can anybody help, what I am doing wrong??

**Comment by radiolips** [comment]
@adumesny is our resident Angular master. Got any thoughts?

**Comment by adumesny** [comment]
@vishal1025 you can't add html and expect angular to bind to those properties after the fact (dynamically inserting). Nothing to do with gridstack.  I believe (never tried) you need to tell angular to parse that new HTML for things to bind.. 
closing for now. re-open if it is a gridstack issue per say.
