### ISSUE TITLE
No dist directory

### ISSUE THREAD

**Issue by SergioMSCosta** [gridstack/gridstack.js#990]
There's no dist directory in the project which is kinda annoying for some users.

**Comment by adumesny** [comment]
/dist files always merged conflicted which was a pain as a developer/contributor, and likely reason people didn't want to redo their pull request over time. 
Pretty easy to generate them yourself, or just use the source .js file - if you are not using the npm package (which I suspect most users do anyway).

Please close.

**Comment by ramonwanghao** [comment]
It could be acceptable that there is no dist folder in the source tree. But when you do formal release, It is better to have the dist folder in the released package.

**Comment by adumesny** [comment]
I kinda want to force people to use the npm package because that is a way to track usage... but I hear you about zip packages.
