### ISSUE TITLE
Widgets are not moving properly

### ISSUE THREAD

**Issue by aamir1754** [gridstack/gridstack.js#991]
Hi,
I've created dynamic form with gridstack, but dragging is not working properly as shown in the video: https://www.screencast.com/t/Yzzamca3VN

**Comment by radiolips** [comment]
Hey @aamir1754 ! The video seems to have been removed. Could you provide the information again, please?

**Comment by radiolips** [comment]
Closing this because there isn't information to actually show a bug in the library (vs implementation). Please reopen with that information if there's a bug in the library.
