### ISSUE TITLE
Angular 7: ERROR TypeError: $(...).gridstack is not a function

### ISSUE THREAD

**Issue by foadshariat7** [gridstack/gridstack.js#993]
## Subject of the issue
I'm trying to use this great feature in my Application, but I get "ERROR TypeError: $(...).gridstack is not a function", I tried all the solutions in other reported issues but none worked for me.

## Your environment
gridstack.js 0.4.0
Chrome 73

## Steps to reproduce
This is the code I added to scripts section in angular.json:
"scripts": [
                            "./node_modules/jquery/dist/jquery.min.js",
                            "./node_modules/jquery-ui-dist/jquery-ui.min.js",
                            "./node_modules/lodash/lodash.min.js",
                            "./node_modules/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js",
                            "./node_modules/gridstack/dist/gridstack.js",
                            "./node_modules/gridstack/dist/gridstack.jQueryUI.min.js"
                        ]

`import { Component, ViewChild, OnInit } from '@angular/core';

import 'gridstack';
declare var $: any; // JQuery

@Component({
  selector: 'home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
  ngOnInit() {
    const options = {
      cell_height: 80,
      vertical_margin: 10
    };
    $('.grid-stack').gridstack(options);
  }
}
`
What am I missing?

**Comment by johnbatters** [comment]
> ## Subject of the issue
> I'm trying to use this great feature in my Application, but I get "ERROR TypeError: $(...).gridstack is not a function", I tried all the solutions in other reported issues but none worked for me.
> 
> ## Your environment
> gridstack.js 0.4.0
> Chrome 73
> 
> ## Steps to reproduce
> This is the code I added to scripts section in angular.json:
> "scripts": [
> "./node_modules/jquery/dist/jquery.min.js",
> "./node_modules/jquery-ui-dist/jquery-ui.min.js",
> "./node_modules/lodash/lodash.min.js",
> "./node_modules/jquery-ui-touch-punch/jquery.ui.touch-punch.min.js",
> "./node_modules/gridstack/dist/gridstack.js",
> "./node_modules/gridstack/dist/gridstack.jQueryUI.min.js"
> ]
> 
> `import { Component, ViewChild, OnInit } from '@angular/core';
> 
> import 'gridstack';
> declare var $: any; // JQuery
> 
> @component({
> selector: 'home',
> templateUrl: './home.component.html',
> styleUrls: ['./home.component.css']
> })
> export class HomeComponent implements OnInit {
> ngOnInit() {
> const options = {
> cell_height: 80,
> vertical_margin: 10
> };
> $('.grid-stack').gridstack(options);
> }
> }
> `
> What am I missing?

Hi Foad, just wondering if you found a solution to this, I've run into the same problem

**Comment by adumesny** [comment]
I'm using Angular 7 and Gridstack without issues (I created an angular wrapper around gridstack). these might help you:
1) in `vendor.ts` I have

import '@flyingdragon/gridstack/dist/gridstack-extra.min.css';
import '@flyingdragon/gridstack/dist/gridstack.min.css';

// tslint:disable-next-line no-unused-variable
import * as $ from 'jquery';

// import '@flyingdragon/gridstack/dist/gridstack.all.js'; // need gridstack.min.js + gridstack.jQueryUI.min.js now for D&D/resize
import '@flyingdragon/gridstack/dist/gridstack';

import '@flyingdragon/gridstack/dist/gridstack.jQueryUI.min.js';

(ignore the flyingdragon part - that's just my own npm version of gridstack which matches the upcoming 0.5.0 release)

2) then in my `grid.component.ts`, I have:

import '@flyingdragon/gridstack';
class GridComponent {
  /** The gridstack object. */
  private grid: GridStack;

  /** A jQuery selection containing the gridstack DOM element. */
  private $grid: JQuery;

public ngAfterViewInit() {
this.$grid = $(this.gridElement.nativeElement);
this.$grid.gridstack(...options...);
this.grid = this.$grid.data('gridstack');
}
}
``

**Comment by radiolips** [comment]
@adumesny Pinging you for this one, too.

**Comment by adumesny** [comment]
closing due to lack of response. I gave the steps that work for me, re-open if still have an issue. thanks.
