### ISSUE TITLE
quick move the item between different grid-stack will assert error

### ISSUE THREAD

**Issue by liuyisnake** [gridstack/gridstack.js#998]
## Subject of the issue
quick move the item between grid-stack will assert exception

## Your environment
* version of gridstack.js
1.0.0(develop) and 0.3.0(master)
* which browser and its version
chrome

## Steps to reproduce
use the demo of gridstack two.html could duplicate the issue
1.create tow grid-stack(grid-stack1 and grid-stack2) and several items
2.move one  item from grid-stack1 to grid-stack2
3.drag the item back to grid-stack1 and hover other draggable itmes, or quick move the item between two grid-stack. 

## Expected behaviour
work as normal

## Actual behaviour
it will assert error 

gridstack.js:660 Uncaught TypeError: Cannot read property 'attr' of null
    at gridstack.js:660
    at Mt (lodash.min.js:9)
    at Function.Te (lodash.min.js:38)
    at GridStackEngine.onchange (gridstack.js:653)
    at GridStackEngine._notify (gridstack.js:321)
    at GridStackEngine.addNode (gridstack.js:370)
    at HTMLDivElement.dragOrResize (gridstack.js:1088)
    at $.<computed>.<computed>._trigger (jquery-ui.js:799)
    at $.<computed>.<computed>._trigger (jquery-ui.js:6378)
    at $.<computed>.<computed>._trigger (jquery-ui.js:407)

i try to trace the dropout and dropover event of jquery-ui
it seems as below if drag the item from grid-stack2 back to grid-stack1 will trigger the dropout event but doesn't trigger the dropover event of grid-stack1 (and onDrag also will be triggered)

**Comment by abrorabdukadirov** [comment]
hi liuyisnake did you solve this problem? I have the same problem

**Comment by radiolips** [comment]
Thanks @liuyisnake . I'll look into this.

**Comment by radiolips** [comment]
@liuyisnake @abrorabdukadirov I believe this is resolved on the latest `develop` branch. Please give it a try. Reopen the ticket if you still have an issue.
