### ISSUE TITLE
wrong counting of minHeight for resizable widget

### ISSUE THREAD

**Issue by miroslav-peterka** [gridstack/gridstack.js#999]
At line

https://github.com/gridstack/gridstack.js/blob/17fcce8dc2808a941e683c9123e40664440bc819/src/gridstack.js#L1281

is some mistake, IMHO because you forgot to take in equation vertical margin.

example:
cellHeight = 80px and vertical margin = 20px
item height is 3, minHeight is 2

minHeight in pixels should be 80 x 2 + 20 = 180px. but at pointed line is counted number 188px

80*3 + 2*20 = 280
280 / 3 = 93.3 ~= 94
94 * 2 = 188px

**Comment by radiolips** [comment]
@miroslav-peterka that may certainly be correct. Could you provide an example that I could take a look at?

**Comment by adumesny** [comment]
@miroslav-peterka you are absolutely right - here is the before when you can't drag smaller and after my fix (coming up) to take margin into account.

before
![two_grids_before](https://user-images.githubusercontent.com/3496166/68261810-19b76d80-fff6-11e9-9a01-dd2783757226.png)

after
![two_grids_after](https://user-images.githubusercontent.com/3496166/68261812-1c19c780-fff6-11e9-8a5b-b498bf601b7a.png)

**Comment by adumesny** [comment]
fixed in upcoming 0.5.2 release
